In [1]:
#use random forest

rs2909 = 2909

# 5 Modeling<a id='5_Modeling'></a>

## 5.3 Imports<a id='5.3_Imports'></a>

In [2]:
import pandas as pd
import numpy as np
import os
import pickle
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import __version__ as sklearn_version
from sklearn.model_selection import cross_validate


import time
from sklearn.decomposition import PCA
from sklearn.preprocessing import scale
from sklearn.model_selection import train_test_split, cross_validate, GridSearchCV, learning_curve
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.dummy import DummyRegressor
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.feature_selection import SelectKBest, f_regression
import datetime

pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

## 5.4 Functions

In [3]:
#return the first 5 and last 5 rows of this dataframe
def p(df_):
    if df_.shape[0] > 6:
        print(df_.shape)
        return pd.concat([df_.head(), df_.tail()])
    else:
        return df_

def rcp(file_, pd_=None, ic_=None):
    if (pd_ == None) and (ic_ == None):
        return pd.read_csv(os.path.join('..', 'processed_data', file_))
    elif (pd_ != None) and (ic_ == None):
        return pd.read_csv(os.path.join('..', 'processed_data', file_), parse_dates=pd_)
    elif (pd_ != None) and (ic_ != None):
        return pd.read_csv(os.path.join('..', 'processed_data', file_), parse_dates=pd_, index_col = ic_)
    else:
        return pd.read_csv(os.path.join('..', 'processed_data', file_), index_col = ic_)
    
def rcr(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'raw_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'raw_data', file_), parse_dates=pd_)
    
#sort dataframe by column
def s(df_, column_):
    return df_.sort_values(column_)

#reset index and sort dataframe by column
def sr(df_, column_, ascending_=True):
    df_ = df_.sort_values(column_, ascending=ascending_)
    return df_.reset_index(drop=True)

#print length of list
def pl(list_):
    print(len(list_))
    return list_

#print length of dictionary
def pdc(dict_):
    print(len(dict_))
    return dict_

## 5.5 Load Data<a id='5.5_Load_Data'></a>

In [4]:
df_train = rcp('150_train_split.csv', None, 0)
p(df_train)

(7186, 88)

,E_OFF_RATING_cma_diff,OFF_RATING_cma_diff,E_DEF_RATING_cma_diff,DEF_RATING_cma_diff,E_NET_RATING_cma_diff,NET_RATING_cma_diff,AST_PCT_cma_diff,AST_TOV_cma_diff,AST_RATIO_cma_diff,OREB_PCT_cma_diff,DREB_PCT_cma_diff,REB_PCT_cma_diff,E_TM_TOV_PCT_cma_diff,TM_TOV_PCT_cma_diff,EFG_PCT_cma_diff,TS_PCT_cma_diff,USG_PCT_cma_diff,E_USG_PCT_cma_diff,E_PACE_cma_diff,PACE_cma_diff,PACE_PER40_cma_diff,POSS_cma_diff,PIE_cma_diff,duration_minutes_cma_diff,w_pct_cma_diff,min_cma_diff,fgm_cma_diff,fga_cma_diff,fg_pct_cma_diff,fg3m_cma_diff,fg3a_cma_diff,fg3_pct_cma_diff,ftm_cma_diff,fta_cma_diff,ft_pct_cma_diff,oreb_cma_diff,dreb_cma_diff,reb_cma_diff,ast_cma_diff,stl_cma_diff,blk_cma_diff,tov_cma_diff,pf_cma_diff,pts_cma_diff,spread_cma_diff,away_home_cma_diff,E_OFF_RATING_sm_cma_diff,OFF_RATING_sm_cma_diff,E_DEF_RATING_sm_cma_diff,DEF_RATING_sm_cma_diff,E_NET_RATING_sm_cma_diff,NET_RATING_sm_cma_diff,AST_PCT_sm_cma_diff,AST_TOV_sm_cma_diff,AST_RATIO_sm_cma_diff,OREB_PCT_sm_cma_diff,DREB_PCT_sm_cma_diff,REB_PCT_sm_cma_diff,E_TM_TOV_PCT_sm_cma_diff,TM_TOV_PCT_sm_cma_diff,EFG_PCT_sm_cma_diff,TS_PCT_sm_cma_diff,E_USG_PCT_sm_cma_diff,POSS_sm_cma_diff,PIE_sm_cma_diff,w_pct_sm_cma_diff,fgm_sm_cma_diff,fga_sm_cma_diff,fg_pct_sm_cma_diff,fg3m_sm_cma_diff,fg3a_sm_cma_diff,fg3_pct_sm_cma_diff,ftm_sm_cma_diff,fta_sm_cma_diff,ft_pct_sm_cma_diff,oreb_sm_cma_diff,dreb_sm_cma_diff,reb_sm_cma_diff,ast_sm_cma_diff,stl_sm_cma_diff,blk_sm_cma_diff,tov_sm_cma_diff,pf_sm_cma_diff,pts_sm_cma_diff,spread_sm_cma_diff,away_home_sm_cma_diff,away_home_a,spread_a
3134,-0.018902,-0.016231,1.321667,1.343521,-1.228430,-1.303603,-1.318706,-1.481543,-1.903444,0.921242,-2.507811,-0.529573,0.446845,0.430833,-0.575159,0.121855,-0.00658,-0.050716,0.174116,0.184420,0.184667,0.087111,-0.946293,-0.146579,-0.692156,-0.146579,-1.441489,-0.954681,-0.761156,0.058212,-0.155516,0.712864,2.741520,2.536967,1.145528,-0.129427,-0.499197,-0.454521,-1.849687,0.374410,0.695530,0.314062,1.079520,0.019169,1.242246,-1.671873,-0.972992,-0.574376,0.972992,0.574376,-0.982755,-0.574453,0.482854,-0.689375,-0.331362,0.453289,0.228158,0.772176,0.513350,0.650436,-0.657641,-0.640307,-0.502838,-1.467600,-0.218142,-0.622246,-1.140080,-0.426922,-0.790581,-0.024232,-0.034710,-0.003680,0.702370,1.160200,-1.334506,0.042893,0.400880,0.340858,-0.223699,0.020952,0.037745,-0.000575,-2.090760,-0.652068,0.652068,1.632487,-0.999416,0.819762
8383,-0.099050,-0.203595,-0.808132,-0.713716,0.644865,0.483580,1.728190,1.736950,1.631711,-1.010155,0.087533,-0.470397,-0.467579,-0.507828,0.560740,0.066701,-0.00658,-0.015186,0.085137,0.074908,0.074809,0.087111,0.662864,-0.003876,1.124071,-0.003876,0.038328,-0.153029,0.213363,1.076767,0.781105,0.678480,-1.100526,-0.236015,-1.452563,-0.918119,1.069529,0.319236,1.475443,-0.610516,0.797801,-0.417220,-1.175610,-0.119667,-0.495752,0.000029,1.384239,1.275388,-1.384239,-1.275388,1.384224,1.275392,-0.650163,-0.418961,-0.082013,-0.146715,-0.071707,0.552885,0.329894,0.273434,1.586312,1.831840,0.891767,1.413205,1.547778,2.450526,0.357308,-2.027860,1.476410,0.911499,0.124828,1.707674,1.539383,1.691886,-0.160638,-1.544978,1.529618,0.260294,-0.328340,-2.382964,2.221644,0.432133,-2.362190,1.504139,-1.504139,1.632487,-0.999416,-0.715532
7423,0.556110,0.547723,0.560475,0.683780,0.017205,-0.111224,0.252549,0.728169,0.622166,0.229666,-1.268548,-0.368039,-0.561384,-0.570175,0.448871,0.380389,-0.00658,-0.008080,-0.414064,-0.477483,-0.477456,-0.144717,0.089375,0.281530,0.373883,0.281530,0.584722,0.423159,0.227545,0.949448,0.943996,0.288787,-0.712005,-1.120647,0.844477,0.002022,0.788563,0.607145,0.626962,-1.908827,0.797801,-0.521689,-0.173330,0.418323,-0.008731,0.835980,-0.513833,-0.527205,0.513833,0.527205,-0.513886,-0.523911,-0.286039,-0.251561,-0.269025,0.644595,-1.124856,-0.262426,0.240646,0.237529,-0.547797,-0.640307,0.581855,-0.507332,-0.604055,0.553294,0.088546,1.013922,-0.565101,-0.024232,0.337545,-0.158211,-1.157660,-1.624824,0.450235,0.748613,-0.009571,0.448277,-0.223699,0.144230,0.302460,0.480211,1.890209,-0.581947,0.581947,0.546086,-0.999416,1.623964
2528,-0.952155,-0.852996,0.086268,0.042980,-0.977366,-0.882992,-0.515762,-0.081084,-0.681277,2.626812,0.005854,2.378467,-0.394616,-0.309012,-1.152861,-1.548392,-0.00658,-0.105670,0.256468,0.219933,0.219938,0.520672,-1.192465,0.376666,0.098365,0.376665,0.325185,1.490359,-0.995229,-0.595361,0.193794,-1.862357,-1.165280,-0.405002,-1.634884,1.688945,-0.069944,0.871062,-0.236808,0.177424,-2.781703,-0.113100,1.001565,-0.382878,0.918201,-0.780192,-0.022339,-0.018436,0.022339,0.018436,-0.022383,-0.018489,-0.025225,-0.009476,-0.019676,0.018504,0.010865,0.029961,0.002373,0.004146,-0.029962,-0.034884,-0.037969,-0.027198,-0.027628,-0.034476,0.011757,0.053359,-0.022729,-0.024232,-0.034710,-0.003680,-0.041642,-0.055083,0.009755,0.042893,-0.009571,0.018601,-0.014416,0.020952,0.037745,-0.000575,0.080677,-0.020983,0.020983,0.002886,-0.999416,0.746653
10064,-0.095322,-0.018096,0.455715,0.277340,-0.506578,-0.283939,0.008202,-0.123970,0.063248,-0.684075,-0.034915,-0.180116,-0.021720,0.046363,0.195875,0.192521,-0.00658,-0.135989,0.180541,0.231867,0.231643,0.221328,-0.317149,-0.003876,-0.751248,-0.003876,0.083861,-0.077874,0.158660,0.185531,-0.155516,0.361854,0.108207,0.189289,0.113047,-0.753808,0.179804,-0.274577,0.076595,0.911642,0.030765,0.070301,-0.423900,0.158005,0.335049,-0.835922,1.374539,1.780788,-1.374539,-1.780788,1.374523,1.780814,2.708242,2.292911,2.567320,0.870684,0.436760,1.851760,-0.630081,-0.534429,1.005709,1.007791,1.821504,-0.027198,1.628380,-0.298601,1.163594,0.533641,0.708558,1.535320,0.124828,1.426558,0.516367,0.552558,0.162722,0.042893,1.016555,0.824243,3.124827,0.760618,0.037745,-0.289047,-1.276471,1.872272,-1.872272,1.632487,-0.999416,0.307998
3378,-1.174518,-1.003384,1.645557,1.503400,-2.614035,-2.438719,-0.579292,-0.263904,-1.131438,0.463775,-1.348773,-0.788668,-0.929084,-0.809170,-1.557884,-1.439692,-0.00658,-0.036504,-0.101063,-0.129497,-0.129447,-0.169121,-2.231198,-0.003876,-0.435995,-0.003876,-0.986161,0.285375,-1.381120,-1.119492,-0.114794,-2.811566,0.151376,0.342399,-0.443959,0.133470,-2.255234,-1.660142,-1.092933,0.508718,0.081900,-1.009210,-0.702311,-0.996071,2.416826,-1.253898,0.035864,-0.001589,-0.035864,0.001589,0.035822,0.001728,-0.922832,0.196554,-0.206688,-0.723531,-0.359983,-1.297028,-0.896358,-0.920408,0.179265,0.234194,-0.657794,-0.027198,0.436445,1.157184,0.242125,-0.320193,0.269786,-0.128202,-1.098298,0.173867,-0.289646,-0.662725,0.605846,-1.721408,-0.420021,-1.377845,-0.432982,0.760618,-0.756400,-1.058306,-0.281229,0.014077,-0.014077,-0.540315,1.000585,-0.349986
1965,0.229928,0.230790,-0.150739,-0.311130,0.351722,0.523296,-0.936250,0.030585,-0.827527,-0.322162,-0.963834,-1.338044,-1.142593,-1.120902,-0.514922,-0.298694,-0.00658,-0.079141,-1.153290,-1.066171,-1.066141,-0.913413,0.153499,0.138827,0.501964,0.138827,-0.576365,-0.428597,-0.244519,-1.024003,-1.092138,-0.135291,0.518313,0.376423,0.163888,0.330643,0.203218,0.337230,-1.184661,-1.058209,0.337579,-1.566377,0.411333,-0.510144,-0.533950,0.000029,-2.476575,-1.585176,2.476575,1.585176,-2.486369,-1.585297,-0.086195,-1.384727,-1.359927,2.696784,-2.996478,0.029961,1.258467,1.673729,-2.069919,-1.632530,-2.827180,-0.027198,-2.196558,0.486332,-2.061549,0.053359,-2.052052,-0.959963,-0.991940,-0.191090,1.074376,0.856379,0.391005,-0.221752,-0.830471,-0.787041,-1.060831,-2.937713,-1.947618,1.730257,0.080677,-1.598696,1.598696,-1.626716,1.000585,1.039090
1161,-0.466237,-0.596032,-0.951336,-0.901526,0.431830,0.271150,-0.390189,-0.673265,-0.555054,-0.160913,-0.082768,0.266902,0.500312,0.389269,-0.112194,-0.047054,-0.00658,0.134041,-0.381091,-0.350132,-0.350204,-0.217927,0.252710,0.138827,-0.334310,0.138827,-0.986161,-0.854475,-0.256675,0.153702,0.604640,-1.215543,0.129792,0.257338,-0.228590,-0.753808,0.905632,0.283247,-0.726022,-0.252361,0.388715,0.418531,-0.034125,-0.657658,-0.352510,0.835980,-1.593826,-1.847984,1.593826,1.847984,-1.589051,-1.858225,-0.137003,-1.276561,-1.282005,-1.068461,-0.532369,-2.129208,0.658242,0.623508,-0.924404,-0.800072,0.891767,-0.747399,-1.903460,-0.246520,-2.637468,-1.467531,-1.448740,0.599589,-0.034710,0.982691,0.609368,0.628514,-0.059622,-1.015687,-1.446147,-1.753811,-1.688679,-0.718714,-0.756400,0.576369,-0.597897,-1.861648,1.861648,0.002886,-0.999416,-0.569314
2771,-1.113941,-1.106853,-0.899436,-0.889968,-0.231041,-0.241453,1.173629,-2.120647,0.444011,1.095629,-0.975798,0.104568,2.734147,2.737653,-0.924534,-0.531375,-0.00658,-0.072035,-0.395881,-0.433009,-0.433007,-0.461957,0.558813,-0.003876,-0.807939,-0.003876,-0.917862,-1.104991,-0.052046,-2.901964,-3.168995,0.103969,0.561482,0.019168,1.272546,0.462092,0.835391,0.895055,0.374710,-0.610516,1.155752,2.090032,0.383492,-1.265066,0.277752,0.418004,1.015619,0.931716,-1.015619,-0.931716,1.005895,0.941813,0.076391,0.021429,1.040058,-0.172802,-0.084744,0.670965,1.270588,1.189012,1.727540,1.646849,1.356636,-1.467600,1.716309,-0.622246,1.624329,-0.907203,2.079722,-0.336142,-1.630092,1.870425,-0.971657,-1.574187,1.810104,-1.015687,2.247906,1.146500,0.822715,0.020952,0.037745,1.153313,0.894966,0.820464,-0.820464,1.632487,-0.999416,-0.276877
9937,0.411658,0.267144,-0.741816,-0.554801,1.066532,0.796684,-0.120345,-0.566747,-0.167305,-0.362773,-0.276997,-0.150528,0.497225,0.392732,0.448871,0.707866,-0.00658,-0.072035,-0.348482,-0.345053,-0.344853,-0.059307,0.822570,0.281530,0.506464,0.281530,-0.485300,-0.967207,0.296430,0.408340,-0.114794,0.816018,1.165849,0.988861,0.558551,-0.589497,-0.030921,-0.346555,-0.336180,1.045950,0.388715,0.209593,0.717585,0.210069,-0.868180,0.835980,1.049571,0.845798,-1.049571,-0.845798,1.049548,0.850837,-0.233538,0.693602,0.136167,-1.690204,-0.843099,-2.702738,-1.663329,-1.773152,0.778175,1.175964,1.356636,-0.747399,0.800376,0.454712,-0.333794,-1.547578,0.571442,0.755544,0.124828,0.898850,1.539383,1.539976,0.398789,-2.206590,-0.830471,-1.995504,-0.328340,1.685201,0.831890,-1.442935,-0.190752,0.820464,-0.820464,0.002886,1.000585,-0.569314

In [5]:
df_test = rcp('150_test_split.csv', None, 0)
p(df_test)

(3080, 88)

,E_OFF_RATING_cma_diff,OFF_RATING_cma_diff,E_DEF_RATING_cma_diff,DEF_RATING_cma_diff,E_NET_RATING_cma_diff,NET_RATING_cma_diff,AST_PCT_cma_diff,AST_TOV_cma_diff,AST_RATIO_cma_diff,OREB_PCT_cma_diff,DREB_PCT_cma_diff,REB_PCT_cma_diff,E_TM_TOV_PCT_cma_diff,TM_TOV_PCT_cma_diff,EFG_PCT_cma_diff,TS_PCT_cma_diff,USG_PCT_cma_diff,E_USG_PCT_cma_diff,E_PACE_cma_diff,PACE_cma_diff,PACE_PER40_cma_diff,POSS_cma_diff,PIE_cma_diff,duration_minutes_cma_diff,w_pct_cma_diff,min_cma_diff,fgm_cma_diff,fga_cma_diff,fg_pct_cma_diff,fg3m_cma_diff,fg3a_cma_diff,fg3_pct_cma_diff,ftm_cma_diff,fta_cma_diff,ft_pct_cma_diff,oreb_cma_diff,dreb_cma_diff,reb_cma_diff,ast_cma_diff,stl_cma_diff,blk_cma_diff,tov_cma_diff,pf_cma_diff,pts_cma_diff,spread_cma_diff,away_home_cma_diff,E_OFF_RATING_sm_cma_diff,OFF_RATING_sm_cma_diff,E_DEF_RATING_sm_cma_diff,DEF_RATING_sm_cma_diff,E_NET_RATING_sm_cma_diff,NET_RATING_sm_cma_diff,AST_PCT_sm_cma_diff,AST_TOV_sm_cma_diff,AST_RATIO_sm_cma_diff,OREB_PCT_sm_cma_diff,DREB_PCT_sm_cma_diff,REB_PCT_sm_cma_diff,E_TM_TOV_PCT_sm_cma_diff,TM_TOV_PCT_sm_cma_diff,EFG_PCT_sm_cma_diff,TS_PCT_sm_cma_diff,E_USG_PCT_sm_cma_diff,POSS_sm_cma_diff,PIE_sm_cma_diff,w_pct_sm_cma_diff,fgm_sm_cma_diff,fga_sm_cma_diff,fg_pct_sm_cma_diff,fg3m_sm_cma_diff,fg3a_sm_cma_diff,fg3_pct_sm_cma_diff,ftm_sm_cma_diff,fta_sm_cma_diff,ft_pct_sm_cma_diff,oreb_sm_cma_diff,dreb_sm_cma_diff,reb_sm_cma_diff,ast_sm_cma_diff,stl_sm_cma_diff,blk_sm_cma_diff,tov_sm_cma_diff,pf_sm_cma_diff,pts_sm_cma_diff,spread_sm_cma_diff,away_home_sm_cma_diff,away_home_a,spread_a
2583,0.364128,0.314684,-0.920580,-0.982429,1.188895,1.256641,-1.064798,-0.921805,-0.600467,0.252360,-0.514153,-0.408023,0.720669,0.669828,0.574508,0.578599,-0.00658,-0.064928,0.449053,0.506638,0.506363,0.416552,1.000424,-0.146579,1.079977,-0.146579,0.607488,-0.115451,0.802937,-0.387406,-0.101220,-1.221274,0.561482,0.733678,-0.036432,0.100608,-0.101162,-0.022657,-0.496703,2.433799,0.490987,0.801583,1.385772,0.583191,-1.202410,0.000029,-0.022339,-0.018436,0.022339,0.018436,-0.022383,-0.018489,-0.025225,-0.009476,-0.019676,0.018504,0.010865,0.029961,0.002373,0.004146,-0.029962,-0.034884,-0.037969,-0.027198,-0.027628,-0.034476,0.011757,0.053359,-0.022729,-0.024232,-0.034710,-0.003680,-0.041642,-0.055083,0.009755,0.042893,-0.009571,0.018601,-0.014416,0.020952,0.037745,-0.000575,0.080677,-0.020983,0.020983,0.002886,1.000585,0.527325
9370,-0.726251,-0.886865,-0.028679,-0.236006,-0.661512,-0.653382,-1.661853,-0.376687,-1.774194,-0.807101,0.385914,-0.289671,-1.054252,-1.086265,-1.014029,-1.034655,-0.00658,-0.086247,-0.983940,-0.785825,-0.785623,-0.803600,-0.960811,-0.003876,-1.871279,-0.003876,-1.487022,-0.340916,-1.206882,-0.164597,-0.060497,-0.274263,-0.668836,-0.593270,-0.465613,-0.162289,-0.147990,-0.202600,-2.468849,-1.058209,-3.139654,-1.636023,0.494856,-1.447289,0.783873,1.253955,-3.175014,-2.959863,3.175014,2.959863,-3.175121,-2.960045,-1.397040,-0.488496,-2.419660,0.435898,0.219467,-0.779727,-1.174939,-1.019147,-3.199741,-3.566522,1.821504,-0.027198,-2.562932,-1.894508,-2.291917,1.654297,-2.984443,-1.895694,-1.630092,-0.743458,-0.785654,0.552558,-2.471957,1.101473,-2.472272,-1.270426,-2.525811,1.870118,-3.138836,-1.154463,-0.733612,-3.176408,3.176408,1.632487,-0.999416,1.112200
5655,-0.544521,-0.381636,0.635441,0.584578,-1.099025,-0.938778,0.475648,0.308365,0.290309,0.386136,-1.368477,-1.277268,0.254977,0.351168,-0.613022,-0.638236,-0.00658,-0.107565,-0.011115,-0.096173,-0.095999,-0.010501,-0.780537,0.138827,-1.522132,0.138827,0.152160,0.360530,-0.181712,-1.405961,-1.214306,-0.711235,-0.215561,-0.116930,-0.225624,0.560678,-0.780163,-0.292572,0.489370,0.329640,-0.429457,0.105124,1.330090,-0.353953,0.984411,-0.835922,-0.400660,-0.736104,0.400660,0.736104,-0.400711,-0.736188,-0.858476,1.350323,-0.643048,-0.224976,-0.110820,-1.353257,-2.178713,-2.230941,-0.893020,-1.195279,-0.037969,1.413205,-0.862959,-1.656424,0.011757,1.494203,-0.772299,-0.648053,0.603442,-1.493099,-0.785654,-0.510815,-1.166473,0.572183,-2.267047,-1.431554,-0.642265,1.870118,-0.756400,-2.308351,0.623537,-0.652068,0.652068,1.632487,-0.999416,-0.057549
7258,0.291436,0.402306,-1.376142,-1.278108,1.534856,1.621467,-0.564419,0.437857,-0.052028,0.799410,0.302170,-0.137733,-0.701027,-0.649840,-0.241274,-0.181492,-0.00658,0.027450,-0.146765,-0.280510,-0.280484,-0.254531,1.744507,-0.003876,1.468719,-0.003876,0.835153,0.385581,0.565892,-2.233537,-2.422412,-1.131014,0.367222,0.410447,-0.017143,0.987886,2.427531,2.406579,0.007799,-1.147748,1.002344,-0.765449,-1.593227,0.175360,-1.698981,0.000029,0.632447,0.699232,-0.632447,-0.699232,0.632417,0.699211,0.223734,-0.905707,0.229673,0.453289,0.228158,1.446916,1.080934,1.054368,0.582025,0.898478,-0.037969,0.693003,1.240024,2.046899,0.242125,-1.547578,1.083343,-1.427828,-2.268245,-0.112180,1.818388,2.223573,-0.368319,0.042893,1.324393,1.065936,0.299508,-0.903631,1.228963,1.153313,-2.497904,0.767873,-0.767873,0.002886,1.000585,-0.349986
2386,-0.012379,-0.009706,0.019376,0.017296,-0.029451,-0.026252,-0.170277,-0.115615,-0.128880,0.036168,-0.029989,-0.024179,0.042035,0.042899,-0.029584,-0.022925,-0.00658,-0.008080,-0.023965,-0.024198,-0.024198,-0.022702,-0.031614,-0.003876,-0.047253,-0.003876,0.015561,-0.002719,0.014812,-0.132767,-0.155516,-0.006349,0.000285,-0.014857,0.017131,0.067746,-0.054334,-0.004662,-0.129792,0.016255,0.081900,0.035478,0.132922,-0.024217,0.029467,0.000029,-0.022339,-0.018436,0.022339,0.018436,-0.022383,-0.018489,-0.025225,-0.009476,-0.019676,0.018504,0.010865,0.029961,0.002373,0.004146,-0.029962,-0.034884,-0.037969,-0.027198,-0.027628,-0.034476,0.011757,0.053359,-0.022729,-0.024232,-0.034710,-0.003680,-0.041642,-0.055083,0.009755,0.042893,-0.009571,0.018601,-0.014416,0.020952,0.037745,-0.000575,0.080677,-0.020983,0.020983,0.002886,1.000585,-0.715532
8109,-0.310602,-0.362993,0.036676,-0.020266,-0.326115,-0.342126,0.625443,-0.625227,0.353187,-0.510882,-0.006062,-0.803062,1.249406,1.196309,0.011722,-0.081526,-0.00658,0.112723,0.215332,0.291702,0.291403,0.209127,-0.296581,-0.003876,-0.601570,-0.003876,-0.075504,0.084962,-0.175634,0.535660,0.753957,-0.176839,-0.668836,-0.712355,0.231635,0.429230,-0.007507,0.229264,0.443506,-0.879132,0.746665,1.184635,0.634062,-0.180408,0.497390,1.671931,-0.022339,-0.018436,0.022339,0.018436,-0.022383,-0.018489,-0.025225,-0.009476,-0.019676,0.018504,0.010865,0.029961,0.002373,0.004146,-0.029962,-0.034884,-0.037969,-0.027198,-0.027628,-0.034476,0.011757,0.053359,-0.022729,-0.024232,-0.034710,-0.003680,-0.041642,-0.055083,0.009755,0.042893,-0.009571,0.018601,-0.014416,0.020952,0.037745,-0.000575,0.080677,-0.020983,0.020983,0.002886,-0.999416,0.161779
9743,-0.409389,-0.383501,-0.060396,0.109756,-0.334037,-0.486209,0.994087,0.385643,0.772375,-0.263635,-0.231959,-0.190512,-0.036053,-0.009056,-0.466732,-0.383149,-0.00658,0.006132,0.446749,0.337043,0.336744,0.721591,0.056708,0.424233,0.379883,0.424233,0.334291,0.711253,-0.228311,-0.642045,-0.019774,-0.953360,0.280884,0.121240,0.399791,0.166332,0.413942,0.409208,1.131464,-0.207592,0.439851,0.314062,-0.089807,0.192714,0.526038,0.835980,0.031014,0.279750,-0.031014,-0.279750,0.030971,0.279710,0.117037,-0.643019,0.245257,-0.077149,-0.039113,0.063698,1.074461,1.135154,0.715407,0.520088,0.426899,-1.467600,0.045647,0.097586,0.357308,0.053359,0.315491,1.535320,-0.194249,1.712605,-1.157660,-1.194411,-0.002106,-0.089430,0.298267,0.179729,0.299508,-1.273464,1.030426,1.297549,0.352107,0.189379,-0.189379,-1.626716,1.000585,1.770183
4546,-0.467169,-0.596032,0.630636,0.387137,-1.018917,-0.959097,-0.415686,-1.155725,-0.803074,-0.440411,-0.371296,-0.920614,0.434960,0.375414,-0.800618,-0.669260,-0.00658,0.084299,0.152053,0.354139,0.353840,0.367746,-0.744241,0.138827,-0.677159,0.138827,-0.371468,0.247797,-0.655802,-0.673874,-0.359130,-0.602350,0.647821,0.852763,-0.604374,1.152197,0.296873,0.859066,-0.519635,0.329640,-0.378322,0.453353,-0.730152,-0.206440,1.041707,-0.417947,-0.439462,-0.564268,0.439462,0.564268,-0.439514,-0.564344,0.797863,-1.801938,-0.487205,0.079374,0.041286,0.198646,1.866957,1.862231,-0.673333,-0.303961,-0.037969,-2.908003,-0.599170,-0.599926,-1.831182,-1.707672,-0.754017,-0.336142,-0.194249,-0.329182,1.818388,2.375483,-1.220404,1.366118,-0.009571,0.824243,-0.432982,-1.088548,1.626035,1.730257,-1.276471,-0.757249,0.757249,-1.626716,1.000585,0.454216
4962,-0.389818,-0.352740,-0.339115,-0.285125,-0.055860,-0.073356,-0.408249,-0.988639,-0.031069,-1.190514,0.422507,-0.529573,0.974376,1.019661,0.180386,-0.133232,-0.00658,-0.072035,0.185996,0.138584,0.138880,0.209127,-0.315939,0.138827,-0.050853,0.138827,0.789620,0.736304,0.164738,0.408340,0.197413,0.005113,-2.114999,-2.294486,0.609875,0.232057,0.367114,0.409208,0.145391,-0.162823,-0.480593,1.010520,0.689744,-0.137022,0.153610,-0.417947,-0.266065,-0.237021,0.266065,0.237021,-0.266114,-0.233293,0.546364,-0.026860,0.366036,-0.398891,0.345497,0.055264,0.781165,0.808643,0.001422,-0.091642,0.194465,-0.207248,-0.249284,0.157572,0.098145,0.293500,-0.022729,0.092734,0.005174,0.085094,-0.715903,-0.890591,0.107523,0.472941,0.195655,0.441563,0.482631,-0.996089,-0.408962,0.828782,0.827109,-0.283935,0.283935,0.002886,-0.999416,0.746653
5706,-0.235114,-0.458073,-0.062318,0.005739,-0.168540,-0.462195,-0.430559,1.448727,-0.052028,-2.189059,-0.509227,-1.382825,-2.012811,-2.118446,-0.681865,-0.703732,-0.00658,0.134041,-0.915691,-0.831042,-0.830964,-0.571771,-0.144134,0.281530,-0.052652,0.281530,-0.280402,0.022333,-0.280987,-1.374131,-1.200732,-0.506359,-0.733589,-0.797416,0.114238,-0.556635,0.390528,-0.004662,-0.473771,-1.774519,0.439851,-2.193190,-0.535265,-0.883267,0.449642,0.000029,-0.468564,-0.341892,0.468564,0.341892,-0.468616,-0.341959,-0.848314,0.175951,-0.144350,-2.877169,2.909561,0.029961,-0.644129,-0.561358,-0.422261,-0.791663,-2.362311,-0.027198,-0.115558,-0.239080,1.163594,1.013922,0.562301,-2.831425,-1.789630,-1.532554,-0.785654,-0.206994,-1.424832,0.572183,0.195655,0.501986,-0.014416,-0.718714,2.023108,-0.865991,-0.190752,-0.336525,0.336525,-1.626716,-0.999416,0.381107

In [6]:
X_train = df_train.drop(columns = 'spread_a')
p(X_train)

(7186, 87)

,E_OFF_RATING_cma_diff,OFF_RATING_cma_diff,E_DEF_RATING_cma_diff,DEF_RATING_cma_diff,E_NET_RATING_cma_diff,NET_RATING_cma_diff,AST_PCT_cma_diff,AST_TOV_cma_diff,AST_RATIO_cma_diff,OREB_PCT_cma_diff,DREB_PCT_cma_diff,REB_PCT_cma_diff,E_TM_TOV_PCT_cma_diff,TM_TOV_PCT_cma_diff,EFG_PCT_cma_diff,TS_PCT_cma_diff,USG_PCT_cma_diff,E_USG_PCT_cma_diff,E_PACE_cma_diff,PACE_cma_diff,PACE_PER40_cma_diff,POSS_cma_diff,PIE_cma_diff,duration_minutes_cma_diff,w_pct_cma_diff,min_cma_diff,fgm_cma_diff,fga_cma_diff,fg_pct_cma_diff,fg3m_cma_diff,fg3a_cma_diff,fg3_pct_cma_diff,ftm_cma_diff,fta_cma_diff,ft_pct_cma_diff,oreb_cma_diff,dreb_cma_diff,reb_cma_diff,ast_cma_diff,stl_cma_diff,blk_cma_diff,tov_cma_diff,pf_cma_diff,pts_cma_diff,spread_cma_diff,away_home_cma_diff,E_OFF_RATING_sm_cma_diff,OFF_RATING_sm_cma_diff,E_DEF_RATING_sm_cma_diff,DEF_RATING_sm_cma_diff,E_NET_RATING_sm_cma_diff,NET_RATING_sm_cma_diff,AST_PCT_sm_cma_diff,AST_TOV_sm_cma_diff,AST_RATIO_sm_cma_diff,OREB_PCT_sm_cma_diff,DREB_PCT_sm_cma_diff,REB_PCT_sm_cma_diff,E_TM_TOV_PCT_sm_cma_diff,TM_TOV_PCT_sm_cma_diff,EFG_PCT_sm_cma_diff,TS_PCT_sm_cma_diff,E_USG_PCT_sm_cma_diff,POSS_sm_cma_diff,PIE_sm_cma_diff,w_pct_sm_cma_diff,fgm_sm_cma_diff,fga_sm_cma_diff,fg_pct_sm_cma_diff,fg3m_sm_cma_diff,fg3a_sm_cma_diff,fg3_pct_sm_cma_diff,ftm_sm_cma_diff,fta_sm_cma_diff,ft_pct_sm_cma_diff,oreb_sm_cma_diff,dreb_sm_cma_diff,reb_sm_cma_diff,ast_sm_cma_diff,stl_sm_cma_diff,blk_sm_cma_diff,tov_sm_cma_diff,pf_sm_cma_diff,pts_sm_cma_diff,spread_sm_cma_diff,away_home_sm_cma_diff,away_home_a
3134,-0.018902,-0.016231,1.321667,1.343521,-1.228430,-1.303603,-1.318706,-1.481543,-1.903444,0.921242,-2.507811,-0.529573,0.446845,0.430833,-0.575159,0.121855,-0.00658,-0.050716,0.174116,0.184420,0.184667,0.087111,-0.946293,-0.146579,-0.692156,-0.146579,-1.441489,-0.954681,-0.761156,0.058212,-0.155516,0.712864,2.741520,2.536967,1.145528,-0.129427,-0.499197,-0.454521,-1.849687,0.374410,0.695530,0.314062,1.079520,0.019169,1.242246,-1.671873,-0.972992,-0.574376,0.972992,0.574376,-0.982755,-0.574453,0.482854,-0.689375,-0.331362,0.453289,0.228158,0.772176,0.513350,0.650436,-0.657641,-0.640307,-0.502838,-1.467600,-0.218142,-0.622246,-1.140080,-0.426922,-0.790581,-0.024232,-0.034710,-0.003680,0.702370,1.160200,-1.334506,0.042893,0.400880,0.340858,-0.223699,0.020952,0.037745,-0.000575,-2.090760,-0.652068,0.652068,1.632487,-0.999416
8383,-0.099050,-0.203595,-0.808132,-0.713716,0.644865,0.483580,1.728190,1.736950,1.631711,-1.010155,0.087533,-0.470397,-0.467579,-0.507828,0.560740,0.066701,-0.00658,-0.015186,0.085137,0.074908,0.074809,0.087111,0.662864,-0.003876,1.124071,-0.003876,0.038328,-0.153029,0.213363,1.076767,0.781105,0.678480,-1.100526,-0.236015,-1.452563,-0.918119,1.069529,0.319236,1.475443,-0.610516,0.797801,-0.417220,-1.175610,-0.119667,-0.495752,0.000029,1.384239,1.275388,-1.384239,-1.275388,1.384224,1.275392,-0.650163,-0.418961,-0.082013,-0.146715,-0.071707,0.552885,0.329894,0.273434,1.586312,1.831840,0.891767,1.413205,1.547778,2.450526,0.357308,-2.027860,1.476410,0.911499,0.124828,1.707674,1.539383,1.691886,-0.160638,-1.544978,1.529618,0.260294,-0.328340,-2.382964,2.221644,0.432133,-2.362190,1.504139,-1.504139,1.632487,-0.999416
7423,0.556110,0.547723,0.560475,0.683780,0.017205,-0.111224,0.252549,0.728169,0.622166,0.229666,-1.268548,-0.368039,-0.561384,-0.570175,0.448871,0.380389,-0.00658,-0.008080,-0.414064,-0.477483,-0.477456,-0.144717,0.089375,0.281530,0.373883,0.281530,0.584722,0.423159,0.227545,0.949448,0.943996,0.288787,-0.712005,-1.120647,0.844477,0.002022,0.788563,0.607145,0.626962,-1.908827,0.797801,-0.521689,-0.173330,0.418323,-0.008731,0.835980,-0.513833,-0.527205,0.513833,0.527205,-0.513886,-0.523911,-0.286039,-0.251561,-0.269025,0.644595,-1.124856,-0.262426,0.240646,0.237529,-0.547797,-0.640307,0.581855,-0.507332,-0.604055,0.553294,0.088546,1.013922,-0.565101,-0.024232,0.337545,-0.158211,-1.157660,-1.624824,0.450235,0.748613,-0.009571,0.448277,-0.223699,0.144230,0.302460,0.480211,1.890209,-0.581947,0.581947,0.546086,-0.999416
2528,-0.952155,-0.852996,0.086268,0.042980,-0.977366,-0.882992,-0.515762,-0.081084,-0.681277,2.626812,0.005854,2.378467,-0.394616,-0.309012,-1.152861,-1.548392,-0.00658,-0.105670,0.256468,0.219933,0.219938,0.520672,-1.192465,0.376666,0.098365,0.376665,0.325185,1.490359,-0.995229,-0.595361,0.193794,-1.862357,-1.165280,-0.405002,-1.634884,1.688945,-0.069944,0.871062,-0.236808,0.177424,-2.781703,-0.113100,1.001565,-0.382878,0.918201,-0.780192,-0.022339,-0.018436,0.022339,0.018436,-0.022383,-0.018489,-0.025225,-0.009476,-0.019676,0.018504,0.010865,0.029961,0.002373,0.004146,-0.029962,-0.034884,-0.037969,-0.027198,-0.027628,-0.034476,0.011757,0.053359,-0.022729,-0.024232,-0.034710,-0.003680,-0.041642,-0.055083,0.009755,0.042893,-0.009571,0.018601,-0.014416,0.020952,0.037745,-0.000575,0.080677,-0.020983,0.020983,0.002886,-0.999416
10064,-0.095322,-0.018096,0.455715,0.277340,-0.506578,-0.283939,0.008202,-0.123970,0.063248,-0.684075,-0.034915,-0.180116,-0.021720,0.046363,0.195875,0.192521,-0.00658,-0.135989,0.180541,0.231867,0.231643,0.221328,-0.317149,-0.003876,-0.751248,-0.003876,0.083861,-0.077874,0.158660,0.185531,-0.155516,0.361854,0.108207,0.189289,0.113047,-0.753808,0.179804,-0.274577,0.076595,0.911642,0.030765,0.070301,-0.423900,0.158005,0.335049,-0.835922,1.374539,1.780788,-1.374539,-1.780788,1.374523,1.780814,2.708242,2.292911,2.567320,0.870684,0.436760,1.851760,-0.630081,-0.534429,1.005709,1.007791,1.821504,-0.027198,1.628380,-0.298601,1.163594,0.533641,0.708558,1.535320,0.124828,1.426558,0.516367,0.552558,0.162722,0.042893,1.016555,0.824243,3.124827,0.760618,0.037745,-0.289047,-1.276471,1.872272,-1.872272,1.632487,-0.999416
3378,-1.174518,-1.003384,1.645557,1.503400,-2.614035,-2.438719,-0.579292,-0.263904,-1.131438,0.463775,-1.348773,-0.788668,-0.929084,-0.809170,-1.557884,-1.439692,-0.00658,-0.036504,-0.101063,-0.129497,-0.129447,-0.169121,-2.231198,-0.003876,-0.435995,-0.003876,-0.986161,0.285375,-1.381120,-1.119492,-0.114794,-2.811566,0.151376,0.342399,-0.443959,0.133470,-2.255234,-1.660142,-1.092933,0.508718,0.081900,-1.009210,-0.702311,-0.996071,2.416826,-1.253898,0.035864,-0.001589,-0.035864,0.001589,0.035822,0.001728,-0.922832,0.196554,-0.206688,-0.723531,-0.359983,-1.297028,-0.896358,-0.920408,0.179265,0.234194,-0.657794,-0.027198,0.436445,1.157184,0.242125,-0.320193,0.269786,-0.128202,-1.098298,0.173867,-0.289646,-0.662725,0.605846,-1.721408,-0.420021,-1.377845,-0.432982,0.760618,-0.756400,-1.058306,-0.281229,0.014077,-0.014077,-0.540315,1.000585
1965,0.229928,0.230790,-0.150739,-0.311130,0.351722,0.523296,-0.936250,0.030585,-0.827527,-0.322162,-0.963834,-1.338044,-1.142593,-1.120902,-0.514922,-0.298694,-0.00658,-0.079141,-1.153290,-1.066171,-1.066141,-0.913413,0.153499,0.138827,0.501964,0.138827,-0.576365,-0.428597,-0.244519,-1.024003,-1.092138,-0.135291,0.518313,0.376423,0.163888,0.330643,0.203218,0.337230,-1.184661,-1.058209,0.337579,-1.566377,0.411333,-0.510144,-0.533950,0.000029,-2.476575,-1.585176,2.476575,1.585176,-2.486369,-1.585297,-0.086195,-1.384727,-1.359927,2.696784,-2.996478,0.029961,1.258467,1.673729,-2.069919,-1.632530,-2.827180,-0.027198,-2.196558,0.486332,-2.061549,0.053359,-2.052052,-0.959963,-0.991940,-0.191090,1.074376,0.856379,0.391005,-0.221752,-0.830471,-0.787041,-1.060831,-2.937713,-1.947618,1.730257,0.080677,-1.598696,1.598696,-1.626716,1.000585
1161,-0.466237,-0.596032,-0.951336,-0.901526,0.431830,0.271150,-0.390189,-0.673265,-0.555054,-0.160913,-0.082768,0.266902,0.500312,0.389269,-0.112194,-0.047054,-0.00658,0.134041,-0.381091,-0.350132,-0.350204,-0.217927,0.252710,0.138827,-0.334310,0.138827,-0.986161,-0.854475,-0.256675,0.153702,0.604640,-1.215543,0.129792,0.257338,-0.228590,-0.753808,0.905632,0.283247,-0.726022,-0.252361,0.388715,0.418531,-0.034125,-0.657658,-0.352510,0.835980,-1.593826,-1.847984,1.593826,1.847984,-1.589051,-1.858225,-0.137003,-1.276561,-1.282005,-1.068461,-0.532369,-2.129208,0.658242,0.623508,-0.924404,-0.800072,0.891767,-0.747399,-1.903460,-0.246520,-2.637468,-1.467531,-1.448740,0.599589,-0.034710,0.982691,0.609368,0.628514,-0.059622,-1.015687,-1.446147,-1.753811,-1.688679,-0.718714,-0.756400,0.576369,-0.597897,-1.861648,1.861648,0.002886,-0.999416
2771,-1.113941,-1.106853,-0.899436,-0.889968,-0.231041,-0.241453,1.173629,-2.120647,0.444011,1.095629,-0.975798,0.104568,2.734147,2.737653,-0.924534,-0.531375,-0.00658,-0.072035,-0.395881,-0.433009,-0.433007,-0.461957,0.558813,-0.003876,-0.807939,-0.003876,-0.917862,-1.104991,-0.052046,-2.901964,-3.168995,0.103969,0.561482,0.019168,1.272546,0.462092,0.835391,0.895055,0.374710,-0.610516,1.155752,2.090032,0.383492,-1.265066,0.277752,0.418004,1.015619,0.931716,-1.015619,-0.931716,1.005895,0.941813,0.076391,0.021429,1.040058,-0.172802,-0.084744,0.670965,1.270588,1.189012,1.727540,1.646849,1.356636,-1.467600,1.716309,-0.622246,1.624329,-0.907203,2.079722,-0.336142,-1.630092,1.870425,-0.971657,-1.574187,1.810104,-1.015687,2.247906,1.146500,0.822715,0.020952,0.037745,1.153313,0.894966,0.820464,-0.820464,1.632487,-0.999416
9937,0.411658,0.267144,-0.741816,-0.554801,1.066532,0.796684,-0.120345,-0.566747,-0.167305,-0.362773,-0.276997,-0.150528,0.497225,0.392732,0.448871,0.707866,-0.00658,-0.072035,-0.348482,-0.345053,-0.344853,-0.059307,0.822570,0.281530,0.506464,0.281530,-0.485300,-0.967207,0.296430,0.408340,-0.114794,0.816018,1.165849,0.988861,0.558551,-0.589497,-0.030921,-0.346555,-0.336180,1.045950,0.388715,0.209593,0.717585,0.210069,-0.868180,0.835980,1.049571,0.845798,-1.049571,-0.845798,1.049548,0.850837,-0.233538,0.693602,0.136167,-1.690204,-0.843099,-2.702738,-1.663329,-1.773152,0.778175,1.175964,1.356636,-0.747399,0.800376,0.454712,-0.333794,-1.547578,0.571442,0.755544,0.124828,0.898850,1.539383,1.539976,0.398789,-2.206590,-0.830471,-1.995504,-0.328340,1.685201,0.831890,-1.442935,-0.190752,0.820464,-0.820464,0.002886,1.000585

In [7]:
y_train = df_train.spread_a
p(y_train)

(7186,)

3134     0.819762
8383    -0.715532
7423     1.623964
2528     0.746653
10064    0.307998
3378    -0.349986
1965     1.039090
1161    -0.569314
2771    -0.276877
9937    -0.569314
Name: spread_a, dtype: float64

In [8]:
X_test = df_test.drop(columns = 'spread_a')
p(X_test)

(3080, 87)

,E_OFF_RATING_cma_diff,OFF_RATING_cma_diff,E_DEF_RATING_cma_diff,DEF_RATING_cma_diff,E_NET_RATING_cma_diff,NET_RATING_cma_diff,AST_PCT_cma_diff,AST_TOV_cma_diff,AST_RATIO_cma_diff,OREB_PCT_cma_diff,DREB_PCT_cma_diff,REB_PCT_cma_diff,E_TM_TOV_PCT_cma_diff,TM_TOV_PCT_cma_diff,EFG_PCT_cma_diff,TS_PCT_cma_diff,USG_PCT_cma_diff,E_USG_PCT_cma_diff,E_PACE_cma_diff,PACE_cma_diff,PACE_PER40_cma_diff,POSS_cma_diff,PIE_cma_diff,duration_minutes_cma_diff,w_pct_cma_diff,min_cma_diff,fgm_cma_diff,fga_cma_diff,fg_pct_cma_diff,fg3m_cma_diff,fg3a_cma_diff,fg3_pct_cma_diff,ftm_cma_diff,fta_cma_diff,ft_pct_cma_diff,oreb_cma_diff,dreb_cma_diff,reb_cma_diff,ast_cma_diff,stl_cma_diff,blk_cma_diff,tov_cma_diff,pf_cma_diff,pts_cma_diff,spread_cma_diff,away_home_cma_diff,E_OFF_RATING_sm_cma_diff,OFF_RATING_sm_cma_diff,E_DEF_RATING_sm_cma_diff,DEF_RATING_sm_cma_diff,E_NET_RATING_sm_cma_diff,NET_RATING_sm_cma_diff,AST_PCT_sm_cma_diff,AST_TOV_sm_cma_diff,AST_RATIO_sm_cma_diff,OREB_PCT_sm_cma_diff,DREB_PCT_sm_cma_diff,REB_PCT_sm_cma_diff,E_TM_TOV_PCT_sm_cma_diff,TM_TOV_PCT_sm_cma_diff,EFG_PCT_sm_cma_diff,TS_PCT_sm_cma_diff,E_USG_PCT_sm_cma_diff,POSS_sm_cma_diff,PIE_sm_cma_diff,w_pct_sm_cma_diff,fgm_sm_cma_diff,fga_sm_cma_diff,fg_pct_sm_cma_diff,fg3m_sm_cma_diff,fg3a_sm_cma_diff,fg3_pct_sm_cma_diff,ftm_sm_cma_diff,fta_sm_cma_diff,ft_pct_sm_cma_diff,oreb_sm_cma_diff,dreb_sm_cma_diff,reb_sm_cma_diff,ast_sm_cma_diff,stl_sm_cma_diff,blk_sm_cma_diff,tov_sm_cma_diff,pf_sm_cma_diff,pts_sm_cma_diff,spread_sm_cma_diff,away_home_sm_cma_diff,away_home_a
2583,0.364128,0.314684,-0.920580,-0.982429,1.188895,1.256641,-1.064798,-0.921805,-0.600467,0.252360,-0.514153,-0.408023,0.720669,0.669828,0.574508,0.578599,-0.00658,-0.064928,0.449053,0.506638,0.506363,0.416552,1.000424,-0.146579,1.079977,-0.146579,0.607488,-0.115451,0.802937,-0.387406,-0.101220,-1.221274,0.561482,0.733678,-0.036432,0.100608,-0.101162,-0.022657,-0.496703,2.433799,0.490987,0.801583,1.385772,0.583191,-1.202410,0.000029,-0.022339,-0.018436,0.022339,0.018436,-0.022383,-0.018489,-0.025225,-0.009476,-0.019676,0.018504,0.010865,0.029961,0.002373,0.004146,-0.029962,-0.034884,-0.037969,-0.027198,-0.027628,-0.034476,0.011757,0.053359,-0.022729,-0.024232,-0.034710,-0.003680,-0.041642,-0.055083,0.009755,0.042893,-0.009571,0.018601,-0.014416,0.020952,0.037745,-0.000575,0.080677,-0.020983,0.020983,0.002886,1.000585
9370,-0.726251,-0.886865,-0.028679,-0.236006,-0.661512,-0.653382,-1.661853,-0.376687,-1.774194,-0.807101,0.385914,-0.289671,-1.054252,-1.086265,-1.014029,-1.034655,-0.00658,-0.086247,-0.983940,-0.785825,-0.785623,-0.803600,-0.960811,-0.003876,-1.871279,-0.003876,-1.487022,-0.340916,-1.206882,-0.164597,-0.060497,-0.274263,-0.668836,-0.593270,-0.465613,-0.162289,-0.147990,-0.202600,-2.468849,-1.058209,-3.139654,-1.636023,0.494856,-1.447289,0.783873,1.253955,-3.175014,-2.959863,3.175014,2.959863,-3.175121,-2.960045,-1.397040,-0.488496,-2.419660,0.435898,0.219467,-0.779727,-1.174939,-1.019147,-3.199741,-3.566522,1.821504,-0.027198,-2.562932,-1.894508,-2.291917,1.654297,-2.984443,-1.895694,-1.630092,-0.743458,-0.785654,0.552558,-2.471957,1.101473,-2.472272,-1.270426,-2.525811,1.870118,-3.138836,-1.154463,-0.733612,-3.176408,3.176408,1.632487,-0.999416
5655,-0.544521,-0.381636,0.635441,0.584578,-1.099025,-0.938778,0.475648,0.308365,0.290309,0.386136,-1.368477,-1.277268,0.254977,0.351168,-0.613022,-0.638236,-0.00658,-0.107565,-0.011115,-0.096173,-0.095999,-0.010501,-0.780537,0.138827,-1.522132,0.138827,0.152160,0.360530,-0.181712,-1.405961,-1.214306,-0.711235,-0.215561,-0.116930,-0.225624,0.560678,-0.780163,-0.292572,0.489370,0.329640,-0.429457,0.105124,1.330090,-0.353953,0.984411,-0.835922,-0.400660,-0.736104,0.400660,0.736104,-0.400711,-0.736188,-0.858476,1.350323,-0.643048,-0.224976,-0.110820,-1.353257,-2.178713,-2.230941,-0.893020,-1.195279,-0.037969,1.413205,-0.862959,-1.656424,0.011757,1.494203,-0.772299,-0.648053,0.603442,-1.493099,-0.785654,-0.510815,-1.166473,0.572183,-2.267047,-1.431554,-0.642265,1.870118,-0.756400,-2.308351,0.623537,-0.652068,0.652068,1.632487,-0.999416
7258,0.291436,0.402306,-1.376142,-1.278108,1.534856,1.621467,-0.564419,0.437857,-0.052028,0.799410,0.302170,-0.137733,-0.701027,-0.649840,-0.241274,-0.181492,-0.00658,0.027450,-0.146765,-0.280510,-0.280484,-0.254531,1.744507,-0.003876,1.468719,-0.003876,0.835153,0.385581,0.565892,-2.233537,-2.422412,-1.131014,0.367222,0.410447,-0.017143,0.987886,2.427531,2.406579,0.007799,-1.147748,1.002344,-0.765449,-1.593227,0.175360,-1.698981,0.000029,0.632447,0.699232,-0.632447,-0.699232,0.632417,0.699211,0.223734,-0.905707,0.229673,0.453289,0.228158,1.446916,1.080934,1.054368,0.582025,0.898478,-0.037969,0.693003,1.240024,2.046899,0.242125,-1.547578,1.083343,-1.427828,-2.268245,-0.112180,1.818388,2.223573,-0.368319,0.042893,1.324393,1.065936,0.299508,-0.903631,1.228963,1.153313,-2.497904,0.767873,-0.767873,0.002886,1.000585
2386,-0.012379,-0.009706,0.019376,0.017296,-0.029451,-0.026252,-0.170277,-0.115615,-0.128880,0.036168,-0.029989,-0.024179,0.042035,0.042899,-0.029584,-0.022925,-0.00658,-0.008080,-0.023965,-0.024198,-0.024198,-0.022702,-0.031614,-0.003876,-0.047253,-0.003876,0.015561,-0.002719,0.014812,-0.132767,-0.155516,-0.006349,0.000285,-0.014857,0.017131,0.067746,-0.054334,-0.004662,-0.129792,0.016255,0.081900,0.035478,0.132922,-0.024217,0.029467,0.000029,-0.022339,-0.018436,0.022339,0.018436,-0.022383,-0.018489,-0.025225,-0.009476,-0.019676,0.018504,0.010865,0.029961,0.002373,0.004146,-0.029962,-0.034884,-0.037969,-0.027198,-0.027628,-0.034476,0.011757,0.053359,-0.022729,-0.024232,-0.034710,-0.003680,-0.041642,-0.055083,0.009755,0.042893,-0.009571,0.018601,-0.014416,0.020952,0.037745,-0.000575,0.080677,-0.020983,0.020983,0.002886,1.000585
8109,-0.310602,-0.362993,0.036676,-0.020266,-0.326115,-0.342126,0.625443,-0.625227,0.353187,-0.510882,-0.006062,-0.803062,1.249406,1.196309,0.011722,-0.081526,-0.00658,0.112723,0.215332,0.291702,0.291403,0.209127,-0.296581,-0.003876,-0.601570,-0.003876,-0.075504,0.084962,-0.175634,0.535660,0.753957,-0.176839,-0.668836,-0.712355,0.231635,0.429230,-0.007507,0.229264,0.443506,-0.879132,0.746665,1.184635,0.634062,-0.180408,0.497390,1.671931,-0.022339,-0.018436,0.022339,0.018436,-0.022383,-0.018489,-0.025225,-0.009476,-0.019676,0.018504,0.010865,0.029961,0.002373,0.004146,-0.029962,-0.034884,-0.037969,-0.027198,-0.027628,-0.034476,0.011757,0.053359,-0.022729,-0.024232,-0.034710,-0.003680,-0.041642,-0.055083,0.009755,0.042893,-0.009571,0.018601,-0.014416,0.020952,0.037745,-0.000575,0.080677,-0.020983,0.020983,0.002886,-0.999416
9743,-0.409389,-0.383501,-0.060396,0.109756,-0.334037,-0.486209,0.994087,0.385643,0.772375,-0.263635,-0.231959,-0.190512,-0.036053,-0.009056,-0.466732,-0.383149,-0.00658,0.006132,0.446749,0.337043,0.336744,0.721591,0.056708,0.424233,0.379883,0.424233,0.334291,0.711253,-0.228311,-0.642045,-0.019774,-0.953360,0.280884,0.121240,0.399791,0.166332,0.413942,0.409208,1.131464,-0.207592,0.439851,0.314062,-0.089807,0.192714,0.526038,0.835980,0.031014,0.279750,-0.031014,-0.279750,0.030971,0.279710,0.117037,-0.643019,0.245257,-0.077149,-0.039113,0.063698,1.074461,1.135154,0.715407,0.520088,0.426899,-1.467600,0.045647,0.097586,0.357308,0.053359,0.315491,1.535320,-0.194249,1.712605,-1.157660,-1.194411,-0.002106,-0.089430,0.298267,0.179729,0.299508,-1.273464,1.030426,1.297549,0.352107,0.189379,-0.189379,-1.626716,1.000585
4546,-0.467169,-0.596032,0.630636,0.387137,-1.018917,-0.959097,-0.415686,-1.155725,-0.803074,-0.440411,-0.371296,-0.920614,0.434960,0.375414,-0.800618,-0.669260,-0.00658,0.084299,0.152053,0.354139,0.353840,0.367746,-0.744241,0.138827,-0.677159,0.138827,-0.371468,0.247797,-0.655802,-0.673874,-0.359130,-0.602350,0.647821,0.852763,-0.604374,1.152197,0.296873,0.859066,-0.519635,0.329640,-0.378322,0.453353,-0.730152,-0.206440,1.041707,-0.417947,-0.439462,-0.564268,0.439462,0.564268,-0.439514,-0.564344,0.797863,-1.801938,-0.487205,0.079374,0.041286,0.198646,1.866957,1.862231,-0.673333,-0.303961,-0.037969,-2.908003,-0.599170,-0.599926,-1.831182,-1.707672,-0.754017,-0.336142,-0.194249,-0.329182,1.818388,2.375483,-1.220404,1.366118,-0.009571,0.824243,-0.432982,-1.088548,1.626035,1.730257,-1.276471,-0.757249,0.757249,-1.626716,1.000585
4962,-0.389818,-0.352740,-0.339115,-0.285125,-0.055860,-0.073356,-0.408249,-0.988639,-0.031069,-1.190514,0.422507,-0.529573,0.974376,1.019661,0.180386,-0.133232,-0.00658,-0.072035,0.185996,0.138584,0.138880,0.209127,-0.315939,0.138827,-0.050853,0.138827,0.789620,0.736304,0.164738,0.408340,0.197413,0.005113,-2.114999,-2.294486,0.609875,0.232057,0.367114,0.409208,0.145391,-0.162823,-0.480593,1.010520,0.689744,-0.137022,0.153610,-0.417947,-0.266065,-0.237021,0.266065,0.237021,-0.266114,-0.233293,0.546364,-0.026860,0.366036,-0.398891,0.345497,0.055264,0.781165,0.808643,0.001422,-0.091642,0.194465,-0.207248,-0.249284,0.157572,0.098145,0.293500,-0.022729,0.092734,0.005174,0.085094,-0.715903,-0.890591,0.107523,0.472941,0.195655,0.441563,0.482631,-0.996089,-0.408962,0.828782,0.827109,-0.283935,0.283935,0.002886,-0.999416
5706,-0.235114,-0.458073,-0.062318,0.005739,-0.168540,-0.462195,-0.430559,1.448727,-0.052028,-2.189059,-0.509227,-1.382825,-2.012811,-2.118446,-0.681865,-0.703732,-0.00658,0.134041,-0.915691,-0.831042,-0.830964,-0.571771,-0.144134,0.281530,-0.052652,0.281530,-0.280402,0.022333,-0.280987,-1.374131,-1.200732,-0.506359,-0.733589,-0.797416,0.114238,-0.556635,0.390528,-0.004662,-0.473771,-1.774519,0.439851,-2.193190,-0.535265,-0.883267,0.449642,0.000029,-0.468564,-0.341892,0.468564,0.341892,-0.468616,-0.341959,-0.848314,0.175951,-0.144350,-2.877169,2.909561,0.029961,-0.644129,-0.561358,-0.422261,-0.791663,-2.362311,-0.027198,-0.115558,-0.239080,1.163594,1.013922,0.562301,-2.831425,-1.789630,-1.532554,-0.785654,-0.206994,-1.424832,0.572183,0.195655,0.501986,-0.014416,-0.718714,2.023108,-0.865991,-0.190752,-0.336525,0.336525,-1.626716,-0.999416

In [9]:
y_test = df_test.spread_a
p(y_test)

(3080,)

2583    0.527325
9370    1.112200
5655   -0.057549
7258   -0.349986
2386   -0.715532
8109    0.161779
9743    1.770183
4546    0.454216
4962    0.746653
5706    0.381107
Name: spread_a, dtype: float64

## 5.6 RF Model

In [10]:

#Code task 22#
#Define a pipeline comprising the steps:
#SimpleImputer() with a strategy of 'median'
#StandardScaler(),
#and then RandomForestRegressor() with a random state of 47
RF_pipe = make_pipeline(
    #StandardScaler(),
    RandomForestRegressor(random_state=rs2909)
)

In [11]:
rf_default_cv_results = cross_validate(RF_pipe, X_train, y_train, cv=5)

In [12]:
rf_cv_scores = rf_default_cv_results['test_score']
rf_cv_scores

array([0.14191887, 0.15810184, 0.15355164, 0.14914375, 0.13823307])

In [13]:
np.mean(rf_cv_scores), np.std(rf_cv_scores)

(0.14818983635764027, 0.007298887983183603)

In [14]:
start_time = time.time()

In [15]:
n_est = [int(n) for n in np.logspace(start=1, stop=3, num=20)]
grid_params = {
        'randomforestregressor__n_estimators': n_est,
        #'standardscaler': [StandardScaler(), None],
        #'simpleimputer__strategy': ['mean', 'median']
}
grid_params

{'randomforestregressor__n_estimators': [10,
  12,
  16,
  20,
  26,
  33,
  42,
  54,
  69,
  88,
  112,
  143,
  183,
  233,
  297,
  379,
  483,
  615,
  784,
  1000]}

In [16]:
print("--- %s seconds ---" % (time.time() - start_time))

--- 0.0329129695892334 seconds ---

In [17]:
start_time = time.time()

In [18]:
rf_grid_cv = GridSearchCV(RF_pipe, param_grid=grid_params, cv=5, n_jobs=-1)

In [19]:
print("--- %s seconds ---" % (time.time() - start_time))

--- 0.03391075134277344 seconds ---

In [20]:
start_time = time.time()

In [21]:
rf_grid_cv.fit(X_train, y_train)

GridSearchCV(cv=5, error_score=nan,
             estimator=Pipeline(memory=None,
                                steps=[('randomforestregressor',
                                        RandomForestRegressor(bootstrap=True,
                                                              ccp_alpha=0.0,
                                                              criterion='mse',
                                                              max_depth=None,
                                                              max_features='auto',
                                                              max_leaf_nodes=None,
                                                              max_samples=None,
                                                              min_impurity_decrease=0.0,
                                                              min_impurity_split=None,
                                                              min_samples_leaf=1,
                                                              min_samples_split=2,
                                                              min_weight_fraction_leaf=0.0,
                                                              n_estimators=100,
                                                              n_jobs=None,
                                                              oob_score=False,
                                                              random_state=2909,
                                                              verbose=0,
                                                              warm_start=False))],
                                verbose=False),
             iid='deprecated', n_jobs=-1,
             param_grid={'randomforestregressor__n_estimators': [10, 12, 16, 20,
                                                                 26, 33, 42, 54,
                                                                 69, 88, 112,
                                                                 143, 183, 233,
                                                                 297, 379, 483,
                                                                 615, 784,
                                                                 1000]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [22]:
print("--- %s seconds ---" % (time.time() - start_time))

--- 1416.2506625652313 seconds ---

In [31]:
1416 / 60

23.6

In [23]:
rf_grid_cv.best_params_

{'randomforestregressor__n_estimators': 1000}

In [24]:
start_time = time.time()

In [25]:
rf_best_cv_results = cross_validate(rf_grid_cv.best_estimator_, X_train, y_train, cv=5)
rf_best_scores = rf_best_cv_results['test_score']
rf_best_scores

array([0.15138007, 0.16280553, 0.16487388, 0.16750328, 0.1469421 ])

<font color='red'> ?????????</font>

In [26]:
print("--- %s seconds ---" % (time.time() - start_time))

--- 1182.3001058101654 seconds ---

In [27]:
np.mean(rf_best_scores), np.std(rf_best_scores)

(0.15870097316767975, 0.008053563783215421)

In [28]:
start_time = time.time()

In [1]:
plt.subplots(figsize=(10, 5))
imps = rf_grid_cv.best_estimator_.named_steps.randomforestregressor.feature_importances_
rf_feat_imps = pd.Series(imps, index=X_train.columns).sort_values(ascending=False)
rf_feat_imps.plot(kind='bar')
plt.xlabel('features')
plt.ylabel('importance')
plt.title('Best random forest regressor feature importances');

NameError: name 'plt' is not defined

In [30]:
print("--- %s seconds ---" % (time.time() - start_time))

--- 1.5200610160827637 seconds ---

<font color='red'> add max of stat features?????</font>

This next step requires some careful thought. We want to refit the model using all available data. But should we include Big Mountain data? On the one hand, we are _not_ trying to estimate model performance on a previously unseen data sample, so theoretically including Big Mountain data should be fine. One might first think that including Big Mountain in the model training would, if anything, improve model performance in predicting Big Mountain's ticket price. But here's where our business context comes in. The motivation for this entire project is based on the sense that Big Mountain needs to adjust its pricing. One way to phrase this problem: we want to train a model to predict Big Mountain's ticket price based on data from _all the other_ resorts! We don't want Big Mountain's current price to bias this. We want to calculate a price based only on its competitors.

In [ ]:
X = ski_data.loc[ski_data.Name != "Big Mountain Resort", model.X_columns]
y = ski_data.loc[ski_data.Name != "Big Mountain Resort", 'AdultWeekend']

In [ ]:
len(X), len(y)

In [ ]:
model.fit(X, y)

In [ ]:
cv_results = cross_validate(model, X, y, scoring='neg_mean_absolute_error', cv=5, n_jobs=-1)

In [ ]:
cv_results['test_score']

<font color='red'> why is there is such large numbers in this test_score? what does it mean? I thought we'd get smaller numbers like in RF_pipe of '04_preprocessing_and_training'<font>

In [ ]:
mae_mean, mae_std = np.mean(-1 * cv_results['test_score']), np.std(-1 * cv_results['test_score'])
mae_mean, mae_std

These numbers will inevitably be different to those in the previous step that used a different training data set. They should, however, be consistent. It's important to appreciate that estimates of model performance are subject to the noise and uncertainty of data!

## 5.7 Calculate Expected Big Mountain Ticket Price From The Model<a id='5.7_Calculate_Expected_Big_Mountain_Ticket_Price_From_The_Model'></a>

In [ ]:
X_bm = ski_data.loc[ski_data.Name == "Big Mountain Resort", model.X_columns]
y_bm = ski_data.loc[ski_data.Name == "Big Mountain Resort", 'AdultWeekend']

In [ ]:
bm_pred = model.predict(X_bm).item()

In [ ]:
y_bm = y_bm.values.item()

In [ ]:
print(f'Big Mountain Resort modelled price is ${bm_pred:.2f}, actual price is ${y_bm:.2f}.')
print(f'Even with the expected mean absolute error of ${mae_mean:.2f}, this suggests there is room for an increase.')

This result should be looked at optimistically and doubtfully! The validity of our model lies in the assumption that other resorts accurately set their prices according to what the market (the ticket-buying public) supports. The fact that our resort seems to be charging that much less that what's predicted suggests our resort might be undercharging. 
But if ours is mispricing itself, are others? It's reasonable to expect that some resorts will be "overpriced" and some "underpriced." Or if resorts are pretty good at pricing strategies, it could be that our model is simply lacking some key data? Certainly we know nothing about operating costs, for example, and they would surely help.

## 5.8 Big Mountain Resort In Market Context<a id='5.8_Big_Mountain_Resort_In_Market_Context'></a>

Features that came up as important in the modeling (not just our final, random forest model) included:
* vertical_drop
* Snow Making_ac
* total_chairs
* fastQuads
* Runs
* LongestRun_mi
* trams
* SkiableTerrain_ac

A handy glossary of skiing terms can be found on the [ski.com](https://www.ski.com/ski-glossary) site. Some potentially relevant contextual information is that vertical drop, although nominally the height difference from the summit to the base, is generally taken from the highest [_lift-served_](http://verticalfeet.com/) point.

It's often useful to define custom functions for visualizing data in meaningful ways. The function below takes a feature name as an input and plots a histogram of the values of that feature. It then marks where Big Mountain sits in the distribution by marking Big Mountain's value with a vertical line using `matplotlib`'s [axvline](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.axvline.html) function. It also performs a little cleaning up of missing values and adds descriptive labels and a title.

In [ ]:
#Code task 1#
#Add code to the `plot_compare` function that displays a vertical, dashed line
#on the histogram to indicate Big Mountain's position in the distribution
#Hint: plt.axvline() plots a vertical line, its position for 'feature1'
#would be `big_mountain['feature1'].values, we'd like a red line, which can be
#specified with c='r', a dashed linestyle is produced by ls='--',
#and it's nice to give it a slightly reduced alpha value, such as 0.8.
#Don't forget to give it a useful label (e.g. 'Big Mountain') so it's listed
#in the legend.
def plot_compare(feat_name, description, state=None, figsize=(10, 5)):
    """Graphically compare distributions of features.
    
    Plot histogram of values for all resorts and reference line to mark
    Big Mountain's position.
    
    Arguments:
    feat_name - the feature column name in the data
    description - text description of the feature
    state - select a specific state (None for all states)
    figsize - (optional) figure size
    """
    
    plt.subplots(figsize=figsize)
    # quirk that hist sometimes objects to NaNs, sometimes doesn't
    # filtering only for finite values tidies this up
    if state is None:
        ski_x = ski_data[feat_name]
    else:
        ski_x = ski_data.loc[ski_data.state == state, feat_name]
    ski_x = ski_x[np.isfinite(ski_x)]
    plt.hist(ski_x, bins=30)
    plt.axvline(x=big_mountain[feat_name].values, c='r', ls='--', alpha=0.8, label='Big Mountain')
    plt.xlabel(description)
    plt.ylabel('frequency')
    plt.title(description + ' distribution for resorts in market share')
    plt.legend()

### 5.8.1 Ticket price<a id='5.8.1_Ticket_price'></a>

Look at where Big Mountain sits overall amongst all resorts for price and for just other resorts in Montana.

In [ ]:
plot_compare('AdultWeekend', 'Adult weekend ticket price ($)')

In [ ]:
plot_compare('AdultWeekend', 'Adult weekend ticket price ($) - Montana only', state='Montana')

### 5.8.2 Vertical drop<a id='5.8.2_Vertical_drop'></a>

In [ ]:
plot_compare('vertical_drop', 'Vertical drop (feet)')

Big Mountain is doing well for vertical drop, but there are still quite a few resorts with a greater drop.

<font color='red'>Big Mountain percentile for vertical drop???????????????<font>

In [ ]:
1 - ski_data[ski_data['vertical_drop'] >= 2353][['Name','vertical_drop']].count() / ski_data['vertical_drop'].count()
#ski_data[['Name','vertical_drop']]

### 5.8.3 Snow making area<a id='5.8.3_Snow_making_area'></a>

In [ ]:
plot_compare('Snow Making_ac', 'Area covered by snow makers (acres)')

Big Mountain is very high up the league table of snow making area.

### 5.8.4 Total number of chairs<a id='5.8.4_Total_number_of_chairs'></a>

In [ ]:
plot_compare('total_chairs', 'Total number of chairs')

Big Mountain has amongst the highest number of total chairs, resorts with more appear to be outliers.

<font color='red'> how were total number of chairs counted????? May the counting method be reason for some of these outliers??????????????????<font>

In [ ]:
ski_data[ski_data['total_chairs'] > 35 ]['AdultWeekend']

In [ ]:
ski_data[ski_data['total_chairs'] > 35 ]

### 5.8.5 Fast quads<a id='5.8.5_Fast_quads'></a>

In [ ]:
plot_compare('fastQuads', 'Number of fast quads')

Most resorts have no fast quads. Big Mountain has 3, which puts it high up that league table. There are some values  much higher, but they are rare.

<font color='red'>league table??????????????<font>

### 5.8.6 Runs<a id='5.8.6_Runs'></a>

In [ ]:
plot_compare('Runs', 'Total number of runs')

Big Mountain compares well for the number of runs. There are some resorts with more, but not many.

### 5.8.7 Longest run<a id='5.8.7_Longest_run'></a>

In [ ]:
plot_compare('LongestRun_mi', 'Longest run length (miles)')

Big Mountain has one of the longest runs. Although it is just over half the length of the longest, the longer ones are rare.

### 5.8.8 Trams<a id='5.8.8_Trams'></a>

In [ ]:
plot_compare('trams', 'Number of trams')

The vast majority of resorts, such as Big Mountain, have no trams.

### 5.8.9 Skiable terrain area<a id='5.8.9_Skiable_terrain_area'></a>

In [ ]:
plot_compare('SkiableTerrain_ac', 'Skiable terrain area (acres)')

Big Mountain is amongst the resorts with the largest amount of skiable terrain.

<font color='red'>percentile????????????<font>

In [ ]:
X_bm['SkiableTerrain_ac']

In [ ]:
1 - ski_data[ski_data['SkiableTerrain_ac'] >= 3000][['Name','SkiableTerrain_ac']].count() / ski_data['SkiableTerrain_ac'].count()

## 5.9 Modeling scenarios<a id='5.9_Modeling_scenarios'></a>

Big Mountain Resort has been reviewing potential scenarios for either cutting costs or increasing revenue (from ticket prices). Ticket price is not determined by any set of parameters; the resort is free to set whatever price it likes. However, the resort operates within a market where people pay more for certain facilities, and less for others. Being able to sense how facilities support a given ticket price is valuable business intelligence. This is where the utility of our model comes in.

The business has shortlisted some options:
1. Permanently closing down up to 10 of the least used runs. This doesn't impact any other resort statistics.
2. Increase the vertical drop by adding a run to a point 150 feet lower down but requiring the installation of an additional chair lift to bring skiers back up, without additional snow making coverage
3. Same as number 2, but adding 2 acres of snow making cover
4. Increase the longest run by 0.2 mile to boast 3.5 miles length, requiring an additional snow making coverage of 4 acres

The expected number of visitors over the season is 350,000 and, on average, visitors ski for five days. Assume the provided data includes the additional lift that Big Mountain recently installed.

<font color='red'>facilities support a given ticket price?????
    
    
how do we know 1?????????
    
    
    
    
<font>

In [ ]:
expected_visitors = 350_000

In [ ]:
all_feats = ['vertical_drop', 'Snow Making_ac', 'total_chairs', 'fastQuads', 
             'Runs', 'LongestRun_mi', 'trams', 'SkiableTerrain_ac']
big_mountain[all_feats]

In [ ]:
#Code task 2#
#In this function, copy the Big Mountain data into a new data frame
#(Note we use .copy()!)
#And then for each feature, and each of its deltas (changes from the original),
#create the modified scenario dataframe (bm2) and make a ticket price prediction
#for it. The difference between the scenario's prediction and the current
#prediction is then calculated and returned.
#Complete the code to increment each feature by the associated delta
def predict_increase(features, deltas):
    """Increase in modelled ticket price by applying delta to feature.
    
    Arguments:
    features - list, names of the features in the ski_data dataframe to change
    deltas - list, the amounts by which to increase the values of the features
    
    Outputs:
    Amount of increase in the predicted ticket price
    """
    
    bm2 = X_bm.copy()
    for f, d in zip(features, deltas):
        bm2[f] += d
    return model.predict(bm2).item() - model.predict(X_bm).item()

### 5.9.1 Scenario 1<a id='5.9.1_Scenario_1'></a>

Close up to 10 of the least used runs. The number of runs is the only parameter varying.

In [ ]:
[i for i in range(-1, -11, -1)]

In [ ]:
runs_delta = [i for i in range(-1, -11, -1)]
price_deltas = [predict_increase(['Runs'], [delta]) for delta in runs_delta]

In [ ]:
price_deltas

In [ ]:
#Code task 3#
#Create two plots, side by side, for the predicted ticket price change (delta) for each
#condition (number of runs closed) in the scenario and the associated predicted revenue
#change on the assumption that each of the expected visitors buys 5 tickets
#There are two things to do here:
#1 - use a list comprehension to create a list of the number of runs closed from `runs_delta`
#2 - use a list comprehension to create a list of predicted revenue changes from `price_deltas`
runs_closed = [-1 * rc for rc in runs_delta] #1
fig, ax = plt.subplots(1, 2, figsize=(10, 5))
fig.subplots_adjust(wspace=0.5)
ax[0].plot(runs_closed, price_deltas, 'o-')
ax[0].set(xlabel='Runs closed', ylabel='Change ($)', title='Ticket price')
revenue_deltas = [5 * expected_visitors * pd for pd in price_deltas] #2
ax[1].plot(runs_closed, revenue_deltas, 'o-')
ax[1].set(xlabel='Runs closed', ylabel='Change ($)', title='Revenue');

The model says closing one run makes no difference. Closing 2 and 3 successively reduces support for ticket price and so revenue. If Big Mountain closes down 3 runs, it seems they may as well close down 4 or 5 as there's no further loss in ticket price. Increasing the closures down to 6 or more leads to a large drop.

### 5.9.2 Scenario 2<a id='5.9.2_Scenario_2'></a>

In this scenario, Big Mountain is adding a run, increasing the vertical drop by 150 feet, and installing an additional chair lift.

In [ ]:
#Code task 4#
#Call `predict_increase` with a list of the features 'Runs', 'vertical_drop', and 'total_chairs'
#and associated deltas of 1, 150, and 1
ticket2_increase = predict_increase(['Runs', 'vertical_drop', 'total_chairs'], [1, 150, 1])
revenue2_increase = 5 * expected_visitors * ticket2_increase

In [ ]:
print(f'This scenario increases support for ticket price by ${ticket2_increase:.2f}')
print(f'Over the season, this could be expected to amount to ${revenue2_increase:.0f}')

<font color='red'> not getting the $1.99 and ~3.5 mil as preshown output suggested??????????? different model used????<font>

### 5.9.3 Scenario 3<a id='5.9.3_Scenario_3'></a>

In this scenario, you are repeating the previous one but adding 2 acres of snow making.

In [ ]:
#Code task 5#
#Repeat scenario 2 conditions, but add an increase of 2 to `Snow Making_ac`
ticket3_increase = predict_increase(['Runs', 'vertical_drop', 'total_chairs', 'Snow Making_ac'], [1, 150, 1, 2])
revenue3_increase = 5 * expected_visitors * ticket3_increase

In [ ]:
print(f'This scenario increases support for ticket price by ${ticket3_increase:.2f}')
print(f'Over the season, this could be expected to amount to ${revenue3_increase:.0f}')

Such a small increase in the snow making area makes no difference!

In [ ]:
print(f'percentage profit: {(revenue3_increase - 1500000) / 1500000 * 100}')

### 5.9.4 Scenario 4<a id='5.9.4_Scenario_4'></a>

This scenario calls for increasing the longest run by .2 miles and guaranteeing its snow coverage by adding 4 acres of snow making capability.

In [ ]:
#Code task 6#
#Predict the increase from adding 0.2 miles to `LongestRun_mi` and 4 to `Snow Making_ac`
predict_increase(['LongestRun_mi', 'Snow Making_ac'], [.2, 4])

No difference whatsoever. Although the longest run feature was used in the linear model, the random forest model (the one we chose because of its better performance) only has longest run way down in the feature importance list.

## 5.10 Summary<a id='5.10_Summary'></a>

**Q: 1** Write a summary of the results of modeling these scenarios. Start by starting the current position; how much does Big Mountain currently charge? What does your modelling suggest for a ticket price that could be supported in the marketplace by Big Mountain's facilities? How would you approach suggesting such a change to the business leadership? Discuss the additional operating cost of the new chair lift per ticket (on the basis of each visitor on average buying 5 day tickets) in the context of raising prices to cover this. For future improvements, state which, if any, of the modeled scenarios you'd recommend for further consideration. Suggest how the business might test, and progress, with any run closures.

**Q: 1** Write a summary of the results of modeling these scenarios. Start by starting the current position; how much does Big Mountain currently charge? What does your modelling suggest for a ticket price that could be supported in the marketplace by Big Mountain's facilities? How would you approach suggesting such a change to the business leadership? Discuss the additional operating cost of the new chair lift per ticket (on the basis of each visitor on average buying 5 day tickets) in the context of raising prices to cover this. For future improvements, state which, if any, of the modeled scenarios you'd recommend for further consideration. Suggest how the business might test, and progress, with any run closures.

**A: 1** Your answer here

Start by starting the current position; how much does Big Mountain currently charge?
<br>-Big Mountain Resort currently charges an 'AdultWeekend' ticket price of $81.00. 

What does your modelling suggest for a ticket price that could be supported in the marketplace by Big Mountain's facilities?
<br>-The modelling suggests 'AdultWeekend' ticket price could be $96.75.

How would you approach suggesting such a change to the business leadership? Discuss the additional operating cost of the new chair lift per ticket (on the basis of each visitor on average buying 5 day tickets) in the context of raising prices to cover this.
<br>-I would approach suggesting a change to the business leadership by speaking about what the data has presented as possible solutions.
<br>-The additional operating cost of adding a chairlift to Big Mountain Resort can be offset by raising the average ticket price for each visitor. -In our ?analysis?, we assume 350,000 visitor per season, each buying an average of 5 day tickets at 81 dollars and therefore a 1.00 dollar increase would yield a 1.75 million dollar income increase.

<br>-Our model shows it would be market competitive (national) to raise the ticket price to by an average of 1.10 dollar. This would yield an annual income increase of 1,927,536 dollars and cover the additional $1,540,000 operating cost for this seasonal.

<br>-Because of Big Mountain's high rank among ticket price predictive categories (i.e. amount of facilities offered), we believe this $1.10 average increase in ticket price is justified given the trend for ticket prices nationally.

For future improvements, state which, if any, of the modeled scenarios you'd recommend for further consideration.
<br>-For future improvements, I would suggest to look more into the scenario of adding another lift while increasing the 'vertical_drop' and increasing the number of 'Runs' at a steady rate.

Suggest how the business might test, and progress, with any run closures.
<br>-Our modeling suggests a small shutdown in number of runs, e.g. 1, should not mean a decrease ticket prices, while the closer of more than that will in stages. We recommend to not to close more than 1 if we are to maximize profits or minimize shutdowns to 3-5 or less.

## 5.11 Further work<a id='5.11_Further_work'></a>

**Q: 2** What next? Highlight any deficiencies in the data that hampered or limited this work. The only price data in our dataset were ticket prices. You were provided with information about the additional operating cost of the new chair lift, but what other cost information would be useful? Big Mountain was already fairly high on some of the league charts of facilities offered, but why was its modeled price so much higher than its current price? Would this mismatch come as a surprise to the business executives? How would you find out? Assuming the business leaders felt this model was useful, how would the business make use of it? Would you expect them to come to you every time they wanted to test a new combination of parameters in a scenario? We hope you would have better things to do, so how might this model be made available for business analysts to use and explore?

**A: 2** Your answer here

**Q: 2** What next? Highlight any deficiencies in the data that hampered or limited this work. The only price data in our dataset were ticket prices. You were provided with information about the additional operating cost of the new chair lift, but what other cost information would be useful? Big Mountain was already fairly high on some of the league charts of facilities offered, but why was its modeled price so much higher than its current price? Would this mismatch come as a surprise to the business executives? How would you find out? Assuming the business leaders felt this model was useful, how would the business make use of it? Would you expect them to come to you every time they wanted to test a new combination of parameters in a scenario? We hope you would have better things to do, so how might this model be made available for business analysts to use and explore?

What next? Highlight any deficiencies in the data that hampered or limited this work. The only price data in our dataset were ticket prices.
<br>-One of the deficiencies in the data included knowing we have 350,000 visitors per season, but not knowing the precise behavior of visitor purchaser behavior like number of day tickets purchased and therefore making an assumption (of 5) on the average number of day tickets purchased per season per vistor.v

You were provided with information about the additional operating cost of the new chair lift, but what other cost information would be useful?
<br>-It would be useful to have information about the location of the this new chair lift in addition to its operating cost. Information of interest about the chair lift per se include speed of chair lift and number of chairs of the chair lift. Other information of interest include elevation spanned by the chairlift and number of runs the chair lift would add to Big Mountain Resort.
<br>-Also, it would be useful to have information about the number of tickets each person purchased each season.


Big Mountain was already fairly high on some of the league charts of facilities offered, but why was its modeled price so much higher than its current price?
<br>-Big Mountain's model price was higher than it's current price maybe because the state of Montana charges less for vistor day ticket.

Would this mismatch come as a surprise to the business executives? 
<br>-Maybe

How would you find out?
<br>-by asking

Assuming the business leaders felt this model was useful, how would the business make use of it? 
<br>-They could look into increasing vertical_drop, Snow Making_ac, total_chairs, fastQuads, Runs, LongestRun_mi, trams, and/or SkiableTerrain_ac and see if it would be the desireable and profitable to take on that scenario using our model.

Would you expect them to come to you every time they wanted to test a new combination of parameters in a scenario?
<br>-Maybe

We hope you would have better things to do, so how might this model be made available for business analysts to use and explore?
<br>-This model can be used and shared via github or other software for business analysts to use and explored.