In [1]:
!pip install ipython-autotime

Requirement already satisfied: ipython-autotime in /opt/anaconda3/lib/python3.8/site-packages (0.3.1)
Requirement already satisfied: ipython in /opt/anaconda3/lib/python3.8/site-packages (from ipython-autotime) (7.19.0)
Requirement already satisfied: pickleshare in /opt/anaconda3/lib/python3.8/site-packages (from ipython->ipython-autotime) (0.7.5)
Requirement already satisfied: decorator in /opt/anaconda3/lib/python3.8/site-packages (from ipython->ipython-autotime) (4.4.2)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /opt/anaconda3/lib/python3.8/site-packages (from ipython->ipython-autotime) (3.0.8)
Requirement already satisfied: jedi>=0.10 in /opt/anaconda3/lib/python3.8/site-packages (from ipython->ipython-autotime) (0.17.1)
Requirement already satisfied: backcall in /opt/anaconda3/lib/python3.8/site-packages (from ipython->ipython-autotime) (0.2.0)
Requirement already satisfied: setuptools>=18.5 in /opt/anaconda3/lib/python3.8/site-packages (from ipython->ipython-autotime) (57.4.0)
Requirement already satisfied: pexpect>4.3 in /opt/anaconda3/lib/python3.8/site-packages (from ipython->ipython-autotime) (4.8.0)
Requirement already satisfied: appnope in /opt/anaconda3/lib/python3.8/site-packages (from ipython->ipython-autotime) (0.1.0)
Requirement already satisfied: traitlets>=4.2 in /opt/anaconda3/lib/python3.8/site-packages (from ipython->ipython-autotime) (5.0.5)
Requirement already satisfied: pygments in /opt/anaconda3/lib/python3.8/site-packages (from ipython->ipython-autotime) (2.7.2)
Requirement already satisfied: parso<0.8.0,>=0.7.0 in /opt/anaconda3/lib/python3.8/site-packages (from jedi>=0.10->ipython->ipython-autotime) (0.7.0)
Requirement already satisfied: ptyprocess>=0.5 in /opt/anaconda3/lib/python3.8/site-packages (from pexpect>4.3->ipython->ipython-autotime) (0.6.0)
Requirement already satisfied: wcwidth in /opt/anaconda3/lib/python3.8/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython->ipython-autotime) (0.2.5)
Requirement already satisfied: ipython-genutils in /opt/anaconda3/lib/python3.8/site-packages (from traitlets>=4.2->ipython->ipython-autotime) (0.2.0)

In [2]:
%load_ext autotime

time: 288 µs (started: 2021-08-20 04:02:22 -07:00)

## 4.3 Imports<a id='4.3_Imports'></a>

In [3]:
import pandas as pd
import numpy as np
import os
import pickle
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import __version__ as sklearn_version
from sklearn.decomposition import PCA
from sklearn.preprocessing import scale
from sklearn.model_selection import train_test_split, cross_validate, GridSearchCV, learning_curve
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.dummy import DummyRegressor
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.feature_selection import SelectKBest, f_regression
import datetime

time: 1.17 s (started: 2021-08-20 04:02:22 -07:00)

In [4]:
#return the first 5 and last 5 rows of this dataframe
def p(df_):
    if df_.shape[0] > 6:
        print(df_.shape)
        return pd.concat([df_.head(), df_.tail()])
    else:
        return df_

def rcp(file_, pd_=None, ic_=None):
    if (pd_ == None) and (ic_ == None):
        return pd.read_csv(os.path.join('..', 'processed_data', file_))
    elif (pd_ != None) and (ic_ == None):
        return pd.read_csv(os.path.join('..', 'processed_data', file_), parse_dates=pd_)
    elif (pd_ != None) and (ic_ != None):
        return pd.read_csv(os.path.join('..', 'processed_data', file_), parse_dates=pd_, index_col = ic_)
    else:
        return pd.read_csv(os.path.join('..', 'processed_data', file_), index_col = ic_)
    
def rcr(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'raw_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'raw_data', file_), parse_dates=pd_)
    
#sort dataframe by column
def s(df_, column_):
    return df_.sort_values(column_)

#reset index and sort dataframe by column
def sr(df_, column_, ascending_=True):
    df_ = df_.sort_values(column_, ascending=ascending_)
    return df_.reset_index(drop=True)

#print length of list
def pl(list_):
    print(len(list_))
    return list_

#print length of dictionary
def pdc(dict_):
    print(len(dict_))
    return dict_

time: 845 µs (started: 2021-08-20 04:02:23 -07:00)

## 4.4 Load Data<a id='4.4_Load_Data'></a>

In [5]:
df_train = rcp('161_train_split.csv', None, 0)
p(df_train)

(7186, 853)

,away_home_a,losses_diff,wins_diff,win_pct_diff,opp_win_pct_diff,opp_losses_diff,opp_wins_diff,opp_opps_losses_diff,opp_opps_wins_diff,opp_opps_win_pct_diff,...,reb_cma_sm_cmax12_diff,ast_cma_sm_cmax12_diff,stl_cma_sm_cmax12_diff,blk_cma_sm_cmax12_diff,tov_cma_sm_cmax12_diff,pf_cma_sm_cmax12_diff,pts_cma_sm_cmax12_diff,spread_cma_sm_cmax12_diff,away_home_cma_sm_cmax12_diff,spread_a
3134,-0.999416,1.099997,-1.006300,-0.869106,0.869106,-1.099997,1.006300,-0.446871,-1.416010,-0.196035,...,0.681655,-1.529913,0.347225,1.073355,1.120699,0.670210,-0.018242,0.800259,-0.480626,11
8383,-0.999416,-1.376256,1.381831,1.147929,-1.147929,1.376256,-1.381831,-1.074563,1.622779,0.541892,...,0.822020,0.882326,-0.004867,-0.341903,-0.861733,-2.815468,-0.223585,-0.786289,-0.970517,-10
7423,-0.999416,-0.614332,0.617629,0.321641,-0.321641,0.614332,-0.617629,2.156205,-0.839025,-0.291209,...,-0.641787,-1.132292,-1.614433,-0.398513,-1.297868,0.016646,-0.037798,-0.714716,1.478941,22
2528,-0.999416,0.147592,-0.242098,-0.605934,0.605934,-0.147592,0.242098,0.125436,-0.031245,-0.757113,...,-0.020170,-0.124983,-0.004867,0.054369,0.010537,0.078890,-0.037798,0.024878,0.009266,10
10064,-0.999416,1.385719,-1.388401,-0.777675,0.777675,-1.385719,1.388401,2.137743,-0.781326,-0.260570,...,0.398060,-0.321900,-1.528206,-1.805683,0.520305,-0.774746,-0.624492,1.636988,-0.270672,4
3378,1.000585,1.004757,-0.910774,-0.595496,0.595496,-1.004757,0.910774,0.993128,-0.858258,-0.209483,...,-0.289963,-1.556421,0.280465,1.363611,-1.369957,-0.997370,0.808996,1.480208,0.855443,-5
1965,1.000585,-0.614332,0.426579,0.488491,-0.488491,0.614332,-0.426579,0.402359,0.468809,-0.000505,...,0.461081,-1.344357,-1.010846,0.733693,-2.209787,0.514600,-0.546266,-1.012939,0.499158,14
1161,-0.999416,0.528554,-0.528673,-0.300758,0.300758,-0.528554,0.528673,-0.188410,-0.569765,-0.042986,...,-1.403768,0.511212,-0.457557,-0.624954,-0.980679,-0.325698,-0.282254,0.287315,0.009266,-8
2771,-0.999416,0.433314,-0.528673,-0.729611,0.729611,-0.433314,0.528673,0.771590,-0.165875,-0.721090,...,1.062646,0.378671,-1.362938,0.507252,2.072266,0.234500,-1.103625,0.740614,0.499158,-4
9937,1.000585,-0.900053,0.904205,0.538977,-0.538977,0.900053,-0.904205,-0.059179,-1.185216,-0.131998,...,-0.842308,-1.476897,1.504101,-1.134447,-0.267004,0.514600,-1.005843,-0.237558,1.478941,-8

time: 1.05 s (started: 2021-08-20 04:02:23 -07:00)

In [6]:
df_test = rcp('161_test_split.csv', None, 0)
p(df_test)

(3080, 853)

,away_home_a,losses_diff,wins_diff,win_pct_diff,opp_win_pct_diff,opp_losses_diff,opp_wins_diff,opp_opps_losses_diff,opp_opps_wins_diff,opp_opps_win_pct_diff,...,reb_cma_sm_cmax12_diff,ast_cma_sm_cmax12_diff,stl_cma_sm_cmax12_diff,blk_cma_sm_cmax12_diff,tov_cma_sm_cmax12_diff,pf_cma_sm_cmax12_diff,pts_cma_sm_cmax12_diff,spread_cma_sm_cmax12_diff,away_home_cma_sm_cmax12_diff,spread_a
2583,1.000585,-0.328610,0.426579,1.350913,-1.350913,0.328610,-0.426579,0.070052,-0.031245,-0.273612,...,-0.020170,-0.124983,-0.004867,0.054369,0.010537,0.078890,-0.037798,0.024878,0.009266,7
9370,-0.999416,1.385719,-1.388401,-1.970642,1.970642,-1.385719,1.388401,0.771590,-0.762094,-0.970663,...,-1.463925,-2.033568,-0.407258,-2.889366,-1.734003,-3.033323,-2.384573,1.170055,1.968833,15
5655,-0.999416,1.385719,-1.770502,-1.539212,1.539212,-1.385719,1.770502,1.362359,-0.127410,-0.408668,...,-1.075642,0.684720,1.197735,-0.722736,0.140296,0.141134,0.169322,1.661311,-1.193195,-1
7258,1.000585,-2.614383,2.623659,1.681878,-1.681878,2.614383,-2.623659,-0.705333,-0.877491,-0.030213,...,1.944940,-0.177999,-0.859949,0.944695,-1.957478,-1.539461,0.079540,-2.623345,0.855443,-5
2386,1.000585,0.052352,-0.051047,-0.051521,0.051521,-0.052352,0.051047,0.014667,0.007220,-0.013957,...,-0.020170,-0.124983,-0.004867,0.054369,0.010537,0.078890,-0.037798,0.024878,0.009266,-10
8109,-0.999416,0.528554,-0.624199,-0.788287,0.788287,-0.528554,0.624199,0.014667,0.314946,0.153835,...,0.541290,0.670261,-0.105465,1.299796,1.120699,-0.263454,-0.164915,-0.523853,0.009266,2
9743,1.000585,-0.328610,0.331054,0.243728,-0.243728,0.328610,-0.331054,-1.499179,0.853465,0.406982,...,0.260560,1.465504,-1.564134,0.563862,1.398239,-0.885896,1.174702,-1.358878,0.009266,24
4546,1.000585,1.004757,-0.910774,-0.694836,0.694836,-1.004757,0.910774,-0.188410,0.103385,0.029099,...,0.681655,-0.310540,0.799916,-0.511734,0.407023,-0.450186,-0.380036,0.943406,0.499158,6
4962,-0.999416,0.623795,-0.624199,-0.319306,0.319306,-0.623795,0.624199,0.476205,-1.377545,-0.130825,...,0.922281,2.101699,-1.463536,2.375392,0.327726,0.203378,1.252928,-2.181974,2.458724,10
5706,-0.999416,0.242833,-0.146573,-0.192442,0.192442,-0.242833,0.146573,-0.114564,0.353411,0.091763,...,-0.461318,1.757094,-1.061144,0.054369,-3.438895,-1.134873,1.712504,-1.144157,0.989049,5

time: 531 ms (started: 2021-08-20 04:02:24 -07:00)

In [7]:
X_train = df_train.drop(columns = 'spread_a')
p(X_train)

(7186, 852)

,away_home_a,losses_diff,wins_diff,win_pct_diff,opp_win_pct_diff,opp_losses_diff,opp_wins_diff,opp_opps_losses_diff,opp_opps_wins_diff,opp_opps_win_pct_diff,...,dreb_cma_sm_cmax12_diff,reb_cma_sm_cmax12_diff,ast_cma_sm_cmax12_diff,stl_cma_sm_cmax12_diff,blk_cma_sm_cmax12_diff,tov_cma_sm_cmax12_diff,pf_cma_sm_cmax12_diff,pts_cma_sm_cmax12_diff,spread_cma_sm_cmax12_diff,away_home_cma_sm_cmax12_diff
3134,-0.999416,1.099997,-1.006300,-0.869106,0.869106,-1.099997,1.006300,-0.446871,-1.416010,-0.196035,...,0.130110,0.681655,-1.529913,0.347225,1.073355,1.120699,0.670210,-0.018242,0.800259,-0.480626
8383,-0.999416,-1.376256,1.381831,1.147929,-1.147929,1.376256,-1.381831,-1.074563,1.622779,0.541892,...,-0.585219,0.822020,0.882326,-0.004867,-0.341903,-0.861733,-2.815468,-0.223585,-0.786289,-0.970517
7423,-0.999416,-0.614332,0.617629,0.321641,-0.321641,0.614332,-0.617629,2.156205,-0.839025,-0.291209,...,-0.134827,-0.641787,-1.132292,-1.614433,-0.398513,-1.297868,0.016646,-0.037798,-0.714716,1.478941
2528,-0.999416,0.147592,-0.242098,-0.605934,0.605934,-0.147592,0.242098,0.125436,-0.031245,-0.757113,...,-0.055345,-0.020170,-0.124983,-0.004867,0.054369,0.010537,0.078890,-0.037798,0.024878,0.009266
10064,-0.999416,1.385719,-1.388401,-0.777675,0.777675,-1.385719,1.388401,2.137743,-0.781326,-0.260570,...,0.043060,0.398060,-0.321900,-1.528206,-1.805683,0.520305,-0.774746,-0.624492,1.636988,-0.270672
3378,1.000585,1.004757,-0.910774,-0.595496,0.595496,-1.004757,0.910774,0.993128,-0.858258,-0.209483,...,-1.305366,-0.289963,-1.556421,0.280465,1.363611,-1.369957,-0.997370,0.808996,1.480208,0.855443
1965,1.000585,-0.614332,0.426579,0.488491,-0.488491,0.614332,-0.426579,0.402359,0.468809,-0.000505,...,0.289072,0.461081,-1.344357,-1.010846,0.733693,-2.209787,0.514600,-0.546266,-1.012939,0.499158
1161,-0.999416,0.528554,-0.528673,-0.300758,0.300758,-0.528554,0.528673,-0.188410,-0.569765,-0.042986,...,-0.982624,-1.403768,0.511212,-0.457557,-0.624954,-0.980679,-0.325698,-0.282254,0.287315,0.009266
2771,-0.999416,0.433314,-0.528673,-0.729611,0.729611,-0.433314,0.528673,0.771590,-0.165875,-0.721090,...,0.474528,1.062646,0.378671,-1.362938,0.507252,2.072266,0.234500,-1.103625,0.740614,0.499158
9937,1.000585,-0.900053,0.904205,0.538977,-0.538977,0.900053,-0.904205,-0.059179,-1.185216,-0.131998,...,-0.744181,-0.842308,-1.476897,1.504101,-1.134447,-0.267004,0.514600,-1.005843,-0.237558,1.478941

time: 37.5 ms (started: 2021-08-20 04:02:25 -07:00)

In [8]:
y_train = df_train.spread_a
p(y_train)

(7186,)

3134     11
8383    -10
7423     22
2528     10
10064     4
3378     -5
1965     14
1161     -8
2771     -4
9937     -8
Name: spread_a, dtype: int64

time: 2.87 ms (started: 2021-08-20 04:02:25 -07:00)

In [9]:
X_test = df_test.drop(columns = 'spread_a')
p(X_test)

(3080, 852)

,away_home_a,losses_diff,wins_diff,win_pct_diff,opp_win_pct_diff,opp_losses_diff,opp_wins_diff,opp_opps_losses_diff,opp_opps_wins_diff,opp_opps_win_pct_diff,...,dreb_cma_sm_cmax12_diff,reb_cma_sm_cmax12_diff,ast_cma_sm_cmax12_diff,stl_cma_sm_cmax12_diff,blk_cma_sm_cmax12_diff,tov_cma_sm_cmax12_diff,pf_cma_sm_cmax12_diff,pts_cma_sm_cmax12_diff,spread_cma_sm_cmax12_diff,away_home_cma_sm_cmax12_diff
2583,1.000585,-0.328610,0.426579,1.350913,-1.350913,0.328610,-0.426579,0.070052,-0.031245,-0.273612,...,-0.055345,-0.020170,-0.124983,-0.004867,0.054369,0.010537,0.078890,-0.037798,0.024878,0.009266
9370,-0.999416,1.385719,-1.388401,-1.970642,1.970642,-1.385719,1.388401,0.771590,-0.762094,-0.970663,...,-1.538992,-1.463925,-2.033568,-0.407258,-2.889366,-1.734003,-3.033323,-2.384573,1.170055,1.968833
5655,-0.999416,1.385719,-1.770502,-1.539212,1.539212,-1.385719,1.770502,1.362359,-0.127410,-0.408668,...,-1.156038,-1.075642,0.684720,1.197735,-0.722736,0.140296,0.141134,0.169322,1.661311,-1.193195
7258,1.000585,-2.614383,2.623659,1.681878,-1.681878,2.614383,-2.623659,-0.705333,-0.877491,-0.030213,...,2.117137,1.944940,-0.177999,-0.859949,0.944695,-1.957478,-1.539461,0.079540,-2.623345,0.855443
2386,1.000585,0.052352,-0.051047,-0.051521,0.051521,-0.052352,0.051047,0.014667,0.007220,-0.013957,...,-0.055345,-0.020170,-0.124983,-0.004867,0.054369,0.010537,0.078890,-0.037798,0.024878,0.009266
8109,-0.999416,0.528554,-0.624199,-0.788287,0.788287,-0.528554,0.624199,0.014667,0.314946,0.153835,...,0.606997,0.541290,0.670261,-0.105465,1.299796,1.120699,-0.263454,-0.164915,-0.523853,0.009266
9743,1.000585,-0.328610,0.331054,0.243728,-0.243728,0.328610,-0.331054,-1.499179,0.853465,0.406982,...,0.209591,0.260560,1.465504,-1.564134,0.563862,1.398239,-0.885896,1.174702,-1.358878,0.009266
4546,1.000585,1.004757,-0.910774,-0.694836,0.694836,-1.004757,0.910774,-0.188410,0.103385,0.029099,...,0.262579,0.681655,-0.310540,0.799916,-0.511734,0.407023,-0.450186,-0.380036,0.943406,0.499158
4962,-0.999416,0.623795,-0.624199,-0.319306,0.319306,-0.623795,0.624199,0.476205,-1.377545,-0.130825,...,2.355580,0.922281,2.101699,-1.463536,2.375392,0.327726,0.203378,1.252928,-2.181974,2.458724
5706,-0.999416,0.242833,-0.146573,-0.192442,0.192442,-0.242833,0.146573,-0.114564,0.353411,0.091763,...,-0.267295,-0.461318,1.757094,-1.061144,0.054369,-3.438895,-1.134873,1.712504,-1.144157,0.989049

time: 22.6 ms (started: 2021-08-20 04:02:25 -07:00)

In [10]:
y_test = df_test.spread_a
p(y_test)

(3080,)

2583     7
9370    15
5655    -1
7258    -5
2386   -10
8109     2
9743    24
4546     6
4962    10
5706     5
Name: spread_a, dtype: int64

time: 3.33 ms (started: 2021-08-20 04:02:25 -07:00)

## 4.10 Random Forest Model<a id='4.10_Random_Forest_Model'></a>

A model that can work very well in a lot of cases is the random forest. For regression, this is provided by `sklearn`'s `RandomForestRegressor` class.

Time to stop the bad practice of repeatedly checking performance on the test split. Instead, go straight from defining the pipeline to assessing performance using cross-validation. `cross_validate` will perform the fitting as part of the process. This uses the default settings for the random forest so you'll then proceed to investigate some different hyperparameters.

### 4.10.1 Define the pipeline<a id='4.10.1_Define_the_pipeline'></a>

In [11]:
RF_pipe = make_pipeline(
    RandomForestRegressor(random_state=47)
)

time: 452 µs (started: 2021-08-20 04:02:25 -07:00)

In [12]:
type(RF_pipe)

sklearn.pipeline.Pipeline

time: 864 µs (started: 2021-08-20 04:02:25 -07:00)

In [13]:
hasattr(RF_pipe, 'fit'), hasattr(RF_pipe, 'predict')

(True, True)

time: 1.46 ms (started: 2021-08-20 04:02:25 -07:00)

### 4.10.2 Fit and assess performance using cross-validation<a id='4.10.2_Fit_and_assess_performance_using_cross-validation'></a>

In [18]:
#Code task 23#
#Call `cross_validate` to estimate the pipeline's performance.
#Pass it the random forest pipe object, `X_train` and `y_train`,
#and get it to use 5-fold cross-validation

from sklearn.metrics import mean_absolute_error

rf_default_cv_results = cross_validate(RF_pipe,
                                       X_train,
                                       y_train,
                                       cv=5,
                                       scoring=['neg_mean_absolute_error'])

time: 18min 9s (started: 2021-08-20 04:03:54 -07:00)

<font color='red'> specify you want mape or mae here instead of test_score?????????</font>

In [19]:
rf_cv_scores = rf_default_cv_results['test_score']
rf_cv_scores

KeyError: 'test_score'

time: 15.5 ms (started: 2021-08-20 04:22:03 -07:00)

<font color='red'> this is test score for the training set cv splits?????</font>

In [ ]:
np.mean(rf_cv_scores), np.std(rf_cv_scores)

In [ ]:

rf_cv_scores_mae = rf_default_cv_results['test_mae']
rf_cv_scores_mae

In [ ]:
np.mean(rf_cv_scores_mae), np.std(rf_cv_scores_mae)

<font color='red'> this 'test_mae' the correct syntax???? </font>

In [ ]:
#https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.cross_validate.html

### 4.10.3 Hyperparameter search using GridSearchCV<a id='4.10.3_Hyperparameter_search_using_GridSearchCV'></a>

Random forest has a number of hyperparameters that can be explored, however here you'll limit yourselves to exploring some different values for the number of trees. You'll try it with and without feature scaling, and try both the mean and median as strategies for imputing missing values.

In [ ]:
#n_est = [int(n) for n in np.logspace(start=1, stop=3, num=20)]

grid_params = {
        'randomforestregressor__n_estimators': [100],
        'randomforestregressor__max_depth': [5, 10, 20, 1000],
        'randomforestregressor__min_samples_split': [50, 100, 1000],
        'randomforestregressor__max_features': [5, 10, 20, 40, 100, 300]
}
grid_params

In [ ]:
#Code task 24#
#Call `GridSearchCV` with the random forest pipeline, passing in the above `grid_params`
#dict for parameters to evaluate, 5-fold cross-validation, and all available CPU cores (if desired)
rf_grid_cv = GridSearchCV(RF_pipe, param_grid=grid_params, cv=5, n_jobs=-1)

In [ ]:
#Code task 25#
#Now call the `GridSearchCV`'s `fit()` method with `X_train` and `y_train` as arguments
#to actually start the grid search. This may take a minute or two.
rf_grid_cv.fit(X_train, y_train)

In [ ]:
#Code task 26#
#Print the best params (`best_params_` attribute) from the grid search
rf_grid_cv.best_params_

It looks like imputing with the median helps, but scaling the features doesn't.

In [ ]:
rf_best_cv_results = cross_validate(rf_grid_cv.best_estimator_, X_train, y_train, cv=5)
rf_best_scores = rf_best_cv_results['test_score']
rf_best_scores

<font color='red'> why is this cross-validatino repeated when it was just done above in GridSearchCV????</font>

In [ ]:
np.mean(rf_best_scores), np.std(rf_best_scores)

You've marginally improved upon the default CV results. Random forest has many more hyperparameters you could tune, but we won't dive into that here.

<font color='red'>what hyperparameters did we just tune???????? n_est????????<font>

In [ ]:
#Code task 27#
#Plot a barplot of the random forest's feature importances,
#assigning the `feature_importances_` attribute of 
#`rf_grid_cv.best_estimator_.named_steps.randomforestregressor` to the name `imps` to then
#create a pandas Series object of the feature importances, with the index given by the
#training data column names, sorting the values in descending order
plt.subplots(figsize=(10, 5))
imps = rf_grid_cv.best_estimator_.named_steps.randomforestregressor.feature_importances_
rf_feat_imps = pd.Series(imps, index=X_train.columns).sort_values(ascending=False)
rf_feat_imps.plot(kind='bar')
plt.xlabel('features')
plt.ylabel('importance')
plt.title('Best random forest regressor feature importances');

In [ ]:
rf_feat_imps

In [ ]:
rf_feat_imps[0:30]

In [ ]:
#feature importance affected by collinearity


#https://www.quora.com/Does-the-random-forests-technique-suffer-if-there-is-a-multi-colinerarity-present-in-the-features-data-when-trying-to-predict-the-classification-of-the-next-datapoint-If-not-why

In [ ]:
# can reduce runtime by dropping the bottom 5% of feature importances

#https://towardsdatascience.com/improving-random-forest-in-python-part-1-893916666cd

In [ ]:
#play with max depth

#specify maximum number of features to include in each node split


#https://www.keboola.com/blog/random-forest-regression

In [ ]:
#Random Search Cross Validation

#https://towardsdatascience.com/hyperparameter-tuning-the-random-forest-in-python-using-scikit-learn-28d2aa77dd74


#random_grid = {'n_estimators': n_estimators,
#               'max_features': max_features,
#               'max_depth': max_depth,
#               'min_samples_split': min_samples_split,
#               'min_samples_leaf': min_samples_leaf,
#               'bootstrap': bootstrap}

## 4.11 Final Model Selection<a id='4.11_Final_Model_Selection'></a>

Time to select your final model to use for further business modeling! It would be good to revisit the above model selection; there is undoubtedly more that could be done to explore possible hyperparameters.
It would also be worthwhile to investigate removing the least useful features. Gathering or calculating, and storing, features adds business cost and dependencies, so if features genuinely are not needed they should be removed.
Building a simpler model with fewer features can also have the advantage of being easier to sell (and/or explain) to stakeholders.
Certainly there seem to be four strong features here and so a model using only those would probably work well.
However, you want to explore some different scenarios where other features vary so keep the fuller 
model for now. 
The business is waiting for this model and you have something that you have confidence in to be much better than guessing with the average price.

Or, rather, you have two "somethings". You built a best linear model and a best random forest model. You need to finally choose between them. You can calculate the mean absolute error using cross-validation. Although `cross-validate` defaults to the $R^2$ [metric for scoring](https://scikit-learn.org/stable/modules/model_evaluation.html#scoring) regression, you can specify the mean absolute error as an alternative via
the `scoring` parameter.

### 4.11.1 Linear regression model performance<a id='4.11.1_Linear_regression_model_performance'></a>

### 4.11.2 Random forest regression model performance<a id='4.11.2_Random_forest_regression_model_performance'></a>

In [ ]:
rf_neg_mae = cross_validate(rf_grid_cv.best_estimator_, X_train, y_train, 
                            scoring='neg_mean_absolute_error', cv=5, n_jobs=-1)

In [ ]:
rf_mae_mean = np.mean(-1 * rf_neg_mae['test_score'])
rf_mae_std = np.std(-1 * rf_neg_mae['test_score'])
rf_mae_mean, rf_mae_std

In [ ]:
mean_absolute_error(y_test, rf_grid_cv.best_estimator_.predict(X_test))

### 4.11.3 Conclusion<a id='4.11.3_Conclusion'></a>

The random forest model has a cross-validation mean absolute error... It also exhibits ... variability. 

???Verifying performance on the test set produces performance consistent with the cross-validation results????

## 4.12 Data quantity assessment<a id='4.12_Data_quantity_assessment'></a>

Finally, you need to advise the business whether it needs to undertake further data collection. Would more data be useful? We're often led to believe more data is always good, but gathering data invariably has a cost associated with it. Assess this trade off by seeing how performance varies with differing data set sizes. The `learning_curve` function does this conveniently.

In [ ]:
fractions = [.2, .25, .3, .35, .4, .45, .5, .6, .75, .8, 1.0]
train_size, train_scores, test_scores = learning_curve(RF_pipe, X_train, y_train, train_sizes=fractions)
train_scores_mean = np.mean(train_scores, axis=1)
train_scores_std = np.std(train_scores, axis=1)
test_scores_mean = np.mean(test_scores, axis=1)
test_scores_std = np.std(test_scores, axis=1)

In [ ]:
plt.subplots(figsize=(10, 5))
plt.errorbar(train_size, test_scores_mean, yerr=test_scores_std)
plt.xlabel('Training set size')
plt.ylabel('CV scores')
plt.title('Cross-validation score as training set size increases');

This shows that you seem to have plenty of data. There's an initial rapid improvement in model scores as one would expect, but it's essentially levelled off by around a sample size of 40-50.

## 4.13 Save best model object from pipeline<a id='4.13_Save_best_model_object_from_pipeline'></a>

In [ ]:
#This may not be "production grade ML deployment" practice, but adding some basic
#information to your saved models can save your bacon in development.
#Just what version model have you just loaded to reuse? What version of `sklearn`
#created it? When did you make it?
#Assign the pandas version number (`pd.__version__`) to the `pandas_version` attribute,
#the numpy version (`np.__version__`) to the `numpy_version` attribute,
#the sklearn version (`sklearn_version`) to the `sklearn_version` attribute,
#and the current datetime (`datetime.datetime.now()`) to the `build_datetime` attribute
#Let's call this model version '1.0'
best_model = rf_grid_cv.best_estimator_
best_model.version = '1.0'
best_model.pandas_version = pd.__version__
best_model.numpy_version = np.__version__
best_model.sklearn_version = sklearn_version
best_model.X_columns = [col for col in X_train.columns]
best_model.build_datetime = datetime.datetime.now()
    
modelpath = os.path.join('..', 'models')
if not os.path.exists(modelpath):
    os.mkdir(modelpath)
nbamodel_path = os.path.join(modelpath, 'nba_spread_a_model_161_max_features_mape_mae.pkl')
if not os.path.exists(nbamodel_path):
    with open(nbamodel_path, 'wb') as f:
        pickle.dump(best_model, f)

## 4.14 Summary<a id='4.14_Summary'></a>

**Q: 1** Write a summary of the work in this notebook. Capture the fact that you gained a baseline idea of performance by simply taking the average price and how well that did. Then highlight that you built a linear model and the features that found. Comment on the estimate of its performance from cross-validation and whether its performance on the test split was consistent with this estimate. Also highlight that a random forest regressor was tried, what preprocessing steps were found to be best, and again what its estimated performance via cross-validation was and whether its performance on the test set was consistent with that. State which model you have decided to use going forwards and why. This summary should provide a quick overview for someone wanting to know quickly why the given model was chosen for the next part of the business problem to help guide important business decisions.

Capture the fact that you gained a baseline idea of performance by simply taking the average price and how well that did.
-Average price yielded an R^2, explained variance, of 0 and a mean absolute error of 18 and 19 on the training (i.e. y_train) and testing (i.e. y_train) sets respectively when compared to their predicted average 'AdultWeekend' ticket price (i.e. y_tr_pred).

Then highlight that you built a linear model and the features that found.
-In building a linear model, features found (using GridSearchCV) included vertical_drop, Snow Making_ac, total_chairs, fastQuads, Runs, LongestRun_mi, trams, SkiableTerrain_ac. In selecting eight (8) features (i.e. hyperparameter k=8) in linear regression to predict 'AdultWeekend' ticket price (i.e. y_train and y_test), the cross validation average test score of R^2 (i.e. explained variance) performance reached a maximum.


Comment on the estimate of its performance from cross-validation and whether its performance on the test split was consistent with this estimate.
-Cross-validation (with number of folds k=5) performance using linear regression model with 15 features (i.e. pipe15) showed an average R^2 score of .6349 and average std of .095. Using the pipe15 model, mean explained variance R^2 of cross-validation is close to the test split R^2 score .6347.


Also highlight that a random forest regressor was tried, what preprocessing steps were found to be best, and again what its estimated performance via cross-validation was and whether its performance on the test set was consistent with that. 
-Preprocessing steps that were found to be best included ?using n_est=69,? omitting the use of feature scaling, and using median instead of mean for feature imputing.
-The estimated performance of random forest regressor via cross-validation was a mean absolute error of 9.754 and standard deviation of 1.353.
-This performance was consistent with performance of the test set where mean absolute error was 9.342 using y_test and X_test.

State which model you have decided to use going forwards and why.
We have decided to go forwards with the random forest regression model because it yields the lower MAE (mean absolute error) between linear regression at 10.448 and random forest regression at 9.754, each by cross validation.