In [1]:
import random
import pandas as pd

In [2]:
one2eight = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']
one2eight

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']

In [3]:
onetwo = [k + 1 for k in range(2)]
onetwo

[1, 2]

In [4]:
[[random.choice(one2eight), random.choice(onetwo)] for k in range(4)]

[['h', 2], ['c', 1], ['a', 2], ['e', 2]]

In [5]:
df = pd.DataFrame([[random.choice(one2eight), random.choice(onetwo)] for k in range(4)], index=[1, 2, 3, 4])
df

   0  1
1  g  2
2  h  2
3  c  2
4  a  1

In [6]:
df.index.name = 'move#'
df.rename(columns={0:'file', 1:'rank'}, inplace=True)
df

      file  rank
move#
1        g     2
2        h     2
3        c     2
4        a     1

In [7]:
def first_four_moves():
    one2eight_ = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']
    onetwo_ = [k + 1 for k in range(2)]
    df_ = pd.DataFrame([[random.choice(one2eight), random.choice(onetwo)] for k in range(4)], index=[1, 2, 3, 4])
    df_.index.name = 'move#'
    df_.rename(columns={0:'file', 1:'rank'}, inplace=True)
    return df_

In [8]:
first_four_moves()

      file  rank
move#
1        b     1
2        g     2
3        d     1
4        g     1

In [9]:
def first_four_moves2():
    one2eight_ = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']
    onetwo_ = [k + 1 for k in range(2)]
    df_ = pd.DataFrame([str(random.choice(one2eight)) + str(random.choice(onetwo)) for k in range(4)], index=[1, 2, 3, 4])
    df_.index.name = 'move#'
    df_.rename(columns={0:'square'}, inplace=True)
    return df_

In [10]:
first_four_moves2()

      square
move#
1         a2
2         b2
3         h1
4         e2

In [11]:
def first_four_moves3():
    one2eight_ = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']
    onetwo_ = [k + 1 for k in range(2)]
    df_ = pd.DataFrame([str(random.choice(one2eight)) + str(random.choice(onetwo)) for k in range(4)], index=[1, 2, 3, 4])
    df_.index.name = 'move#'
    df_.rename(columns={0:'square'}, inplace=True)
    df_.reset_index(inplace=True)
    return df_

In [12]:
first_four_moves3()

   move# square
0      1     d1
1      2     f1
2      3     g1
3      4     e2

In [13]:
def first_four_moves4():
    one2eight_ = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']
    onetwo_ = [k + 1 for k in range(2)]
    df_ = pd.DataFrame([str(random.choice(one2eight)) + str(random.choice(onetwo)) for k in range(4)], index=[1, 2, 3, 4])
    df_.index.name = 'move#'
    df_.rename(columns={0:'square'}, inplace=True)
    df_.reset_index(inplace=True, drop=True)
    return df_

In [14]:
first_four_moves4()

  square
0     f2
1     b2
2     f1
3     b1

In [15]:
first_four_moves4()

  square
0     g1
1     d1
2     h2
3     b1

In [16]:
first_four_moves4()

  square
0     h1
1     d1
2     a2
3     e1

In [17]:
game3 = first_four_moves4()
game3

  square
0     e1
1     d2
2     e2
3     b2

In [18]:
game4 = first_four_moves4()
game4

  square
0     h2
1     b1
2     e1
3     g1

In [19]:
game5 = first_four_moves4()
game5

  square
0     a1
1     b1
2     d1
3     h1