In [1]:
import pandas as pd
import numpy as np
import os

import matplotlib.pyplot as plt

pd.options.display.max_rows = 999
pd.options.display.max_columns = 999

In [2]:
df_games = pd.read_csv('C:\\Users\\Paul\\sb\\Untitled Folder\\raw_data\\nba_games_all.csv')
df_games.head()

,game_id,game_date,matchup,team_id,is_home,wl,w,l,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,a_team_id,season_year,season_type,season
0,20800741,2009-02-06,SAC vs. UTA,1610612762,f,W,29.0,22.0,0.569,240,39.0,74.0,0.527,4.0,13.0,0.308,29.0,37.0,1.0,8.0,36.0,44,19.0,5.0,4.0,18.0,26.0,111,1610612758,2008,Regular Season,2008-09
1,20800701,2009-01-31,POR vs. UTA,1610612762,f,L,26.0,22.0,0.542,240,37.0,68.0,0.544,5.0,20.0,0.250,29.0,37.0,1.0,7.0,20.0,27,17.0,6.0,0.0,15.0,22.0,108,1610612757,2008,Regular Season,2008-09
2,20800584,2009-01-16,MEM vs. UTA,1610612762,f,W,24.0,16.0,0.600,240,37.0,71.0,0.521,7.0,19.0,0.368,20.0,27.0,1.0,7.0,26.0,33,23.0,9.0,3.0,15.0,22.0,101,1610612763,2008,Regular Season,2008-09
3,20800558,2009-01-12,IND @ UTA,1610612762,t,W,23.0,15.0,0.605,240,39.0,85.0,0.459,8.0,18.0,0.444,34.0,37.0,1.0,9.0,31.0,40,24.0,10.0,6.0,8.0,20.0,120,1610612754,2008,Regular Season,2008-09
4,20800440,2008-12-27,HOU vs. UTA,1610612762,f,L,18.0,14.0,0.563,290,49.0,100.0,0.490,5.0,13.0,0.385,12.0,18.0,1.0,11.0,29.0,40,35.0,13.0,7.0,9.0,27.0,115,1610612745,2008,Regular Season,2008-09

In [3]:
df_games.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125624 entries, 0 to 125623
Data columns (total 32 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   game_id      125624 non-null  int64
 1   game_date    119376 non-null  object
 2   matchup      125624 non-null  object
 3   team_id      125624 non-null  int64
 4   is_home      125624 non-null  object
 5   wl           125614 non-null  object
 6   w            41000 non-null   float64
 7   l            41000 non-null   float64
 8   w_pct        41000 non-null   float64
 9   min          125624 non-null  int64
 10  fgm          125607 non-null  float64
 11  fga          90894 non-null   float64
 12  fg_pct       90871 non-null   float64
 13  fg3m         95248 non-null   float64
 14  fg3a         84316 non-null   float64
 15  fg3_pct      80062 non-null   float64
 16  ftm          125605 non-null  float64
 17  fta          120011 non-null  float64
 18  ft_pct       119960 non-null  float64
 19  oreb         83786 non-null   float64
 20  dreb         83639 non-null   float64
 21  reb          125624 non-null  int64
 22  ast          90068 non-null   float64
 23  stl          83960 non-null   float64
 24  blk          84407 non-null   float64
 25  tov          84293 non-null   float64
 26  pf           121742 non-null  float64
 27  pts          125624 non-null  int64
 28  a_team_id    125624 non-null  int64
 29  season_year  125624 non-null  int64
 30  season_type  125624 non-null  object
 31  season       125624 non-null  object
dtypes: float64(19), int64(7), object(6)
memory usage: 30.7+ MB

In [4]:
df_games['game_date'] = pd.to_datetime(df_games['game_date'])
df_games.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125624 entries, 0 to 125623
Data columns (total 32 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   game_id      125624 non-null  int64
 1   game_date    119376 non-null  datetime64[ns]
 2   matchup      125624 non-null  object
 3   team_id      125624 non-null  int64
 4   is_home      125624 non-null  object
 5   wl           125614 non-null  object
 6   w            41000 non-null   float64
 7   l            41000 non-null   float64
 8   w_pct        41000 non-null   float64
 9   min          125624 non-null  int64
 10  fgm          125607 non-null  float64
 11  fga          90894 non-null   float64
 12  fg_pct       90871 non-null   float64
 13  fg3m         95248 non-null   float64
 14  fg3a         84316 non-null   float64
 15  fg3_pct      80062 non-null   float64
 16  ftm          125605 non-null  float64
 17  fta          120011 non-null  float64
 18  ft_pct       119960 non-null  float64
 19  oreb         83786 non-null   float64
 20  dreb         83639 non-null   float64
 21  reb          125624 non-null  int64
 22  ast          90068 non-null   float64
 23  stl          83960 non-null   float64
 24  blk          84407 non-null   float64
 25  tov          84293 non-null   float64
 26  pf           121742 non-null  float64
 27  pts          125624 non-null  int64
 28  a_team_id    125624 non-null  int64
 29  season_year  125624 non-null  int64
 30  season_type  125624 non-null  object
 31  season       125624 non-null  object
dtypes: datetime64[ns](1), float64(19), int64(7), object(5)
memory usage: 30.7+ MB

In [5]:
df_games[df_games.is_home != 'f']

,game_id,game_date,matchup,team_id,is_home,wl,w,l,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,a_team_id,season_year,season_type,season
3,20800558,2009-01-12,IND @ UTA,1610612762,t,W,23.0,15.0,0.605,240,39.0,85.0,0.459,8.0,18.0,0.444,34.0,37.0,1.0,9.0,31.0,40,24.0,10.0,6.0,8.0,20.0,120,1610612754,2008,Regular Season,2008-09
6,29800603,1999-04-21,TOR @ WAS,1610612764,t,L,NaN,NaN,NaN,240,38.0,85.0,0.447,3.0,8.0,0.375,12.0,19.0,1.0,16.0,27.0,43,18.0,7.0,3.0,15.0,24.0,91,1610612761,1998,Regular Season,1998-99
7,29800577,1999-04-18,BOS @ WAS,1610612764,t,L,NaN,NaN,NaN,240,33.0,76.0,0.434,4.0,7.0,0.571,28.0,40.0,1.0,11.0,28.0,39,23.0,9.0,5.0,17.0,26.0,98,1610612738,1998,Regular Season,1998-99
8,29800561,1999-04-16,CHI @ WAS,1610612764,t,W,NaN,NaN,NaN,240,37.0,83.0,0.446,2.0,10.0,0.200,11.0,15.0,1.0,6.0,45.0,51,21.0,9.0,4.0,14.0,16.0,87,1610612741,1998,Regular Season,1998-99
9,20800344,2008-12-13,ORL @ UTA,1610612762,t,L,15.0,10.0,0.600,240,33.0,77.0,0.429,8.0,18.0,0.444,20.0,29.0,1.0,17.0,29.0,46,25.0,11.0,4.0,22.0,23.0,94,1610612753,2008,Regular Season,2008-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125617,10800107,NaT,ATL @ DET,1610612765,t,L,6.0,2.0,0.750,240,34.0,87.0,0.391,5.0,14.0,0.357,14.0,18.0,1.0,10.0,32.0,42,21.0,9.0,4.0,14.0,23.0,87,1610612737,2008,Pre Season,2008-09
125619,20801131,2009-04-03,MIN @ UTA,1610612762,t,L,46.0,30.0,0.605,240,36.0,75.0,0.480,5.0,11.0,0.455,25.0,29.0,1.0,4.0,24.0,28,22.0,11.0,4.0,10.0,16.0,102,1610612750,2008,Regular Season,2008-09
125620,20801058,2009-03-24,HOU @ UTA,1610612762,t,W,44.0,26.0,0.629,240,38.0,85.0,0.447,4.0,14.0,0.286,19.0,25.0,1.0,3.0,39.0,42,23.0,6.0,12.0,8.0,17.0,99,1610612745,2008,Regular Season,2008-09
125622,20800839,2009-02-23,ATL @ UTA,1610612762,t,W,34.0,23.0,0.596,240,44.0,88.0,0.500,6.0,13.0,0.462,14.0,17.0,1.0,14.0,29.0,43,30.0,11.0,6.0,15.0,19.0,108,1610612737,2008,Regular Season,2008-09
125623,20800810,2009-02-19,BOS @ UTA,1610612762,t,W,32.0,23.0,0.582,240,32.0,77.0,0.416,2.0,10.0,0.200,24.0,31.0,1.0,7.0,28.0,35,16.0,7.0,6.0,11.0,18.0,90,1610612738,2008,Regular Season,2008-09

In [6]:
df_games[df_games.is_home != 'f'].shape[0]

62812

In [7]:
df_games['new_column'] = 0
df_games = df_games.drop(columns='new_column')
df_games.head()

,game_id,game_date,matchup,team_id,is_home,wl,w,l,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,a_team_id,season_year,season_type,season
0,20800741,2009-02-06,SAC vs. UTA,1610612762,f,W,29.0,22.0,0.569,240,39.0,74.0,0.527,4.0,13.0,0.308,29.0,37.0,1.0,8.0,36.0,44,19.0,5.0,4.0,18.0,26.0,111,1610612758,2008,Regular Season,2008-09
1,20800701,2009-01-31,POR vs. UTA,1610612762,f,L,26.0,22.0,0.542,240,37.0,68.0,0.544,5.0,20.0,0.250,29.0,37.0,1.0,7.0,20.0,27,17.0,6.0,0.0,15.0,22.0,108,1610612757,2008,Regular Season,2008-09
2,20800584,2009-01-16,MEM vs. UTA,1610612762,f,W,24.0,16.0,0.600,240,37.0,71.0,0.521,7.0,19.0,0.368,20.0,27.0,1.0,7.0,26.0,33,23.0,9.0,3.0,15.0,22.0,101,1610612763,2008,Regular Season,2008-09
3,20800558,2009-01-12,IND @ UTA,1610612762,t,W,23.0,15.0,0.605,240,39.0,85.0,0.459,8.0,18.0,0.444,34.0,37.0,1.0,9.0,31.0,40,24.0,10.0,6.0,8.0,20.0,120,1610612754,2008,Regular Season,2008-09
4,20800440,2008-12-27,HOU vs. UTA,1610612762,f,L,18.0,14.0,0.563,290,49.0,100.0,0.490,5.0,13.0,0.385,12.0,18.0,1.0,11.0,29.0,40,35.0,13.0,7.0,9.0,27.0,115,1610612745,2008,Regular Season,2008-09

In [8]:
column_names = df_games.columns
column_names

Index(['game_id', 'game_date', 'matchup', 'team_id', 'is_home', 'wl', 'w', 'l',
       'w_pct', 'min', 'fgm', 'fga', 'fg_pct', 'fg3m', 'fg3a', 'fg3_pct',
       'ftm', 'fta', 'ft_pct', 'oreb', 'dreb', 'reb', 'ast', 'stl', 'blk',
       'tov', 'pf', 'pts', 'a_team_id', 'season_year', 'season_type',
       'season'],
      dtype='object')

In [9]:
type(column_names)

pandas.core.indexes.base.Index

In [10]:
column_names = column_names.drop(['game_id', 'game_date', 'is_home', 'season_year', 'season_type', 'season'])
column_names

Index(['matchup', 'team_id', 'wl', 'w', 'l', 'w_pct', 'min', 'fgm', 'fga',
       'fg_pct', 'fg3m', 'fg3a', 'fg3_pct', 'ftm', 'fta', 'ft_pct', 'oreb',
       'dreb', 'reb', 'ast', 'stl', 'blk', 'tov', 'pf', 'pts', 'a_team_id'],
      dtype='object')

In [11]:
#empty_df = pd.DataFrame({}, columns=column_names)
#empty_df

In [12]:
empty_df = df_games[df_games.is_home == 'f']
empty_df

,game_id,game_date,matchup,team_id,is_home,wl,w,l,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,a_team_id,season_year,season_type,season
0,20800741,2009-02-06,SAC vs. UTA,1610612762,f,W,29.0,22.0,0.569,240,39.0,74.0,0.527,4.0,13.0,0.308,29.0,37.0,1.0,8.0,36.0,44,19.0,5.0,4.0,18.0,26.0,111,1610612758,2008,Regular Season,2008-09
1,20800701,2009-01-31,POR vs. UTA,1610612762,f,L,26.0,22.0,0.542,240,37.0,68.0,0.544,5.0,20.0,0.250,29.0,37.0,1.0,7.0,20.0,27,17.0,6.0,0.0,15.0,22.0,108,1610612757,2008,Regular Season,2008-09
2,20800584,2009-01-16,MEM vs. UTA,1610612762,f,W,24.0,16.0,0.600,240,37.0,71.0,0.521,7.0,19.0,0.368,20.0,27.0,1.0,7.0,26.0,33,23.0,9.0,3.0,15.0,22.0,101,1610612763,2008,Regular Season,2008-09
4,20800440,2008-12-27,HOU vs. UTA,1610612762,f,L,18.0,14.0,0.563,290,49.0,100.0,0.490,5.0,13.0,0.385,12.0,18.0,1.0,11.0,29.0,40,35.0,13.0,7.0,9.0,27.0,115,1610612745,2008,Regular Season,2008-09
5,20800395,2008-12-20,CHI vs. UTA,1610612762,f,L,17.0,12.0,0.586,240,38.0,79.0,0.481,2.0,11.0,0.182,20.0,22.0,1.0,12.0,21.0,33,21.0,9.0,5.0,20.0,19.0,98,1610612741,2008,Regular Season,2008-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125613,20800441,2008-12-27,MIL vs. DET,1610612765,f,W,17.0,11.0,0.607,240,34.0,79.0,0.430,3.0,16.0,0.188,16.0,20.0,1.0,15.0,38.0,53,16.0,8.0,5.0,12.0,27.0,87,1610612749,2008,Regular Season,2008-09
125614,20800052,2008-11-05,TOR vs. DET,1610612765,f,W,4.0,0.0,1.000,240,39.0,85.0,0.459,3.0,12.0,0.250,19.0,22.0,1.0,10.0,33.0,43,21.0,6.0,5.0,5.0,18.0,100,1610612761,2008,Regular Season,2008-09
125615,20800042,2008-11-03,CHA vs. DET,1610612765,f,W,3.0,0.0,1.000,240,42.0,84.0,0.500,8.0,16.0,0.500,9.0,11.0,1.0,16.0,26.0,42,23.0,4.0,4.0,8.0,22.0,101,1610612766,2008,Regular Season,2008-09
125618,10800025,NaT,WAS vs. DET,1610612765,f,W,3.0,0.0,1.000,240,27.0,67.0,0.403,1.0,6.0,0.167,18.0,26.0,1.0,5.0,31.0,36,18.0,13.0,4.0,17.0,17.0,73,1610612764,2008,Pre Season,2008-09
125621,20801029,2009-03-20,OKC vs. UTA,1610612762,f,W,43.0,26.0,0.623,240,41.0,84.0,0.488,1.0,7.0,0.143,18.0,26.0,1.0,11.0,30.0,41,24.0,8.0,3.0,10.0,13.0,101,1610612760,2008,Regular Season,2008-09

In [13]:
#df_games[df_games.is_home == 't'].rename(columns={column_name: column_name + '_away'})

In [14]:
for column_name in column_names:
    empty_df = empty_df[empty_df.is_home == 'f'].rename(columns={column_name: column_name + '_away'})
    
empty_df

,game_id,game_date,matchup_away,team_id_away,is_home,wl_away,w_away,l_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,a_team_id_away,season_year,season_type,season
0,20800741,2009-02-06,SAC vs. UTA,1610612762,f,W,29.0,22.0,0.569,240,39.0,74.0,0.527,4.0,13.0,0.308,29.0,37.0,1.0,8.0,36.0,44,19.0,5.0,4.0,18.0,26.0,111,1610612758,2008,Regular Season,2008-09
1,20800701,2009-01-31,POR vs. UTA,1610612762,f,L,26.0,22.0,0.542,240,37.0,68.0,0.544,5.0,20.0,0.250,29.0,37.0,1.0,7.0,20.0,27,17.0,6.0,0.0,15.0,22.0,108,1610612757,2008,Regular Season,2008-09
2,20800584,2009-01-16,MEM vs. UTA,1610612762,f,W,24.0,16.0,0.600,240,37.0,71.0,0.521,7.0,19.0,0.368,20.0,27.0,1.0,7.0,26.0,33,23.0,9.0,3.0,15.0,22.0,101,1610612763,2008,Regular Season,2008-09
4,20800440,2008-12-27,HOU vs. UTA,1610612762,f,L,18.0,14.0,0.563,290,49.0,100.0,0.490,5.0,13.0,0.385,12.0,18.0,1.0,11.0,29.0,40,35.0,13.0,7.0,9.0,27.0,115,1610612745,2008,Regular Season,2008-09
5,20800395,2008-12-20,CHI vs. UTA,1610612762,f,L,17.0,12.0,0.586,240,38.0,79.0,0.481,2.0,11.0,0.182,20.0,22.0,1.0,12.0,21.0,33,21.0,9.0,5.0,20.0,19.0,98,1610612741,2008,Regular Season,2008-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125613,20800441,2008-12-27,MIL vs. DET,1610612765,f,W,17.0,11.0,0.607,240,34.0,79.0,0.430,3.0,16.0,0.188,16.0,20.0,1.0,15.0,38.0,53,16.0,8.0,5.0,12.0,27.0,87,1610612749,2008,Regular Season,2008-09
125614,20800052,2008-11-05,TOR vs. DET,1610612765,f,W,4.0,0.0,1.000,240,39.0,85.0,0.459,3.0,12.0,0.250,19.0,22.0,1.0,10.0,33.0,43,21.0,6.0,5.0,5.0,18.0,100,1610612761,2008,Regular Season,2008-09
125615,20800042,2008-11-03,CHA vs. DET,1610612765,f,W,3.0,0.0,1.000,240,42.0,84.0,0.500,8.0,16.0,0.500,9.0,11.0,1.0,16.0,26.0,42,23.0,4.0,4.0,8.0,22.0,101,1610612766,2008,Regular Season,2008-09
125618,10800025,NaT,WAS vs. DET,1610612765,f,W,3.0,0.0,1.000,240,27.0,67.0,0.403,1.0,6.0,0.167,18.0,26.0,1.0,5.0,31.0,36,18.0,13.0,4.0,17.0,17.0,73,1610612764,2008,Pre Season,2008-09
125621,20801029,2009-03-20,OKC vs. UTA,1610612762,f,W,43.0,26.0,0.623,240,41.0,84.0,0.488,1.0,7.0,0.143,18.0,26.0,1.0,11.0,30.0,41,24.0,8.0,3.0,10.0,13.0,101,1610612760,2008,Regular Season,2008-09

In [15]:
for column_name in column_names:
    df_games = df_games[df_games.is_home == 't'].rename(columns={column_name: column_name + '_home'})
    
df_games

,game_id,game_date,matchup_home,team_id_home,is_home,wl_home,w_home,l_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,a_team_id_home,season_year,season_type,season
3,20800558,2009-01-12,IND @ UTA,1610612762,t,W,23.0,15.0,0.605,240,39.0,85.0,0.459,8.0,18.0,0.444,34.0,37.0,1.0,9.0,31.0,40,24.0,10.0,6.0,8.0,20.0,120,1610612754,2008,Regular Season,2008-09
6,29800603,1999-04-21,TOR @ WAS,1610612764,t,L,NaN,NaN,NaN,240,38.0,85.0,0.447,3.0,8.0,0.375,12.0,19.0,1.0,16.0,27.0,43,18.0,7.0,3.0,15.0,24.0,91,1610612761,1998,Regular Season,1998-99
7,29800577,1999-04-18,BOS @ WAS,1610612764,t,L,NaN,NaN,NaN,240,33.0,76.0,0.434,4.0,7.0,0.571,28.0,40.0,1.0,11.0,28.0,39,23.0,9.0,5.0,17.0,26.0,98,1610612738,1998,Regular Season,1998-99
8,29800561,1999-04-16,CHI @ WAS,1610612764,t,W,NaN,NaN,NaN,240,37.0,83.0,0.446,2.0,10.0,0.200,11.0,15.0,1.0,6.0,45.0,51,21.0,9.0,4.0,14.0,16.0,87,1610612741,1998,Regular Season,1998-99
9,20800344,2008-12-13,ORL @ UTA,1610612762,t,L,15.0,10.0,0.600,240,33.0,77.0,0.429,8.0,18.0,0.444,20.0,29.0,1.0,17.0,29.0,46,25.0,11.0,4.0,22.0,23.0,94,1610612753,2008,Regular Season,2008-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125617,10800107,NaT,ATL @ DET,1610612765,t,L,6.0,2.0,0.750,240,34.0,87.0,0.391,5.0,14.0,0.357,14.0,18.0,1.0,10.0,32.0,42,21.0,9.0,4.0,14.0,23.0,87,1610612737,2008,Pre Season,2008-09
125619,20801131,2009-04-03,MIN @ UTA,1610612762,t,L,46.0,30.0,0.605,240,36.0,75.0,0.480,5.0,11.0,0.455,25.0,29.0,1.0,4.0,24.0,28,22.0,11.0,4.0,10.0,16.0,102,1610612750,2008,Regular Season,2008-09
125620,20801058,2009-03-24,HOU @ UTA,1610612762,t,W,44.0,26.0,0.629,240,38.0,85.0,0.447,4.0,14.0,0.286,19.0,25.0,1.0,3.0,39.0,42,23.0,6.0,12.0,8.0,17.0,99,1610612745,2008,Regular Season,2008-09
125622,20800839,2009-02-23,ATL @ UTA,1610612762,t,W,34.0,23.0,0.596,240,44.0,88.0,0.500,6.0,13.0,0.462,14.0,17.0,1.0,14.0,29.0,43,30.0,11.0,6.0,15.0,19.0,108,1610612737,2008,Regular Season,2008-09
125623,20800810,2009-02-19,BOS @ UTA,1610612762,t,W,32.0,23.0,0.582,240,32.0,77.0,0.416,2.0,10.0,0.200,24.0,31.0,1.0,7.0,28.0,35,16.0,7.0,6.0,11.0,18.0,90,1610612738,2008,Regular Season,2008-09

In [16]:
#add columns to original dataframe
df_games.columns

Index(['game_id', 'game_date', 'matchup_home', 'team_id_home', 'is_home',
       'wl_home', 'w_home', 'l_home', 'w_pct_home', 'min_home', 'fgm_home',
       'fga_home', 'fg_pct_home', 'fg3m_home', 'fg3a_home', 'fg3_pct_home',
       'ftm_home', 'fta_home', 'ft_pct_home', 'oreb_home', 'dreb_home',
       'reb_home', 'ast_home', 'stl_home', 'blk_home', 'tov_home', 'pf_home',
       'pts_home', 'a_team_id_home', 'season_year', 'season_type', 'season'],
      dtype='object')

In [17]:
away_column_names = empty_df.columns.drop(['game_id', 'game_date', 'is_home',
                                           'matchup_away', 'team_id_away', 'is_home', 'wl_away'])
away_column_names

Index(['w_away', 'l_away', 'w_pct_away', 'min_away', 'fgm_away', 'fga_away',
       'fg_pct_away', 'fg3m_away', 'fg3a_away', 'fg3_pct_away', 'ftm_away',
       'fta_away', 'ft_pct_away', 'oreb_away', 'dreb_away', 'reb_away',
       'ast_away', 'stl_away', 'blk_away', 'tov_away', 'pf_away', 'pts_away',
       'a_team_id_away', 'season_year', 'season_type', 'season'],
      dtype='object')

In [18]:
cols_numeric = empty_df.select_dtypes([np.number]).columns
cols_numeric

Index(['game_id', 'team_id_away', 'w_away', 'l_away', 'w_pct_away', 'min_away',
       'fgm_away', 'fga_away', 'fg_pct_away', 'fg3m_away', 'fg3a_away',
       'fg3_pct_away', 'ftm_away', 'fta_away', 'ft_pct_away', 'oreb_away',
       'dreb_away', 'reb_away', 'ast_away', 'stl_away', 'blk_away', 'tov_away',
       'pf_away', 'pts_away', 'a_team_id_away', 'season_year'],
      dtype='object')

In [19]:
for column in cols_numeric:
    df_games[column] = 0
df_games

,game_id,game_date,matchup_home,team_id_home,is_home,wl_home,w_home,l_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,a_team_id_home,season_year,season_type,season,team_id_away,w_away,l_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,a_team_id_away
3,0,2009-01-12,IND @ UTA,1610612762,t,W,23.0,15.0,0.605,240,39.0,85.0,0.459,8.0,18.0,0.444,34.0,37.0,1.0,9.0,31.0,40,24.0,10.0,6.0,8.0,20.0,120,1610612754,0,Regular Season,2008-09,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
6,0,1999-04-21,TOR @ WAS,1610612764,t,L,NaN,NaN,NaN,240,38.0,85.0,0.447,3.0,8.0,0.375,12.0,19.0,1.0,16.0,27.0,43,18.0,7.0,3.0,15.0,24.0,91,1610612761,0,Regular Season,1998-99,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7,0,1999-04-18,BOS @ WAS,1610612764,t,L,NaN,NaN,NaN,240,33.0,76.0,0.434,4.0,7.0,0.571,28.0,40.0,1.0,11.0,28.0,39,23.0,9.0,5.0,17.0,26.0,98,1610612738,0,Regular Season,1998-99,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
8,0,1999-04-16,CHI @ WAS,1610612764,t,W,NaN,NaN,NaN,240,37.0,83.0,0.446,2.0,10.0,0.200,11.0,15.0,1.0,6.0,45.0,51,21.0,9.0,4.0,14.0,16.0,87,1610612741,0,Regular Season,1998-99,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
9,0,2008-12-13,ORL @ UTA,1610612762,t,L,15.0,10.0,0.600,240,33.0,77.0,0.429,8.0,18.0,0.444,20.0,29.0,1.0,17.0,29.0,46,25.0,11.0,4.0,22.0,23.0,94,1610612753,0,Regular Season,2008-09,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125617,0,NaT,ATL @ DET,1610612765,t,L,6.0,2.0,0.750,240,34.0,87.0,0.391,5.0,14.0,0.357,14.0,18.0,1.0,10.0,32.0,42,21.0,9.0,4.0,14.0,23.0,87,1610612737,0,Pre Season,2008-09,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
125619,0,2009-04-03,MIN @ UTA,1610612762,t,L,46.0,30.0,0.605,240,36.0,75.0,0.480,5.0,11.0,0.455,25.0,29.0,1.0,4.0,24.0,28,22.0,11.0,4.0,10.0,16.0,102,1610612750,0,Regular Season,2008-09,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
125620,0,2009-03-24,HOU @ UTA,1610612762,t,W,44.0,26.0,0.629,240,38.0,85.0,0.447,4.0,14.0,0.286,19.0,25.0,1.0,3.0,39.0,42,23.0,6.0,12.0,8.0,17.0,99,1610612745,0,Regular Season,2008-09,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
125622,0,2009-02-23,ATL @ UTA,1610612762,t,W,34.0,23.0,0.596,240,44.0,88.0,0.500,6.0,13.0,0.462,14.0,17.0,1.0,14.0,29.0,43,30.0,11.0,6.0,15.0,19.0,108,1610612737,0,Regular Season,2008-09,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
125623,0,2009-02-19,BOS @ UTA,1610612762,t,W,32.0,23.0,0.582,240,32.0,77.0,0.416,2.0,10.0,0.200,24.0,31.0,1.0,7.0,28.0,35,16.0,7.0,6.0,11.0,18.0,90,1610612738,0,Regular Season,2008-09,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [20]:
df = pd.concat([df_games, empty_df])
df

,game_id,game_date,matchup_home,team_id_home,is_home,wl_home,w_home,l_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,a_team_id_home,season_year,season_type,season,team_id_away,w_away,l_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,a_team_id_away,matchup_away,wl_away
3,0,2009-01-12,IND @ UTA,1.610613e+09,t,W,23.0,15.0,0.605,240.0,39.0,85.0,0.459,8.0,18.0,0.444,34.0,37.0,1.0,9.0,31.0,40.0,24.0,10.0,6.0,8.0,20.0,120.0,1.610613e+09,0,Regular Season,2008-09,0,0.0,0.0,0.000,0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0,0,NaN,NaN
6,0,1999-04-21,TOR @ WAS,1.610613e+09,t,L,NaN,NaN,NaN,240.0,38.0,85.0,0.447,3.0,8.0,0.375,12.0,19.0,1.0,16.0,27.0,43.0,18.0,7.0,3.0,15.0,24.0,91.0,1.610613e+09,0,Regular Season,1998-99,0,0.0,0.0,0.000,0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0,0,NaN,NaN
7,0,1999-04-18,BOS @ WAS,1.610613e+09,t,L,NaN,NaN,NaN,240.0,33.0,76.0,0.434,4.0,7.0,0.571,28.0,40.0,1.0,11.0,28.0,39.0,23.0,9.0,5.0,17.0,26.0,98.0,1.610613e+09,0,Regular Season,1998-99,0,0.0,0.0,0.000,0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0,0,NaN,NaN
8,0,1999-04-16,CHI @ WAS,1.610613e+09,t,W,NaN,NaN,NaN,240.0,37.0,83.0,0.446,2.0,10.0,0.200,11.0,15.0,1.0,6.0,45.0,51.0,21.0,9.0,4.0,14.0,16.0,87.0,1.610613e+09,0,Regular Season,1998-99,0,0.0,0.0,0.000,0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0,0,NaN,NaN
9,0,2008-12-13,ORL @ UTA,1.610613e+09,t,L,15.0,10.0,0.600,240.0,33.0,77.0,0.429,8.0,18.0,0.444,20.0,29.0,1.0,17.0,29.0,46.0,25.0,11.0,4.0,22.0,23.0,94.0,1.610613e+09,0,Regular Season,2008-09,0,0.0,0.0,0.000,0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125613,20800441,2008-12-27,NaN,NaN,f,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008,Regular Season,2008-09,1610612765,17.0,11.0,0.607,240,34.0,79.0,0.430,3.0,16.0,0.188,16.0,20.0,1.0,15.0,38.0,53,16.0,8.0,5.0,12.0,27.0,87,1610612749,MIL vs. DET,W
125614,20800052,2008-11-05,NaN,NaN,f,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008,Regular Season,2008-09,1610612765,4.0,0.0,1.000,240,39.0,85.0,0.459,3.0,12.0,0.250,19.0,22.0,1.0,10.0,33.0,43,21.0,6.0,5.0,5.0,18.0,100,1610612761,TOR vs. DET,W
125615,20800042,2008-11-03,NaN,NaN,f,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008,Regular Season,2008-09,1610612765,3.0,0.0,1.000,240,42.0,84.0,0.500,8.0,16.0,0.500,9.0,11.0,1.0,16.0,26.0,42,23.0,4.0,4.0,8.0,22.0,101,1610612766,CHA vs. DET,W
125618,10800025,NaT,NaN,NaN,f,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008,Pre Season,2008-09,1610612765,3.0,0.0,1.000,240,27.0,67.0,0.403,1.0,6.0,0.167,18.0,26.0,1.0,5.0,31.0,36,18.0,13.0,4.0,17.0,17.0,73,1610612764,WAS vs. DET,W
125621,20801029,2009-03-20,NaN,NaN,f,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008,Regular Season,2008-09,1610612762,43.0,26.0,0.623,240,41.0,84.0,0.488,1.0,7.0,0.143,18.0,26.0,1.0,11.0,30.0,41,24.0,8.0,3.0,10.0,13.0,101,1610612760,OKC vs. UTA,W

In [21]:
df.groupby(['game_id', 'game_date']).sum()

                     team_id_home  w_home  l_home  w_pct_home  min_home  \
game_id  game_date
0        1950-11-01  4.831833e+09     0.0     0.0         0.0       0.0
         1950-11-02  3.221225e+09     0.0     0.0         0.0       0.0
         1950-11-04  8.053058e+09     0.0     0.0         0.0       0.0
         1950-11-05  4.831838e+09     0.0     0.0         0.0       0.0
         1950-11-07  3.221223e+09     0.0     0.0         0.0       0.0
...                           ...     ...     ...         ...       ...
49900084 2000-06-09  0.000000e+00     0.0     0.0         0.0       0.0
49900085 2000-06-11  0.000000e+00     0.0     0.0         0.0       0.0
49900086 2000-06-14  0.000000e+00     0.0     0.0         0.0       0.0
49900087 2000-06-16  0.000000e+00     0.0     0.0         0.0       0.0
49900088 2000-06-19  0.000000e+00     0.0     0.0         0.0       0.0

                     fgm_home  fga_home  fg_pct_home  fg3m_home  fg3a_home  \
game_id  game_date
0        1950-11-01      37.0       0.0          0.0        0.0        0.0
         1950-11-02      60.0       0.0          0.0        0.0        0.0
         1950-11-04     123.0       0.0          0.0        0.0        0.0
         1950-11-05      93.0       0.0          0.0        0.0        0.0
         1950-11-07      66.0       0.0          0.0        0.0        0.0
...                       ...       ...          ...        ...        ...
49900084 2000-06-09       0.0       0.0          0.0        0.0        0.0
49900085 2000-06-11       0.0       0.0          0.0        0.0        0.0
49900086 2000-06-14       0.0       0.0          0.0        0.0        0.0
49900087 2000-06-16       0.0       0.0          0.0        0.0        0.0
49900088 2000-06-19       0.0       0.0          0.0        0.0        0.0

                     fg3_pct_home  ftm_home  fta_home  ft_pct_home  oreb_home  \
game_id  game_date
0        1950-11-01           0.0      26.0       0.0          0.0        0.0
         1950-11-02           0.0      51.0      71.0          2.0        0.0
         1950-11-04           0.0     111.0     140.0          4.0        0.0
         1950-11-05           0.0      70.0     102.0          3.0        0.0
         1950-11-07           0.0      37.0      49.0          2.0        0.0
...                           ...       ...       ...          ...        ...
49900084 2000-06-09           0.0       0.0       0.0          0.0        0.0
49900085 2000-06-11           0.0       0.0       0.0          0.0        0.0
49900086 2000-06-14           0.0       0.0       0.0          0.0        0.0
49900087 2000-06-16           0.0       0.0       0.0          0.0        0.0
49900088 2000-06-19           0.0       0.0       0.0          0.0        0.0

                     dreb_home  reb_home  ast_home  stl_home  blk_home  \
game_id  game_date
0        1950-11-01        0.0       0.0       0.0       0.0       0.0
         1950-11-02        0.0       0.0       0.0       0.0       0.0
         1950-11-04        0.0       0.0       0.0       0.0       0.0
         1950-11-05        0.0       0.0       0.0       0.0       0.0
         1950-11-07        0.0       0.0       0.0       0.0       0.0
...                        ...       ...       ...       ...       ...
49900084 2000-06-09        0.0       0.0       0.0       0.0       0.0
49900085 2000-06-11        0.0       0.0       0.0       0.0       0.0
49900086 2000-06-14        0.0       0.0       0.0       0.0       0.0
49900087 2000-06-16        0.0       0.0       0.0       0.0       0.0
49900088 2000-06-19        0.0       0.0       0.0       0.0       0.0

                     tov_home  pf_home  pts_home  a_team_id_home  season_year  \
game_id  game_date
0        1950-11-01       0.0      0.0     288.0    4.831836e+09            0
         1950-11-02       0.0      0.0     171.0    3.221226e+09            0
         1950-11-04       0.0      0.0     446.0    8.053061e+09            0
         1950-11-05       0.0      0.0     256.0    4.831836e+09            0
         1950-11-07       0.0      0.0     169.0    3.221223e+09            0
...                       ...      ...       ...             ...          ...
49900084 2000-06-09       0.0      0.0       0.0    0.000000e+00         1999
49900085 2000-06-11       0.0      0.0       0.0    0.000000e+00         1999
49900086 2000-06-14       0.0      0.0       0.0    0.000000e+00         1999
49900087 2000-06-16       0.0      0.0       0.0    0.000000e+00         1999
49900088 2000-06-19       0.0      0.0       0.0    0.000000e+00         1999

                     team_id_away  w_away  l_away  w_pct_away  min_away  \
game_id  game_date
0        1950-11-01             0     0.0     0.0         0.0         0
         1950-11-02             0     0.0     0.0         0.0         0
         1950-11-04             0     0.0     0.0         0.0         0
         1950-11-05             0     0.0     0.0         0.0         0
         1950-11-07             0     0.0     0.0         0.0         0
...                           ...     ...     ...         ...       ...
49900084 2000-06-09    1610612754     0.0     0.0         0.0       240
49900085 2000-06-11    1610612747     0.0     0.0         0.0       240
49900086 2000-06-14    1610612747     0.0     0.0         0.0       265
49900087 2000-06-16    1610612747     0.0     0.0         0.0       240
49900088 2000-06-19    1610612754     0.0     0.0         0.0       240

                     fgm_away  fga_away  fg_pct_away  fg3m_away  fg3a_away  \
game_id  game_date
0        1950-11-01       0.0       0.0        0.000        0.0        0.0
         1950-11-02       0.0       0.0        0.000        0.0        0.0
         1950-11-04       0.0       0.0        0.000        0.0        0.0
         1950-11-05       0.0       0.0        0.000        0.0        0.0
         1950-11-07       0.0       0.0        0.000        0.0        0.0
...                       ...       ...          ...        ...        ...
49900084 2000-06-09      33.0      88.0        0.375        5.0       20.0
49900085 2000-06-11      38.0      76.0        0.500        7.0       17.0
49900086 2000-06-14      48.0      93.0        0.516        4.0       12.0
49900087 2000-06-16      36.0      90.0        0.400        4.0       19.0
49900088 2000-06-19      36.0      77.0        0.468       12.0       25.0

                     fg3_pct_away  ftm_away  fta_away  ft_pct_away  oreb_away  \
game_id  game_date
0        1950-11-01         0.000       0.0       0.0          0.0        0.0
         1950-11-02         0.000       0.0       0.0          0.0        0.0
         1950-11-04         0.000       0.0       0.0          0.0        0.0
         1950-11-05         0.000       0.0       0.0          0.0        0.0
         1950-11-07         0.000       0.0       0.0          0.0        0.0
...                           ...       ...       ...          ...        ...
49900084 2000-06-09         0.250      33.0      39.0          1.0       13.0
49900085 2000-06-11         0.412       8.0      19.0          0.0        8.0
49900086 2000-06-14         0.333      20.0      30.0          1.0       14.0
49900087 2000-06-16         0.211      11.0      21.0          1.0       13.0
49900088 2000-06-19         0.480      27.0      32.0          1.0        9.0

                     dreb_away  reb_away  ast_away  stl_away  blk_away  \
game_id  game_date
0        1950-11-01        0.0         0       0.0       0.0       0.0
         1950-11-02        0.0         0       0.0       0.0       0.0
         1950-11-04        0.0         0       0.0       0.0       0.0
         1950-11-05        0.0         0       0.0       0.0       0.0
         1950-11-07        0.0         0       0.0       0.0       0.0
...                        ...       ...       ...       ...       ...
49900084 2000-06-09       33.0        46      19.0       5.0       5.0
49900085 2000-06-11       25.0        33      23.0       9.0       4.0
49900086 2000-06-14       28.0        42      20.0       6.0       4.0
49900087 2000-06-16       21.0        34      18.0       9.0       2.0
49900088 2000-06-19       32.0        41      24.0       2.0       6.0

                     tov_away  pf_away  pts_away  a_team_id_away
game_id  game_date
0        1950-11-01       0.0      0.0         0               0
         1950-11-02       0.0      0.0         0               0
         1950-11-04       0.0      0.0         0               0
         1950-11-05       0.0      0.0         0               0
         1950-11-07       0.0      0.0         0               0
...                       ...      ...       ...             ...
49900084 2000-06-09       4.0     38.0       104      1610612747
49900085 2000-06-11      16.0     27.0        91      1610612754
49900086 2000-06-14      12.0     31.0       120      1610612754
49900087 2000-06-16      12.0     33.0        87      1610612754
49900088 2000-06-19       9.0     27.0       111      1610612747

[71621 rows x 49 columns]

In [22]:
df

,game_id,game_date,matchup_home,team_id_home,is_home,wl_home,w_home,l_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,a_team_id_home,season_year,season_type,season,team_id_away,w_away,l_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,a_team_id_away,matchup_away,wl_away
3,0,2009-01-12,IND @ UTA,1.610613e+09,t,W,23.0,15.0,0.605,240.0,39.0,85.0,0.459,8.0,18.0,0.444,34.0,37.0,1.0,9.0,31.0,40.0,24.0,10.0,6.0,8.0,20.0,120.0,1.610613e+09,0,Regular Season,2008-09,0,0.0,0.0,0.000,0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0,0,NaN,NaN
6,0,1999-04-21,TOR @ WAS,1.610613e+09,t,L,NaN,NaN,NaN,240.0,38.0,85.0,0.447,3.0,8.0,0.375,12.0,19.0,1.0,16.0,27.0,43.0,18.0,7.0,3.0,15.0,24.0,91.0,1.610613e+09,0,Regular Season,1998-99,0,0.0,0.0,0.000,0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0,0,NaN,NaN
7,0,1999-04-18,BOS @ WAS,1.610613e+09,t,L,NaN,NaN,NaN,240.0,33.0,76.0,0.434,4.0,7.0,0.571,28.0,40.0,1.0,11.0,28.0,39.0,23.0,9.0,5.0,17.0,26.0,98.0,1.610613e+09,0,Regular Season,1998-99,0,0.0,0.0,0.000,0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0,0,NaN,NaN
8,0,1999-04-16,CHI @ WAS,1.610613e+09,t,W,NaN,NaN,NaN,240.0,37.0,83.0,0.446,2.0,10.0,0.200,11.0,15.0,1.0,6.0,45.0,51.0,21.0,9.0,4.0,14.0,16.0,87.0,1.610613e+09,0,Regular Season,1998-99,0,0.0,0.0,0.000,0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0,0,NaN,NaN
9,0,2008-12-13,ORL @ UTA,1.610613e+09,t,L,15.0,10.0,0.600,240.0,33.0,77.0,0.429,8.0,18.0,0.444,20.0,29.0,1.0,17.0,29.0,46.0,25.0,11.0,4.0,22.0,23.0,94.0,1.610613e+09,0,Regular Season,2008-09,0,0.0,0.0,0.000,0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125613,20800441,2008-12-27,NaN,NaN,f,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008,Regular Season,2008-09,1610612765,17.0,11.0,0.607,240,34.0,79.0,0.430,3.0,16.0,0.188,16.0,20.0,1.0,15.0,38.0,53,16.0,8.0,5.0,12.0,27.0,87,1610612749,MIL vs. DET,W
125614,20800052,2008-11-05,NaN,NaN,f,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008,Regular Season,2008-09,1610612765,4.0,0.0,1.000,240,39.0,85.0,0.459,3.0,12.0,0.250,19.0,22.0,1.0,10.0,33.0,43,21.0,6.0,5.0,5.0,18.0,100,1610612761,TOR vs. DET,W
125615,20800042,2008-11-03,NaN,NaN,f,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008,Regular Season,2008-09,1610612765,3.0,0.0,1.000,240,42.0,84.0,0.500,8.0,16.0,0.500,9.0,11.0,1.0,16.0,26.0,42,23.0,4.0,4.0,8.0,22.0,101,1610612766,CHA vs. DET,W
125618,10800025,NaT,NaN,NaN,f,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008,Pre Season,2008-09,1610612765,3.0,0.0,1.000,240,27.0,67.0,0.403,1.0,6.0,0.167,18.0,26.0,1.0,5.0,31.0,36,18.0,13.0,4.0,17.0,17.0,73,1610612764,WAS vs. DET,W
125621,20801029,2009-03-20,NaN,NaN,f,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008,Regular Season,2008-09,1610612762,43.0,26.0,0.623,240,41.0,84.0,0.488,1.0,7.0,0.143,18.0,26.0,1.0,11.0,30.0,41,24.0,8.0,3.0,10.0,13.0,101,1610612760,OKC vs. UTA,W

In [23]:
#pd.merge(df_games, empty_df, on=['game_id', 'game_date']).set_index(['game_id', 'game_date'])

In [24]:
#pd.merge(df_games, empty_df, on=['game_id', 'game_date']).set_index(['game_id', 'game_date'])

In [25]:
df_years = pd.to_datetime(df_games.game_date)
df_years

3        2009-01-12
6        1999-04-21
7        1999-04-18
8        1999-04-16
9        2008-12-13
            ...
125617          NaT
125619   2009-04-03
125620   2009-03-24
125622   2009-02-23
125623   2009-02-19
Name: game_date, Length: 62812, dtype: datetime64[ns]

In [26]:
df_years.dt.year.value_counts().sort_values()

1950.0     157
1958.0     298
1957.0     306
1955.0     307
1959.0     307
1960.0     315
1954.0     317
1956.0     321
1961.0     342
1963.0     354
1965.0     356
1953.0     357
1951.0     362
1952.0     363
1962.0     364
1964.0     366
1966.0     376
1967.0     438
1968.0     521
1969.0     568
1970.0     607
1971.0     649
1972.0     655
1974.0     661
1973.0     664
1975.0     732
2018.0     770
1976.0     812
1998.0     838
1980.0     855
1981.0     860
1979.0     879
1978.0     881
1977.0     899
2011.0     916
1983.0     969
1986.0     971
1985.0     978
1987.0     982
1982.0     983
1984.0    1001
1988.0    1065
1989.0    1122
1992.0    1148
1991.0    1185
1990.0    1186
1994.0    1187
1993.0    1194
1999.0    1213
1995.0    1223
2001.0    1237
2017.0    1246
2004.0    1248
1997.0    1249
2003.0    1254
2002.0    1257
2000.0    1269
1996.0    1270
2009.0    1279
2010.0    1279
2015.0    1282
2016.0    1289
2007.0    1299
2013.0    1307
2008.0    1308
2014.0    1309
2005.0    1323
2006.0    1340
2012.0    1463
Name: game_date, dtype: int64

In [27]:
df_teams = pd.read_csv('C:\\Users\\Paul\\sb\\Untitled Folder\\raw_data\\nba_teams_all.csv')
df_teams.head()

   league_id     team_id  min_year  max_year abbreviation
0          0  1610612737    1949.0    2018.0          ATL
1          0  1610612738    1946.0    2018.0          BOS
2          0  1610612739    1970.0    2018.0          CLE
3          0  1610612740    2002.0    2018.0          NOP
4          0  1610612741    1966.0    2018.0          CHI

In [28]:
df_games = df_games[df_games.season_type == 'Regular Season'][(df_games.season == '2006-07') |
                                                   (df_games.season == '2007-08') |
                                                   (df_games.season == '2008-09') |
                                                   (df_games.season == '2009-10') | 
                                                   (df_games.season == '2010-11') |
                                                   (df_games.season == '2011-12') |
                                                   (df_games.season == '2012-13') |
                                                   (df_games.season == '2013-14') |
                                                   (df_games.season == '2014-15') |
                                                   (df_games.season == '2015-16') | 
                                                   (df_games.season == '2016-17') | 
                                                   (df_games.season == '2017-18')]
df_games

C:\Users\Paul\anaconda3\lib\site-packages\ipykernel_launcher.py:12: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  if sys.path[0] == '':

,game_id,game_date,matchup_home,team_id_home,is_home,wl_home,w_home,l_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,a_team_id_home,season_year,season_type,season,team_id_away,w_away,l_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,a_team_id_away
3,0,2009-01-12,IND @ UTA,1610612762,t,W,23.0,15.0,0.605,240,39.0,85.0,0.459,8.0,18.0,0.444,34.0,37.0,1.0,9.0,31.0,40,24.0,10.0,6.0,8.0,20.0,120,1610612754,0,Regular Season,2008-09,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
9,0,2008-12-13,ORL @ UTA,1610612762,t,L,15.0,10.0,0.600,240,33.0,77.0,0.429,8.0,18.0,0.444,20.0,29.0,1.0,17.0,29.0,46,25.0,11.0,4.0,22.0,23.0,94,1610612753,0,Regular Season,2008-09,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10,0,2008-12-11,POR @ UTA,1610612762,t,W,15.0,9.0,0.625,240,35.0,72.0,0.486,3.0,10.0,0.300,24.0,30.0,1.0,10.0,28.0,38,23.0,9.0,1.0,11.0,21.0,97,1610612757,0,Regular Season,2008-09,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
11,0,2009-04-01,WAS @ MEM,1610612763,t,W,20.0,54.0,0.270,240,38.0,79.0,0.481,8.0,18.0,0.444,28.0,34.0,1.0,12.0,25.0,37,21.0,10.0,6.0,12.0,22.0,112,1610612764,0,Regular Season,2008-09,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
15,0,2009-02-09,NOH @ MEM,1610612763,t,W,15.0,36.0,0.294,240,28.0,77.0,0.364,3.0,15.0,0.200,26.0,35.0,1.0,20.0,44.0,64,18.0,3.0,9.0,18.0,21.0,85,1610612740,0,Regular Season,2008-09,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125616,0,2008-11-01,WAS @ DET,1610612765,t,W,2.0,0.0,1.000,240,42.0,79.0,0.532,6.0,14.0,0.429,27.0,32.0,1.0,16.0,33.0,49,24.0,5.0,7.0,17.0,24.0,117,1610612764,0,Regular Season,2008-09,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
125619,0,2009-04-03,MIN @ UTA,1610612762,t,L,46.0,30.0,0.605,240,36.0,75.0,0.480,5.0,11.0,0.455,25.0,29.0,1.0,4.0,24.0,28,22.0,11.0,4.0,10.0,16.0,102,1610612750,0,Regular Season,2008-09,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
125620,0,2009-03-24,HOU @ UTA,1610612762,t,W,44.0,26.0,0.629,240,38.0,85.0,0.447,4.0,14.0,0.286,19.0,25.0,1.0,3.0,39.0,42,23.0,6.0,12.0,8.0,17.0,99,1610612745,0,Regular Season,2008-09,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
125622,0,2009-02-23,ATL @ UTA,1610612762,t,W,34.0,23.0,0.596,240,44.0,88.0,0.500,6.0,13.0,0.462,14.0,17.0,1.0,14.0,29.0,43,30.0,11.0,6.0,15.0,19.0,108,1610612737,0,Regular Season,2008-09,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
125623,0,2009-02-19,BOS @ UTA,1610612762,t,W,32.0,23.0,0.582,240,32.0,77.0,0.416,2.0,10.0,0.200,24.0,31.0,1.0,7.0,28.0,35,16.0,7.0,6.0,11.0,18.0,90,1610612738,0,Regular Season,2008-09,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [29]:
df_games = pd.merge(df_games
         , df_teams[['team_id','abbreviation']], on=['team_id'], how='left')
df_games

KeyError: 'team_id'

In [ ]:
df_games.sort_values('game_id')

In [ ]:
df_games[df_games['game_id'] == 20600001]

In [ ]:
df_games = df_games[df_games['game_date'].notnull()]

In [ ]:
df_games.shape

In [ ]:
df_games.sort_values('game_id', inplace=True)

In [ ]:
df_games = df_games.reset_index().drop(columns='index')
df_games

In [ ]:
game_ids = df_games.game_id.unique()
game_ids

In [ ]:
df_games['game_date'] = pd.to_datetime(df_games['game_date'])

In [ ]:
def build_game_date_indexed_rows():
    df_empty = pd.DataFrame({})

    for id_ in game_ids:

        visitor_ = df_games[df_games['is_home'] == 'f'][df_games['game_id'] == id_]
        home_ = df_games[df_games['is_home'] == 't'][df_games['game_id'] == id_]


        #visitor team abbreviation
        s0 = str('_') + df_games[df_games['game_id'] == id_][df_games['is_home'] == 'f']['abbreviation'].iloc[0]

        #home team abbreviation
        s1 = str('_') + df_games[df_games['game_id'] == id_][df_games['is_home'] == 't']['abbreviation'].iloc[0]


        df_single_game = pd.merge(visitor_, home_, on=['game_id', 'game_date'], how='inner', suffixes=[s0, s1])

        df_empty = pd.concat([df_empty, df_single_game])
    
    df_empty = df_empty.reset_index().drop(columns='index').set_index(['game_id', 'game_date'])
    return df_empty

In [ ]:
import time
start_time = time.time()

In [ ]:

df = build_game_date_indexed_rows()

In [ ]:
df

In [ ]:
print("--- %s seconds ---" % (time.time() - start_time))

In [ ]:
print("--- %s minutes ---" % ((time.time() - start_time) / 60))

In [ ]:
df.iloc[:, 1]

In [ ]:
datapath = 'C:\\Users\\Paul\\sb\\DSCapstone2\\processed_data'

if not os.path.exists(datapath):
    os.mkdir(datapath)
    
datapath_df = os.path.join(datapath, '1games_df.csv')
if not os.path.exists(datapath_df):
    df.to_csv(datapath_df, index=True)