# Basics and Package Structure

If you're just interested in pulling data, you will primarily be using `nba_api.stats.endpoints`.
This submodule contains a class for each API endpoint supported by stats.nba.com.
For example, [the PlayerCareerStats class](https://github.com/swar/nba_api/blob/master/nba_api/stats/endpoints/playercareerstats.py) is initialized with a player ID and returns some career statistics for the player.

In [1]:
from nba_api.stats.endpoints import playercareerstats
# Anthony Davis
career = playercareerstats.PlayerCareerStats(player_id='203076')
career.get_data_frames()[0]

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,203076,2012-13,00,1610612740,NOH,20.0,64,60,1846.0,349,...,0.751,165,357,522,63,75,112,89,158,867
1,203076,2013-14,00,1610612740,NOP,21.0,67,66,2358.0,522,...,0.791,207,466,673,105,89,189,109,200,1394
2,203076,2014-15,00,1610612740,NOP,22.0,68,68,2455.0,642,...,0.805,173,523,696,149,100,200,95,141,1656
3,203076,2015-16,00,1610612740,NOP,23.0,61,61,2164.0,560,...,0.758,130,497,627,116,78,125,121,148,1481
4,203076,2016-17,00,1610612740,NOP,24.0,75,75,2708.0,770,...,0.802,172,712,884,157,94,167,181,168,2099
5,203076,2017-18,00,1610612740,NOP,25.0,75,75,2727.0,780,...,0.828,187,644,831,174,115,193,162,159,2110
6,203076,2018-19,00,1610612740,NOP,26.0,56,56,1850.0,530,...,0.794,174,498,672,218,88,135,112,132,1452
7,203076,2019-20,00,1610612747,LAL,27.0,62,62,2131.0,551,...,0.846,142,435,577,200,91,143,154,156,1618
8,203076,2020-21,00,1610612747,LAL,28.0,23,23,755.0,204,...,0.715,47,146,193,70,31,41,45,42,518

`career`, above, is a `PlayerCareerStats` object.
This class (and the other endpoint classes) supports several methods of accessing the data: `get_dict()`, `get_json()`, `get_data_frames()`, and more.
`get_data_frames()` returns a list of pandas DataFrames, and when working in notebooks, this is often your best option for viewing data.
In general, the first DataFrame in this list is the primary returned data structure and the one you'll want to look at.

Almost all of the endpoint classes take at least one required argument, along with several optional ones.
In the case of `PlayerCareerStats`, a player ID is required, but the user may also specify a league ID.

At the time of writing this notebook, these are the endpoints available:

<table><tr></tr><tr><td>boxscoreadvancedv2</td><td>boxscorefourfactorsv2</td><td>boxscoremiscv2</td><td>boxscoreplayertrackv2</td></tr><tr><td>boxscorescoringv2</td><td>boxscoresummaryv2</td><td>boxscoretraditionalv2</td><td>boxscoreusagev2</td></tr><tr><td>commonallplayers</td><td>commonplayerinfo</td><td>commonplayoffseries</td><td>commonteamroster</td></tr><tr><td>commonteamyears</td><td>defensehub</td><td>draftcombinedrillresults</td><td>draftcombinenonstationaryshooting</td></tr><tr><td>draftcombineplayeranthro</td><td>draftcombinespotshooting</td><td>draftcombinestats</td><td>drafthistory</td></tr><tr><td>franchisehistory</td><td>homepageleaders</td><td>homepagev2</td><td>infographicfanduelplayer</td></tr><tr><td>leaderstiles</td><td>leaguedashlineups</td><td>leaguedashplayerbiostats</td><td>leaguedashplayerclutch</td></tr><tr><td>leaguedashplayerptshot</td><td>leaguedashplayershotlocations</td><td>leaguedashplayerstats</td><td>leaguedashptdefend</td></tr><tr><td>leaguedashptstats</td><td>leaguedashptteamdefend</td><td>leaguedashteamclutch</td><td>leaguedashteamptshot</td></tr><tr><td>leaguedashteamshotlocations</td><td>leaguedashteamstats</td><td>leaguegamefinder</td><td>leaguegamelog</td></tr><tr><td>leagueleaders</td><td>leaguestandings</td><td>playbyplay</td><td>playbyplayv2</td></tr><tr><td>playerawards</td><td>playercareerstats</td><td>playercompare</td><td>playerdashboardbyclutch</td></tr><tr><td>playerdashboardbygamesplits</td><td>playerdashboardbygeneralsplits</td><td>playerdashboardbylastngames</td><td>playerdashboardbyopponent</td></tr><tr><td>playerdashboardbyshootingsplits</td><td>playerdashboardbyteamperformance</td><td>playerdashboardbyyearoveryear</td><td>playerdashptpass</td></tr><tr><td>playerdashptreb</td><td>playerdashptshotdefend</td><td>playerdashptshots</td><td>playerfantasyprofile</td></tr><tr><td>playerfantasyprofilebargraph</td><td>playergamelog</td><td>playergamestreakfinder</td><td>playernextngames</td></tr><tr><td>playerprofilev2</td><td>playersvsplayers</td><td>playervsplayer</td><td>playoffpicture</td></tr><tr><td>scoreboard</td><td>scoreboardv2</td><td>shotchartdetail</td><td>shotchartlineupdetail</td></tr><tr><td>teamdashboardbyclutch</td><td>teamdashboardbygamesplits</td><td>teamdashboardbygeneralsplits</td><td>teamdashboardbylastngames</td></tr><tr><td>teamdashboardbyopponent</td><td>teamdashboardbyshootingsplits</td><td>teamdashboardbyteamperformance</td><td>teamdashboardbyyearoveryear</td></tr><tr><td>teamdashlineups</td><td>teamdashptpass</td><td>teamdashptreb</td><td>teamdashptshots</td></tr><tr><td>teamdetails</td><td>teamgamelog</td><td>teamgamestreakfinder</td><td>teamhistoricalleaders</td></tr><tr><td>teaminfocommon</td><td>teamplayerdashboard</td><td>teamplayeronoffdetails</td><td>teamplayeronoffsummary</td></tr><tr><td>teamvsplayer</td><td>teamyearbyyearstats</td><td>videodetails</td><td>videoevents</td></tr><tr><td>videostatus</td></tr></table>

In [22]:
help(playerdashboardbylastngames)

Help on module nba_api.stats.endpoints.playerdashboardbylastngames in nba_api.stats.endpoints:

NAME
    nba_api.stats.endpoints.playerdashboardbylastngames

CLASSES
    nba_api.stats.endpoints._base.Endpoint(builtins.object)
        PlayerDashboardByLastNGames

    class PlayerDashboardByLastNGames(nba_api.stats.endpoints._base.Endpoint)
     |  PlayerDashboardByLastNGames(player_id, last_n_games='0', measure_type_detailed='Base', month='0', opponent_team_id=0, pace_adjust='N', per_mode_detailed='Totals', period='0', plus_minus='N', rank='N', season='2020-21', season_type_playoffs='Regular Season', date_from_nullable='', date_to_nullable='', game_segment_nullable='', league_id_nullable='', location_nullable='', outcome_nullable='', po_round_nullable='', season_segment_nullable='', shot_clock_range_nullable='', vs_conference_nullable='', vs_division_nullable='', proxy=None, headers=None, timeout=30, get_request=True)
     |
     |  Method resolution order:
     |      PlayerDashboardByLastNGames
     |      nba_api.stats.endpoints._base.Endpoint
     |      builtins.object
     |
     |  Methods defined here:
     |
     |  __init__(self, player_id, last_n_games='0', measure_type_detailed='Base', month='0', opponent_team_id=0, pace_adjust='N', per_mode_detailed='Totals', period='0', plus_minus='N', rank='N', season='2020-21', season_type_playoffs='Regular Season', date_from_nullable='', date_to_nullable='', game_segment_nullable='', league_id_nullable='', location_nullable='', outcome_nullable='', po_round_nullable='', season_segment_nullable='', shot_clock_range_nullable='', vs_conference_nullable='', vs_division_nullable='', proxy=None, headers=None, timeout=30, get_request=True)
     |      Initialize self.  See help(type(self)) for accurate signature.
     |
     |  get_request(self)
     |
     |  load_response(self)
     |
     |  ----------------------------------------------------------------------
     |  Data and other attributes defined here:
     |
     |  data_sets = None
     |
     |  endpoint = 'playerdashboardbylastngames'
     |
     |  expected_data = {'GameNumberPlayerDashboard': ['GROUP_SET', 'GROUP_VAL...
     |
     |  headers = None
     |
     |  nba_response = None
     |
     |  player_stats = None
     |
     |  team_stats = None
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from nba_api.stats.endpoints._base.Endpoint:
     |
     |  get_available_data(self)
     |
     |  get_data_frames(self)
     |
     |  get_dict(self)
     |
     |  get_json(self)
     |
     |  get_normalized_dict(self)
     |
     |  get_normalized_json(self)
     |
     |  get_request_url(self)
     |
     |  get_response(self)
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors inherited from nba_api.stats.endpoints._base.Endpoint:
     |
     |  __dict__
     |      dictionary for instance variables (if defined)
     |
     |  __weakref__
     |      list of weak references to the object (if defined)
     |
     |  ----------------------------------------------------------------------
     |  Data and other attributes inherited from nba_api.stats.endpoints._base.Endpoint:
     |
     |  DataSet = <class 'nba_api.stats.endpoints._base.Endpoint.DataSet'>

FILE
    c:\users\paul\anaconda3\lib\site-packages\nba_api\stats\endpoints\playerdashboardbylastngames.py

In [9]:
from nba_api.stats.static import teams 
teams = teams.get_teams()
GSW = [x for x in teams if x['full_name'] == 'Golden State Warriors'][0]
GSW_id = GSW['id']

In [10]:
from nba_api.stats.endpoints import playerdashboardbylastngames

In [13]:
playerdashboardbylastngames.PlayerDashboardByLastNGames(player_id=203076).get_data_frames()[0]

,GROUP_SET,GROUP_VALUE,GP,W,L,W_PCT,MIN,FGM,FGA,FG_PCT,...,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,CFID,CFPARAMS
0,Overall,2020-21,23,17,6,0.739,755.011667,204,383,0.533,...,1,1,1,1,1,1,1,1,34,2020-21

In [3]:
playerdashboardbylastngames.__init__('GameNumberPlayerDashboard', player_id=203076)

TypeError: 'player_id' is an invalid keyword argument for module()

In [27]:
playerdashboardbylastngames.get_data_frames()

AttributeError: module 'nba_api.stats.endpoints.playerdashboardbylastngames' has no attribute 'get_data_frames'

In [20]:
playerdashboardbylastngames.month

AttributeError: module 'nba_api.stats.endpoints.playerdashboardbylastngames' has no attribute 'month'

In [19]:
help(playerdashboardbylastngames)

Help on module nba_api.stats.endpoints.playerdashboardbylastngames in nba_api.stats.endpoints:

NAME
    nba_api.stats.endpoints.playerdashboardbylastngames

CLASSES
    nba_api.stats.endpoints._base.Endpoint(builtins.object)
        PlayerDashboardByLastNGames

    class PlayerDashboardByLastNGames(nba_api.stats.endpoints._base.Endpoint)
     |  PlayerDashboardByLastNGames(player_id, last_n_games='0', measure_type_detailed='Base', month='0', opponent_team_id=0, pace_adjust='N', per_mode_detailed='Totals', period='0', plus_minus='N', rank='N', season='2020-21', season_type_playoffs='Regular Season', date_from_nullable='', date_to_nullable='', game_segment_nullable='', league_id_nullable='', location_nullable='', outcome_nullable='', po_round_nullable='', season_segment_nullable='', shot_clock_range_nullable='', vs_conference_nullable='', vs_division_nullable='', proxy=None, headers=None, timeout=30, get_request=True)
     |
     |  Method resolution order:
     |      PlayerDashboardByLastNGames
     |      nba_api.stats.endpoints._base.Endpoint
     |      builtins.object
     |
     |  Methods defined here:
     |
     |  __init__(self, player_id, last_n_games='0', measure_type_detailed='Base', month='0', opponent_team_id=0, pace_adjust='N', per_mode_detailed='Totals', period='0', plus_minus='N', rank='N', season='2020-21', season_type_playoffs='Regular Season', date_from_nullable='', date_to_nullable='', game_segment_nullable='', league_id_nullable='', location_nullable='', outcome_nullable='', po_round_nullable='', season_segment_nullable='', shot_clock_range_nullable='', vs_conference_nullable='', vs_division_nullable='', proxy=None, headers=None, timeout=30, get_request=True)
     |      Initialize self.  See help(type(self)) for accurate signature.
     |
     |  get_request(self)
     |
     |  load_response(self)
     |
     |  ----------------------------------------------------------------------
     |  Data and other attributes defined here:
     |
     |  data_sets = None
     |
     |  endpoint = 'playerdashboardbylastngames'
     |
     |  expected_data = {'GameNumberPlayerDashboard': ['GROUP_SET', 'GROUP_VAL...
     |
     |  headers = None
     |
     |  nba_response = None
     |
     |  player_stats = None
     |
     |  team_stats = None
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from nba_api.stats.endpoints._base.Endpoint:
     |
     |  get_available_data(self)
     |
     |  get_data_frames(self)
     |
     |  get_dict(self)
     |
     |  get_json(self)
     |
     |  get_normalized_dict(self)
     |
     |  get_normalized_json(self)
     |
     |  get_request_url(self)
     |
     |  get_response(self)
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors inherited from nba_api.stats.endpoints._base.Endpoint:
     |
     |  __dict__
     |      dictionary for instance variables (if defined)
     |
     |  __weakref__
     |      list of weak references to the object (if defined)
     |
     |  ----------------------------------------------------------------------
     |  Data and other attributes inherited from nba_api.stats.endpoints._base.Endpoint:
     |
     |  DataSet = <class 'nba_api.stats.endpoints._base.Endpoint.DataSet'>

FILE
    c:\users\paul\anaconda3\lib\site-packages\nba_api\stats\endpoints\playerdashboardbylastngames.py

In [18]:
playerdashboardbylastngames.get_available_data()

AttributeError: module 'nba_api.stats.endpoints.playerdashboardbylastngames' has no attribute 'get_available_data'

In [13]:
from nba_api.stats.endpoints import playerdashboardbyshootingsplits
# get_teams returns a list of 30 dictionaries, each an NBA team.

In [10]:
help(leaguedashplayershotlocations)

Help on module nba_api.stats.endpoints.leaguedashplayershotlocations in nba_api.stats.endpoints:

NAME
    nba_api.stats.endpoints.leaguedashplayershotlocations

CLASSES
    nba_api.stats.endpoints._base.Endpoint(builtins.object)
        LeagueDashPlayerShotLocations

    class LeagueDashPlayerShotLocations(nba_api.stats.endpoints._base.Endpoint)
     |  LeagueDashPlayerShotLocations(distance_range='By Zone', last_n_games='0', measure_type_simple='Base', month='0', opponent_team_id=0, pace_adjust='N', per_mode_detailed='Totals', period='0', plus_minus='N', rank='N', season='2020-21', season_type_all_star='Regular Season', college_nullable='', conference_nullable='', country_nullable='', date_from_nullable='', date_to_nullable='', division_simple_nullable='', draft_pick_nullable='', draft_year_nullable='', game_scope_simple_nullable='', game_segment_nullable='', height_nullable='', league_id_nullable='', location_nullable='', outcome_nullable='', po_round_nullable='', player_experience_nullable='', player_position_abbreviation_nullable='', season_segment_nullable='', shot_clock_range_nullable='', starter_bench_nullable='', team_id_nullable='', vs_conference_nullable='', vs_division_nullable='', weight_nullable='', proxy=None, headers=None, timeout=30, get_request=True)
     |
     |  Method resolution order:
     |      LeagueDashPlayerShotLocations
     |      nba_api.stats.endpoints._base.Endpoint
     |      builtins.object
     |
     |  Methods defined here:
     |
     |  __init__(self, distance_range='By Zone', last_n_games='0', measure_type_simple='Base', month='0', opponent_team_id=0, pace_adjust='N', per_mode_detailed='Totals', period='0', plus_minus='N', rank='N', season='2020-21', season_type_all_star='Regular Season', college_nullable='', conference_nullable='', country_nullable='', date_from_nullable='', date_to_nullable='', division_simple_nullable='', draft_pick_nullable='', draft_year_nullable='', game_scope_simple_nullable='', game_segment_nullable='', height_nullable='', league_id_nullable='', location_nullable='', outcome_nullable='', po_round_nullable='', player_experience_nullable='', player_position_abbreviation_nullable='', season_segment_nullable='', shot_clock_range_nullable='', starter_bench_nullable='', team_id_nullable='', vs_conference_nullable='', vs_division_nullable='', weight_nullable='', proxy=None, headers=None, timeout=30, get_request=True)
     |      Initialize self.  See help(type(self)) for accurate signature.
     |
     |  get_request(self)
     |
     |  load_response(self)
     |
     |  ----------------------------------------------------------------------
     |  Data and other attributes defined here:
     |
     |  data_sets = None
     |
     |  endpoint = 'leaguedashplayershotlocations'
     |
     |  expected_data = {'ShotLocations': [{'columnNames': ['Restricted Area',...
     |
     |  headers = None
     |
     |  nba_response = None
     |
     |  player_stats = None
     |
     |  team_stats = None
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from nba_api.stats.endpoints._base.Endpoint:
     |
     |  get_available_data(self)
     |
     |  get_data_frames(self)
     |
     |  get_dict(self)
     |
     |  get_json(self)
     |
     |  get_normalized_dict(self)
     |
     |  get_normalized_json(self)
     |
     |  get_request_url(self)
     |
     |  get_response(self)
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors inherited from nba_api.stats.endpoints._base.Endpoint:
     |
     |  __dict__
     |      dictionary for instance variables (if defined)
     |
     |  __weakref__
     |      list of weak references to the object (if defined)
     |
     |  ----------------------------------------------------------------------
     |  Data and other attributes inherited from nba_api.stats.endpoints._base.Endpoint:
     |
     |  DataSet = <class 'nba_api.stats.endpoints._base.Endpoint.DataSet'>

FILE
    c:\users\paul\anaconda3\lib\site-packages\nba_api\stats\endpoints\leaguedashplayershotlocations.py

In [14]:
nba_teams = playerdashboardbyshootingsplits.get_available_data()

AttributeError: module 'nba_api.stats.endpoints.playerdashboardbyshootingsplits' has no attribute 'get_available_data'

In [15]:
playerdashboardbyshootingsplits

In [9]:


print('Number of teams fetched: {}'.format(len(nba_teams)))
nba_teams[:3]

TypeError: object of type 'module' has no len()

### Getting Team and Player IDs
The package also includes utilities for fetching player and team information available under `nba_api.stats.static`.
You can use this to fetch player IDs and team IDs, which are often used as inputs to API endpoints.

In [2]:
from nba_api.stats.static import teams
# get_teams returns a list of 30 dictionaries, each an NBA team.
nba_teams = teams.get_teams()
print('Number of teams fetched: {}'.format(len(nba_teams)))
nba_teams[:3]

Number of teams fetched: 30

[{'id': 1610612737,
  'full_name': 'Atlanta Hawks',
  'abbreviation': 'ATL',
  'nickname': 'Hawks',
  'city': 'Atlanta',
  'state': 'Atlanta',
  'year_founded': 1949},
 {'id': 1610612738,
  'full_name': 'Boston Celtics',
  'abbreviation': 'BOS',
  'nickname': 'Celtics',
  'city': 'Boston',
  'state': 'Massachusetts',
  'year_founded': 1946},
 {'id': 1610612739,
  'full_name': 'Cleveland Cavaliers',
  'abbreviation': 'CLE',
  'nickname': 'Cavaliers',
  'city': 'Cleveland',
  'state': 'Ohio',
  'year_founded': 1970}]

In [3]:
from nba_api.stats.static import players
# get_players returns a list of dictionaries, each representing a player.
nba_players = players.get_players()
print('Number of players fetched: {}'.format(len(nba_players)))
nba_players[:5]

Number of players fetched: 4501

[{'id': 76001,
  'full_name': 'Alaa Abdelnaby',
  'first_name': 'Alaa',
  'last_name': 'Abdelnaby',
  'is_active': False},
 {'id': 76002,
  'full_name': 'Zaid Abdul-Aziz',
  'first_name': 'Zaid',
  'last_name': 'Abdul-Aziz',
  'is_active': False},
 {'id': 76003,
  'full_name': 'Kareem Abdul-Jabbar',
  'first_name': 'Kareem',
  'last_name': 'Abdul-Jabbar',
  'is_active': False},
 {'id': 51,
  'full_name': 'Mahmoud Abdul-Rauf',
  'first_name': 'Mahmoud',
  'last_name': 'Abdul-Rauf',
  'is_active': False},
 {'id': 1505,
  'full_name': 'Tariq Abdul-Wahad',
  'first_name': 'Tariq',
  'last_name': 'Abdul-Wahad',
  'is_active': False}]

To search for an individual team or player by its name (or other attribute), dictionary comprehensions are your friend.

In [4]:
spurs = [team for team in nba_teams
         if team['full_name'] == 'San Antonio Spurs'][0]
spurs

{'id': 1610612759,
 'full_name': 'San Antonio Spurs',
 'abbreviation': 'SAS',
 'nickname': 'Spurs',
 'city': 'San Antonio',
 'state': 'Texas',
 'year_founded': 1976}

In [5]:
big_fundamental = [player for player in nba_players
                   if player['full_name'] == 'Tim Duncan'][0]
big_fundamental

{'id': 1495,
 'full_name': 'Tim Duncan',
 'first_name': 'Tim',
 'last_name': 'Duncan',
 'is_active': False}