In [15]:
import pandas as pd

pd.options.display.max_columns = 999
pd.options.display.max_colwidth = 999
pd.options.display.max_rows = 999

In [16]:
from nba_api.stats.endpoints import playerdashboardbylastngames, boxscoreadvancedv2

In [17]:
playerdashboardbylastngames.PlayerDashboardByLastNGames(player_id=203076).get_data_frames()[0]

,GROUP_SET,GROUP_VALUE,GP,W,L,W_PCT,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,TOV,STL,BLK,BLKA,PF,PFD,PTS,PLUS_MINUS,NBA_FANTASY_PTS,DD2,TD3,GP_RANK,W_RANK,L_RANK,W_PCT_RANK,MIN_RANK,FGM_RANK,FGA_RANK,FG_PCT_RANK,FG3M_RANK,FG3A_RANK,FG3_PCT_RANK,FTM_RANK,FTA_RANK,FT_PCT_RANK,OREB_RANK,DREB_RANK,REB_RANK,AST_RANK,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,CFID,CFPARAMS
0,Overall,2020-21,23,17,6,0.739,755.011667,204,383,0.533,17,58,0.293,93,130,0.715,47,146,193,70,45,31,41,13,42,103,518,135,1025.6,8,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,34,2020-21

In [18]:
playerdashboardbylastngames.PlayerDashboardByLastNGames(player_id=203076)

In [19]:
help(boxscoreadvancedv2)

Help on module nba_api.stats.endpoints.boxscoreadvancedv2 in nba_api.stats.endpoints:

NAME
    nba_api.stats.endpoints.boxscoreadvancedv2

CLASSES
    nba_api.stats.endpoints._base.Endpoint(builtins.object)
        BoxScoreAdvancedV2

    class BoxScoreAdvancedV2(nba_api.stats.endpoints._base.Endpoint)
     |  BoxScoreAdvancedV2(game_id, end_period='0', end_range='0', range_type='0', start_period='0', start_range='0', proxy=None, headers=None, timeout=30, get_request=True)
     |
     |  Method resolution order:
     |      BoxScoreAdvancedV2
     |      nba_api.stats.endpoints._base.Endpoint
     |      builtins.object
     |
     |  Methods defined here:
     |
     |  __init__(self, game_id, end_period='0', end_range='0', range_type='0', start_period='0', start_range='0', proxy=None, headers=None, timeout=30, get_request=True)
     |      Initialize self.  See help(type(self)) for accurate signature.
     |
     |  get_request(self)
     |
     |  load_response(self)
     |
     |  ----------------------------------------------------------------------
     |  Data and other attributes defined here:
     |
     |  data_sets = None
     |
     |  endpoint = 'boxscoreadvancedv2'
     |
     |  expected_data = {'PlayerStats': ['GAME_ID', 'TEAM_ID', 'TEAM_ABBREVIAT...
     |
     |  headers = None
     |
     |  nba_response = None
     |
     |  player_stats = None
     |
     |  team_stats = None
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from nba_api.stats.endpoints._base.Endpoint:
     |
     |  get_available_data(self)
     |
     |  get_data_frames(self)
     |
     |  get_dict(self)
     |
     |  get_json(self)
     |
     |  get_normalized_dict(self)
     |
     |  get_normalized_json(self)
     |
     |  get_request_url(self)
     |
     |  get_response(self)
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors inherited from nba_api.stats.endpoints._base.Endpoint:
     |
     |  __dict__
     |      dictionary for instance variables (if defined)
     |
     |  __weakref__
     |      list of weak references to the object (if defined)
     |
     |  ----------------------------------------------------------------------
     |  Data and other attributes inherited from nba_api.stats.endpoints._base.Endpoint:
     |
     |  DataSet = <class 'nba_api.stats.endpoints._base.Endpoint.DataSet'>

FILE
    c:\users\paul\anaconda3\lib\site-packages\nba_api\stats\endpoints\boxscoreadvancedv2.py

In [20]:
boxscoreadvancedv2 = boxscoreadvancedv2.BoxScoreAdvancedV2(game_id='0041700317').get_data_frames()[0]
boxscoreadvancedv2

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
0,0041700317,1610612744,GSW,Golden State,201142,Kevin Durant,F,,44:20,110.4,111.9,96.3,98.8,14.1,13.1,0.200,2.50,15.2,0.000,0.088,0.051,6.1,0.643,0.669,0.286,0.294,93.33,91.49,76.24,84,0.203
1,0041700317,1610612744,GSW,Golden State,203110,Draymond Green,F,,44:08,108.8,111.8,95.7,100.0,13.2,11.8,0.156,1.00,21.7,0.098,0.167,0.137,21.7,0.385,0.385,0.184,0.187,95.21,91.91,76.59,85,0.072
2,0041700317,1610612744,GSW,Golden State,1626172,Kevon Looney,C,,16:58,101.5,94.1,92.5,93.9,9.0,0.2,0.000,0.00,0.0,0.167,0.100,0.132,0.0,0.400,0.340,0.146,0.156,91.99,94.76,78.97,34,0.036
3,0041700317,1610612744,GSW,Golden State,202691,Klay Thompson,G,,30:43,109.0,110.2,106.3,108.3,2.7,1.8,0.056,0.50,5.9,0.000,0.107,0.055,11.8,0.731,0.684,0.239,0.244,94.40,92.99,77.49,59,0.112
4,0041700317,1610612744,GSW,Golden State,201939,Stephen Curry,G,,44:23,109.0,111.8,93.5,96.5,15.5,15.3,0.385,2.00,27.0,0.000,0.158,0.092,13.5,0.614,0.614,0.273,0.278,94.56,91.94,76.62,85,0.214
5,0041700317,1610612744,GSW,Golden State,2733,Shaun Livingston,,,24:28,98.6,97.9,129.0,123.4,-30.4,-25.5,0.059,0.00,25.0,0.043,0.043,0.043,0.0,0.667,0.667,0.056,0.058,89.87,92.23,76.85,47,0.045
6,0041700317,1610612744,GSW,Golden State,1628395,Jordan Bell,,,15:46,131.0,125.8,67.7,71.0,63.4,54.8,0.214,1.50,42.9,0.231,0.071,0.122,28.6,0.000,0.000,0.108,0.115,94.77,94.35,78.62,31,0.050
7,0041700317,1610612744,GSW,Golden State,1626188,Quinn Cook,,,1:26,100.0,50.0,0.0,0.0,100.0,50.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,81.62,117.07,97.56,4,0.500
8,0041700317,1610612744,GSW,Golden State,201156,Nick Young,,,16:50,114.2,112.9,89.2,96.8,25.1,16.1,0.000,0.00,0.0,0.000,0.000,0.000,0.0,1.500,1.500,0.029,0.031,91.63,88.38,73.65,31,0.020
9,0041700317,1610612744,GSW,Golden State,1627775,Patrick McCaw,,,0:59,200.0,100.0,200.0,200.0,0.0,-100.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,73.85,98.46,82.05,2,0.000
10,0041700317,1610612744,GSW,Golden State,201580,JaVale McGee,,DNP - Coach's Decision,None,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0,NaN
11,0041700317,1610612744,GSW,Golden State,2585,Zaza Pachulia,,DNP - Coach's Decision,None,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0,NaN
12,0041700317,1610612744,GSW,Golden State,2561,David West,,DNP - Coach's Decision,None,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0,NaN
13,0041700317,1610612745,HOU,Houston,2772,Trevor Ariza,F,,41:50,87.1,90.0,108.5,108.8,-21.5,-18.8,0.074,1.00,12.5,0.055,0.103,0.074,12.5,0.000,0.000,0.143,0.145,93.42,91.79,76.49,80,-0.074
14,0041700317,1610612745,HOU,Houston,200782,P.J. Tucker,F,,44:34,101.4,105.9,105.5,105.8,-4.1,0.1,0.065,0.67,12.5,0.148,0.095,0.125,18.8,0.667,0.651,0.133,0.135,94.27,92.07,76.73,85,0.109
15,0041700317,1610612745,HOU,Houston,203991,Clint Capela,C,,37:04,94.2,93.2,110.4,114.1,-16.1,-20.9,0.000,0.00,0.0,0.085,0.139,0.108,7.1,0.900,0.791,0.156,0.164,94.27,93.26,77.72,73,0.163
16,0041700317,1610612745,HOU,Houston,201569,Eric Gordon,G,,39:52,100.8,102.6,110.1,110.5,-9.3,-7.9,0.286,6.00,19.4,0.000,0.081,0.035,3.2,0.455,0.484,0.263,0.271,93.09,92.11,76.76,77,0.129
17,0041700317,1610612745,HOU,Houston,201935,James Harden,G,,42:50,93.4,97.6,110.3,113.4,-17.0,-15.9,0.333,1.20,14.0,0.018,0.125,0.063,11.6,0.448,0.492,0.366,0.368,95.22,91.88,76.56,82,0.161
18,0041700317,1610612745,HOU,Houston,101123,Gerald Green,,,20:40,116.8,119.5,103.6,97.5,13.2,22.0,0.000,0.00,0.0,0.000,0.222,0.095,0.0,0.214,0.214,0.135,0.137,92.44,94.06,78.39,41,0.018
19,0041700317,1610612745,HOU,Houston,201583,Ryan Anderson,,,8:00,67.8,62.5,147.8,129.4,-80.1,-66.9,0.000,0.00,0.0,0.083,0.000,0.063,0.0,0.000,0.000,0.000,0.000,88.90,98.98,82.48,16,-0.104
20,0041700317,1610612745,HOU,Houston,2207,Joe Johnson,,,5:10,133.3,120.0,101.5,88.9,31.8,31.1,0.167,0.00,50.0,0.000,0.500,0.222,0.0,0.000,0.000,0.083,0.091,78.51,88.37,73.64,10,0.108
21,0041700317,1610612745,HOU,Houston,204028,Tarik Black,,DNP - Coach's Decision,None,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0,NaN
22,0041700317,1610612745,HOU,Houston,1628935,Aaron Jackson,,DNP - Coach's Decision,None,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0,NaN
23,0041700317,1610612745,HOU,Houston,201601,Luc Mbah a Moute,,DNP - Coach's Decision,None,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0,NaN
24,0041700317,1610612745,HOU,Houston,2403,Nene,,DNP - Coach's Decision,None,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0,NaN
25,0041700317,1610612745,HOU,Houston,101108,Chris Paul,,DNP - Injury/Illness,None,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0,NaN

In [21]:
df2 = pd.read_csv('C:\\Users\\Paul\\sb\\DSCapstone2\\raw_data\\injuries_2010-2020.csv')
df2

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
...,...,...,...,...,...
27100,2020-09-30,Lakers,Dion Waiters,NaN,activated from IL
27101,2020-10-02,Heat,NaN,Bam Adebayo,strained neck (DTD)
27102,2020-10-02,Heat,NaN,Goran Dragic,placed on IL with torn plantar fascia in left foot
27103,2020-10-02,Heat,Chris Silva,NaN,activated from IL
27104,2020-10-06,Heat,Bam Adebayo,NaN,returned to lineup