In [1]:
#use get_dummies as widely as possible

#use scaler anywhere

#use game_id and game_date as index????

# 4 Pre-Processing and Training Data<a id='4_Pre-Processing_and_Training_Data'></a>

## 4.2 Introduction<a id='4.2_Introduction'></a>

## 4.3 Imports<a id='4.3_Imports'></a>

In [2]:
import pandas as pd
import numpy as np
import os
import pickle
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import __version__ as sklearn_version
from sklearn.decomposition import PCA
from sklearn.preprocessing import scale
from sklearn.model_selection import train_test_split, cross_validate, GridSearchCV, learning_curve
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.dummy import DummyRegressor
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.feature_selection import SelectKBest, f_regression
import datetime

pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

## 4.4 Functions<a id='4.4_Imports'></a>

In [3]:
#return the first 5 and last 5 rows of this dataframe
def p(df_):
    if df_.shape[0] > 6:
        print(df_.shape)
        return pd.concat([df_.head(), df_.tail()])
    else:
        return df_

def rcp(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'processed_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'processed_data', file_), parse_dates=pd_)
    
def rcr(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'raw_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'raw_data', file_), parse_dates=pd_)
    
#sort dataframe by column
def s(df_, column_):
    return df_.sort_values(column_)

#reset index and sort dataframe by column
def sr(df_, column_, ascending_=True):
    df_ = df_.sort_values(column_, ascending=ascending_)
    return df_.reset_index(drop=True)

#print length of list
def pl(list_):
    print(len(list_))
    return list_

#print length of dictionary
def pdc(dict_):
    print(len(dict_))
    return dict_

## 4.5 Load Data<a id='4.5_Load_Data'></a>

In [4]:
df = rcp('53AAprediction_stats_2010_2018.csv')
p(df)

(10266, 107)

,game_id,TEAM_NAME_a,TEAM_ABBREVIATION_a,TEAM_CITY_a,team_id_a,spread_a,away_home_a,game_date,matchup,season_type,season,TEAM_NAME_b,TEAM_ABBREVIATION_b,TEAM_CITY_b,team_id_b,E_OFF_RATING_cma_diff,OFF_RATING_cma_diff,E_DEF_RATING_cma_diff,DEF_RATING_cma_diff,E_NET_RATING_cma_diff,NET_RATING_cma_diff,AST_PCT_cma_diff,AST_TOV_cma_diff,AST_RATIO_cma_diff,OREB_PCT_cma_diff,DREB_PCT_cma_diff,REB_PCT_cma_diff,E_TM_TOV_PCT_cma_diff,TM_TOV_PCT_cma_diff,EFG_PCT_cma_diff,TS_PCT_cma_diff,USG_PCT_cma_diff,E_USG_PCT_cma_diff,E_PACE_cma_diff,PACE_cma_diff,PACE_PER40_cma_diff,POSS_cma_diff,PIE_cma_diff,duration_minutes_cma_diff,w_pct_cma_diff,min_cma_diff,fgm_cma_diff,fga_cma_diff,fg_pct_cma_diff,fg3m_cma_diff,fg3a_cma_diff,fg3_pct_cma_diff,ftm_cma_diff,fta_cma_diff,ft_pct_cma_diff,oreb_cma_diff,dreb_cma_diff,reb_cma_diff,ast_cma_diff,stl_cma_diff,blk_cma_diff,tov_cma_diff,pf_cma_diff,pts_cma_diff,spread_cma_diff,away_home_cma_diff,E_OFF_RATING_sm_cma_diff,OFF_RATING_sm_cma_diff,E_DEF_RATING_sm_cma_diff,DEF_RATING_sm_cma_diff,E_NET_RATING_sm_cma_diff,NET_RATING_sm_cma_diff,AST_PCT_sm_cma_diff,AST_TOV_sm_cma_diff,AST_RATIO_sm_cma_diff,OREB_PCT_sm_cma_diff,DREB_PCT_sm_cma_diff,REB_PCT_sm_cma_diff,E_TM_TOV_PCT_sm_cma_diff,TM_TOV_PCT_sm_cma_diff,EFG_PCT_sm_cma_diff,TS_PCT_sm_cma_diff,USG_PCT_sm_cma_diff,E_USG_PCT_sm_cma_diff,E_PACE_sm_cma_diff,PACE_sm_cma_diff,PACE_PER40_sm_cma_diff,POSS_sm_cma_diff,PIE_sm_cma_diff,duration_minutes_sm_cma_diff,w_pct_sm_cma_diff,min_sm_cma_diff,fgm_sm_cma_diff,fga_sm_cma_diff,fg_pct_sm_cma_diff,fg3m_sm_cma_diff,fg3a_sm_cma_diff,fg3_pct_sm_cma_diff,ftm_sm_cma_diff,fta_sm_cma_diff,ft_pct_sm_cma_diff,oreb_sm_cma_diff,dreb_sm_cma_diff,reb_sm_cma_diff,ast_sm_cma_diff,stl_sm_cma_diff,blk_sm_cma_diff,tov_sm_cma_diff,pf_sm_cma_diff,pts_sm_cma_diff,spread_sm_cma_diff,away_home_sm_cma_diff
0,21000001,Celtics,BOS,Boston,1610612738,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,Heat,MIA,Miami,1610612748,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,21000002,Suns,PHX,Phoenix,1610612756,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,Trail Blazers,POR,Portland,1610612757,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,21000003,Rockets,HOU,Houston,1610612745,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,Lakers,LAL,Los Angeles,1610612747,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,21000009,Timberwolves,MIN,Minnesota,1610612750,1,1,2010-10-27,MIN vs. SAC,Regular Season,2010-11,Kings,SAC,Sacramento,1610612758,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,21000006,Heat,MIA,Miami,1610612748,-10,0,2010-10-27,MIA vs. PHI,Regular Season,2010-11,76ers,PHI,Philadelphia,1610612755,87.900000,87.900000,95.700000,95.700000,-7.700000,-7.700000,0.556000,0.880000,12.800000,0.250000,0.732000,0.472000,18.681000,18.700000,0.419000,0.471000,1.0,0.200000,91.500000,91.500000,76.250000,91.000000,0.401000,240.000000,0.000000,240.000000,27.000000,74.000000,0.365000,8.000000,20.000000,0.400000,18.000000,25.000000,0.720000,11.000000,28.000000,39.000000,15.000000,10.000000,6.000000,17.000000,21.000000,80.000000,8.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10261,41700317,Warriors,GSW,Golden State,1610612744,-9,0,2018-05-28,GSW vs. HOU,Playoffs,2017-18,Rockets,HOU,Houston,1610612745,2.533333,1.141667,-7.666667,-6.816667,10.183333,7.950000,0.105500,0.220833,3.358333,-0.006750,-0.002750,0.011500,-0.475083,-0.625000,0.003750,0.005083,0.0,0.002083,3.746667,3.958333,3.297500,3.666667,0.062833,0.000000,0.136167,0.000000,3.916667,4.000000,0.025583,-3.166667,-7.333333,-0.021833,0.583333,0.000000,0.039151,1.250000,2.250000,3.500000,6.166667,0.916667,-0.083333,0.750000,-1.000000,5.250000,-7.583333,0.000000,8.900,6.222222,-8.900,-6.222222,17.800000,12.422222,0.117111,0.593333,4.611111,-0.035333,-0.035333,-0.002444,-0.648444,-0.966667,0.04500,0.047778,0.0,0.002111,0.0,0.0,0.0,0.111111,0.106000,0.0,0.028778,0.0,3.777778,-0.555556,0.050778,-1.111111,-8.777778,0.059333,-0.333333,-3.333333,0.117998,-0.666667,0.888889,0.222222,6.555556,-0.222222,2.222222,0.111111,1.444444,6.111111,-12.222222,-0.111111
10262,41700401,Cavaliers,CLE,Cleveland,1610612739,10,0,2018-05-31,CLE vs. GSW,Playoffs,2017-18,Warriors,GSW,Golden State,1610612744,0.641667,2.991667,5.983333,6.825000,-5.341667,-3.841667,-0.090333,0.285000,-2.408333,0.027583,-0.009833,0.009750,-0.940417,-0.766667,0.001250,0.002500,0.0,-0.001333,-7.474167,-8.649167,-7.207500,-7.416667,-0.027083,2.083333,-0.123333,2.083333,-2.833333,-6.666667,0.003750,-1.250000,-3.000000,-0.002917,1.500000,3.416667,-0.055855,-1.166667,-3.083333,-4.250000,-5.416667,-3.583333,-0.416667,-2.000000,0.666667,-5.416667,3.333333,0.000000,-10.600,-9.100000,10.600,9.100000,-21.100000,-18.200000,-0.254000,-0.610000,-7.900000,0.035500,0.035500,-0.001000,-1.777500,-1.600000,-0.08950,-0.084000,0.0,0.000000,0.0,0.0,0.0,0.500000,-0.205000,0.0,-0.141500,0.0,-4.000000,7.500000,-0.085000,0.000000,-2.500000,0.011000,-0.500000,0.000000,-0.021444,4.000000,-5.000000,-1.000000,-11.500000,1.000000,-4.000000,-1.000000,0.000000,-8.500000,17.000000,0.000000
10263,41700402,Cavaliers,CLE,Cleveland,1610612739,19,0,2018-06-03,CLE vs. GSW,Playoffs,2017-18,Warriors,GSW,Golden State,1610612744,-0.275000,1.616667,5.450000,6.266667,-5.733333,-4.658333,-0.096833,0.158333,-2.625000,0.040083,0.023250,0.028917,-0.634250,-0.491667,-0.002417,-0.005167,0.0,-0.001417,-6.150833,-7.107500,-5.923333,-5.666667,-0.037083,2.083333,-0.170917,2.083333,-2.000000,-4.500000,0.002500,-1.416667,-3.083333,-0.005333,0.666667,2.916667,-0.076499,-0.083333,-1.833333,-1.916667,-5.250000,-3.833333,-0.166667,-1.583333,0.250000,-4.750000,3.500000,-0.083333,-9.900,-10.200000,9.900,10.200000,-19.733333,-20.400000,-0.257667,-1.200000,-8.433333,0.099000,0.099000,0.058000,0.155000,0.200000,-0.08900,-0.090667,0.0,0.000667,0.0,0.0,0.0,1.000000,-0.199333,0.0,-0.427667,0.0,-3.333333,8.000000,-0.079000,-1.000000,-1.333333,-0.023000,-1.333333,0.666667,-0.088538,7.666667,-3.333333,4.333333,-12.000000,-1.000000,-3.666667,0.666667,0.000000,-9.000000,18.000000,-0.333333
10264,41700403,Cavaliers,CLE,Cleveland,1610612739,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,Warriors,GSW,Golden State,1610612744,-1.958333,-0.608333,6.666667,7.500000,-8.633333,-8.116667,-0.070000,-0.006667,-2.416667,0.037417,0.040667,0.034000,-0.010750,0.100000,-0.014083,-0.011917,0.0,-0.001583,-4.626667,-5.416667,-4.514167,-4.583333,-0.044417,0.000000,-0.254250,0.000000,-2.750000,-4.750000,-0.005917,-2.000000,-3.416667,-0.018583,1.833333,3.833333,-0.055607,0.166667,-1.666667,-1.500000,-4.583333,-2.916667,-0.250000,-0.833333,-1.000000,-5.666667,6.333333,-0.083333,-12.425,-13.550000,12.425,13.550000,-24.800000,-27.100000,-0.173250,-0.915000,-7.100000,0.097500,0.097500,0.051500,-0.149500,-0.225000,-0.11775,-0.108250,0.0,-0.000250,0.0,0.0,0.0,1.500000,-0.182000,0.0,-0.570750,0.0,-5.000000,8.000000,-0.099750,-2.250000,-3.250000,-0.038250,0.750000,1.750000,-0.028858,8.000000,-4.500000,3.500000,-9.750000,0.750000,-3.750000,0.000000,-2.500000,-11.500000,23.000000,-0.500000
10265,41700404,Cavaliers,CLE,Cleveland,1610612739,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,Warriors,GSW,Golden State,1610612744,-6.716667,-4.966667,7.100000,7.758333,-13.825000,-12.750000,-0.071167,-0.633333,-3.308333,0.055417,0.045000,0.038583,0.879500,1.058333,-0.040917,-0.036833,0.0,-0.001750,-3.470000,-4.416667,-3.680833,-3.583333,-0.070917,0.000000,-0.365333,0.000000,-4.166667,-3.166667,-0.030833,-2.166667,-2.583333,-0.034333,1.833333,3.916667,-0.060729,1.333333,-1.166667,0.166667,-5.416667,-2.416667,-0.250000,0.166667,-0.916667,-8.666667,10.750000,0.000000,-12.540,-12.760000,12.540,12.760000,-25.040000,-25.560000,-0.167200,-0.936000,-6.920000,0.116800,0.116800,0.068400,0.392200,0.420000,-0.11220,-0.107000,0.0,-0.000600,0.0,0.0,0.0,1.400000,-0.173200,0.0,-0.656600,0.0,-4.400000,8.600000,-0.096600,-1.800000,-1.600000,-0.041800,-0.200000,1.000000,-0.049093,8.200000,-3.400000,4.800000,-9.200000,0.600000,-3.200000,0.600000,-2.400000,-10.800000,21.600000,-0.200000

## 4.6 Get Indicator Variables<a id='4.6 Get_Indicator_Variables'></a>

In [5]:
# Create dummy or indicator features for categorical variables Hint: you’ll need
# to think about your old favorite pandas functions here like get_dummies().

df.select_dtypes('object')

,TEAM_NAME_a,TEAM_ABBREVIATION_a,TEAM_CITY_a,game_date,matchup,season_type,season,TEAM_NAME_b,TEAM_ABBREVIATION_b,TEAM_CITY_b
0,Celtics,BOS,Boston,2010-10-26,BOS vs. MIA,Regular Season,2010-11,Heat,MIA,Miami
1,Suns,PHX,Phoenix,2010-10-26,PHX vs. POR,Regular Season,2010-11,Trail Blazers,POR,Portland
2,Rockets,HOU,Houston,2010-10-26,HOU vs. LAL,Regular Season,2010-11,Lakers,LAL,Los Angeles
3,Timberwolves,MIN,Minnesota,2010-10-27,MIN vs. SAC,Regular Season,2010-11,Kings,SAC,Sacramento
4,Heat,MIA,Miami,2010-10-27,MIA vs. PHI,Regular Season,2010-11,76ers,PHI,Philadelphia
...,...,...,...,...,...,...,...,...,...,...
10261,Warriors,GSW,Golden State,2018-05-28,GSW vs. HOU,Playoffs,2017-18,Rockets,HOU,Houston
10262,Cavaliers,CLE,Cleveland,2018-05-31,CLE vs. GSW,Playoffs,2017-18,Warriors,GSW,Golden State
10263,Cavaliers,CLE,Cleveland,2018-06-03,CLE vs. GSW,Playoffs,2017-18,Warriors,GSW,Golden State
10264,Cavaliers,CLE,Cleveland,2018-06-06,CLE vs. GSW,Playoffs,2017-18,Warriors,GSW,Golden State
10265,Cavaliers,CLE,Cleveland,2018-06-08,CLE vs. GSW,Playoffs,2017-18,Warriors,GSW,Golden State

In [6]:
column_names_categorical_list = list(df.select_dtypes('object').columns) + ['team_id_a', 'team_id_b', 'away_home_a']
pl(column_names_categorical_list)

13

['TEAM_NAME_a',
 'TEAM_ABBREVIATION_a',
 'TEAM_CITY_a',
 'game_date',
 'matchup',
 'season_type',
 'season',
 'TEAM_NAME_b',
 'TEAM_ABBREVIATION_b',
 'TEAM_CITY_b',
 'team_id_a',
 'team_id_b',
 'away_home_a']

In [7]:
column_names_categorical_list_rgi = [k for k in column_names_categorical_list if not k in ['game_date']]
pl(column_names_categorical_list_rgi)

12

['TEAM_NAME_a',
 'TEAM_ABBREVIATION_a',
 'TEAM_CITY_a',
 'matchup',
 'season_type',
 'season',
 'TEAM_NAME_b',
 'TEAM_ABBREVIATION_b',
 'TEAM_CITY_b',
 'team_id_a',
 'team_id_b',
 'away_home_a']

In [8]:
df_indicator_variables = pd.get_dummies(df[column_names_categorical_list_rgi])
p(df_indicator_variables)

(10266, 686)

,team_id_a,team_id_b,away_home_a,TEAM_NAME_a_76ers,TEAM_NAME_a_Bobcats,TEAM_NAME_a_Bucks,TEAM_NAME_a_Bulls,TEAM_NAME_a_Cavaliers,TEAM_NAME_a_Celtics,TEAM_NAME_a_Clippers,TEAM_NAME_a_Grizzlies,TEAM_NAME_a_Hawks,TEAM_NAME_a_Heat,TEAM_NAME_a_Hornets,TEAM_NAME_a_Jazz,TEAM_NAME_a_Kings,TEAM_NAME_a_Knicks,TEAM_NAME_a_Lakers,TEAM_NAME_a_Magic,TEAM_NAME_a_Mavericks,TEAM_NAME_a_Nets,TEAM_NAME_a_Nuggets,TEAM_NAME_a_Pacers,TEAM_NAME_a_Pelicans,TEAM_NAME_a_Pistons,TEAM_NAME_a_Raptors,TEAM_NAME_a_Rockets,TEAM_NAME_a_Spurs,TEAM_NAME_a_Suns,TEAM_NAME_a_Thunder,TEAM_NAME_a_Timberwolves,TEAM_NAME_a_Trail Blazers,TEAM_NAME_a_Warriors,TEAM_ABBREVIATION_a_ATL,TEAM_ABBREVIATION_a_BKN,TEAM_ABBREVIATION_a_BOS,TEAM_ABBREVIATION_a_CHA,TEAM_ABBREVIATION_a_CHI,TEAM_ABBREVIATION_a_CLE,TEAM_ABBREVIATION_a_DAL,TEAM_ABBREVIATION_a_DEN,TEAM_ABBREVIATION_a_DET,TEAM_ABBREVIATION_a_GSW,TEAM_ABBREVIATION_a_HOU,TEAM_ABBREVIATION_a_IND,TEAM_ABBREVIATION_a_LAC,TEAM_ABBREVIATION_a_LAL,TEAM_ABBREVIATION_a_MEM,TEAM_ABBREVIATION_a_MIA,TEAM_ABBREVIATION_a_MIL,TEAM_ABBREVIATION_a_MIN,TEAM_ABBREVIATION_a_NJN,TEAM_ABBREVIATION_a_NOH,TEAM_ABBREVIATION_a_NOP,TEAM_ABBREVIATION_a_NYK,TEAM_ABBREVIATION_a_OKC,TEAM_ABBREVIATION_a_ORL,TEAM_ABBREVIATION_a_PHI,TEAM_ABBREVIATION_a_PHX,TEAM_ABBREVIATION_a_POR,TEAM_ABBREVIATION_a_SAC,TEAM_ABBREVIATION_a_SAS,TEAM_ABBREVIATION_a_TOR,TEAM_ABBREVIATION_a_UTA,TEAM_CITY_a_Atlanta,TEAM_CITY_a_Boston,TEAM_CITY_a_Brooklyn,TEAM_CITY_a_Charlotte,TEAM_CITY_a_Chicago,TEAM_CITY_a_Cleveland,TEAM_CITY_a_Dallas,TEAM_CITY_a_Denver,TEAM_CITY_a_Detroit,TEAM_CITY_a_Golden State,TEAM_CITY_a_Houston,TEAM_CITY_a_Indiana,TEAM_CITY_a_Los Angeles,TEAM_CITY_a_Memphis,TEAM_CITY_a_Miami,TEAM_CITY_a_Milwaukee,TEAM_CITY_a_Minnesota,TEAM_CITY_a_New Jersey,TEAM_CITY_a_New Orleans,TEAM_CITY_a_New York,TEAM_CITY_a_Oklahoma City,TEAM_CITY_a_Orlando,TEAM_CITY_a_Philadelphia,TEAM_CITY_a_Phoenix,TEAM_CITY_a_Portland,TEAM_CITY_a_Sacramento,TEAM_CITY_a_San Antonio,TEAM_CITY_a_Toronto,TEAM_CITY_a_Utah,matchup_ATL vs. BKN,matchup_ATL vs. BOS,matchup_ATL vs. CHA,matchup_ATL vs. CHI,matchup_ATL vs. CLE,matchup_ATL vs. DAL,matchup_ATL vs. DEN,matchup_ATL vs. DET,matchup_ATL vs. GSW,matchup_ATL vs. HOU,matchup_ATL vs. IND,matchup_ATL vs. LAC,matchup_ATL vs. LAL,matchup_ATL vs. MEM,matchup_ATL vs. MIA,matchup_ATL vs. MIL,matchup_ATL vs. MIN,matchup_ATL vs. NJN,matchup_ATL vs. NOH,matchup_ATL vs. NOP,matchup_ATL vs. NYK,matchup_ATL vs. OKC,matchup_ATL vs. ORL,matchup_ATL vs. PHI,matchup_ATL vs. PHX,matchup_ATL vs. POR,matchup_ATL vs. SAC,matchup_ATL vs. SAS,matchup_ATL vs. TOR,matchup_ATL vs. UTA,matchup_ATL vs. WAS,matchup_BKN vs. BOS,matchup_BKN vs. CHA,matchup_BKN vs. CHI,matchup_BKN vs. CLE,matchup_BKN vs. DAL,matchup_BKN vs. DEN,matchup_BKN vs. DET,matchup_BKN vs. GSW,matchup_BKN vs. HOU,matchup_BKN vs. IND,matchup_BKN vs. LAC,matchup_BKN vs. LAL,matchup_BKN vs. MEM,matchup_BKN vs. MIA,matchup_BKN vs. MIL,matchup_BKN vs. MIN,matchup_BKN vs. NOH,matchup_BKN vs. NOP,matchup_BKN vs. NYK,matchup_BKN vs. OKC,matchup_BKN vs. ORL,matchup_BKN vs. PHI,matchup_BKN vs. PHX,matchup_BKN vs. POR,matchup_BKN vs. SAC,matchup_BKN vs. SAS,matchup_BKN vs. TOR,matchup_BKN vs. UTA,matchup_BKN vs. WAS,matchup_BOS vs. CHA,matchup_BOS vs. CHI,matchup_BOS vs. CLE,matchup_BOS vs. DAL,matchup_BOS vs. DEN,matchup_BOS vs. DET,matchup_BOS vs. GSW,matchup_BOS vs. HOU,matchup_BOS vs. IND,matchup_BOS vs. LAC,matchup_BOS vs. LAL,matchup_BOS vs. MEM,matchup_BOS vs. MIA,matchup_BOS vs. MIL,matchup_BOS vs. MIN,matchup_BOS vs. NJN,matchup_BOS vs. NOH,matchup_BOS vs. NOP,matchup_BOS vs. NYK,matchup_BOS vs. OKC,matchup_BOS vs. ORL,matchup_BOS vs. PHI,matchup_BOS vs. PHX,matchup_BOS vs. POR,matchup_BOS vs. SAC,matchup_BOS vs. SAS,matchup_BOS vs. TOR,matchup_BOS vs. UTA,matchup_BOS vs. WAS,matchup_CHA vs. CHI,matchup_CHA vs. CLE,matchup_CHA vs. DAL,matchup_CHA vs. DEN,matchup_CHA vs. DET,matchup_CHA vs. GSW,matchup_CHA vs. HOU,matchup_CHA vs. IND,matchup_CHA vs. LAC,matchup_CHA vs. LAL,matchup_CHA vs. MEM,matchup_CHA vs. MIA,matchup_CHA vs. MIL,matchup_CHA vs. MIN,matchup_CHA vs. NJN,matchup_CHA vs. NOH,matchup_CHA vs. NOP,matchup_CHA vs. NYK,matchup_CHA vs. OKC,matchup_CHA vs. ORL,matchup_CHA vs. PHI,matchup_CHA vs. PHX,matchup_CHA vs. POR,matchup_CHA vs. SAC,matchup_CHA vs. SAS,matchup_CHA vs. TOR,matchup_CHA vs. UTA,matchup_CHA vs. WAS,matchup_CHI vs. CLE,matchup_CHI vs. DAL,matchup_CHI vs. DEN,matchup_CHI vs. DET,matchup_CHI vs. GSW,matchup_CHI vs. HOU,matchup_CHI vs. IND,matchup_CHI vs. LAC,matchup_CHI vs. LAL,matchup_CHI vs. MEM,matchup_CHI vs. MIA,matchup_CHI vs. MIL,matchup_CHI vs. MIN,matchup_CHI vs. NJN,matchup_CHI vs. NOH,matchup_CHI vs. NOP,matchup_CHI vs. NYK,matchup_CHI vs. OKC,matchup_CHI vs. ORL,matchup_CHI vs. PHI,matchup_CHI vs. PHX,matchup_CHI vs. POR,matchup_CHI vs. SAC,matchup_CHI vs. SAS,matchup_CHI vs. TOR,matchup_CHI vs. UTA,matchup_CHI vs. WAS,matchup_CLE vs. DAL,matchup_CLE vs. DEN,matchup_CLE vs. DET,matchup_CLE vs. GSW,matchup_CLE vs. HOU,matchup_CLE vs. IND,matchup_CLE vs. LAC,matchup_CLE vs. LAL,matchup_CLE vs. MEM,matchup_CLE vs. MIA,matchup_CLE vs. MIL,matchup_CLE vs. MIN,matchup_CLE vs. NJN,matchup_CLE vs. NOH,matchup_CLE vs. NOP,matchup_CLE vs. NYK,matchup_CLE vs. OKC,matchup_CLE vs. ORL,matchup_CLE vs. PHI,matchup_CLE vs. PHX,matchup_CLE vs. POR,matchup_CLE vs. SAC,matchup_CLE vs. SAS,matchup_CLE vs. TOR,matchup_CLE vs. UTA,matchup_CLE vs. WAS,matchup_DAL vs. DEN,matchup_DAL vs. DET,matchup_DAL vs. GSW,matchup_DAL vs. HOU,matchup_DAL vs. IND,matchup_DAL vs. LAC,matchup_DAL vs. LAL,matchup_DAL vs. MEM,matchup_DAL vs. MIA,matchup_DAL vs. MIL,matchup_DAL vs. MIN,matchup_DAL vs. NJN,matchup_DAL vs. NOH,matchup_DAL vs. NOP,matchup_DAL vs. NYK,matchup_DAL vs. OKC,matchup_DAL vs. ORL,matchup_DAL vs. PHI,matchup_DAL vs. PHX,matchup_DAL vs. POR,matchup_DAL vs. SAC,matchup_DAL vs. SAS,matchup_DAL vs. TOR,matchup_DAL vs. UTA,matchup_DAL vs. WAS,matchup_DEN vs. DET,matchup_DEN vs. GSW,matchup_DEN vs. HOU,matchup_DEN vs. IND,matchup_DEN vs. LAC,matchup_DEN vs. LAL,matchup_DEN vs. MEM,matchup_DEN vs. MIA,matchup_DEN vs. MIL,matchup_DEN vs. MIN,matchup_DEN vs. NJN,matchup_DEN vs. NOH,matchup_DEN vs. NOP,matchup_DEN vs. NYK,matchup_DEN vs. OKC,matchup_DEN vs. ORL,matchup_DEN vs. PHI,matchup_DEN vs. PHX,matchup_DEN vs. POR,matchup_DEN vs. SAC,matchup_DEN vs. SAS,matchup_DEN vs. TOR,matchup_DEN vs. UTA,matchup_DEN vs. WAS,matchup_DET vs. GSW,matchup_DET vs. HOU,matchup_DET vs. IND,matchup_DET vs. LAC,matchup_DET vs. LAL,matchup_DET vs. MEM,matchup_DET vs. MIA,matchup_DET vs. MIL,matchup_DET vs. MIN,matchup_DET vs. NJN,matchup_DET vs. NOH,matchup_DET vs. NOP,matchup_DET vs. NYK,matchup_DET vs. OKC,matchup_DET vs. ORL,matchup_DET vs. PHI,matchup_DET vs. PHX,matchup_DET vs. POR,matchup_DET vs. SAC,matchup_DET vs. SAS,matchup_DET vs. TOR,matchup_DET vs. UTA,matchup_DET vs. WAS,matchup_GSW vs. HOU,matchup_GSW vs. IND,matchup_GSW vs. LAC,matchup_GSW vs. LAL,matchup_GSW vs. MEM,matchup_GSW vs. MIA,matchup_GSW vs. MIL,matchup_GSW vs. MIN,matchup_GSW vs. NJN,matchup_GSW vs. NOH,matchup_GSW vs. NOP,matchup_GSW vs. NYK,matchup_GSW vs. OKC,matchup_GSW vs. ORL,matchup_GSW vs. PHI,matchup_GSW vs. PHX,matchup_GSW vs. POR,matchup_GSW vs. SAC,matchup_GSW vs. SAS,matchup_GSW vs. TOR,matchup_GSW vs. UTA,matchup_GSW vs. WAS,matchup_HOU vs. IND,matchup_HOU vs. LAC,matchup_HOU vs. LAL,matchup_HOU vs. MEM,matchup_HOU vs. MIA,matchup_HOU vs. MIL,matchup_HOU vs. MIN,matchup_HOU vs. NJN,matchup_HOU vs. NOH,matchup_HOU vs. NOP,matchup_HOU vs. NYK,matchup_HOU vs. OKC,matchup_HOU vs. ORL,matchup_HOU vs. PHI,matchup_HOU vs. PHX,matchup_HOU vs. POR,matchup_HOU vs. SAC,matchup_HOU vs. SAS,matchup_HOU vs. TOR,matchup_HOU vs. UTA,matchup_HOU vs. WAS,matchup_IND vs. LAC,matchup_IND vs. LAL,matchup_IND vs. MEM,matchup_IND vs. MIA,matchup_IND vs. MIL,matchup_IND vs. MIN,matchup_IND vs. NJN,matchup_IND vs. NOH,matchup_IND vs. NOP,matchup_IND vs. NYK,matchup_IND vs. OKC,matchup_IND vs. ORL,matchup_IND vs. PHI,matchup_IND vs. PHX,matchup_IND vs. POR,matchup_IND vs. SAC,matchup_IND vs. SAS,matchup_IND vs. TOR,matchup_IND vs. UTA,matchup_IND vs. WAS,matchup_LAC vs. LAL,matchup_LAC vs. MEM,matchup_LAC vs. MIA,matchup_LAC vs. MIL,matchup_LAC vs. MIN,matchup_LAC vs. NJN,matchup_LAC vs. NOH,matchup_LAC vs. NOP,matchup_LAC vs. NYK,matchup_LAC vs. OKC,matchup_LAC vs. ORL,matchup_LAC vs. PHI,matchup_LAC vs. PHX,matchup_LAC vs. POR,matchup_LAC vs. SAC,matchup_LAC vs. SAS,matchup_LAC vs. TOR,matchup_LAC vs. UTA,matchup_LAC vs. WAS,matchup_LAL vs. MEM,matchup_LAL vs. MIA,matchup_LAL vs. MIL,matchup_LAL vs. MIN,matchup_LAL vs. NJN,matchup_LAL vs. NOH,matchup_LAL vs. NOP,matchup_LAL vs. NYK,matchup_LAL vs. OKC,matchup_LAL vs. ORL,matchup_LAL vs. PHI,matchup_LAL vs. PHX,matchup_LAL vs. POR,matchup_LAL vs. SAC,matchup_LAL vs. SAS,matchup_LAL vs. TOR,matchup_LAL vs. UTA,matchup_LAL vs. WAS,matchup_MEM vs. MIA,matchup_MEM vs. MIL,matchup_MEM vs. MIN,matchup_MEM vs. NJN,matchup_MEM vs. NOH,matchup_MEM vs. NOP,matchup_MEM vs. NYK,matchup_MEM vs. OKC,matchup_MEM vs. ORL,matchup_MEM vs. PHI,matchup_MEM vs. PHX,matchup_MEM vs. POR,matchup_MEM vs. SAC,matchup_MEM vs. SAS,matchup_MEM vs. TOR,matchup_MEM vs. UTA,matchup_MEM vs. WAS,matchup_MIA vs. MIL,matchup_MIA vs. MIN,matchup_MIA vs. NJN,matchup_MIA vs. NOH,matchup_MIA vs. NOP,matchup_MIA vs. NYK,matchup_MIA vs. OKC,matchup_MIA vs. ORL,matchup_MIA vs. PHI,matchup_MIA vs. PHX,matchup_MIA vs. POR,matchup_MIA vs. SAC,matchup_MIA vs. SAS,matchup_MIA vs. TOR,matchup_MIA vs. UTA,matchup_MIA vs. WAS,matchup_MIL vs. MIN,matchup_MIL vs. NJN,matchup_MIL vs. NOH,matchup_MIL vs. NOP,matchup_MIL vs. NYK,matchup_MIL vs. OKC,matchup_MIL vs. ORL,matchup_MIL vs. PHI,matchup_MIL vs. PHX,matchup_MIL vs. POR,matchup_MIL vs. SAC,matchup_MIL vs. SAS,matchup_MIL vs. TOR,matchup_MIL vs. UTA,matchup_MIL vs. WAS,matchup_MIN vs. NJN,matchup_MIN vs. NOH,matchup_MIN vs. NOP,matchup_MIN vs. NYK,matchup_MIN vs. OKC,matchup_MIN vs. ORL,matchup_MIN vs. PHI,matchup_MIN vs. PHX,matchup_MIN vs. POR,matchup_MIN vs. SAC,matchup_MIN vs. SAS,matchup_MIN vs. TOR,matchup_MIN vs. UTA,matchup_MIN vs. WAS,matchup_NJN vs. NOH,matchup_NJN vs. NYK,matchup_NJN vs. OKC,matchup_NJN vs. ORL,matchup_NJN vs. PHI,matchup_NJN vs. PHX,matchup_NJN vs. POR,matchup_NJN vs. SAC,matchup_NJN vs. SAS,matchup_NJN vs. TOR,matchup_NJN vs. UTA,matchup_NJN vs. WAS,matchup_NOH vs. NYK,matchup_NOH vs. OKC,matchup_NOH vs. ORL,matchup_NOH vs. PHI,matchup_NOH vs. PHX,matchup_NOH vs. POR,matchup_NOH vs. SAC,matchup_NOH vs. SAS,matchup_NOH vs. TOR,matchup_NOH vs. UTA,matchup_NOH vs. WAS,matchup_NOP vs. NYK,matchup_NOP vs. OKC,matchup_NOP vs. ORL,matchup_NOP vs. PHI,matchup_NOP vs. PHX,matchup_NOP vs. POR,matchup_NOP vs. SAC,matchup_NOP vs. SAS,matchup_NOP vs. TOR,matchup_NOP vs. UTA,matchup_NOP vs. WAS,matchup_NYK vs. OKC,matchup_NYK vs. ORL,matchup_NYK vs. PHI,matchup_NYK vs. PHX,matchup_NYK vs. POR,matchup_NYK vs. SAC,matchup_NYK vs. SAS,matchup_NYK vs. TOR,matchup_NYK vs. UTA,matchup_NYK vs. WAS,matchup_OKC vs. ORL,matchup_OKC vs. PHI,matchup_OKC vs. PHX,matchup_OKC vs. POR,matchup_OKC vs. SAC,matchup_OKC vs. SAS,matchup_OKC vs. TOR,matchup_OKC vs. UTA,matchup_OKC vs. WAS,matchup_ORL vs. PHI,matchup_ORL vs. PHX,matchup_ORL vs. POR,matchup_ORL vs. SAC,matchup_ORL vs. SAS,matchup_ORL vs. TOR,matchup_ORL vs. UTA,matchup_ORL vs. WAS,matchup_PHI vs. PHX,matchup_PHI vs. POR,matchup_PHI vs. SAC,matchup_PHI vs. SAS,matchup_PHI vs. TOR,matchup_PHI vs. UTA,matchup_PHI vs. WAS,matchup_PHX vs. POR,matchup_PHX vs. SAC,matchup_PHX vs. SAS,matchup_PHX vs. TOR,matchup_PHX vs. UTA,matchup_PHX vs. WAS,matchup_POR vs. SAC,matchup_POR vs. SAS,matchup_POR vs. TOR,matchup_POR vs. UTA,matchup_POR vs. WAS,matchup_SAC vs. SAS,matchup_SAC vs. TOR,matchup_SAC vs. UTA,matchup_SAC vs. WAS,matchup_SAS vs. TOR,matchup_SAS vs. UTA,matchup_SAS vs. WAS,matchup_TOR vs. UTA,matchup_TOR vs. WAS,matchup_UTA vs. WAS,season_type_Playoffs,season_type_Regular Season,season_2010-11,season_2011-12,season_2012-13,season_2013-14,season_2014-15,season_2015-16,season_2016-17,season_2017-18,TEAM_NAME_b_76ers,TEAM_NAME_b_Bobcats,TEAM_NAME_b_Bucks,TEAM_NAME_b_Bulls,TEAM_NAME_b_Cavaliers,TEAM_NAME_b_Celtics,TEAM_NAME_b_Clippers,TEAM_NAME_b_Grizzlies,TEAM_NAME_b_Heat,TEAM_NAME_b_Hornets,TEAM_NAME_b_Jazz,TEAM_NAME_b_Kings,TEAM_NAME_b_Knicks,TEAM_NAME_b_Lakers,TEAM_NAME_b_Magic,TEAM_NAME_b_Mavericks,TEAM_NAME_b_Nets,TEAM_NAME_b_Nuggets,TEAM_NAME_b_Pacers,TEAM_NAME_b_Pelicans,TEAM_NAME_b_Pistons,TEAM_NAME_b_Raptors,TEAM_NAME_b_Rockets,TEAM_NAME_b_Spurs,TEAM_NAME_b_Suns,TEAM_NAME_b_Thunder,TEAM_NAME_b_Timberwolves,TEAM_NAME_b_Trail Blazers,TEAM_NAME_b_Warriors,TEAM_NAME_b_Wizards,TEAM_ABBREVIATION_b_BKN,TEAM_ABBREVIATION_b_BOS,TEAM_ABBREVIATION_b_CHA,TEAM_ABBREVIATION_b_CHI,TEAM_ABBREVIATION_b_CLE,TEAM_ABBREVIATION_b_DAL,TEAM_ABBREVIATION_b_DEN,TEAM_ABBREVIATION_b_DET,TEAM_ABBREVIATION_b_GSW,TEAM_ABBREVIATION_b_HOU,TEAM_ABBREVIATION_b_IND,TEAM_ABBREVIATION_b_LAC,TEAM_ABBREVIATION_b_LAL,TEAM_ABBREVIATION_b_MEM,TEAM_ABBREVIATION_b_MIA,TEAM_ABBREVIATION_b_MIL,TEAM_ABBREVIATION_b_MIN,TEAM_ABBREVIATION_b_NJN,TEAM_ABBREVIATION_b_NOH,TEAM_ABBREVIATION_b_NOP,TEAM_ABBREVIATION_b_NYK,TEAM_ABBREVIATION_b_OKC,TEAM_ABBREVIATION_b_ORL,TEAM_ABBREVIATION_b_PHI,TEAM_ABBREVIATION_b_PHX,TEAM_ABBREVIATION_b_POR,TEAM_ABBREVIATION_b_SAC,TEAM_ABBREVIATION_b_SAS,TEAM_ABBREVIATION_b_TOR,TEAM_ABBREVIATION_b_UTA,TEAM_ABBREVIATION_b_WAS,TEAM_CITY_b_Boston,TEAM_CITY_b_Brooklyn,TEAM_CITY_b_Charlotte,TEAM_CITY_b_Chicago,TEAM_CITY_b_Cleveland,TEAM_CITY_b_Dallas,TEAM_CITY_b_Denver,TEAM_CITY_b_Detroit,TEAM_CITY_b_Golden State,TEAM_CITY_b_Houston,TEAM_CITY_b_Indiana,TEAM_CITY_b_Los Angeles,TEAM_CITY_b_Memphis,TEAM_CITY_b_Miami,TEAM_CITY_b_Milwaukee,TEAM_CITY_b_Minnesota,TEAM_CITY_b_New Jersey,TEAM_CITY_b_New Orleans,TEAM_CITY_b_New York,TEAM_CITY_b_Oklahoma City,TEAM_CITY_b_Orlando,TEAM_CITY_b_Philadelphia,TEAM_CITY_b_Phoenix,TEAM_CITY_b_Portland,TEAM_CITY_b_Sacramento,TEAM_CITY_b_San Antonio,TEAM_CITY_b_Toronto,TEAM_CITY_b_Utah,TEAM_CITY_b_Washington
0,1610612738,1610612748,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,1610612756,1610612757,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
2,1610612745,1610612747,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,1610612750,1610612758,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0

In [9]:
df = df.drop(columns=column_names_categorical_list_rgi)
p(df)

(10266, 95)

,game_id,spread_a,game_date,E_OFF_RATING_cma_diff,OFF_RATING_cma_diff,E_DEF_RATING_cma_diff,DEF_RATING_cma_diff,E_NET_RATING_cma_diff,NET_RATING_cma_diff,AST_PCT_cma_diff,AST_TOV_cma_diff,AST_RATIO_cma_diff,OREB_PCT_cma_diff,DREB_PCT_cma_diff,REB_PCT_cma_diff,E_TM_TOV_PCT_cma_diff,TM_TOV_PCT_cma_diff,EFG_PCT_cma_diff,TS_PCT_cma_diff,USG_PCT_cma_diff,E_USG_PCT_cma_diff,E_PACE_cma_diff,PACE_cma_diff,PACE_PER40_cma_diff,POSS_cma_diff,PIE_cma_diff,duration_minutes_cma_diff,w_pct_cma_diff,min_cma_diff,fgm_cma_diff,fga_cma_diff,fg_pct_cma_diff,fg3m_cma_diff,fg3a_cma_diff,fg3_pct_cma_diff,ftm_cma_diff,fta_cma_diff,ft_pct_cma_diff,oreb_cma_diff,dreb_cma_diff,reb_cma_diff,ast_cma_diff,stl_cma_diff,blk_cma_diff,tov_cma_diff,pf_cma_diff,pts_cma_diff,spread_cma_diff,away_home_cma_diff,E_OFF_RATING_sm_cma_diff,OFF_RATING_sm_cma_diff,E_DEF_RATING_sm_cma_diff,DEF_RATING_sm_cma_diff,E_NET_RATING_sm_cma_diff,NET_RATING_sm_cma_diff,AST_PCT_sm_cma_diff,AST_TOV_sm_cma_diff,AST_RATIO_sm_cma_diff,OREB_PCT_sm_cma_diff,DREB_PCT_sm_cma_diff,REB_PCT_sm_cma_diff,E_TM_TOV_PCT_sm_cma_diff,TM_TOV_PCT_sm_cma_diff,EFG_PCT_sm_cma_diff,TS_PCT_sm_cma_diff,USG_PCT_sm_cma_diff,E_USG_PCT_sm_cma_diff,E_PACE_sm_cma_diff,PACE_sm_cma_diff,PACE_PER40_sm_cma_diff,POSS_sm_cma_diff,PIE_sm_cma_diff,duration_minutes_sm_cma_diff,w_pct_sm_cma_diff,min_sm_cma_diff,fgm_sm_cma_diff,fga_sm_cma_diff,fg_pct_sm_cma_diff,fg3m_sm_cma_diff,fg3a_sm_cma_diff,fg3_pct_sm_cma_diff,ftm_sm_cma_diff,fta_sm_cma_diff,ft_pct_sm_cma_diff,oreb_sm_cma_diff,dreb_sm_cma_diff,reb_sm_cma_diff,ast_sm_cma_diff,stl_sm_cma_diff,blk_sm_cma_diff,tov_sm_cma_diff,pf_sm_cma_diff,pts_sm_cma_diff,spread_sm_cma_diff,away_home_sm_cma_diff
0,21000001,-8,2010-10-26,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,21000002,14,2010-10-26,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,21000003,2,2010-10-26,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,21000009,1,2010-10-27,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,21000006,-10,2010-10-27,87.900000,87.900000,95.700000,95.700000,-7.700000,-7.700000,0.556000,0.880000,12.800000,0.250000,0.732000,0.472000,18.681000,18.700000,0.419000,0.471000,1.0,0.200000,91.500000,91.500000,76.250000,91.000000,0.401000,240.000000,0.000000,240.000000,27.000000,74.000000,0.365000,8.000000,20.000000,0.400000,18.000000,25.000000,0.720000,11.000000,28.000000,39.000000,15.000000,10.000000,6.000000,17.000000,21.000000,80.000000,8.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10261,41700317,-9,2018-05-28,2.533333,1.141667,-7.666667,-6.816667,10.183333,7.950000,0.105500,0.220833,3.358333,-0.006750,-0.002750,0.011500,-0.475083,-0.625000,0.003750,0.005083,0.0,0.002083,3.746667,3.958333,3.297500,3.666667,0.062833,0.000000,0.136167,0.000000,3.916667,4.000000,0.025583,-3.166667,-7.333333,-0.021833,0.583333,0.000000,0.039151,1.250000,2.250000,3.500000,6.166667,0.916667,-0.083333,0.750000,-1.000000,5.250000,-7.583333,0.000000,8.900,6.222222,-8.900,-6.222222,17.800000,12.422222,0.117111,0.593333,4.611111,-0.035333,-0.035333,-0.002444,-0.648444,-0.966667,0.04500,0.047778,0.0,0.002111,0.0,0.0,0.0,0.111111,0.106000,0.0,0.028778,0.0,3.777778,-0.555556,0.050778,-1.111111,-8.777778,0.059333,-0.333333,-3.333333,0.117998,-0.666667,0.888889,0.222222,6.555556,-0.222222,2.222222,0.111111,1.444444,6.111111,-12.222222,-0.111111
10262,41700401,10,2018-05-31,0.641667,2.991667,5.983333,6.825000,-5.341667,-3.841667,-0.090333,0.285000,-2.408333,0.027583,-0.009833,0.009750,-0.940417,-0.766667,0.001250,0.002500,0.0,-0.001333,-7.474167,-8.649167,-7.207500,-7.416667,-0.027083,2.083333,-0.123333,2.083333,-2.833333,-6.666667,0.003750,-1.250000,-3.000000,-0.002917,1.500000,3.416667,-0.055855,-1.166667,-3.083333,-4.250000,-5.416667,-3.583333,-0.416667,-2.000000,0.666667,-5.416667,3.333333,0.000000,-10.600,-9.100000,10.600,9.100000,-21.100000,-18.200000,-0.254000,-0.610000,-7.900000,0.035500,0.035500,-0.001000,-1.777500,-1.600000,-0.08950,-0.084000,0.0,0.000000,0.0,0.0,0.0,0.500000,-0.205000,0.0,-0.141500,0.0,-4.000000,7.500000,-0.085000,0.000000,-2.500000,0.011000,-0.500000,0.000000,-0.021444,4.000000,-5.000000,-1.000000,-11.500000,1.000000,-4.000000,-1.000000,0.000000,-8.500000,17.000000,0.000000
10263,41700402,19,2018-06-03,-0.275000,1.616667,5.450000,6.266667,-5.733333,-4.658333,-0.096833,0.158333,-2.625000,0.040083,0.023250,0.028917,-0.634250,-0.491667,-0.002417,-0.005167,0.0,-0.001417,-6.150833,-7.107500,-5.923333,-5.666667,-0.037083,2.083333,-0.170917,2.083333,-2.000000,-4.500000,0.002500,-1.416667,-3.083333,-0.005333,0.666667,2.916667,-0.076499,-0.083333,-1.833333,-1.916667,-5.250000,-3.833333,-0.166667,-1.583333,0.250000,-4.750000,3.500000,-0.083333,-9.900,-10.200000,9.900,10.200000,-19.733333,-20.400000,-0.257667,-1.200000,-8.433333,0.099000,0.099000,0.058000,0.155000,0.200000,-0.08900,-0.090667,0.0,0.000667,0.0,0.0,0.0,1.000000,-0.199333,0.0,-0.427667,0.0,-3.333333,8.000000,-0.079000,-1.000000,-1.333333,-0.023000,-1.333333,0.666667,-0.088538,7.666667,-3.333333,4.333333,-12.000000,-1.000000,-3.666667,0.666667,0.000000,-9.000000,18.000000,-0.333333
10264,41700403,8,2018-06-06,-1.958333,-0.608333,6.666667,7.500000,-8.633333,-8.116667,-0.070000,-0.006667,-2.416667,0.037417,0.040667,0.034000,-0.010750,0.100000,-0.014083,-0.011917,0.0,-0.001583,-4.626667,-5.416667,-4.514167,-4.583333,-0.044417,0.000000,-0.254250,0.000000,-2.750000,-4.750000,-0.005917,-2.000000,-3.416667,-0.018583,1.833333,3.833333,-0.055607,0.166667,-1.666667,-1.500000,-4.583333,-2.916667,-0.250000,-0.833333,-1.000000,-5.666667,6.333333,-0.083333,-12.425,-13.550000,12.425,13.550000,-24.800000,-27.100000,-0.173250,-0.915000,-7.100000,0.097500,0.097500,0.051500,-0.149500,-0.225000,-0.11775,-0.108250,0.0,-0.000250,0.0,0.0,0.0,1.500000,-0.182000,0.0,-0.570750,0.0,-5.000000,8.000000,-0.099750,-2.250000,-3.250000,-0.038250,0.750000,1.750000,-0.028858,8.000000,-4.500000,3.500000,-9.750000,0.750000,-3.750000,0.000000,-2.500000,-11.500000,23.000000,-0.500000
10265,41700404,23,2018-06-08,-6.716667,-4.966667,7.100000,7.758333,-13.825000,-12.750000,-0.071167,-0.633333,-3.308333,0.055417,0.045000,0.038583,0.879500,1.058333,-0.040917,-0.036833,0.0,-0.001750,-3.470000,-4.416667,-3.680833,-3.583333,-0.070917,0.000000,-0.365333,0.000000,-4.166667,-3.166667,-0.030833,-2.166667,-2.583333,-0.034333,1.833333,3.916667,-0.060729,1.333333,-1.166667,0.166667,-5.416667,-2.416667,-0.250000,0.166667,-0.916667,-8.666667,10.750000,0.000000,-12.540,-12.760000,12.540,12.760000,-25.040000,-25.560000,-0.167200,-0.936000,-6.920000,0.116800,0.116800,0.068400,0.392200,0.420000,-0.11220,-0.107000,0.0,-0.000600,0.0,0.0,0.0,1.400000,-0.173200,0.0,-0.656600,0.0,-4.400000,8.600000,-0.096600,-1.800000,-1.600000,-0.041800,-0.200000,1.000000,-0.049093,8.200000,-3.400000,4.800000,-9.200000,0.600000,-3.200000,0.600000,-2.400000,-10.800000,21.600000,-0.200000

In [10]:
column_names_not_scaled_list = ['game_id', 'game_date', 'spread_a']
pl(column_names_not_scaled_list)

3

['game_id', 'game_date', 'spread_a']

In [11]:
#column check
df.drop(columns=column_names_not_scaled_list)

,E_OFF_RATING_cma_diff,OFF_RATING_cma_diff,E_DEF_RATING_cma_diff,DEF_RATING_cma_diff,E_NET_RATING_cma_diff,NET_RATING_cma_diff,AST_PCT_cma_diff,AST_TOV_cma_diff,AST_RATIO_cma_diff,OREB_PCT_cma_diff,DREB_PCT_cma_diff,REB_PCT_cma_diff,E_TM_TOV_PCT_cma_diff,TM_TOV_PCT_cma_diff,EFG_PCT_cma_diff,TS_PCT_cma_diff,USG_PCT_cma_diff,E_USG_PCT_cma_diff,E_PACE_cma_diff,PACE_cma_diff,PACE_PER40_cma_diff,POSS_cma_diff,PIE_cma_diff,duration_minutes_cma_diff,w_pct_cma_diff,min_cma_diff,fgm_cma_diff,fga_cma_diff,fg_pct_cma_diff,fg3m_cma_diff,fg3a_cma_diff,fg3_pct_cma_diff,ftm_cma_diff,fta_cma_diff,ft_pct_cma_diff,oreb_cma_diff,dreb_cma_diff,reb_cma_diff,ast_cma_diff,stl_cma_diff,blk_cma_diff,tov_cma_diff,pf_cma_diff,pts_cma_diff,spread_cma_diff,away_home_cma_diff,E_OFF_RATING_sm_cma_diff,OFF_RATING_sm_cma_diff,E_DEF_RATING_sm_cma_diff,DEF_RATING_sm_cma_diff,E_NET_RATING_sm_cma_diff,NET_RATING_sm_cma_diff,AST_PCT_sm_cma_diff,AST_TOV_sm_cma_diff,AST_RATIO_sm_cma_diff,OREB_PCT_sm_cma_diff,DREB_PCT_sm_cma_diff,REB_PCT_sm_cma_diff,E_TM_TOV_PCT_sm_cma_diff,TM_TOV_PCT_sm_cma_diff,EFG_PCT_sm_cma_diff,TS_PCT_sm_cma_diff,USG_PCT_sm_cma_diff,E_USG_PCT_sm_cma_diff,E_PACE_sm_cma_diff,PACE_sm_cma_diff,PACE_PER40_sm_cma_diff,POSS_sm_cma_diff,PIE_sm_cma_diff,duration_minutes_sm_cma_diff,w_pct_sm_cma_diff,min_sm_cma_diff,fgm_sm_cma_diff,fga_sm_cma_diff,fg_pct_sm_cma_diff,fg3m_sm_cma_diff,fg3a_sm_cma_diff,fg3_pct_sm_cma_diff,ftm_sm_cma_diff,fta_sm_cma_diff,ft_pct_sm_cma_diff,oreb_sm_cma_diff,dreb_sm_cma_diff,reb_sm_cma_diff,ast_sm_cma_diff,stl_sm_cma_diff,blk_sm_cma_diff,tov_sm_cma_diff,pf_sm_cma_diff,pts_sm_cma_diff,spread_sm_cma_diff,away_home_sm_cma_diff
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,87.900000,87.900000,95.700000,95.700000,-7.700000,-7.700000,0.556000,0.880000,12.800000,0.250000,0.732000,0.472000,18.681000,18.700000,0.419000,0.471000,1.0,0.200000,91.500000,91.500000,76.250000,91.000000,0.401000,240.000000,0.000000,240.000000,27.000000,74.000000,0.365000,8.000000,20.000000,0.400000,18.000000,25.000000,0.720000,11.000000,28.000000,39.000000,15.000000,10.000000,6.000000,17.000000,21.000000,80.000000,8.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10261,2.533333,1.141667,-7.666667,-6.816667,10.183333,7.950000,0.105500,0.220833,3.358333,-0.006750,-0.002750,0.011500,-0.475083,-0.625000,0.003750,0.005083,0.0,0.002083,3.746667,3.958333,3.297500,3.666667,0.062833,0.000000,0.136167,0.000000,3.916667,4.000000,0.025583,-3.166667,-7.333333,-0.021833,0.583333,0.000000,0.039151,1.250000,2.250000,3.500000,6.166667,0.916667,-0.083333,0.750000,-1.000000,5.250000,-7.583333,0.000000,8.900,6.222222,-8.900,-6.222222,17.800000,12.422222,0.117111,0.593333,4.611111,-0.035333,-0.035333,-0.002444,-0.648444,-0.966667,0.04500,0.047778,0.0,0.002111,0.0,0.0,0.0,0.111111,0.106000,0.0,0.028778,0.0,3.777778,-0.555556,0.050778,-1.111111,-8.777778,0.059333,-0.333333,-3.333333,0.117998,-0.666667,0.888889,0.222222,6.555556,-0.222222,2.222222,0.111111,1.444444,6.111111,-12.222222,-0.111111
10262,0.641667,2.991667,5.983333,6.825000,-5.341667,-3.841667,-0.090333,0.285000,-2.408333,0.027583,-0.009833,0.009750,-0.940417,-0.766667,0.001250,0.002500,0.0,-0.001333,-7.474167,-8.649167,-7.207500,-7.416667,-0.027083,2.083333,-0.123333,2.083333,-2.833333,-6.666667,0.003750,-1.250000,-3.000000,-0.002917,1.500000,3.416667,-0.055855,-1.166667,-3.083333,-4.250000,-5.416667,-3.583333,-0.416667,-2.000000,0.666667,-5.416667,3.333333,0.000000,-10.600,-9.100000,10.600,9.100000,-21.100000,-18.200000,-0.254000,-0.610000,-7.900000,0.035500,0.035500,-0.001000,-1.777500,-1.600000,-0.08950,-0.084000,0.0,0.000000,0.0,0.0,0.0,0.500000,-0.205000,0.0,-0.141500,0.0,-4.000000,7.500000,-0.085000,0.000000,-2.500000,0.011000,-0.500000,0.000000,-0.021444,4.000000,-5.000000,-1.000000,-11.500000,1.000000,-4.000000,-1.000000,0.000000,-8.500000,17.000000,0.000000
10263,-0.275000,1.616667,5.450000,6.266667,-5.733333,-4.658333,-0.096833,0.158333,-2.625000,0.040083,0.023250,0.028917,-0.634250,-0.491667,-0.002417,-0.005167,0.0,-0.001417,-6.150833,-7.107500,-5.923333,-5.666667,-0.037083,2.083333,-0.170917,2.083333,-2.000000,-4.500000,0.002500,-1.416667,-3.083333,-0.005333,0.666667,2.916667,-0.076499,-0.083333,-1.833333,-1.916667,-5.250000,-3.833333,-0.166667,-1.583333,0.250000,-4.750000,3.500000,-0.083333,-9.900,-10.200000,9.900,10.200000,-19.733333,-20.400000,-0.257667,-1.200000,-8.433333,0.099000,0.099000,0.058000,0.155000,0.200000,-0.08900,-0.090667,0.0,0.000667,0.0,0.0,0.0,1.000000,-0.199333,0.0,-0.427667,0.0,-3.333333,8.000000,-0.079000,-1.000000,-1.333333,-0.023000,-1.333333,0.666667,-0.088538,7.666667,-3.333333,4.333333,-12.000000,-1.000000,-3.666667,0.666667,0.000000,-9.000000,18.000000,-0.333333
10264,-1.958333,-0.608333,6.666667,7.500000,-8.633333,-8.116667,-0.070000,-0.006667,-2.416667,0.037417,0.040667,0.034000,-0.010750,0.100000,-0.014083,-0.011917,0.0,-0.001583,-4.626667,-5.416667,-4.514167,-4.583333,-0.044417,0.000000,-0.254250,0.000000,-2.750000,-4.750000,-0.005917,-2.000000,-3.416667,-0.018583,1.833333,3.833333,-0.055607,0.166667,-1.666667,-1.500000,-4.583333,-2.916667,-0.250000,-0.833333,-1.000000,-5.666667,6.333333,-0.083333,-12.425,-13.550000,12.425,13.550000,-24.800000,-27.100000,-0.173250,-0.915000,-7.100000,0.097500,0.097500,0.051500,-0.149500,-0.225000,-0.11775,-0.108250,0.0,-0.000250,0.0,0.0,0.0,1.500000,-0.182000,0.0,-0.570750,0.0,-5.000000,8.000000,-0.099750,-2.250000,-3.250000,-0.038250,0.750000,1.750000,-0.028858,8.000000,-4.500000,3.500000,-9.750000,0.750000,-3.750000,0.000000,-2.500000,-11.500000,23.000000,-0.500000
10265,-6.716667,-4.966667,7.100000,7.758333,-13.825000,-12.750000,-0.071167,-0.633333,-3.308333,0.055417,0.045000,0.038583,0.879500,1.058333,-0.040917,-0.036833,0.0,-0.001750,-3.470000,-4.416667,-3.680833,-3.583333,-0.070917,0.000000,-0.365333,0.000000,-4.166667,-3.166667,-0.030833,-2.166667,-2.583333,-0.034333,1.833333,3.916667,-0.060729,1.333333,-1.166667,0.166667,-5.416667,-2.416667,-0.250000,0.166667,-0.916667,-8.666667,10.750000,0.000000,-12.540,-12.760000,12.540,12.760000,-25.040000,-25.560000,-0.167200,-0.936000,-6.920000,0.116800,0.116800,0.068400,0.392200,0.420000,-0.11220,-0.107000,0.0,-0.000600,0.0,0.0,0.0,1.400000,-0.173200,0.0,-0.656600,0.0,-4.400000,8.600000,-0.096600,-1.800000,-1.600000,-0.041800,-0.200000,1.000000,-0.049093,8.200000,-3.400000,4.800000,-9.200000,0.600000,-3.200000,0.600000,-2.400000,-10.800000,21.600000,-0.200000

In [12]:
df = pd.concat([df, df_indicator_variables], axis=1)
p(df)

(10266, 781)

,game_id,spread_a,game_date,E_OFF_RATING_cma_diff,OFF_RATING_cma_diff,E_DEF_RATING_cma_diff,DEF_RATING_cma_diff,E_NET_RATING_cma_diff,NET_RATING_cma_diff,AST_PCT_cma_diff,AST_TOV_cma_diff,AST_RATIO_cma_diff,OREB_PCT_cma_diff,DREB_PCT_cma_diff,REB_PCT_cma_diff,E_TM_TOV_PCT_cma_diff,TM_TOV_PCT_cma_diff,EFG_PCT_cma_diff,TS_PCT_cma_diff,USG_PCT_cma_diff,E_USG_PCT_cma_diff,E_PACE_cma_diff,PACE_cma_diff,PACE_PER40_cma_diff,POSS_cma_diff,PIE_cma_diff,duration_minutes_cma_diff,w_pct_cma_diff,min_cma_diff,fgm_cma_diff,fga_cma_diff,fg_pct_cma_diff,fg3m_cma_diff,fg3a_cma_diff,fg3_pct_cma_diff,ftm_cma_diff,fta_cma_diff,ft_pct_cma_diff,oreb_cma_diff,dreb_cma_diff,reb_cma_diff,ast_cma_diff,stl_cma_diff,blk_cma_diff,tov_cma_diff,pf_cma_diff,pts_cma_diff,spread_cma_diff,away_home_cma_diff,E_OFF_RATING_sm_cma_diff,OFF_RATING_sm_cma_diff,E_DEF_RATING_sm_cma_diff,DEF_RATING_sm_cma_diff,E_NET_RATING_sm_cma_diff,NET_RATING_sm_cma_diff,AST_PCT_sm_cma_diff,AST_TOV_sm_cma_diff,AST_RATIO_sm_cma_diff,OREB_PCT_sm_cma_diff,DREB_PCT_sm_cma_diff,REB_PCT_sm_cma_diff,E_TM_TOV_PCT_sm_cma_diff,TM_TOV_PCT_sm_cma_diff,EFG_PCT_sm_cma_diff,TS_PCT_sm_cma_diff,USG_PCT_sm_cma_diff,E_USG_PCT_sm_cma_diff,E_PACE_sm_cma_diff,PACE_sm_cma_diff,PACE_PER40_sm_cma_diff,POSS_sm_cma_diff,PIE_sm_cma_diff,duration_minutes_sm_cma_diff,w_pct_sm_cma_diff,min_sm_cma_diff,fgm_sm_cma_diff,fga_sm_cma_diff,fg_pct_sm_cma_diff,fg3m_sm_cma_diff,fg3a_sm_cma_diff,fg3_pct_sm_cma_diff,ftm_sm_cma_diff,fta_sm_cma_diff,ft_pct_sm_cma_diff,oreb_sm_cma_diff,dreb_sm_cma_diff,reb_sm_cma_diff,ast_sm_cma_diff,stl_sm_cma_diff,blk_sm_cma_diff,tov_sm_cma_diff,pf_sm_cma_diff,pts_sm_cma_diff,spread_sm_cma_diff,away_home_sm_cma_diff,team_id_a,team_id_b,away_home_a,TEAM_NAME_a_76ers,TEAM_NAME_a_Bobcats,TEAM_NAME_a_Bucks,TEAM_NAME_a_Bulls,TEAM_NAME_a_Cavaliers,TEAM_NAME_a_Celtics,TEAM_NAME_a_Clippers,TEAM_NAME_a_Grizzlies,TEAM_NAME_a_Hawks,TEAM_NAME_a_Heat,TEAM_NAME_a_Hornets,TEAM_NAME_a_Jazz,TEAM_NAME_a_Kings,TEAM_NAME_a_Knicks,TEAM_NAME_a_Lakers,TEAM_NAME_a_Magic,TEAM_NAME_a_Mavericks,TEAM_NAME_a_Nets,TEAM_NAME_a_Nuggets,TEAM_NAME_a_Pacers,TEAM_NAME_a_Pelicans,TEAM_NAME_a_Pistons,TEAM_NAME_a_Raptors,TEAM_NAME_a_Rockets,TEAM_NAME_a_Spurs,TEAM_NAME_a_Suns,TEAM_NAME_a_Thunder,TEAM_NAME_a_Timberwolves,TEAM_NAME_a_Trail Blazers,TEAM_NAME_a_Warriors,TEAM_ABBREVIATION_a_ATL,TEAM_ABBREVIATION_a_BKN,TEAM_ABBREVIATION_a_BOS,TEAM_ABBREVIATION_a_CHA,TEAM_ABBREVIATION_a_CHI,TEAM_ABBREVIATION_a_CLE,TEAM_ABBREVIATION_a_DAL,TEAM_ABBREVIATION_a_DEN,TEAM_ABBREVIATION_a_DET,TEAM_ABBREVIATION_a_GSW,TEAM_ABBREVIATION_a_HOU,TEAM_ABBREVIATION_a_IND,TEAM_ABBREVIATION_a_LAC,TEAM_ABBREVIATION_a_LAL,TEAM_ABBREVIATION_a_MEM,TEAM_ABBREVIATION_a_MIA,TEAM_ABBREVIATION_a_MIL,TEAM_ABBREVIATION_a_MIN,TEAM_ABBREVIATION_a_NJN,TEAM_ABBREVIATION_a_NOH,TEAM_ABBREVIATION_a_NOP,TEAM_ABBREVIATION_a_NYK,TEAM_ABBREVIATION_a_OKC,TEAM_ABBREVIATION_a_ORL,TEAM_ABBREVIATION_a_PHI,TEAM_ABBREVIATION_a_PHX,TEAM_ABBREVIATION_a_POR,TEAM_ABBREVIATION_a_SAC,TEAM_ABBREVIATION_a_SAS,TEAM_ABBREVIATION_a_TOR,TEAM_ABBREVIATION_a_UTA,TEAM_CITY_a_Atlanta,TEAM_CITY_a_Boston,TEAM_CITY_a_Brooklyn,TEAM_CITY_a_Charlotte,TEAM_CITY_a_Chicago,TEAM_CITY_a_Cleveland,TEAM_CITY_a_Dallas,TEAM_CITY_a_Denver,TEAM_CITY_a_Detroit,TEAM_CITY_a_Golden State,TEAM_CITY_a_Houston,TEAM_CITY_a_Indiana,TEAM_CITY_a_Los Angeles,TEAM_CITY_a_Memphis,TEAM_CITY_a_Miami,TEAM_CITY_a_Milwaukee,TEAM_CITY_a_Minnesota,TEAM_CITY_a_New Jersey,TEAM_CITY_a_New Orleans,TEAM_CITY_a_New York,TEAM_CITY_a_Oklahoma City,TEAM_CITY_a_Orlando,TEAM_CITY_a_Philadelphia,TEAM_CITY_a_Phoenix,TEAM_CITY_a_Portland,TEAM_CITY_a_Sacramento,TEAM_CITY_a_San Antonio,TEAM_CITY_a_Toronto,TEAM_CITY_a_Utah,matchup_ATL vs. BKN,matchup_ATL vs. BOS,matchup_ATL vs. CHA,matchup_ATL vs. CHI,matchup_ATL vs. CLE,matchup_ATL vs. DAL,matchup_ATL vs. DEN,matchup_ATL vs. DET,matchup_ATL vs. GSW,matchup_ATL vs. HOU,matchup_ATL vs. IND,matchup_ATL vs. LAC,matchup_ATL vs. LAL,matchup_ATL vs. MEM,matchup_ATL vs. MIA,matchup_ATL vs. MIL,matchup_ATL vs. MIN,matchup_ATL vs. NJN,matchup_ATL vs. NOH,matchup_ATL vs. NOP,matchup_ATL vs. NYK,matchup_ATL vs. OKC,matchup_ATL vs. ORL,matchup_ATL vs. PHI,matchup_ATL vs. PHX,matchup_ATL vs. POR,matchup_ATL vs. SAC,matchup_ATL vs. SAS,matchup_ATL vs. TOR,matchup_ATL vs. UTA,matchup_ATL vs. WAS,matchup_BKN vs. BOS,matchup_BKN vs. CHA,matchup_BKN vs. CHI,matchup_BKN vs. CLE,matchup_BKN vs. DAL,matchup_BKN vs. DEN,matchup_BKN vs. DET,matchup_BKN vs. GSW,matchup_BKN vs. HOU,matchup_BKN vs. IND,matchup_BKN vs. LAC,matchup_BKN vs. LAL,matchup_BKN vs. MEM,matchup_BKN vs. MIA,matchup_BKN vs. MIL,matchup_BKN vs. MIN,matchup_BKN vs. NOH,matchup_BKN vs. NOP,matchup_BKN vs. NYK,matchup_BKN vs. OKC,matchup_BKN vs. ORL,matchup_BKN vs. PHI,matchup_BKN vs. PHX,matchup_BKN vs. POR,matchup_BKN vs. SAC,matchup_BKN vs. SAS,matchup_BKN vs. TOR,matchup_BKN vs. UTA,matchup_BKN vs. WAS,matchup_BOS vs. CHA,matchup_BOS vs. CHI,matchup_BOS vs. CLE,matchup_BOS vs. DAL,matchup_BOS vs. DEN,matchup_BOS vs. DET,matchup_BOS vs. GSW,matchup_BOS vs. HOU,matchup_BOS vs. IND,matchup_BOS vs. LAC,matchup_BOS vs. LAL,matchup_BOS vs. MEM,matchup_BOS vs. MIA,matchup_BOS vs. MIL,matchup_BOS vs. MIN,matchup_BOS vs. NJN,matchup_BOS vs. NOH,matchup_BOS vs. NOP,matchup_BOS vs. NYK,matchup_BOS vs. OKC,matchup_BOS vs. ORL,matchup_BOS vs. PHI,matchup_BOS vs. PHX,matchup_BOS vs. POR,matchup_BOS vs. SAC,matchup_BOS vs. SAS,matchup_BOS vs. TOR,matchup_BOS vs. UTA,matchup_BOS vs. WAS,matchup_CHA vs. CHI,matchup_CHA vs. CLE,matchup_CHA vs. DAL,matchup_CHA vs. DEN,matchup_CHA vs. DET,matchup_CHA vs. GSW,matchup_CHA vs. HOU,matchup_CHA vs. IND,matchup_CHA vs. LAC,matchup_CHA vs. LAL,matchup_CHA vs. MEM,matchup_CHA vs. MIA,matchup_CHA vs. MIL,matchup_CHA vs. MIN,matchup_CHA vs. NJN,matchup_CHA vs. NOH,matchup_CHA vs. NOP,matchup_CHA vs. NYK,matchup_CHA vs. OKC,matchup_CHA vs. ORL,matchup_CHA vs. PHI,matchup_CHA vs. PHX,matchup_CHA vs. POR,matchup_CHA vs. SAC,matchup_CHA vs. SAS,matchup_CHA vs. TOR,matchup_CHA vs. UTA,matchup_CHA vs. WAS,matchup_CHI vs. CLE,matchup_CHI vs. DAL,matchup_CHI vs. DEN,matchup_CHI vs. DET,matchup_CHI vs. GSW,matchup_CHI vs. HOU,matchup_CHI vs. IND,matchup_CHI vs. LAC,matchup_CHI vs. LAL,matchup_CHI vs. MEM,matchup_CHI vs. MIA,matchup_CHI vs. MIL,matchup_CHI vs. MIN,matchup_CHI vs. NJN,matchup_CHI vs. NOH,matchup_CHI vs. NOP,matchup_CHI vs. NYK,matchup_CHI vs. OKC,matchup_CHI vs. ORL,matchup_CHI vs. PHI,matchup_CHI vs. PHX,matchup_CHI vs. POR,matchup_CHI vs. SAC,matchup_CHI vs. SAS,matchup_CHI vs. TOR,matchup_CHI vs. UTA,matchup_CHI vs. WAS,matchup_CLE vs. DAL,matchup_CLE vs. DEN,matchup_CLE vs. DET,matchup_CLE vs. GSW,matchup_CLE vs. HOU,matchup_CLE vs. IND,matchup_CLE vs. LAC,matchup_CLE vs. LAL,matchup_CLE vs. MEM,matchup_CLE vs. MIA,matchup_CLE vs. MIL,matchup_CLE vs. MIN,matchup_CLE vs. NJN,matchup_CLE vs. NOH,matchup_CLE vs. NOP,matchup_CLE vs. NYK,matchup_CLE vs. OKC,matchup_CLE vs. ORL,matchup_CLE vs. PHI,matchup_CLE vs. PHX,matchup_CLE vs. POR,matchup_CLE vs. SAC,matchup_CLE vs. SAS,matchup_CLE vs. TOR,matchup_CLE vs. UTA,matchup_CLE vs. WAS,matchup_DAL vs. DEN,matchup_DAL vs. DET,matchup_DAL vs. GSW,matchup_DAL vs. HOU,matchup_DAL vs. IND,matchup_DAL vs. LAC,matchup_DAL vs. LAL,matchup_DAL vs. MEM,matchup_DAL vs. MIA,matchup_DAL vs. MIL,matchup_DAL vs. MIN,matchup_DAL vs. NJN,matchup_DAL vs. NOH,matchup_DAL vs. NOP,matchup_DAL vs. NYK,matchup_DAL vs. OKC,matchup_DAL vs. ORL,matchup_DAL vs. PHI,matchup_DAL vs. PHX,matchup_DAL vs. POR,matchup_DAL vs. SAC,matchup_DAL vs. SAS,matchup_DAL vs. TOR,matchup_DAL vs. UTA,matchup_DAL vs. WAS,matchup_DEN vs. DET,matchup_DEN vs. GSW,matchup_DEN vs. HOU,matchup_DEN vs. IND,matchup_DEN vs. LAC,matchup_DEN vs. LAL,matchup_DEN vs. MEM,matchup_DEN vs. MIA,matchup_DEN vs. MIL,matchup_DEN vs. MIN,matchup_DEN vs. NJN,matchup_DEN vs. NOH,matchup_DEN vs. NOP,matchup_DEN vs. NYK,matchup_DEN vs. OKC,matchup_DEN vs. ORL,matchup_DEN vs. PHI,matchup_DEN vs. PHX,matchup_DEN vs. POR,matchup_DEN vs. SAC,matchup_DEN vs. SAS,matchup_DEN vs. TOR,matchup_DEN vs. UTA,matchup_DEN vs. WAS,matchup_DET vs. GSW,matchup_DET vs. HOU,matchup_DET vs. IND,matchup_DET vs. LAC,matchup_DET vs. LAL,matchup_DET vs. MEM,matchup_DET vs. MIA,matchup_DET vs. MIL,matchup_DET vs. MIN,matchup_DET vs. NJN,matchup_DET vs. NOH,matchup_DET vs. NOP,matchup_DET vs. NYK,matchup_DET vs. OKC,matchup_DET vs. ORL,matchup_DET vs. PHI,matchup_DET vs. PHX,matchup_DET vs. POR,matchup_DET vs. SAC,matchup_DET vs. SAS,matchup_DET vs. TOR,matchup_DET vs. UTA,matchup_DET vs. WAS,matchup_GSW vs. HOU,matchup_GSW vs. IND,matchup_GSW vs. LAC,matchup_GSW vs. LAL,matchup_GSW vs. MEM,matchup_GSW vs. MIA,matchup_GSW vs. MIL,matchup_GSW vs. MIN,matchup_GSW vs. NJN,matchup_GSW vs. NOH,matchup_GSW vs. NOP,matchup_GSW vs. NYK,matchup_GSW vs. OKC,matchup_GSW vs. ORL,matchup_GSW vs. PHI,matchup_GSW vs. PHX,matchup_GSW vs. POR,matchup_GSW vs. SAC,matchup_GSW vs. SAS,matchup_GSW vs. TOR,matchup_GSW vs. UTA,matchup_GSW vs. WAS,matchup_HOU vs. IND,matchup_HOU vs. LAC,matchup_HOU vs. LAL,matchup_HOU vs. MEM,matchup_HOU vs. MIA,matchup_HOU vs. MIL,matchup_HOU vs. MIN,matchup_HOU vs. NJN,matchup_HOU vs. NOH,matchup_HOU vs. NOP,matchup_HOU vs. NYK,matchup_HOU vs. OKC,matchup_HOU vs. ORL,matchup_HOU vs. PHI,matchup_HOU vs. PHX,matchup_HOU vs. POR,matchup_HOU vs. SAC,matchup_HOU vs. SAS,matchup_HOU vs. TOR,matchup_HOU vs. UTA,matchup_HOU vs. WAS,matchup_IND vs. LAC,matchup_IND vs. LAL,matchup_IND vs. MEM,matchup_IND vs. MIA,matchup_IND vs. MIL,matchup_IND vs. MIN,matchup_IND vs. NJN,matchup_IND vs. NOH,matchup_IND vs. NOP,matchup_IND vs. NYK,matchup_IND vs. OKC,matchup_IND vs. ORL,matchup_IND vs. PHI,matchup_IND vs. PHX,matchup_IND vs. POR,matchup_IND vs. SAC,matchup_IND vs. SAS,matchup_IND vs. TOR,matchup_IND vs. UTA,matchup_IND vs. WAS,matchup_LAC vs. LAL,matchup_LAC vs. MEM,matchup_LAC vs. MIA,matchup_LAC vs. MIL,matchup_LAC vs. MIN,matchup_LAC vs. NJN,matchup_LAC vs. NOH,matchup_LAC vs. NOP,matchup_LAC vs. NYK,matchup_LAC vs. OKC,matchup_LAC vs. ORL,matchup_LAC vs. PHI,matchup_LAC vs. PHX,matchup_LAC vs. POR,matchup_LAC vs. SAC,matchup_LAC vs. SAS,matchup_LAC vs. TOR,matchup_LAC vs. UTA,matchup_LAC vs. WAS,matchup_LAL vs. MEM,matchup_LAL vs. MIA,matchup_LAL vs. MIL,matchup_LAL vs. MIN,matchup_LAL vs. NJN,matchup_LAL vs. NOH,matchup_LAL vs. NOP,matchup_LAL vs. NYK,matchup_LAL vs. OKC,matchup_LAL vs. ORL,matchup_LAL vs. PHI,matchup_LAL vs. PHX,matchup_LAL vs. POR,matchup_LAL vs. SAC,matchup_LAL vs. SAS,matchup_LAL vs. TOR,matchup_LAL vs. UTA,matchup_LAL vs. WAS,matchup_MEM vs. MIA,matchup_MEM vs. MIL,matchup_MEM vs. MIN,matchup_MEM vs. NJN,matchup_MEM vs. NOH,matchup_MEM vs. NOP,matchup_MEM vs. NYK,matchup_MEM vs. OKC,matchup_MEM vs. ORL,matchup_MEM vs. PHI,matchup_MEM vs. PHX,matchup_MEM vs. POR,matchup_MEM vs. SAC,matchup_MEM vs. SAS,matchup_MEM vs. TOR,matchup_MEM vs. UTA,matchup_MEM vs. WAS,matchup_MIA vs. MIL,matchup_MIA vs. MIN,matchup_MIA vs. NJN,matchup_MIA vs. NOH,matchup_MIA vs. NOP,matchup_MIA vs. NYK,matchup_MIA vs. OKC,matchup_MIA vs. ORL,matchup_MIA vs. PHI,matchup_MIA vs. PHX,matchup_MIA vs. POR,matchup_MIA vs. SAC,matchup_MIA vs. SAS,matchup_MIA vs. TOR,matchup_MIA vs. UTA,matchup_MIA vs. WAS,matchup_MIL vs. MIN,matchup_MIL vs. NJN,matchup_MIL vs. NOH,matchup_MIL vs. NOP,matchup_MIL vs. NYK,matchup_MIL vs. OKC,matchup_MIL vs. ORL,matchup_MIL vs. PHI,matchup_MIL vs. PHX,matchup_MIL vs. POR,matchup_MIL vs. SAC,matchup_MIL vs. SAS,matchup_MIL vs. TOR,matchup_MIL vs. UTA,matchup_MIL vs. WAS,matchup_MIN vs. NJN,matchup_MIN vs. NOH,matchup_MIN vs. NOP,matchup_MIN vs. NYK,matchup_MIN vs. OKC,matchup_MIN vs. ORL,matchup_MIN vs. PHI,matchup_MIN vs. PHX,matchup_MIN vs. POR,matchup_MIN vs. SAC,matchup_MIN vs. SAS,matchup_MIN vs. TOR,matchup_MIN vs. UTA,matchup_MIN vs. WAS,matchup_NJN vs. NOH,matchup_NJN vs. NYK,matchup_NJN vs. OKC,matchup_NJN vs. ORL,matchup_NJN vs. PHI,matchup_NJN vs. PHX,matchup_NJN vs. POR,matchup_NJN vs. SAC,matchup_NJN vs. SAS,matchup_NJN vs. TOR,matchup_NJN vs. UTA,matchup_NJN vs. WAS,matchup_NOH vs. NYK,matchup_NOH vs. OKC,matchup_NOH vs. ORL,matchup_NOH vs. PHI,matchup_NOH vs. PHX,matchup_NOH vs. POR,matchup_NOH vs. SAC,matchup_NOH vs. SAS,matchup_NOH vs. TOR,matchup_NOH vs. UTA,matchup_NOH vs. WAS,matchup_NOP vs. NYK,matchup_NOP vs. OKC,matchup_NOP vs. ORL,matchup_NOP vs. PHI,matchup_NOP vs. PHX,matchup_NOP vs. POR,matchup_NOP vs. SAC,matchup_NOP vs. SAS,matchup_NOP vs. TOR,matchup_NOP vs. UTA,matchup_NOP vs. WAS,matchup_NYK vs. OKC,matchup_NYK vs. ORL,matchup_NYK vs. PHI,matchup_NYK vs. PHX,matchup_NYK vs. POR,matchup_NYK vs. SAC,matchup_NYK vs. SAS,matchup_NYK vs. TOR,matchup_NYK vs. UTA,matchup_NYK vs. WAS,matchup_OKC vs. ORL,matchup_OKC vs. PHI,matchup_OKC vs. PHX,matchup_OKC vs. POR,matchup_OKC vs. SAC,matchup_OKC vs. SAS,matchup_OKC vs. TOR,matchup_OKC vs. UTA,matchup_OKC vs. WAS,matchup_ORL vs. PHI,matchup_ORL vs. PHX,matchup_ORL vs. POR,matchup_ORL vs. SAC,matchup_ORL vs. SAS,matchup_ORL vs. TOR,matchup_ORL vs. UTA,matchup_ORL vs. WAS,matchup_PHI vs. PHX,matchup_PHI vs. POR,matchup_PHI vs. SAC,matchup_PHI vs. SAS,matchup_PHI vs. TOR,matchup_PHI vs. UTA,matchup_PHI vs. WAS,matchup_PHX vs. POR,matchup_PHX vs. SAC,matchup_PHX vs. SAS,matchup_PHX vs. TOR,matchup_PHX vs. UTA,matchup_PHX vs. WAS,matchup_POR vs. SAC,matchup_POR vs. SAS,matchup_POR vs. TOR,matchup_POR vs. UTA,matchup_POR vs. WAS,matchup_SAC vs. SAS,matchup_SAC vs. TOR,matchup_SAC vs. UTA,matchup_SAC vs. WAS,matchup_SAS vs. TOR,matchup_SAS vs. UTA,matchup_SAS vs. WAS,matchup_TOR vs. UTA,matchup_TOR vs. WAS,matchup_UTA vs. WAS,season_type_Playoffs,season_type_Regular Season,season_2010-11,season_2011-12,season_2012-13,season_2013-14,season_2014-15,season_2015-16,season_2016-17,season_2017-18,TEAM_NAME_b_76ers,TEAM_NAME_b_Bobcats,TEAM_NAME_b_Bucks,TEAM_NAME_b_Bulls,TEAM_NAME_b_Cavaliers,TEAM_NAME_b_Celtics,TEAM_NAME_b_Clippers,TEAM_NAME_b_Grizzlies,TEAM_NAME_b_Heat,TEAM_NAME_b_Hornets,TEAM_NAME_b_Jazz,TEAM_NAME_b_Kings,TEAM_NAME_b_Knicks,TEAM_NAME_b_Lakers,TEAM_NAME_b_Magic,TEAM_NAME_b_Mavericks,TEAM_NAME_b_Nets,TEAM_NAME_b_Nuggets,TEAM_NAME_b_Pacers,TEAM_NAME_b_Pelicans,TEAM_NAME_b_Pistons,TEAM_NAME_b_Raptors,TEAM_NAME_b_Rockets,TEAM_NAME_b_Spurs,TEAM_NAME_b_Suns,TEAM_NAME_b_Thunder,TEAM_NAME_b_Timberwolves,TEAM_NAME_b_Trail Blazers,TEAM_NAME_b_Warriors,TEAM_NAME_b_Wizards,TEAM_ABBREVIATION_b_BKN,TEAM_ABBREVIATION_b_BOS,TEAM_ABBREVIATION_b_CHA,TEAM_ABBREVIATION_b_CHI,TEAM_ABBREVIATION_b_CLE,TEAM_ABBREVIATION_b_DAL,TEAM_ABBREVIATION_b_DEN,TEAM_ABBREVIATION_b_DET,TEAM_ABBREVIATION_b_GSW,TEAM_ABBREVIATION_b_HOU,TEAM_ABBREVIATION_b_IND,TEAM_ABBREVIATION_b_LAC,TEAM_ABBREVIATION_b_LAL,TEAM_ABBREVIATION_b_MEM,TEAM_ABBREVIATION_b_MIA,TEAM_ABBREVIATION_b_MIL,TEAM_ABBREVIATION_b_MIN,TEAM_ABBREVIATION_b_NJN,TEAM_ABBREVIATION_b_NOH,TEAM_ABBREVIATION_b_NOP,TEAM_ABBREVIATION_b_NYK,TEAM_ABBREVIATION_b_OKC,TEAM_ABBREVIATION_b_ORL,TEAM_ABBREVIATION_b_PHI,TEAM_ABBREVIATION_b_PHX,TEAM_ABBREVIATION_b_POR,TEAM_ABBREVIATION_b_SAC,TEAM_ABBREVIATION_b_SAS,TEAM_ABBREVIATION_b_TOR,TEAM_ABBREVIATION_b_UTA,TEAM_ABBREVIATION_b_WAS,TEAM_CITY_b_Boston,TEAM_CITY_b_Brooklyn,TEAM_CITY_b_Charlotte,TEAM_CITY_b_Chicago,TEAM_CITY_b_Cleveland,TEAM_CITY_b_Dallas,TEAM_CITY_b_Denver,TEAM_CITY_b_Detroit,TEAM_CITY_b_Golden State,TEAM_CITY_b_Houston,TEAM_CITY_b_Indiana,TEAM_CITY_b_Los Angeles,TEAM_CITY_b_Memphis,TEAM_CITY_b_Miami,TEAM_CITY_b_Milwaukee,TEAM_CITY_b_Minnesota,TEAM_CITY_b_New Jersey,TEAM_CITY_b_New Orleans,TEAM_CITY_b_New York,TEAM_CITY_b_Oklahoma City,TEAM_CITY_b_Orlando,TEAM_CITY_b_Philadelphia,TEAM_CITY_b_Phoenix,TEAM_CITY_b_Portland,TEAM_CITY_b_Sacramento,TEAM_CITY_b_San Antonio,TEAM_CITY_b_Toronto,TEAM_CITY_b_Utah,TEAM_CITY_b_Washington
0,21000001,-8,2010-10-26,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1610612738,1610612748,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [13]:
df = df.drop(columns=['game_id', 'game_date'])
p(df)

(10266, 779)

,spread_a,E_OFF_RATING_cma_diff,OFF_RATING_cma_diff,E_DEF_RATING_cma_diff,DEF_RATING_cma_diff,E_NET_RATING_cma_diff,NET_RATING_cma_diff,AST_PCT_cma_diff,AST_TOV_cma_diff,AST_RATIO_cma_diff,OREB_PCT_cma_diff,DREB_PCT_cma_diff,REB_PCT_cma_diff,E_TM_TOV_PCT_cma_diff,TM_TOV_PCT_cma_diff,EFG_PCT_cma_diff,TS_PCT_cma_diff,USG_PCT_cma_diff,E_USG_PCT_cma_diff,E_PACE_cma_diff,PACE_cma_diff,PACE_PER40_cma_diff,POSS_cma_diff,PIE_cma_diff,duration_minutes_cma_diff,w_pct_cma_diff,min_cma_diff,fgm_cma_diff,fga_cma_diff,fg_pct_cma_diff,fg3m_cma_diff,fg3a_cma_diff,fg3_pct_cma_diff,ftm_cma_diff,fta_cma_diff,ft_pct_cma_diff,oreb_cma_diff,dreb_cma_diff,reb_cma_diff,ast_cma_diff,stl_cma_diff,blk_cma_diff,tov_cma_diff,pf_cma_diff,pts_cma_diff,spread_cma_diff,away_home_cma_diff,E_OFF_RATING_sm_cma_diff,OFF_RATING_sm_cma_diff,E_DEF_RATING_sm_cma_diff,DEF_RATING_sm_cma_diff,E_NET_RATING_sm_cma_diff,NET_RATING_sm_cma_diff,AST_PCT_sm_cma_diff,AST_TOV_sm_cma_diff,AST_RATIO_sm_cma_diff,OREB_PCT_sm_cma_diff,DREB_PCT_sm_cma_diff,REB_PCT_sm_cma_diff,E_TM_TOV_PCT_sm_cma_diff,TM_TOV_PCT_sm_cma_diff,EFG_PCT_sm_cma_diff,TS_PCT_sm_cma_diff,USG_PCT_sm_cma_diff,E_USG_PCT_sm_cma_diff,E_PACE_sm_cma_diff,PACE_sm_cma_diff,PACE_PER40_sm_cma_diff,POSS_sm_cma_diff,PIE_sm_cma_diff,duration_minutes_sm_cma_diff,w_pct_sm_cma_diff,min_sm_cma_diff,fgm_sm_cma_diff,fga_sm_cma_diff,fg_pct_sm_cma_diff,fg3m_sm_cma_diff,fg3a_sm_cma_diff,fg3_pct_sm_cma_diff,ftm_sm_cma_diff,fta_sm_cma_diff,ft_pct_sm_cma_diff,oreb_sm_cma_diff,dreb_sm_cma_diff,reb_sm_cma_diff,ast_sm_cma_diff,stl_sm_cma_diff,blk_sm_cma_diff,tov_sm_cma_diff,pf_sm_cma_diff,pts_sm_cma_diff,spread_sm_cma_diff,away_home_sm_cma_diff,team_id_a,team_id_b,away_home_a,TEAM_NAME_a_76ers,TEAM_NAME_a_Bobcats,TEAM_NAME_a_Bucks,TEAM_NAME_a_Bulls,TEAM_NAME_a_Cavaliers,TEAM_NAME_a_Celtics,TEAM_NAME_a_Clippers,TEAM_NAME_a_Grizzlies,TEAM_NAME_a_Hawks,TEAM_NAME_a_Heat,TEAM_NAME_a_Hornets,TEAM_NAME_a_Jazz,TEAM_NAME_a_Kings,TEAM_NAME_a_Knicks,TEAM_NAME_a_Lakers,TEAM_NAME_a_Magic,TEAM_NAME_a_Mavericks,TEAM_NAME_a_Nets,TEAM_NAME_a_Nuggets,TEAM_NAME_a_Pacers,TEAM_NAME_a_Pelicans,TEAM_NAME_a_Pistons,TEAM_NAME_a_Raptors,TEAM_NAME_a_Rockets,TEAM_NAME_a_Spurs,TEAM_NAME_a_Suns,TEAM_NAME_a_Thunder,TEAM_NAME_a_Timberwolves,TEAM_NAME_a_Trail Blazers,TEAM_NAME_a_Warriors,TEAM_ABBREVIATION_a_ATL,TEAM_ABBREVIATION_a_BKN,TEAM_ABBREVIATION_a_BOS,TEAM_ABBREVIATION_a_CHA,TEAM_ABBREVIATION_a_CHI,TEAM_ABBREVIATION_a_CLE,TEAM_ABBREVIATION_a_DAL,TEAM_ABBREVIATION_a_DEN,TEAM_ABBREVIATION_a_DET,TEAM_ABBREVIATION_a_GSW,TEAM_ABBREVIATION_a_HOU,TEAM_ABBREVIATION_a_IND,TEAM_ABBREVIATION_a_LAC,TEAM_ABBREVIATION_a_LAL,TEAM_ABBREVIATION_a_MEM,TEAM_ABBREVIATION_a_MIA,TEAM_ABBREVIATION_a_MIL,TEAM_ABBREVIATION_a_MIN,TEAM_ABBREVIATION_a_NJN,TEAM_ABBREVIATION_a_NOH,TEAM_ABBREVIATION_a_NOP,TEAM_ABBREVIATION_a_NYK,TEAM_ABBREVIATION_a_OKC,TEAM_ABBREVIATION_a_ORL,TEAM_ABBREVIATION_a_PHI,TEAM_ABBREVIATION_a_PHX,TEAM_ABBREVIATION_a_POR,TEAM_ABBREVIATION_a_SAC,TEAM_ABBREVIATION_a_SAS,TEAM_ABBREVIATION_a_TOR,TEAM_ABBREVIATION_a_UTA,TEAM_CITY_a_Atlanta,TEAM_CITY_a_Boston,TEAM_CITY_a_Brooklyn,TEAM_CITY_a_Charlotte,TEAM_CITY_a_Chicago,TEAM_CITY_a_Cleveland,TEAM_CITY_a_Dallas,TEAM_CITY_a_Denver,TEAM_CITY_a_Detroit,TEAM_CITY_a_Golden State,TEAM_CITY_a_Houston,TEAM_CITY_a_Indiana,TEAM_CITY_a_Los Angeles,TEAM_CITY_a_Memphis,TEAM_CITY_a_Miami,TEAM_CITY_a_Milwaukee,TEAM_CITY_a_Minnesota,TEAM_CITY_a_New Jersey,TEAM_CITY_a_New Orleans,TEAM_CITY_a_New York,TEAM_CITY_a_Oklahoma City,TEAM_CITY_a_Orlando,TEAM_CITY_a_Philadelphia,TEAM_CITY_a_Phoenix,TEAM_CITY_a_Portland,TEAM_CITY_a_Sacramento,TEAM_CITY_a_San Antonio,TEAM_CITY_a_Toronto,TEAM_CITY_a_Utah,matchup_ATL vs. BKN,matchup_ATL vs. BOS,matchup_ATL vs. CHA,matchup_ATL vs. CHI,matchup_ATL vs. CLE,matchup_ATL vs. DAL,matchup_ATL vs. DEN,matchup_ATL vs. DET,matchup_ATL vs. GSW,matchup_ATL vs. HOU,matchup_ATL vs. IND,matchup_ATL vs. LAC,matchup_ATL vs. LAL,matchup_ATL vs. MEM,matchup_ATL vs. MIA,matchup_ATL vs. MIL,matchup_ATL vs. MIN,matchup_ATL vs. NJN,matchup_ATL vs. NOH,matchup_ATL vs. NOP,matchup_ATL vs. NYK,matchup_ATL vs. OKC,matchup_ATL vs. ORL,matchup_ATL vs. PHI,matchup_ATL vs. PHX,matchup_ATL vs. POR,matchup_ATL vs. SAC,matchup_ATL vs. SAS,matchup_ATL vs. TOR,matchup_ATL vs. UTA,matchup_ATL vs. WAS,matchup_BKN vs. BOS,matchup_BKN vs. CHA,matchup_BKN vs. CHI,matchup_BKN vs. CLE,matchup_BKN vs. DAL,matchup_BKN vs. DEN,matchup_BKN vs. DET,matchup_BKN vs. GSW,matchup_BKN vs. HOU,matchup_BKN vs. IND,matchup_BKN vs. LAC,matchup_BKN vs. LAL,matchup_BKN vs. MEM,matchup_BKN vs. MIA,matchup_BKN vs. MIL,matchup_BKN vs. MIN,matchup_BKN vs. NOH,matchup_BKN vs. NOP,matchup_BKN vs. NYK,matchup_BKN vs. OKC,matchup_BKN vs. ORL,matchup_BKN vs. PHI,matchup_BKN vs. PHX,matchup_BKN vs. POR,matchup_BKN vs. SAC,matchup_BKN vs. SAS,matchup_BKN vs. TOR,matchup_BKN vs. UTA,matchup_BKN vs. WAS,matchup_BOS vs. CHA,matchup_BOS vs. CHI,matchup_BOS vs. CLE,matchup_BOS vs. DAL,matchup_BOS vs. DEN,matchup_BOS vs. DET,matchup_BOS vs. GSW,matchup_BOS vs. HOU,matchup_BOS vs. IND,matchup_BOS vs. LAC,matchup_BOS vs. LAL,matchup_BOS vs. MEM,matchup_BOS vs. MIA,matchup_BOS vs. MIL,matchup_BOS vs. MIN,matchup_BOS vs. NJN,matchup_BOS vs. NOH,matchup_BOS vs. NOP,matchup_BOS vs. NYK,matchup_BOS vs. OKC,matchup_BOS vs. ORL,matchup_BOS vs. PHI,matchup_BOS vs. PHX,matchup_BOS vs. POR,matchup_BOS vs. SAC,matchup_BOS vs. SAS,matchup_BOS vs. TOR,matchup_BOS vs. UTA,matchup_BOS vs. WAS,matchup_CHA vs. CHI,matchup_CHA vs. CLE,matchup_CHA vs. DAL,matchup_CHA vs. DEN,matchup_CHA vs. DET,matchup_CHA vs. GSW,matchup_CHA vs. HOU,matchup_CHA vs. IND,matchup_CHA vs. LAC,matchup_CHA vs. LAL,matchup_CHA vs. MEM,matchup_CHA vs. MIA,matchup_CHA vs. MIL,matchup_CHA vs. MIN,matchup_CHA vs. NJN,matchup_CHA vs. NOH,matchup_CHA vs. NOP,matchup_CHA vs. NYK,matchup_CHA vs. OKC,matchup_CHA vs. ORL,matchup_CHA vs. PHI,matchup_CHA vs. PHX,matchup_CHA vs. POR,matchup_CHA vs. SAC,matchup_CHA vs. SAS,matchup_CHA vs. TOR,matchup_CHA vs. UTA,matchup_CHA vs. WAS,matchup_CHI vs. CLE,matchup_CHI vs. DAL,matchup_CHI vs. DEN,matchup_CHI vs. DET,matchup_CHI vs. GSW,matchup_CHI vs. HOU,matchup_CHI vs. IND,matchup_CHI vs. LAC,matchup_CHI vs. LAL,matchup_CHI vs. MEM,matchup_CHI vs. MIA,matchup_CHI vs. MIL,matchup_CHI vs. MIN,matchup_CHI vs. NJN,matchup_CHI vs. NOH,matchup_CHI vs. NOP,matchup_CHI vs. NYK,matchup_CHI vs. OKC,matchup_CHI vs. ORL,matchup_CHI vs. PHI,matchup_CHI vs. PHX,matchup_CHI vs. POR,matchup_CHI vs. SAC,matchup_CHI vs. SAS,matchup_CHI vs. TOR,matchup_CHI vs. UTA,matchup_CHI vs. WAS,matchup_CLE vs. DAL,matchup_CLE vs. DEN,matchup_CLE vs. DET,matchup_CLE vs. GSW,matchup_CLE vs. HOU,matchup_CLE vs. IND,matchup_CLE vs. LAC,matchup_CLE vs. LAL,matchup_CLE vs. MEM,matchup_CLE vs. MIA,matchup_CLE vs. MIL,matchup_CLE vs. MIN,matchup_CLE vs. NJN,matchup_CLE vs. NOH,matchup_CLE vs. NOP,matchup_CLE vs. NYK,matchup_CLE vs. OKC,matchup_CLE vs. ORL,matchup_CLE vs. PHI,matchup_CLE vs. PHX,matchup_CLE vs. POR,matchup_CLE vs. SAC,matchup_CLE vs. SAS,matchup_CLE vs. TOR,matchup_CLE vs. UTA,matchup_CLE vs. WAS,matchup_DAL vs. DEN,matchup_DAL vs. DET,matchup_DAL vs. GSW,matchup_DAL vs. HOU,matchup_DAL vs. IND,matchup_DAL vs. LAC,matchup_DAL vs. LAL,matchup_DAL vs. MEM,matchup_DAL vs. MIA,matchup_DAL vs. MIL,matchup_DAL vs. MIN,matchup_DAL vs. NJN,matchup_DAL vs. NOH,matchup_DAL vs. NOP,matchup_DAL vs. NYK,matchup_DAL vs. OKC,matchup_DAL vs. ORL,matchup_DAL vs. PHI,matchup_DAL vs. PHX,matchup_DAL vs. POR,matchup_DAL vs. SAC,matchup_DAL vs. SAS,matchup_DAL vs. TOR,matchup_DAL vs. UTA,matchup_DAL vs. WAS,matchup_DEN vs. DET,matchup_DEN vs. GSW,matchup_DEN vs. HOU,matchup_DEN vs. IND,matchup_DEN vs. LAC,matchup_DEN vs. LAL,matchup_DEN vs. MEM,matchup_DEN vs. MIA,matchup_DEN vs. MIL,matchup_DEN vs. MIN,matchup_DEN vs. NJN,matchup_DEN vs. NOH,matchup_DEN vs. NOP,matchup_DEN vs. NYK,matchup_DEN vs. OKC,matchup_DEN vs. ORL,matchup_DEN vs. PHI,matchup_DEN vs. PHX,matchup_DEN vs. POR,matchup_DEN vs. SAC,matchup_DEN vs. SAS,matchup_DEN vs. TOR,matchup_DEN vs. UTA,matchup_DEN vs. WAS,matchup_DET vs. GSW,matchup_DET vs. HOU,matchup_DET vs. IND,matchup_DET vs. LAC,matchup_DET vs. LAL,matchup_DET vs. MEM,matchup_DET vs. MIA,matchup_DET vs. MIL,matchup_DET vs. MIN,matchup_DET vs. NJN,matchup_DET vs. NOH,matchup_DET vs. NOP,matchup_DET vs. NYK,matchup_DET vs. OKC,matchup_DET vs. ORL,matchup_DET vs. PHI,matchup_DET vs. PHX,matchup_DET vs. POR,matchup_DET vs. SAC,matchup_DET vs. SAS,matchup_DET vs. TOR,matchup_DET vs. UTA,matchup_DET vs. WAS,matchup_GSW vs. HOU,matchup_GSW vs. IND,matchup_GSW vs. LAC,matchup_GSW vs. LAL,matchup_GSW vs. MEM,matchup_GSW vs. MIA,matchup_GSW vs. MIL,matchup_GSW vs. MIN,matchup_GSW vs. NJN,matchup_GSW vs. NOH,matchup_GSW vs. NOP,matchup_GSW vs. NYK,matchup_GSW vs. OKC,matchup_GSW vs. ORL,matchup_GSW vs. PHI,matchup_GSW vs. PHX,matchup_GSW vs. POR,matchup_GSW vs. SAC,matchup_GSW vs. SAS,matchup_GSW vs. TOR,matchup_GSW vs. UTA,matchup_GSW vs. WAS,matchup_HOU vs. IND,matchup_HOU vs. LAC,matchup_HOU vs. LAL,matchup_HOU vs. MEM,matchup_HOU vs. MIA,matchup_HOU vs. MIL,matchup_HOU vs. MIN,matchup_HOU vs. NJN,matchup_HOU vs. NOH,matchup_HOU vs. NOP,matchup_HOU vs. NYK,matchup_HOU vs. OKC,matchup_HOU vs. ORL,matchup_HOU vs. PHI,matchup_HOU vs. PHX,matchup_HOU vs. POR,matchup_HOU vs. SAC,matchup_HOU vs. SAS,matchup_HOU vs. TOR,matchup_HOU vs. UTA,matchup_HOU vs. WAS,matchup_IND vs. LAC,matchup_IND vs. LAL,matchup_IND vs. MEM,matchup_IND vs. MIA,matchup_IND vs. MIL,matchup_IND vs. MIN,matchup_IND vs. NJN,matchup_IND vs. NOH,matchup_IND vs. NOP,matchup_IND vs. NYK,matchup_IND vs. OKC,matchup_IND vs. ORL,matchup_IND vs. PHI,matchup_IND vs. PHX,matchup_IND vs. POR,matchup_IND vs. SAC,matchup_IND vs. SAS,matchup_IND vs. TOR,matchup_IND vs. UTA,matchup_IND vs. WAS,matchup_LAC vs. LAL,matchup_LAC vs. MEM,matchup_LAC vs. MIA,matchup_LAC vs. MIL,matchup_LAC vs. MIN,matchup_LAC vs. NJN,matchup_LAC vs. NOH,matchup_LAC vs. NOP,matchup_LAC vs. NYK,matchup_LAC vs. OKC,matchup_LAC vs. ORL,matchup_LAC vs. PHI,matchup_LAC vs. PHX,matchup_LAC vs. POR,matchup_LAC vs. SAC,matchup_LAC vs. SAS,matchup_LAC vs. TOR,matchup_LAC vs. UTA,matchup_LAC vs. WAS,matchup_LAL vs. MEM,matchup_LAL vs. MIA,matchup_LAL vs. MIL,matchup_LAL vs. MIN,matchup_LAL vs. NJN,matchup_LAL vs. NOH,matchup_LAL vs. NOP,matchup_LAL vs. NYK,matchup_LAL vs. OKC,matchup_LAL vs. ORL,matchup_LAL vs. PHI,matchup_LAL vs. PHX,matchup_LAL vs. POR,matchup_LAL vs. SAC,matchup_LAL vs. SAS,matchup_LAL vs. TOR,matchup_LAL vs. UTA,matchup_LAL vs. WAS,matchup_MEM vs. MIA,matchup_MEM vs. MIL,matchup_MEM vs. MIN,matchup_MEM vs. NJN,matchup_MEM vs. NOH,matchup_MEM vs. NOP,matchup_MEM vs. NYK,matchup_MEM vs. OKC,matchup_MEM vs. ORL,matchup_MEM vs. PHI,matchup_MEM vs. PHX,matchup_MEM vs. POR,matchup_MEM vs. SAC,matchup_MEM vs. SAS,matchup_MEM vs. TOR,matchup_MEM vs. UTA,matchup_MEM vs. WAS,matchup_MIA vs. MIL,matchup_MIA vs. MIN,matchup_MIA vs. NJN,matchup_MIA vs. NOH,matchup_MIA vs. NOP,matchup_MIA vs. NYK,matchup_MIA vs. OKC,matchup_MIA vs. ORL,matchup_MIA vs. PHI,matchup_MIA vs. PHX,matchup_MIA vs. POR,matchup_MIA vs. SAC,matchup_MIA vs. SAS,matchup_MIA vs. TOR,matchup_MIA vs. UTA,matchup_MIA vs. WAS,matchup_MIL vs. MIN,matchup_MIL vs. NJN,matchup_MIL vs. NOH,matchup_MIL vs. NOP,matchup_MIL vs. NYK,matchup_MIL vs. OKC,matchup_MIL vs. ORL,matchup_MIL vs. PHI,matchup_MIL vs. PHX,matchup_MIL vs. POR,matchup_MIL vs. SAC,matchup_MIL vs. SAS,matchup_MIL vs. TOR,matchup_MIL vs. UTA,matchup_MIL vs. WAS,matchup_MIN vs. NJN,matchup_MIN vs. NOH,matchup_MIN vs. NOP,matchup_MIN vs. NYK,matchup_MIN vs. OKC,matchup_MIN vs. ORL,matchup_MIN vs. PHI,matchup_MIN vs. PHX,matchup_MIN vs. POR,matchup_MIN vs. SAC,matchup_MIN vs. SAS,matchup_MIN vs. TOR,matchup_MIN vs. UTA,matchup_MIN vs. WAS,matchup_NJN vs. NOH,matchup_NJN vs. NYK,matchup_NJN vs. OKC,matchup_NJN vs. ORL,matchup_NJN vs. PHI,matchup_NJN vs. PHX,matchup_NJN vs. POR,matchup_NJN vs. SAC,matchup_NJN vs. SAS,matchup_NJN vs. TOR,matchup_NJN vs. UTA,matchup_NJN vs. WAS,matchup_NOH vs. NYK,matchup_NOH vs. OKC,matchup_NOH vs. ORL,matchup_NOH vs. PHI,matchup_NOH vs. PHX,matchup_NOH vs. POR,matchup_NOH vs. SAC,matchup_NOH vs. SAS,matchup_NOH vs. TOR,matchup_NOH vs. UTA,matchup_NOH vs. WAS,matchup_NOP vs. NYK,matchup_NOP vs. OKC,matchup_NOP vs. ORL,matchup_NOP vs. PHI,matchup_NOP vs. PHX,matchup_NOP vs. POR,matchup_NOP vs. SAC,matchup_NOP vs. SAS,matchup_NOP vs. TOR,matchup_NOP vs. UTA,matchup_NOP vs. WAS,matchup_NYK vs. OKC,matchup_NYK vs. ORL,matchup_NYK vs. PHI,matchup_NYK vs. PHX,matchup_NYK vs. POR,matchup_NYK vs. SAC,matchup_NYK vs. SAS,matchup_NYK vs. TOR,matchup_NYK vs. UTA,matchup_NYK vs. WAS,matchup_OKC vs. ORL,matchup_OKC vs. PHI,matchup_OKC vs. PHX,matchup_OKC vs. POR,matchup_OKC vs. SAC,matchup_OKC vs. SAS,matchup_OKC vs. TOR,matchup_OKC vs. UTA,matchup_OKC vs. WAS,matchup_ORL vs. PHI,matchup_ORL vs. PHX,matchup_ORL vs. POR,matchup_ORL vs. SAC,matchup_ORL vs. SAS,matchup_ORL vs. TOR,matchup_ORL vs. UTA,matchup_ORL vs. WAS,matchup_PHI vs. PHX,matchup_PHI vs. POR,matchup_PHI vs. SAC,matchup_PHI vs. SAS,matchup_PHI vs. TOR,matchup_PHI vs. UTA,matchup_PHI vs. WAS,matchup_PHX vs. POR,matchup_PHX vs. SAC,matchup_PHX vs. SAS,matchup_PHX vs. TOR,matchup_PHX vs. UTA,matchup_PHX vs. WAS,matchup_POR vs. SAC,matchup_POR vs. SAS,matchup_POR vs. TOR,matchup_POR vs. UTA,matchup_POR vs. WAS,matchup_SAC vs. SAS,matchup_SAC vs. TOR,matchup_SAC vs. UTA,matchup_SAC vs. WAS,matchup_SAS vs. TOR,matchup_SAS vs. UTA,matchup_SAS vs. WAS,matchup_TOR vs. UTA,matchup_TOR vs. WAS,matchup_UTA vs. WAS,season_type_Playoffs,season_type_Regular Season,season_2010-11,season_2011-12,season_2012-13,season_2013-14,season_2014-15,season_2015-16,season_2016-17,season_2017-18,TEAM_NAME_b_76ers,TEAM_NAME_b_Bobcats,TEAM_NAME_b_Bucks,TEAM_NAME_b_Bulls,TEAM_NAME_b_Cavaliers,TEAM_NAME_b_Celtics,TEAM_NAME_b_Clippers,TEAM_NAME_b_Grizzlies,TEAM_NAME_b_Heat,TEAM_NAME_b_Hornets,TEAM_NAME_b_Jazz,TEAM_NAME_b_Kings,TEAM_NAME_b_Knicks,TEAM_NAME_b_Lakers,TEAM_NAME_b_Magic,TEAM_NAME_b_Mavericks,TEAM_NAME_b_Nets,TEAM_NAME_b_Nuggets,TEAM_NAME_b_Pacers,TEAM_NAME_b_Pelicans,TEAM_NAME_b_Pistons,TEAM_NAME_b_Raptors,TEAM_NAME_b_Rockets,TEAM_NAME_b_Spurs,TEAM_NAME_b_Suns,TEAM_NAME_b_Thunder,TEAM_NAME_b_Timberwolves,TEAM_NAME_b_Trail Blazers,TEAM_NAME_b_Warriors,TEAM_NAME_b_Wizards,TEAM_ABBREVIATION_b_BKN,TEAM_ABBREVIATION_b_BOS,TEAM_ABBREVIATION_b_CHA,TEAM_ABBREVIATION_b_CHI,TEAM_ABBREVIATION_b_CLE,TEAM_ABBREVIATION_b_DAL,TEAM_ABBREVIATION_b_DEN,TEAM_ABBREVIATION_b_DET,TEAM_ABBREVIATION_b_GSW,TEAM_ABBREVIATION_b_HOU,TEAM_ABBREVIATION_b_IND,TEAM_ABBREVIATION_b_LAC,TEAM_ABBREVIATION_b_LAL,TEAM_ABBREVIATION_b_MEM,TEAM_ABBREVIATION_b_MIA,TEAM_ABBREVIATION_b_MIL,TEAM_ABBREVIATION_b_MIN,TEAM_ABBREVIATION_b_NJN,TEAM_ABBREVIATION_b_NOH,TEAM_ABBREVIATION_b_NOP,TEAM_ABBREVIATION_b_NYK,TEAM_ABBREVIATION_b_OKC,TEAM_ABBREVIATION_b_ORL,TEAM_ABBREVIATION_b_PHI,TEAM_ABBREVIATION_b_PHX,TEAM_ABBREVIATION_b_POR,TEAM_ABBREVIATION_b_SAC,TEAM_ABBREVIATION_b_SAS,TEAM_ABBREVIATION_b_TOR,TEAM_ABBREVIATION_b_UTA,TEAM_ABBREVIATION_b_WAS,TEAM_CITY_b_Boston,TEAM_CITY_b_Brooklyn,TEAM_CITY_b_Charlotte,TEAM_CITY_b_Chicago,TEAM_CITY_b_Cleveland,TEAM_CITY_b_Dallas,TEAM_CITY_b_Denver,TEAM_CITY_b_Detroit,TEAM_CITY_b_Golden State,TEAM_CITY_b_Houston,TEAM_CITY_b_Indiana,TEAM_CITY_b_Los Angeles,TEAM_CITY_b_Memphis,TEAM_CITY_b_Miami,TEAM_CITY_b_Milwaukee,TEAM_CITY_b_Minnesota,TEAM_CITY_b_New Jersey,TEAM_CITY_b_New Orleans,TEAM_CITY_b_New York,TEAM_CITY_b_Oklahoma City,TEAM_CITY_b_Orlando,TEAM_CITY_b_Philadelphia,TEAM_CITY_b_Phoenix,TEAM_CITY_b_Portland,TEAM_CITY_b_Sacramento,TEAM_CITY_b_San Antonio,TEAM_CITY_b_Toronto,TEAM_CITY_b_Utah,TEAM_CITY_b_Washington
0,-8,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1610612738,1610612748,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,14,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1610612756,1610612757,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0

In [14]:
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns='spread_a'), 
                                                    df.spread_a, test_size=0.3, 
                                                    random_state=47)

In [16]:
scaler = StandardScaler()

In [17]:
scaler.fit(X_train)

X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [18]:
X_train_scaled

array([[ 0.03030427, -0.0865669 , -0.50811061, ..., -0.25352959,
        -0.25569858, -0.25999554],
       [ 0.38630736,  0.49407582,  0.00807544, ..., -0.25352959,
        -0.25569858, -0.25999554],
       [ 0.12897904, -0.10498461,  0.27980548, ...,  3.94431283,
        -0.25569858, -0.25999554],
       ...,
       [-1.13251018, -1.03362523,  1.48087244, ..., -0.25352959,
        -0.25569858, -0.25999554],
       [ 0.28763259,  0.3195922 ,  0.32122158, ..., -0.25352959,
        -0.25569858, -0.25999554],
       [ 0.88064862,  0.85370596,  0.31213024, ..., -0.25352959,
        -0.25569858, -0.25999554]])

In [19]:
X_test_scaled

array([[  0.83131123,   0.79748345,  -0.96469788, ...,  -0.25352959,
         -0.25569858,  -0.25999554],
       [  1.02672597,   0.91768328,   0.2616228 , ...,  -0.25352959,
         -0.25569858,  -0.25999554],
       [ -9.78977018, -10.79501455, -12.22381672, ...,  -0.25352959,
         -0.25569858,  -0.25999554],
       ...,
       [ -0.61108174,  -0.65557738,   0.77174796, ...,  -0.25352959,
         -0.25569858,  -0.25999554],
       [ -0.27829624,  -0.17477806,   0.41920602, ...,  -0.25352959,
         -0.25569858,  -0.25999554],
       [ -1.35404471,  -1.30407484,  -0.66670397, ...,  -0.25352959,
         -0.25569858,  -0.25999554]])

In [20]:
lm = LinearRegression().fit(X_train_scaled, y_train)

In [21]:
y_train_pred = lm.predict(X_train_scaled)
y_test_pred = lm.predict(X_test_scaled)

In [23]:

# r^2 - train, test
linear_regression_r2_score = r2_score(y_train, y_train_pred), r2_score(y_test, y_test_pred)
linear_regression_r2_score

(0.22431770482002755, 0.07466476063527627)

<font color='red'> ???????????????????????</font>

In [24]:
linear_model_mse = mean_squared_error(y_train, y_train_pred), mean_squared_error(y_test, y_test_pred)
linear_model_mse

(143.84436724530104, 176.6659488019485)

<font color='red'> ?????????????????????????????????</font>

In [25]:
mean_absolute_error(y_train, y_train_pred), mean_absolute_error(y_test, y_test_pred)

(9.442653129018128, 10.52355452136699)

In [26]:
RF_pipe = make_pipeline(
    StandardScaler(),
    RandomForestRegressor(random_state=47)
)

In [27]:
rf_default_cv_results = cross_validate(RF_pipe, X_train, y_train, cv=5)

In [28]:
rf_cv_scores = rf_default_cv_results['test_score']
rf_cv_scores

array([0.16286598, 0.12012528, 0.13231787, 0.1933716 , 0.18417137])

In [29]:
np.mean(rf_cv_scores), np.std(rf_cv_scores)

(0.15857042022359608, 0.02846825454194327)

In [30]:
n_est = [int(n) for n in np.logspace(start=1, stop=3, num=20)]
grid_params = {
        'randomforestregressor__n_estimators': n_est,
        'standardscaler': [StandardScaler(), None],
}
grid_params

{'randomforestregressor__n_estimators': [10,
  12,
  16,
  20,
  26,
  33,
  42,
  54,
  69,
  88,
  112,
  143,
  183,
  233,
  297,
  379,
  483,
  615,
  784,
  1000],
 'standardscaler': [StandardScaler(), None]}

In [31]:
rf_grid_cv = GridSearchCV(RF_pipe, param_grid=grid_params, cv=5, n_jobs=-1)

In [32]:
rf_grid_cv.fit(X_train, y_train)

/opt/anaconda3/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py:688: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

KeyboardInterrupt:

In [ ]:
rf_grid_cv.best_params_

In [ ]:
rf_best_cv_results = cross_validate(rf_grid_cv.best_estimator_, X_train, y_train, cv=5)
rf_best_scores = rf_best_cv_results['test_score']
rf_best_scores

In [ ]:
np.mean(rf_best_scores), np.std(rf_best_scores)

In [ ]:
plt.subplots(figsize=(10, 5))
imps = rf_grid_cv.best_estimator_.named_steps.randomforestregressor.feature_importances_
rf_feat_imps = pd.Series(imps, index=X_train.columns).sort_values(ascending=False)
rf_feat_imps.plot(kind='bar')
plt.xlabel('features')
plt.ylabel('importance')
plt.title('Best random forest regressor feature importances');

## 4.7 Train/Test Split<a id='4.7_Train/Test_Split'></a>

So far, you've treated ski resort data as a single entity. In machine learning, when you train your model on all of your data, you end up with no data set aside to evaluate model performance. You could keep making more and more complex models that fit the data better and better and not realise you were overfitting to that one set of samples. By partitioning the data into training and testing splits, without letting a model (or missing-value imputation) learn anything about the test split, you have a somewhat independent assessment of how your model might perform in the future. An often overlooked subtlety here is that people all too frequently use the test set to assess model performance _and then compare multiple models to pick the best_. This means their overall model selection process is  fitting to one specific data set, now the test split. You could keep going, trying to get better and better performance on that one data set, but that's  where cross-validation becomes especially useful. While training models, a test split is very useful as a final check on expected future performance.

What partition sizes would you have with a 70/30 train/test split?

In [ ]:
len(df) * .7, len(df) * .3

In [31]:
p(df)

(7450, 122)

,game_id,game_date,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_year,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,season_type,season,book_name,book_id,total1,total2,price1,price2,lc_sum_MIN_away,lc_sum_E_OFF_RATING_away,lc_sum_OFF_RATING_away,lc_sum_E_DEF_RATING_away,lc_sum_DEF_RATING_away,lc_sum_E_NET_RATING_away,lc_sum_NET_RATING_away,lc_sum_AST_PCT_away,lc_sum_AST_TOV_away,lc_sum_AST_RATIO_away,lc_sum_OREB_PCT_away,lc_sum_DREB_PCT_away,lc_sum_REB_PCT_away,lc_sum_TM_TOV_PCT_away,lc_sum_EFG_PCT_away,lc_sum_TS_PCT_away,lc_sum_USG_PCT_away,lc_sum_E_USG_PCT_away,lc_sum_E_PACE_away,lc_sum_PACE_away,lc_sum_PACE_PER40_away,lc_sum_POSS_away,lc_sum_PIE_away,lc_mean_MIN_away,lc_mean_E_OFF_RATING_away,lc_mean_OFF_RATING_away,lc_mean_E_DEF_RATING_away,lc_mean_DEF_RATING_away,lc_mean_E_NET_RATING_away,lc_mean_NET_RATING_away,lc_mean_AST_PCT_away,lc_mean_AST_TOV_away,lc_mean_AST_RATIO_away,lc_mean_OREB_PCT_away,lc_mean_DREB_PCT_away,lc_mean_REB_PCT_away,lc_mean_TM_TOV_PCT_away,lc_mean_EFG_PCT_away,lc_mean_TS_PCT_away,lc_mean_USG_PCT_away,lc_mean_E_USG_PCT_away,lc_mean_E_PACE_away,lc_mean_PACE_away,lc_mean_PACE_PER40_away,lc_mean_POSS_away,lc_mean_PIE_away,lc_max_MIN_away,lc_max_E_OFF_RATING_away,lc_max_OFF_RATING_away,lc_max_E_DEF_RATING_away,lc_max_DEF_RATING_away,lc_max_E_NET_RATING_away,lc_max_NET_RATING_away,lc_max_AST_PCT_away,lc_max_AST_TOV_away,lc_max_AST_RATIO_away,lc_max_OREB_PCT_away,lc_max_DREB_PCT_away,lc_max_REB_PCT_away,lc_max_TM_TOV_PCT_away,lc_max_EFG_PCT_away,lc_max_TS_PCT_away,lc_max_USG_PCT_away,lc_max_E_USG_PCT_away,lc_max_E_PACE_away,lc_max_PACE_away,lc_max_PACE_PER40_away,lc_max_POSS_away,lc_max_PIE_away
0,21000044,2010-11-01,1610612741,0.667,240,43.0,71.0,0.606,5.0,13.0,0.385,19.0,32.0,1.0,9.0,27.0,36,27.0,4.0,4.0,15.0,33.0,110,2010.0,1610612757,0.750,240,33.0,80.0,0.413,0.0,14.0,0.000,32.0,41.0,1.0,16.0,19.0,35,15.0,9.0,2.0,10.0,27.0,98,Regular Season,2010-11,Pinnacle Sports,238,187.0,187.0,-105.0,-105.0,50.458291,316.665128,317.949634,318.083077,310.663040,-1.416447,7.270403,0.328857,0.781418,32.385897,0.282006,0.520890,0.405909,52.022308,1.391468,1.519216,0.543589,0.581734,276.853861,281.646315,234.705436,94.308425,0.309566,16.819430,105.555043,105.983211,106.027692,103.554347,-0.472149,2.423468,0.109619,0.260473,10.795299,0.094002,0.173630,0.135303,17.340769,0.463823,0.506405,0.181196,0.193911,92.284620,93.882105,78.235145,31.436142,0.103189,23.894444,110.733333,111.938095,119.023077,111.869231,9.323810,10.638095,0.250000,0.498571,21.569231,0.134857,0.259033,0.196714,26.896667,0.587286,0.619190,0.243385,0.277077,98.715385,103.763077,86.470769,43.190476,0.161143
1,21000045,2010-11-01,1610612758,0.750,240,42.0,88.0,0.477,5.0,12.0,0.417,22.0,27.0,1.0,16.0,24.0,40,15.0,5.0,4.0,11.0,24.0,111,2010.0,1610612761,0.333,240,39.0,85.0,0.459,9.0,21.0,0.429,21.0,29.0,1.0,17.0,25.0,42,19.0,3.0,3.0,14.0,26.0,108,Regular Season,2010-11,Pinnacle Sports,238,208.0,208.0,100.0,-110.0,14.468889,254.300000,242.613333,281.546667,281.566667,-27.240000,-38.946667,0.509600,0.033333,102.286667,0.109467,0.605600,0.382200,118.220000,0.273333,0.299267,0.204800,0.223733,363.560000,379.422000,316.186667,35.400000,0.309933,4.822963,84.766667,80.871111,93.848889,93.855556,-9.080000,-12.982222,0.169867,0.011111,34.095556,0.036489,0.201867,0.127400,39.406667,0.091111,0.099756,0.068267,0.074578,121.186667,126.474000,105.395556,11.800000,0.103311,7.118889,104.000000,100.813333,109.100000,109.100000,0.900000,-4.946667,0.500000,0.033333,100.000000,0.109467,0.333000,0.200000,100.000000,0.273333,0.299267,0.121800,0.131733,139.170000,147.890000,123.240000,14.400000,0.333000
2,21000046,2010-11-01,1610612746,0.000,240,38.0,82.0,0.463,4.0,13.0,0.308,8.0,16.0,0.0,10.0,30.0,40,26.0,10.0,6.0,17.0,18.0,88,2010.0,1610612759,0.667,240,38.0,79.0,0.481,9.0,21.0,0.429,12.0,15.0,1.0,7.0,32.0,39,28.0,11.0,3.0,18.0,21.0,97,Regular Season,2010-11,Pinnacle Sports,238,193.5,193.5,-102.0,-108.0,30.466667,218.127273,211.145455,202.936364,201.400000,15.072727,9.754545,0.241455,0.363636,46.072727,0.080182,0.208091,0.150545,8.781818,0.902273,0.910636,0.316727,0.326818,189.123636,192.874545,160.727273,60.363636,0.183909,15.233333,109.063636,105.572727,101.468182,100.700000,7.536364,4.877273,0.120727,0.181818,23.036364,0.040091,0.104045,0.075273,4.390909,0.451136,0.455318,0.158364,0.163409,94.561818,96.437273,80.363636,30.181818,0.091955,16.516667,112.200000,106.900000,102.000000,101.400000,10.100000,6.900000,0.182000,0.363636,40.000000,0.080182,0.141091,0.107545,8.781818,0.569273,0.577636,0.216727,0.221818,98.130000,101.510000,84.590000,31.363636,0.124909
3,21000047,2010-11-02,1610612739,0.250,240,32.0,74.0,0.432,5.0,17.0,0.294,19.0,26.0,1.0,10.0,34.0,44,15.0,2.0,4.0,14.0,22.0,88,2010.0,1610612737,1.000,240,37.0,84.0,0.440,5.0,17.0,0.294,21.0,30.0,1.0,14.0,29.0,43,26.0,7.0,7.0,7.0,17.0,100,Regular Season,2010-11,Pinnacle Sports,238,190.0,190.0,101.0,-111.0,30.194667,208.824000,211.900000,277.060000,271.156000,-68.232000,-59.248000,0.005000,0.020000,0.500000,0.058320,1.118760,0.291280,19.672000,1.641880,1.663240,0.451880,0.505040,283.410400,297.389200,247.825200,60.680000,0.096600,10.064889,69.608000,70.633333,92.353333,90.385333,-22.744000,-19.749333,0.001667,0.006667,0.166667,0.019440,0.372920,0.097093,6.557333,0.547293,0.554413,0.150627,0.168347,94.470133,99.129733,82.608400,20.226667,0.032200,14.583333,113.800000,116.700000,107.860000,109.056000,24.400000,29.600000,0.005000,0.020000,0.500000,0.058320,1.000000,0.200000,19.672000,1.167000,1.167000,0.200000,0.250000,100.320000,103.680000,86.400000,30.000000,0.075000
4,21000048,2010-11-02,1610612764,0.333,265,37.0,78.0,0.474,6.0,12.0,0.500,36.0,43.0,1.0,9.0,27.0,36,24.0,15.0,2.0,21.0,24.0,116,2010.0,1610612755,0.000,265,44.0,80.0,0.550,4.0,15.0,0.267,23.0,29.0,1.0,7.0,28.0,35,34.0,10.0,3.0,22.0,30.0,115,Regular Season,2010-11,Pinnacle Sports,238,192.0,192.0,-105.0,-105.0,16.963611,194.003333,200.586667,234.478333,236.576667,-40.475000,-35.986667,0.060983,0.255500,8.905000,0.007233,0.136633,0.071917,6.331667,0.340617,0.364883,0.194217,0.200567,215.120333,214.633167,178.860000,35.466667,0.003667,8.481806,97.001667,100.293333,117.239167,118.288333,-20.237500,-17.993333,0.030492,0.127750,4.452500,0.003617,0.068317,0.035958,3.165833,0.170308,0.182442,0.097108,0.100283,107.560167,107.316583,89.430000,17.733333,0.001833,11.980278,101.403333,100.586667,138.900000,145.500000,5.825000,9.513333,0.060983,0.255500,8.905000,0.007233,0.136633,0.071917,6.331667,0.340617,0.364883,0.194217,0.200567,112.700000,108.683167,90.570000,24.466667,0.050667
7445,41500403,2016-06-08,1610612739,0.333,240,48.0,91.0,0.527,12.0,25.0,0.480,12.0,17.0,1.0,17.0,35.0,52,23.0,8.0,3.0,13.0,25.0,120,2015.0,1610612744,0.667,240,32.0,76.0,0.421,9.0,33.0,0.273,17.0,26.0,1.0,8.0,24.0,32,21.0,5.0,4.0,18.0,23.0,90,Playoffs,2015-16,Pinnacle Sports,238,206.5,206.5,-103.0,-107.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
7446,41500404,2016-06-10,1610612739,0.250,240,38.0,81.0,0.469,6.0,25.0,0.240,15.0,26.0,1.0,16.0,24.0,40,15.0,5.0,6.0,11.0,24.0,97,2015.0,1610612744,0.750,240,33.0,81.0,0.407,17.0,36.0,0.472,25.0,31.0,1.0,14.0,29.0,43,23.0,7.0,6.0,8.0,22.0,108,Playoffs,2015-16,Pinnacle Sports,238,207.5,207.5,-105.0,-105.0,23.771521,211.327160,203.375884,217.791498,214.610887,-6.456832,-11.234259,0.293903,0.937792,33.370833,0.049290,0.187325,0.116477,24.145398,0.905547,0.975911,0.367691,0.384118,198.296787,203.010352,169.175254,49.943743,0.136105,11.885760,105.663580,101.687942,108.895749,107.305443,-3.228416,-5.617130,0.146952,0.468896,16.685417,0.024645,0.093663,0.058239,12.072699,0.452773,0.487956,0.183846,0.192059,99.148394,101.505176,84.587627,24.971871,0.068053,14.779545,107.327160,103.064773,114.607407,112.065432,0.814773,0.525000,0.188210,0.479383,19.833333,0.030216,0.112086,0.065000,15.113580,0.491386,0.539739,0.187691,0.198765,100.474318,101.827284,84.856049,31.079545,0.073068
7447,41500405,2016-06-13,1610612744,0.600,240,32.0,88.0,0.364,14.0,43.0,0.326,19.0,26.0,1.0,13.0,30.0,43,18.0,6.0,9.0,17.0,21.0,97,2015.0,1610612739,0.400,240,44.0,83.0,0.530,10.0,24.0,0.417,14.0,23.0,1.0,8.0,33.0,41,15.0,11.0,9.0,16.0,22.0,112,Playoffs,2015-16,Pinnacle Sports,238,209.0,209.0,-103.0,-107.0,16.513793,105.905747,106.129885,102.180460,101.628736,3.725287,4.500000,0.068851,0.298851,11.437931,0.027885,0.176356,0.099287,8.465517,0.523943,0.545609,0.153425,0.156897,94.277241,94.480000,78.732299,32.333333,0.084943,16.513793,105.905747,106.129885,102.180460,101.628736,3.725287,4.500000,0.068851,0.298851,11.437931,0.027885,0.176356,0.099287,8.465517,0.523943,0.545609,0.153425,0.156897,94.277241,94.480000,78.732299,32.333333,0.084943,16.513793,105.905747,106.129885,102.180460,101.628736,3.725287,4.500000,0.068851,0.298851,11.437931,0.027885,0.176356,0.099287,8.465517,0.523943,0.545609,0.153425,0.156897,94.277241,94.480000,78.732299,32.333333,0.084943
7448,41500406,2016-06-16,1610612739,0.500,240,40.0,77.0,0.519,10.0,27.0,0.370,25.0,32.0,1.0,8.0,37.0,45,24.0,12.0,7.0,10.0,25.0,115,2015.0,1610612744,0.500,240,33.0,82.0,0.402,15.0,39.0,0.385,20.0,29.0,1.0,9.0,26.0,35,19.0,5.0,3.0,14.0,25.0,101,Playoffs,2015-16,Pinnacle Sports,238,207.5,207.5,-104.0,-106.0,19.746014,110.730435,110.559783,97.881522,99.747826,12.847826,10.811957,0.143902,0.946413,29.347826,0.092815,0.216750,0.159707,15.857609,0.588707,0.591272,0.117511,0.119185,100.577717,99.806304,83.172174,40.847826,0.104424,19.746014,110.730435,110.559783,97.881522,99.747826,12.847826,10.811957,0.143902,0.946413,29.347826,0.092815,0.216750,0.159707,15.857609,0.588707,0.591272,0.117511,0.119185,100.577717,99.806304,83.172174,40.847826,0.104424,19.746014,110.730435,110.559783,97.881522,99.747826,12.847826,10.811957,0.143902,0.946413,29.347826,0.092815,0.216750,0.159707,15.857609,0.588707,0.591272,0.117511,0.119185,100.577717,99.806304,83.172174,40.847826,0.104424
7449,41500407,2016-06-19,1610612744,0.429,240,32.0,83.0,0.386,15.0,41.0,0.366,10.0,13.0,1.0,7.0,32.0,39,22.0,7.0,5.0,10.0,23.0,89,2015.0,1610612739,0.571,240,33.0,82.0,0.402,6.0,25.0,0.240,21.0,25.0,1.0,9.0,39.0,48,17.0,7.0,6.0,11.0,15.0,93,Playoffs,2015-16,Pinnacle Sports,238,205.0,205.0,-106.0,-104.0,68.681735,488.346069,471.775529,493.645706,478.357883,-5.308709,-6.577348,0.478451,2.611434,58.469711,0.137016,0.569201,0.349494,40.582525,2.171163,2.294264,0.725604,0.778065,460.573147,490.210795,408.505172,135.967235,0.414359,13.736347,97.669214,94.355106,98.729141,95.671577,-1.061742,-1.315470,0.095690,0.522287,11.693942,0.027403,0.113840,0.069899,8.116505,0.434233,0.458853,0.145121,0.155613,92.114629,98.042159,81.701034,27.193447,0.082872,21.963542,107.636458,107.391667,105.982955,104.864773,7.351042,7.808333,0.299979,1.910417,33.256250,0.081045,0.176356,0.126557,14.509091,0.523943,0.545609,0.170635,0.175979,95.671364,102.968125,85.805625,43.468750,0.108375

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns='AdultWeekend'), 
                                                    df.AdultWeekend, test_size=0.3, 
                                                    random_state=47)

<font color='red'> what colomns to keep and what columns to drop???</font>

In [ ]:
X_train.shape, X_test.shape

In [ ]:
y_train.shape, y_test.shape

In [ ]:
#Code task 1#
#Save the 'Name', 'state', and 'Region' columns from the train/test data into names_train and names_test
#Then drop those columns from `X_train` and `X_test`. Use 'inplace=True'
names_list = ['Name', 'state', 'Region']
names_train = X_train[names_list]
names_test = X_test[names_list]
X_train.drop(columns=names_list, inplace=True)
X_test.drop(columns=names_list, inplace=True)
X_train.shape, X_test.shape

In [ ]:
#Code task 2#
#Check the `dtypes` attribute of `X_train` to verify all features are numeric
X_train.dtypes

In [ ]:
#Code task 3#
#Repeat this check for the test split in `X_test`
X_test.dtypes

In [ ]:
#y_train.describe()

You have only numeric features in your X now!

## 4.8 Initial Not-Even-A-Model<a id='4.8_Initial_Not-Even-A-Model'></a>

A good place to start is to see how good the mean is as a predictor. In other words, what if you simply say your best guess is the average price?

In [ ]:
#Code task 4#
#Calculate the mean of `y_train`
train_mean = y_train.mean()
train_mean

`sklearn`'s `DummyRegressor` easily does this:

In [ ]:
#Code task 5#
#Fit the dummy regressor on the training data
#Hint, call its `.fit()` method with `X_train` and `y_train` as arguments
#Then print the object's `constant_` attribute and verify it's the same as the mean above
dumb_reg = DummyRegressor(strategy='mean')
dumb_reg.fit(X_train, y_train)
dumb_reg.constant_

How good is this? How closely does this match, or explain, the actual values? There are many ways of assessing how good one set of values agrees with another, which brings us to the subject of metrics.

<font color='red'>???????????<font >

### 4.8.1 Metrics<a id='4.8.1_Metrics'></a>

#### 4.8.1.1 R-squared, or coefficient of determination<a id='4.8.1.1_R-squared,_or_coefficient_of_determination'></a>

One measure is $R^2$, the [coefficient of determination](https://en.wikipedia.org/wiki/Coefficient_of_determination). This is a measure of the proportion of variance in the dependent variable (our ticket price) that is predicted by our "model". The linked Wikipedia articles gives a nice explanation of how negative values can arise. This is frequently a cause of confusion for newcomers who, reasonably, ask how can a squared value be negative?

Recall the mean can be denoted by $\bar{y}$, where

$$\bar{y} = \frac{1}{n}\sum_{i=1}^ny_i$$

and where $y_i$ are the individual values of the dependent variable.

The total sum of squares (error), can be expressed as

$$SS_{tot} = \sum_i(y_i-\bar{y})^2$$

The above formula should be familiar as it's simply the variance without the denominator to scale (divide) by the sample size.

The residual sum of squares is similarly defined to be

$$SS_{res} = \sum_i(y_i-\hat{y})^2$$

where $\hat{y}$ are our predicted values for the depended variable.

The coefficient of determination, $R^2$, here is given by

$$R^2 = 1 - \frac{SS_{res}}{SS_{tot}}$$

Putting it into words, it's one minus the ratio of the residual variance to the original variance. Thus, the baseline model here, which always predicts $\bar{y}$, should give $R^2=0$. A model that perfectly predicts the observed values would have no residual error and so give $R^2=1$. Models that do worse than predicting the mean will have increased the sum of squares of residuals and so produce a negative $R^2$.

In [ ]:
#Code task 6#
#Calculate the R^2 as defined above
def r_squared(y, ypred):
    """R-squared score.
    
    Calculate the R-squared, or coefficient of determination, of the input.
    
    Arguments:
    y -- the observed values
    ypred -- the predicted values
    """
    ybar = np.sum(y) / len(y) #yes, we could use np.mean(y)
    sum_sq_tot = np.sum((y - ybar)**2) #total sum of squares error
    sum_sq_res = np.sum((y - ypred)**2) #residual sum of squares error
    R2 = 1.0 - sum_sq_res / sum_sq_tot
    return R2

Make your predictions by creating an array of length the size of the training set with the single value of the mean.

In [ ]:
y_tr_pred_ = train_mean * np.ones(len(y_train))
y_tr_pred_[:5]

Remember the `sklearn` dummy regressor?

In [ ]:
y_tr_pred = dumb_reg.predict(X_train)
y_tr_pred[:5]

You can see that `DummyRegressor` produces exactly the same results and saves you having to mess about broadcasting the mean (or whichever other statistic we used - check out the [documentation](https://scikit-learn.org/stable/modules/generated/sklearn.dummy.DummyRegressor.html) to see what's available) to an array of the appropriate length. It also gives you an object with `fit()` and `predict()` methods as well so you can use them as conveniently as any other `sklearn` estimator.

In [ ]:
r_squared(y_train, y_tr_pred)

Exactly as expected, if you use the average value as your prediction, you get an $R^2$ of zero _on our training set_. What if you use this "model" to predict unseen values from the test set? Remember, of course, that your "model" is trained on the training set; you still use the training set mean as your prediction.

Make your predictions by creating an array of length the size of the test set with the single value of the (training) mean.

In [ ]:
y_te_pred = train_mean * np.ones(len(y_test))
r_squared(y_test, y_te_pred)

Generally, you can expect performance on a test set to be slightly worse than on the training set. As you are getting an $R^2$ of zero on the training set, there's nowhere to go but negative!

$R^2$ is a common metric, and interpretable in terms of the amount of variance explained, it's less appealing if you want an idea of how "close" your predictions are to the true values. Metrics that summarise the difference between predicted and actual values are _mean absolute error_ and _mean squared error_.

#### 4.8.1.2 Mean Absolute Error<a id='4.7.1.2_Mean_Absolute_Error'></a>

This is very simply the average of the absolute errors:

$$MAE = \frac{1}{n}\sum_i^n|y_i - \hat{y}|$$

In [ ]:
#Code task 7#
#Calculate the MAE as defined above
def mae(y, ypred):
    """Mean absolute error.
    
    Calculate the mean absolute error of the arguments

    Arguments:
    y -- the observed values
    ypred -- the predicted values
    """
    abs_error = np.abs(y - ypred)
    mae = np.mean(abs_error)
    return mae

In [ ]:
mae(y_train, y_tr_pred)

In [ ]:
mae(y_test, y_te_pred)

Mean absolute error is arguably the most intuitive of all the metrics, this essentially tells you that, on average, you might expect to be off by around \\$19 if you guessed ticket price based on an average of known values.

#### 4.8.1.3 Mean Squared Error<a id='4.8.1.3_Mean_Squared_Error'></a>

Another common metric (and an important one internally for optimizing machine learning models) is the mean squared error. This is simply the average of the square of the errors:

$$MSE = \frac{1}{n}\sum_i^n(y_i - \hat{y})^2$$

In [ ]:
#Code task 8#
#Calculate the MSE as defined above
def mse(y, ypred):
    """Mean square error.
    
    Calculate the mean square error of the arguments

    Arguments:
    y -- the observed values
    ypred -- the predicted values
    """
    sq_error = (y - ypred)**2
    mse = np.mean(sq_error)
    return mse

In [ ]:
mse(y_train, y_tr_pred)

In [ ]:
mse(y_test, y_te_pred)

So here, you get a slightly better MSE on the test set than you did on the train set. And what does a squared error mean anyway? To convert this back to our measurement space, we often take the square root, to form the _root mean square error_ thus:

In [ ]:
np.sqrt([mse(y_train, y_tr_pred), mse(y_test, y_te_pred)])

### 4.8.2 sklearn metrics<a id='4.7.2_sklearn_metrics'></a>

Functions are good, but you don't want to have to define functions every time we want to assess performance. `sklearn.metrics` provides many commonly used metrics, included the ones above.

##### 4.8.2.0.1 R-squared<a id='4.7.2.0.1_R-squared'></a>

In [ ]:
r2_score(y_train, y_tr_pred), r2_score(y_test, y_te_pred)

##### 4.8.2.0.2 Mean absolute error<a id='4.7.2.0.2_Mean_absolute_error'></a>

In [ ]:
mean_absolute_error(y_train, y_tr_pred), mean_absolute_error(y_test, y_te_pred)

##### 4.8.2.0.3 Mean squared error<a id='4.7.2.0.3_Mean_squared_error'></a>

In [ ]:
mean_squared_error(y_train, y_tr_pred), mean_squared_error(y_test, y_te_pred)

### 4.8.3 Note On Calculating Metrics<a id='4.7.3_Note_On_Calculating_Metrics'></a>

When calling functions to calculate metrics, it is important to take care in the order of the arguments. Two of the metrics above actually don't care if the arguments are reversed; one does. Which one cares?

In a Jupyter code cell, running `r2_score?` will bring up the docstring for the function, and `r2_score??` will bring up the actual code of the function! Try them and compare the source for `sklearn`'s function with yours. Feel free to explore what happens when you reverse the order of the arguments and compare behaviour of `sklearn`'s function and yours.

In [ ]:
applesauce = np.array([8, 2, 3, 5])
applesauce

In [ ]:
applesauce.shape

In [ ]:
applesauce.ndim

In [ ]:
applesauce = applesauce.reshape(-1, 1)
applesauce

In [ ]:
applesauce.ndim

In [ ]:
applesauce.shape[1]

In [ ]:
r2_score?

In [ ]:
r2_score??

In [ ]:
y_tr_pred

In [ ]:
y_train

In [ ]:
# train set - sklearn
# correct order, incorrect order
r2_score(y_train, y_tr_pred), r2_score(y_tr_pred, y_train)

In [ ]:
# test set - sklearn
# correct order, incorrect order
r2_score(y_test, y_te_pred), r2_score(y_te_pred, y_test)

In [ ]:
# train set - using our homebrew function
# correct order, incorrect order
r_squared(y_train, y_tr_pred), r_squared(y_tr_pred, y_train)

In [ ]:
# test set - using our homebrew function
# correct order, incorrect order
r_squared(y_test, y_te_pred), r_squared(y_te_pred, y_test)

You can get very different results swapping the argument order. It's worth highlighting this because data scientists do this too much in the real world! Don't be one of them! Frequently the argument order doesn't matter, but it will bite you when you do it with a function that does care. It's sloppy, bad practice and if you don't make a habit of putting arguments in the right order, you will forget!

Remember:
* argument order matters,
* check function syntax with `func?` in a code cell

## 4.9 Initial Models<a id='4.9_Initial_Models'></a>

### 4.9.1 Imputing missing feature (predictor) values<a id='4.9.1_Imputing_missing_feature_(predictor)_values'></a>

Recall when performing EDA, you imputed (filled in) some missing values in pandas. You did this judiciously for exploratory/visualization purposes. You left many missing values in the data. You can impute missing values using scikit-learn, but note that you should learn values to impute from a train split and apply that to the test split to then assess how well your imputation worked.

#### 4.9.1.1 Impute missing values with median<a id='4.9.1.1_Impute_missing_values_with_median'></a>

There's missing values. Recall from your data exploration that many distributions were skewed. Your first thought might be to impute missing values using the median.

##### 4.9.1.1.1 Learn the values to impute from the train set<a id='4.9.1.1.1_Learn_the_values_to_impute_from_the_train_set'></a>

In [ ]:
# These are the values we'll use to fill in any missing values
X_defaults_median = X_train.median()
X_defaults_median

##### 4.9.1.1.2 Apply the imputation to both train and test splits<a id='4.9.1.1.2_Apply_the_imputation_to_both_train_and_test_splits'></a>

In [ ]:
#Code task 9#
#Call `X_train` and `X_test`'s `fillna()` method, passing `X_defaults_median` as the values to use
#Assign the results to `X_tr` and `X_te`, respectively
X_tr = X_train.fillna(X_defaults_median)
X_te = X_test.fillna(X_defaults_median)

##### 4.9.1.1.3 Scale the data<a id='4.9.1.1.3_Scale_the_data'></a>

As you have features measured in many different units, with numbers that vary by orders of magnitude, start off by scaling them to put them all on a consistent scale. The [StandardScaler](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html) scales each feature to zero mean and unit variance.

In [ ]:
#Code task 10#
#Call the StandardScaler`s fit method on `X_tr` to fit the scaler
#then use it's `transform()` method to apply the scaling to both the train and test split
#data (`X_tr` and `X_te`), naming the results `X_tr_scaled` and `X_te_scaled`, respectively
scaler = StandardScaler()
scaler.fit(X_tr)
X_tr_scaled = scaler.transform(X_tr)
X_te_scaled = scaler.transform(X_te)

In [ ]:
X_tr_scaled

##### 4.9.1.1.4 Train the model on the train split<a id='4.9.1.1.4_Train_the_model_on_the_train_split'></a>

In [ ]:
lm = LinearRegression().fit(X_tr_scaled, y_train)

##### 4.9.1.1.5 Make predictions using the model on both train and test splits<a id='4.9.1.1.5_Make_predictions_using_the_model_on_both_train_and_test_splits'></a>

In [ ]:
#Code task 11#
#Call the `predict()` method of the model (`lm`) on both the (scaled) train and test data
#Assign the predictions to `y_tr_pred` and `y_te_pred`, respectively
y_tr_pred = lm.predict(X_tr_scaled)
y_te_pred = lm.predict(X_te_scaled)

##### 4.9.1.1.6 Assess model performance<a id='4.9.1.1.6_Assess_model_performance'></a>

In [ ]:
# r^2 - train, test
median_r2 = r2_score(y_train, y_tr_pred), r2_score(y_test, y_te_pred)
median_r2

Recall that you estimated ticket price by simply using a known average. As expected, this produced an $R^2$ of zero for both the training and test set, because $R^2$ tells us how much of the variance you're explaining beyond that of using just the mean, and you were using just the mean. Here we see that our simple linear regression model explains over 80% of the variance on the train set and over 70% on the test set. Clearly you are onto something, although the much lower value for the test set suggests you're overfitting somewhat. This isn't a surprise as you've made no effort to select a parsimonious set of features or deal with multicollinearity in our data.

In [ ]:
#Code task 12#
#Now calculate the mean absolute error scores using `sklearn`'s `mean_absolute_error` function
# as we did above for R^2
# MAE - train, test
median_mae = mean_absolute_error(y_train, y_tr_pred), mean_absolute_error(y_test, y_te_pred)
median_mae

Using this model, then, on average you'd expect to estimate a ticket price within \\$9 or so of the real price. This is much, much better than the \\$19 from just guessing using the average. There may be something to this machine learning lark after all!

In [ ]:
#Code task 13#
#And also do the same using `sklearn`'s `mean_squared_error`
# MSE - train, test
median_mse = mean_squared_error(y_train, y_tr_pred), mean_squared_error(y_test, y_te_pred)
median_mse

#### 4.9.1.2 Impute missing values with the mean<a id='4.9.1.2_Impute_missing_values_with_the_mean'></a>

You chose to use the median for filling missing values because of the skew of many of our predictor feature distributions. What if you wanted to try something else, such as the mean?

##### 4.9.1.2.1 Learn the values to impute from the train set<a id='4.9.1.2.1_Learn_the_values_to_impute_from_the_train_set'></a>

In [ ]:
#Code task 14#
#As we did for the median above, calculate mean values for imputing missing values
# These are the values we'll use to fill in any missing values
X_defaults_mean = X_train.mean()
X_defaults_mean

By eye, you can immediately tell that your replacement values are much higher than those from using the median.

##### 4.9.1.2.2 Apply the imputation to both train and test splits<a id='4.9.1.2.2_Apply_the_imputation_to_both_train_and_test_splits'></a>

In [ ]:
X_tr = X_train.fillna(X_defaults_mean)
X_te = X_test.fillna(X_defaults_mean)

##### 4.9.1.2.3 Scale the data<a id='4.9.1.2.3_Scale_the_data'></a>

In [ ]:
scaler = StandardScaler()
scaler.fit(X_tr)
X_tr_scaled = scaler.transform(X_tr)
X_te_scaled = scaler.transform(X_te)

##### 4.9.1.2.4 Train the model on the train split<a id='4.9.1.2.4_Train_the_model_on_the_train_split'></a>

In [ ]:
lm = LinearRegression().fit(X_tr_scaled, y_train)

##### 4.9.1.2.5 Make predictions using the model on both train and test splits<a id='4.9.1.2.5_Make_predictions_using_the_model_on_both_train_and_test_splits'></a>

In [ ]:
y_tr_pred = lm.predict(X_tr_scaled)
y_te_pred = lm.predict(X_te_scaled)

##### 4.9.1.2.6 Assess model performance<a id='4.9.1.2.6_Assess_model_performance'></a>

In [ ]:
r2_score(y_train, y_tr_pred), r2_score(y_test, y_te_pred)

In [ ]:
mean_absolute_error(y_train, y_tr_pred), mean_absolute_error(y_test, y_te_pred)

In [ ]:
mean_squared_error(y_train, y_tr_pred), mean_squared_error(y_test, y_te_pred)

These results don't seem very different to when you used the median for imputing missing values. Perhaps it doesn't make much difference here. Maybe your overtraining dominates. Maybe other feature transformations, such as taking the log, would help. You could try with just a subset of features rather than using all of them as inputs.

To perform the median/mean comparison, you copied and pasted a lot of code just to change the function for imputing missing values. It would make more sense to write a function that performed the sequence of steps:
1. impute missing values
2. scale the features
3. train a model
4. calculate model performance

But these are common steps and `sklearn` provides something much better than writing custom functions.

### 4.9.2 Pipelines<a id='4.9.2_Pipelines'></a>

One of the most important and useful components of `sklearn` is the [pipeline](https://scikit-learn.org/stable/modules/generated/sklearn.pipeline.Pipeline.html). In place of `panda`'s `fillna` DataFrame method, there is `sklearn`'s `SimpleImputer`. Remember the first linear model above performed the steps:

1. replace missing values with the median for each feature
2. scale the data to zero mean and unit variance
3. train a linear regression model

and all these steps were trained on the train split and then applied to the test split for assessment.

The pipeline below defines exactly those same steps. Crucially, the resultant `Pipeline` object has a `fit()` method and a `predict()` method, just like the `LinearRegression()` object itself. Just as you might create a linear regression model and train it with `.fit()` and predict with `.predict()`, you can wrap the entire process of imputing and feature scaling and regression in a single object you can train with `.fit()` and predict with `.predict()`. And that's basically a pipeline: a model on steroids.

<font color='red'>"2. scale the data to zero mean and unit variance" is this just getting z scores for each feature??????????????????????<font >

#### 4.9.2.1 Define the pipeline<a id='4.9.2.1_Define_the_pipeline'></a>

In [ ]:
pipe = make_pipeline(
    SimpleImputer(strategy='median'), 
    StandardScaler(), 
    LinearRegression()
)

In [ ]:
type(pipe)

In [ ]:
hasattr(pipe, 'fit'), hasattr(pipe, 'predict')

#### 4.9.2.2 Fit the pipeline<a id='4.9.2.2_Fit_the_pipeline'></a>

Here, a single call to the pipeline's `fit()` method combines the steps of learning the imputation (determining what values to use to fill the missing ones), the scaling (determining the mean to subtract and the variance to divide by), and then training the model. It does this all in the one call with the training data as arguments.

In [ ]:
#Code task 15#
#Call the pipe's `fit()` method with `X_train` and `y_train` as arguments
pipe.fit(X_train, y_train)

#### 4.9.2.3 Make predictions on the train and test sets<a id='4.9.2.3_Make_predictions_on_the_train_and_test_sets'></a>

In [ ]:
y_tr_pred = pipe.predict(X_train)
y_te_pred = pipe.predict(X_test)

#### 4.9.2.4 Assess performance<a id='4.9.2.4_Assess_performance'></a>

In [ ]:
r2_score(y_train, y_tr_pred), r2_score(y_test, y_te_pred)

And compare with your earlier (non-pipeline) result:

In [ ]:
median_r2

In [ ]:
mean_absolute_error(y_train, y_tr_pred), mean_absolute_error(y_test, y_te_pred)

And compare with your earlier result:

In [ ]:
median_mae

In [ ]:
mean_squared_error(y_train, y_tr_pred), mean_squared_error(y_test, y_te_pred)

Compare with your earlier result:

In [ ]:
median_mse

These results confirm the pipeline is doing exactly what's expected, and results are identical to your earlier steps. This allows you to move faster but with confidence.

## 4.10 Refining The Linear Model<a id='4.10_Refining_The_Linear_Model'></a>

You suspected the model was overfitting. This is no real surprise given the number of features you blindly used. It's likely a judicious subset of features would generalize better. `sklearn` has a number of feature selection functions available. The one you'll use here is `SelectKBest` which, as you might guess, selects the k best features. You can read about SelectKBest 
[here](https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.SelectKBest.html#sklearn.feature_selection.SelectKBest). `f_regression` is just the [score function](https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.f_regression.html#sklearn.feature_selection.f_regression) you're using because you're performing regression. It's important to choose an appropriate one for your machine learning task.

### 4.10.1 Define the pipeline<a id='4.10.1_Define_the_pipeline'></a>

Redefine your pipeline to include this feature selection step:

In [ ]:
#Code task 16#
#Add `SelectKBest` as a step in the pipeline between `StandardScaler()` and `LinearRegression()`
#Don't forget to tell it to use `f_regression` as its score function
pipe = make_pipeline(
    SimpleImputer(strategy='median'), 
    StandardScaler(),
    SelectKBest(score_func=f_regression),
    LinearRegression()
)

<font color='red'>'f_regression'???????????????
f-score??????????????
p-value????????????
<font>

### 4.10.2 Fit the pipeline<a id='4.10.2_Fit_the_pipeline'></a>

In [ ]:
pipe.fit(X_train, y_train)

### 4.10.3 Assess performance on the train and test set<a id='4.10.3_Assess_performance_on_the_train_and_test_set'></a>

In [ ]:
y_tr_pred = pipe.predict(X_train)
y_te_pred = pipe.predict(X_test)

In [ ]:
r2_score(y_train, y_tr_pred), r2_score(y_test, y_te_pred)

In [ ]:
mean_absolute_error(y_train, y_tr_pred), mean_absolute_error(y_test, y_te_pred)

This has made things worse! Clearly selecting a subset of features has an impact on performance. `SelectKBest` defaults to k=10. You've just seen that 10 is worse than using all features. What is the best k? You could create a new pipeline with a different value of k:

### 4.10.4 Define a new pipeline to select a different number of features<a id='4.10.4_Define_a_new_pipeline_to_select_a_different_number_of_features'></a>

In [ ]:
#Code task 17#
#Modify the `SelectKBest` step to use a value of 15 for k
pipe15 = make_pipeline(
    SimpleImputer(strategy='median'), 
    StandardScaler(),
    SelectKBest(score_func=f_regression, k=15),
    LinearRegression()
)

### 4.10.5 Fit the pipeline<a id='4.10.5_Fit_the_pipeline'></a>

In [ ]:
pipe15.fit(X_train, y_train)

### 4.10.6 Assess performance on train and test data<a id='4.10.6_Assess_performance_on_train_and_test_data'></a>

In [ ]:
y_tr_pred = pipe15.predict(X_train)
y_te_pred = pipe15.predict(X_test)

In [ ]:
r2_score(y_train, y_tr_pred), r2_score(y_test, y_te_pred)

In [ ]:
mean_absolute_error(y_train, y_tr_pred), mean_absolute_error(y_test, y_te_pred)

You could keep going, trying different values of k, training a model, measuring performance on the test set, and then picking the model with the best test set performance. There's a fundamental problem with this approach: _you're tuning the model to the arbitrary test set_! If you continue this way you'll end up with a model works well on the particular quirks of our test set _but fails to generalize to new data_. The whole point of keeping a test set is for it to be a set of that new data, to check how well our model might perform on data it hasn't seen.

The way around this is a technique called _cross-validation_. You partition the training set into k folds, train our model on k-1 of those folds, and calculate performance on the fold not used in training. This procedure then cycles through k times with a different fold held back each time. Thus you end up building k models on k sets of data with k estimates of how the model performs on unseen data but without having to touch the test set.

### 4.10.7 Assessing performance using cross-validation<a id='4.10.7_Assessing_performance_using_cross-validation'></a>

In [ ]:
cv_results = cross_validate(pipe15, X_train, y_train, cv=5)

In [ ]:
cv_scores = cv_results['test_score']
cv_scores

<font color='red'>what is an f score????????<font >

Without using the same random state for initializing the CV folds, your actual numbers will be different.

In [ ]:
np.mean(cv_scores), np.std(cv_scores)

These results highlight that assessing model performance in inherently open to variability. You'll get different results depending on the quirks of which points are in which fold. An advantage of this is that you can also obtain an estimate of the variability, or uncertainty, in your performance estimate.

In [ ]:
np.round((np.mean(cv_scores) - 2 * np.std(cv_scores), np.mean(cv_scores) + 2 * np.std(cv_scores)), 2)

<font color='red'>XXXXXXXXXXXwhat are these calculations based on???????????????????????</font>

### 4.10.8 Hyperparameter search using GridSearchCV<a id='4.10.8_Hyperparameter_search_using_GridSearchCV'></a>

Pulling the above together, we have:
* a pipeline that
    * imputes missing values
    * scales the data
    * selects the k best features
    * trains a linear regression model
* a technique (cross-validation) for estimating model performance

Now you want to use cross-validation for multiple values of k and use cross-validation to pick the value of k that gives the best performance. `make_pipeline` automatically names each step as the lowercase name of the step and the parameters of the step are then accessed by appending a double underscore followed by the parameter name. You know the name of the step will be 'selectkbest' and you know the parameter is 'k'.

You can also list the names of all the parameters in a pipeline like this:

In [ ]:
#Code task 18#
#Call `pipe`'s `get_params()` method to get a dict of available parameters and print their names
#using dict's `keys()` method
pipe.get_params().keys()

The above can be particularly useful as your pipelines becomes more complex (you can even nest pipelines within pipelines).

In [ ]:
k = [k+1 for k in range(len(X_train.columns))]
grid_params = {'selectkbest__k': k}
grid_params

Now you have a range of `k` to investigate. Is 1 feature best? 2? 3? 4? All of them? You could write a for loop and iterate over each possible value, doing all the housekeeping oyurselves to track the best value of k. But this is  a common task so there's a built in function in `sklearn`. This is [`GridSearchCV`](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html).
This takes the pipeline object, in fact it takes anything with a `.fit()` and `.predict()` method. In simple cases with no feature selection or imputation or feature scaling etc. you may see the classifier or regressor object itself directly passed into `GridSearchCV`. The other key input is the parameters and values to search over. Optional parameters include the cross-validation strategy and number of CPUs to use.

In [ ]:
lr_grid_cv = GridSearchCV(pipe, param_grid=grid_params, cv=5, n_jobs=-1)

In [ ]:
lr_grid_cv.fit(X_train, y_train)

In [ ]:
score_mean = lr_grid_cv.cv_results_['mean_test_score']
score_std = lr_grid_cv.cv_results_['std_test_score']
cv_k = [k for k in lr_grid_cv.cv_results_['param_selectkbest__k']]

In [ ]:
#Code task 19#
#Print the `best_params_` attribute of `lr_grid_cv`
lr_grid_cv.best_params_

In [ ]:
#Code task 20#
#Assign the value of k from the above dict of `best_params_` and assign it to `best_k`
best_k = lr_grid_cv.best_params_['selectkbest__k']
plt.subplots(figsize=(10, 5))
plt.errorbar(cv_k, score_mean, yerr=score_std)
plt.axvline(x=best_k, c='r', ls='--', alpha=.5)
plt.xlabel('k')
plt.ylabel('CV score (r-squared)')
plt.title('Pipeline mean CV score (error bars +/- 1sd)');

The above suggests a good value for k is 8. There was an initial rapid increase with k, followed by a slow decline. Also noticeable is the variance of the results greatly increase above k=8. As you increasingly overfit, expect greater swings in performance as different points move in and out of the train/test folds.

Which features were most useful? Step into your best model, shown below. Starting with the fitted grid search object, you get the best estimator, then the named step 'selectkbest', for which you can its `get_support()` method for a logical mask of the features selected.

In [ ]:
selected = lr_grid_cv.best_estimator_.named_steps.selectkbest.get_support()
selected

Similarly, instead of using the 'selectkbest' named step, you can access the named step for the linear regression model and, from that, grab the model coefficients via its `coef_` attribute:

In [ ]:
#Code task 21#
#Get the linear model coefficients from the `coef_` attribute and store in `coefs`,
#get the matching feature names from the column names of the dataframe,
#and display the results as a pandas Series with `coefs` as the values and `features` as the index,
#sorting the values in descending order
coefs = lr_grid_cv.best_estimator_.named_steps.linearregression.coef_
features = X_train.columns[selected]
pd.Series(coefs, index=features).sort_values(ascending=False)

These results suggest that vertical drop is your biggest positive feature. This makes intuitive sense and is consistent with what you saw during the EDA work. Also, you see the area covered by snow making equipment is a strong positive as well. People like guaranteed skiing! The skiable terrain area is negatively associated with ticket price! This seems odd. People will pay less for larger resorts? There could be all manner of reasons for this. It could be  an effect whereby larger resorts can host more visitors at any one time and so can charge less per ticket. As has been mentioned previously, the data are missing information about visitor numbers. Bear in mind,  the coefficient for skiable terrain is negative _for this model_. For example, if you kept the total number of chairs and fastQuads constant, but increased the skiable terrain extent, you might imagine the resort is worse off because the chairlift capacity is stretched thinner.

<font color='red'>"As has been mentioned previously, the data are missing information about visitor numbers"!!!<font>

## 4.11 Random Forest Model<a id='4.11_Random_Forest_Model'></a>

A model that can work very well in a lot of cases is the random forest. For regression, this is provided by `sklearn`'s `RandomForestRegressor` class.

Time to stop the bad practice of repeatedly checking performance on the test split. Instead, go straight from defining the pipeline to assessing performance using cross-validation. `cross_validate` will perform the fitting as part of the process. This uses the default settings for the random forest so you'll then proceed to investigate some different hyperparameters.

### 4.11.1 Define the pipeline<a id='4.11.1_Define_the_pipeline'></a>

In [ ]:
#Code task 22#
#Define a pipeline comprising the steps:
#SimpleImputer() with a strategy of 'median'
#StandardScaler(),
#and then RandomForestRegressor() with a random state of 47
RF_pipe = make_pipeline(
    SimpleImputer(strategy='median'),
    StandardScaler(),
    RandomForestRegressor(random_state=47)
)

### 4.11.2 Fit and assess performance using cross-validation<a id='4.11.2_Fit_and_assess_performance_using_cross-validation'></a>

In [ ]:
#Code task 23#
#Call `cross_validate` to estimate the pipeline's performance.
#Pass it the random forest pipe object, `X_train` and `y_train`,
#and get it to use 5-fold cross-validation
rf_default_cv_results = cross_validate(RF_pipe, X_train, y_train, cv=5)

In [ ]:
rf_cv_scores = rf_default_cv_results['test_score']
rf_cv_scores

In [ ]:
np.mean(rf_cv_scores), np.std(rf_cv_scores)

### 4.11.3 Hyperparameter search using GridSearchCV<a id='4.11.3_Hyperparameter_search_using_GridSearchCV'></a>

Random forest has a number of hyperparameters that can be explored, however here you'll limit yourselves to exploring some different values for the number of trees. You'll try it with and without feature scaling, and try both the mean and median as strategies for imputing missing values.

In [ ]:
n_est = [int(n) for n in np.logspace(start=1, stop=3, num=20)]
grid_params = {
        'randomforestregressor__n_estimators': n_est,
        'standardscaler': [StandardScaler(), None],
        'simpleimputer__strategy': ['mean', 'median']
}
grid_params

In [ ]:
#Code task 24#
#Call `GridSearchCV` with the random forest pipeline, passing in the above `grid_params`
#dict for parameters to evaluate, 5-fold cross-validation, and all available CPU cores (if desired)
rf_grid_cv = GridSearchCV(RF_pipe, param_grid=grid_params, cv=5, n_jobs=-1)

In [ ]:
#Code task 25#
#Now call the `GridSearchCV`'s `fit()` method with `X_train` and `y_train` as arguments
#to actually start the grid search. This may take a minute or two.
rf_grid_cv.fit(X_train, y_train)

In [ ]:
#Code task 26#
#Print the best params (`best_params_` attribute) from the grid search
rf_grid_cv.best_params_

It looks like imputing with the median helps, but scaling the features doesn't.

In [ ]:
rf_best_cv_results = cross_validate(rf_grid_cv.best_estimator_, X_train, y_train, cv=5)
rf_best_scores = rf_best_cv_results['test_score']
rf_best_scores

In [ ]:
np.mean(rf_best_scores), np.std(rf_best_scores)

You've marginally improved upon the default CV results. Random forest has many more hyperparameters you could tune, but we won't dive into that here.

<font color='red'>what hyperparameters did we just tune???????? n_est????????<font>

In [ ]:
#Code task 27#
#Plot a barplot of the random forest's feature importances,
#assigning the `feature_importances_` attribute of 
#`rf_grid_cv.best_estimator_.named_steps.randomforestregressor` to the name `imps` to then
#create a pandas Series object of the feature importances, with the index given by the
#training data column names, sorting the values in descending order
plt.subplots(figsize=(10, 5))
imps = rf_grid_cv.best_estimator_.named_steps.randomforestregressor.feature_importances_
rf_feat_imps = pd.Series(imps, index=X_train.columns).sort_values(ascending=False)
rf_feat_imps.plot(kind='bar')
plt.xlabel('features')
plt.ylabel('importance')
plt.title('Best random forest regressor feature importances');

Encouragingly, the dominant top four features are in common with your linear model:
* fastQuads
* Runs
* Snow Making_ac
* vertical_drop

<font color='red'> we already know that these are important features because of their positive relation to AdultWeekend ticket price. why do we need to check this again?????????????? <font>

## 4.12 Final Model Selection<a id='4.12_Final_Model_Selection'></a>

Time to select your final model to use for further business modeling! It would be good to revisit the above model selection; there is undoubtedly more that could be done to explore possible hyperparameters.
It would also be worthwhile to investigate removing the least useful features. Gathering or calculating, and storing, features adds business cost and dependencies, so if features genuinely are not needed they should be removed.
Building a simpler model with fewer features can also have the advantage of being easier to sell (and/or explain) to stakeholders.
Certainly there seem to be four strong features here and so a model using only those would probably work well.
However, you want to explore some different scenarios where other features vary so keep the fuller 
model for now. 
The business is waiting for this model and you have something that you have confidence in to be much better than guessing with the average price.

Or, rather, you have two "somethings". You built a best linear model and a best random forest model. You need to finally choose between them. You can calculate the mean absolute error using cross-validation. Although `cross-validate` defaults to the $R^2$ [metric for scoring](https://scikit-learn.org/stable/modules/model_evaluation.html#scoring) regression, you can specify the mean absolute error as an alternative via
the `scoring` parameter.

### 4.12.1 Linear regression model performance<a id='4.12.1_Linear_regression_model_performance'></a>

In [ ]:
# 'neg_mean_absolute_error' uses the (negative of) the mean absolute error
lr_neg_mae = cross_validate(lr_grid_cv.best_estimator_, X_train, y_train, 
                            scoring='neg_mean_absolute_error', cv=5, n_jobs=-1)

In [ ]:
lr_mae_mean = np.mean(-1 * lr_neg_mae['test_score'])
lr_mae_std = np.std(-1 * lr_neg_mae['test_score'])
lr_mae_mean, lr_mae_std

In [ ]:
mean_absolute_error(y_test, lr_grid_cv.best_estimator_.predict(X_test))

### 4.12.2 Random forest regression model performance<a id='4.12.2_Random_forest_regression_model_performance'></a>

In [ ]:
rf_neg_mae = cross_validate(rf_grid_cv.best_estimator_, X_train, y_train, 
                            scoring='neg_mean_absolute_error', cv=5, n_jobs=-1)

In [ ]:
rf_mae_mean = np.mean(-1 * rf_neg_mae['test_score'])
rf_mae_std = np.std(-1 * rf_neg_mae['test_score'])
rf_mae_mean, rf_mae_std

In [ ]:
mean_absolute_error(y_test, rf_grid_cv.best_estimator_.predict(X_test))

### 4.12.3 Conclusion<a id='4.12.3_Conclusion'></a>

The random forest model has a lower cross-validation mean absolute error by almost \\$1. It also exhibits less variability. Verifying performance on the test set produces performance consistent with the cross-validation results.

## 4.13 Data quantity assessment<a id='4.13_Data_quantity_assessment'></a>

Finally, you need to advise the business whether it needs to undertake further data collection. Would more data be useful? We're often led to believe more data is always good, but gathering data invariably has a cost associated with it. Assess this trade off by seeing how performance varies with differing data set sizes. The `learning_curve` function does this conveniently.

In [ ]:
fractions = [.2, .25, .3, .35, .4, .45, .5, .6, .75, .8, 1.0]
train_size, train_scores, test_scores = learning_curve(pipe, X_train, y_train, train_sizes=fractions)
train_scores_mean = np.mean(train_scores, axis=1)
train_scores_std = np.std(train_scores, axis=1)
test_scores_mean = np.mean(test_scores, axis=1)
test_scores_std = np.std(test_scores, axis=1)

In [ ]:
plt.subplots(figsize=(10, 5))
plt.errorbar(train_size, test_scores_mean, yerr=test_scores_std)
plt.xlabel('Training set size')
plt.ylabel('CV scores')
plt.title('Cross-validation score as training set size increases');

This shows that you seem to have plenty of data. There's an initial rapid improvement in model scores as one would expect, but it's essentially levelled off by around a sample size of 40-50.

## 4.14 Save best model object from pipeline<a id='4.14_Save_best_model_object_from_pipeline'></a>

In [ ]:
#Code task 28#
#This may not be "production grade ML deployment" practice, but adding some basic
#information to your saved models can save your bacon in development.
#Just what version model have you just loaded to reuse? What version of `sklearn`
#created it? When did you make it?
#Assign the pandas version number (`pd.__version__`) to the `pandas_version` attribute,
#the numpy version (`np.__version__`) to the `numpy_version` attribute,
#the sklearn version (`sklearn_version`) to the `sklearn_version` attribute,
#and the current datetime (`datetime.datetime.now()`) to the `build_datetime` attribute
#Let's call this model version '1.0'
best_model = rf_grid_cv.best_estimator_
best_model.version = '1.0'
best_model.pandas_version = pd.__version__
best_model.numpy_version = np.__version__
best_model.sklearn_version = sklearn_version
best_model.X_columns = [col for col in X_train.columns]
best_model.build_datetime = datetime.datetime.now()
    
modelpath = 'models'
if not os.path.exists(modelpath):
    os.mkdir(modelpath)
skimodel_path = os.path.join(modelpath, 'ski_resort_pricing_model.pkl')
if not os.path.exists(skimodel_path):
    with open(skimodel_path, 'wb') as f:
        pickle.dump(best_model, f)

## 4.15 Summary<a id='4.15_Summary'></a>

**Q: 1** Write a summary of the work in this notebook. Capture the fact that you gained a baseline idea of performance by simply taking the average price and how well that did. Then highlight that you built a linear model and the features that found. Comment on the estimate of its performance from cross-validation and whether its performance on the test split was consistent with this estimate. Also highlight that a random forest regressor was tried, what preprocessing steps were found to be best, and again what its estimated performance via cross-validation was and whether its performance on the test set was consistent with that. State which model you have decided to use going forwards and why. This summary should provide a quick overview for someone wanting to know quickly why the given model was chosen for the next part of the business problem to help guide important business decisions.

Capture the fact that you gained a baseline idea of performance by simply taking the average price and how well that did.
-Average price yielded an R^2, explained variance, of 0 and a mean absolute error of 18 and 19 on the training (i.e. y_train) and testing (i.e. y_train) sets respectively when compared to their predicted average 'AdultWeekend' ticket price (i.e. y_tr_pred).

Then highlight that you built a linear model and the features that found.
-In building a linear model, features found (using GridSearchCV) included vertical_drop, Snow Making_ac, total_chairs, fastQuads, Runs, LongestRun_mi, trams, SkiableTerrain_ac. In selecting eight (8) features (i.e. hyperparameter k=8) in linear regression to predict 'AdultWeekend' ticket price (i.e. y_train and y_test), the cross validation average test score of R^2 (i.e. explained variance) performance reached a maximum.


Comment on the estimate of its performance from cross-validation and whether its performance on the test split was consistent with this estimate.
-Cross-validation (with number of folds k=5) performance using linear regression model with 15 features (i.e. pipe15) showed an average R^2 score of .6349 and average std of .095. Using the pipe15 model, mean explained variance R^2 of cross-validation is close to the test split R^2 score .6347.


Also highlight that a random forest regressor was tried, what preprocessing steps were found to be best, and again what its estimated performance via cross-validation was and whether its performance on the test set was consistent with that. 
-Preprocessing steps that were found to be best included ?using n_est=69,? omitting the use of feature scaling, and using median instead of mean for feature imputing.
-The estimated performance of random forest regressor via cross-validation was a mean absolute error of 9.754 and standard deviation of 1.353.
-This performance was consistent with performance of the test set where mean absolute error was 9.342 using y_test and X_test.

State which model you have decided to use going forwards and why.
We have decided to go forwards with the random forest regression model because it yields the lower MAE (mean absolute error) between linear regression at 10.448 and random forest regression at 9.754, each by cross validation.