In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import sqlite3

pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

pd.set_option('max_colwidth', None)

In [2]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:90% !important; }</style>"))

In [3]:
#return first 5 and last 5 rows of dataframe
def p(df_):
    return pd.concat([df_.head(), df_.tail()])

In [4]:
def replace_player(df_):
    df_.player.replace({'J.J. Redick':'JJ Redick'}, inplace=True)
    
    df_.player.replace({'A.J. Price': 'AJ Price'}, inplace=True)
    
    df_.player.replace({'Alex Ajinca':'Alexis Ajinca'}, inplace=True)
    
    df_.player.replace({'C.J. Miles': 'CJ Miles'}, inplace=True)
    
    df_.player.replace({'D.J. White': 'DJ White'}, inplace=True)
    
    df_.player.replace({"Hamady N'Diaye" : 'Hamady Ndiaye'}, inplace=True)
    
    df_.player.replace({'J.J. Hickson': 'JJ Hickson'}, inplace=True)
    
    df_.player.replace({'John Wallace' : 'John Wall'}, inplace=True)
    
    df_.player.replace({'Jose Barea' : 'J.J. Barea'}, inplace=True)
    
    df_.player.replace({'Wes Johnson':'Wesley Johnson'}, inplace=True)
    
    df_.player.replace({'B.J. Mullens':'Byron Mullens'}, inplace=True)
    
    df_.player.replace({'Bill Walker':'Henry Walker'}, inplace=True)
    
    df_.player.replace({'Gerald Henderson Jr.':'Gerald Henderson'}, inplace=True)
    
    df_.player.replace({'Jianlian Yi':'Yi Jianlian'}, inplace=True)
    
    df_.player.replace({'Mike Conley Jr.':'Mike Conley'}, inplace=True)
    
    df_.player.replace({'Mike Dunleavy Jr.':'Mike Dunleavy'}, inplace=True)
    
    df_.player.replace({'Nene Hilario': 'Nene'}, inplace=True)
    
    df_.player.replace({'Didier Mbenga':'DJ Mbenga'}, inplace=True)
    
    df_.player.replace({'A.J. Hammons':'AJ Hammons'}, inplace=True)
    
    df_.player.replace({'C.J. McCollum':'CJ McCollum'}, inplace=True)
    
    df_.player.replace({'D.J. Augustine':'D.J. Augustin'}, inplace=True)
    
    df_.player.replace({'DeAndre Bembry':"DeAndre' Bembry"}, inplace=True)
    
    df_.player.replace({'Giorgios Papagiannis':'Georgios Papagiannis'}, inplace=True)
    
    df_.player.replace({'Glen Rice Jr.':'Glen Rice'}, inplace=True)
    
    df_.player.replace({'J.R. Smith':'JR Smith'}, inplace=True)
    
    df_.player.replace({'James Ennis':'James Ennis III'}, inplace=True)
    
    df_.player.replace({'John Collins  John Collins':'John Collins'}, inplace=True)
    
    df_.player.replace({'Juan Hernangomez':'Juancho Hernangomez'}, inplace=True)
    
    df_.player.replace({'Billy Ouattara':'Yakuba Ouattara'}, inplace=True)
    
    df_.player.replace({'Courtney Simpson':'Diamon Simpson'}, inplace=True)
    
    df_.player.replace({'Danuel House':'Danuel House Jr.'}, inplace=True)
    
    df_.player.replace({'Domas Sabonis':'Domantas Sabonis'}, inplace=True)
    
    df_.player.replace({'Jake Wiley':'Jacob Wiley'}, inplace=True)
    
    df_.player.replace({'James McAdoo':'James Michael McAdoo'}, inplace=True)
    
    df_.player.replace({'Jeff Pendergraph':'Jeff Ayres'}, inplace=True)
    
    df_.player.replace({'Jeff Taylor':'Jeffery Taylor'}, inplace=True)
    
    df_.player.replace({'K.J. McDaniels':'KJ McDaniels'}, inplace=True)
    
    df_.player.replace({'K.J. McDaniels':'KJ McDaniels'}, inplace=True)
    
    df_.player.replace({'Malcom Lee':'Malcolm Lee'}, inplace=True)
    
    df_.player.replace({'Marcus Morris':'Marcus Morris Sr.'}, inplace=True)
    
    df_.player.replace({'Matt Williams':'Matt Williams Jr.'}, inplace=True)
    
    df_.player.replace({"Maurice N'dour":'Maurice Ndour'}, inplace=True)
    
    df_.player.replace({'Milos Tedosic':'Milos Teodosic'}, inplace=True)
    
    df_.player.replace({'Moe Harkless':'Maurice Harkless'}, inplace=True)
    
    df_.player.replace({'O.G. Anunoby':'OG Anunoby'}, inplace=True)
    
    df_.player.replace({'Ognen Kuzmic':'Ognjen Kuzmic'}, inplace=True)
    
    df_.player.replace({'P.J. Dozier':'PJ Dozier'}, inplace=True)
    
    df_.player.replace({'P.J. Hairston':'PJ Hairston'}, inplace=True)
    
    df_.player.replace({'Qi Zhou':'Zhou Qi'}, inplace=True)
    
    df_.player.replace({'R.J. Hunter':'RJ Hunter'}, inplace=True)
    
    df_.player.replace({'Ray McCallum Jr.':'Ray McCallum'}, inplace=True)
    
    df_.player.replace({'Ron Artest':'Metta World Peace'}, inplace=True)
    
    df_.player.replace({'Roy Marble':'Devyn Marble'}, inplace=True)
    
    df_.player.replace({'Stephen Zimmerman Jr.':'Stephen Zimmerman'}, inplace=True)
    
    df_.player.replace({'Tony Wroten Jr.':'Tony Wroten'}, inplace=True)
    
    df_.player.replace({'Toure Murry':"Toure' Murry"}, inplace=True)
    
    df_.player.replace({'Viacheslav Kravstov':'Viacheslav Kravtsov'}, inplace=True)
    
    df_.player.replace({'Vince Hunter':'Vincent Hunter'}, inplace=True)
    
    df_.player.replace({'Walker Russell Jr.':'Walker Russell'}, inplace=True)
    
    df_.player.replace({'Wayne Selden Jr.':'Wayne Selden'}, inplace=True)
    
    df_.player.replace({'Wes Matthews Jr.':'Wesley Matthews'}, inplace=True)
    
    return df_

In [5]:
#names dropped from Injury Report dataframe df_inj1018 for the following reasons:
#a. no player nba regular season or playoff boxscore advanced stats between the 2009-10 and 2017-18 seasons.
#b. player did not play an nba regular season or playoff game between the 2009-10 and 2017-18 seasons.
#c. no player nba regular season or playoff boxscore advanced stats between the 2009-10 and 2017-18 seasons. Player plays in nba games
#   following the 2017-18 season.
#d. this is the injury of a coach, not a player. coaches do not have boxscore advanced stats


def drop_player(df_):
    df_.drop(df_[df_.player.str.contains('Marion Hillard')].index, inplace = True) #a
    
    df_.drop(df_[df_.player.str.contains('Matt Janning')].index, inplace = True) #a
    
    df_.drop(df_[df_.player.str.contains("Da'Sean Butler")].index, inplace = True) #a
    
    df_.drop(df_[df_.player.str.contains('Eric Griffin')].index, inplace = True) #a
    
    df_.drop(df_[df_.player.str.contains('Harry Giles')].index, inplace = True) #c
    
    df_.drop(df_[df_.player.str.contains('Magnum Rolle')].index, inplace = True) #a
    
    df_.drop(df_[df_.player.str.contains('Robert Vaden')].index, inplace = True) #a
    
    df_.drop(df_[df_.player.str.contains('Steve Clifford')].index, inplace = True) #d
    
    df_.drop(df_[df_.player.str.contains('Steve Kerr')].index, inplace = True) #d
    
    df_.drop(df_[df_.player.str.contains('Terrico White')].index, inplace = True)#a
    
    df_.drop(df_[df_.player.str.contains('Tyronn Lue')].index, inplace = True) #d
    
    
    
    return df_

In [6]:
#gi('Wes Matthews Jr.')

In [7]:
#gb('Wesley Matthews')

In [8]:
#gia("Toure' Murry")

In [9]:
#get injury data for player
def gi(player_):
    return df_inj1018[df_inj1018.player.str.contains(player_)]

In [10]:
#get boxscore advance for player
def gb(player_):
    return df_5bsa1018[df_5bsa1018.PLAYER_NAME.str.contains(player_)]

In [11]:
def gia(player_):
    return df_ina1018[df_ina1018.player.str.contains(player_)]

In [12]:
os.getcwd()

'/Users/pauljacob/Documents/GitHub/DSCapstone2/02_Data_Wrangling'

In [13]:
#get last game_date of 2017-18 season
path = os.path.join('..', 'processed_data', '7season_first_game_date_last_game_date.csv')
df_7sfgdlgd = pd.read_csv(path, parse_dates=['first', 'last'])
last_game_date_s1718 = df_7sfgdlgd.iloc[8]['last']
last_game_date_s1718

Timestamp('2018-06-08 00:00:00')

In [14]:
#get injury report for the 2010-11 thru 2017-18 seasons
path = os.path.join('..', 'raw_data', 'injuries_2010-2020.csv')
df_inj1020 = pd.read_csv(path, parse_dates=['Date'])

#preprocess player
df_inj1020.Acquired.fillna('', inplace=True)
df_inj1020.Relinquished.fillna('', inplace=True)
df_inj1020['player'] = df_inj1020.Relinquished + ' ' + df_inj1020.Acquired
df_inj1020.player = df_inj1020.player.str.strip()

df_inj1018 = df_inj1020.loc[df_inj1020['Date'] <= last_game_date_s1718]
df_inj1018 = replace_player(df_inj1018)
df_inj1018 = drop_player(df_inj1018)
df_inj1018

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/series.py:4563: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().replace(
/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

,Date,Team,Acquired,Relinquished,Notes,player
0,2010-10-03,Bulls,,Carlos Boozer,fractured bone in right pinky finger (out indefinitely),Carlos Boozer
1,2010-10-06,Pistons,,Jonas Jerebko,torn right Achilles tendon (out indefinitely),Jonas Jerebko
3,2010-10-08,Blazers,,Jeff Ayres,torn ACL in right knee (out indefinitely),Jeff Ayres
4,2010-10-08,Nets,,Troy Murphy,strained lower back (out indefinitely),Troy Murphy
5,2010-10-08,Pistons,,Jonas Jerebko,surgery to repair torn right Achilles tendon,Jonas Jerebko
...,...,...,...,...,...,...
22252,2018-05-25,Rockets,,Chris Paul,strained right hamstring (out for season),Chris Paul
22253,2018-05-26,Cavaliers,,Kevin Love,concussion (DTD),Kevin Love
22254,2018-05-26,Warriors,Patrick McCaw,,activated from IL,Patrick McCaw
22255,2018-05-31,Cavaliers,Kevin Love,,returned to lineup,Kevin Love
22256,2018-06-06,Warriors,Andre Iguodala,,returned to lineup,Andre Iguodala

In [15]:
df_inj1018.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 22232 entries, 0 to 22256
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          22232 non-null  datetime64[ns]
 1   Team          22230 non-null  object
 2   Acquired      22232 non-null  object
 3   Relinquished  22232 non-null  object
 4   Notes         22232 non-null  object
 5   player        22232 non-null  object
dtypes: datetime64[ns](1), object(5)
memory usage: 1.2+ MB

In [16]:
df_inj1018.head()

,Date,Team,Acquired,Relinquished,Notes,player
0,2010-10-03,Bulls,,Carlos Boozer,fractured bone in right pinky finger (out indefinitely),Carlos Boozer
1,2010-10-06,Pistons,,Jonas Jerebko,torn right Achilles tendon (out indefinitely),Jonas Jerebko
3,2010-10-08,Blazers,,Jeff Ayres,torn ACL in right knee (out indefinitely),Jeff Ayres
4,2010-10-08,Nets,,Troy Murphy,strained lower back (out indefinitely),Troy Murphy
5,2010-10-08,Pistons,,Jonas Jerebko,surgery to repair torn right Achilles tendon,Jonas Jerebko

In [17]:

print(df_inj1018.shape)
p(df_inj1018)

(22232, 6)

,Date,Team,Acquired,Relinquished,Notes,player
0,2010-10-03,Bulls,,Carlos Boozer,fractured bone in right pinky finger (out indefinitely),Carlos Boozer
1,2010-10-06,Pistons,,Jonas Jerebko,torn right Achilles tendon (out indefinitely),Jonas Jerebko
3,2010-10-08,Blazers,,Jeff Ayres,torn ACL in right knee (out indefinitely),Jeff Ayres
4,2010-10-08,Nets,,Troy Murphy,strained lower back (out indefinitely),Troy Murphy
5,2010-10-08,Pistons,,Jonas Jerebko,surgery to repair torn right Achilles tendon,Jonas Jerebko
22252,2018-05-25,Rockets,,Chris Paul,strained right hamstring (out for season),Chris Paul
22253,2018-05-26,Cavaliers,,Kevin Love,concussion (DTD),Kevin Love
22254,2018-05-26,Warriors,Patrick McCaw,,activated from IL,Patrick McCaw
22255,2018-05-31,Cavaliers,Kevin Love,,returned to lineup,Kevin Love
22256,2018-06-06,Warriors,Andre Iguodala,,returned to lineup,Andre Iguodala

In [18]:
df_inj1018.player.value_counts()

Dwyane Wade       126
Manu Ginobili     124
Kevin Love        120
Tony Parker       108
Nene              101
                 ...
Earl Boykins        1
Derrick Byars       1
Scotty Hopson       1
Marcus Cousin       1
Diamon Simpson      1
Name: player, Length: 1002, dtype: int64

In [19]:
#AAA. On the 2011-01-22 nba game Wade was NWT due to a migraine (by the nba.com boxscore) during this Heat vs. Raptors
# game. Was Wade inactive for this game according to the inactive player game-by-game dataframe df_ina1018?


path = os.path.join('..', 'raw_data','basketball.sqlite')
path
con = sqlite3.connect(path)
cursor = con.cursor()

cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
print(cursor.fetchall())

[('Player',), ('Team',), ('Team_Attributes',), ('Team_History',), ('Player_Attributes',), ('Game_Officials',), ('Game_Inactive_Players',), ('Team_Salary',), ('Player_Salary',), ('Draft',), ('Draft_Combine',), ('Player_Photos',), ('Player_Bios',), ('Game',), ('News',), ('News_Missing',)]

In [20]:
df_ina = pd.read_sql_query("SELECT * from Game_Inactive_Players", con)
df_ina['player'] = df_ina.FIRST_NAME + " " + df_ina.LAST_NAME
df_ina.player = df_ina.player.str.strip()
df_ina

,PLAYER_ID,FIRST_NAME,LAST_NAME,JERSEY_NUM,TEAM_ID,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION,GAME_ID,player
0,184,Bobby,Phills,14,1610612739,Cleveland,Cavaliers,CLE,0029600034,Bobby Phills
1,781,Will,Perdue,41,1610612759,San Antonio,Spurs,SAS,0029600034,Will Perdue
2,120,Steven,Smith,8,1610612737,Atlanta,Hawks,ATL,0029600132,Steven Smith
3,698,Eddie,Johnson,8,1610612754,Indiana,Pacers,IND,0029600203,Eddie Johnson
4,32,Clifford,Rozier,44,1610612753,Orlando,Magic,ORL,0029600213,Clifford Rozier
...,...,...,...,...,...,...,...,...,...,...
97932,2544,LeBron,James,23,1610612747,Los Angeles,Lakers,LAL,0022000982,LeBron James
97933,203115,Will,Barton,5,1610612743,Denver,Nuggets,DEN,0022000982,Will Barton
97934,1627750,Jamal,Murray,27,1610612743,Denver,Nuggets,DEN,0022000982,Jamal Murray
97935,1630192,Zeke,Nnaji,22,1610612743,Denver,Nuggets,DEN,0022000982,Zeke Nnaji
97936,1628420,Monte,Morris,11,1610612743,Denver,Nuggets,DEN,0022000982,Monte Morris

In [21]:
df_ina.GAME_ID = df_ina.GAME_ID.astype(int)
df_ina.GAME_ID.head()

0    29600034
1    29600034
2    29600132
3    29600203
4    29600213
Name: GAME_ID, dtype: int64

In [22]:
df_ina.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97937 entries, 0 to 97936
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   PLAYER_ID          97937 non-null  object
 1   FIRST_NAME         97937 non-null  object
 2   LAST_NAME          97937 non-null  object
 3   JERSEY_NUM         97937 non-null  object
 4   TEAM_ID            97937 non-null  object
 5   TEAM_CITY          97937 non-null  object
 6   TEAM_NAME          97937 non-null  object
 7   TEAM_ABBREVIATION  97937 non-null  object
 8   GAME_ID            97937 non-null  int64
 9   player             97937 non-null  object
dtypes: int64(1), object(9)
memory usage: 7.5+ MB

In [23]:
df_ina[df_ina.player.str.contains('Dwyane Wade')]

,PLAYER_ID,FIRST_NAME,LAST_NAME,JERSEY_NUM,TEAM_ID,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION,GAME_ID,player
3883,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20500623,Dwyane Wade
5043,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20500868,Dwyane Wade
5116,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20500884,Dwyane Wade
6665,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20501214,Dwyane Wade
6749,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20501219,Dwyane Wade
8457,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20600316,Dwyane Wade
8547,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20600330,Dwyane Wade
9051,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20600432,Dwyane Wade
9106,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20600442,Dwyane Wade
11027,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20600813,Dwyane Wade
11143,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20600835,Dwyane Wade
11182,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20600841,Dwyane Wade
11277,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20600856,Dwyane Wade
11329,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20600872,Dwyane Wade
11442,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20600896,Dwyane Wade
11508,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20600911,Dwyane Wade
11568,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20600922,Dwyane Wade
11647,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20600939,Dwyane Wade
11710,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20600950,Dwyane Wade
11786,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20600967,Dwyane Wade
11823,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20600974,Dwyane Wade
11906,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20600991,Dwyane Wade
12004,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20601008,Dwyane Wade
12077,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20601023,Dwyane Wade
12102,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20601033,Dwyane Wade
12194,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20601047,Dwyane Wade
12269,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20601058,Dwyane Wade
12336,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20601078,Dwyane Wade
12404,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20601088,Dwyane Wade
12442,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20601102,Dwyane Wade
12542,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20601119,Dwyane Wade
12563,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20601123,Dwyane Wade
13065,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20601219,Dwyane Wade
13174,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20700012,Dwyane Wade
13229,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20700017,Dwyane Wade
13317,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20700038,Dwyane Wade
13399,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20700059,Dwyane Wade
13484,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20700070,Dwyane Wade
13568,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20700087,Dwyane Wade
13647,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20700096,Dwyane Wade
17692,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20700942,Dwyane Wade
17752,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20700956,Dwyane Wade
17810,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20700968,Dwyane Wade
17892,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20700984,Dwyane Wade
17962,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20701000,Dwyane Wade
18012,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20701006,Dwyane Wade
18065,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20701023,Dwyane Wade
18134,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20701030,Dwyane Wade
18179,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20701046,Dwyane Wade
18238,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20701059,Dwyane Wade
18289,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20701070,Dwyane Wade
18392,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20701093,Dwyane Wade
18431,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20701100,Dwyane Wade
18497,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20701117,Dwyane Wade
18581,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20701128,Dwyane Wade
18643,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20701143,Dwyane Wade
18686,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20701155,Dwyane Wade
18828,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20701182,Dwyane Wade
18898,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20701197,Dwyane Wade
18950,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20701203,Dwyane Wade
19022,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20701222,Dwyane Wade
23990,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20801009,Dwyane Wade
24979,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20801214,Dwyane Wade
25010,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20801223,Dwyane Wade
28801,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20900808,Dwyane Wade
28834,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20900819,Dwyane Wade
28909,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20900839,Dwyane Wade
29041,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20900872,Dwyane Wade
30433,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,20901222,Dwyane Wade
31414,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21000185,Dwyane Wade
32614,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21000432,Dwyane Wade
36112,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21001164,Dwyane Wade
36437,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21001221,Dwyane Wade
37140,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21100213,Dwyane Wade
37202,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21100229,Dwyane Wade
37234,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21100240,Dwyane Wade
37279,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21100254,Dwyane Wade
37314,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21100260,Dwyane Wade
38946,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21100794,Dwyane Wade
39089,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21100838,Dwyane Wade
39596,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21100981,Dwyane Wade
39861,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21200072,Dwyane Wade
40032,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21200121,Dwyane Wade
40070,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21200138,Dwyane Wade
43338,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21201041,Dwyane Wade
43360,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21201049,Dwyane Wade
43693,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21201126,Dwyane Wade
43707,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21201140,Dwyane Wade
43784,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21201157,Dwyane Wade
43832,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21201165,Dwyane Wade
44076,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21300005,Dwyane Wade
44618,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21300158,Dwyane Wade
44648,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21300164,Dwyane Wade
45015,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21300264,Dwyane Wade
45056,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21300279,Dwyane Wade
45143,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21300300,Dwyane Wade
45566,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21300411,Dwyane Wade
45625,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21300434,Dwyane Wade
46284,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21300612,Dwyane Wade
46299,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21300617,Dwyane Wade
46346,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21300631,Dwyane Wade
46880,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21300774,Dwyane Wade
47322,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21300893,Dwyane Wade
47792,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21301003,Dwyane Wade
47924,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21301036,Dwyane Wade
47970,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21301049,Dwyane Wade
48255,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21301121,Dwyane Wade
48325,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21301135,Dwyane Wade
48397,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21301149,Dwyane Wade
48419,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21301158,Dwyane Wade
48486,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21301167,Dwyane Wade
48527,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21301180,Dwyane Wade
49246,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21400124,Dwyane Wade
49303,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21400143,Dwyane Wade
49314,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21400149,Dwyane Wade
49410,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21400170,Dwyane Wade
49473,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21400185,Dwyane Wade
49512,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21400195,Dwyane Wade
49555,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21400206,Dwyane Wade
51056,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21400582,Dwyane Wade
51144,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21400598,Dwyane Wade
51530,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21400702,Dwyane Wade
51590,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21400716,Dwyane Wade
51627,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21400727,Dwyane Wade
51671,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21400737,Dwyane Wade
51694,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21400757,Dwyane Wade
51810,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21400777,Dwyane Wade
51865,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21400796,Dwyane Wade
52922,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21401064,Dwyane Wade
54135,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21500124,Dwyane Wade
60912,2548,Dwyane,Wade,3,1610612741,Chicago,Bulls,CHI,21600517,Dwyane Wade
62016,2548,Dwyane,Wade,3,1610612741,Chicago,Bulls,CHI,21600792,Dwyane Wade
62300,2548,Dwyane,Wade,3,1610612741,Chicago,Bulls,CHI,21600849,Dwyane Wade
62672,2548,Dwyane,Wade,3,1610612741,Chicago,Bulls,CHI,21600938,Dwyane Wade
62716,2548,Dwyane,Wade,3,1610612741,Chicago,Bulls,CHI,21600949,Dwyane Wade
63027,2548,Dwyane,Wade,3,1610612741,Chicago,Bulls,CHI,21601021,Dwyane Wade
63040,2548,Dwyane,Wade,3,1610612741,Chicago,Bulls,CHI,21601032,Dwyane Wade
63164,2548,Dwyane,Wade,3,1610612741,Chicago,Bulls,CHI,21601051,Dwyane Wade
63174,2548,Dwyane,Wade,3,1610612741,Chicago,Bulls,CHI,21601061,Dwyane Wade
63242,2548,Dwyane,Wade,3,1610612741,Chicago,Bulls,CHI,21601077,Dwyane Wade
63325,2548,Dwyane,Wade,3,1610612741,Chicago,Bulls,CHI,21601090,Dwyane Wade
63434,2548,Dwyane,Wade,3,1610612741,Chicago,Bulls,CHI,21601122,Dwyane Wade
63503,2548,Dwyane,Wade,3,1610612741,Chicago,Bulls,CHI,21601138,Dwyane Wade
63570,2548,Dwyane,Wade,3,1610612741,Chicago,Bulls,CHI,21601146,Dwyane Wade
63592,2548,Dwyane,Wade,3,1610612741,Chicago,Bulls,CHI,21601160,Dwyane Wade
63661,2548,Dwyane,Wade,3,1610612741,Chicago,Bulls,CHI,21601173,Dwyane Wade
67052,2548,Dwyane,Wade,9,1610612739,Cleveland,Cavaliers,CLE,21700397,Dwyane Wade
67368,2548,Dwyane,Wade,9,1610612739,Cleveland,Cavaliers,CLE,21700440,Dwyane Wade
69541,2548,Dwyane,Wade,9,1610612739,Cleveland,Cavaliers,CLE,21700715,Dwyane Wade
69673,2548,Dwyane,Wade,9,1610612739,Cleveland,Cavaliers,CLE,21700734,Dwyane Wade
70262,2548,Dwyane,Wade,9,1610612739,Cleveland,Cavaliers,CLE,21700807,Dwyane Wade
71767,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21701004,Dwyane Wade
71906,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21701018,Dwyane Wade
71999,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21701034,Dwyane Wade
72200,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21701054,Dwyane Wade
72322,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21701068,Dwyane Wade
73134,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21701172,Dwyane Wade
74771,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21800156,Dwyane Wade
74879,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21800170,Dwyane Wade
74953,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21800177,Dwyane Wade
75069,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21800191,Dwyane Wade
75151,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21800205,Dwyane Wade
75274,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21800217,Dwyane Wade
75410,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,21800235,Dwyane Wade

In [24]:
#stick a date for game_id: get (game_id, game_date, team_id) dataframe df_3gigdti1018
path = os.path.join('..', 'processed_data', '3game_id_game_date_team_id.csv')
path
df_3gigdti = pd.read_csv(path)
df_3gigdti1018 = df_3gigdti[(df_3gigdti.season == '2010-11') |
                            (df_3gigdti.season == '2011-12') |
                            (df_3gigdti.season == '2012-13') |
                            (df_3gigdti.season == '2013-14') |
                            (df_3gigdti.season == '2014-15') |
                            (df_3gigdti.season == '2015-16') |
                            (df_3gigdti.season == '2016-17') |
                            (df_3gigdti.season == '2017-18')]
df_3gigdti1018.head()

,game_id,game_date,team_id,is_home,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,season_year,season_type,season
9840,21000001,2010-10-26,1610612738,t,1.0,240,32.0,69.0,0.464,8.0,16.0,0.500,16.0,25.0,1.0,8.0,34.0,42,25.0,6.0,4.0,18.0,19.0,88,2010,Regular Season,2010-11
9841,21000001,2010-10-26,1610612748,f,0.0,240,27.0,74.0,0.365,8.0,20.0,0.400,18.0,25.0,1.0,11.0,28.0,39,15.0,10.0,6.0,17.0,21.0,80,2010,Regular Season,2010-11
9842,21000002,2010-10-26,1610612757,t,1.0,240,43.0,93.0,0.462,10.0,20.0,0.500,10.0,15.0,1.0,18.0,30.0,48,31.0,11.0,2.0,12.0,22.0,106,2010,Regular Season,2010-11
9843,21000002,2010-10-26,1610612756,f,0.0,240,36.0,74.0,0.486,9.0,19.0,0.474,11.0,16.0,1.0,7.0,23.0,30,15.0,3.0,4.0,19.0,19.0,92,2010,Regular Season,2010-11
9844,21000003,2010-10-26,1610612745,f,0.0,240,38.0,91.0,0.418,8.0,20.0,0.400,26.0,28.0,1.0,16.0,37.0,53,25.0,6.0,7.0,20.0,25.0,110,2010,Regular Season,2010-11

In [25]:
df_3gigdti1018[['game_id', 'game_date', 'team_id']].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20534 entries, 9840 to 31037
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   game_id    20534 non-null  int64
 1   game_date  20534 non-null  object
 2   team_id    20534 non-null  int64
dtypes: int64(2), object(1)
memory usage: 641.7+ KB

In [26]:
df_ina.rename(columns={'GAME_ID':'game_id'}).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97937 entries, 0 to 97936
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   PLAYER_ID          97937 non-null  object
 1   FIRST_NAME         97937 non-null  object
 2   LAST_NAME          97937 non-null  object
 3   JERSEY_NUM         97937 non-null  object
 4   TEAM_ID            97937 non-null  object
 5   TEAM_CITY          97937 non-null  object
 6   TEAM_NAME          97937 non-null  object
 7   TEAM_ABBREVIATION  97937 non-null  object
 8   game_id            97937 non-null  int64
 9   player             97937 non-null  object
dtypes: int64(1), object(9)
memory usage: 7.5+ MB

In [27]:
#stick a date for game_id: merge
df_ina1018 = pd.merge(df_3gigdti1018[['game_id', 'game_date']], df_ina.rename(columns={'GAME_ID':'game_id'}), on='game_id', how='inner').drop_duplicates()
df_ina1018

,game_id,game_date,PLAYER_ID,FIRST_NAME,LAST_NAME,JERSEY_NUM,TEAM_ID,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION,player
0,21000001,2010-10-26,202376,Luke,Harangody,55,1610612738,Boston,Celtics,BOS,Luke Harangody
1,21000001,2010-10-26,2570,Kendrick,Perkins,43,1610612738,Boston,Celtics,BOS,Kendrick Perkins
2,21000001,2010-10-26,202340,Avery,Bradley,0,1610612738,Boston,Celtics,BOS,Avery Bradley
3,21000001,2010-10-26,202354,Dexter,Pittman,45,1610612748,Miami,Heat,MIA,Dexter Pittman
4,21000001,2010-10-26,2034,Mike,Miller,13,1610612748,Miami,Heat,MIA,Mike Miller
...,...,...,...,...,...,...,...,...,...,...,...
86249,21701230,2018-04-11,202697,Iman,Shumpert,4,1610612758,Sacramento,Kings,SAC,Iman Shumpert
86250,21701230,2018-04-11,203900,Markel,Brown,26,1610612745,Houston,Rockets,HOU,Markel Brown
86251,21701230,2018-04-11,201583,Ryan,Anderson,33,1610612745,Houston,Rockets,HOU,Ryan Anderson
86252,21701230,2018-04-11,2772,Trevor,Ariza,1,1610612745,Houston,Rockets,HOU,Trevor Ariza
86253,21701230,2018-04-11,201601,Luc,Mbah a Moute,12,1610612745,Houston,Rockets,HOU,Luc Mbah a Moute

In [28]:
df_ina1018[df_ina1018.player.str.contains('Dwyane Wade')]

,game_id,game_date,PLAYER_ID,FIRST_NAME,LAST_NAME,JERSEY_NUM,TEAM_ID,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION,player
1837,21000185,2010-11-20,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
4292,21000432,2010-12-23,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
11254,21001164,2011-04-06,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
11848,21001221,2011-04-13,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
13314,21100213,2012-01-19,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
13429,21100229,2012-01-21,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
13511,21100240,2012-01-22,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
13605,21100254,2012-01-24,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
13644,21100260,2012-01-25,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
16940,21100794,2012-04-03,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
17214,21100838,2012-04-08,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
18185,21100981,2012-04-26,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
18763,21200072,2012-11-09,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
19113,21200121,2012-11-15,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
19233,21200138,2012-11-17,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
25707,21201041,2013-03-24,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
25762,21201049,2013-03-25,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
26344,21201126,2013-04-05,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
26452,21201140,2013-04-06,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
26583,21201157,2013-04-09,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
26646,21201165,2013-04-10,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
27199,21300005,2013-10-30,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
28286,21300158,2013-11-19,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
28327,21300164,2013-11-20,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
29062,21300264,2013-12-03,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
29172,21300279,2013-12-05,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
29328,21300300,2013-12-08,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
30134,21300411,2013-12-23,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
30313,21300434,2013-12-27,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
31613,21300612,2014-01-20,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
31648,21300617,2014-01-21,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
31742,21300631,2014-01-23,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
32833,21300774,2014-02-11,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
33722,21300893,2014-03-03,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
34637,21301003,2014-03-18,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
34900,21301036,2014-03-22,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
35002,21301049,2014-03-24,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
35589,21301121,2014-04-02,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
35701,21301135,2014-04-04,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
35815,21301149,2014-04-06,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
35891,21301158,2014-04-08,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
35970,21301167,2014-04-09,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
36076,21301180,2014-04-11,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
37488,21400124,2014-11-14,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
37637,21400143,2014-11-16,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
37685,21400149,2014-11-17,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
37860,21400170,2014-11-20,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
37980,21400185,2014-11-22,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
38064,21400195,2014-11-23,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
38159,21400206,2014-11-25,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
41215,21400582,2015-01-14,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
41345,21400598,2015-01-16,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
42120,21400702,2015-01-30,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
42226,21400716,2015-02-01,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
42304,21400727,2015-02-03,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
42381,21400737,2015-02-04,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
42532,21400757,2015-02-06,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
42690,21400777,2015-02-09,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
42827,21400796,2015-02-11,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
44898,21401064,2015-03-25,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
47305,21500124,2015-11-12,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
60898,21600517,2017-01-02,2548,Dwyane,Wade,3,1610612741,Chicago,Bulls,CHI,Dwyane Wade
63154,21600792,2017-02-08,2548,Dwyane,Wade,3,1610612741,Chicago,Bulls,CHI,Dwyane Wade
63650,21600849,2017-02-16,2548,Dwyane,Wade,3,1610612741,Chicago,Bulls,CHI,Dwyane Wade
64374,21600938,2017-03-06,2548,Dwyane,Wade,3,1610612741,Chicago,Bulls,CHI,Dwyane Wade
64467,21600949,2017-03-08,2548,Dwyane,Wade,3,1610612741,Chicago,Bulls,CHI,Dwyane Wade
65068,21601021,2017-03-17,2548,Dwyane,Wade,3,1610612741,Chicago,Bulls,CHI,Dwyane Wade
65158,21601032,2017-03-18,2548,Dwyane,Wade,3,1610612741,Chicago,Bulls,CHI,Dwyane Wade
65326,21601051,2017-03-21,2548,Dwyane,Wade,3,1610612741,Chicago,Bulls,CHI,Dwyane Wade
65414,21601061,2017-03-22,2548,Dwyane,Wade,3,1610612741,Chicago,Bulls,CHI,Dwyane Wade
65556,21601077,2017-03-24,2548,Dwyane,Wade,3,1610612741,Chicago,Bulls,CHI,Dwyane Wade
65667,21601090,2017-03-26,2548,Dwyane,Wade,3,1610612741,Chicago,Bulls,CHI,Dwyane Wade
65928,21601122,2017-03-30,2548,Dwyane,Wade,3,1610612741,Chicago,Bulls,CHI,Dwyane Wade
66065,21601138,2017-04-01,2548,Dwyane,Wade,3,1610612741,Chicago,Bulls,CHI,Dwyane Wade
66130,21601146,2017-04-02,2548,Dwyane,Wade,3,1610612741,Chicago,Bulls,CHI,Dwyane Wade
66249,21601160,2017-04-04,2548,Dwyane,Wade,3,1610612741,Chicago,Bulls,CHI,Dwyane Wade
66360,21601173,2017-04-06,2548,Dwyane,Wade,3,1610612741,Chicago,Bulls,CHI,Dwyane Wade
73110,21700397,2017-12-12,2548,Dwyane,Wade,9,1610612739,Cleveland,Cavaliers,CLE,Dwyane Wade
73774,21700440,2017-12-17,2548,Dwyane,Wade,9,1610612739,Cleveland,Cavaliers,CLE,Dwyane Wade
78090,21700715,2018-01-26,2548,Dwyane,Wade,9,1610612739,Cleveland,Cavaliers,CLE,Dwyane Wade
78404,21700734,2018-01-28,2548,Dwyane,Wade,9,1610612739,Cleveland,Cavaliers,CLE,Dwyane Wade
79583,21700807,2018-02-07,2548,Dwyane,Wade,9,1610612739,Cleveland,Cavaliers,CLE,Dwyane Wade
82623,21701004,2018-03-12,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
82845,21701018,2018-03-14,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
83107,21701034,2018-03-16,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
83436,21701054,2018-03-19,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
83663,21701068,2018-03-21,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade
85307,21701172,2018-04-04,2548,Dwyane,Wade,3,1610612748,Miami,Heat,MIA,Dwyane Wade

In [29]:
#get game_id, game_date pairs
df_3gdgiti0618 = pd.read_csv(os.path.join('..', 'processed_data', '3game_id_game_date_team_id.csv'))
df_3gdgi0618 = df_3gdgiti0618[['game_date', 'game_id']].drop_duplicates()
df_3gdgi0618

        game_date   game_id
0      2006-10-31  20600001
2      2006-10-31  20600002
4      2006-11-01  20600003
6      2006-11-01  20600004
8      2006-11-01  20600005
...           ...       ...
31028  2018-05-28  41700317
31030  2018-05-31  41700401
31032  2018-06-03  41700402
31034  2018-06-06  41700403
31036  2018-06-08  41700404

[15519 rows x 2 columns]

In [30]:
df_5bsa1018 = pd.read_csv(os.path.join('..', 'processed_data', '5boxscoreadvancedv2_2009_2018.csv'))
df_5bsa1018.shape

(291643, 31)

In [31]:
df_5bsa1018.PLAYER_NAME = df_5bsa1018.PLAYER_NAME.fillna('')
df_5bsa1018 = pd.merge(df_3gdgi0618, df_5bsa1018.rename(columns={'GAME_ID':'game_id'}), on='game_id', how='inner')
df_5bsa1018

,game_date,game_id,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
0,2009-10-27,20900001,1.610613e+09,BOS,Boston,1718.0,Paul Pierce,F,NaN,37:59,95.3,97.4,96.5,98.6,-1.2,-1.3,0.053,0.50,4.8,0.028,0.270,0.151,9.5,0.538,0.661,0.233,0.239,96.88,94.76,78.97,76.0,0.189
1,2009-10-27,20900001,1.610613e+09,BOS,Boston,708.0,Kevin Garnett,F,NaN,33:05,95.6,95.5,101.0,103.1,-5.4,-7.6,0.059,1.00,7.1,0.097,0.233,0.164,7.1,0.500,0.553,0.178,0.181,95.96,95.03,79.19,66.0,0.147
2,2009-10-27,20900001,1.610613e+09,BOS,Boston,2570.0,Kendrick Perkins,C,NaN,25:42,99.2,100.0,108.2,104.3,-9.1,-4.3,0.077,0.33,9.1,0.000,0.050,0.024,27.3,0.571,0.605,0.196,0.198,86.53,87.77,73.14,47.0,0.030
3,2009-10-27,20900001,1.610613e+09,BOS,Boston,951.0,Ray Allen,G,NaN,42:21,105.2,108.8,105.4,105.1,-0.2,3.7,0.120,1.00,12.5,0.000,0.054,0.028,12.5,0.375,0.440,0.236,0.240,91.50,90.12,75.10,80.0,0.051
4,2009-10-27,20900001,1.610613e+09,BOS,Boston,200765.0,Rajon Rondo,G,NaN,34:29,92.7,94.1,98.0,97.1,-5.3,-3.0,0.526,5.00,50.0,0.061,0.125,0.092,10.0,0.500,0.500,0.130,0.133,95.63,95.36,79.46,68.0,0.158
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291638,2018-06-08,41700404,1.610613e+09,CLE,Cleveland,1626204.0,Larry Nance Jr.,NaN,NaN,23:12,93.4,97.6,93.1,95.2,0.3,2.3,0.333,0.00,33.3,0.176,0.077,0.133,0.0,0.429,0.444,0.148,0.146,88.76,85.87,71.56,41.0,0.139
291639,2018-06-08,41700404,1.610613e+09,CLE,Cleveland,1626224.0,Cedi Osman,NaN,NaN,4:03,100.0,114.3,76.1,75.0,23.9,39.3,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.333,0.333,0.333,0.333,94.10,88.89,74.07,7.0,0.000
291640,2018-06-08,41700404,1.610613e+09,CLE,Cleveland,101181.0,Jose Calderon,NaN,NaN,4:03,100.0,114.3,76.1,75.0,23.9,39.3,0.250,0.00,50.0,0.000,0.200,0.100,0.0,0.000,0.000,0.111,0.111,94.10,88.89,74.07,7.0,0.174
291641,2018-06-08,41700404,1.610613e+09,CLE,Cleveland,1627790.0,Ante Zizic,NaN,NaN,1:40,100.0,133.3,0.0,0.0,100.0,133.3,0.000,0.00,0.0,0.333,0.000,0.200,0.0,1.000,1.000,0.400,0.400,100.80,86.40,72.00,3.0,2.250
291642,2018-06-08,41700404,1.610613e+09,CLE,Cleveland,203903.0,Jordan Clarkson,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN

In [38]:
print(len(set(df_inj1018.player) - set(df_5bsa1018.PLAYER_NAME)))
set(df_inj1018.player) - set(df_5bsa1018.PLAYER_NAME)

0

set()

In [39]:
print(len(set(df_5bsa1018.PLAYER_NAME) - set(df_inj1020.player)))
set(df_5bsa1018.PLAYER_NAME) - set(df_inj1020.player)

129

{'Aaron Jackson',
 'Adam Morrison',
 'Adonal Foyle',
 'Alando Tucker',
 'Alex Stepheson',
 'Alexander Johnson',
 'Allen Iverson',
 'Andre Emmett',
 'Andre Ingram',
 'Anthony Johnson',
 'Antonio Anderson',
 'Antonio Daniels',
 'Ben Bentil',
 'Blake Ahearn',
 'Bobby Simmons',
 'Carldell Johnson',
 'Casper Ware',
 'Cedric Jackson',
 'Charles Jenkins',
 'Chris Hunter',
 'Chris Richard',
 'Chucky Atkins',
 'Coby Karl',
 'Courtney Fortson',
 'D.J. Kennedy',
 'DJ Stephens',
 'Darnell Jackson',
 'Darryl Watkins',
 'David Wear',
 'Desmond Mason',
 'Devean George',
 'Devin Brown',
 'Dionte Christmas',
 'Drew Gordon',
 'Eddie House',
 'Edwin Ubiles',
 'Elijah Millsap',
 'Eric Dawson',
 'Fabricio Oberto',
 'Flip Murray',
 'Ike Diogu',
 'Ime Udoka',
 'J.R. Giddens',
 "JJ O'Brien",
 'Jabari Brown',
 'Jameel Warney',
 'James Nunnally',
 'James Singleton',
 'JamesOn Curry',
 'Jarron Collins',
 'Jarvis Hayes',
 'Jason Hart',
 'Javaris Crittenton',
 'Jawad Williams',
 'Jeff Foote',
 'Jerome Dyson',
 'Jerrelle Benimon',
 'Jerry Smith',
 'Jonathan Bender',
 'Jonathan Gibson',
 'Jorge Gutierrez',
 'Josh Akognon',
 'Josh Boone',
 'Josh Davis',
 'Josh Gray',
 'Kalin Lucas',
 'Kareem Rush',
 'Keith Appling',
 'Keith Benson',
 'Kenny Hasbrouck',
 'Kenny Thomas',
 'Kevin Ollie',
 'Kyle Collinsworth',
 'Kyle Weaver',
 'Langston Galloway',
 'Larry Hughes',
 'Larry Owens',
 'Lindsey Hunter',
 'Luke Zeller',
 'Malik Hairston',
 'Marcus Haislip',
 'Marcus Landry',
 'Marcus Williams',
 'Mardy Collins',
 'Marqus Blakely',
 'Michael Finley',
 'Mickael Gelabale',
 'Mike Wilks',
 'Mikki Moore',
 'Morris Almond',
 'Nathan Jawai',
 'Oleksiy Pecherov',
 'Oliver Lafayette',
 'Omari Johnson',
 'Othello Hunter',
 'Patricio Garino',
 'Patrick Ewing',
 "Patrick O'Bryant",
 'Paul Davis',
 'Primoz Brezec',
 'Rafer Alston',
 'Randolph Morris',
 'Rasho Nesterovic',
 'Ricky Davis',
 'Rodney Purvis',
 'Roko Ukic',
 'Ronald Dupree',
 'Ronald Roberts Jr.',
 'Ryan Bowen',
 'Sean May',
 'Shane Edwards',
 'Shannon Brown',
 'Shawn Long',
 'Sim Bhullar',
 'Sindarius Thornwell',
 'Speedy Claxton',
 'Steven Hunter',
 'Taylor Griffin',
 'Tim Thomas',
 'Travis Diener',
 'Travis Outlaw',
 'Trenton Hassell',
 'Trey Gilder',
 'Trey McKinney-Jones',
 'Walt Lemon Jr.',
 'Will Cherry',
 'Will Conroy',
 'Xavier Rathan-Mayes',
 'Yakhouba Diawara'}

In [34]:
#df.select_dtypes('object')

In [35]:
#df[''].value_counts().head()

In [36]:
#missing_x = df[[' ', ' ']].isnull().sum(axis=1)

In [37]:
df.hist(figsize=(15,10))
plt.subplots_adjust(hspace=.5);

NameError: name 'df' is not defined

In [ ]:
#df.loc[5, ' '] = 1111

In [ ]:

df.column_name.hist(bins=30)
plt.xlabel('column_name')
plt.ylabel('Count')
plt.title('Distribution of');

In [ ]:
df.column_name[df.column_name < 1000].describe()

In [ ]:
df.iloc[115]

In [ ]:
#type()

In [ ]:
#len()

In [ ]:
#df.iloc[:, 4]

In [ ]:
#df.iloc[:, [0,5,6]].copy()

In [ ]:
#set(df.column_name) - set(df2.column_name)

In [ ]:
#df.state[df.column_name.str.contains('state1|state2|state3|state4')]

In [ ]:
#regex
#df.column_name.replace(to_replace='\[.*\]', value='', regex=True, inplace=True)

In [ ]:
#df.plot(x='column_name1', y='column_name2', kind='scatter');

In [ ]:
#df.loc[df.column_name == 'state1', ['column_name', 'column_name']]

In [ ]:
#missing = pd.concat([df.isnull().sum(axis=1), 100 * df.isnull().mean(axis=1)], axis=1)
#missing.columns=['count', '%']
#missing.sort_values(by='count', ascending=False).head(10)

In [ ]:
#missing['%'].unique()

In [ ]:
#datapath = 'data'

In [ ]:
#if not os.path.exists(datapath):
    #os.mkdir(datapath)

In [ ]:
#datapath_df = os.path.join(datapath, 'df_cleaned.csv')
#if not os.path.exists(datapath_df):
#    df.to_csv(datapath_df, index=False)

In [ ]:
#datapath_df2 = os.path.join(datapath, 'df2.csv')
#if not os.path.exists(datapath_df2):
#    df2.to_csv(datapath_df2, index=False)