In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import sqlite3

pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

pd.set_option('max_colwidth', None)

In [2]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:90% !important; }</style>"))

In [3]:
def replace_player(df_):
    df_.player.replace({'J.J. Redick':'JJ Redick'}, inplace=True)
    
    df_.player.replace({'A.J. Price': 'AJ Price'}, inplace=True)
    
    df_.player.replace({'Alex Ajinca':'Alexis Ajinca'}, inplace=True)
    
    df_.player.replace({'C.J. Miles': 'CJ Miles'}, inplace=True)
    
    df_.player.replace({'D.J. White': 'DJ White'}, inplace=True)
    
    df_.player.replace({"Hamady N'Diaye" : 'Hamady Ndiaye'}, inplace=True)
    
    df_.player.replace({'J.J. Hickson': 'JJ Hickson'}, inplace=True)
    
    df_.player.replace({'John Wallace' : 'John Wall'}, inplace=True)
    
    df_.player.replace({'Jose Barea' : 'J.J. Barea'}, inplace=True)
    
    df_.player.replace({'Wes Johnson':'Wesley Johnson'}, inplace=True)
    
    df_.player.replace({'B.J. Mullens':'Byron Mullens'}, inplace=True)
    
    df_.player.replace({'Bill Walker':'Henry Walker'}, inplace=True)
    
    df_.player.replace({'Gerald Henderson Jr.':'Gerald Henderson'}, inplace=True)
    
    df_.player.replace({'Jianlian Yi':'Yi Jianlian'}, inplace=True)
    
    df_.player.replace({'Mike Conley Jr.':'Mike Conley'}, inplace=True)
    
    df_.player.replace({'Mike Dunleavy Jr.':'Mike Dunleavy'}, inplace=True)
    
    df_.player.replace({'Nene Hilario': 'Nene'}, inplace=True)
    
    df_.player.replace({'Didier Mbenga':'DJ Mbenga'}, inplace=True)
    
    df_.player.replace({'A.J. Hammons':'AJ Hammons'}, inplace=True)
    
    df_.player.replace({'C.J. McCollum':'CJ McCollum'}, inplace=True)
    
    df_.player.replace({'D.J. Augustine':'D.J. Augustin'}, inplace=True)
    
    df_.player.replace({'DeAndre Bembry':"DeAndre' Bembry"}, inplace=True)
    
    df_.player.replace({'Giorgios Papagiannis':'Georgios Papagiannis'}, inplace=True)
    
    df_.player.replace({'Glen Rice Jr.':'Glen Rice'}, inplace=True)
    
    df_.player.replace({'J.R. Smith':'JR Smith'}, inplace=True)
    
    df_.player.replace({'James Ennis':'James Ennis III'}, inplace=True)
    
    df_.player.replace({'John Collins  John Collins':'John Collins'}, inplace=True)
    
    df_.player.replace({'Juan Hernangomez':'Juancho Hernangomez'}, inplace=True)
    
    df_.player.replace({'Billy Ouattara':'Yakuba Ouattara'}, inplace=True)
    
    df_.player.replace({'Courtney Simpson':'Diamon Simpson'}, inplace=True)
    
    df_.player.replace({'Danuel House':'Danuel House Jr.'}, inplace=True)
    
    df_.player.replace({'Domas Sabonis':'Domantas Sabonis'}, inplace=True)
    
    df_.player.replace({'Jake Wiley':'Jacob Wiley'}, inplace=True)
    
    df_.player.replace({'James McAdoo':'James Michael McAdoo'}, inplace=True)
    
    df_.player.replace({'Jeff Pendergraph':'Jeff Ayres'}, inplace=True)
    
    df_.player.replace({'Jeff Taylor':'Jeffery Taylor'}, inplace=True)
    
    df_.player.replace({'K.J. McDaniels':'KJ McDaniels'}, inplace=True)
    
    df_.player.replace({'K.J. McDaniels':'KJ McDaniels'}, inplace=True)
    
    df_.player.replace({'Malcom Lee':'Malcolm Lee'}, inplace=True)
    
    df_.player.replace({'Marcus Morris':'Marcus Morris Sr.'}, inplace=True)
    
    df_.player.replace({'Matt Williams':'Matt Williams Jr.'}, inplace=True)
    
    df_.player.replace({"Maurice N'dour":'Maurice Ndour'}, inplace=True)
    
    df_.player.replace({'Milos Tedosic':'Milos Teodosic'}, inplace=True)
    
    df_.player.replace({'Moe Harkless':'Maurice Harkless'}, inplace=True)
    
    df_.player.replace({'O.G. Anunoby':'OG Anunoby'}, inplace=True)
    
    df_.player.replace({'Ognen Kuzmic':'Ognjen Kuzmic'}, inplace=True)
    
    df_.player.replace({'P.J. Dozier':'PJ Dozier'}, inplace=True)
    
    df_.player.replace({'P.J. Hairston':'PJ Hairston'}, inplace=True)
    
    df_.player.replace({'Qi Zhou':'Zhou Qi'}, inplace=True)
    
    df_.player.replace({'R.J. Hunter':'RJ Hunter'}, inplace=True)
    
    df_.player.replace({'Ray McCallum Jr.':'Ray McCallum'}, inplace=True)
    
    df_.player.replace({'Ron Artest':'Metta World Peace'}, inplace=True)
    
    df_.player.replace({'Roy Marble':'Devyn Marble'}, inplace=True)
    
    df_.player.replace({'Stephen Zimmerman Jr.':'Stephen Zimmerman'}, inplace=True)
    
    df_.player.replace({'Tony Wroten Jr.':'Tony Wroten'}, inplace=True)
    
    df_.player.replace({'Toure Murry':"Toure' Murry"}, inplace=True)
    
    df_.player.replace({'Viacheslav Kravstov':'Viacheslav Kravtsov'}, inplace=True)
    
    df_.player.replace({'Vince Hunter':'Vincent Hunter'}, inplace=True)
    
    df_.player.replace({'Walker Russell Jr.':'Walker Russell'}, inplace=True)
    
    df_.player.replace({'Wayne Selden Jr.':'Wayne Selden'}, inplace=True)
    
    df_.player.replace({'Wes Matthews Jr.':'Wesley Matthews'}, inplace=True)
    
    return df_

#names dropped from Injury Report dataframe df_inj1018 for the following reasons:
#a. no player nba regular season or playoff boxscore advanced stats between the 2009-10 and 2017-18 seasons.
#b. player did not play an nba regular season or playoff game between the 2009-10 and 2017-18 seasons.
#c. no player nba regular season or playoff boxscore advanced stats between the 2009-10 and 2017-18 seasons. Player plays in nba games
#   following the 2017-18 season.
#d. this is the injury of a coach, not a player. coaches do not have boxscore advanced stats


def drop_player(df_):
    df_.drop(df_[df_.player.str.contains('Marion Hillard')].index, inplace = True) #a
    
    df_.drop(df_[df_.player.str.contains('Matt Janning')].index, inplace = True) #a
    
    df_.drop(df_[df_.player.str.contains("Da'Sean Butler")].index, inplace = True) #a
    
    df_.drop(df_[df_.player.str.contains('Eric Griffin')].index, inplace = True) #a
    
    df_.drop(df_[df_.player.str.contains('Harry Giles')].index, inplace = True) #c
    
    df_.drop(df_[df_.player.str.contains('Magnum Rolle')].index, inplace = True) #a
    
    df_.drop(df_[df_.player.str.contains('Robert Vaden')].index, inplace = True) #a
    
    df_.drop(df_[df_.player.str.contains('Steve Clifford')].index, inplace = True) #d
    
    df_.drop(df_[df_.player.str.contains('Steve Kerr')].index, inplace = True) #d
    
    df_.drop(df_[df_.player.str.contains('Terrico White')].index, inplace = True)#a
    
    df_.drop(df_[df_.player.str.contains('Tyronn Lue')].index, inplace = True) #d
    
    return df_
    
    
#get injury data for player
def gi(player_):
    return df_inj1018[df_inj1018.player.str.contains(player_)] 

#get boxscore advance for player
def gb(player_):
    return df_5bsa1018[df_5bsa1018.PLAYER_NAME.str.contains(player_)]

#get inactive player game-by-game
def gia(player_):
    return df_ina1018[df_ina1018.player.str.contains(player_)]

#return first 5 and last 5 rows of dataframe
def p(df_):
    return pd.concat([df_.head(), df_.tail()])

In [4]:
os.getcwd()

'/Users/pauljacob/Documents/GitHub/DSCapstone2/02_Data_Wrangling'

In [5]:
#get injury report for 2010-11 thru 2017-18 sesasons: df_inj1018

#last game_date of 2017-18 season
path = os.path.join('..', 'processed_data', '7season_first_game_date_last_game_date.csv')
df_7sfgdlgd = pd.read_csv(path, parse_dates=['first', 'last'])
last_game_date_s1718 = df_7sfgdlgd.iloc[8]['last']
last_game_date_s1718

#read in raw injury report
path = os.path.join('..', 'raw_data', 'injuries_2010-2020.csv')
df_inj1020 = pd.read_csv(path, parse_dates=['Date'])

#preprocess player & Date
df_inj1020.Acquired.fillna('', inplace=True)
df_inj1020.Relinquished.fillna('', inplace=True)
df_inj1020['player'] = df_inj1020.Relinquished + ' ' + df_inj1020.Acquired
df_inj1020.player = df_inj1020.player.str.strip()

df_inj1018 = df_inj1020.loc[df_inj1020['Date'] <= last_game_date_s1718]
df_inj1018 = replace_player(df_inj1018)
df_inj1018 = drop_player(df_inj1018)

#filter Date to game_date
df_3gdgiti0618 = pd.read_csv(os.path.join('..', 'processed_data', '3game_id_game_date_team_id.csv'), parse_dates=['game_date'])
df_3gdgi0618 = df_3gdgiti0618[['game_date', 'game_id']].drop_duplicates()
df_3gd0618 = df_3gdgi0618.game_date.drop_duplicates()
df_inj1018 = pd.merge(df_3gd0618.drop_duplicates(), df_inj1018.rename(columns={'Date':'game_date'}), on='game_date', how='inner')
p(df_inj1018)

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/series.py:4563: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().replace(
/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

,game_date,Team,Acquired,Relinquished,Notes,player
0,2010-10-26,Blazers,,Elliot Williams,placed on IL,Elliot Williams
1,2010-10-26,Blazers,,Greg Oden,placed on IL with left knee injury (out for season),Greg Oden
2,2010-10-26,Blazers,,Joel Przybilla,placed on IL placed on IL recovering from surgery on right knee to repair ruptured patella tendon,Joel Przybilla
3,2010-10-26,Celtics,,Avery Bradley,placed on IL recovering from surgery on left ankle,Avery Bradley
4,2010-10-26,Celtics,,Kendrick Perkins,placed on IL recovering from surgery on right knee to repair torn ACL,Kendrick Perkins
21916,2018-05-22,Warriors,,Andre Iguodala,bruised left leg (DTD),Andre Iguodala
21917,2018-05-26,Cavaliers,,Kevin Love,concussion (DTD),Kevin Love
21918,2018-05-26,Warriors,Patrick McCaw,,activated from IL,Patrick McCaw
21919,2018-05-31,Cavaliers,Kevin Love,,returned to lineup,Kevin Love
21920,2018-06-06,Warriors,Andre Iguodala,,returned to lineup,Andre Iguodala

In [6]:
def in_game_injury_team_win_lose():
    
    #check players stats on game_date injury dates

    #get injury report games relinquished: df_inj1018r
    df_inj1018r = df_inj1018[df_inj1018.Relinquished != '']

    #read in nba boxscore advanced data for seasons 2009-10 thru 2017-18: df_5bsa1018
    df_5bsa1018 = pd.read_csv(os.path.join('..', 'processed_data', '5boxscoreadvancedv2_2009_2018.csv'))
    df_5bsa1018.PLAYER_NAME = df_5bsa1018.PLAYER_NAME.fillna('')
    df_5bsa1018 = pd.merge(df_3gdgi0618, df_5bsa1018.rename(columns={'GAME_ID':'game_id'}), on='game_id', how='inner')
    df_5bsa1018.MIN = df_5bsa1018.MIN.fillna('00:00')
    df_5bsa1018.MIN = pd.to_timedelta('00:' + df_5bsa1018.MIN).astype('timedelta64[s]').astype('float64') / 60
    df_5bsa1018.TEAM_ID = df_5bsa1018.TEAM_ID.fillna(0).astype('int64')

    df_5bsa1018


    
    df_gdinj1018 = pd.merge(df_inj1018r, df_5bsa1018.rename(columns={'PLAYER_NAME':'player'}), how='inner', on=['game_date', 'player'])

    df_gdinj1018[['E_OFF_RATING', 'OFF_RATING',
           'E_DEF_RATING', 'DEF_RATING', 'E_NET_RATING', 'NET_RATING', 'AST_PCT',
           'AST_TOV', 'AST_RATIO', 'OREB_PCT', 'DREB_PCT', 'REB_PCT', 'TM_TOV_PCT',
           'EFG_PCT', 'TS_PCT', 'USG_PCT', 'E_USG_PCT', 'E_PACE', 'PACE',
           'PACE_PER40', 'POSS', 'PIE']] = df_gdinj1018[['E_OFF_RATING', 'OFF_RATING',
           'E_DEF_RATING', 'DEF_RATING', 'E_NET_RATING', 'NET_RATING', 'AST_PCT',
           'AST_TOV', 'AST_RATIO', 'OREB_PCT', 'DREB_PCT', 'REB_PCT', 'TM_TOV_PCT',
           'EFG_PCT', 'TS_PCT', 'USG_PCT', 'E_USG_PCT', 'E_PACE', 'PACE',
           'PACE_PER40', 'POSS', 'PIE']].fillna(0)
    
    df_gdinj1018['ig_player_injury'] = 0
    df_gdinj1018.loc[df_gdinj1018.MIN != 0, 'ig_player_injury'] = 1
    
    df_temp = df_gdinj1018[df_gdinj1018.MIN != 0][['game_id','TEAM_ID', 'ig_player_injury']]
    df_temp['pts'] = 0


    
    df_3gdgiti0618[['game_id', 'team_id', 'pts']]
    df_temp2 = df_3gdgiti0618[['game_id', 'team_id', 'pts']]
    df_temp2['ig_player_injury'] = 0
    df_temp2 = pd.merge(df_temp.game_id.drop_duplicates(), df_temp2, how='left', on='game_id')


    df_temp = pd.concat([df_temp.rename(columns={'TEAM_ID':'team_id'}), df_temp2])

    df_temp = df_temp.groupby(['game_id', 'team_id']).sum()

    df_temp.reset_index(inplace=True)

    df_temp = df_temp[(df_temp.game_id != 21000342) &
                                              (df_temp.game_id != 21000646) &
                                              (df_temp.game_id != 21500064) &
                                              (df_temp.game_id != 21600060) &
                                             (df_temp.game_id != 21600176) &
                                             (df_temp.game_id != 21600663) &
                                             (df_temp.game_id != 21600834) &
                                             (df_temp.game_id != 41500213) &
                                             (df_temp.game_id != 41600311)]
    
    game_id_winlose = set(df_temp.game_id)

    injury_wl = pd.DataFrame({'injury_&_win':[0], 'injury_&_lose':[0]})
    injury_wl
    
    for gi in game_id_winlose:
        df_ip = df_temp[df_temp.game_id == gi][['ig_player_injury', 'pts']].reset_index(drop=True)
        df_ip = df_ip.reset_index(drop=True)
        if (df_ip.iloc[0,0] > df_ip.iloc[1,0]) & (df_ip.iloc[0,1] > df_ip.iloc[1,1]):
            injury_wl['injury_&_win'] = injury_wl['injury_&_win'] + 1
        if (df_ip.iloc[0,0] > df_ip.iloc[1,0]) & (df_ip.iloc[0,1] < df_ip.iloc[1,1]):
            injury_wl['injury_&_lose'] = injury_wl['injury_&_lose'] + 1
        if (df_ip.iloc[0,0] < df_ip.iloc[1,0]) & (df_ip.iloc[0,1] < df_ip.iloc[1,1]):
            injury_wl['injury_&_win'] = injury_wl['injury_&_win'] + 1
        if (df_ip.iloc[0,0] < df_ip.iloc[1,0]) & (df_ip.iloc[0,1] > df_ip.iloc[1,1]):
            injury_wl['injury_&_lose'] = injury_wl['injury_&_lose'] + 1
        
    return injury_wl

In [7]:
in_game_injury_team_win_lose()

<ipython-input-6-fb2c2a1eb55e>:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_temp2['ig_player_injury'] = 0

   injury_&_win  injury_&_lose
0            87            102

<font color='red'> how did this happen that we have NaN entries???<font>

In [8]:
print(df_gdinj1018[df_gdinj1018.OFF_RATING != 0].shape)
df_gdinj1018[df_gdinj1018.OFF_RATING != 0].head()

NameError: name 'df_gdinj1018' is not defined

In [ ]:
print(df_gdinj1018[df_gdinj1018.USG_PCT != 0].shape)
df_gdinj1018[df_gdinj1018.USG_PCT != 0].head()

In [ ]:
print(df_gdinj1018[df_gdinj1018.USG_PCT == 0].shape)
df_gdinj1018[df_gdinj1018.USG_PCT == 0].head()

In [ ]:
set(df_gdinj1018[df_gdinj1018.USG_PCT == 0][['game_date', 'player', 'OFF_RATING', 'USG_PCT']]) - set(df_gdinj1018[df_gdinj1018.OFF_RATING == 0][['game_date', 'player', 'OFF_RATING', 'USG_PCT']])

In [ ]:
set(df_gdinj1018[df_gdinj1018.OFF_RATING == 0][['game_date', 'player', 'OFF_RATING', 'USG_PCT']]) - set(df_gdinj1018[df_gdinj1018.USG_PCT == 0][['game_date', 'player', 'OFF_RATING', 'USG_PCT']])

In [ ]:
df_gdinj1018.OFF_RATING.value_counts()

In [ ]:
df_gdinj1018[df_gdinj1018.OFF_RATING.isnull()]

In [ ]:
#AAA. On the 2011-01-22 nba game Wade was NWT due to a migraine (by the nba.com boxscore) during this Heat vs. Raptors
# game. Was Wade inactive for this game according to the inactive player game-by-game dataframe df_ina1018?


path = os.path.join('..', 'raw_data','basketball.sqlite')
path
con = sqlite3.connect(path)
cursor = con.cursor()

cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
print(cursor.fetchall())

In [ ]:
df_ina = pd.read_sql_query("SELECT * from Game_Inactive_Players", con)
df_ina['player'] = df_ina.FIRST_NAME + " " + df_ina.LAST_NAME
df_ina.player = df_ina.player.str.strip()
df_ina

In [ ]:
df_ina.GAME_ID = df_ina.GAME_ID.astype(int)
df_ina.GAME_ID.head()

In [ ]:
df_ina.info()

In [ ]:
#stick a date for game_id: get (game_id, game_date, team_id) dataframe df_3gigdti1018
path = os.path.join('..', 'processed_data', '3game_id_game_date_team_id.csv')
path
df_3gigdti = pd.read_csv(path)
df_3gigdti1018 = df_3gigdti[(df_3gigdti.season == '2010-11') |
                            (df_3gigdti.season == '2011-12') |
                            (df_3gigdti.season == '2012-13') |
                            (df_3gigdti.season == '2013-14') |
                            (df_3gigdti.season == '2014-15') |
                            (df_3gigdti.season == '2015-16') |
                            (df_3gigdti.season == '2016-17') |
                            (df_3gigdti.season == '2017-18')]
df_3gigdti1018.head()

In [ ]:
df_3gigdti1018[['game_id', 'game_date', 'team_id']].info()

In [ ]:
df_ina.rename(columns={'GAME_ID':'game_id'}).info()

In [ ]:
#stick a date for game_id: merge
df_ina1018 = pd.merge(df_3gigdti1018[['game_id', 'game_date']], df_ina.rename(columns={'GAME_ID':'game_id'}), on='game_id', how='inner').drop_duplicates()
df_ina1018

In [ ]:
df_5bsa1018 = pd.read_csv(os.path.join('..', 'processed_data', '5boxscoreadvancedv2_2009_2018.csv'))
df_5bsa1018.PLAYER_NAME = df_5bsa1018.PLAYER_NAME.fillna('')
df_5bsa1018 = pd.merge(df_3gdgi0618, df_5bsa1018.rename(columns={'GAME_ID':'game_id'}), on='game_id', how='inner')
df_5bsa1018

In [ ]:
p(df_5bsa1018[['game_date', 'game_id', 'PLAYER_NAME']])

In [ ]:
pd.merge(df_inj1018, df_5bsa1018[['game_date', 'game_id', 'PLAYER_NAME']].rename(columns={'PLAYER_NAME':'player'}), how='inner', on=['game_date',  'player'])

In [ ]:
df_5bsa1018

In [ ]:
print(len(set(df_inj1018.player) - set(df_5bsa1018.PLAYER_NAME)))
set(df_inj1018.player) - set(df_5bsa1018.PLAYER_NAME)

In [ ]:
print(len(set(df_5bsa1018.PLAYER_NAME) - set(df_inj1020.player)))
set(df_5bsa1018.PLAYER_NAME) - set(df_inj1020.player)

In [ ]:
#df.select_dtypes('object')

In [ ]:
#df[''].value_counts().head()

In [ ]:
#missing_x = df[[' ', ' ']].isnull().sum(axis=1)

In [ ]:
df.hist(figsize=(15,10))
plt.subplots_adjust(hspace=.5);

In [ ]:
#df.loc[5, ' '] = 1111

In [ ]:

df.column_name.hist(bins=30)
plt.xlabel('column_name')
plt.ylabel('Count')
plt.title('Distribution of');

In [ ]:
df.column_name[df.column_name < 1000].describe()

In [ ]:
df.iloc[115]

In [ ]:
#type()

In [ ]:
#len()

In [ ]:
#df.iloc[:, 4]

In [ ]:
#df.iloc[:, [0,5,6]].copy()

In [ ]:
#set(df.column_name) - set(df2.column_name)

In [ ]:
#df.state[df.column_name.str.contains('state1|state2|state3|state4')]

In [ ]:
#regex
#df.column_name.replace(to_replace='\[.*\]', value='', regex=True, inplace=True)

In [ ]:
#df.plot(x='column_name1', y='column_name2', kind='scatter');

In [ ]:
#df.loc[df.column_name == 'state1', ['column_name', 'column_name']]

In [ ]:
#missing = pd.concat([df.isnull().sum(axis=1), 100 * df.isnull().mean(axis=1)], axis=1)
#missing.columns=['count', '%']
#missing.sort_values(by='count', ascending=False).head(10)

In [ ]:
#missing['%'].unique()

In [ ]:
#datapath = 'data'

In [ ]:
#if not os.path.exists(datapath):
    #os.mkdir(datapath)

In [ ]:
#datapath_df = os.path.join(datapath, 'df_cleaned.csv')
#if not os.path.exists(datapath_df):
#    df.to_csv(datapath_df, index=False)

In [ ]:
#datapath_df2 = os.path.join(datapath, 'df2.csv')
#if not os.path.exists(datapath_df2):
#    df2.to_csv(datapath_df2, index=False)