In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [2]:
os.getcwd()

'/Users/pauljacob/Documents/GitHub/DSCapstone2/02_Data_Wrangling'

In [10]:
path0 = os.path.join('..', 'processed_data')
os.listdir(path0)

['2game_id_game_date.csv',
 '3game_id_game_date_team_id.csv',
 '.DS_Store',
 '6injuries_2010-11.csv',
 '5boxscoreadvancedv2_2009_2010.csv',
 '4game_id_date_stats_betting_totals.csv',
 '5boxscoreadvancedv2_2006_2018.csv',
 '5boxscoreadvancedv2_2010_2018.csv',
 '3game_date_home_away.csv',
 'archived',
 '0team_id_abbreviation_df.csv']

In [11]:
path1 = os.path.join('..', 'processed_data', '6injuries_2010-11.csv')

In [12]:
df = pd.read_csv(path1)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1678 entries, 0 to 1677
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   game_date  1678 non-null   object
 1   Team       1678 non-null   object
 2   team_id    1678 non-null   int64
 3   player     1678 non-null   object
 4   game_id    1678 non-null   int64
dtypes: int64(2), object(3)
memory usage: 65.7+ KB

In [15]:
df

       game_date       Team     team_id              player   game_id
0     2010-10-26    Blazers  1610612757     Elliot Williams  21000002
1     2010-10-26    Blazers  1610612757           Greg Oden  21000002
2     2010-10-26    Blazers  1610612757      Joel Przybilla  21000002
3     2010-10-26    Celtics  1610612738       Avery Bradley  21000001
4     2010-10-26    Celtics  1610612738    Kendrick Perkins  21000001
...          ...        ...         ...                 ...       ...
1673  2011-05-26      Bulls  1610612741           Omer Asik  41000305
1674  2011-05-31       Heat  1610612748  Zydrunas Ilgauskas  41000401
1675  2011-06-05  Mavericks  1610612742     Brendan Haywood  41000403
1676  2011-06-07  Mavericks  1610612742   Rodrigue Beaubois  41000404
1677  2011-06-09  Mavericks  1610612742     Brendan Haywood  41000405

[1678 rows x 5 columns]

In [17]:
df[df.player.str.contains('John Wall')]

      game_date     Team     team_id        player   game_id
221  2010-11-16  Wizards  1610612764    John Wall   21000153
253  2010-11-21  Wizards  1610612764    John Wall   21000192
291  2010-11-27  Wizards  1610612764    John Wall   21000235
306  2010-11-29  Wizards  1610612764    John Wall   21000250
378  2010-12-08  Wizards  1610612764    John Wall   21000325
422  2010-12-14  Wizards  1610612764    John Wall   21000362
441  2010-12-16  Wizards  1610612764  John Wallace  21000378
468  2010-12-18  Wizards  1610612764  John Wallace  21000393

In [19]:
path3 = os.path.join('..', 'raw_data')
os.listdir(path3)

['teams.csv',
 'nba_players_all.csv',
 'nba_betting_totals.csv',
 'games.csv',
 'nba_games_all.csv',
 'nba_teams.csv',
 'nba_betting_money_line.csv',
 'injuries_2010-2020.csv',
 'nba_betting_spread.csv',
 'nba_teams_all.csv']

In [ ]:
path3 = os.path.join('..', 'raw_data', '6injuries_2010-11.csv')

In [ ]:
#df.select_dtypes('object')

In [ ]:
#df[''].value_counts().head()

In [ ]:
#missing_x = df[[' ', ' ']].isnull().sum(axis=1)

In [ ]:
df.hist(figsize=(15,10))
plt.subplots_adjust(hspace=.5);

In [ ]:
#df.loc[5, ' '] = 1111

In [ ]:

df.column_name.hist(bins=30)
plt.xlabel('column_name')
plt.ylabel('Count')
plt.title('Distribution of');

In [ ]:
df.column_name[df.column_name < 1000].describe()

In [ ]:
df.iloc[115]

In [ ]:
#type()

In [ ]:
#len()

In [ ]:
#df.iloc[:, 4]

In [ ]:
#df.iloc[:, [0,5,6]].copy()

In [ ]:
#set(df.column_name) - set(df2.column_name)

In [ ]:
#df.state[df.column_name.str.contains('state1|state2|state3|state4')]

In [ ]:
#regex
#df.column_name.replace(to_replace='\[.*\]', value='', regex=True, inplace=True)

In [ ]:
#df.plot(x='column_name1', y='column_name2', kind='scatter');

In [ ]:
#df.loc[df.column_name == 'state1', ['column_name', 'column_name']]

In [ ]:
#missing = pd.concat([df.isnull().sum(axis=1), 100 * df.isnull().mean(axis=1)], axis=1)
#missing.columns=['count', '%']
#missing.sort_values(by='count', ascending=False).head(10)

In [ ]:
#missing['%'].unique()

In [ ]:
#datapath = 'data'

In [ ]:
#if not os.path.exists(datapath):
    #os.mkdir(datapath)

In [ ]:
#datapath_df = os.path.join(datapath, 'df_cleaned.csv')
#if not os.path.exists(datapath_df):
#    df.to_csv(datapath_df, index=False)

In [ ]:
#datapath_df2 = os.path.join(datapath, 'df2.csv')
#if not os.path.exists(datapath_df2):
#    df2.to_csv(datapath_df2, index=False)