In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [2]:
os.getcwd()

'C:\\Users\\Paul\\sb\\DSCasptone2\\02_Data_Wrangling'

In [6]:
df = pd.read_csv('C:\\Users\\Paul\\sb\\DSCasptone2\\raw_data\\nba_games_all.csv')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125624 entries, 0 to 125623
Data columns (total 32 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   game_id      125624 non-null  int64
 1   game_date    119376 non-null  object
 2   matchup      125624 non-null  object
 3   team_id      125624 non-null  int64
 4   is_home      125624 non-null  object
 5   wl           125614 non-null  object
 6   w            41000 non-null   float64
 7   l            41000 non-null   float64
 8   w_pct        41000 non-null   float64
 9   min          125624 non-null  int64
 10  fgm          125607 non-null  float64
 11  fga          90894 non-null   float64
 12  fg_pct       90871 non-null   float64
 13  fg3m         95248 non-null   float64
 14  fg3a         84316 non-null   float64
 15  fg3_pct      80062 non-null   float64
 16  ftm          125605 non-null  float64
 17  fta          120011 non-null  float64
 18  ft_pct       119960 non-null  float64
 19  oreb         83786 non-null   float64
 20  dreb         83639 non-null   float64
 21  reb          125624 non-null  int64
 22  ast          90068 non-null   float64
 23  stl          83960 non-null   float64
 24  blk          84407 non-null   float64
 25  tov          84293 non-null   float64
 26  pf           121742 non-null  float64
 27  pts          125624 non-null  int64
 28  a_team_id    125624 non-null  int64
 29  season_year  125624 non-null  int64
 30  season_type  125624 non-null  object
 31  season       125624 non-null  object
dtypes: float64(19), int64(7), object(6)
memory usage: 30.7+ MB

In [8]:
df.head()

,game_id,game_date,matchup,team_id,is_home,wl,w,l,w_pct,min,...,ast,stl,blk,tov,pf,pts,a_team_id,season_year,season_type,season
0,20800741,2009-02-06,SAC vs. UTA,1610612762,f,W,29.0,22.0,0.569,240,...,19.0,5.0,4.0,18.0,26.0,111,1610612758,2008,Regular Season,2008-09
1,20800701,2009-01-31,POR vs. UTA,1610612762,f,L,26.0,22.0,0.542,240,...,17.0,6.0,0.0,15.0,22.0,108,1610612757,2008,Regular Season,2008-09
2,20800584,2009-01-16,MEM vs. UTA,1610612762,f,W,24.0,16.0,0.600,240,...,23.0,9.0,3.0,15.0,22.0,101,1610612763,2008,Regular Season,2008-09
3,20800558,2009-01-12,IND @ UTA,1610612762,t,W,23.0,15.0,0.605,240,...,24.0,10.0,6.0,8.0,20.0,120,1610612754,2008,Regular Season,2008-09
4,20800440,2008-12-27,HOU vs. UTA,1610612762,f,L,18.0,14.0,0.563,290,...,35.0,13.0,7.0,9.0,27.0,115,1610612745,2008,Regular Season,2008-09

In [9]:
df.select_dtypes('object')

         game_date      matchup is_home wl     season_type   season
0       2009-02-06  SAC vs. UTA       f  W  Regular Season  2008-09
1       2009-01-31  POR vs. UTA       f  L  Regular Season  2008-09
2       2009-01-16  MEM vs. UTA       f  W  Regular Season  2008-09
3       2009-01-12    IND @ UTA       t  W  Regular Season  2008-09
4       2008-12-27  HOU vs. UTA       f  L  Regular Season  2008-09
...            ...          ...     ... ..             ...      ...
125619  2009-04-03    MIN @ UTA       t  L  Regular Season  2008-09
125620  2009-03-24    HOU @ UTA       t  W  Regular Season  2008-09
125621  2009-03-20  OKC vs. UTA       f  W  Regular Season  2008-09
125622  2009-02-23    ATL @ UTA       t  W  Regular Season  2008-09
125623  2009-02-19    BOS @ UTA       t  W  Regular Season  2008-09

[125624 rows x 6 columns]

In [ ]:
#df[''].value_counts().head()

In [ ]:
#missing_x = df[[' ', ' ']].isnull().sum(axis=1)

In [ ]:
df.hist(figsize=(15,10))
plt.subplots_adjust(hspace=.5);

In [ ]:
#df.loc[5, ' '] = 1111

In [ ]:

df.column_name.hist(bins=30)
plt.xlabel('column_name')
plt.ylabel('Count')
plt.title('Distribution of');

In [ ]:
df.column_name[df.column_name < 1000].describe()

In [ ]:
df.iloc[115]

In [ ]:
#type()

In [ ]:
#len()

In [ ]:
#df.iloc[:, 4]

In [ ]:
#df.iloc[:, [0,5,6]].copy()

In [ ]:
#set(df.column_name) - set(df2.column_name)

In [ ]:
#df.state[df.column_name.str.contains('state1|state2|state3|state4')]

In [ ]:
#regex
#df.column_name.replace(to_replace='\[.*\]', value='', regex=True, inplace=True)

In [ ]:
#df.plot(x='column_name1', y='column_name2', kind='scatter');

In [ ]:
#df.loc[df.column_name == 'state1', ['column_name', 'column_name']]

In [ ]:
#missing = pd.concat([df.isnull().sum(axis=1), 100 * df.isnull().mean(axis=1)], axis=1)
#missing.columns=['count', '%']
#missing.sort_values(by='count', ascending=False).head(10)

In [ ]:
#missing['%'].unique()

In [ ]:
#datapath = 'data'

In [ ]:
#if not os.path.exists(datapath):
    #os.mkdir(datapath)

In [ ]:
#datapath_df = os.path.join(datapath, 'df_cleaned.csv')
#if not os.path.exists(datapath_df):
#    df.to_csv(datapath_df, index=False)

In [ ]:
#datapath_df2 = os.path.join(datapath, 'df2.csv')
#if not os.path.exists(datapath_df2):
#    df2.to_csv(datapath_df2, index=False)