In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import sqlite3

pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

pd.set_option('max_colwidth', None)

In [2]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:90% !important; }</style>"))

In [3]:
#return first 5 and last 5 rows of dataframe
def p(df_):
    return pd.concat([df_.head(), df_.tail()])

In [4]:
os.getcwd()

'/Users/pauljacob/Documents/GitHub/DSCapstone2/02_Data_Wrangling'

In [5]:
#pd.read_csv(os.path.join('..','processed_data','A9game_date_team_relinquished_player_2010_2018.csv'))

In [6]:
#add PLAYER_ID using df_5bsa1018
df_ina_pip = pd.read_csv(os.path.join('..','processed_data','A11inactive_game_id_team_id_player_id_2010_2018.csv'))[['PLAYER_ID', 'player']].drop_duplicates().reset_index(drop=True)
print(df_ina_pip.shape)
p(df_ina_pip)

#add team_id using '10season_team_team_id_2010_2018.csv'

(990, 2)

     PLAYER_ID            player
0       202376    Luke Harangody
1         2570  Kendrick Perkins
2       202340     Avery Bradley
3       202354    Dexter Pittman
4         2034       Mike Miller
985    1626198     Le'Bryan Nash
986    1628389       Bam Adebayo
987    1627748        Thon Maker
988    1628369      Jayson Tatum
989     204065    David Stockton

In [7]:
print(pd.read_csv(os.path.join('..','processed_data','A12bsa_game_id_team_id_player_id_2010_2018.csv')).shape)
p(pd.read_csv(os.path.join('..','processed_data','A12bsa_game_id_team_id_player_id_2010_2018.csv')))

(44547, 33)

,game_id,game_date,team_id,season,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
0,21000001,2010-10-26,1610612738,2010-11,BOS,Boston,201623.0,Semih Erden,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,21000001,2010-10-26,1610612738,2010-11,BOS,Boston,101144.0,Von Wafer,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,21000001,2010-10-26,1610612738,2010-11,BOS,Boston,2753.0,Delonte West,NaN,NWT - League Suspension,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,21000001,2010-10-26,1610612748,2010-11,MIA,Miami,201596.0,Mario Chalmers,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,21000001,2010-10-26,1610612748,2010-11,MIA,Miami,436.0,Juwan Howard,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44542,41700403,2018-06-06,1610612739,2017-18,CLE,Cleveland,101181.0,Jose Calderon,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44543,41700403,2018-06-06,1610612739,2017-18,CLE,Cleveland,203903.0,Jordan Clarkson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44544,41700403,2018-06-06,1610612739,2017-18,CLE,Cleveland,1626224.0,Cedi Osman,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44545,41700403,2018-06-06,1610612739,2017-18,CLE,Cleveland,1627790.0,Ante Zizic,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44546,41700404,2018-06-08,1610612739,2017-18,CLE,Cleveland,203903.0,Jordan Clarkson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [8]:
df_bsa_pip = pd.read_csv(os.path.join('..','processed_data','A12bsa_game_id_team_id_player_id_2010_2018.csv'))[['PLAYER_ID', 'PLAYER_NAME']].drop_duplicates().reset_index(drop=True)
print(df_bsa_pip.shape)
p(df_bsa_pip)

(1059, 2)

      PLAYER_ID     PLAYER_NAME
0      201623.0     Semih Erden
1      101144.0       Von Wafer
2        2753.0    Delonte West
3      201596.0  Mario Chalmers
4         436.0    Juwan Howard
1054  1627821.0  James Webb III
1055  1628369.0    Jayson Tatum
1056     2420.0    Nenad Krstic
1057   101204.0    Dwayne Jones
1058  1628935.0   Aaron Jackson

In [9]:
df_bsa_pip2 = pd.read_csv(os.path.join('..','processed_data','A12bsa_game_id_team_id_player_id_2010_2018.csv'))[['PLAYER_ID', 'PLAYER_NAME']]
print(df_bsa_pip2.shape)
p(df_bsa_pip2)

(44547, 2)

       PLAYER_ID      PLAYER_NAME
0       201623.0      Semih Erden
1       101144.0        Von Wafer
2         2753.0     Delonte West
3       201596.0   Mario Chalmers
4          436.0     Juwan Howard
44542   101181.0    Jose Calderon
44543   203903.0  Jordan Clarkson
44544  1626224.0       Cedi Osman
44545  1627790.0       Ante Zizic
44546   203903.0  Jordan Clarkson

In [10]:
df_bsa_pip2.value_counts('PLAYER_ID')

PLAYER_ID
202332.0     263
2617.0       249
2592.0       242
201202.0     196
2555.0       186
            ...
202067.0       1
1627936.0      1
1628369.0      1
1628454.0      1
202536.0       1
Length: 1059, dtype: int64

In [11]:
df_pip1018 = pd.concat([df_ina_pip, df_bsa_pip.rename(columns={'PLAYER_NAME':'player'})]).drop_duplicates().reset_index(drop=True)
print(df_pip1018.shape)
p(df_pip1018)

(1081, 2)

      PLAYER_ID            player
0      202376.0    Luke Harangody
1        2570.0  Kendrick Perkins
2      202340.0     Avery Bradley
3      202354.0    Dexter Pittman
4        2034.0       Mike Miller
1076  1627866.0     Jameel Warney
1077  1628681.0     Rodney Purvis
1078   202918.0      Xavier Silas
1079   101204.0      Dwayne Jones
1080  1628935.0     Aaron Jackson

In [12]:
datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)

datapath_df = os.path.join(datapath, '13player_id_player_2010_2018.csv')
if not os.path.exists(datapath_df):
    df_pip1018.to_csv(datapath_df, index=False)

In [13]:
#get player_id, player, team_id, team, season for seasons 2010-11 thru 2017-18

In [14]:
'''datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)

datapath_df = os.path.join(datapath, '13player_id_player_team_id_team_season_2010_2018.csv')
if not os.path.exists(datapath_df):
    df_piptits1018.to_csv(datapath_df, index=False)'''

"datapath = os.path.join('..', 'processed_data')\n\nif not os.path.exists(datapath):\n    os.mkdir(datapath)\n\ndatapath_df = os.path.join(datapath, '13player_id_player_team_id_team_season_2010_2018.csv')\nif not os.path.exists(datapath_df):\n    df_piptits1018.to_csv(datapath_df, index=False)"