In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os


pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

In [2]:
os.getcwd()

'C:\\Users\\Paul\\sb\\DSCapstone2\\02_Data_Wrangling'

In [3]:
os.listdir()

['.ipynb_checkpoints',
 '02_data_wrangling.ipynb',
 '02_data_wrangling_game_id_player_name_advanced_stats_api_calls_100_cuts.ipynb',
 '02_data_wrangling_injuries_stats_games_merge-Copy1.ipynb',
 '02_data_wrangling_injuries_stats_games_merge-Copy2.ipynb',
 '02_data_wrangling_injuries_stats_games_merge-Copy3.ipynb',
 '02_data_wrangling_injuries_stats_games_merge-Copy4.ipynb',
 '02_data_wrangling_injuries_stats_games_merge.ipynb',
 '02_data_wrangling_injuries_stats_games_merge_v2.ipynb',
 '02_data_wrangling_nba_advanced_stats_100_cuts-Copy1.ipynb',
 '02_data_wrangling_temp-Copy1.ipynb',
 '02_data_wrangling_temp-Copy2.ipynb',
 '02_data_wrangling_temp-Copy3.ipynb',
 '02_data_wrangling_temp.ipynb',
 '02_data_wrangling_v2.ipynb',
 'archived',
 'csvoutput_02_data_wrangling_0team_id_abbreviation_df.ipynb',
 'csvoutput_02_data_wrangling_2game_id_game_date.ipynb',
 'csvoutput_02_data_wrangling_3game_id_game_date_home_away.ipynb',
 'csvoutput_02_data_wrangling_4game_id_date_stats_betting_totals.ipynb',
 'csvoutput_02_data_wrangling_5boxscoreadvancedv2_2006_2018.ipynb',
 'nba_api']

In [4]:
listtt = os.listdir('C:\\Users\\Paul\\sb\\DSCapstone2\\processed_data_preliminary')
listtt

['5game_id_team_id_player_name_advanced_stats.csv',
 '5game_id_team_id_player_name_advanced_stats10131.csv',
 '5game_id_team_id_player_name_advanced_stats10279.csv',
 '5game_id_team_id_player_name_advanced_stats10427.csv',
 '5game_id_team_id_player_name_advanced_stats10575.csv',
 '5game_id_team_id_player_name_advanced_stats10723.csv',
 '5game_id_team_id_player_name_advanced_stats10871.csv',
 '5game_id_team_id_player_name_advanced_stats11019.csv',
 '5game_id_team_id_player_name_advanced_stats1103.csv',
 '5game_id_team_id_player_name_advanced_stats11167.csv',
 '5game_id_team_id_player_name_advanced_stats11315.csv',
 '5game_id_team_id_player_name_advanced_stats11463.csv',
 '5game_id_team_id_player_name_advanced_stats11611.csv',
 '5game_id_team_id_player_name_advanced_stats11759.csv',
 '5game_id_team_id_player_name_advanced_stats11907.csv',
 '5game_id_team_id_player_name_advanced_stats12055.csv',
 '5game_id_team_id_player_name_advanced_stats12203.csv',
 '5game_id_team_id_player_name_advanced_stats12351.csv',
 '5game_id_team_id_player_name_advanced_stats12499.csv',
 '5game_id_team_id_player_name_advanced_stats1251.csv',
 '5game_id_team_id_player_name_advanced_stats12647.csv',
 '5game_id_team_id_player_name_advanced_stats12795.csv',
 '5game_id_team_id_player_name_advanced_stats12943.csv',
 '5game_id_team_id_player_name_advanced_stats13091.csv',
 '5game_id_team_id_player_name_advanced_stats13239.csv',
 '5game_id_team_id_player_name_advanced_stats13387.csv',
 '5game_id_team_id_player_name_advanced_stats13535.csv',
 '5game_id_team_id_player_name_advanced_stats13683.csv',
 '5game_id_team_id_player_name_advanced_stats13831.csv',
 '5game_id_team_id_player_name_advanced_stats13979.csv',
 '5game_id_team_id_player_name_advanced_stats1399.csv',
 '5game_id_team_id_player_name_advanced_stats14127.csv',
 '5game_id_team_id_player_name_advanced_stats14275.csv',
 '5game_id_team_id_player_name_advanced_stats14423.csv',
 '5game_id_team_id_player_name_advanced_stats14571.csv',
 '5game_id_team_id_player_name_advanced_stats14719.csv',
 '5game_id_team_id_player_name_advanced_stats14867.csv',
 '5game_id_team_id_player_name_advanced_stats15015.csv',
 '5game_id_team_id_player_name_advanced_stats15163.csv',
 '5game_id_team_id_player_name_advanced_stats15311.csv',
 '5game_id_team_id_player_name_advanced_stats15459.csv',
 '5game_id_team_id_player_name_advanced_stats1547.csv',
 '5game_id_team_id_player_name_advanced_stats1695.csv',
 '5game_id_team_id_player_name_advanced_stats1843.csv',
 '5game_id_team_id_player_name_advanced_stats1991.csv',
 '5game_id_team_id_player_name_advanced_stats2139.csv',
 '5game_id_team_id_player_name_advanced_stats2287.csv',
 '5game_id_team_id_player_name_advanced_stats2435.csv',
 '5game_id_team_id_player_name_advanced_stats2583.csv',
 '5game_id_team_id_player_name_advanced_stats2731.csv',
 '5game_id_team_id_player_name_advanced_stats2879.csv',
 '5game_id_team_id_player_name_advanced_stats3027.csv',
 '5game_id_team_id_player_name_advanced_stats3175.csv',
 '5game_id_team_id_player_name_advanced_stats3323.csv',
 '5game_id_team_id_player_name_advanced_stats3471.csv',
 '5game_id_team_id_player_name_advanced_stats3619.csv',
 '5game_id_team_id_player_name_advanced_stats3767.csv',
 '5game_id_team_id_player_name_advanced_stats3915.csv',
 '5game_id_team_id_player_name_advanced_stats4063.csv',
 '5game_id_team_id_player_name_advanced_stats4211.csv',
 '5game_id_team_id_player_name_advanced_stats4359.csv',
 '5game_id_team_id_player_name_advanced_stats4507.csv',
 '5game_id_team_id_player_name_advanced_stats4655.csv',
 '5game_id_team_id_player_name_advanced_stats4803.csv',
 '5game_id_team_id_player_name_advanced_stats4951.csv',
 '5game_id_team_id_player_name_advanced_stats5099.csv',
 '5game_id_team_id_player_name_advanced_stats5247.csv',
 '5game_id_team_id_player_name_advanced_stats5395.csv',
 '5game_id_team_id_player_name_advanced_stats5543.csv',
 '5game_id_team_id_player_name_advanced_stats5691.csv',
 '5game_id_team_id_player_name_advanced_stats5839.csv',
 '5game_id_team_id_player_name_advanced_stats5987.csv',
 '5game_id_team_id_player_name_advanced_stats6135.csv',
 '5game_id_team_id_player_name_advanced_stats6283.csv',
 '5game_id_team_id_player_name_advanced_stats6431.csv',
 '5game_id_team_id_player_name_advanced_stats6579.csv',
 '5game_id_team_id_player_name_advanced_stats6727.csv',
 '5game_id_team_id_player_name_advanced_stats6875.csv',
 '5game_id_team_id_player_name_advanced_stats7023.csv',
 '5game_id_team_id_player_name_advanced_stats7171.csv',
 '5game_id_team_id_player_name_advanced_stats7319.csv',
 '5game_id_team_id_player_name_advanced_stats7467.csv',
 '5game_id_team_id_player_name_advanced_stats7615.csv',
 '5game_id_team_id_player_name_advanced_stats7763.csv',
 '5game_id_team_id_player_name_advanced_stats7911.csv',
 '5game_id_team_id_player_name_advanced_stats8059.csv',
 '5game_id_team_id_player_name_advanced_stats807.csv',
 '5game_id_team_id_player_name_advanced_stats8207.csv',
 '5game_id_team_id_player_name_advanced_stats8355.csv',
 '5game_id_team_id_player_name_advanced_stats8503.csv',
 '5game_id_team_id_player_name_advanced_stats8651.csv',
 '5game_id_team_id_player_name_advanced_stats8799.csv',
 '5game_id_team_id_player_name_advanced_stats8947.csv',
 '5game_id_team_id_player_name_advanced_stats9095.csv',
 '5game_id_team_id_player_name_advanced_stats9243.csv',
 '5game_id_team_id_player_name_advanced_stats9391.csv',
 '5game_id_team_id_player_name_advanced_stats9539.csv',
 '5game_id_team_id_player_name_advanced_stats955.csv',
 '5game_id_team_id_player_name_advanced_stats9687.csv',
 '5game_id_team_id_player_name_advanced_stats9835.csv',
 '5game_id_team_id_player_name_advanced_stats9983.csv']

In [5]:
len(listtt)

101

In [6]:
listtt[0]

'5game_id_team_id_player_name_advanced_stats.csv'

In [7]:
df_empty = pd.DataFrame({})
df_empty

Empty DataFrame
Columns: []
Index: []

In [8]:
for i in range(len(listtt)):
    print(i)
    df_temp = pd.read_csv('C:\\Users\\Paul\\sb\\DSCapstone2\\processed_data_preliminary\\' + str(listtt[i]))
    df_empty = pd.concat([df_empty, df_temp])

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100

In [9]:
df_empty.head()

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
0,20600001,1610612741,CHI,Chicago,2736,Luol Deng,F,NaN,24:07,102.3,102.1,86.6,87.0,15.7,15.2,0.083,0.33,6.3,0.040,0.056,0.047,18.8,0.444,0.515,0.263,0.273,92.67,92.55,77.13,47,0.064
1,20600001,1610612741,CHI,Chicago,136,P.J. Brown,F,NaN,18:23,104.2,108.1,69.3,65.8,34.9,42.3,0.077,0.50,16.7,0.000,0.200,0.086,33.3,0.500,0.694,0.111,0.113,97.24,97.91,81.60,37,0.088
2,20600001,1610612741,CHI,Chicago,1112,Ben Wallace,C,NaN,28:29,98.0,103.7,77.0,76.8,21.0,26.9,0.059,0.00,16.7,0.194,0.192,0.193,0.0,0.400,0.460,0.077,0.077,95.18,92.69,77.24,54,0.152
3,20600001,1610612741,CHI,Chicago,2732,Ben Gordon,G,NaN,22:56,86.6,91.1,75.4,73.9,11.1,17.2,0.167,1.00,13.3,0.000,0.050,0.020,13.3,0.111,0.268,0.232,0.235,96.77,95.26,79.38,45,-0.096
4,20600001,1610612741,CHI,Chicago,2550,Kirk Hinrich,G,NaN,34:38,108.3,113.6,77.3,76.5,31.0,37.2,0.167,0.00,13.6,0.000,0.133,0.065,0.0,0.639,0.658,0.241,0.237,94.60,92.86,77.38,66,0.296

In [10]:
#df_empty.reset_index(drop=True, inplace=True)

In [11]:
df_empty

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
0,20600001,1610612741,CHI,Chicago,2736,Luol Deng,F,NaN,24:07,102.3,102.1,86.6,87.0,15.7,15.2,0.083,0.33,6.3,0.040,0.056,0.047,18.8,0.444,0.515,0.263,0.273,92.67,92.55,77.13,47,0.064
1,20600001,1610612741,CHI,Chicago,136,P.J. Brown,F,NaN,18:23,104.2,108.1,69.3,65.8,34.9,42.3,0.077,0.50,16.7,0.000,0.200,0.086,33.3,0.500,0.694,0.111,0.113,97.24,97.91,81.60,37,0.088
2,20600001,1610612741,CHI,Chicago,1112,Ben Wallace,C,NaN,28:29,98.0,103.7,77.0,76.8,21.0,26.9,0.059,0.00,16.7,0.194,0.192,0.193,0.0,0.400,0.460,0.077,0.077,95.18,92.69,77.24,54,0.152
3,20600001,1610612741,CHI,Chicago,2732,Ben Gordon,G,NaN,22:56,86.6,91.1,75.4,73.9,11.1,17.2,0.167,1.00,13.3,0.000,0.050,0.020,13.3,0.111,0.268,0.232,0.235,96.77,95.26,79.38,45,-0.096
4,20600001,1610612741,CHI,Chicago,2550,Kirk Hinrich,G,NaN,34:38,108.3,113.6,77.3,76.5,31.0,37.2,0.167,0.00,13.6,0.000,0.133,0.065,0.0,0.639,0.658,0.241,0.237,94.60,92.86,77.38,66,0.296
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3750,21400531,1610612750,MIN,Minnesota,203897,Zach LaVine,NaN,NaN,12:38,90.4,92.9,122.2,125.0,-31.8,-32.1,0.222,0.50,18.2,0.000,0.067,0.034,36.4,0.500,0.615,0.273,0.275,109.12,106.46,88.71,28,0.041
3751,21400531,1610612750,MIN,Minnesota,201978,Chase Budinger,NaN,NaN,24:07,121.0,119.6,126.6,130.8,-5.6,-11.2,0.053,1.00,11.1,0.100,0.115,0.109,11.1,0.714,0.714,0.136,0.139,103.62,102.50,85.42,51,0.090
3752,21400531,1610612750,MIN,Minnesota,203133,Robbie Hummel,NaN,NaN,7:11,92.9,92.9,108.4,106.7,-15.5,-13.8,0.000,0.00,0.0,0.000,0.111,0.077,0.0,0.000,0.000,0.000,0.000,96.09,96.89,80.74,14,-0.042
3753,21400531,1610612750,MIN,Minnesota,203584,Troy Daniels,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0,NaN
3754,21400531,1610612750,MIN,Minnesota,203922,Glenn Robinson III,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0,NaN

In [12]:
datapath = 'C:\\Users\\Paul\\sb\\DSCapstone2\\processed_data'

if not os.path.exists(datapath):
    os.mkdir(datapath)

datapath_df = os.path.join(datapath, '5boxscoreadvancedv2_2006_2018.csv')
if not os.path.exists(datapath_df):
    df_empty.to_csv(datapath_df, index=False)