In [37]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os


pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

In [38]:
os.getcwd()

'/Users/pauljacob/Documents/GitHub/DSCapstone2/02_Data_Wrangling'

In [39]:
os.listdir()

['csvoutput_02_data_wrangling_0team_id_abbreviation_df.ipynb',
 'csvoutput_02_data_wrangling_5boxscoreadvancedv2_2009_2010.ipynb',
 '.DS_Store',
 '02_data_wrangling_game_id_player_name_advanced_stats_api_calls_100_cuts.ipynb',
 '02_data_wrangling_injuries_stats_games_merge.ipynb',
 'csvoutput_02_data_wrangling_2game_id_game_date.ipynb',
 '02_data_wrangling_temp-Copy2.ipynb',
 'csvoutput_02_data_wrangling_6date_team_id_player_name_A_v3.ipynb',
 '02_data_wrangling_v2.ipynb',
 '02_data_wrangling_temp.ipynb',
 'csvoutput_02_data_wrangling_5boxscoreadvancedv2_2006_2018.ipynb',
 'csvoutput_02_data_wrangling_4game_id_date_stats_betting_totals.ipynb',
 '.ipynb_checkpoints',
 '02_data_wrangling_temp-Copy1.ipynb',
 '02_data_wrangling_injuries_stats_games_merge-Copy4.ipynb',
 'csvoutput_02_data_wrangling_5boxscoreadvancedv2_2010_2018.ipynb',
 'archived',
 'nba_api',
 'csvoutput_02_data_wrangling_6date_team_id_player_name_A_v4.ipynb',
 '02_data_wrangling.ipynb',
 'csvoutput_02_data_wrangling_3game_id_game_date_home_away.ipynb']

In [40]:
listtt = os.listdir(os.path.join('..', 'processed_data_preliminary'))
listtt.remove('.DS_Store')
listtt

['5game_id_team_id_player_name_advanced_stats3175.csv',
 '5game_id_team_id_player_name_advanced_stats13831.csv',
 '5game_id_team_id_player_name_advanced_stats13979.csv',
 '5game_id_team_id_player_name_advanced_stats1399.csv',
 '5game_id_team_id_player_name_advanced_stats3767.csv',
 '5game_id_team_id_player_name_advanced_stats807.csv',
 '5game_id_team_id_player_name_advanced_stats9539.csv',
 '5game_id_team_id_player_name_advanced_stats1991.csv',
 '5game_id_team_id_player_name_advanced_stats8355.csv',
 '5game_id_team_id_player_name_advanced_stats13239.csv',
 '5game_id_team_id_player_name_advanced_stats11611.csv',
 '5game_id_team_id_player_name_advanced_stats15311.csv',
 '5game_id_team_id_player_name_advanced_stats2731.csv',
 '5game_id_team_id_player_name_advanced_stats11759.csv',
 '5game_id_team_id_player_name_advanced_stats14423.csv',
 '5game_id_team_id_player_name_advanced_stats4803.csv',
 '5game_id_team_id_player_name_advanced_stats7467.csv',
 '5game_id_team_id_player_name_advanced_stats5099.csv',
 '5game_id_team_id_player_name_advanced_stats10279.csv',
 '5game_id_team_id_player_name_advanced_stats11167.csv',
 '5game_id_team_id_player_name_advanced_stats.csv',
 '5game_id_team_id_player_name_advanced_stats2287.csv',
 '5game_id_team_id_player_name_advanced_stats10871.csv',
 '5game_id_team_id_player_name_advanced_stats12055.csv',
 '5game_id_team_id_player_name_advanced_stats12647.csv',
 '5game_id_team_id_player_name_advanced_stats10723.csv',
 '5game_id_team_id_player_name_advanced_stats6431.csv',
 '5game_id_team_id_player_name_advanced_stats15459.csv',
 '5game_id_team_id_player_name_advanced_stats6579.csv',
 '5game_id_team_id_player_name_advanced_stats10131.csv',
 '5game_id_team_id_player_name_advanced_stats14867.csv',
 '5game_id_team_id_player_name_advanced_stats12351.csv',
 '5game_id_team_id_player_name_advanced_stats8651.csv',
 '5game_id_team_id_player_name_advanced_stats11315.csv',
 '5game_id_team_id_player_name_advanced_stats10427.csv',
 '5game_id_team_id_player_name_advanced_stats14127.csv',
 '5game_id_team_id_player_name_advanced_stats7615.csv',
 '5game_id_team_id_player_name_advanced_stats12795.csv',
 '5game_id_team_id_player_name_advanced_stats9835.csv',
 '5game_id_team_id_player_name_advanced_stats7171.csv',
 '5game_id_team_id_player_name_advanced_stats3471.csv',
 '5game_id_team_id_player_name_advanced_stats7763.csv',
 '5game_id_team_id_player_name_advanced_stats9983.csv',
 '5game_id_team_id_player_name_advanced_stats2583.csv',
 '5game_id_team_id_player_name_advanced_stats5987.csv',
 '5game_id_team_id_player_name_advanced_stats6875.csv',
 '5game_id_team_id_player_name_advanced_stats2435.csv',
 '5game_id_team_id_player_name_advanced_stats6135.csv',
 '5game_id_team_id_player_name_advanced_stats15015.csv',
 '5game_id_team_id_player_name_advanced_stats6727.csv',
 '5game_id_team_id_player_name_advanced_stats14719.csv',
 '5game_id_team_id_player_name_advanced_stats1843.csv',
 '5game_id_team_id_player_name_advanced_stats15163.csv',
 '5game_id_team_id_player_name_advanced_stats11463.csv',
 '5game_id_team_id_player_name_advanced_stats1103.csv',
 '5game_id_team_id_player_name_advanced_stats6283.csv',
 '5game_id_team_id_player_name_advanced_stats4655.csv',
 '5game_id_team_id_player_name_advanced_stats13683.csv',
 '5game_id_team_id_player_name_advanced_stats13091.csv',
 '5game_id_team_id_player_name_advanced_stats4063.csv',
 '5game_id_team_id_player_name_advanced_stats4507.csv',
 '5game_id_team_id_player_name_advanced_stats1251.csv',
 '5game_id_team_id_player_name_advanced_stats3915.csv',
 '5game_id_team_id_player_name_advanced_stats13535.csv',
 '5game_id_team_id_player_name_advanced_stats5395.csv',
 '5game_id_team_id_player_name_advanced_stats1695.csv',
 '5game_id_team_id_player_name_advanced_stats3323.csv',
 '5game_id_team_id_player_name_advanced_stats9391.csv',
 '5game_id_team_id_player_name_advanced_stats5839.csv',
 '5game_id_team_id_player_name_advanced_stats10575.csv',
 '5game_id_team_id_player_name_advanced_stats12203.csv',
 '5game_id_team_id_player_name_advanced_stats8059.csv',
 '5game_id_team_id_player_name_advanced_stats5543.csv',
 '5game_id_team_id_player_name_advanced_stats11907.csv',
 '5game_id_team_id_player_name_advanced_stats8503.csv',
 '5game_id_team_id_player_name_advanced_stats14275.csv',
 '5game_id_team_id_player_name_advanced_stats7023.csv',
 '5game_id_team_id_player_name_advanced_stats12943.csv',
 '5game_id_team_id_player_name_advanced_stats7911.csv',
 '5game_id_team_id_player_name_advanced_stats9243.csv',
 '5game_id_team_id_player_name_advanced_stats5691.csv',
 '5game_id_team_id_player_name_advanced_stats8799.csv',
 '5game_id_team_id_player_name_advanced_stats13387.csv',
 '5game_id_team_id_player_name_advanced_stats3619.csv',
 '5game_id_team_id_player_name_advanced_stats7319.csv',
 '5game_id_team_id_player_name_advanced_stats9687.csv',
 '5game_id_team_id_player_name_advanced_stats9095.csv',
 '5game_id_team_id_player_name_advanced_stats955.csv',
 '5game_id_team_id_player_name_advanced_stats1547.csv',
 '5game_id_team_id_player_name_advanced_stats4359.csv',
 '5game_id_team_id_player_name_advanced_stats4211.csv',
 '5game_id_team_id_player_name_advanced_stats3027.csv',
 '5game_id_team_id_player_name_advanced_stats12499.csv',
 '5game_id_team_id_player_name_advanced_stats8947.csv',
 '5game_id_team_id_player_name_advanced_stats11019.csv',
 '5game_id_team_id_player_name_advanced_stats2139.csv',
 '5game_id_team_id_player_name_advanced_stats4951.csv',
 '5game_id_team_id_player_name_advanced_stats14571.csv',
 '5game_id_team_id_player_name_advanced_stats2879.csv',
 '5game_id_team_id_player_name_advanced_stats8207.csv',
 '5game_id_team_id_player_name_advanced_stats5247.csv']

In [41]:
len(listtt)

101

In [42]:
listtt[0]

'5game_id_team_id_player_name_advanced_stats3175.csv'

In [43]:
df_empty = pd.DataFrame({})
df_empty

Empty DataFrame
Columns: []
Index: []

In [44]:
for i in range(len(listtt)):
    print(i)
    df_temp = pd.read_csv(os.path.join('..', 'processed_data_preliminary', str(listtt[i])))
    df_empty = pd.concat([df_empty, df_temp])

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100

In [45]:
df_empty.head()

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
0,20800716,1610612738,BOS,Boston,1718,Paul Pierce,F,NaN,37:00,112.4,117.1,96.2,97.1,16.2,20.0,0.240,3.00,17.6,0.033,0.158,0.103,5.9,0.457,0.547,0.346,0.342,93.17,90.81,75.67,70,0.182
1,20800716,1610612738,BOS,Boston,201175,Glen Davis,F,NaN,41:55,106.0,110.3,107.6,110.0,-1.6,0.3,0.069,0.67,12.5,0.100,0.211,0.162,18.8,0.545,0.524,0.159,0.157,93.32,90.48,75.40,78,0.079
2,20800716,1610612738,BOS,Boston,2570,Kendrick Perkins,C,NaN,31:47,99.1,101.7,103.4,108.6,-4.3,-6.9,0.042,1.00,20.0,0.038,0.219,0.138,20.0,0.333,0.333,0.059,0.059,91.69,88.33,73.61,59,0.064
3,20800716,1610612738,BOS,Boston,951,Ray Allen,G,NaN,43:04,107.7,109.9,105.0,107.1,2.7,2.7,0.111,1.00,12.0,0.029,0.044,0.038,12.0,0.583,0.609,0.237,0.238,93.78,91.95,76.63,81,0.090
4,20800716,1610612738,BOS,Boston,200765,Rajon Rondo,G,NaN,35:49,108.6,113.0,100.1,102.8,8.5,10.2,0.348,1.14,28.6,0.107,0.057,0.079,25.0,0.750,0.776,0.253,0.251,97.00,93.81,78.18,69,0.154

In [46]:
#df_empty.reset_index(drop=True, inplace=True)

In [47]:
df_empty

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
0,20800716,1610612738,BOS,Boston,1718,Paul Pierce,F,NaN,37:00,112.4,117.1,96.2,97.1,16.2,20.0,0.240,3.00,17.6,0.033,0.158,0.103,5.9,0.457,0.547,0.346,0.342,93.17,90.81,75.67,70,0.182
1,20800716,1610612738,BOS,Boston,201175,Glen Davis,F,NaN,41:55,106.0,110.3,107.6,110.0,-1.6,0.3,0.069,0.67,12.5,0.100,0.211,0.162,18.8,0.545,0.524,0.159,0.157,93.32,90.48,75.40,78,0.079
2,20800716,1610612738,BOS,Boston,2570,Kendrick Perkins,C,NaN,31:47,99.1,101.7,103.4,108.6,-4.3,-6.9,0.042,1.00,20.0,0.038,0.219,0.138,20.0,0.333,0.333,0.059,0.059,91.69,88.33,73.61,59,0.064
3,20800716,1610612738,BOS,Boston,951,Ray Allen,G,NaN,43:04,107.7,109.9,105.0,107.1,2.7,2.7,0.111,1.00,12.0,0.029,0.044,0.038,12.0,0.583,0.609,0.237,0.238,93.78,91.95,76.63,81,0.090
4,20800716,1610612738,BOS,Boston,200765,Rajon Rondo,G,NaN,35:49,108.6,113.0,100.1,102.8,8.5,10.2,0.348,1.14,28.6,0.107,0.057,0.079,25.0,0.750,0.776,0.253,0.251,97.00,93.81,78.18,69,0.154
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3545,21000475,1610612757,POR,Portland,201988,Patty Mills,NaN,NaN,14:49,63.1,56.3,109.7,110.3,-46.6,-54.1,0.667,0.00,22.2,0.000,0.111,0.037,0.0,0.143,0.143,0.206,0.237,93.40,98.77,82.31,32,-0.073
3546,21000475,1610612757,POR,Portland,1752,Sean Marks,NaN,NaN,6:35,59.5,53.8,124.2,115.4,-64.6,-61.5,0.000,0.00,0.0,0.111,0.000,0.077,50.0,0.000,0.000,0.143,0.157,86.91,94.78,78.99,13,-0.429
3547,21000475,1610612757,POR,Portland,202356,Armon Johnson,NaN,NaN,1:10,0.0,0.0,215.5,166.7,-215.5,-166.7,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,86.40,123.43,102.86,3,0.000
3548,21000475,1610612757,POR,Portland,202337,Luke Babbitt,NaN,NaN,1:10,0.0,0.0,215.5,166.7,-215.5,-166.7,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.667,1.064,86.40,123.43,102.86,3,-0.857
3549,21000475,1610612757,POR,Portland,200750,Brandon Roy,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0,NaN

In [48]:
datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)

datapath_df = os.path.join(datapath, '5boxscoreadvancedv2_2006_2018.csv')
if not os.path.exists(datapath_df):
    df_empty.to_csv(datapath_df, index=False)