In [1]:
'''from IPython.core.display import display, HTML
display(HTML("<style>.container { width:90% !important; }</style>"))'''

'from IPython.core.display import display, HTML\ndisplay(HTML("<style>.container { width:90% !important; }</style>"))'

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os


pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

In [3]:
#return the first 5 and last 5 rows of this dataframe
def p(df_):
    if df_.shape[0] > 6:
        print(df_.shape)
        return pd.concat([df_.head(), df_.tail()])
    else:
        return df_

def rcp(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'processed_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'processed_data', file_), parse_dates=pd_)
    
def rcr(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'raw_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'raw_data', file_), parse_dates=pd_)

In [4]:
os.getcwd()

'/Users/pauljacob/Documents/GitHub/DSCapstone2/02_Data_Wrangling'

In [5]:
os.listdir()

['csvoutput_02_data_wrangling_6injuries_2010_11_player_replace_v1-Copy1.ipynb',
 'csvoutput_02_data_wrangling_0team_id_abbreviation_df.ipynb',
 'Untitled1.ipynb',
 'csvoutput_02_data_wrangling_6injuries_2011_12_date_range_check.ipynb',
 '.DS_Store',
 'csvoutput_02_data_wrangling_13player_id_player.ipynb',
 '02_data_wrangling_game_id_player_name_advanced_stats_api_calls_100_cuts.ipynb',
 'csvoutput_02_data_wrangling_6injuries_2010_11_player_replace_v2.ipynb',
 'Untitled3.ipynb',
 'csvoutput_02_data_wrangling_19boxscoreadvancedv2_team_2010_2018.ipynb',
 'xxx02_data_wrangling_nba_api_player_inactive_games_check.ipynb',
 'Untitled.ipynb',
 'Untitled4.ipynb',
 'csvoutput_02_data_wrangling_3game_id_game_date_home_away_V2.ipynb',
 'csvoutput_02_data_wrangling_10team_id_season_team.ipynb',
 'csvoutput_02_data_wrangling_18game_id_team_id_home_away.ipynb',
 'csvoutput_02_data_wrangling_4game_id_team_stats_betting_totals_spreads_money_line.ipynb',
 '02_data_wrangling_contribution_lost_injury_inactive_Q.ipynb',
 'Untitled2.ipynb',
 'trash',
 'csvoutput_02_data_wrangling_6injuries_2010_11_player_replace_v1.ipynb',
 'sqlitetask3-Copy1.ipynb',
 'csvoutput_02_data_wrangling_2game_id_game_date.ipynb',
 'csvoutput_02_data_wrangling_6date_team_id_player_name_A_v3.ipynb',
 'csvoutput_02_data_wrangling_8_franchise_start_end.ipynb',
 'csvoutput_02_data_wrangling_6injuries_2010_11_player_replace_v1_clean_up.ipynb',
 'csvoutput_02_data_wrangling_21boxscoreadvancedv2_boxscores_team_away_home_2010_2018.ipynb',
 'csvoutput_02_data_wrangling_15game_date_game_id_team_id_season_player_id_player.ipynb',
 'csvoutput_02_data_wrangling_20boxscoreadvancedv2_team_away_home_2010_2018.ipynb',
 '02_data_wrangling_v2.ipynb',
 '02_data_wrangling_temp.ipynb',
 'csvoutput_02_data_wrangling_5boxscoreadvancedv2_2006_2018.ipynb',
 '.ipynb_checkpoints',
 'csvoutput_02_data_wrangling_14player_id_player_team_id_season_team.ipynb',
 'csvoutput_02_data_wrangling_6team_id_abbreviation_nickname.ipynb',
 '02_data_wrangling_contribution_lost_injury_inactive.ipynb',
 '02_data_wrangling_team_stats_api_calls_1000_cuts.ipynb',
 'archived',
 'csvoutput_02_data_wrangling_7season_first_game_date_last_game_date.ipynb',
 'csvoutput_02_data_wrangling_5boxscoreadvancedv2_2009_2018.ipynb',
 'nba_api',
 'csvoutput_02_data_wrangling_6date_team_id_player_name_A_v4.ipynb',
 '02_data_wrangling_contribution_lost_injury_inactive_v7.ipynb',
 '02_data_wrangling.ipynb',
 'basketball.sqlite',
 'csvoutput_02_data_wrangling_3game_id_game_date_home_away.ipynb']

In [6]:
listtt = os.listdir(os.path.join('..', 'processed_data_preliminary'))
listtt.remove('.DS_Store')
listtt

['5game_id_team_id_advanced_stats5880.csv',
 '5game_id_team_id_advanced_stats6345.csv',
 '5game_id_team_id_advanced_stats8340.csv',
 '5game_id_team_id_advanced_stats5670.csv',
 '5game_id_team_id_player_name_advanced_stats3175.csv',
 '5game_id_team_id_advanced_stats14805.csv',
 '5game_id_team_id_advanced_stats11955.csv',
 '5game_id_team_id_advanced_stats13830.csv',
 '5game_id_team_id_advanced_stats12045.csv',
 '5game_id_team_id_player_name_advanced_stats13831.csv',
 '5game_id_team_id_advanced_stats3765.csv',
 '5game_id_team_id_advanced_stats10875.csv',
 '5game_id_team_id_advanced_stats2490.csv',
 '5game_id_team_id_advanced_stats14385.csv',
 '5game_id_team_id_advanced_stats405.csv',
 '5game_id_team_id_advanced_stats13575.csv',
 '5game_id_team_id_player_name_advanced_stats13979.csv',
 '5game_id_team_id_advanced_stats9300.csv',
 '5game_id_team_id_advanced_stats7305.csv',
 '5game_id_team_id_player_name_advanced_stats1399.csv',
 '5game_id_team_id_advanced_stats12870.csv',
 '5game_id_team_id_advanced_stats11160.csv',
 '5game_id_team_id_advanced_stats6225.csv',
 '5game_id_team_id_advanced_stats13005.csv',
 '5game_id_team_id_advanced_stats10530.csv',
 '5game_id_team_id_advanced_stats3375.csv',
 '5game_id_team_id_advanced_stats8220.csv',
 '5game_id_team_id_player_name_advanced_stats3767.csv',
 '5game_id_team_id_advanced_stats13950.csv',
 '5game_id_team_id_advanced_stats11835.csv',
 '5game_id_team_id_player_name_advanced_stats807.csv',
 '5game_id_team_id_advanced_stats11820.csv',
 '5game_id_team_id_advanced_stats14970.csv',
 '5game_id_team_id_player_name_advanced_stats9539.csv',
 '5game_id_team_id_advanced_stats30.csv',
 '5game_id_team_id_advanced_stats3360.csv',
 '5game_id_team_id_advanced_stats14025.csv',
 '5game_id_team_id_advanced_stats8235.csv',
 '5game_id_team_id_advanced_stats7890.csv',
 '5game_id_team_id_advanced_stats2730.csv',
 '5game_id_team_id_advanced_stats11175.csv',
 '5game_id_team_id_advanced_stats570.csv',
 '5game_id_team_id_advanced_stats8745.csv',
 '5game_id_team_id_advanced_stats13560.csv',
 '5game_id_team_id_advanced_stats15105.csv',
 '5game_id_team_id_advanced_stats9315.csv',
 '5game_id_team_id_advanced_stats10860.csv',
 '5game_id_team_id_advanced_stats8625.csv',
 '5game_id_team_id_advanced_stats11565.csv',
 '5game_id_team_id_advanced_stats11940.csv',
 '5game_id_team_id_advanced_stats12285.csv',
 '5game_id_team_id_advanced_stats4590.csv',
 '5game_id_team_id_advanced_stats8355.csv',
 '5game_id_team_id_advanced_stats14145.csv',
 '5game_id_team_id_advanced_stats1365.csv',
 '5game_id_team_id_advanced_stats13170.csv',
 '5game_id_team_id_advanced_stats5895.csv',
 '5game_id_team_id_advanced_stats9705.csv',
 '5game_id_team_id_advanced_stats9075.csv',
 '5game_id_team_id_advanced_stats6420.csv',
 '5game_id_team_id_advanced_stats4545.csv',
 '5game_id_team_id_advanced_stats5115.csv',
 '5game_id_team_id_advanced_stats3570.csv',
 '5game_id_team_id_advanced_stats10335.csv',
 '5game_id_team_id_advanced_stats2685.csv',
 '5game_id_team_id_player_name_advanced_stats1991.csv',
 '5game_id_team_id_advanced_stats14190.csv',
 '5game_id_team_id_advanced_stats4035.csv',
 '5game_id_team_id_advanced_stats6150.csv',
 '5game_id_team_id_advanced_stats7500.csv',
 '5game_id_team_id_advanced_stats3000.csv',
 '5game_id_team_id_advanced_stats12720.csv',
 '5game_id_team_id_advanced_stats1830.csv',
 '5game_id_team_id_advanced_stats360.csv',
 '5game_id_team_id_advanced_stats9465.csv',
 '5game_id_team_id_advanced_stats6030.csv',
 '5game_id_team_id_advanced_stats4155.csv',
 '5game_id_team_id_advanced_stats1005.csv',
 '5game_id_team_id_advanced_stats5505.csv',
 '5game_id_team_id_advanced_stats10725.csv',
 '5game_id_team_id_advanced_stats6795.csv',
 '5game_id_team_id_advanced_stats2295.csv',
 '5game_id_team_id_advanced_stats1950.csv',
 '5game_id_team_id_player_name_advanced_stats8355.csv',
 '5game_id_team_id_advanced_stats4800.csv',
 '5game_id_team_id_advanced_stats10080.csv',
 '5game_id_team_id_advanced_stats14580.csv',
 '5game_id_team_id_advanced_stats8790.csv',
 '5game_id_team_id_advanced_stats4425.csv',
 '5game_id_team_id_advanced_stats6540.csv',
 '5game_id_team_id_advanced_stats2040.csv',
 '5game_id_team_id_advanced_stats7110.csv',
 '5game_id_team_id_advanced_stats12330.csv',
 '5game_id_team_id_advanced_stats1575.csv',
 '5game_id_team_id_advanced_stats4380.csv',
 '5game_id_team_id_advanced_stats7845.csv',
 '5game_id_team_id_player_name_advanced_stats13239.csv',
 '5game_id_team_id_advanced_stats9840.csv',
 '5game_id_team_id_advanced_stats12495.csv',
 '5game_id_team_id_advanced_stats765.csv',
 '5game_id_team_id_advanced_stats9855.csv',
 '5game_id_team_id_advanced_stats12480.csv',
 '5game_id_team_id_advanced_stats4395.csv',
 '5game_id_team_id_advanced_stats8550.csv',
 '5game_id_team_id_advanced_stats3405.csv',
 '5game_id_team_id_advanced_stats1560.csv',
 '5game_id_team_id_advanced_stats2055.csv',
 '5game_id_team_id_advanced_stats11610.csv',
 '5game_id_team_id_advanced_stats6555.csv',
 '5game_id_team_id_advanced_stats4815.csv',
 '5game_id_team_id_advanced_stats14595.csv',
 '5game_id_team_id_advanced_stats10095.csv',
 '5game_id_team_id_advanced_stats2280.csv',
 '5game_id_team_id_advanced_stats6780.csv',
 '5game_id_team_id_player_name_advanced_stats11611.csv',
 '5game_id_team_id_player_name_advanced_stats15311.csv',
 '5game_id_team_id_advanced_stats4140.csv',
 '5game_id_team_id_advanced_stats375.csv',
 '5game_id_team_id_player_name_advanced_stats2731.csv',
 '5game_id_team_id_advanced_stats6810.csv',
 '5game_id_team_id_advanced_stats12090.csv',
 '5game_id_team_id_player_name_advanced_stats11759.csv',
 '5game_id_team_id_advanced_stats4785.csv',
 '5game_id_team_id_advanced_stats3015.csv',
 '5game_id_team_id_advanced_stats7515.csv',
 '5game_id_team_id_advanced_stats10650.csv',
 '5game_id_team_id_advanced_stats1170.csv',
 '5game_id_team_id_advanced_stats12735.csv',
 '5game_id_team_id_advanced_stats13365.csv',
 '5game_id_team_id_advanced_stats4020.csv',
 '5game_id_team_id_advanced_stats2445.csv',
 '5game_id_team_id_advanced_stats9510.csv',
 '5game_id_team_id_advanced_stats10485.csv',
 '5game_id_team_id_player_name_advanced_stats14423.csv',
 '5game_id_team_id_advanced_stats6390.csv',
 '5game_id_team_id_advanced_stats5100.csv',
 '5game_id_team_id_advanced_stats7065.csv',
 '5game_id_team_id_advanced_stats10320.csv',
 '5game_id_team_id_advanced_stats8430.csv',
 '5game_id_team_id_advanced_stats6435.csv',
 '5game_id_team_id_player_name_advanced_stats4803.csv',
 '5game_id_team_id_advanced_stats9060.csv',
 '5game_id_team_id_advanced_stats15270.csv',
 '5game_id_team_id_advanced_stats12255.csv',
 '5game_id_team_id_advanced_stats1410.csv',
 '5game_id_team_id_advanced_stats11760.csv',
 '5game_id_team_id_advanced_stats13605.csv',
 '5game_id_team_id_advanced_stats8385.csv',
 '5game_id_team_id_advanced_stats615.csv',
 '5game_id_team_id_advanced_stats7920.csv',
 '5game_id_team_id_player_name_advanced_stats7467.csv',
 '5game_id_team_id_advanced_stats14340.csv',
 '5game_id_team_id_advanced_stats5460.csv',
 '5game_id_team_id_player_name_advanced_stats5099.csv',
 '5game_id_team_id_advanced_stats4965.csv',
 '5game_id_team_id_advanced_stats8805.csv',
 '5game_id_team_id_advanced_stats12645.csv',
 '5game_id_team_id_advanced_stats3165.csv',
 '5game_id_team_id_advanced_stats14220.csv',
 '5game_id_team_id_advanced_stats11370.csv',
 '5game_id_team_id_advanced_stats2535.csv',
 '5game_id_team_id_advanced_stats13215.csv',
 '5game_id_team_id_advanced_stats6960.csv',
 '5game_id_team_id_player_name_advanced_stats10279.csv',
 '5game_id_team_id_player_name_advanced_stats11167.csv',
 '5game_id_team_id_advanced_stats13995.csv',
 '5game_id_team_id_advanced_stats5070.csv',
 '5game_id_team_id_advanced_stats15300.csv',
 '5game_id_team_id_advanced_stats2910.csv',
 '5game_id_team_id_advanced_stats5925.csv',
 '5game_id_team_id_advanced_stats990.csv',
 '5game_id_team_id_advanced_stats13770.csv',
 '5game_id_team_id_advanced_stats15315.csv',
 '5game_id_team_id_advanced_stats9105.csv',
 '5game_id_team_id_advanced_stats10245.csv',
 '5game_id_team_id_advanced_stats14745.csv',
 '5game_id_team_id_advanced_stats13980.csv',
 '5game_id_team_id_advanced_stats3825.csv',
 '5game_id_team_id_advanced_stats8970.csv',
 '5game_id_team_id_advanced_stats210.csv',
 '5game_id_team_id_advanced_stats6975.csv',
 '5game_id_team_id_advanced_stats2520.csv',
 '5game_id_team_id_advanced_stats13200.csv',
 '5game_id_team_id_advanced_stats14235.csv',
 '5game_id_team_id_advanced_stats8025.csv',
 '5game_id_team_id_advanced_stats7470.csv',
 '5game_id_team_id_advanced_stats3945.csv',
 '5game_id_team_id_advanced_stats11205.csv',
 '5game_id_team_id_advanced_stats8145.csv',
 '5game_id_team_id_advanced_stats14355.csv',
 '5game_id_team_id_advanced_stats5475.csv',
 '5game_id_team_id_advanced_stats7935.csv',
 '5game_id_team_id_advanced_stats5850.csv',
 '5game_id_team_id_advanced_stats9930.csv',
 '5game_id_team_id_advanced_stats600.csv',
 '5game_id_team_id_advanced_stats2865.csv',
 '5game_id_team_id_advanced_stats2130.csv',
 '5game_id_team_id_advanced_stats11775.csv',
 '5game_id_team_id_player_name_advanced_stats.csv',
 '5game_id_team_id_advanced_stats12240.csv',
 '5game_id_team_id_advanced_stats14625.csv',
 '5game_id_team_id_advanced_stats11985.csv',
 '5game_id_team_id_player_name_advanced_stats2287.csv',
 '5game_id_team_id_advanced_stats7710.csv',
 '5game_id_team_id_advanced_stats10455.csv',
 '5game_id_team_id_advanced_stats3210.csv',
 '5game_id_team_id_player_name_advanced_stats10871.csv',
 '5game_id_team_id_advanced_stats2640.csv',
 '5game_id_team_id_advanced_stats825.csv',
 '5game_id_team_id_player_name_advanced_stats12055.csv',
 '5game_id_team_id_advanced_stats1605.csv',
 '5game_id_team_id_advanced_stats7260.csv',
 '5game_id_team_id_advanced_stats10125.csv',
 '5game_id_team_id_advanced_stats15075.csv',
 '5game_id_team_id_advanced_stats3990.csv',
 '5game_id_team_id_advanced_stats6630.csv',
 '5game_id_team_id_advanced_stats13410.csv',
 '5game_id_team_id_advanced_stats4755.csv',
 '5game_id_team_id_advanced_stats10680.csv',
 '5game_id_team_id_advanced_stats8190.csv',
 '5game_id_team_id_advanced_stats6195.csv',
 '5game_id_team_id_advanced_stats12915.csv',
 '5game_id_team_id_advanced_stats3600.csv',
 '5game_id_team_id_advanced_stats5265.csv',
 '5game_id_team_id_advanced_stats12120.csv',
 '5game_id_team_id_advanced_stats1995.csv',
 '5game_id_team_id_advanced_stats4635.csv',
 '5game_id_team_id_advanced_stats11415.csv',
 '5game_id_team_id_advanced_stats6750.csv',
 '5game_id_team_id_advanced_stats2250.csv',
 '5game_id_team_id_advanced_stats1215.csv',
 '5game_id_team_id_advanced_stats5715.csv',
 '5game_id_team_id_advanced_stats12450.csv',
 '5game_id_team_id_advanced_stats9885.csv',
 '5game_id_team_id_advanced_stats9675.csv',
 '5game_id_team_id_advanced_stats15465.csv',
 '5game_id_team_id_advanced_stats945.csv',
 '5game_id_team_id_advanced_stats10290.csv',
 '5game_id_team_id_player_name_advanced_stats12647.csv',
 '5game_id_team_id_advanced_stats14790.csv',
 '5game_id_team_id_advanced_stats8580.csv',
 '5game_id_team_id_advanced_stats6585.csv',
 '5game_id_team_id_advanced_stats2085.csv',
 '5game_id_team_id_player_name_advanced_stats10723.csv',
 '5game_id_team_id_advanced_stats8595.csv',
 '5game_id_team_id_advanced_stats9660.csv',
 '5game_id_team_id_advanced_stats4350.csv',
 '5game_id_team_id_advanced_stats5700.csv',
 '5game_id_team_id_advanced_stats1200.csv',
 '5game_id_team_id_advanced_stats7665.csv',
 '5game_id_team_id_advanced_stats4185.csv',
 '5game_id_team_id_advanced_stats10905.csv',
 '5game_id_team_id_player_name_advanced_stats6431.csv',
 '5game_id_team_id_advanced_stats12690.csv',
 '5game_id_team_id_player_name_advanced_stats15459.csv',
 '5game_id_team_id_advanced_stats1980.csv',
 '5game_id_team_id_advanced_stats4620.csv',
 '5game_id_team_id_advanced_stats11400.csv',
 '5game_id_team_id_advanced_stats3615.csv',
 '5game_id_team_id_advanced_stats14550.csv',
 '5game_id_team_id_advanced_stats10050.csv',
 '5game_id_team_id_advanced_stats1770.csv',
 '5game_id_team_id_advanced_stats12135.csv',
 '5game_id_team_id_player_name_advanced_stats6579.csv',
 '5game_id_team_id_advanced_stats6180.csv',
 '5game_id_team_id_advanced_stats12900.csv',
 '5game_id_team_id_advanced_stats10695.csv',
 '5game_id_team_id_advanced_stats9270.csv',
 '5game_id_team_id_advanced_stats15060.csv',
 '5game_id_team_id_advanced_stats2325.csv',
 '5game_id_team_id_advanced_stats4740.csv',
 '5game_id_team_id_advanced_stats5310.csv',
 '5game_id_team_id_advanced_stats7275.csv',
 '5game_id_team_id_advanced_stats14430.csv',
 '5game_id_team_id_advanced_stats165.csv',
 '5game_id_team_id_player_name_advanced_stats10131.csv',
 '5game_id_team_id_advanced_stats4230.csv',
 '5game_id_team_id_advanced_stats15510.csv',
 '5game_id_team_id_advanced_stats2655.csv',
 '5game_id_team_id_advanced_stats11010.csv',
 '5game_id_team_id_advanced_stats10440.csv',
 '5game_id_team_id_advanced_stats12525.csv',
 '5game_id_team_id_advanced_stats9015.csv',
 '5game_id_team_id_advanced_stats8445.csv',
 '5game_id_team_id_advanced_stats14655.csv',
 '5game_id_team_id_advanced_stats3510.csv',
 '5game_id_team_id_advanced_stats13890.csv',
 '5game_id_team_id_advanced_stats5175.csv',
 '5game_id_team_id_advanced_stats5820.csv',
 '5game_id_team_id_advanced_stats2430.csv',
 '5game_id_team_id_player_name_advanced_stats14867.csv',
 '5game_id_team_id_advanced_stats7560.csv',
 '5game_id_team_id_advanced_stats14325.csv',
 '5game_id_team_id_advanced_stats3060.csv',
 '5game_id_team_id_advanced_stats300.csv',
 '5game_id_team_id_advanced_stats2550.csv',
 '5game_id_team_id_advanced_stats9405.csv',
 '5game_id_team_id_advanced_stats8055.csv',
 '5game_id_team_id_advanced_stats1065.csv',
 '5game_id_team_id_advanced_stats5565.csv',
 '5game_id_team_id_advanced_stats3855.csv',
 '5game_id_team_id_player_name_advanced_stats12351.csv',
 '5game_id_team_id_advanced_stats4860.csv',
 '5game_id_team_id_advanced_stats1515.csv',
 '5game_id_team_id_advanced_stats7170.csv',
 '5game_id_team_id_advanced_stats11895.csv',
 '5game_id_team_id_player_name_advanced_stats8651.csv',
 '5game_id_team_id_advanced_stats6285.csv',
 '5game_id_team_id_advanced_stats5940.csv',
 '5game_id_team_id_advanced_stats8280.csv',
 '5game_id_team_id_advanced_stats10590.csv',
 '5game_id_team_id_advanced_stats705.csv',
 '5game_id_team_id_advanced_stats14085.csv',
 '5game_id_team_id_advanced_stats8295.csv',
 '5game_id_team_id_player_name_advanced_stats11315.csv',
 '5game_id_team_id_advanced_stats7830.csv',
 '5game_id_team_id_advanced_stats2790.csv',
 '5game_id_team_id_advanced_stats5955.csv',
 '5game_id_team_id_advanced_stats1500.csv',
 '5game_id_team_id_advanced_stats12345.csv',
 '5game_id_team_id_advanced_stats3465.csv',
 '5game_id_team_id_advanced_stats11880.csv',
 '5game_id_team_id_advanced_stats11670.csv',
 '5game_id_team_id_advanced_stats90.csv',
 '5game_id_team_id_advanced_stats4875.csv',
 '5game_id_team_id_advanced_stats3840.csv',
 '5game_id_team_id_advanced_stats8040.csv',
 '5game_id_team_id_advanced_stats14250.csv',
 '5game_id_team_id_advanced_stats6045.csv',
 '5game_id_team_id_player_name_advanced_stats10427.csv',
 '5game_id_team_id_player_name_advanced_stats14127.csv',
 '5game_id_team_id_advanced_stats315.csv',
 '5game_id_team_id_advanced_stats8685.csv',
 '5game_id_team_id_advanced_stats6870.csv',
 '5game_id_team_id_player_name_advanced_stats7615.csv',
 '5game_id_team_id_advanced_stats1845.csv',
 '5game_id_team_id_advanced_stats1110.csv',
 '5game_id_team_id_advanced_stats3075.csv',
 '5game_id_team_id_advanced_stats7575.csv',
 '5game_id_team_id_advanced_stats9570.csv',
 '5game_id_team_id_advanced_stats13305.csv',
 '5game_id_team_id_advanced_stats5835.csv',
 '5game_id_team_id_advanced_stats7950.csv',
 '5game_id_team_id_advanced_stats7005.csv',
 '5game_id_team_id_advanced_stats14640.csv',
 '5game_id_team_id_advanced_stats12225.csv',
 '5game_id_team_id_advanced_stats5160.csv',
 '5game_id_team_id_advanced_stats4530.csv',
 '5game_id_team_id_advanced_stats15210.csv',
 '5game_id_team_id_advanced_stats9000.csv',
 '5game_id_team_id_advanced_stats840.csv',
 '5game_id_team_id_advanced_stats2625.csv',
 '5game_id_team_id_advanced_stats12555.csv',
 '5game_id_team_id_player_name_advanced_stats12795.csv',
 '5game_id_team_id_advanced_stats5610.csv',
 '5game_id_team_id_advanced_stats14130.csv',
 '5game_id_team_id_advanced_stats14865.csv',
 '5game_id_team_id_advanced_stats6480.csv',
 '5game_id_team_id_advanced_stats10395.csv',
 '5game_id_team_id_advanced_stats1890.csv',
 '5game_id_team_id_player_name_advanced_stats9835.csv',
 '5game_id_team_id_advanced_stats2355.csv',
 '5game_id_team_id_advanced_stats10140.csv',
 '5game_id_team_id_advanced_stats3705.csv',
 '5game_id_team_id_advanced_stats4095.csv',
 '5game_id_team_id_player_name_advanced_stats7171.csv',
 '5game_id_team_id_advanced_stats10815.csv',
 '5game_id_team_id_player_name_advanced_stats3471.csv',
 '5game_id_team_id_advanced_stats465.csv',
 '5game_id_team_id_advanced_stats12780.csv',
 '5game_id_team_id_advanced_stats9360.csv',
 '5game_id_team_id_advanced_stats2235.csv',
 '5game_id_team_id_advanced_stats6735.csv',
 '5game_id_team_id_advanced_stats4650.csv',
 '5game_id_team_id_advanced_stats13515.csv',
 '5game_id_team_id_advanced_stats14520.csv',
 '5game_id_team_id_advanced_stats8730.csv',
 '5game_id_team_id_advanced_stats10020.csv',
 '5game_id_team_id_advanced_stats7365.csv',
 '5game_id_team_id_advanced_stats6090.csv',
 '5game_id_team_id_advanced_stats12810.csv',
 '5game_id_team_id_player_name_advanced_stats7763.csv',
 '5game_id_team_id_advanced_stats10785.csv',
 '5game_id_team_id_advanced_stats4320.csv',
 '5game_id_team_id_advanced_stats13065.csv',
 '5game_id_team_id_advanced_stats11100.csv',
 '5game_id_team_id_advanced_stats2745.csv',
 '5game_id_team_id_advanced_stats3315.csv',
 '5game_id_team_id_advanced_stats12435.csv',
 '5game_id_team_id_advanced_stats45.csv',
 '5game_id_team_id_advanced_stats4485.csv',
 '5game_id_team_id_advanced_stats12390.csv',
 '5game_id_team_id_advanced_stats14910.csv',
 '5game_id_team_id_advanced_stats3300.csv',
 '5game_id_team_id_advanced_stats10545.csv',
 '5game_id_team_id_advanced_stats12420.csv',
 '5game_id_team_id_advanced_stats4335.csv',
 '5game_id_team_id_advanced_stats11115.csv',
 '5game_id_team_id_advanced_stats510.csv',
 '5game_id_team_id_player_name_advanced_stats9983.csv',
 '5game_id_team_id_advanced_stats12150.csv',
 '5game_id_team_id_advanced_stats10035.csv',
 '5game_id_team_id_advanced_stats14535.csv',
 '5game_id_team_id_advanced_stats6720.csv',
 '5game_id_team_id_advanced_stats9375.csv',
 '5game_id_team_id_advanced_stats2220.csv',
 '5game_id_team_id_advanced_stats15165.csv',
 '5game_id_team_id_advanced_stats13500.csv',
 '5game_id_team_id_advanced_stats12795.csv',
 '5game_id_team_id_advanced_stats4080.csv',
 '5game_id_team_id_advanced_stats10800.csv',
 '5game_id_team_id_advanced_stats10155.csv',
 '5game_id_team_id_advanced_stats12030.csv',
 '5game_id_team_id_advanced_stats4725.csv',
 '5game_id_team_id_advanced_stats2340.csv',
 '5game_id_team_id_advanced_stats11505.csv',
 '5game_id_team_id_advanced_stats13845.csv',
 '5game_id_team_id_advanced_stats0.csv',
 '5game_id_team_id_advanced_stats8490.csv',
 '5game_id_team_id_advanced_stats10380.csv',
 '5game_id_team_id_advanced_stats6495.csv',
 '5game_id_team_id_advanced_stats12540.csv',
 '5game_id_team_id_advanced_stats1305.csv',
 '5game_id_team_id_advanced_stats10425.csv',
 '5game_id_team_id_advanced_stats6330.csv',
 '5game_id_team_id_advanced_stats9765.csv',
 '5game_id_team_id_advanced_stats855.csv',
 '5game_id_team_id_advanced_stats13110.csv',
 '5game_id_team_id_player_name_advanced_stats2583.csv',
 '5game_id_team_id_advanced_stats7770.csv',
 '5game_id_team_id_advanced_stats3270.csv',
 '5game_id_team_id_advanced_stats8325.csv',
 '5game_id_team_id_advanced_stats7980.csv',
 '5game_id_team_id_advanced_stats4245.csv',
 '5game_id_team_id_advanced_stats8655.csv',
 '5game_id_team_id_advanced_stats14445.csv',
 '5game_id_team_id_advanced_stats7200.csv',
 '5game_id_team_id_advanced_stats1665.csv',
 '5game_id_team_id_advanced_stats13470.csv',

In [7]:
listttt = [k for k in listtt if 'player_name' not in k]
listttt

['5game_id_team_id_advanced_stats5880.csv',
 '5game_id_team_id_advanced_stats6345.csv',
 '5game_id_team_id_advanced_stats8340.csv',
 '5game_id_team_id_advanced_stats5670.csv',
 '5game_id_team_id_advanced_stats14805.csv',
 '5game_id_team_id_advanced_stats11955.csv',
 '5game_id_team_id_advanced_stats13830.csv',
 '5game_id_team_id_advanced_stats12045.csv',
 '5game_id_team_id_advanced_stats3765.csv',
 '5game_id_team_id_advanced_stats10875.csv',
 '5game_id_team_id_advanced_stats2490.csv',
 '5game_id_team_id_advanced_stats14385.csv',
 '5game_id_team_id_advanced_stats405.csv',
 '5game_id_team_id_advanced_stats13575.csv',
 '5game_id_team_id_advanced_stats9300.csv',
 '5game_id_team_id_advanced_stats7305.csv',
 '5game_id_team_id_advanced_stats12870.csv',
 '5game_id_team_id_advanced_stats11160.csv',
 '5game_id_team_id_advanced_stats6225.csv',
 '5game_id_team_id_advanced_stats13005.csv',
 '5game_id_team_id_advanced_stats10530.csv',
 '5game_id_team_id_advanced_stats3375.csv',
 '5game_id_team_id_advanced_stats8220.csv',
 '5game_id_team_id_advanced_stats13950.csv',
 '5game_id_team_id_advanced_stats11835.csv',
 '5game_id_team_id_advanced_stats11820.csv',
 '5game_id_team_id_advanced_stats14970.csv',
 '5game_id_team_id_advanced_stats30.csv',
 '5game_id_team_id_advanced_stats3360.csv',
 '5game_id_team_id_advanced_stats14025.csv',
 '5game_id_team_id_advanced_stats8235.csv',
 '5game_id_team_id_advanced_stats7890.csv',
 '5game_id_team_id_advanced_stats2730.csv',
 '5game_id_team_id_advanced_stats11175.csv',
 '5game_id_team_id_advanced_stats570.csv',
 '5game_id_team_id_advanced_stats8745.csv',
 '5game_id_team_id_advanced_stats13560.csv',
 '5game_id_team_id_advanced_stats15105.csv',
 '5game_id_team_id_advanced_stats9315.csv',
 '5game_id_team_id_advanced_stats10860.csv',
 '5game_id_team_id_advanced_stats8625.csv',
 '5game_id_team_id_advanced_stats11565.csv',
 '5game_id_team_id_advanced_stats11940.csv',
 '5game_id_team_id_advanced_stats12285.csv',
 '5game_id_team_id_advanced_stats4590.csv',
 '5game_id_team_id_advanced_stats8355.csv',
 '5game_id_team_id_advanced_stats14145.csv',
 '5game_id_team_id_advanced_stats1365.csv',
 '5game_id_team_id_advanced_stats13170.csv',
 '5game_id_team_id_advanced_stats5895.csv',
 '5game_id_team_id_advanced_stats9705.csv',
 '5game_id_team_id_advanced_stats9075.csv',
 '5game_id_team_id_advanced_stats6420.csv',
 '5game_id_team_id_advanced_stats4545.csv',
 '5game_id_team_id_advanced_stats5115.csv',
 '5game_id_team_id_advanced_stats3570.csv',
 '5game_id_team_id_advanced_stats10335.csv',
 '5game_id_team_id_advanced_stats2685.csv',
 '5game_id_team_id_advanced_stats14190.csv',
 '5game_id_team_id_advanced_stats4035.csv',
 '5game_id_team_id_advanced_stats6150.csv',
 '5game_id_team_id_advanced_stats7500.csv',
 '5game_id_team_id_advanced_stats3000.csv',
 '5game_id_team_id_advanced_stats12720.csv',
 '5game_id_team_id_advanced_stats1830.csv',
 '5game_id_team_id_advanced_stats360.csv',
 '5game_id_team_id_advanced_stats9465.csv',
 '5game_id_team_id_advanced_stats6030.csv',
 '5game_id_team_id_advanced_stats4155.csv',
 '5game_id_team_id_advanced_stats1005.csv',
 '5game_id_team_id_advanced_stats5505.csv',
 '5game_id_team_id_advanced_stats10725.csv',
 '5game_id_team_id_advanced_stats6795.csv',
 '5game_id_team_id_advanced_stats2295.csv',
 '5game_id_team_id_advanced_stats1950.csv',
 '5game_id_team_id_advanced_stats4800.csv',
 '5game_id_team_id_advanced_stats10080.csv',
 '5game_id_team_id_advanced_stats14580.csv',
 '5game_id_team_id_advanced_stats8790.csv',
 '5game_id_team_id_advanced_stats4425.csv',
 '5game_id_team_id_advanced_stats6540.csv',
 '5game_id_team_id_advanced_stats2040.csv',
 '5game_id_team_id_advanced_stats7110.csv',
 '5game_id_team_id_advanced_stats12330.csv',
 '5game_id_team_id_advanced_stats1575.csv',
 '5game_id_team_id_advanced_stats4380.csv',
 '5game_id_team_id_advanced_stats7845.csv',
 '5game_id_team_id_advanced_stats9840.csv',
 '5game_id_team_id_advanced_stats12495.csv',
 '5game_id_team_id_advanced_stats765.csv',
 '5game_id_team_id_advanced_stats9855.csv',
 '5game_id_team_id_advanced_stats12480.csv',
 '5game_id_team_id_advanced_stats4395.csv',
 '5game_id_team_id_advanced_stats8550.csv',
 '5game_id_team_id_advanced_stats3405.csv',
 '5game_id_team_id_advanced_stats1560.csv',
 '5game_id_team_id_advanced_stats2055.csv',
 '5game_id_team_id_advanced_stats11610.csv',
 '5game_id_team_id_advanced_stats6555.csv',
 '5game_id_team_id_advanced_stats4815.csv',
 '5game_id_team_id_advanced_stats14595.csv',
 '5game_id_team_id_advanced_stats10095.csv',
 '5game_id_team_id_advanced_stats2280.csv',
 '5game_id_team_id_advanced_stats6780.csv',
 '5game_id_team_id_advanced_stats4140.csv',
 '5game_id_team_id_advanced_stats375.csv',
 '5game_id_team_id_advanced_stats6810.csv',
 '5game_id_team_id_advanced_stats12090.csv',
 '5game_id_team_id_advanced_stats4785.csv',
 '5game_id_team_id_advanced_stats3015.csv',
 '5game_id_team_id_advanced_stats7515.csv',
 '5game_id_team_id_advanced_stats10650.csv',
 '5game_id_team_id_advanced_stats1170.csv',
 '5game_id_team_id_advanced_stats12735.csv',
 '5game_id_team_id_advanced_stats13365.csv',
 '5game_id_team_id_advanced_stats4020.csv',
 '5game_id_team_id_advanced_stats2445.csv',
 '5game_id_team_id_advanced_stats9510.csv',
 '5game_id_team_id_advanced_stats10485.csv',
 '5game_id_team_id_advanced_stats6390.csv',
 '5game_id_team_id_advanced_stats5100.csv',
 '5game_id_team_id_advanced_stats7065.csv',
 '5game_id_team_id_advanced_stats10320.csv',
 '5game_id_team_id_advanced_stats8430.csv',
 '5game_id_team_id_advanced_stats6435.csv',
 '5game_id_team_id_advanced_stats9060.csv',
 '5game_id_team_id_advanced_stats15270.csv',
 '5game_id_team_id_advanced_stats12255.csv',
 '5game_id_team_id_advanced_stats1410.csv',
 '5game_id_team_id_advanced_stats11760.csv',
 '5game_id_team_id_advanced_stats13605.csv',
 '5game_id_team_id_advanced_stats8385.csv',
 '5game_id_team_id_advanced_stats615.csv',
 '5game_id_team_id_advanced_stats7920.csv',
 '5game_id_team_id_advanced_stats14340.csv',
 '5game_id_team_id_advanced_stats5460.csv',
 '5game_id_team_id_advanced_stats4965.csv',
 '5game_id_team_id_advanced_stats8805.csv',
 '5game_id_team_id_advanced_stats12645.csv',
 '5game_id_team_id_advanced_stats3165.csv',
 '5game_id_team_id_advanced_stats14220.csv',
 '5game_id_team_id_advanced_stats11370.csv',
 '5game_id_team_id_advanced_stats2535.csv',
 '5game_id_team_id_advanced_stats13215.csv',
 '5game_id_team_id_advanced_stats6960.csv',
 '5game_id_team_id_advanced_stats13995.csv',
 '5game_id_team_id_advanced_stats5070.csv',
 '5game_id_team_id_advanced_stats15300.csv',
 '5game_id_team_id_advanced_stats2910.csv',
 '5game_id_team_id_advanced_stats5925.csv',
 '5game_id_team_id_advanced_stats990.csv',
 '5game_id_team_id_advanced_stats13770.csv',
 '5game_id_team_id_advanced_stats15315.csv',
 '5game_id_team_id_advanced_stats9105.csv',
 '5game_id_team_id_advanced_stats10245.csv',
 '5game_id_team_id_advanced_stats14745.csv',
 '5game_id_team_id_advanced_stats13980.csv',
 '5game_id_team_id_advanced_stats3825.csv',
 '5game_id_team_id_advanced_stats8970.csv',
 '5game_id_team_id_advanced_stats210.csv',
 '5game_id_team_id_advanced_stats6975.csv',
 '5game_id_team_id_advanced_stats2520.csv',
 '5game_id_team_id_advanced_stats13200.csv',
 '5game_id_team_id_advanced_stats14235.csv',
 '5game_id_team_id_advanced_stats8025.csv',
 '5game_id_team_id_advanced_stats7470.csv',
 '5game_id_team_id_advanced_stats3945.csv',
 '5game_id_team_id_advanced_stats11205.csv',
 '5game_id_team_id_advanced_stats8145.csv',
 '5game_id_team_id_advanced_stats14355.csv',
 '5game_id_team_id_advanced_stats5475.csv',
 '5game_id_team_id_advanced_stats7935.csv',
 '5game_id_team_id_advanced_stats5850.csv',
 '5game_id_team_id_advanced_stats9930.csv',
 '5game_id_team_id_advanced_stats600.csv',
 '5game_id_team_id_advanced_stats2865.csv',
 '5game_id_team_id_advanced_stats2130.csv',
 '5game_id_team_id_advanced_stats11775.csv',
 '5game_id_team_id_advanced_stats12240.csv',
 '5game_id_team_id_advanced_stats14625.csv',
 '5game_id_team_id_advanced_stats11985.csv',
 '5game_id_team_id_advanced_stats7710.csv',
 '5game_id_team_id_advanced_stats10455.csv',
 '5game_id_team_id_advanced_stats3210.csv',
 '5game_id_team_id_advanced_stats2640.csv',
 '5game_id_team_id_advanced_stats825.csv',
 '5game_id_team_id_advanced_stats1605.csv',
 '5game_id_team_id_advanced_stats7260.csv',
 '5game_id_team_id_advanced_stats10125.csv',
 '5game_id_team_id_advanced_stats15075.csv',
 '5game_id_team_id_advanced_stats3990.csv',
 '5game_id_team_id_advanced_stats6630.csv',
 '5game_id_team_id_advanced_stats13410.csv',
 '5game_id_team_id_advanced_stats4755.csv',
 '5game_id_team_id_advanced_stats10680.csv',
 '5game_id_team_id_advanced_stats8190.csv',
 '5game_id_team_id_advanced_stats6195.csv',
 '5game_id_team_id_advanced_stats12915.csv',
 '5game_id_team_id_advanced_stats3600.csv',
 '5game_id_team_id_advanced_stats5265.csv',
 '5game_id_team_id_advanced_stats12120.csv',
 '5game_id_team_id_advanced_stats1995.csv',
 '5game_id_team_id_advanced_stats4635.csv',
 '5game_id_team_id_advanced_stats11415.csv',
 '5game_id_team_id_advanced_stats6750.csv',
 '5game_id_team_id_advanced_stats2250.csv',
 '5game_id_team_id_advanced_stats1215.csv',
 '5game_id_team_id_advanced_stats5715.csv',
 '5game_id_team_id_advanced_stats12450.csv',
 '5game_id_team_id_advanced_stats9885.csv',
 '5game_id_team_id_advanced_stats9675.csv',
 '5game_id_team_id_advanced_stats15465.csv',
 '5game_id_team_id_advanced_stats945.csv',
 '5game_id_team_id_advanced_stats10290.csv',
 '5game_id_team_id_advanced_stats14790.csv',
 '5game_id_team_id_advanced_stats8580.csv',
 '5game_id_team_id_advanced_stats6585.csv',
 '5game_id_team_id_advanced_stats2085.csv',
 '5game_id_team_id_advanced_stats8595.csv',
 '5game_id_team_id_advanced_stats9660.csv',
 '5game_id_team_id_advanced_stats4350.csv',
 '5game_id_team_id_advanced_stats5700.csv',
 '5game_id_team_id_advanced_stats1200.csv',
 '5game_id_team_id_advanced_stats7665.csv',
 '5game_id_team_id_advanced_stats4185.csv',
 '5game_id_team_id_advanced_stats10905.csv',
 '5game_id_team_id_advanced_stats12690.csv',
 '5game_id_team_id_advanced_stats1980.csv',
 '5game_id_team_id_advanced_stats4620.csv',
 '5game_id_team_id_advanced_stats11400.csv',
 '5game_id_team_id_advanced_stats3615.csv',
 '5game_id_team_id_advanced_stats14550.csv',
 '5game_id_team_id_advanced_stats10050.csv',
 '5game_id_team_id_advanced_stats1770.csv',
 '5game_id_team_id_advanced_stats12135.csv',
 '5game_id_team_id_advanced_stats6180.csv',
 '5game_id_team_id_advanced_stats12900.csv',
 '5game_id_team_id_advanced_stats10695.csv',
 '5game_id_team_id_advanced_stats9270.csv',
 '5game_id_team_id_advanced_stats15060.csv',
 '5game_id_team_id_advanced_stats2325.csv',
 '5game_id_team_id_advanced_stats4740.csv',
 '5game_id_team_id_advanced_stats5310.csv',
 '5game_id_team_id_advanced_stats7275.csv',
 '5game_id_team_id_advanced_stats14430.csv',
 '5game_id_team_id_advanced_stats165.csv',
 '5game_id_team_id_advanced_stats4230.csv',
 '5game_id_team_id_advanced_stats15510.csv',
 '5game_id_team_id_advanced_stats2655.csv',
 '5game_id_team_id_advanced_stats11010.csv',
 '5game_id_team_id_advanced_stats10440.csv',
 '5game_id_team_id_advanced_stats12525.csv',
 '5game_id_team_id_advanced_stats9015.csv',
 '5game_id_team_id_advanced_stats8445.csv',
 '5game_id_team_id_advanced_stats14655.csv',
 '5game_id_team_id_advanced_stats3510.csv',
 '5game_id_team_id_advanced_stats13890.csv',
 '5game_id_team_id_advanced_stats5175.csv',
 '5game_id_team_id_advanced_stats5820.csv',
 '5game_id_team_id_advanced_stats2430.csv',
 '5game_id_team_id_advanced_stats7560.csv',
 '5game_id_team_id_advanced_stats14325.csv',
 '5game_id_team_id_advanced_stats3060.csv',
 '5game_id_team_id_advanced_stats300.csv',
 '5game_id_team_id_advanced_stats2550.csv',
 '5game_id_team_id_advanced_stats9405.csv',
 '5game_id_team_id_advanced_stats8055.csv',
 '5game_id_team_id_advanced_stats1065.csv',
 '5game_id_team_id_advanced_stats5565.csv',
 '5game_id_team_id_advanced_stats3855.csv',
 '5game_id_team_id_advanced_stats4860.csv',
 '5game_id_team_id_advanced_stats1515.csv',
 '5game_id_team_id_advanced_stats7170.csv',
 '5game_id_team_id_advanced_stats11895.csv',
 '5game_id_team_id_advanced_stats6285.csv',
 '5game_id_team_id_advanced_stats5940.csv',
 '5game_id_team_id_advanced_stats8280.csv',
 '5game_id_team_id_advanced_stats10590.csv',
 '5game_id_team_id_advanced_stats705.csv',
 '5game_id_team_id_advanced_stats14085.csv',
 '5game_id_team_id_advanced_stats8295.csv',
 '5game_id_team_id_advanced_stats7830.csv',
 '5game_id_team_id_advanced_stats2790.csv',
 '5game_id_team_id_advanced_stats5955.csv',
 '5game_id_team_id_advanced_stats1500.csv',
 '5game_id_team_id_advanced_stats12345.csv',
 '5game_id_team_id_advanced_stats3465.csv',
 '5game_id_team_id_advanced_stats11880.csv',
 '5game_id_team_id_advanced_stats11670.csv',
 '5game_id_team_id_advanced_stats90.csv',
 '5game_id_team_id_advanced_stats4875.csv',
 '5game_id_team_id_advanced_stats3840.csv',
 '5game_id_team_id_advanced_stats8040.csv',
 '5game_id_team_id_advanced_stats14250.csv',
 '5game_id_team_id_advanced_stats6045.csv',
 '5game_id_team_id_advanced_stats315.csv',
 '5game_id_team_id_advanced_stats8685.csv',
 '5game_id_team_id_advanced_stats6870.csv',
 '5game_id_team_id_advanced_stats1845.csv',
 '5game_id_team_id_advanced_stats1110.csv',
 '5game_id_team_id_advanced_stats3075.csv',
 '5game_id_team_id_advanced_stats7575.csv',
 '5game_id_team_id_advanced_stats9570.csv',
 '5game_id_team_id_advanced_stats13305.csv',
 '5game_id_team_id_advanced_stats5835.csv',
 '5game_id_team_id_advanced_stats7950.csv',
 '5game_id_team_id_advanced_stats7005.csv',
 '5game_id_team_id_advanced_stats14640.csv',
 '5game_id_team_id_advanced_stats12225.csv',
 '5game_id_team_id_advanced_stats5160.csv',
 '5game_id_team_id_advanced_stats4530.csv',
 '5game_id_team_id_advanced_stats15210.csv',
 '5game_id_team_id_advanced_stats9000.csv',
 '5game_id_team_id_advanced_stats840.csv',
 '5game_id_team_id_advanced_stats2625.csv',
 '5game_id_team_id_advanced_stats12555.csv',
 '5game_id_team_id_advanced_stats5610.csv',
 '5game_id_team_id_advanced_stats14130.csv',
 '5game_id_team_id_advanced_stats14865.csv',
 '5game_id_team_id_advanced_stats6480.csv',
 '5game_id_team_id_advanced_stats10395.csv',
 '5game_id_team_id_advanced_stats1890.csv',
 '5game_id_team_id_advanced_stats2355.csv',
 '5game_id_team_id_advanced_stats10140.csv',
 '5game_id_team_id_advanced_stats3705.csv',
 '5game_id_team_id_advanced_stats4095.csv',
 '5game_id_team_id_advanced_stats10815.csv',
 '5game_id_team_id_advanced_stats465.csv',
 '5game_id_team_id_advanced_stats12780.csv',
 '5game_id_team_id_advanced_stats9360.csv',
 '5game_id_team_id_advanced_stats2235.csv',
 '5game_id_team_id_advanced_stats6735.csv',
 '5game_id_team_id_advanced_stats4650.csv',
 '5game_id_team_id_advanced_stats13515.csv',
 '5game_id_team_id_advanced_stats14520.csv',
 '5game_id_team_id_advanced_stats8730.csv',
 '5game_id_team_id_advanced_stats10020.csv',
 '5game_id_team_id_advanced_stats7365.csv',
 '5game_id_team_id_advanced_stats6090.csv',
 '5game_id_team_id_advanced_stats12810.csv',
 '5game_id_team_id_advanced_stats10785.csv',
 '5game_id_team_id_advanced_stats4320.csv',
 '5game_id_team_id_advanced_stats13065.csv',
 '5game_id_team_id_advanced_stats11100.csv',
 '5game_id_team_id_advanced_stats2745.csv',
 '5game_id_team_id_advanced_stats3315.csv',
 '5game_id_team_id_advanced_stats12435.csv',
 '5game_id_team_id_advanced_stats45.csv',
 '5game_id_team_id_advanced_stats4485.csv',
 '5game_id_team_id_advanced_stats12390.csv',
 '5game_id_team_id_advanced_stats14910.csv',
 '5game_id_team_id_advanced_stats3300.csv',
 '5game_id_team_id_advanced_stats10545.csv',
 '5game_id_team_id_advanced_stats12420.csv',
 '5game_id_team_id_advanced_stats4335.csv',
 '5game_id_team_id_advanced_stats11115.csv',
 '5game_id_team_id_advanced_stats510.csv',
 '5game_id_team_id_advanced_stats12150.csv',
 '5game_id_team_id_advanced_stats10035.csv',
 '5game_id_team_id_advanced_stats14535.csv',
 '5game_id_team_id_advanced_stats6720.csv',
 '5game_id_team_id_advanced_stats9375.csv',
 '5game_id_team_id_advanced_stats2220.csv',
 '5game_id_team_id_advanced_stats15165.csv',
 '5game_id_team_id_advanced_stats13500.csv',
 '5game_id_team_id_advanced_stats12795.csv',
 '5game_id_team_id_advanced_stats4080.csv',
 '5game_id_team_id_advanced_stats10800.csv',
 '5game_id_team_id_advanced_stats10155.csv',
 '5game_id_team_id_advanced_stats12030.csv',
 '5game_id_team_id_advanced_stats4725.csv',
 '5game_id_team_id_advanced_stats2340.csv',
 '5game_id_team_id_advanced_stats11505.csv',
 '5game_id_team_id_advanced_stats13845.csv',
 '5game_id_team_id_advanced_stats0.csv',
 '5game_id_team_id_advanced_stats8490.csv',
 '5game_id_team_id_advanced_stats10380.csv',
 '5game_id_team_id_advanced_stats6495.csv',
 '5game_id_team_id_advanced_stats12540.csv',
 '5game_id_team_id_advanced_stats1305.csv',
 '5game_id_team_id_advanced_stats10425.csv',
 '5game_id_team_id_advanced_stats6330.csv',
 '5game_id_team_id_advanced_stats9765.csv',
 '5game_id_team_id_advanced_stats855.csv',
 '5game_id_team_id_advanced_stats13110.csv',
 '5game_id_team_id_advanced_stats7770.csv',
 '5game_id_team_id_advanced_stats3270.csv',
 '5game_id_team_id_advanced_stats8325.csv',
 '5game_id_team_id_advanced_stats7980.csv',
 '5game_id_team_id_advanced_stats4245.csv',
 '5game_id_team_id_advanced_stats8655.csv',
 '5game_id_team_id_advanced_stats14445.csv',
 '5game_id_team_id_advanced_stats7200.csv',
 '5game_id_team_id_advanced_stats1665.csv',
 '5game_id_team_id_advanced_stats13470.csv',
 '5game_id_team_id_advanced_stats15015.csv',
 '5game_id_team_id_advanced_stats12975.csv',
 '5game_id_team_id_advanced_stats5205.csv',
 '5game_id_team_id_advanced_stats3660.csv',
 '5game_id_team_id_advanced_stats11475.csv',
 '5game_id_team_id_advanced_stats14280.csv',
 '5game_id_team_id_advanced_stats2595.csv',
 '5game_id_team_id_advanced_stats14055.csv',
 '5game_id_team_id_advanced_stats1275.csv',
 '5game_id_team_id_advanced_stats5775.csv',
 '5game_id_team_id_advanced_stats5985.csv',
 '5game_id_team_id_advanced_stats15405.csv',
 '5game_id_team_id_advanced_stats9615.csv',
 '5game_id_team_id_advanced_stats6240.csv',
 '5game_id_team_id_advanced_stats11850.csv',
 '5game_id_team_id_advanced_stats13935.csv',
 '5game_id_team_id_advanced_stats13920.csv',
 '5game_id_team_id_advanced_stats6255.csv',
 '5game_id_team_id_advanced_stats930.csv',
 '5game_id_team_id_advanced_stats9600.csv',
 '5game_id_team_id_advanced_stats7605.csv',
 '5game_id_team_id_advanced_stats8250.csv',
 '5game_id_team_id_advanced_stats14040.csv',
 '5game_id_team_id_advanced_stats5760.csv',
 '5game_id_team_id_advanced_stats1260.csv',
 '5game_id_team_id_advanced_stats10965.csv',
 '5game_id_team_id_advanced_stats2580.csv',
 '5game_id_team_id_advanced_stats14295.csv',
 '5game_id_team_id_advanced_stats8085.csv',
 '5game_id_team_id_advanced_stats3885.csv',
 '5game_id_team_id_advanced_stats11460.csv',
 '5game_id_team_id_advanced_stats1710.csv',
 '5game_id_team_id_advanced_stats3675.csv',
 '5game_id_team_id_advanced_stats12960.csv',
 '5game_id_team_id_advanced_stats6645.csv',
 '5game_id_team_id_advanced_stats15000.csv',
 '5game_id_team_id_advanced_stats9210.csv',
 '5game_id_team_id_advanced_stats7215.csv',
 '5game_id_team_id_advanced_stats8640.csv',
 '5game_id_team_id_advanced_stats5370.csv',
 '5game_id_team_id_advanced_stats2190.csv',
 '5game_id_team_id_advanced_stats105.csv',
 '5game_id_team_id_advanced_stats14685.csv',
 '5game_id_team_id_advanced_stats11925.csv',
 '5game_id_team_id_advanced_stats7995.csv',
 '5game_id_team_id_advanced_stats11070.csv',
 '5game_id_team_id_advanced_stats9990.csv',
 '5game_id_team_id_advanced_stats10350.csv',
 '5game_id_team_id_advanced_stats1470.csv',
 '5game_id_team_id_advanced_stats13665.csv',
 '5game_id_team_id_advanced_stats11700.csv',
 '5game_id_team_id_advanced_stats2145.csv',
 '5game_id_team_id_advanced_stats675.csv',
 '5game_id_team_id_advanced_stats9945.csv',
 '5game_id_team_id_advanced_stats885.csv',
 '5game_id_team_id_advanced_stats5400.csv',

In [8]:
len(listttt)

1035

In [9]:
listttt[0]

'5game_id_team_id_advanced_stats5880.csv'

In [10]:
df_empty = pd.DataFrame({})
df_empty

Empty DataFrame
Columns: []
Index: []

In [11]:
for i in range(len(listttt)):
    print(i)
    df_temp = pd.read_csv(os.path.join('..', 'processed_data_preliminary', str(listttt[i])))
    df_empty = pd.concat([df_empty, df_temp])

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688
689
690
691
692
693
694
695
696
697
698
699
700
701
702
703
704
705
706
707
708
709
710
711
712
713
714
715
716
717
718
719
720
721
722
723
724
725
726
727
728
729
730
731
732
733
734
735
736
737
738
739
740
741
742
743
744
745
746
747
748
749
750
751
752
753
754
755
756
757
758
759
760
761
762
763
764
765
766
767
768
769
770
771
772
773
774
775
776
777
778
779
780
781
782
783
784
785
786
787
788
789
790
791
792
793
794
795
796
797
798
799
800
801
802
803
804
805
806
807
808
809
810
811
812
813
814
815
816
817
818
819
820
821
822
823
824
825
826
827
828
829
830
831
832
833
834
835
836
837
838
839
840
841
842
843
844
845
846
847
848
849
850
851
852
853
854
855
856
857
858
859
860
861
862
863
864
865
866
867
868
869
870
871
872
873
874
875
876
877
878
879
880
881
882
883
884
885
886
887
888
889
890
891
892
893
894
895
896
897
898
899
900
901
902
903
904
905
906
907
908
909
910
911
912
913
914
915
916
917
918
919
920
921
922
923
924
925
926
927
928
929
930
931
932
933
934
935
936
937
938
939
940
941
942
943
944
945
946
947
948
949
950
951
952
953
954
955
956
957
958
959
960
961
962
963
964
965
966
967
968
969
970
971
972
973
974
975
976
977
978
979
980
981
982
983
984
985
986
987
988
989
990
991
992
993
994
995
996
997
998
999
1000
1001
1002
1003
1004
1005
1006
1007
1008
1009
1010
1011
1012
1013
1014
1015
1016
1017
1018
1019
1020
1021
1022
1023
1024
1025
1026
1027
1028
1029
1030
1031
1032
1033
1034

In [12]:
df_empty.head()

,GAME_ID,TEAM_ID,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
0,21000961,1610612740,Hornets,NOH,New Orleans,240:00,102.5,106.9,102.1,105.7,0.3,1.1,0.382,1.44,11.5,0.319,NaN,NaN,9.916,10.3,0.462,0.512,1.0,0.198,90.42,87.0,72.50,87,0.479
1,21000961,1610612742,Mavericks,DAL,Dallas,240:00,102.1,105.7,102.5,106.9,-0.3,-1.1,0.710,2.00,19.0,NaN,0.681,NaN,12.211,12.6,0.493,0.554,1.0,0.191,90.42,87.0,72.50,87,0.521
2,21000962,1610612759,Spurs,SAS,San Antonio,240:00,125.0,124.7,110.9,118.2,14.1,6.5,0.467,1.40,18.3,0.222,0.556,0.444,16.892,16.9,0.686,0.704,1.0,0.198,91.30,88.5,73.75,89,0.610
3,21000962,1610612765,Pistons,DET,Detroit,240:00,110.9,118.2,125.0,124.7,-14.1,-6.5,0.524,1.83,16.2,0.444,0.778,0.556,12.793,13.6,0.484,0.511,1.0,0.197,91.30,88.5,73.75,88,0.390
4,21000963,1610612758,Kings,SAC,Sacramento,240:00,97.0,101.0,104.9,106.0,-7.9,-5.0,0.529,0.86,12.9,0.370,0.841,0.582,19.970,20.8,0.440,0.509,1.0,0.196,103.12,100.5,83.75,101,0.478

In [13]:
df_empty.reset_index(drop=True, inplace=True)
p(df_empty)

(31036, 29)

,GAME_ID,TEAM_ID,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
0,21000961,1610612740,Hornets,NOH,New Orleans,240:00,102.5,106.9,102.1,105.7,0.3,1.1,0.382,1.44,11.5,0.319,NaN,NaN,9.916,10.3,0.462,0.512,1.0,0.198,90.42,87.0,72.50,87,0.479
1,21000961,1610612742,Mavericks,DAL,Dallas,240:00,102.1,105.7,102.5,106.9,-0.3,-1.1,0.710,2.00,19.0,NaN,0.681,NaN,12.211,12.6,0.493,0.554,1.0,0.191,90.42,87.0,72.50,87,0.521
2,21000962,1610612759,Spurs,SAS,San Antonio,240:00,125.0,124.7,110.9,118.2,14.1,6.5,0.467,1.40,18.3,0.222,0.556,0.444,16.892,16.9,0.686,0.704,1.0,0.198,91.30,88.5,73.75,89,0.610
3,21000962,1610612765,Pistons,DET,Detroit,240:00,110.9,118.2,125.0,124.7,-14.1,-6.5,0.524,1.83,16.2,0.444,0.778,0.556,12.793,13.6,0.484,0.511,1.0,0.197,91.30,88.5,73.75,88,0.390
4,21000963,1610612758,Kings,SAC,Sacramento,240:00,97.0,101.0,104.9,106.0,-7.9,-5.0,0.529,0.86,12.9,0.370,0.841,0.582,19.970,20.8,0.440,0.509,1.0,0.196,103.12,100.5,83.75,101,0.478
31031,21700898,1610612738,Celtics,BOS,Boston,240:00,112.5,111.2,100.9,101.0,11.6,10.2,0.641,3.13,19.1,0.231,0.830,0.515,8.258,8.2,0.523,0.557,1.0,0.200,96.98,97.5,81.25,98,0.529
31032,21700899,1610612741,Bulls,CHI,Chicago,240:00,85.2,87.0,102.4,104.0,-17.2,-17.0,0.515,1.21,12.7,0.297,0.840,0.535,13.709,14.0,0.387,0.422,1.0,0.198,101.82,100.0,83.33,100,0.408
31033,21700899,1610612751,Nets,BKN,Brooklyn,240:00,102.4,104.0,85.2,87.0,17.2,17.0,0.775,2.07,22.2,0.160,0.703,0.465,14.775,15.0,0.533,0.556,1.0,0.195,101.82,100.0,83.33,100,0.592
31034,21700900,1610612752,Knicks,NYK,New York,240:00,106.8,109.9,124.5,121.4,-17.7,-11.5,0.596,2.00,19.7,0.265,0.762,0.495,13.467,13.9,0.542,0.555,1.0,0.200,102.20,102.0,85.00,101,0.421
31035,21700900,1610612744,Warriors,GSW,Golden State,240:00,124.5,121.4,106.8,109.9,17.7,11.5,0.705,2.58,22.2,0.238,0.735,0.505,11.947,11.7,0.606,0.648,1.0,0.201,102.20,102.0,85.00,103,0.579

In [14]:
31036 / 2

15518.0

<font color='red'> this number of games correct for seasons 2006-07 thru 2017-18???</font> -yes, 15519 - 1 = 15518 for a post boston marathon game not played between the pacers and celtics

In [15]:
df_empty.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31036 entries, 0 to 31035
Data columns (total 29 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   GAME_ID            31036 non-null  int64
 1   TEAM_ID            31036 non-null  int64
 2   TEAM_NAME          31036 non-null  object
 3   TEAM_ABBREVIATION  31036 non-null  object
 4   TEAM_CITY          31036 non-null  object
 5   MIN                31036 non-null  object
 6   E_OFF_RATING       31036 non-null  float64
 7   OFF_RATING         31036 non-null  float64
 8   E_DEF_RATING       31036 non-null  float64
 9   DEF_RATING         31036 non-null  float64
 10  E_NET_RATING       31036 non-null  float64
 11  NET_RATING         31036 non-null  float64
 12  AST_PCT            31036 non-null  float64
 13  AST_TOV            31036 non-null  float64
 14  AST_RATIO          31036 non-null  float64
 15  OREB_PCT           26705 non-null  float64
 16  DREB_PCT           26707 non-null  float64
 17  REB_PCT            23068 non-null  float64
 18  E_TM_TOV_PCT       31036 non-null  float64
 19  TM_TOV_PCT         31036 non-null  float64
 20  EFG_PCT            31036 non-null  float64
 21  TS_PCT             31036 non-null  float64
 22  USG_PCT            31036 non-null  float64
 23  E_USG_PCT          31036 non-null  float64
 24  E_PACE             31036 non-null  float64
 25  PACE               31036 non-null  float64
 26  PACE_PER40         31036 non-null  float64
 27  POSS               31036 non-null  int64
 28  PIE                31036 non-null  float64
dtypes: float64(22), int64(3), object(4)
memory usage: 6.9+ MB

In [16]:
#df_empty.MIN.str.replace(':00', '').value_counts()

In [17]:
yoyo = df_empty.MIN.str.split(':')
type(yoyo)

pandas.core.series.Series

In [18]:
import numpy as np

In [19]:
df_ms = pd.DataFrame({})

In [20]:
df_ms[['minutes', 'seconds']] = pd.DataFrame(yoyo.tolist())
df_ms

      minutes seconds
0         240      00
1         240      00
2         240      00
3         240      00
4         240      00
...       ...     ...
31031     240      00
31032     240      00
31033     240      00
31034     240      00
31035     240      00

[31036 rows x 2 columns]

In [21]:
df_ms = df_ms.astype('int64')
p(df_ms)

(31036, 2)

       minutes  seconds
0          240        0
1          240        0
2          240        0
3          240        0
4          240        0
31031      240        0
31032      240        0
31033      240        0
31034      240        0
31035      240        0

In [22]:
df_ms[['hours']] = np.floor(df_ms.minutes / 60)
p(df_ms)

(31036, 3)

       minutes  seconds  hours
0          240        0    4.0
1          240        0    4.0
2          240        0    4.0
3          240        0    4.0
4          240        0    4.0
31031      240        0    4.0
31032      240        0    4.0
31033      240        0    4.0
31034      240        0    4.0
31035      240        0    4.0

In [23]:
df_ms.minutes = df_ms.minutes - (np.floor(df_ms.minutes / 60) * 60)
p(df_ms)

(31036, 3)

       minutes  seconds  hours
0          0.0        0    4.0
1          0.0        0    4.0
2          0.0        0    4.0
3          0.0        0    4.0
4          0.0        0    4.0
31031      0.0        0    4.0
31032      0.0        0    4.0
31033      0.0        0    4.0
31034      0.0        0    4.0
31035      0.0        0    4.0

In [24]:
df_ms.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31036 entries, 0 to 31035
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   minutes  31036 non-null  float64
 1   seconds  31036 non-null  int64
 2   hours    31036 non-null  float64
dtypes: float64(2), int64(1)
memory usage: 727.5 KB

In [25]:
df_ms.value_counts('minutes')

minutes
0.0     29152
25.0     1590
50.0      232
15.0       48
59.0        8
40.0        6
dtype: int64

In [26]:
df_ms = df_ms.astype('int64')
p(df_ms)

(31036, 3)

       minutes  seconds  hours
0            0        0      4
1            0        0      4
2            0        0      4
3            0        0      4
4            0        0      4
31031        0        0      4
31032        0        0      4
31033        0        0      4
31034        0        0      4
31035        0        0      4

In [27]:
df_ms.value_counts('minutes')

minutes
0     29152
25     1590
50      232
15       48
59        8
40        6
dtype: int64

In [28]:
indexes_min_zero = df_ms.minutes[df_ms.minutes == 0].index
indexes_min_zero

Int64Index([    0,     1,     2,     3,     4,     5,     6,     7,     8,
                9,
            ...
            31026, 31027, 31028, 31029, 31030, 31031, 31032, 31033, 31034,
            31035],
           dtype='int64', length=29152)

In [29]:
df_ms.at[indexes_min_zero, 'minutes'] = '00'

In [30]:
df_ms.value_counts('minutes')

minutes
00    29152
25     1590
50      232
15       48
59        8
40        6
dtype: int64

In [31]:
df_ms.value_counts('seconds')

seconds
0     31028
56        4
60        2
59        2
dtype: int64

In [32]:
df_ms.seconds = df_ms.seconds.astype('string')

In [33]:
indexes_sec_zero = df_ms.seconds[df_ms.seconds == '0'].index
len(indexes_sec_zero)

31028

In [34]:
indexes_sec_zero = list(indexes_sec_zero)

In [35]:
df_ms.at[indexes_sec_zero, 'seconds'] = '00'

In [36]:
df_ms.value_counts('seconds')

seconds
00    31028
56        4
60        2
59        2
dtype: int64

In [37]:
df_ms.value_counts('hours')

hours
4    30974
5       54
3        8
dtype: int64

In [38]:
df_ms.hours = '0' + df_ms.hours.astype('string')

In [39]:
df_ms.value_counts('hours')

hours
04    30974
05       54
03        8
dtype: int64

In [40]:
p(df_ms)

(31036, 3)

      minutes seconds hours
0          00      00    04
1          00      00    04
2          00      00    04
3          00      00    04
4          00      00    04
31031      00      00    04
31032      00      00    04
31033      00      00    04
31034      00      00    04
31035      00      00    04

In [41]:
df_ms.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31036 entries, 0 to 31035
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   minutes  31036 non-null  object
 1   seconds  31036 non-null  string
 2   hours    31036 non-null  string
dtypes: object(1), string(2)
memory usage: 727.5+ KB

<font color='red'> why do we have object for minutes here?????</font>

In [42]:
df_ms.minutes.value_counts()

00    29152
25     1590
50      232
15       48
59        8
40        6
Name: minutes, dtype: int64

In [43]:
df_ms.minutes = df_ms.minutes.astype('string')
df_ms.minutes

0        00
1        00
2        00
3        00
4        00
         ..
31031    00
31032    00
31033    00
31034    00
31035    00
Name: minutes, Length: 31036, dtype: string

In [44]:
df_ms['duration'] = df_ms.hours + ':' + df_ms.minutes + ':' + df_ms.seconds
p(df_ms)

(31036, 4)

      minutes seconds hours  duration
0          00      00    04  04:00:00
1          00      00    04  04:00:00
2          00      00    04  04:00:00
3          00      00    04  04:00:00
4          00      00    04  04:00:00
31031      00      00    04  04:00:00
31032      00      00    04  04:00:00
31033      00      00    04  04:00:00
31034      00      00    04  04:00:00
31035      00      00    04  04:00:00

In [45]:
df_ms['duration'] = pd.to_timedelta(df_ms.duration)
p(df_ms)

(31036, 4)

      minutes seconds hours        duration
0          00      00    04 0 days 04:00:00
1          00      00    04 0 days 04:00:00
2          00      00    04 0 days 04:00:00
3          00      00    04 0 days 04:00:00
4          00      00    04 0 days 04:00:00
31031      00      00    04 0 days 04:00:00
31032      00      00    04 0 days 04:00:00
31033      00      00    04 0 days 04:00:00
31034      00      00    04 0 days 04:00:00
31035      00      00    04 0 days 04:00:00

In [46]:
df_ms.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31036 entries, 0 to 31035
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   minutes   31036 non-null  string
 1   seconds   31036 non-null  string
 2   hours     31036 non-null  string
 3   duration  31036 non-null  timedelta64[ns]
dtypes: string(3), timedelta64[ns](1)
memory usage: 970.0 KB

In [47]:
df_duration = pd.DataFrame({})

In [48]:
df_duration['duration'] = df_ms.duration
p(df_duration)

(31036, 1)

             duration
0     0 days 04:00:00
1     0 days 04:00:00
2     0 days 04:00:00
3     0 days 04:00:00
4     0 days 04:00:00
31031 0 days 04:00:00
31032 0 days 04:00:00
31033 0 days 04:00:00
31034 0 days 04:00:00
31035 0 days 04:00:00

In [49]:
df_empty = pd.concat([df_empty, df_duration], axis=1)
p(df_empty)

(31036, 30)

,GAME_ID,TEAM_ID,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration
0,21000961,1610612740,Hornets,NOH,New Orleans,240:00,102.5,106.9,102.1,105.7,0.3,1.1,0.382,1.44,11.5,0.319,NaN,NaN,9.916,10.3,0.462,0.512,1.0,0.198,90.42,87.0,72.50,87,0.479,0 days 04:00:00
1,21000961,1610612742,Mavericks,DAL,Dallas,240:00,102.1,105.7,102.5,106.9,-0.3,-1.1,0.710,2.00,19.0,NaN,0.681,NaN,12.211,12.6,0.493,0.554,1.0,0.191,90.42,87.0,72.50,87,0.521,0 days 04:00:00
2,21000962,1610612759,Spurs,SAS,San Antonio,240:00,125.0,124.7,110.9,118.2,14.1,6.5,0.467,1.40,18.3,0.222,0.556,0.444,16.892,16.9,0.686,0.704,1.0,0.198,91.30,88.5,73.75,89,0.610,0 days 04:00:00
3,21000962,1610612765,Pistons,DET,Detroit,240:00,110.9,118.2,125.0,124.7,-14.1,-6.5,0.524,1.83,16.2,0.444,0.778,0.556,12.793,13.6,0.484,0.511,1.0,0.197,91.30,88.5,73.75,88,0.390,0 days 04:00:00
4,21000963,1610612758,Kings,SAC,Sacramento,240:00,97.0,101.0,104.9,106.0,-7.9,-5.0,0.529,0.86,12.9,0.370,0.841,0.582,19.970,20.8,0.440,0.509,1.0,0.196,103.12,100.5,83.75,101,0.478,0 days 04:00:00
31031,21700898,1610612738,Celtics,BOS,Boston,240:00,112.5,111.2,100.9,101.0,11.6,10.2,0.641,3.13,19.1,0.231,0.830,0.515,8.258,8.2,0.523,0.557,1.0,0.200,96.98,97.5,81.25,98,0.529,0 days 04:00:00
31032,21700899,1610612741,Bulls,CHI,Chicago,240:00,85.2,87.0,102.4,104.0,-17.2,-17.0,0.515,1.21,12.7,0.297,0.840,0.535,13.709,14.0,0.387,0.422,1.0,0.198,101.82,100.0,83.33,100,0.408,0 days 04:00:00
31033,21700899,1610612751,Nets,BKN,Brooklyn,240:00,102.4,104.0,85.2,87.0,17.2,17.0,0.775,2.07,22.2,0.160,0.703,0.465,14.775,15.0,0.533,0.556,1.0,0.195,101.82,100.0,83.33,100,0.592,0 days 04:00:00
31034,21700900,1610612752,Knicks,NYK,New York,240:00,106.8,109.9,124.5,121.4,-17.7,-11.5,0.596,2.00,19.7,0.265,0.762,0.495,13.467,13.9,0.542,0.555,1.0,0.200,102.20,102.0,85.00,101,0.421,0 days 04:00:00
31035,21700900,1610612744,Warriors,GSW,Golden State,240:00,124.5,121.4,106.8,109.9,17.7,11.5,0.705,2.58,22.2,0.238,0.735,0.505,11.947,11.7,0.606,0.648,1.0,0.201,102.20,102.0,85.00,103,0.579,0 days 04:00:00

In [50]:
df_empty['duration_minutes'] = df_empty.duration.dt.seconds / 60
df_empty

,GAME_ID,TEAM_ID,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration,duration_minutes
0,21000961,1610612740,Hornets,NOH,New Orleans,240:00,102.5,106.9,102.1,105.7,0.3,1.1,0.382,1.44,11.5,0.319,NaN,NaN,9.916,10.3,0.462,0.512,1.0,0.198,90.42,87.0,72.50,87,0.479,0 days 04:00:00,240.0
1,21000961,1610612742,Mavericks,DAL,Dallas,240:00,102.1,105.7,102.5,106.9,-0.3,-1.1,0.710,2.00,19.0,NaN,0.681,NaN,12.211,12.6,0.493,0.554,1.0,0.191,90.42,87.0,72.50,87,0.521,0 days 04:00:00,240.0
2,21000962,1610612759,Spurs,SAS,San Antonio,240:00,125.0,124.7,110.9,118.2,14.1,6.5,0.467,1.40,18.3,0.222,0.556,0.444,16.892,16.9,0.686,0.704,1.0,0.198,91.30,88.5,73.75,89,0.610,0 days 04:00:00,240.0
3,21000962,1610612765,Pistons,DET,Detroit,240:00,110.9,118.2,125.0,124.7,-14.1,-6.5,0.524,1.83,16.2,0.444,0.778,0.556,12.793,13.6,0.484,0.511,1.0,0.197,91.30,88.5,73.75,88,0.390,0 days 04:00:00,240.0
4,21000963,1610612758,Kings,SAC,Sacramento,240:00,97.0,101.0,104.9,106.0,-7.9,-5.0,0.529,0.86,12.9,0.370,0.841,0.582,19.970,20.8,0.440,0.509,1.0,0.196,103.12,100.5,83.75,101,0.478,0 days 04:00:00,240.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31031,21700898,1610612738,Celtics,BOS,Boston,240:00,112.5,111.2,100.9,101.0,11.6,10.2,0.641,3.13,19.1,0.231,0.830,0.515,8.258,8.2,0.523,0.557,1.0,0.200,96.98,97.5,81.25,98,0.529,0 days 04:00:00,240.0
31032,21700899,1610612741,Bulls,CHI,Chicago,240:00,85.2,87.0,102.4,104.0,-17.2,-17.0,0.515,1.21,12.7,0.297,0.840,0.535,13.709,14.0,0.387,0.422,1.0,0.198,101.82,100.0,83.33,100,0.408,0 days 04:00:00,240.0
31033,21700899,1610612751,Nets,BKN,Brooklyn,240:00,102.4,104.0,85.2,87.0,17.2,17.0,0.775,2.07,22.2,0.160,0.703,0.465,14.775,15.0,0.533,0.556,1.0,0.195,101.82,100.0,83.33,100,0.592,0 days 04:00:00,240.0
31034,21700900,1610612752,Knicks,NYK,New York,240:00,106.8,109.9,124.5,121.4,-17.7,-11.5,0.596,2.00,19.7,0.265,0.762,0.495,13.467,13.9,0.542,0.555,1.0,0.200,102.20,102.0,85.00,101,0.421,0 days 04:00:00,240.0
31035,21700900,1610612744,Warriors,GSW,Golden State,240:00,124.5,121.4,106.8,109.9,17.7,11.5,0.705,2.58,22.2,0.238,0.735,0.505,11.947,11.7,0.606,0.648,1.0,0.201,102.20,102.0,85.00,103,0.579,0 days 04:00:00,240.0

In [51]:
df_empty.value_counts('duration_minutes')

duration_minutes
240.000000    29154
265.000000     1590
290.000000      232
315.000000       48
340.000000        6
239.933333        4
239.983333        2
dtype: int64

In [52]:
#LA -> Los Angeles for column 'TEAM_CITY'
df_empty.loc[(df_empty.TEAM_CITY == 'LA'), 'TEAM_CITY'] = 'Los Angeles'

In [53]:
datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)

datapath_df = os.path.join(datapath, '19boxscoreadvancedv2_team_2006_2018.csv')
if not os.path.exists(datapath_df):
    df_empty.to_csv(datapath_df, index=False)