In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [2]:
os.getcwd()

'C:\\Users\\Paul\\sb\\DSCapstone2\\02_Data_Wrangling'

In [3]:
df = pd.read_csv('C:\\Users\\Paul\\sb\\DSCapstone2\\raw_data\\nba_betting_totals.csv')
df

,game_id,book_name,book_id,team_id,a_team_id,total1,total2,price1,price2
0,21100131,Pinnacle Sports,238,1610612740,1610612743,192.0,192.0,-105.0,-105.0
1,21100131,5Dimes,19,1610612740,1610612743,192.0,192.0,-105.0,-105.0
2,21100131,Bookmaker,93,1610612740,1610612743,192.0,192.0,-110.0,-110.0
3,21100131,BetOnline,1096,1610612740,1610612743,191.5,191.5,-110.0,-110.0
4,21100131,Bovada,999996,1610612740,1610612743,192.0,192.0,-110.0,-110.0
...,...,...,...,...,...,...,...,...,...
131381,41700215,Heritage,169,1610612755,1610612738,204.5,204.5,-105.0,-105.0
131382,41700215,Intertops,180,1610612755,1610612738,205.0,205.0,-110.0,-110.0
131383,41700215,YouWager,139,1610612755,1610612738,204.5,204.5,-110.0,-110.0
131384,41700215,JustBet,1275,1610612755,1610612738,204.0,204.0,-110.0,-110.0
131385,41700215,Sportsbetting,999991,1610612755,1610612738,204.5,204.5,-110.0,-110.0

In [4]:
df = df.iloc[df.game_id.drop_duplicates().index]
df

,game_id,book_name,book_id,team_id,a_team_id,total1,total2,price1,price2
0,21100131,Pinnacle Sports,238,1610612740,1610612743,192.0,192.0,-105.0,-105.0
10,21100137,Pinnacle Sports,238,1610612760,1610612763,193.5,193.5,-105.0,-105.0
20,21100148,Pinnacle Sports,238,1610612760,1610612740,183.5,183.5,-105.0,-105.0
30,21100149,Pinnacle Sports,238,1610612745,1610612759,198.5,198.5,-105.0,-105.0
40,21100152,Pinnacle Sports,238,1610612753,1610612757,186.0,186.0,-107.0,-103.0
...,...,...,...,...,...,...,...,...,...
131336,41700212,Pinnacle Sports,238,1610612755,1610612738,206.5,206.5,-103.0,-107.0
131346,41700233,Pinnacle Sports,238,1610612744,1610612740,233.5,233.5,-103.0,-107.0
131356,41700213,Pinnacle Sports,238,1610612738,1610612755,206.5,206.5,-103.0,-107.0
131366,41700234,Pinnacle Sports,238,1610612744,1610612740,231.0,231.0,-103.0,-107.0
131376,41700215,Pinnacle Sports,238,1610612755,1610612738,204.5,204.5,-106.0,-104.0

In [5]:
#df.iloc[df.game_id.drop_duplicates().index]['book_name'].value_counts()

In [6]:
df2 = pd.read_csv('C:\\Users\\Paul\\sb\\DSCapstone2\\processed_data\\3game_date_home_away.csv', parse_dates=['game_date'])
df2

,game_id,game_date,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,...,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,season_type,season
0,20600001,2006-10-31,1610612748,0.000,240,25.0,65.0,0.385,3.0,17.0,...,36.0,49,22.0,10.0,5.0,16.0,21.0,108,Regular Season,2006-07
1,20600002,2006-10-31,1610612747,1.000,240,46.0,83.0,0.554,6.0,12.0,...,25.0,29,29.0,7.0,5.0,21.0,25.0,106,Regular Season,2006-07
2,20600003,2006-11-01,1610612755,1.000,240,31.0,74.0,0.419,3.0,9.0,...,25.0,42,11.0,9.0,4.0,18.0,24.0,75,Regular Season,2006-07
3,20600004,2006-11-01,1610612766,0.000,240,37.0,78.0,0.474,4.0,10.0,...,32.0,50,26.0,14.0,5.0,17.0,26.0,106,Regular Season,2006-07
4,20600005,2006-11-01,1610612753,1.000,240,35.0,59.0,0.593,6.0,8.0,...,16.0,27,21.0,7.0,0.0,15.0,31.0,94,Regular Season,2006-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15514,41700317,2018-05-28,1610612745,0.429,240,36.0,90.0,0.400,7.0,44.0,...,31.0,42,25.0,9.0,7.0,16.0,22.0,101,Playoffs,2017-18
15515,41700401,2018-05-31,1610612744,1.000,265,46.0,90.0,0.511,13.0,36.0,...,34.0,53,18.0,5.0,3.0,11.0,18.0,114,Playoffs,2017-18
15516,41700402,2018-06-03,1610612744,1.000,240,47.0,82.0,0.573,15.0,36.0,...,26.0,42,25.0,9.0,4.0,10.0,15.0,103,Playoffs,2017-18
15517,41700403,2018-06-06,1610612739,0.000,240,40.0,92.0,0.435,9.0,31.0,...,31.0,37,27.0,6.0,5.0,10.0,20.0,110,Playoffs,2017-18
15518,41700404,2018-06-08,1610612739,0.000,240,30.0,87.0,0.345,8.0,27.0,...,34.0,44,25.0,7.0,13.0,8.0,24.0,108,Playoffs,2017-18

In [7]:
pd.merge(df2, df, on='game_id', how='right')

,game_id,game_date,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,...,season_type,season,book_name,book_id,team_id,a_team_id,total1,total2,price1,price2
0,21100131,2012-01-09,1.610613e+09,0.600,240.0,29.0,71.0,0.408,8.0,23.0,...,Regular Season,2011-12,Pinnacle Sports,238,1610612740,1610612743,192.0,192.0,-105.0,-105.0
1,21100137,2012-01-10,1.610613e+09,0.333,240.0,39.0,85.0,0.459,5.0,12.0,...,Regular Season,2011-12,Pinnacle Sports,238,1610612760,1610612763,193.5,193.5,-105.0,-105.0
2,21100148,2012-01-11,1.610613e+09,0.300,240.0,36.0,80.0,0.450,1.0,16.0,...,Regular Season,2011-12,Pinnacle Sports,238,1610612760,1610612740,183.5,183.5,-105.0,-105.0
3,21100149,2012-01-11,1.610613e+09,0.636,265.0,42.0,92.0,0.457,5.0,16.0,...,Regular Season,2011-12,Pinnacle Sports,238,1610612745,1610612759,198.5,198.5,-105.0,-105.0
4,21100152,2012-01-11,1.610613e+09,0.700,240.0,41.0,86.0,0.477,10.0,25.0,...,Regular Season,2011-12,Pinnacle Sports,238,1610612753,1610612757,186.0,186.0,-107.0,-103.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14913,41700212,2018-05-03,1.610613e+09,1.000,240.0,37.0,82.0,0.451,15.0,36.0,...,Playoffs,2017-18,Pinnacle Sports,238,1610612755,1610612738,206.5,206.5,-103.0,-107.0
14914,41700233,2018-05-04,1.610613e+09,0.333,240.0,48.0,96.0,0.500,14.0,31.0,...,Playoffs,2017-18,Pinnacle Sports,238,1610612744,1610612740,233.5,233.5,-103.0,-107.0
14915,41700213,2018-05-05,1.610613e+09,0.000,265.0,38.0,97.0,0.392,9.0,30.0,...,Playoffs,2017-18,Pinnacle Sports,238,1610612738,1610612755,206.5,206.5,-103.0,-107.0
14916,41700234,2018-05-06,1.610613e+09,0.250,240.0,32.0,88.0,0.364,4.0,26.0,...,Playoffs,2017-18,Pinnacle Sports,238,1610612744,1610612740,231.0,231.0,-103.0,-107.0
14917,41700215,2018-05-09,1.610613e+09,0.800,240.0,38.0,85.0,0.447,7.0,20.0,...,Playoffs,2017-18,Pinnacle Sports,238,1610612755,1610612738,204.5,204.5,-106.0,-104.0

<font color='red'> why is team_id_home going to float????<font>

In [8]:
pd.merge(df2, df, on='game_id', how='right').info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 14918 entries, 0 to 14917
Data columns (total 55 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   game_id       14918 non-null  int64
 1   game_date     14886 non-null  datetime64[ns]
 2   team_id_home  14886 non-null  float64
 3   w_pct_home    14886 non-null  float64
 4   min_home      14886 non-null  float64
 5   fgm_home      14886 non-null  float64
 6   fga_home      14886 non-null  float64
 7   fg_pct_home   14886 non-null  float64
 8   fg3m_home     14886 non-null  float64
 9   fg3a_home     14886 non-null  float64
 10  fg3_pct_home  14886 non-null  float64
 11  ftm_home      14886 non-null  float64
 12  fta_home      14886 non-null  float64
 13  ft_pct_home   14886 non-null  float64
 14  oreb_home     14886 non-null  float64
 15  dreb_home     14886 non-null  float64
 16  reb_home      14886 non-null  float64
 17  ast_home      14886 non-null  float64
 18  stl_home      14886 non-null  float64
 19  blk_home      14886 non-null  float64
 20  tov_home      14886 non-null  float64
 21  pf_home       14886 non-null  float64
 22  pts_home      14886 non-null  float64
 23  season_year   14886 non-null  float64
 24  team_id_away  14886 non-null  float64
 25  w_pct_away    14886 non-null  float64
 26  min_away      14886 non-null  float64
 27  fgm_away      14886 non-null  float64
 28  fga_away      14886 non-null  float64
 29  fg_pct_away   14886 non-null  float64
 30  fg3m_away     14886 non-null  float64
 31  fg3a_away     14886 non-null  float64
 32  fg3_pct_away  14886 non-null  float64
 33  ftm_away      14886 non-null  float64
 34  fta_away      14886 non-null  float64
 35  ft_pct_away   14886 non-null  float64
 36  oreb_away     14886 non-null  float64
 37  dreb_away     14886 non-null  float64
 38  reb_away      14886 non-null  float64
 39  ast_away      14886 non-null  float64
 40  stl_away      14886 non-null  float64
 41  blk_away      14886 non-null  float64
 42  tov_away      14886 non-null  float64
 43  pf_away       14886 non-null  float64
 44  pts_away      14886 non-null  float64
 45  season_type   14886 non-null  object
 46  season        14886 non-null  object
 47  book_name     14918 non-null  object
 48  book_id       14918 non-null  int64
 49  team_id       14918 non-null  int64
 50  a_team_id     14918 non-null  int64
 51  total1        14918 non-null  float64
 52  total2        14918 non-null  float64
 53  price1        14918 non-null  float64
 54  price2        14918 non-null  float64
dtypes: datetime64[ns](1), float64(47), int64(4), object(3)
memory usage: 6.4+ MB

In [9]:
df = pd.merge(df2, df, on='game_id', how='left')
df

,game_id,game_date,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,...,season_type,season,book_name,book_id,team_id,a_team_id,total1,total2,price1,price2
0,20600001,2006-10-31,1610612748,0.000,240,25.0,65.0,0.385,3.0,17.0,...,Regular Season,2006-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20600002,2006-10-31,1610612747,1.000,240,46.0,83.0,0.554,6.0,12.0,...,Regular Season,2006-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20600003,2006-11-01,1610612755,1.000,240,31.0,74.0,0.419,3.0,9.0,...,Regular Season,2006-07,Pinnacle Sports,238.0,1.610613e+09,1.610613e+09,199.0,199.0,-111.0,101.0
3,20600004,2006-11-01,1610612766,0.000,240,37.0,78.0,0.474,4.0,10.0,...,Regular Season,2006-07,Pinnacle Sports,238.0,1.610613e+09,1.610613e+09,193.5,193.5,-105.0,-105.0
4,20600005,2006-11-01,1610612753,1.000,240,35.0,59.0,0.593,6.0,8.0,...,Regular Season,2006-07,Pinnacle Sports,238.0,1.610613e+09,1.610613e+09,183.5,183.5,-105.0,-105.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15514,41700317,2018-05-28,1610612745,0.429,240,36.0,90.0,0.400,7.0,44.0,...,Playoffs,2017-18,Pinnacle Sports,238.0,1.610613e+09,1.610613e+09,208.5,208.5,-105.0,-105.0
15515,41700401,2018-05-31,1610612744,1.000,265,46.0,90.0,0.511,13.0,36.0,...,Playoffs,2017-18,Pinnacle Sports,238.0,1.610613e+09,1.610613e+09,217.5,217.5,-106.0,-104.0
15516,41700402,2018-06-03,1610612744,1.000,240,47.0,82.0,0.573,15.0,36.0,...,Playoffs,2017-18,Pinnacle Sports,238.0,1.610613e+09,1.610613e+09,216.5,216.5,103.0,-114.0
15517,41700403,2018-06-06,1610612739,0.000,240,40.0,92.0,0.435,9.0,31.0,...,Playoffs,2017-18,Pinnacle Sports,238.0,1.610613e+09,1.610613e+09,215.5,215.5,-113.0,102.0
15518,41700404,2018-06-08,1610612739,0.000,240,30.0,87.0,0.345,8.0,27.0,...,Playoffs,2017-18,Pinnacle Sports,238.0,1.610613e+09,1.610613e+09,216.5,216.5,-107.0,-103.0

In [10]:
pd.merge(df2, df, on='game_id', how='left').info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 15519 entries, 0 to 15518
Columns: 101 entries, game_id to price2
dtypes: datetime64[ns](2), float64(77), int64(17), object(5)
memory usage: 12.1+ MB

In [11]:
datapath = 'C:\\Users\\Paul\\sb\\DSCapstone2\\processed_data'

if not os.path.exists(datapath):
    os.mkdir(datapath)
    
datapath_df = os.path.join(datapath, '4game_id_date_stats_betting_totals.csv')
if not os.path.exists(datapath_df):
    df.to_csv(datapath_df, index=False)