In [28]:
import pandas as pd
import time
from nba_api.stats.endpoints import boxscoreadvancedv2
import os

pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

pd.set_option('max_colwidth', None)

In [29]:
#get advanced stats dataset to use player

df_or = pd.read_csv(os.path.join('..', 'processed_data', '5boxscoreadvancedv2_2010_2018.csv'))
df_or

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
0,20900001,1.610613e+09,BOS,Boston,1718.0,Paul Pierce,F,NaN,37:59,95.3,97.4,96.5,98.6,-1.2,-1.3,0.053,0.50,4.8,0.028,0.270,0.151,9.5,0.538,0.661,0.233,0.239,96.88,94.76,78.97,76.0,0.189
1,20900001,1.610613e+09,BOS,Boston,708.0,Kevin Garnett,F,NaN,33:05,95.6,95.5,101.0,103.1,-5.4,-7.6,0.059,1.00,7.1,0.097,0.233,0.164,7.1,0.500,0.553,0.178,0.181,95.96,95.03,79.19,66.0,0.147
2,20900001,1.610613e+09,BOS,Boston,2570.0,Kendrick Perkins,C,NaN,25:42,99.2,100.0,108.2,104.3,-9.1,-4.3,0.077,0.33,9.1,0.000,0.050,0.024,27.3,0.571,0.605,0.196,0.198,86.53,87.77,73.14,47.0,0.030
3,20900001,1.610613e+09,BOS,Boston,951.0,Ray Allen,G,NaN,42:21,105.2,108.8,105.4,105.1,-0.2,3.7,0.120,1.00,12.5,0.000,0.054,0.028,12.5,0.375,0.440,0.236,0.240,91.50,90.12,75.10,80.0,0.051
4,20900001,1.610613e+09,BOS,Boston,200765.0,Rajon Rondo,G,NaN,34:29,92.7,94.1,98.0,97.1,-5.3,-3.0,0.526,5.00,50.0,0.061,0.125,0.092,10.0,0.500,0.500,0.130,0.133,95.63,95.36,79.46,68.0,0.158
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291638,41700404,1.610613e+09,CLE,Cleveland,1626204.0,Larry Nance Jr.,NaN,NaN,23:12,93.4,97.6,93.1,95.2,0.3,2.3,0.333,0.00,33.3,0.176,0.077,0.133,0.0,0.429,0.444,0.148,0.146,88.76,85.87,71.56,41.0,0.139
291639,41700404,1.610613e+09,CLE,Cleveland,1626224.0,Cedi Osman,NaN,NaN,4:03,100.0,114.3,76.1,75.0,23.9,39.3,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.333,0.333,0.333,0.333,94.10,88.89,74.07,7.0,0.000
291640,41700404,1.610613e+09,CLE,Cleveland,101181.0,Jose Calderon,NaN,NaN,4:03,100.0,114.3,76.1,75.0,23.9,39.3,0.250,0.00,50.0,0.000,0.200,0.100,0.0,0.000,0.000,0.111,0.111,94.10,88.89,74.07,7.0,0.174
291641,41700404,1.610613e+09,CLE,Cleveland,1627790.0,Ante Zizic,NaN,NaN,1:40,100.0,133.3,0.0,0.0,100.0,133.3,0.000,0.00,0.0,0.333,0.000,0.200,0.0,1.000,1.000,0.400,0.400,100.80,86.40,72.00,3.0,2.250
291642,41700404,1.610613e+09,CLE,Cleveland,203903.0,Jordan Clarkson,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN

In [30]:
from nba_api.stats.endpoints import boxscoreplayertrackv2

boxscoreplayertrackv2.BoxScorePlayerTrackV2(game_id='0041700404').get_data_frames()[0]

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,SPD,DIST,ORBC,DRBC,RBC,TCHS,SAST,FTAST,PASS,AST,CFGM,CFGA,CFG_PCT,UFGM,UFGA,UFG_PCT,FG_PCT,DFGM,DFGA,DFG_PCT
0,0041700404,1610612744,GSW,Golden State,201142,Kevin Durant,F,,37:38,3.91,2.45,5,14,17,78,1,0,55,10,5,11,0.455,2,6,0.333,0.412,3,6,0.500
1,0041700404,1610612744,GSW,Golden State,203110,Draymond Green,F,,38:37,3.99,2.56,2,14,16,91,0,1,75,9,1,1,1.000,3,7,0.429,0.500,4,7,0.571
2,0041700404,1610612744,GSW,Golden State,201580,JaVale McGee,C,,16:28,4.30,1.18,5,3,8,15,0,0,11,0,1,2,0.500,2,2,1.000,0.750,0,0,0.000
3,0041700404,1610612744,GSW,Golden State,202691,Klay Thompson,G,,28:30,4.30,2.04,2,11,13,31,1,0,19,0,0,3,0.000,4,7,0.571,0.400,3,3,1.000
4,0041700404,1610612744,GSW,Golden State,201939,Stephen Curry,G,,38:45,4.54,2.92,4,13,16,95,0,0,59,4,6,12,0.500,6,15,0.400,0.444,0,1,0.000
5,0041700404,1610612744,GSW,Golden State,2738,Andre Iguodala,,,22:41,4.04,1.52,3,3,6,34,0,0,24,0,0,1,0.000,4,7,0.571,0.500,2,2,1.000
6,0041700404,1610612744,GSW,Golden State,1628395,Jordan Bell,,,18:24,4.30,1.32,4,4,8,27,0,0,23,1,1,2,0.500,1,1,1.000,0.667,1,5,0.200
7,0041700404,1610612744,GSW,Golden State,2733,Shaun Livingston,,,14:04,4.20,0.98,2,4,6,22,1,0,19,0,0,0,0.000,0,1,0.000,0.000,0,0,0.000
8,0041700404,1610612744,GSW,Golden State,201156,Nick Young,,,8:59,3.84,0.58,0,3,3,9,0,0,5,0,0,1,0.000,1,3,0.333,0.250,0,0,0.000
9,0041700404,1610612744,GSW,Golden State,2561,David West,,,7:36,3.88,0.49,0,0,0,11,0,0,10,1,1,1,1.000,0,0,0.000,1.000,1,1,1.000
10,0041700404,1610612744,GSW,Golden State,1626172,Kevon Looney,,,2:47,3.81,0.18,1,0,1,5,0,0,3,0,0,0,0.000,1,2,0.500,0.500,1,1,1.000
11,0041700404,1610612744,GSW,Golden State,2585,Zaza Pachulia,,,2:47,4.00,0.19,2,1,3,6,0,0,3,0,0,1,0.000,0,0,0.000,0.000,0,0,0.000
12,0041700404,1610612744,GSW,Golden State,1627775,Patrick McCaw,,,2:47,3.78,0.18,1,0,1,8,0,0,8,0,0,0,0.000,0,0,0.000,0.000,0,0,0.000
13,0041700404,1610612739,CLE,Cleveland,2544,LeBron James,F,,40:34,3.78,2.55,3,8,11,103,2,0,71,8,3,8,0.375,4,5,0.800,0.538,1,3,0.333
14,0041700404,1610612739,CLE,Cleveland,201567,Kevin Love,F,,27:44,4.11,1.89,7,9,16,56,0,1,40,2,1,4,0.250,3,9,0.333,0.308,1,2,0.500
15,0041700404,1610612739,CLE,Cleveland,202684,Tristan Thompson,C,,16:12,4.44,1.19,9,6,15,22,0,0,16,0,2,4,0.500,1,1,1.000,0.600,2,3,0.667
16,0041700404,1610612739,CLE,Cleveland,2747,JR Smith,G,,26:35,4.12,1.82,2,5,7,33,0,0,24,1,0,3,0.000,3,5,0.600,0.375,1,1,1.000
17,0041700404,1610612739,CLE,Cleveland,201588,George Hill,G,,25:05,4.26,1.78,3,5,8,40,0,0,30,1,0,2,0.000,1,5,0.200,0.143,3,3,1.000
18,0041700404,1610612739,CLE,Cleveland,203918,Rodney Hood,,,26:32,4.31,1.90,7,9,16,50,0,0,33,2,2,8,0.250,2,6,0.333,0.286,0,0,0.000
19,0041700404,1610612739,CLE,Cleveland,201145,Jeff Green,,,23:40,3.92,1.54,0,0,0,27,1,0,18,1,0,2,0.000,2,6,0.333,0.250,1,1,1.000
20,0041700404,1610612739,CLE,Cleveland,2594,Kyle Korver,,,20:42,4.49,1.55,0,2,2,19,0,0,12,1,0,0,0.000,0,6,0.000,0.000,2,2,1.000
21,0041700404,1610612739,CLE,Cleveland,1626204,Larry Nance Jr.,,,23:12,4.31,1.66,11,6,17,33,0,0,24,4,3,5,0.600,0,2,0.000,0.429,3,4,0.750
22,0041700404,1610612739,CLE,Cleveland,1626224,Cedi Osman,,,4:03,3.84,0.26,0,0,0,5,0,0,2,0,1,1,1.000,0,2,0.000,0.333,0,0,0.000
23,0041700404,1610612739,CLE,Cleveland,101181,Jose Calderon,,,4:03,3.61,0.25,0,2,2,9,1,0,8,1,0,0,0.000,0,1,0.000,0.000,1,1,1.000
24,0041700404,1610612739,CLE,Cleveland,1627790,Ante Zizic,,,1:40,3.34,0.09,1,1,2,3,0,0,1,0,1,1,1.000,1,1,1.000,1.000,0,0,0.000
25,0041700404,1610612739,CLE,Cleveland,203903,Jordan Clarkson,,DNP - Coach's Decision,0:00,0.00,0.00,0,0,0,0,0,0,0,0,0,0,0.000,0,0,0.000,0.000,0,0,0.000

In [36]:
boxscoreplayertrackv2.BoxScorePlayerTrackV2(game_id='0041700404').get_data_frames()[1]

,GAME_ID,TEAM_ID,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,DIST,ORBC,DRBC,RBC,TCHS,SAST,FTAST,PASS,AST,CFGM,CFGA,CFG_PCT,UFGM,UFGA,UFG_PCT,FG_PCT,DFGM,DFGA,DFG_PCT
0,0041700404,1610612744,Warriors,GSW,Golden State,240:00,16.57,31,70,98,432,3,1,314,25,15,35,0.429,24,51,0.471,0.453,15,26,0.577
1,0041700404,1610612739,Cavaliers,CLE,Cleveland,240:00,16.48,43,53,96,400,4,1,279,21,13,38,0.342,17,49,0.347,0.345,15,20,0.750

In [37]:
boxscoreplayertrackv2.BoxScorePlayerTrackV2(game_id='0041700404').get_data_frames()[2]

IndexError: list index out of range

In [31]:
boxscoreadvancedv2.BoxScoreAdvancedV2(game_id='0020900001').get_data_frames()[0]

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
0,0020900001,1610612738,BOS,Boston,1718,Paul Pierce,F,,37:59,95.3,97.4,96.5,98.6,-1.2,-1.3,0.053,0.50,4.8,0.028,0.270,0.151,9.5,0.538,0.661,0.233,0.239,96.88,94.76,78.97,76,0.189
1,0020900001,1610612738,BOS,Boston,708,Kevin Garnett,F,,33:05,95.6,95.5,101.0,103.1,-5.4,-7.6,0.059,1.00,7.1,0.097,0.233,0.164,7.1,0.500,0.553,0.178,0.181,95.96,95.03,79.19,66,0.147
2,0020900001,1610612738,BOS,Boston,2570,Kendrick Perkins,C,,25:42,99.2,100.0,108.2,104.3,-9.1,-4.3,0.077,0.33,9.1,0.000,0.050,0.024,27.3,0.571,0.605,0.196,0.198,86.53,87.77,73.14,47,0.030
3,0020900001,1610612738,BOS,Boston,951,Ray Allen,G,,42:21,105.2,108.8,105.4,105.1,-0.2,3.7,0.120,1.00,12.5,0.000,0.054,0.028,12.5,0.375,0.440,0.236,0.240,91.50,90.12,75.10,80,0.051
4,0020900001,1610612738,BOS,Boston,200765,Rajon Rondo,G,,34:29,92.7,94.1,98.0,97.1,-5.3,-3.0,0.526,5.00,50.0,0.061,0.125,0.092,10.0,0.500,0.500,0.130,0.133,95.63,95.36,79.46,68,0.158
5,0020900001,1610612738,BOS,Boston,739,Rasheed Wallace,,,23:50,105.9,110.9,88.7,89.1,17.2,21.7,0.000,0.00,0.0,0.000,0.125,0.068,0.0,0.611,0.607,0.189,0.195,95.03,92.62,77.18,46,0.082
6,0020900001,1610612738,BOS,Boston,2605,Marquis Daniels,,,17:33,125.5,118.8,77.8,79.4,47.7,39.3,0.250,2.00,25.0,0.000,0.053,0.033,12.5,0.700,0.700,0.171,0.192,88.86,90.23,75.19,32,0.169
7,0020900001,1610612738,BOS,Boston,200749,Shelden Williams,,,12:30,110.4,108.7,78.8,78.3,31.6,30.4,0.000,0.00,0.0,0.000,0.214,0.136,25.0,0.000,0.725,0.160,0.177,87.30,88.30,73.58,23,0.070
8,0020900001,1610612738,BOS,Boston,2067,Eddie House,,,12:30,111.1,118.2,90.3,90.9,20.9,27.3,0.333,2.00,33.3,0.000,0.083,0.048,16.7,0.500,0.500,0.167,0.171,87.50,84.50,70.42,22,0.091
9,0020900001,1610612738,BOS,Boston,201592,J.R. Giddens,,DNP - Coach's Decision,None,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0,NaN
10,0020900001,1610612738,BOS,Boston,201991,Lester Hudson,,DNP - Coach's Decision,None,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0,NaN
11,0020900001,1610612738,BOS,Boston,2243,Brian Scalabrine,,NWT- Right Ankle Sprain,None,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0,NaN
12,0020900001,1610612739,CLE,Cleveland,2544,LeBron James,F,,44:55,99.8,101.2,99.2,101.2,0.5,0.0,0.471,1.60,19.5,0.000,0.100,0.049,12.2,0.636,0.685,0.351,0.354,93.44,91.90,76.59,86,0.240
13,0020900001,1610612739,CLE,Cleveland,2760,Anderson Varejao,F,,32:50,109.3,108.2,115.5,116.1,-6.1,-7.9,0.050,0.00,8.3,0.179,0.091,0.140,0.0,0.333,0.418,0.167,0.168,89.69,89.89,74.91,61,0.040
14,0020900001,1610612739,CLE,Cleveland,406,Shaquille O'Neal,C,,28:48,98.5,96.4,95.5,96.2,3.0,0.1,0.083,1.00,7.1,0.000,0.385,0.200,7.1,0.455,0.421,0.213,0.221,89.33,89.99,75.00,55,0.121
15,0020900001,1610612739,CLE,Cleveland,1515,Anthony Parker,G,,40:10,108.0,107.8,101.4,103.9,6.6,3.9,0.160,1.33,23.5,0.000,0.083,0.042,17.6,0.444,0.506,0.153,0.157,93.10,92.03,76.69,77,0.076
16,0020900001,1610612739,CLE,Cleveland,2590,Mo Williams,G,,35:02,98.9,92.8,109.1,107.2,-10.2,-14.5,0.167,1.50,18.8,0.000,0.000,0.000,12.5,0.375,0.564,0.176,0.187,90.74,94.53,78.77,69,0.044
17,0020900001,1610612739,CLE,Cleveland,980,Zydrunas Ilgauskas,,,24:39,86.4,85.4,88.3,91.5,-1.9,-6.1,0.000,0.00,0.0,0.042,0.154,0.100,0.0,0.250,0.521,0.118,0.124,93.69,92.52,77.10,48,0.124
18,0020900001,1610612739,CLE,Cleveland,200789,Daniel Gibson,,,13:42,79.3,85.7,99.0,96.6,-19.7,-10.8,0.000,0.00,0.0,0.000,0.083,0.036,25.0,0.333,0.291,0.133,0.132,102.55,99.82,83.18,28,-0.125
19,0020900001,1610612739,CLE,Cleveland,201581,JJ Hickson,,,6:13,45.0,46.2,85.0,90.9,-40.0,-44.8,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.071,0.075,96.80,92.63,77.19,13,-0.500
20,0020900001,1610612739,CLE,Cleveland,200081,Jamario Moon,,,13:41,79.5,80.8,106.1,115.4,-26.5,-34.6,0.000,0.00,0.0,0.000,0.200,0.077,25.0,0.333,0.333,0.143,0.141,95.96,91.26,76.05,26,0.017
21,0020900001,1610612739,CLE,Cleveland,201616,Darnell Jackson,,DNP - Coach's Decision,None,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0,NaN
22,0020900001,1610612739,CLE,Cleveland,201207,Coby Karl,,DNP - Coach's Decision,None,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0,NaN
23,0020900001,1610612739,CLE,Cleveland,101214,Jawad Williams,,DNP - Coach's Decision,None,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0,NaN

In [32]:
boxscoreadvancedv2.BoxScoreAdvancedV2(game_id='0020900001').get_data_frames()[1]

,GAME_ID,TEAM_ID,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
0,0020900001,1610612739,Cavaliers,CLE,Cleveland,240:00,96.7,97.8,101.7,104.4,-5.0,-6.6,0.586,1.21,14.8,0.222,0.732,0.465,15.204,15.4,0.457,0.529,1.0,0.200,92.76,91.0,75.83,91,0.451
1,0020900001,1610612738,Celtics,BOS,Boston,240:00,101.7,104.4,96.7,97.8,5.0,6.6,0.625,1.25,16.7,0.268,0.778,0.535,17.123,17.6,0.507,0.569,1.0,0.197,92.76,91.0,75.83,91,0.549

In [35]:
boxscoreadvancedv2.BoxScoreAdvancedV2(game_id='0020900001').get_data_frames()[2]

IndexError: list index out of range

In [50]:
boxscoreadvancedv2.BoxScoreAdvancedV2(game_id='0021000005').get_data_frames()[0]

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
0,0021000005,1610612765,DET,Detroit,2419,Tayshaun Prince,F,,31:26,108.3,105.1,112.6,117.5,-4.3,-12.5,0.056,0.00,7.1,0.000,0.071,0.033,0.0,0.500,0.535,0.197,0.209,89.10,88.55,73.80,59,0.080
1,0021000005,1610612765,DET,Detroit,201948,Austin Daye,F,,21:11,101.9,102.7,111.9,113.5,-10.0,-10.8,0.077,0.00,11.1,0.000,0.167,0.079,0.0,0.250,0.250,0.186,0.194,84.73,83.82,69.85,37,0.000
2,0021000005,1610612765,DET,Detroit,1112,Ben Wallace,C,,27:00,102.3,96.0,118.0,122.4,-15.7,-26.4,0.063,1.00,11.1,0.115,0.304,0.204,11.1,0.667,0.460,0.140,0.154,86.88,87.98,73.32,50,0.086
3,0021000005,1610612765,DET,Detroit,1888,Richard Hamilton,G,,31:49,106.1,101.7,121.6,125.9,-15.5,-24.2,0.176,3.00,16.7,0.030,0.115,0.068,5.6,0.464,0.464,0.221,0.236,88.66,89.02,74.19,60,0.097
4,0021000005,1610612765,DET,Detroit,201155,Rodney Stuckey,G,,29:23,110.6,107.3,115.1,120.8,-4.5,-13.5,0.389,0.00,35.0,0.034,0.083,0.057,0.0,0.450,0.554,0.210,0.223,89.00,88.21,73.51,55,0.148
5,0021000005,1610612765,DET,Detroit,101198,Will Bynum,,,18:37,100.4,102.6,97.5,102.8,2.9,-0.1,0.167,0.00,15.4,0.043,0.100,0.070,0.0,0.350,0.442,0.244,0.251,99.01,95.40,79.50,38,0.114
6,0021000005,1610612765,DET,Detroit,2732,Ben Gordon,,,23:25,97.7,100.0,114.5,119.1,-16.8,-19.1,0.214,1.50,25.0,0.000,0.042,0.018,16.7,0.917,0.872,0.158,0.160,101.55,98.39,81.99,49,0.103
7,0021000005,1610612765,DET,Detroit,101111,Charlie Villanueva,,,22:49,109.3,110.4,87.8,93.3,21.5,17.1,0.000,0.00,0.0,0.037,0.083,0.059,9.1,0.700,0.700,0.200,0.206,101.29,97.79,81.50,48,0.120
8,0021000005,1610612765,DET,Detroit,101131,Jason Maxiell,,,20:34,113.9,120.5,95.2,102.6,18.6,17.9,0.000,0.00,0.0,0.087,0.200,0.140,9.1,0.556,0.511,0.239,0.238,95.97,89.85,74.88,39,0.135
9,0021000005,1610612765,DET,Detroit,1503,Tracy McGrady,,,13:45,113.5,125.9,87.3,92.6,26.2,33.3,0.231,0.00,50.0,0.063,0.077,0.069,0.0,0.000,0.000,0.091,0.088,102.28,94.25,78.55,27,0.053
10,0021000005,1610612765,DET,Detroit,202328,Greg Monroe,,DNP - Coach's Decision,None,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0,NaN
11,0021000005,1610612765,DET,Detroit,201969,DaJuan Summers,,DNP - Coach's Decision,None,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0,NaN
12,0021000005,1610612751,NJN,New Jersey,2566,Travis Outlaw,F,,21:24,95.2,102.6,104.7,112.8,-9.4,-10.2,0.000,0.00,0.0,0.000,0.120,0.065,11.1,0.214,0.317,0.205,0.205,93.08,86.36,71.96,38,-0.065
13,0021000005,1610612751,NJN,New Jersey,693,Joe Smith,F,,5:25,101.4,100.0,85.0,100.0,16.3,0.0,0.000,0.00,0.0,0.000,0.125,0.077,0.0,0.000,0.000,0.111,0.113,91.45,84.18,70.15,9,-0.105
14,0021000005,1610612751,NJN,New Jersey,201572,Brook Lopez,C,,37:15,114.1,114.5,101.6,105.8,12.5,8.7,0.000,0.00,0.0,0.097,0.150,0.127,4.3,0.550,0.574,0.299,0.302,90.94,88.92,74.10,69,0.168
15,0021000005,1610612751,NJN,New Jersey,201627,Anthony Morrow,G,,37:21,113.9,117.6,108.1,104.2,5.8,13.4,0.000,0.00,0.0,0.030,0.026,0.028,0.0,0.650,0.623,0.130,0.129,89.11,89.32,74.43,68,0.063
16,0021000005,1610612751,NJN,New Jersey,2734,Devin Harris,G,,30:43,119.9,122.8,106.7,110.3,13.3,12.5,0.500,3.00,31.0,0.000,0.121,0.067,10.3,0.533,0.624,0.317,0.316,92.48,89.85,74.88,57,0.227
17,0021000005,1610612751,NJN,New Jersey,202324,Derrick Favors,,,20:00,87.3,89.7,110.6,105.1,-23.2,-15.4,0.000,0.00,0.0,0.150,0.318,0.238,12.5,0.600,0.592,0.174,0.181,92.59,93.60,78.00,39,0.175
18,0021000005,1610612751,NJN,New Jersey,201944,Terrence Williams,,,32:22,116.2,122.2,102.5,98.4,13.8,23.8,0.167,1.33,25.0,0.000,0.171,0.092,18.8,0.625,0.563,0.160,0.159,94.70,94.17,78.48,63,0.072
19,0021000005,1610612751,NJN,New Jersey,200770,Jordan Farmar,,,22:00,110.5,118.6,100.8,100.0,9.7,18.6,0.250,2.00,28.6,0.000,0.000,0.000,14.3,0.500,0.644,0.200,0.199,100.15,97.09,80.91,43,0.127
20,0021000005,1610612751,NJN,New Jersey,101130,Johan Petro,,,9:05,98.4,105.3,115.5,111.1,-17.0,-5.8,0.000,0.00,0.0,0.100,0.182,0.143,0.0,0.500,0.500,0.087,0.090,99.51,97.82,81.51,19,0.097
21,0021000005,1610612751,NJN,New Jersey,2743,Kris Humphries,,,18:09,100.3,109.4,131.6,128.1,-31.2,-18.8,0.000,0.00,0.0,0.067,0.417,0.222,0.0,1.000,1.000,0.056,0.054,87.33,84.63,70.52,32,0.109
22,0021000005,1610612751,NJN,New Jersey,101211,Stephen Graham,,,2:18,50.0,40.0,82.0,80.0,-32.0,-40.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.200,0.250,92.93,104.65,87.21,5,-0.167
23,0021000005,1610612751,NJN,New Jersey,202345,Damion James,,,3:59,94.8,100.0,107.3,111.1,-12.5,-11.1,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.333,0.291,0.300,0.287,107.01,102.43,85.36,8,-0.222

In [49]:
boxscoreadvancedv2.BoxScoreAdvancedV2(game_id='0021000005').get_data_frames()[1]

,GAME_ID,TEAM_ID,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
0,0021000005,1610612751,Nets,NJN,New Jersey,240:00,108.0,113.5,106.3,108.9,1.7,4.6,0.436,1.42,14.2,0.318,0.712,0.531,12.826,13.5,0.525,0.558,1.0,0.197,92.88,89.5,74.58,89,0.519
1,0021000005,1610612765,Pistons,DET,Detroit,240:00,106.3,108.9,108.0,113.5,-1.7,-4.6,0.568,3.50,17.0,0.288,0.682,0.469,6.508,6.7,0.494,0.509,1.0,0.200,92.88,89.5,74.58,90,0.481

In [55]:
from nba_api.stats.endpoints import commonallplayers
from nba_api.stats.endpoints import commonallplayers

In [59]:
commonallplayers.CommonAllPlayers(season='2010-11').get_data_frames()[0]

,PERSON_ID,DISPLAY_LAST_COMMA_FIRST,DISPLAY_FIRST_LAST,ROSTERSTATUS,FROM_YEAR,TO_YEAR,PLAYERCODE,TEAM_ID,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CODE,GAMES_PLAYED_FLAG,OTHERLEAGUE_EXPERIENCE_CH
0,76001,"Abdelnaby, Alaa",Alaa Abdelnaby,0,1990,1994,HISTADD_alaa_abdelnaby,0,,,,,Y,00
1,76002,"Abdul-Aziz, Zaid",Zaid Abdul-Aziz,0,1968,1977,HISTADD_zaid_abdul-aziz,0,,,,,Y,00
2,76003,"Abdul-Jabbar, Kareem",Kareem Abdul-Jabbar,0,1969,1988,HISTADD_kareem_abdul-jabbar,0,,,,,Y,00
3,51,"Abdul-Rauf, Mahmoud",Mahmoud Abdul-Rauf,0,1990,2000,mahmoud_abdul-rauf,0,,,,,Y,00
4,1505,"Abdul-Wahad, Tariq",Tariq Abdul-Wahad,0,1997,2003,tariq_abdul-wahad,0,,,,,Y,00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4594,1627790,"Zizic, Ante",Ante Zizic,0,2017,2019,ante_zizic,0,,,,,Y,01
4595,78647,"Zoet, Jim",Jim Zoet,0,1982,1982,HISTADD_jim_zoet,0,,,,,Y,00
4596,78648,"Zopf, Bill",Bill Zopf,0,1970,1970,HISTADD_zip_zopf,0,,,,,Y,00
4597,1627826,"Zubac, Ivica",Ivica Zubac,0,2016,2020,ivica_zubac,0,,,,,Y,01
4598,78650,"Zunic, Matt",Matt Zunic,0,1948,1948,HISTADD_matt_zunic,0,,,,,Y,00

In [60]:
commonallplayers.CommonAllPlayers().get_data_frames()[0]

,PERSON_ID,DISPLAY_LAST_COMMA_FIRST,DISPLAY_FIRST_LAST,ROSTERSTATUS,FROM_YEAR,TO_YEAR,PLAYERCODE,TEAM_ID,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CODE,GAMES_PLAYED_FLAG,OTHERLEAGUE_EXPERIENCE_CH
0,76001,"Abdelnaby, Alaa",Alaa Abdelnaby,0,1990,1994,HISTADD_alaa_abdelnaby,0,,,,,Y,00
1,76002,"Abdul-Aziz, Zaid",Zaid Abdul-Aziz,0,1968,1977,HISTADD_zaid_abdul-aziz,0,,,,,Y,00
2,76003,"Abdul-Jabbar, Kareem",Kareem Abdul-Jabbar,0,1969,1988,HISTADD_kareem_abdul-jabbar,0,,,,,Y,00
3,51,"Abdul-Rauf, Mahmoud",Mahmoud Abdul-Rauf,0,1990,2000,mahmoud_abdul-rauf,0,,,,,Y,00
4,1505,"Abdul-Wahad, Tariq",Tariq Abdul-Wahad,0,1997,2003,tariq_abdul-wahad,0,,,,,Y,00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4594,1627790,"Zizic, Ante",Ante Zizic,0,2017,2019,ante_zizic,0,,,,,Y,01
4595,78647,"Zoet, Jim",Jim Zoet,0,1982,1982,HISTADD_jim_zoet,0,,,,,Y,00
4596,78648,"Zopf, Bill",Bill Zopf,0,1970,1970,HISTADD_zip_zopf,0,,,,,Y,00
4597,1627826,"Zubac, Ivica",Ivica Zubac,1,2016,2020,ivica_zubac,1610612746,LA,Clippers,LAC,clippers,Y,01
4598,78650,"Zunic, Matt",Matt Zunic,0,1948,1948,HISTADD_matt_zunic,0,,,,,Y,00

In [63]:
#commonallplayers.CommonAllPlayers().get_data_frames()[1]

IndexError: list index out of range

In [ ]:
#help(commonallplayers)

In [64]:
from nba_api.stats.endpoints import commonteamroster

In [71]:
commonteamroster.CommonTeamRoster(team_id='001610612751', season='2010-11').get_data_frames()[0]

,TeamID,SEASON,LeagueID,PLAYER,PLAYER_SLUG,NUM,POSITION,HEIGHT,WEIGHT,BIRTH_DATE,AGE,EXP,SCHOOL,PLAYER_ID
0,1610612751,2010,00,Sundiata Gaines,sundiata-gaines,0,G,6-1,200,"APR 18, 1986",25.0,1,Georgia,202178
1,1610612751,2010,00,Jordan Farmar,jordan-farmar,2,G,6-2,180,"NOV 30, 1986",24.0,4,UCLA,200770
2,1610612751,2010,00,Mario West,mario-west,6,G,6-5,210,"JUN 19, 1984",27.0,3,Georgia Tech,201238
3,1610612751,2010,00,Deron Williams,deron-williams,8,G,6-3,209,"JUN 26, 1984",27.0,5,Illinois,101114
4,1610612751,2010,00,Damion James,damion-james,10,F,6-7,220,"OCT 07, 1987",23.0,R,Texas-Austin,202345
5,1610612751,2010,00,Brook Lopez,brook-lopez,11,C,7-0,265,"APR 01, 1988",23.0,2,Stanford,201572
6,1610612751,2010,00,Ben Uzoh,ben-uzoh,18,G,6-3,205,"MAR 18, 1988",23.0,R,Tulsa,202386
7,1610612751,2010,00,Sasha Vujacic,sasha-vujacic,20,G,6-7,205,"MAR 08, 1984",27.0,6,Udine,2756
8,1610612751,2010,00,Travis Outlaw,travis-outlaw,21,F,6-9,207,"SEP 18, 1984",26.0,7,Starkville HS (MS),2566
9,1610612751,2010,00,Anthony Morrow,anthony-morrow,22,G,6-5,210,"SEP 27, 1985",25.0,2,Georgia Tech,201627
10,1610612751,2010,00,Stephen Graham,stephen-graham,26,G-F,6-6,215,"JUN 11, 1982",29.0,5,Oklahoma State,101211
11,1610612751,2010,00,Johan Petro,johan-petro,27,C,7-0,247,"JAN 27, 1986",25.0,5,Pau Orthez,101130
12,1610612751,2010,00,Brandan Wright,brandan-wright,34,F,6-10,210,"OCT 05, 1987",23.0,2,North Carolina,201148
13,1610612751,2010,00,Kris Humphries,kris-humphries,43,F,6-9,235,"FEB 06, 1985",26.0,6,Minnesota,2743
14,1610612751,2010,00,Dan Gadzuric,dan-gadzuric,50,C,6-11,240,"FEB 02, 1978",33.0,8,UCLA,2429

In [73]:
commonteamroster.CommonTeamRoster(team_id='001610612751', season='2010-11').get_data_frames()[1]

,TEAM_ID,SEASON,COACH_ID,FIRST_NAME,LAST_NAME,COACH_NAME,IS_ASSISTANT,COACH_TYPE,SORT_SEQUENCE,SUB_SORT_SEQUENCE
0,1610612751,2010,2885,Avery,Johnson,Avery Johnson,1,Head Coach,None,1
1,1610612751,2010,202434,Popeye,Jones,Popeye Jones,2,Assistant Coach,None,5
2,1610612751,2010,2517,Sam,Mitchell,Sam Mitchell,2,Assistant Coach,None,5
3,1610612751,2010,2703,John,Loyer,John Loyer,2,Assistant Coach,None,5
4,1610612751,2010,2806,Tom,Barrise,Tom Barrise,2,Assistant Coach,None,5
5,1610612751,2010,200869,Larry,Krystkowiak,Larry Krystkowiak,2,Assistant Coach,None,5
6,1610612751,2010,1673,Rich,Dalatri,Rich Dalatri,2,Assistant Coach,None,5
7,1610612751,2010,1303,Tim,Walsh,Tim Walsh,3,Trainer,None,7

In [74]:
#commonteamroster.CommonTeamRoster(team_id='001610612751', season='2010-11').get_data_frames()[2]

IndexError: list index out of range

In [72]:
commonteamroster.CommonTeamRoster(team_id='001610612765', season='2010-11').get_data_frames()[0]

,TeamID,SEASON,LeagueID,PLAYER,PLAYER_SLUG,NUM,POSITION,HEIGHT,WEIGHT,BIRTH_DATE,AGE,EXP,SCHOOL,PLAYER_ID
0,1610612765,2010,00,Tracy McGrady,tracy-mcgrady,1,G,6-8,223,"MAY 24, 1979",32.0,13,Mount Zion Christian Academy (NC),1503
1,1610612765,2010,00,Rodney Stuckey,rodney-stuckey,3,G,6-5,205,"APR 21, 1986",25.0,3,Eastern Washington,201155
2,1610612765,2010,00,Austin Daye,austin-daye,5,F,6-11,200,"JUN 05, 1988",23.0,1,Gonzaga,201948
3,1610612765,2010,00,Ben Wallace,ben-wallace,6,C,6-9,240,"SEP 10, 1974",36.0,14,Virginia Union,1112
4,1610612765,2010,00,Ben Gordon,ben-gordon,7,G,6-3,200,"APR 04, 1983",28.0,6,Connecticut,2732
5,1610612765,2010,00,Chris Wilcox,chris-wilcox,9,C,6-10,235,"SEP 03, 1982",28.0,8,Maryland,2404
6,1610612765,2010,00,Greg Monroe,greg-monroe,10,C-F,6-11,250,"JUN 04, 1990",21.0,R,Georgetown,202328
7,1610612765,2010,00,Will Bynum,will-bynum,12,G,6-0,185,"JAN 04, 1983",28.0,3,Georgia Tech,101198
8,1610612765,2010,00,Tayshaun Prince,tayshaun-prince,22,F,6-9,215,"FEB 28, 1980",31.0,8,Kentucky,2419
9,1610612765,2010,00,Terrico White,terrico-white,23,G,6-5,213,"MAR 07, 1990",21.0,R,Mississippi,202358
10,1610612765,2010,00,Charlie Villanueva,charlie-villanueva,31,F,6-11,232,"AUG 24, 1984",26.0,5,Connecticut,101111
11,1610612765,2010,00,Richard Hamilton,richard-hamilton,32,G,6-7,193,"FEB 14, 1978",33.0,11,Connecticut,1888
12,1610612765,2010,00,Jonas Jerebko,jonas-jerebko,33,F,6-10,231,"MAR 02, 1987",24.0,1,,201973
13,1610612765,2010,00,DaJuan Summers,dajuan-summers,35,F,6-8,240,"JAN 24, 1988",23.0,1,Georgetown,201969
14,1610612765,2010,00,Jason Maxiell,jason-maxiell,54,F,6-7,260,"FEB 18, 1983",28.0,5,Cincinnati,101131

In [78]:
from nba_api.stats.endpoints import leaguedashplayerbiostats

In [80]:
leaguedashplayerbiostats.LeagueDashPlayerBioStats(season='2010-11').get_data_frames()[0]

,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,AGE,PLAYER_HEIGHT,PLAYER_HEIGHT_INCHES,PLAYER_WEIGHT,COLLEGE,COUNTRY,DRAFT_YEAR,DRAFT_ROUND,DRAFT_NUMBER,GP,PTS,REB,AST,NET_RATING,OREB_PCT,DREB_PCT,USG_PCT,TS_PCT,AST_PCT
0,201985,AJ Price,1610612754,IND,24.0,6-2,74,181,Connecticut,USA,2009,2,52,50,323,72,111,2.2,0.019,0.073,0.223,0.454,0.233
1,201166,Aaron Brooks,1610612756,PHX,26.0,6-0,72,161,Oregon,USA,2007,1,26,59,634,78,233,-6.6,0.015,0.046,0.251,0.489,0.289
2,201189,Aaron Gray,1610612740,NOH,26.0,7-0,84,270,Pittsburgh,USA,2007,2,49,41,129,171,16,3.9,0.121,0.236,0.130,0.566,0.044
3,201151,Acie Law,1610612744,GSW,26.0,6-3,75,202,Texas A&M,USA,2007,1,11,51,215,63,84,-8.7,0.017,0.072,0.156,0.502,0.182
4,1733,Al Harrington,1610612743,DEN,31.0,6-9,81,250,None,USA,1998,1,25,73,765,332,101,4.8,0.047,0.157,0.219,0.527,0.096
5,201143,Al Horford,1610612737,ATL,25.0,6-10,82,245,Florida,Dominican Republic,2007,1,3,77,1178,718,266,0.7,0.073,0.210,0.197,0.587,0.169
6,2744,Al Jefferson,1610612762,UTA,26.0,6-10,82,280,None,USA,2004,1,15,82,1528,794,149,-3.1,0.085,0.202,0.239,0.528,0.090
7,201154,Al Thornton,1610612744,GSW,27.0,6-8,80,235,Florida State,USA,2007,1,14,71,524,213,62,-5.0,0.042,0.122,0.179,0.531,0.072
8,202329,Al-Farouq Aminu,1610612746,LAC,20.0,6-9,81,215,Wake Forest,USA,2010,1,8,81,457,267,60,-6.4,0.052,0.135,0.168,0.499,0.067
9,201582,Alexis Ajinca,1610612761,TOR,23.0,7-2,86,248,None,France,2008,1,20,34,143,78,10,0.7,0.052,0.179,0.207,0.507,0.049
10,202087,Alonzo Gee,1610612739,CLE,24.0,6-6,78,220,Alabama,USA,Undrafted,Undrafted,Undrafted,56,331,182,38,-11.0,0.054,0.111,0.142,0.544,0.056
11,2405,Amar'e Stoudemire,1610612752,NYK,28.0,6-10,82,240,None,USA,2002,1,9,78,1971,636,202,1.3,0.072,0.157,0.307,0.565,0.128
12,101161,Amir Johnson,1610612761,TOR,24.0,6-9,81,210,No College,USA,2005,2,56,72,688,461,81,-2.4,0.104,0.158,0.152,0.608,0.064
13,2760,Anderson Varejao,1610612739,CLE,28.0,6-11,83,260,None,Brazil,2004,2,30,31,282,301,45,-9.0,0.097,0.215,0.133,0.560,0.074
14,101154,Andray Blatche,1610612764,WAS,24.0,6-11,83,260,None,USA,2005,2,49,64,1076,526,144,-6.1,0.084,0.169,0.254,0.497,0.115
15,2738,Andre Iguodala,1610612755,PHI,27.0,6-6,78,207,Arizona,USA,2004,1,9,67,945,387,422,3.4,0.026,0.136,0.191,0.530,0.261
16,1889,Andre Miller,1610612757,POR,35.0,6-2,74,200,Utah,USA,1999,1,8,81,1029,302,566,4.6,0.040,0.087,0.203,0.529,0.348
17,200745,Andrea Bargnani,1610612761,TOR,25.0,7-0,84,250,None,Italy,2006,1,1,66,1414,343,119,-7.2,0.033,0.124,0.279,0.533,0.086
18,1905,Andrei Kirilenko,1610612762,UTA,30.0,6-9,81,235,None,Russia,1999,1,24,64,750,327,192,-0.4,0.054,0.119,0.177,0.567,0.145
19,2804,Andres Nocioni,1610612755,PHI,31.0,6-7,79,225,None,Argentina,Undrafted,Undrafted,Undrafted,54,327,169,45,-7.8,0.021,0.169,0.169,0.538,0.076
20,101106,Andrew Bogut,1610612749,MIL,26.0,7-0,84,260,Utah,Australia,2005,1,1,65,830,720,131,0.8,0.089,0.237,0.197,0.496,0.103
21,101115,Andrew Bynum,1610612747,LAL,23.0,7-0,84,285,None,USA,2005,1,10,54,612,508,73,7.4,0.119,0.225,0.178,0.606,0.079
22,2740,Andris Biedrins,1610612744,GSW,25.0,7-0,84,240,None,Latvia,2004,1,11,59,294,426,60,-8.4,0.103,0.219,0.104,0.526,0.060
23,202360,Andy Rautins,1610612752,NYK,24.0,6-4,76,190,Syracuse,USA,2010,2,38,5,8,1,3,-22.4,0.000,0.040,0.268,0.508,0.250
24,1712,Antawn Jamison,1610612739,CLE,35.0,6-9,81,235,North Carolina,USA,1998,1,4,56,1010,375,93,-10.4,0.044,0.164,0.252,0.516,0.092
25,1853,Anthony Carter,1610612752,NYK,36.0,6-2,74,195,Hawaii,USA,Undrafted,Undrafted,Undrafted,33,110,51,69,0.9,0.015,0.096,0.140,0.502,0.234
26,201627,Anthony Morrow,1610612751,NJN,25.0,6-5,77,210,Georgia Tech,USA,Undrafted,Undrafted,Undrafted,58,764,172,68,-4.3,0.020,0.076,0.175,0.573,0.063
27,1515,Anthony Parker,1610612739,CLE,36.0,6-6,78,210,Bradley,USA,1997,1,21,72,600,218,218,-7.5,0.016,0.091,0.144,0.505,0.164
28,201576,Anthony Randolph,1610612750,MIN,21.0,6-11,83,225,Louisiana State,USA,2008,1,14,40,305,160,33,-10.7,0.069,0.198,0.256,0.505,0.103
29,201229,Anthony Tolliver,1610612750,MIN,26.0,6-9,81,243,Creighton,USA,Undrafted,Undrafted,Undrafted,65,434,295,82,-2.5,0.064,0.153,0.130,0.585,0.090
30,101120,Antoine Wright,1610612758,SAC,27.0,6-7,79,215,Texas A&M,USA,2005,1,15,7,2,3,0,-31.0,0.053,0.032,0.125,0.125,0.000
31,1498,Antonio Daniels,1610612755,PHI,36.0,6-4,76,205,Bowling Green,USA,1997,1,4,4,6,5,2,22.5,0.000,0.139,0.093,0.510,0.080
32,686,Antonio McDyess,1610612759,SAS,36.0,6-9,81,245,Alabama,USA,1995,1,2,73,390,395,84,5.7,0.095,0.200,0.147,0.516,0.093
33,202356,Armon Johnson,1610612757,POR,22.0,6-3,75,195,Nevada-Reno,USA,2010,2,34,38,110,36,45,-1.7,0.037,0.093,0.228,0.497,0.300
34,201167,Arron Afflalo,1610612743,DEN,25.0,6-5,77,215,UCLA,USA,2007,1,27,69,867,251,168,3.6,0.021,0.089,0.147,0.620,0.109
35,201948,Austin Daye,1610612765,DET,23.0,6-11,83,200,Gonzaga,USA,2009,1,15,72,537,274,78,-4.6,0.045,0.160,0.181,0.518,0.085
36,202340,Avery Bradley,1610612738,BOS,20.0,6-2,74,180,Texas-Austin,USA,2010,1,19,31,52,17,12,-16.3,0.025,0.078,0.238,0.360,0.135
37,1884,Baron Davis,1610612739,CLE,32.0,6-3,75,215,UCLA,USA,1999,1,3,58,760,156,391,-0.7,0.021,0.077,0.240,0.506,0.388
38,2732,Ben Gordon,1610612765,DET,28.0,6-3,75,200,Connecticut,USA,2004,1,3,82,921,195,171,-2.8,0.020,0.082,0.206,0.548,0.129
39,202386,Ben Uzoh,1610612751,NJN,23.0,6-3,75,205,Tulsa,USA,Undrafted,Undrafted,Undrafted,42,158,61,69,-8.2,0.067,0.074,0.199,0.468,0.278
40,1112,Ben Wallace,1610612765,DET,36.0,6-9,81,240,Virginia Union,USA,Undrafted,Undrafted,Undrafted,54,154,350,72,-7.6,0.106,0.204,0.082,0.442,0.086
41,2757,Beno Udrih,1610612758,SAC,28.0,6-3,75,205,None,Slovenia,2004,1,28,79,1086,265,386,-5.6,0.014,0.086,0.164,0.587,0.219
42,201933,Blake Griffin,1610612746,LAC,22.0,6-10,82,251,Oklahoma,USA,2009,1,1,82,1845,989,312,-2.2,0.090,0.238,0.270,0.549,0.184
43,2250,Bobby Simmons,1610612759,SAS,31.0,6-6,78,235,DePaul,USA,2001,2,41,2,0,0,2,20.0,0.000,0.000,0.086,0.000,0.182
44,2564,Boris Diaw,1610612766,CHA,29.0,6-8,80,235,None,France,2003,1,21,82,924,414,337,-4.5,0.040,0.118,0.166,0.558,0.203
45,1802,Brad Miller,1610612745,HOU,35.0,7-0,84,261,Purdue,USA,Undrafted,Undrafted,Undrafted,60,382,222,145,1.8,0.043,0.178,0.167,0.566,0.220
46,201148,Brandan Wright,1610612751,NJN,23.0,6-10,82,210,North Carolina,USA,2007,1,8,37,141,89,12,-7.5,0.078,0.156,0.165,0.540,0.053
47,101138,Brandon Bass,1610612753,ORL,26.0,6-8,80,250,Louisiana State,USA,2005,2,33,76,854,424,57,5.0,0.073,0.149,0.198,0.571,0.051
48,201943,Brandon Jennings,1610612749,MIL,21.0,6-1,73,169,None,USA,2009,1,10,63,1019,234,305,-1.6,0.019,0.095,0.246,0.493,0.261
49,200750,Brandon Roy,1610612757,POR,26.0,6-6,78,211,Washington,USA,2006,1,6,47,573,121,129,2.6,0.022,0.081,0.225,0.491,0.168
50,201575,Brandon Rush,1610612754,IND,25.0,6-6,78,210,Kansas,USA,2008,1,13,67,607,217,62,-5.6,0.019,0.105,0.160,0.540,0.058
51,2217,Brendan Haywood,1610612742,DAL,31.0,7-0,84,263,North Carolina,USA,2001,1,20,72,320,376,19,-0.5,0.102,0.197,0.120,0.532,0.022
52,2073,Brian Cardinal,1610612742,DAL,34.0,6-8,80,240,Purdue,USA,2000,2,44,56,145,59,40,-2.7,0.017,0.085,0.093,0.672,0.097
53,2567,Brian Cook,1610612746,LAC,30.0,6-9,81,250,Illinois,USA,2003,1,24,40,193,96,15,-2.6,0.041,0.186,0.202,0.534,0.057
54,2243,Brian Scalabrine,1610612741,CHI,33.0,6-9,81,235,Southern California,USA,2001,2,34,18,20,8,6,-2.1,0.011,0.068,0.114,0.526,0.098
55,1730,Brian Skinner,1610612749,MIL,35.0,6-9,81,255,Baylor,USA,1998,1,22,2,0,0,0,-89.0,0.000,0.000,0.000,0.000,0.000
56,201572,Brook Lopez,1610612751,NJN,23.0,7-0,84,265,Stanford,USA,2008,1,10,82,1673,488,129,-6.2,0.070,0.108,0.270,0.549,0.087
57,201957,Byron Mullens,1610612760,OKC,22.0,7-0,84,275,Ohio State,USA,2009,1,24,13,25,24,0,-12.4,0.061,0.228,0.204,0.366,0.000
58,201228,C.J. Watson,1610612741,CHI,27.0,6-2,74,175,Tennessee,USA,Undrafted,Undrafted,Undrafted,82,405,94,186,6.7,0.015,0.073,0.212,0.466,0.303
59,101139,CJ Miles,1610612762,UTA,24.0,6-6,78,232,None,USA,2005,2,34,78,1000,255,135,2.2,0.028,0.109,0.244,0.507,0.118
60,201171,Carl Landry,1610612740,NOH,27.0,6-9,81,248,Purdue,USA,2007,2,31,76,903,347,63,-4.3,0.082,0.098,0.204,0.555,0.052
61,2306,Carlos Arroyo,1610612738,BOS,31.0,6-2,74,200,Florida International,Puerto Rico,Undrafted,Undrafted,Undrafted,64,310,103,125,4.1,0.019,0.069,0.137,0.528,0.160
62,2430,Carlos Boozer,1610612741,CHI,29.0,6-9,81,266,Duke,USA,2002,2,34,59,1033,565,145,6.9,0.075,0.242,0.267,0.542,0.137
63,2568,Carlos Delfino,1610612749,MIL,28.0,6-6,78,230,None,Argentina,2003,1,25,49,565,200,112,-2.7,0.015,0.122,0.176,0.517,0.123
64,2546,Carmelo Anthony,1610612752,NYK,27.0,6-8,80,230,Syracuse,USA,2003,1,3,77,1970,563,221,3.8,0.045,0.160,0.318,0.557,0.149
65,2406,Caron Butler,1610612742,DAL,31.0,6-7,79,228,Connecticut,USA,2002,1,10,29,436,118,46,8.7,0.029,0.109,0.251,0.523,0.091
66,201858,Cartier Martin,1610612764,WAS,26.0,6-7,79,220,Kansas State,USA,Undrafted,Undrafted,Undrafted,52,209,74,18,2.2,0.037,0.102,0.171,0.524,0.050
67,101112,Channing Frye,1610612756,PHX,28.0,6-11,83,245,Arizona,USA,2005,1,8,77,976,513,96,2.1,0.027,0.177,0.167,0.557,0.056
68,2294,Charlie Bell,1610612744,GSW,32.0,6-3,75,200,Michigan State,USA,Undrafted,Undrafted,Undrafted,19,32,18,13,1.8,0.034,0.070,0.131,0.357,0.113
69,101111,Charlie Villanueva,1610612765,DET,26.0,6-11,83,232,Connecticut,USA,2005,1,7,76,840,295,48,-4.4,0.031,0.165,0.229,0.553,0.050
70,201978,Chase Budinger,1610612745,HOU,23.0,6-7,79,218,Arizona,USA,2009,2,44,78,765,281,127,4.4,0.029,0.131,0.195,0.534,0.113
71,1497,Chauncey Billups,1610612752,NYK,34.0,6-3,75,210,Colorado,USA,1997,1,3,72,1208,190,387,2.9,0.011,0.071,0.221,0.617,0.266
72,2365,Chris Andersen,1610612743,DEN,32.0,6-10,82,228,Blinn J.C.,USA,Undrafted,Undrafted,Undrafted,45,250,219,20,6.2,0.102,0.192,0.129,0.636,0.043
73,2547,Chris Bosh,1610612748,MIA,27.0,6-11,83,235,Georgia Tech,USA,2003,1,4,77,1438,641,144,11.2,0.057,0.178,0.232,0.569,0.086
74,201604,Chris Douglas-Roberts,1610612749,MIL,24.0,6-7,79,210,Memphis,USA,2008,2,40,44,323,88,50,-1.2,0.008,0.097,0.181,0.517,0.098
75,2768,Chris Duhon,1610612753,ORL,28.0,6-1,73,190,Duke,USA,2004,2,38,51,125,52,118,0.2,0.012,0.057,0.118,0.446,0.251
76,202419,Chris Johnson,1610612757,POR,25.0,6-11,83,210,Louisiana State,USA,Undrafted,Undrafted,Undrafted,14,33,32,3,-18.6,0.079,0.154,0.126,0.554,0.037
77,2549,Chris Kaman,1610612746,LAC,29.0,7-0,84,265,Central Michigan,USA,2003,1,6,32,397,225,46,-3.6,0.061,0.200,0.242,0.495,0.100
78,101108,Chris Paul,1610612740,NOH,26.0,6-0,72,175,Wake Forest,USA,2005,1,4,80,1268,327,782,4.4,0.014,0.112,0.206,0.578,0.441
79,200809,Chris Quinn,1610612759,SAS,27.0,6-2,74,175,Notre Dame,USA,Undrafted,Undrafted,Undrafted,41,81,25,42,-7.5,0.011,0.076,0.164,0.428,0.236
80,2404,Chris Wilcox,1610612765,DET,28.0,6-10,82,235,Maryland,USA,2002,1,8,57,424,271,43,0.0,0.101,0.209,0.183,0.587,0.068
81,201963,Christian Eyenga,1610612739,CLE,22.0,6-5,77,210,None,Congo,2009,1,30,44,303,123,35,-10.7,0.028,0.105,0.169,0.476,0.061
82,101236,Chuck Hayes,1610612745,HOU,28.0,6-6,78,238,Kentucky,USA,Undrafted,Undrafted,Undrafted,74,582,599,202,6.1,0.108,0.186,0.130,0.554,0.140
83,202332,Cole Aldrich,1610612760,OKC,22.0,6-11,83,245,Kansas,USA,2010,1,11,18,18,35,4,2.1,0.096,0.143,0.079,0.537,0.041
84,201147,Corey Brewer,1610612742,DAL,25.0,6-9,81,188,Florida,USA,2007,1,7,69,552,175,89,-3.6,0.036,0.079,0.183,0.482,0.090
85,1894,Corey Maggette,1610612749,MIL,31.0,6-6,78,225,Duke,USA,1999,1,13,67,805,241,84,-2.3,0.032,0.148,0.272,0.573,0.111
86,201584,Courtney Lee,1610612745,HOU,25.0,6-5,77,200,Western Kentucky,USA,2008,1,22,81,672,209,100,0.6,0.029,0.092,0.175,0.534,0.092
87,202342,Craig Brackins,1610612755,PHI,23.0,6-10,82,230,Iowa State,USA,2010,1,21,3,8,4,1,-20.4,0.050,0.083,0.219,0.250,0.050
88,200783,Craig Smith,1610612746,LAC,27.0,6-7,79,265,Boston College,USA,2006,2,36,48,258,117,31,-5.1,0.073,0.136,0.189,0.592,0.095
89,201571,D.J. Augustin,1610612766,CHA,23.0,6-0,72,180,Texas-Austin,USA,2008,1,9,82,1178,225,498,-5.2,0.015,0.073,0.205,0.541,0.306
90,2788,DJ Mbenga,1610612740,NOH,30.0,7-0,84,255,None,Belgium,Undrafted,Undrafted,Undrafted,41,59,86,6,-4.4,0.108,0.150,0.108,0.518,0.032
91,201591,DJ White,1610612766,CHA,24.0,6-9,81,251,Indiana,USA,2008,1,29,47,268,158,19,-2.5,0.068,0.173,0.180,0.542,0.051
92,201969,DaJuan Summers,1610612765,DET,23.0,6-8,80,240,Georgetown,USA,2009,2,35,22,74,12,2,-3.0,0.011,0.053,0.212,0.476,0.017
93,201161,Daequan Cook,1610612760,OKC,24.0,6-5,77,210,Ohio State,USA,2007,1,21,43,239,72,20,7.4,0.014,0.108,0.155,0.630,0.055
94,2563,Dahntay Jones,1610612754,IND,30.0,6-6,78,210,Duke,USA,2003,1,20,45,283,65,33,-2.0,0.007,0.104,0.213,0.558,0.103
95,2863,Damien Wilkins,1610612737,ATL,31.0,6-6,78,225,Georgia,USA,Undrafted,Undrafted,Undrafted,52,180,90,41,-8.1,0.037,0.104,0.124,0.557,0.099
96,202345,Damion James,1610612751,NJN,23.0,6-7,79,220,Texas-Austin,USA,2010,1,24,25,110,85,20,-2.8,0.043,0.184,0.154,0.477,0.082
97,2429,Dan Gadzuric,1610612751,NJN,33.0,6-11,83,240,UCLA,Netherlands,2002,2,33,42,118,135,14,-7.0,0.139,0.150,0.156,0.419,0.046
98,200789,Daniel Gibson,1610612739,CLE,25.0,6-2,74,200,Texas-Austin,USA,2006,2,42,67,780,177,201,-5.5,0.013,0.085,0.193,0.533,0.185
99,201568,Danilo Gallinari,1610612743,DEN,22.0,6-10,82,225,None,Italy,2008,1,6,62,970,305,104,1.8,0.029,0.119,0.188,0.597,0.074
100,101122,Danny Granger,1610612754,IND,28.0,6-8,80,228,New Mexico,USA,2005,1,17,79,1622,425,203,-0.2,0.032,0.119,0.263,0.554,0.128
101,201980,Danny Green,1610612759,SAS,24.0,6-6,78,210,North Carolina,USA,2009,2,46,8,41,15,2,6.7,0.031,0.141,0.190,0.586,0.039
102,201967,Dante Cunningham,1610612766,CHA,24.0,6-8,80,230,Villanova,USA,2009,2,33,78,482,277,43,-4.3,0.062,0.126,0.156,0.483,0.044
103,2443,Darius Songaila,1610612755,PHI,33.0,6-9,81,248,Wake Forest,Lithuania,2002,2,49,10,16,10,2,-13.2,0.026,0.136,0.126,0.477,0.044
104,2545,Darko Milicic,1610612750,MIN,26.0,7-0,84,275,None,Serbia,2003,1,2,69,606,360,104,-6.3,0.077,0.132,0.197,0.482,0.099
105,201616,Darnell Jackson,1610612758,SAC,25.0,6-9,81,253,Kansas,USA,2008,2,52,59,187,94,14,-6.1,0.090,0.091,0.170,0.521,0.048
106,201589,Darrell Arthur,1610612763,MEM,23.0,6-9,81,235,Kansas,USA,2008,1,27,80,729,342,53,1.7,0.071,0.145,0.211,0.534,0.056
107,201954,Darren Collison,1610612754,IND,23.0,6-0,72,160,UCLA,USA,2009,1,21,79,1039,225,403,-2.6,0.017,0.076,0.212,0.534,0.280
108,2431,David Andersen,1610612740,NOH,31.0,6-11,83,247,None,Australia,2002,2,36,40,134,84,13,1.3,0.056,0.190,0.180,0.513,0.054
109,101135,David Lee,1610612744,GSW,28.0,6-9,81,240,Florida,USA,2005,1,30,73,1203,714,233,-2.0,0.084,0.194,0.209,0.549,0.136
110,2561,David West,1610612740,NOH,30.0,6-9,81,240,Xavier,USA,2003,1,18,70,1322,529,164,3.0,0.069,0.170,0.257,0.558,0.126
111,201599,DeAndre Jordan,1610612746,LAC,22.0,6-11,83,265,Texas A&M,USA,2008,2,35,80,566,575,42,-1.8,0.108,0.183,0.118,0.648,0.031
112,201971,DeJuan Blair,1610612759,SAS,22.0,6-7,79,270,Pittsburgh,USA,2009,2,37,81,674,565,77,3.9,0.129,0.208,0.193,0.524,0.067
113,201942,DeMar DeRozan,1610612761,TOR,21.0,6-7,79,220,Southern California,USA,2009,1,9,82,1410,315,148,-7.3,0.027,0.092,0.230,0.530,0.085
114,202326,DeMarcus Cousins,1610612758,SAC,20.0,6-11,83,270,Kentucky,USA,2010,1,5,81,1143,699,204,-6.3,0.091,0.223,0.270,0.484,0.149
115,201960,DeMarre Carroll,1610612745,HOU,24.0,6-8,80,212,Missouri,USA,2009,1,27,12,10,8,4,4.7,0.037,0.133,0.105,0.388,0.103
116,2205,DeSagana Diop,1610612766,CHA,29.0,7-0,84,280,None,Senegal,2001,1,8,16,20,40,7,-9.6,0.069,0.151,0.100,0.347,0.063
117,2052,DeShawn Stevenson,1610612742,DAL,30.0,6-5,77,218,None,USA,2000,1,23,72,383,106,77,1.8,0.019,0.076,0.157,0.549,0.101
118,2753,Delonte West,1610612738,BOS,27.0,6-3,75,180,St. Joseph's (PA),USA,2004,1,24,24,135,37,64,-10.1,0.015,0.074,0.167,0.533,0.268
119,965,Derek Fisher,1610612747,LAL,36.0,6-1,73,210,Arkansas-Little Rock,USA,1996,1,24,82,558,152,224,9.8,0.006,0.060,0.125,0.486,0.134
120,101114,Deron Williams,1610612751,NJN,27.0,6-3,75,209,Illinois,USA,2005,1,3,65,1309,260,667,-2.3,0.017,0.094,0.253,0.566,0.448
121,201974,Derrick Brown,1610612752,NYK,23.0,6-8,80,220,Xavier,USA,2009,2,40,49,185,99,33,-3.9,0.077,0.106,0.148,0.588,0.093
122,202382,Derrick Caracter,1610612747,LAL,23.0,6-9,81,275,Texas-El Paso,USA,2010,2,58,41,81,43,7,-11.8,0.090,0.105,0.186,0.532,0.054
123,202324,Derrick Favors,1610612762,UTA,19.0,6-10,82,246,Georgia Tech,USA,2010,1,3,78,533,412,39,-6.7,0.114,0.161,0.168,0.542,0.044
124,201565,Derrick Rose,1610612741,CHI,22.0,6-3,75,190,Memphis,USA,2008,1,1,81,2026,330,623,8.5,0.028,0.082,0.314,0.550,0.372
125,202365,Devin Ebanks,1610612747,LAL,21.0,6-9,81,215,West Virginia,USA,2010,2,43,20,62,27,2,-18.4,0.115,0.092,0.227,0.507,0.033
126,2734,Devin Harris,1610612762,UTA,28.0,6-3,75,190,Wisconsin,USA,2004,1,5,71,1079,169,503,-5.1,0.008,0.072,0.245,0.545,0.373
127,202354,Dexter Pittman,1610612748,MIA,23.0,6-11,83,308,Texas-Austin,USA,2010,2,32,2,2,3,0,40.7,0.125,0.167,0.200,0.333,0.000
128,1717,Dirk Nowitzki,1610612742,DAL,33.0,7-0,84,245,None,Germany,1998,1,9,73,1681,513,190,10.3,0.023,0.184,0.274,0.612,0.136
129,201187,Dominic McGuire,1610612766,CHA,25.0,6-9,81,220,Fresno State,USA,2007,2,47,52,174,199,43,-3.6,0.086,0.183,0.134,0.437,0.092
130,202346,Dominique Jones,1610612742,DAL,22.0,6-5,77,215,South Florida,USA,2010,1,25,18,42,25,19,-8.8,0.045,0.147,0.213,0.400,0.241
131,201590,Donte Greene,1610612758,SAC,23.0,6-11,83,226,Syracuse,USA,2008,1,28,69,400,147,48,-3.3,0.042,0.087,0.179,0.482,0.066
132,2748,Dorell Wright,1610612744,GSW,25.0,6-9,81,205,None,USA,2004,1,19,82,1344,431,242,-1.9,0.028,0.112,0.190,0.539,0.114
133,2400,Drew Gooden,1610612749,MIL,29.0,6-10,82,250,Kansas,USA,2002,1,4,35,396,238,47,-2.2,0.085,0.207,0.245,0.487,0.108
134,2730,Dwight Howard,1610612753,ORL,25.0,6-11,83,265,None,USA,2004,1,1,78,1784,1098,107,8.4,0.113,0.268,0.272,0.616,0.067
135,2548,Dwyane Wade,1610612748,MIA,29.0,6-4,76,220,Marquette,USA,2003,1,5,76,1941,485,346,10.4,0.049,0.127,0.308,0.581,0.223
136,2853,Earl Barron,1610612757,POR,29.0,7-0,84,250,Memphis,USA,Undrafted,Undrafted,Undrafted,21,79,76,11,-4.8,0.108,0.164,0.184,0.361,0.054
137,1863,Earl Boykins,1610612749,MIL,35.0,5-5,65,133,Eastern Michigan,USA,Undrafted,Undrafted,Undrafted,57,408,55,141,3.1,0.018,0.048,0.235,0.526,0.301
138,201947,Earl Clark,1610612753,ORL,23.0,6-10,82,225,Louisville,USA,2009,1,14,42,163,101,9,-6.1,0.080,0.136,0.194,0.456,0.035
139,2248,Earl Watson,1610612762,UTA,32.0,6-1,73,195,UCLA,USA,2001,2,39,80,343,182,278,0.6,0.036,0.091,0.135,0.500,0.260
140,202334,Ed Davis,1610612761,TOR,22.0,6-10,82,215,North Carolina,USA,2010,1,13,65,501,462,40,-9.8,0.107,0.190,0.131,0.583,0.039
141,2067,Eddie House,1610612748,MIA,33.0,6-1,73,190,Arizona State,USA,2000,2,37,56,362,92,62,5.0,0.010,0.083,0.169,0.535,0.104
142,2059,Eduardo Najera,1610612766,CHA,34.0,6-8,80,235,Oklahoma,Mexico,2000,2,38,31,69,44,20,2.3,0.039,0.078,0.112,0.449,0.089
143,202327,Ekpe Udoh,1610612744,GSW,24.0,6-10,82,245,Baylor,USA,2010,1,6,58,236,181,40,6.1,0.078,0.097,0.128,0.472,0.051
144,1882,Elton Brand,1610612755,PHI,32.0,6-9,81,254,Duke,USA,1999,1,1,81,1217,676,120,2.5,0.087,0.164,0.196,0.553,0.070
145,2731,Emeka Okafor,1610612740,NOH,28.0,6-10,82,255,Connecticut,USA,2004,1,2,72,745,684,42,3.8,0.110,0.220,0.157,0.584,0.029
146,202339,Eric Bledsoe,1610612746,LAC,21.0,6-1,73,195,Kentucky,USA,2010,1,18,81,543,223,289,-6.4,0.038,0.086,0.175,0.499,0.254
147,201569,Eric Gordon,1610612746,LAC,22.0,6-3,75,215,Indiana,USA,2008,1,7,56,1247,164,244,-0.1,0.022,0.057,0.258,0.566,0.197
148,201953,Eric Maynor,1610612760,OKC,24.0,6-3,75,175,Virginia Commonwealth,USA,2009,1,20,82,348,121,238,8.5,0.023,0.080,0.164,0.485,0.313
149,956,Erick Dampier,1610612748,MIA,35.0,6-11,83,265,Mississippi State,USA,1996,1,10,51,128,177,22,6.2,0.074,0.148,0.079,0.591,0.039
150,101141,Ersan Ilyasova,1610612749,MIL,24.0,6-10,82,235,None,Turkey,2005,2,36,60,571,365,56,1.9,0.069,0.190,0.186,0.516,0.064
151,2041,Etan Thomas,1610612737,ATL,33.0,6-10,82,260,Syracuse,USA,2000,1,12,13,32,23,2,-13.7,0.070,0.218,0.176,0.580,0.050

In [82]:
from nba_api.stats.endpoints import playercompare

In [85]:
from playercompare.PlayerCompare().get_data_frames()

SyntaxError: invalid syntax (<ipython-input-85-4e38a25e1586>, line 1)

In [88]:
from nba_api.stats.endpoints import boxscoretraditionalv2

In [93]:
boxscoretraditionalv2.BoxScoreTraditionalV2(game_id = '0020900001').get_data_frames()[0]

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS
0,0020900001,1610612738,BOS,Boston,1718,Paul Pierce,F,,37:59,6.0,13.0,0.462,2.0,5.0,0.400,9.0,10.0,0.900,1.0,10.0,11.0,1.0,1.0,1.0,2.0,5.0,23.0,1.0
1,0020900001,1610612738,BOS,Boston,708,Kevin Garnett,F,,33:05,5.0,10.0,0.500,0.0,0.0,0.000,3.0,4.0,0.750,3.0,7.0,10.0,1.0,1.0,3.0,1.0,3.0,13.0,-4.0
2,0020900001,1610612738,BOS,Boston,2570,Kendrick Perkins,C,,25:42,4.0,7.0,0.571,0.0,0.0,0.000,1.0,1.0,1.000,0.0,1.0,1.0,1.0,0.0,1.0,3.0,3.0,9.0,-2.0
3,0020900001,1610612738,BOS,Boston,951,Ray Allen,G,,42:21,5.0,16.0,0.313,2.0,4.0,0.500,4.0,5.0,0.800,0.0,2.0,2.0,3.0,3.0,0.0,3.0,2.0,16.0,4.0
4,0020900001,1610612738,BOS,Boston,200765,Rajon Rondo,G,,34:29,4.0,8.0,0.500,0.0,0.0,0.000,0.0,0.0,0.000,2.0,4.0,6.0,10.0,3.0,0.0,2.0,4.0,8.0,-3.0
5,0020900001,1610612738,BOS,Boston,739,Rasheed Wallace,,,23:50,4.0,9.0,0.444,3.0,6.0,0.500,1.0,2.0,0.500,0.0,3.0,3.0,0.0,0.0,2.0,0.0,5.0,12.0,10.0
6,0020900001,1610612738,BOS,Boston,2605,Marquis Daniels,,,17:33,3.0,5.0,0.600,1.0,1.0,1.000,0.0,0.0,0.000,0.0,1.0,1.0,2.0,1.0,0.0,1.0,1.0,7.0,11.0
7,0020900001,1610612738,BOS,Boston,200749,Shelden Williams,,,12:30,0.0,1.0,0.000,0.0,0.0,0.000,4.0,4.0,1.000,0.0,3.0,3.0,0.0,0.0,0.0,1.0,3.0,4.0,7.0
8,0020900001,1610612738,BOS,Boston,2067,Eddie House,,,12:30,1.0,3.0,0.333,1.0,3.0,0.333,0.0,0.0,0.000,0.0,1.0,1.0,2.0,0.0,1.0,1.0,1.0,3.0,6.0
9,0020900001,1610612738,BOS,Boston,201592,J.R. Giddens,,DNP - Coach's Decision,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,0020900001,1610612738,BOS,Boston,201991,Lester Hudson,,DNP - Coach's Decision,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,0020900001,1610612738,BOS,Boston,2243,Brian Scalabrine,,NWT- Right Ankle Sprain,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,0020900001,1610612739,CLE,Cleveland,2544,LeBron James,F,,44:55,12.0,22.0,0.545,4.0,9.0,0.444,10.0,13.0,0.769,0.0,4.0,4.0,8.0,2.0,4.0,5.0,4.0,38.0,0.0
13,0020900001,1610612739,CLE,Cleveland,2760,Anderson Varejao,F,,32:50,3.0,9.0,0.333,0.0,0.0,0.000,3.0,4.0,0.750,5.0,2.0,7.0,1.0,2.0,1.0,0.0,5.0,9.0,-6.0
14,0020900001,1610612739,CLE,Cleveland,406,Shaquille O'Neal,C,,28:48,5.0,11.0,0.455,0.0,0.0,0.000,0.0,2.0,0.000,0.0,10.0,10.0,1.0,0.0,1.0,1.0,2.0,10.0,2.0
15,0020900001,1610612739,CLE,Cleveland,1515,Anthony Parker,G,,40:10,3.0,9.0,0.333,2.0,3.0,0.667,2.0,2.0,1.000,0.0,3.0,3.0,4.0,1.0,2.0,3.0,0.0,10.0,3.0
16,0020900001,1610612739,CLE,Cleveland,2590,Mo Williams,G,,35:02,3.0,8.0,0.375,0.0,3.0,0.000,6.0,6.0,1.000,0.0,0.0,0.0,3.0,1.0,0.0,2.0,4.0,12.0,-10.0
17,0020900001,1610612739,CLE,Cleveland,980,Zydrunas Ilgauskas,,,24:39,1.0,4.0,0.250,0.0,0.0,0.000,4.0,4.0,1.000,1.0,4.0,5.0,0.0,0.0,0.0,0.0,2.0,6.0,-2.0
18,0020900001,1610612739,CLE,Cleveland,200789,Daniel Gibson,,,13:42,1.0,3.0,0.333,0.0,1.0,0.000,0.0,1.0,0.000,0.0,1.0,1.0,0.0,0.0,0.0,1.0,2.0,2.0,-4.0
19,0020900001,1610612739,CLE,Cleveland,201581,JJ Hickson,,,6:13,0.0,1.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0,-4.0
20,0020900001,1610612739,CLE,Cleveland,200081,Jamario Moon,,,13:41,1.0,3.0,0.333,0.0,1.0,0.000,0.0,0.0,0.000,0.0,2.0,2.0,0.0,0.0,1.0,1.0,1.0,2.0,-9.0
21,0020900001,1610612739,CLE,Cleveland,201616,Darnell Jackson,,DNP - Coach's Decision,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,0020900001,1610612739,CLE,Cleveland,201207,Coby Karl,,DNP - Coach's Decision,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,0020900001,1610612739,CLE,Cleveland,101214,Jawad Williams,,DNP - Coach's Decision,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [90]:
help(boxscoretraditionalv2)

Help on module nba_api.stats.endpoints.boxscoretraditionalv2 in nba_api.stats.endpoints:

NAME
    nba_api.stats.endpoints.boxscoretraditionalv2

CLASSES
    nba_api.stats.endpoints._base.Endpoint(builtins.object)
        BoxScoreTraditionalV2

    class BoxScoreTraditionalV2(nba_api.stats.endpoints._base.Endpoint)
     |  BoxScoreTraditionalV2(game_id, end_period='0', end_range='0', range_type='0', start_period='0', start_range='0', proxy=None, headers=None, timeout=30, get_request=True)
     |
     |  Method resolution order:
     |      BoxScoreTraditionalV2
     |      nba_api.stats.endpoints._base.Endpoint
     |      builtins.object
     |
     |  Methods defined here:
     |
     |  __init__(self, game_id, end_period='0', end_range='0', range_type='0', start_period='0', start_range='0', proxy=None, headers=None, timeout=30, get_request=True)
     |      Initialize self.  See help(type(self)) for accurate signature.
     |
     |  get_request(self)
     |
     |  load_response(self)
     |
     |  ----------------------------------------------------------------------
     |  Data and other attributes defined here:
     |
     |  data_sets = None
     |
     |  endpoint = 'boxscoretraditionalv2'
     |
     |  expected_data = {'PlayerStats': ['GAME_ID', 'TEAM_ID', 'TEAM_ABBREVIAT...
     |
     |  headers = None
     |
     |  nba_response = None
     |
     |  player_stats = None
     |
     |  team_stats = None
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from nba_api.stats.endpoints._base.Endpoint:
     |
     |  get_available_data(self)
     |
     |  get_data_frames(self)
     |
     |  get_dict(self)
     |
     |  get_json(self)
     |
     |  get_normalized_dict(self)
     |
     |  get_normalized_json(self)
     |
     |  get_request_url(self)
     |
     |  get_response(self)
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors inherited from nba_api.stats.endpoints._base.Endpoint:
     |
     |  __dict__
     |      dictionary for instance variables (if defined)
     |
     |  __weakref__
     |      list of weak references to the object (if defined)
     |
     |  ----------------------------------------------------------------------
     |  Data and other attributes inherited from nba_api.stats.endpoints._base.Endpoint:
     |
     |  DataSet = <class 'nba_api.stats.endpoints._base.Endpoint.DataSet'>

FILE
    /opt/anaconda3/lib/python3.8/site-packages/nba_api/stats/endpoints/boxscoretraditionalv2.py

In [86]:
help(playercompare)

Help on module nba_api.stats.endpoints.playercompare in nba_api.stats.endpoints:

NAME
    nba_api.stats.endpoints.playercompare

CLASSES
    nba_api.stats.endpoints._base.Endpoint(builtins.object)
        PlayerCompare

    class PlayerCompare(nba_api.stats.endpoints._base.Endpoint)
     |  PlayerCompare(vs_player_id_list, player_id_list, last_n_games='0', measure_type_detailed_defense='Base', month='0', opponent_team_id=0, pace_adjust='N', per_mode_detailed='Totals', period='0', plus_minus='N', rank='N', season='2020-21', season_type_playoffs='Regular Season', conference_nullable='', date_from_nullable='', date_to_nullable='', division_simple_nullable='', game_segment_nullable='', league_id_nullable='', location_nullable='', outcome_nullable='', season_segment_nullable='', shot_clock_range_nullable='', vs_conference_nullable='', vs_division_nullable='', proxy=None, headers=None, timeout=30, get_request=True)
     |
     |  Method resolution order:
     |      PlayerCompare
     |      nba_api.stats.endpoints._base.Endpoint
     |      builtins.object
     |
     |  Methods defined here:
     |
     |  __init__(self, vs_player_id_list, player_id_list, last_n_games='0', measure_type_detailed_defense='Base', month='0', opponent_team_id=0, pace_adjust='N', per_mode_detailed='Totals', period='0', plus_minus='N', rank='N', season='2020-21', season_type_playoffs='Regular Season', conference_nullable='', date_from_nullable='', date_to_nullable='', division_simple_nullable='', game_segment_nullable='', league_id_nullable='', location_nullable='', outcome_nullable='', season_segment_nullable='', shot_clock_range_nullable='', vs_conference_nullable='', vs_division_nullable='', proxy=None, headers=None, timeout=30, get_request=True)
     |      Initialize self.  See help(type(self)) for accurate signature.
     |
     |  get_request(self)
     |
     |  load_response(self)
     |
     |  ----------------------------------------------------------------------
     |  Data and other attributes defined here:
     |
     |  data_sets = None
     |
     |  endpoint = 'playercompare'
     |
     |  expected_data = {'Individual': ['GROUP_SET', 'DESCRIPTION', 'MIN', 'FG...
     |
     |  headers = None
     |
     |  nba_response = None
     |
     |  player_stats = None
     |
     |  team_stats = None
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from nba_api.stats.endpoints._base.Endpoint:
     |
     |  get_available_data(self)
     |
     |  get_data_frames(self)
     |
     |  get_dict(self)
     |
     |  get_json(self)
     |
     |  get_normalized_dict(self)
     |
     |  get_normalized_json(self)
     |
     |  get_request_url(self)
     |
     |  get_response(self)
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors inherited from nba_api.stats.endpoints._base.Endpoint:
     |
     |  __dict__
     |      dictionary for instance variables (if defined)
     |
     |  __weakref__
     |      list of weak references to the object (if defined)
     |
     |  ----------------------------------------------------------------------
     |  Data and other attributes inherited from nba_api.stats.endpoints._base.Endpoint:
     |
     |  DataSet = <class 'nba_api.stats.endpoints._base.Endpoint.DataSet'>

FILE
    /opt/anaconda3/lib/python3.8/site-packages/nba_api/stats/endpoints/playercompare.py

In [79]:
help(leaguedashplayerbiostats)

Help on module nba_api.stats.endpoints.leaguedashplayerbiostats in nba_api.stats.endpoints:

NAME
    nba_api.stats.endpoints.leaguedashplayerbiostats

CLASSES
    nba_api.stats.endpoints._base.Endpoint(builtins.object)
        LeagueDashPlayerBioStats

    class LeagueDashPlayerBioStats(nba_api.stats.endpoints._base.Endpoint)
     |  LeagueDashPlayerBioStats(league_id='00', per_mode_simple='Totals', season='2020-21', season_type_all_star='Regular Season', college_nullable='', conference_nullable='', country_nullable='', date_from_nullable='', date_to_nullable='', division_simple_nullable='', draft_pick_nullable='', draft_year_nullable='', game_scope_simple_nullable='', game_segment_nullable='', height_nullable='', last_n_games_nullable='', location_nullable='', month_nullable='', opponent_team_id_nullable='', outcome_nullable='', po_round_nullable='', period_nullable='', player_experience_nullable='', player_position_abbreviation_nullable='', season_segment_nullable='', shot_clock_range_nullable='', starter_bench_nullable='', team_id_nullable='', vs_conference_nullable='', vs_division_nullable='', weight_nullable='', proxy=None, headers=None, timeout=30, get_request=True)
     |
     |  Method resolution order:
     |      LeagueDashPlayerBioStats
     |      nba_api.stats.endpoints._base.Endpoint
     |      builtins.object
     |
     |  Methods defined here:
     |
     |  __init__(self, league_id='00', per_mode_simple='Totals', season='2020-21', season_type_all_star='Regular Season', college_nullable='', conference_nullable='', country_nullable='', date_from_nullable='', date_to_nullable='', division_simple_nullable='', draft_pick_nullable='', draft_year_nullable='', game_scope_simple_nullable='', game_segment_nullable='', height_nullable='', last_n_games_nullable='', location_nullable='', month_nullable='', opponent_team_id_nullable='', outcome_nullable='', po_round_nullable='', period_nullable='', player_experience_nullable='', player_position_abbreviation_nullable='', season_segment_nullable='', shot_clock_range_nullable='', starter_bench_nullable='', team_id_nullable='', vs_conference_nullable='', vs_division_nullable='', weight_nullable='', proxy=None, headers=None, timeout=30, get_request=True)
     |      Initialize self.  See help(type(self)) for accurate signature.
     |
     |  get_request(self)
     |
     |  load_response(self)
     |
     |  ----------------------------------------------------------------------
     |  Data and other attributes defined here:
     |
     |  data_sets = None
     |
     |  endpoint = 'leaguedashplayerbiostats'
     |
     |  expected_data = {'LeagueDashPlayerBioStats': ['PLAYER_ID', 'PLAYER_NAM...
     |
     |  headers = None
     |
     |  nba_response = None
     |
     |  player_stats = None
     |
     |  team_stats = None
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from nba_api.stats.endpoints._base.Endpoint:
     |
     |  get_available_data(self)
     |
     |  get_data_frames(self)
     |
     |  get_dict(self)
     |
     |  get_json(self)
     |
     |  get_normalized_dict(self)
     |
     |  get_normalized_json(self)
     |
     |  get_request_url(self)
     |
     |  get_response(self)
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors inherited from nba_api.stats.endpoints._base.Endpoint:
     |
     |  __dict__
     |      dictionary for instance variables (if defined)
     |
     |  __weakref__
     |      list of weak references to the object (if defined)
     |
     |  ----------------------------------------------------------------------
     |  Data and other attributes inherited from nba_api.stats.endpoints._base.Endpoint:
     |
     |  DataSet = <class 'nba_api.stats.endpoints._base.Endpoint.DataSet'>

FILE
    /opt/anaconda3/lib/python3.8/site-packages/nba_api/stats/endpoints/leaguedashplayerbiostats.py

In [68]:
help(commonteamroster)

Help on module nba_api.stats.endpoints.commonteamroster in nba_api.stats.endpoints:

NAME
    nba_api.stats.endpoints.commonteamroster

CLASSES
    nba_api.stats.endpoints._base.Endpoint(builtins.object)
        CommonTeamRoster

    class CommonTeamRoster(nba_api.stats.endpoints._base.Endpoint)
     |  CommonTeamRoster(team_id, season='2020-21', league_id_nullable='', proxy=None, headers=None, timeout=30, get_request=True)
     |
     |  Method resolution order:
     |      CommonTeamRoster
     |      nba_api.stats.endpoints._base.Endpoint
     |      builtins.object
     |
     |  Methods defined here:
     |
     |  __init__(self, team_id, season='2020-21', league_id_nullable='', proxy=None, headers=None, timeout=30, get_request=True)
     |      Initialize self.  See help(type(self)) for accurate signature.
     |
     |  get_request(self)
     |
     |  load_response(self)
     |
     |  ----------------------------------------------------------------------
     |  Data and other attributes defined here:
     |
     |  data_sets = None
     |
     |  endpoint = 'commonteamroster'
     |
     |  expected_data = {'Coaches': ['TEAM_ID', 'SEASON', 'COACH_ID', 'FIRST_N...
     |
     |  headers = None
     |
     |  nba_response = None
     |
     |  player_stats = None
     |
     |  team_stats = None
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from nba_api.stats.endpoints._base.Endpoint:
     |
     |  get_available_data(self)
     |
     |  get_data_frames(self)
     |
     |  get_dict(self)
     |
     |  get_json(self)
     |
     |  get_normalized_dict(self)
     |
     |  get_normalized_json(self)
     |
     |  get_request_url(self)
     |
     |  get_response(self)
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors inherited from nba_api.stats.endpoints._base.Endpoint:
     |
     |  __dict__
     |      dictionary for instance variables (if defined)
     |
     |  __weakref__
     |      list of weak references to the object (if defined)
     |
     |  ----------------------------------------------------------------------
     |  Data and other attributes inherited from nba_api.stats.endpoints._base.Endpoint:
     |
     |  DataSet = <class 'nba_api.stats.endpoints._base.Endpoint.DataSet'>

FILE
    /opt/anaconda3/lib/python3.8/site-packages/nba_api/stats/endpoints/commonteamroster.py

Help on module nba_api.stats.endpoints.commonallplayers in nba_api.stats.endpoints:

NAME
    nba_api.stats.endpoints.commonallplayers

CLASSES
    nba_api.stats.endpoints._base.Endpoint(builtins.object)
        CommonAllPlayers

    class CommonAllPlayers(nba_api.stats.endpoints._base.Endpoint)
     |  CommonAllPlayers(is_only_current_season=0, league_id='00', season='2020-21', proxy=None, headers=None, timeout=30, get_request=True)
     |
     |  Method resolution order:
     |      CommonAllPlayers
     |      nba_api.stats.endpoints._base.Endpoint
     |      builtins.object
     |
     |  Methods defined here:
     |
     |  __init__(self, is_only_current_season=0, league_id='00', season='2020-21', proxy=None, headers=None, timeout=30, get_request=True)
     |      Initialize self.  See help(type(self)) for accurate signature.
     |
     |  get_request(self)
     |
     |  load_response(self)
     |
     |  ----------------------------------------------------------------------
     |  Data and other attributes defined here:
     |
     |  data_sets = None
     |
     |  endpoint = 'commonallplayers'
     |
     |  expected_data = {'CommonAllPlayers': ['PERSON_ID', 'DISPLAY_LAST_COMMA...
     |
     |  headers = None
     |
     |  nba_response = None
     |
     |  player_stats = None
     |
     |  team_stats = None
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from nba_api.stats.endpoints._base.Endpoint:
     |
     |  get_available_data(self)
     |
     |  get_data_frames(self)
     |
     |  get_dict(self)
     |
     |  get_json(self)
     |
     |  get_normalized_dict(self)
     |
     |  get_normalized_json(self)
     |
     |  get_request_url(self)
     |
     |  get_response(self)
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors inherited from nba_api.stats.endpoints._base.Endpoint:
     |
     |  __dict__
     |      dictionary for instance variables (if defined)
     |
     |  __weakref__
     |      list of weak references to the object (if defined)
     |
     |  ----------------------------------------------------------------------
     |  Data and other attributes inherited from nba_api.stats.endpoints._base.Endpoint:
     |
     |  DataSet = <class 'nba_api.stats.endpoints._base.Endpoint.DataSet'>

FILE
    /opt/anaconda3/lib/python3.8/site-packages/nba_api/stats/endpoints/commonallplayers.py

In [51]:
df_games2 = pd.read_csv(os.path.join('..', 'processed_data', '4game_id_date_stats_betting_totals_2010_2018.csv'))
df_games2.head(11)

,game_id,game_date,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_year,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,season_type,season,book_name,book_id,team_id,a_team_id,total1,total2,price1,price2
0,21000001,2010-10-26,1610612738,1.0,240,32.0,69.0,0.464,8.0,16.0,0.500,16.0,25.0,1.0,8.0,34.0,42,25.0,6.0,4.0,18.0,19.0,88,2010.0,1610612748,0.0,240,27.0,74.0,0.365,8.0,20.0,0.400,18.0,25.0,1.0,11.0,28.0,39,15.0,10.0,6.0,17.0,21.0,80,Regular Season,2010-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,21000002,2010-10-26,1610612757,1.0,240,43.0,93.0,0.462,10.0,20.0,0.500,10.0,15.0,1.0,18.0,30.0,48,31.0,11.0,2.0,12.0,22.0,106,2010.0,1610612756,0.0,240,36.0,74.0,0.486,9.0,19.0,0.474,11.0,16.0,1.0,7.0,23.0,30,15.0,3.0,4.0,19.0,19.0,92,Regular Season,2010-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,21000003,2010-10-26,1610612747,1.0,240,40.0,96.0,0.417,9.0,21.0,0.429,23.0,28.0,1.0,14.0,30.0,44,21.0,11.0,4.0,12.0,24.0,112,2010.0,1610612745,0.0,240,38.0,91.0,0.418,8.0,20.0,0.400,26.0,28.0,1.0,16.0,37.0,53,25.0,6.0,7.0,20.0,25.0,110,Regular Season,2010-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,21000004,2010-10-27,1610612739,1.0,240,36.0,81.0,0.444,6.0,20.0,0.300,17.0,21.0,1.0,8.0,29.0,37,24.0,5.0,4.0,14.0,20.0,95,2010.0,1610612738,0.5,240,34.0,72.0,0.472,3.0,12.0,0.250,16.0,21.0,1.0,6.0,32.0,38,24.0,8.0,1.0,19.0,24.0,87,Regular Season,2010-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,21000005,2010-10-27,1610612751,1.0,240,39.0,80.0,0.488,6.0,14.0,0.429,17.0,24.0,1.0,9.0,35.0,44,17.0,4.0,4.0,11.0,23.0,101,2010.0,1610612765,0.0,240,37.0,83.0,0.446,8.0,19.0,0.421,16.0,30.0,1.0,10.0,27.0,37,21.0,7.0,3.0,6.0,19.0,98,Regular Season,2010-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,21000006,2010-10-27,1610612755,0.0,240,36.0,83.0,0.434,7.0,18.0,0.389,8.0,11.0,1.0,10.0,28.0,38,24.0,10.0,4.0,16.0,22.0,87,2010.0,1610612748,0.5,240,33.0,69.0,0.478,8.0,16.0,0.500,23.0,31.0,1.0,5.0,32.0,37,15.0,8.0,6.0,16.0,18.0,97,Regular Season,2010-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,21000007,2010-10-27,1610612761,0.0,240,36.0,94.0,0.383,3.0,10.0,0.300,18.0,24.0,1.0,12.0,33.0,45,20.0,6.0,5.0,11.0,20.0,93,2010.0,1610612752,1.0,240,38.0,88.0,0.432,7.0,24.0,0.292,15.0,17.0,1.0,13.0,36.0,49,12.0,4.0,10.0,15.0,23.0,98,Regular Season,2010-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,21000008,2010-10-27,1610612763,0.0,240,40.0,86.0,0.465,4.0,9.0,0.444,20.0,25.0,1.0,9.0,30.0,39,13.0,7.0,4.0,14.0,26.0,104,2010.0,1610612737,1.0,240,42.0,80.0,0.525,8.0,16.0,0.500,27.0,31.0,1.0,9.0,35.0,44,20.0,7.0,9.0,15.0,20.0,119,Regular Season,2010-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,21000009,2010-10-27,1610612750,0.0,240,43.0,91.0,0.473,8.0,18.0,0.444,22.0,28.0,1.0,11.0,35.0,46,22.0,5.0,8.0,13.0,32.0,116,2010.0,1610612758,1.0,240,39.0,85.0,0.459,4.0,11.0,0.364,35.0,47.0,1.0,14.0,31.0,45,25.0,8.0,4.0,13.0,24.0,117,Regular Season,2010-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,21000010,2010-10-27,1610612740,1.0,240,34.0,79.0,0.430,4.0,17.0,0.235,23.0,29.0,1.0,6.0,38.0,44,23.0,4.0,0.0,9.0,26.0,95,2010.0,1610612749,0.0,240,33.0,77.0,0.429,8.0,23.0,0.348,17.0,28.0,1.0,8.0,37.0,45,14.0,4.0,2.0,12.0,27.0,91,Regular Season,2010-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,21000011,2010-10-27,1610612760,1.0,240,32.0,78.0,0.410,4.0,18.0,0.222,38.0,47.0,1.0,9.0,35.0,44,17.0,11.0,10.0,12.0,15.0,106,2010.0,1610612741,0.0,240,40.0,93.0,0.430,2.0,14.0,0.143,13.0,22.0,1.0,15.0,36.0,51,21.0,6.0,6.0,14.0,28.0,95,Regular Season,2010-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
df_games_all = pd.read_csv(os.path.join('..', 'raw_data', 'nba_games_all.csv'))
df_games_all.head()

,game_id,game_date,matchup,team_id,is_home,wl,w,l,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,a_team_id,season_year,season_type,season
0,20800741,2009-02-06,SAC vs. UTA,1610612762,f,W,29.0,22.0,0.569,240,39.0,74.0,0.527,4.0,13.0,0.308,29.0,37.0,1.0,8.0,36.0,44,19.0,5.0,4.0,18.0,26.0,111,1610612758,2008,Regular Season,2008-09
1,20800701,2009-01-31,POR vs. UTA,1610612762,f,L,26.0,22.0,0.542,240,37.0,68.0,0.544,5.0,20.0,0.250,29.0,37.0,1.0,7.0,20.0,27,17.0,6.0,0.0,15.0,22.0,108,1610612757,2008,Regular Season,2008-09
2,20800584,2009-01-16,MEM vs. UTA,1610612762,f,W,24.0,16.0,0.600,240,37.0,71.0,0.521,7.0,19.0,0.368,20.0,27.0,1.0,7.0,26.0,33,23.0,9.0,3.0,15.0,22.0,101,1610612763,2008,Regular Season,2008-09
3,20800558,2009-01-12,IND @ UTA,1610612762,t,W,23.0,15.0,0.605,240,39.0,85.0,0.459,8.0,18.0,0.444,34.0,37.0,1.0,9.0,31.0,40,24.0,10.0,6.0,8.0,20.0,120,1610612754,2008,Regular Season,2008-09
4,20800440,2008-12-27,HOU vs. UTA,1610612762,f,L,18.0,14.0,0.563,290,49.0,100.0,0.490,5.0,13.0,0.385,12.0,18.0,1.0,11.0,29.0,40,35.0,13.0,7.0,9.0,27.0,115,1610612745,2008,Regular Season,2008-09

In [ ]:
df_games_all[df_games_all.game_id == 41700404]

In [43]:
df_bsadv = pd.read_csv(os.path.join('..', 'processed_data', '5boxscoreadvancedv2_2010_2018.csv'))
df_bsadv.head()

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
0,20900001,1.610613e+09,BOS,Boston,1718.0,Paul Pierce,F,NaN,37:59,95.3,97.4,96.5,98.6,-1.2,-1.3,0.053,0.50,4.8,0.028,0.270,0.151,9.5,0.538,0.661,0.233,0.239,96.88,94.76,78.97,76.0,0.189
1,20900001,1.610613e+09,BOS,Boston,708.0,Kevin Garnett,F,NaN,33:05,95.6,95.5,101.0,103.1,-5.4,-7.6,0.059,1.00,7.1,0.097,0.233,0.164,7.1,0.500,0.553,0.178,0.181,95.96,95.03,79.19,66.0,0.147
2,20900001,1.610613e+09,BOS,Boston,2570.0,Kendrick Perkins,C,NaN,25:42,99.2,100.0,108.2,104.3,-9.1,-4.3,0.077,0.33,9.1,0.000,0.050,0.024,27.3,0.571,0.605,0.196,0.198,86.53,87.77,73.14,47.0,0.030
3,20900001,1.610613e+09,BOS,Boston,951.0,Ray Allen,G,NaN,42:21,105.2,108.8,105.4,105.1,-0.2,3.7,0.120,1.00,12.5,0.000,0.054,0.028,12.5,0.375,0.440,0.236,0.240,91.50,90.12,75.10,80.0,0.051
4,20900001,1.610613e+09,BOS,Boston,200765.0,Rajon Rondo,G,NaN,34:29,92.7,94.1,98.0,97.1,-5.3,-3.0,0.526,5.00,50.0,0.061,0.125,0.092,10.0,0.500,0.500,0.130,0.133,95.63,95.36,79.46,68.0,0.158

In [ ]:
df_bsadv

In [ ]:
from nba_api.stats.endpoints import boxscoreplayertrackv2

In [44]:
boxscoreplayertrackv2.BoxScorePlayerTrackV2(game_id='0041700404').get_data_frames()[0]

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,SPD,DIST,ORBC,DRBC,RBC,TCHS,SAST,FTAST,PASS,AST,CFGM,CFGA,CFG_PCT,UFGM,UFGA,UFG_PCT,FG_PCT,DFGM,DFGA,DFG_PCT
0,0041700404,1610612744,GSW,Golden State,201142,Kevin Durant,F,,37:38,3.91,2.45,5,14,17,78,1,0,55,10,5,11,0.455,2,6,0.333,0.412,3,6,0.500
1,0041700404,1610612744,GSW,Golden State,203110,Draymond Green,F,,38:37,3.99,2.56,2,14,16,91,0,1,75,9,1,1,1.000,3,7,0.429,0.500,4,7,0.571
2,0041700404,1610612744,GSW,Golden State,201580,JaVale McGee,C,,16:28,4.30,1.18,5,3,8,15,0,0,11,0,1,2,0.500,2,2,1.000,0.750,0,0,0.000
3,0041700404,1610612744,GSW,Golden State,202691,Klay Thompson,G,,28:30,4.30,2.04,2,11,13,31,1,0,19,0,0,3,0.000,4,7,0.571,0.400,3,3,1.000
4,0041700404,1610612744,GSW,Golden State,201939,Stephen Curry,G,,38:45,4.54,2.92,4,13,16,95,0,0,59,4,6,12,0.500,6,15,0.400,0.444,0,1,0.000
5,0041700404,1610612744,GSW,Golden State,2738,Andre Iguodala,,,22:41,4.04,1.52,3,3,6,34,0,0,24,0,0,1,0.000,4,7,0.571,0.500,2,2,1.000
6,0041700404,1610612744,GSW,Golden State,1628395,Jordan Bell,,,18:24,4.30,1.32,4,4,8,27,0,0,23,1,1,2,0.500,1,1,1.000,0.667,1,5,0.200
7,0041700404,1610612744,GSW,Golden State,2733,Shaun Livingston,,,14:04,4.20,0.98,2,4,6,22,1,0,19,0,0,0,0.000,0,1,0.000,0.000,0,0,0.000
8,0041700404,1610612744,GSW,Golden State,201156,Nick Young,,,8:59,3.84,0.58,0,3,3,9,0,0,5,0,0,1,0.000,1,3,0.333,0.250,0,0,0.000
9,0041700404,1610612744,GSW,Golden State,2561,David West,,,7:36,3.88,0.49,0,0,0,11,0,0,10,1,1,1,1.000,0,0,0.000,1.000,1,1,1.000
10,0041700404,1610612744,GSW,Golden State,1626172,Kevon Looney,,,2:47,3.81,0.18,1,0,1,5,0,0,3,0,0,0,0.000,1,2,0.500,0.500,1,1,1.000
11,0041700404,1610612744,GSW,Golden State,2585,Zaza Pachulia,,,2:47,4.00,0.19,2,1,3,6,0,0,3,0,0,1,0.000,0,0,0.000,0.000,0,0,0.000
12,0041700404,1610612744,GSW,Golden State,1627775,Patrick McCaw,,,2:47,3.78,0.18,1,0,1,8,0,0,8,0,0,0,0.000,0,0,0.000,0.000,0,0,0.000
13,0041700404,1610612739,CLE,Cleveland,2544,LeBron James,F,,40:34,3.78,2.55,3,8,11,103,2,0,71,8,3,8,0.375,4,5,0.800,0.538,1,3,0.333
14,0041700404,1610612739,CLE,Cleveland,201567,Kevin Love,F,,27:44,4.11,1.89,7,9,16,56,0,1,40,2,1,4,0.250,3,9,0.333,0.308,1,2,0.500
15,0041700404,1610612739,CLE,Cleveland,202684,Tristan Thompson,C,,16:12,4.44,1.19,9,6,15,22,0,0,16,0,2,4,0.500,1,1,1.000,0.600,2,3,0.667
16,0041700404,1610612739,CLE,Cleveland,2747,JR Smith,G,,26:35,4.12,1.82,2,5,7,33,0,0,24,1,0,3,0.000,3,5,0.600,0.375,1,1,1.000
17,0041700404,1610612739,CLE,Cleveland,201588,George Hill,G,,25:05,4.26,1.78,3,5,8,40,0,0,30,1,0,2,0.000,1,5,0.200,0.143,3,3,1.000
18,0041700404,1610612739,CLE,Cleveland,203918,Rodney Hood,,,26:32,4.31,1.90,7,9,16,50,0,0,33,2,2,8,0.250,2,6,0.333,0.286,0,0,0.000
19,0041700404,1610612739,CLE,Cleveland,201145,Jeff Green,,,23:40,3.92,1.54,0,0,0,27,1,0,18,1,0,2,0.000,2,6,0.333,0.250,1,1,1.000
20,0041700404,1610612739,CLE,Cleveland,2594,Kyle Korver,,,20:42,4.49,1.55,0,2,2,19,0,0,12,1,0,0,0.000,0,6,0.000,0.000,2,2,1.000
21,0041700404,1610612739,CLE,Cleveland,1626204,Larry Nance Jr.,,,23:12,4.31,1.66,11,6,17,33,0,0,24,4,3,5,0.600,0,2,0.000,0.429,3,4,0.750
22,0041700404,1610612739,CLE,Cleveland,1626224,Cedi Osman,,,4:03,3.84,0.26,0,0,0,5,0,0,2,0,1,1,1.000,0,2,0.000,0.333,0,0,0.000
23,0041700404,1610612739,CLE,Cleveland,101181,Jose Calderon,,,4:03,3.61,0.25,0,2,2,9,1,0,8,1,0,0,0.000,0,1,0.000,0.000,1,1,1.000
24,0041700404,1610612739,CLE,Cleveland,1627790,Ante Zizic,,,1:40,3.34,0.09,1,1,2,3,0,0,1,0,1,1,1.000,1,1,1.000,1.000,0,0,0.000
25,0041700404,1610612739,CLE,Cleveland,203903,Jordan Clarkson,,DNP - Coach's Decision,0:00,0.00,0.00,0,0,0,0,0,0,0,0,0,0,0.000,0,0,0.000,0.000,0,0,0.000

In [ ]:
help(boxscoreplayertrackv2)

In [ ]:
df2 = pd.read_csv(os.path.join('..', 'processed_data', '3game_date_home_away.csv'), parse_dates=['game_date'])
df2



df_empty = pd.DataFrame({})

In [ ]:
game_ids = '00' + df2.game_id.apply(str)
game_ids

In [ ]:
path = os.path.join('..', 'processed_data_preliminary', '5game_id_team_id_player_name_advanced_stats.csv')
df5 = pd.read_csv(path)
df5

In [ ]:
game_ids[game_ids == '0020600808']

In [ ]:
game_ids.shape

In [ ]:
14712 / 100

In [ ]:
startstops = [807 + i * 148 for i in range(0, 101)]
startstops

In [ ]:
startstops[100] = 15519
startstops[100]

In [ ]:
startstops

In [ ]:
game_ids

In [ ]:
len(startstops)

In [ ]:
for _ in range(len(startstops) - 1):
    print(_)

In [ ]:
game_ids[startstops[0]:startstops[1],]

In [ ]:
for i in range(len(startstops) - 1):
    for game_id_ in game_ids[startstops[i]:startstops[i+1],]:
        print(str(game_id_) + ': ' + str(startstops[i]) + ' : ' + str(startstops[i+1]))

In [ ]:
#set(df.column_name) - set(df2.column_name)

In [ ]:
#df.state[df.column_name.str.contains('state1|state2|state3|state4')]

In [ ]:
#regex
#df.column_name.replace(to_replace='\[.*\]', value='', regex=True, inplace=True)

In [ ]:
#df.plot(x='column_name1', y='column_name2', kind='scatter');

In [ ]:
#df.loc[df.column_name == 'state1', ['column_name', 'column_name']]

In [ ]:
#missing = pd.concat([df.isnull().sum(axis=1), 100 * df.isnull().mean(axis=1)], axis=1)
#missing.columns=['count', '%']
#missing.sort_values(by='count', ascending=False).head(10)

In [ ]:
#missing['%'].unique()

In [ ]:
#datapath = 'data'

In [ ]:
#if not os.path.exists(datapath):
    #os.mkdir(datapath)

In [ ]:
#datapath_df = os.path.join(datapath, 'df_cleaned.csv')
#if not os.path.exists(datapath_df):
#    df.to_csv(datapath_df, index=False)

In [ ]:
#datapath_df2 = os.path.join(datapath, 'df2.csv')
#if not os.path.exists(datapath_df2):
#    df2.to_csv(datapath_df2, index=False)