In [1]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA
from sklearn.preprocessing import scale


pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

pd.set_option('display.max_colwidth', None)
pd.options.display.max_info_columns = 999

#return the first 5 and last 5 rows of this dataframe
def p(df_):
    if df_.shape[0] > 6:
        print(df_.shape)
        return pd.concat([df_.head(), df_.tail()])
    else:
        return df_

def rcp(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'processed_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'processed_data', file_), parse_dates=pd_)
    
def rcr(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'raw_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'raw_data', file_), parse_dates=pd_)
    
#sort dataframe by column
def s(df_, column_):
    return df_.sort_values(column_)

#reset index and sort dataframe by column
def sr(df_, column_):
    df_ = df_.sort_values(column_)
    return df_.reset_index(drop=True)

#print length of list
def pl(list_):
    print(len(list_))
    return list_

#print length of list
def pdc(dict_):
    print(len(dict_))
    return dict_

In [2]:
df = rcp('52stat_matchup_cma_diff_2010_2018.csv', ['game_date'])
df = sr(df, 'game_date')
p(df)

(10266, 390)

,game_id,TEAM_NAME_a,TEAM_ABBREVIATION_a,TEAM_CITY_a,MIN_a,duration_a,E_OFF_RATING_a,OFF_RATING_a,E_DEF_RATING_a,DEF_RATING_a,E_NET_RATING_a,NET_RATING_a,AST_PCT_a,AST_TOV_a,AST_RATIO_a,OREB_PCT_a,DREB_PCT_a,REB_PCT_a,E_TM_TOV_PCT_a,TM_TOV_PCT_a,EFG_PCT_a,TS_PCT_a,USG_PCT_a,E_USG_PCT_a,E_PACE_a,PACE_a,PACE_PER40_a,POSS_a,PIE_a,duration_minutes_a,team_id_a,w_pct_a,min_a,fgm_a,fga_a,fg_pct_a,fg3m_a,fg3a_a,fg3_pct_a,ftm_a,fta_a,ft_pct_a,oreb_a,dreb_a,reb_a,ast_a,stl_a,blk_a,tov_a,pf_a,pts_a,wl_a,spread_a,away_home_a,game_date,matchup,season_type,season,season_year,a,b,E_OFF_RATING_cma_a,OFF_RATING_cma_a,E_DEF_RATING_cma_a,DEF_RATING_cma_a,E_NET_RATING_cma_a,NET_RATING_cma_a,AST_PCT_cma_a,AST_TOV_cma_a,AST_RATIO_cma_a,OREB_PCT_cma_a,DREB_PCT_cma_a,REB_PCT_cma_a,E_TM_TOV_PCT_cma_a,TM_TOV_PCT_cma_a,EFG_PCT_cma_a,TS_PCT_cma_a,USG_PCT_cma_a,E_USG_PCT_cma_a,E_PACE_cma_a,PACE_cma_a,PACE_PER40_cma_a,POSS_cma_a,PIE_cma_a,duration_minutes_cma_a,w_pct_cma_a,min_cma_a,fgm_cma_a,fga_cma_a,fg_pct_cma_a,fg3m_cma_a,fg3a_cma_a,fg3_pct_cma_a,ftm_cma_a,fta_cma_a,ft_pct_cma_a,oreb_cma_a,dreb_cma_a,reb_cma_a,ast_cma_a,stl_cma_a,blk_cma_a,tov_cma_a,pf_cma_a,pts_cma_a,spread_cma_a,away_home_cma_a,TEAM_NAME_b,TEAM_ABBREVIATION_b,TEAM_CITY_b,MIN_b,duration_b,E_OFF_RATING_b,OFF_RATING_b,E_DEF_RATING_b,DEF_RATING_b,E_NET_RATING_b,NET_RATING_b,AST_PCT_b,AST_TOV_b,AST_RATIO_b,OREB_PCT_b,DREB_PCT_b,REB_PCT_b,E_TM_TOV_PCT_b,TM_TOV_PCT_b,EFG_PCT_b,TS_PCT_b,USG_PCT_b,E_USG_PCT_b,E_PACE_b,PACE_b,PACE_PER40_b,POSS_b,PIE_b,duration_minutes_b,team_id_b,w_pct_b,min_b,fgm_b,fga_b,fg_pct_b,fg3m_b,fg3a_b,fg3_pct_b,ftm_b,fta_b,ft_pct_b,oreb_b,dreb_b,reb_b,ast_b,stl_b,blk_b,tov_b,pf_b,pts_b,wl_b,spread_b,away_home_b,E_OFF_RATING_cma_b,OFF_RATING_cma_b,E_DEF_RATING_cma_b,DEF_RATING_cma_b,E_NET_RATING_cma_b,NET_RATING_cma_b,AST_PCT_cma_b,AST_TOV_cma_b,AST_RATIO_cma_b,OREB_PCT_cma_b,DREB_PCT_cma_b,REB_PCT_cma_b,E_TM_TOV_PCT_cma_b,TM_TOV_PCT_cma_b,EFG_PCT_cma_b,TS_PCT_cma_b,USG_PCT_cma_b,E_USG_PCT_cma_b,E_PACE_cma_b,PACE_cma_b,PACE_PER40_cma_b,POSS_cma_b,PIE_cma_b,duration_minutes_cma_b,w_pct_cma_b,min_cma_b,fgm_cma_b,fga_cma_b,fg_pct_cma_b,fg3m_cma_b,fg3a_cma_b,fg3_pct_cma_b,ftm_cma_b,fta_cma_b,ft_pct_cma_b,oreb_cma_b,dreb_cma_b,reb_cma_b,ast_cma_b,stl_cma_b,blk_cma_b,tov_cma_b,pf_cma_b,pts_cma_b,spread_cma_b,away_home_cma_b,E_OFF_RATING_cma_diff,OFF_RATING_cma_diff,E_DEF_RATING_cma_diff,DEF_RATING_cma_diff,E_NET_RATING_cma_diff,NET_RATING_cma_diff,AST_PCT_cma_diff,AST_TOV_cma_diff,AST_RATIO_cma_diff,OREB_PCT_cma_diff,DREB_PCT_cma_diff,REB_PCT_cma_diff,E_TM_TOV_PCT_cma_diff,TM_TOV_PCT_cma_diff,EFG_PCT_cma_diff,TS_PCT_cma_diff,USG_PCT_cma_diff,E_USG_PCT_cma_diff,E_PACE_cma_diff,PACE_cma_diff,PACE_PER40_cma_diff,POSS_cma_diff,PIE_cma_diff,duration_minutes_cma_diff,w_pct_cma_diff,min_cma_diff,fgm_cma_diff,fga_cma_diff,fg_pct_cma_diff,fg3m_cma_diff,fg3a_cma_diff,fg3_pct_cma_diff,ftm_cma_diff,fta_cma_diff,ft_pct_cma_diff,oreb_cma_diff,dreb_cma_diff,reb_cma_diff,ast_cma_diff,stl_cma_diff,blk_cma_diff,tov_cma_diff,pf_cma_diff,pts_cma_diff,spread_cma_diff,away_home_cma_diff,E_OFF_RATING_sm_cma_diff,OFF_RATING_sm_cma_diff,E_DEF_RATING_sm_cma_diff,DEF_RATING_sm_cma_diff,E_NET_RATING_sm_cma_diff,NET_RATING_sm_cma_diff,AST_PCT_sm_cma_diff,AST_TOV_sm_cma_diff,AST_RATIO_sm_cma_diff,OREB_PCT_sm_cma_diff,DREB_PCT_sm_cma_diff,REB_PCT_sm_cma_diff,E_TM_TOV_PCT_sm_cma_diff,TM_TOV_PCT_sm_cma_diff,EFG_PCT_sm_cma_diff,TS_PCT_sm_cma_diff,USG_PCT_sm_cma_diff,E_USG_PCT_sm_cma_diff,E_PACE_sm_cma_diff,PACE_sm_cma_diff,PACE_PER40_sm_cma_diff,POSS_sm_cma_diff,PIE_sm_cma_diff,duration_minutes_sm_cma_diff,w_pct_sm_cma_diff,min_sm_cma_diff,fgm_sm_cma_diff,fga_sm_cma_diff,fg_pct_sm_cma_diff,fg3m_sm_cma_diff,fg3a_sm_cma_diff,fg3_pct_sm_cma_diff,ftm_sm_cma_diff,fta_sm_cma_diff,ft_pct_sm_cma_diff,oreb_sm_cma_diff,dreb_sm_cma_diff,reb_sm_cma_diff,ast_sm_cma_diff,stl_sm_cma_diff,blk_sm_cma_diff,tov_sm_cma_diff,pf_sm_cma_diff,pts_sm_cma_diff,spread_sm_cma_diff,away_home_sm_cma_diff,E_OFF_RATING_sm_cma_a,OFF_RATING_sm_cma_a,E_DEF_RATING_sm_cma_a,DEF_RATING_sm_cma_a,E_NET_RATING_sm_cma_a,NET_RATING_sm_cma_a,AST_PCT_sm_cma_a,AST_TOV_sm_cma_a,AST_RATIO_sm_cma_a,OREB_PCT_sm_cma_a,DREB_PCT_sm_cma_a,REB_PCT_sm_cma_a,E_TM_TOV_PCT_sm_cma_a,TM_TOV_PCT_sm_cma_a,EFG_PCT_sm_cma_a,TS_PCT_sm_cma_a,USG_PCT_sm_cma_a,E_USG_PCT_sm_cma_a,E_PACE_sm_cma_a,PACE_sm_cma_a,PACE_PER40_sm_cma_a,POSS_sm_cma_a,PIE_sm_cma_a,duration_minutes_sm_cma_a,w_pct_sm_cma_a,min_sm_cma_a,fgm_sm_cma_a,fga_sm_cma_a,fg_pct_sm_cma_a,fg3m_sm_cma_a,fg3a_sm_cma_a,fg3_pct_sm_cma_a,ftm_sm_cma_a,fta_sm_cma_a,ft_pct_sm_cma_a,oreb_sm_cma_a,dreb_sm_cma_a,reb_sm_cma_a,ast_sm_cma_a,stl_sm_cma_a,blk_sm_cma_a,tov_sm_cma_a,pf_sm_cma_a,pts_sm_cma_a,spread_sm_cma_a,away_home_sm_cma_a,E_OFF_RATING_sm_cma_b,OFF_RATING_sm_cma_b,E_DEF_RATING_sm_cma_b,DEF_RATING_sm_cma_b,E_NET_RATING_sm_cma_b,NET_RATING_sm_cma_b,AST_PCT_sm_cma_b,AST_TOV_sm_cma_b,AST_RATIO_sm_cma_b,OREB_PCT_sm_cma_b,DREB_PCT_sm_cma_b,REB_PCT_sm_cma_b,E_TM_TOV_PCT_sm_cma_b,TM_TOV_PCT_sm_cma_b,EFG_PCT_sm_cma_b,TS_PCT_sm_cma_b,USG_PCT_sm_cma_b,E_USG_PCT_sm_cma_b,E_PACE_sm_cma_b,PACE_sm_cma_b,PACE_PER40_sm_cma_b,POSS_sm_cma_b,PIE_sm_cma_b,duration_minutes_sm_cma_b,w_pct_sm_cma_b,min_sm_cma_b,fgm_sm_cma_b,fga_sm_cma_b,fg_pct_sm_cma_b,fg3m_sm_cma_b,fg3a_sm_cma_b,fg3_pct_sm_cma_b,ftm_sm_cma_b,fta_sm_cma_b,ft_pct_sm_cma_b,oreb_sm_cma_b,dreb_sm_cma_b,reb_sm_cma_b,ast_sm_cma_b,stl_sm_cma_b,blk_sm_cma_b,tov_sm_cma_b,pf_sm_cma_b,pts_sm_cma_b,spread_sm_cma_b,away_home_sm_cma_b
0,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.50,76.25,92,0.599,240.0,1610612738,1.000,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.50,76.25,91,0.401,240.0,1610612748,0.000,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.00,75.00,90,0.375,240.0,1610612756,0.000,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.00,75.00,90,0.625,240.0,1610612757,1.000,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.50,86.25,103,0.507,240.0,1610612745,0.000,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,HOU,LAL,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.50,86.25,104,0.493,240.0,1610612747,1.000,240,40,96,0.417,9,21,0.429,23,28,0.821429,14,30,44,21,11,4,12,24,112,W,-2,1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,21000009,Timberwolves,MIN,Minnesota,240:00,0 days 04:00:00,110.1,112.6,111.8,114.7,-1.6,-2.1,0.512,1.69,15.9,0.320,0.691,0.514,12.343,12.6,0.516,0.561,1.0,0.199,105.00,102.50,85.42,103,0.482,240.0,1610612750,0.000,240,43,91,0.473,8,18,0.444,22,28,0.785714,11,35,46,22,5,8,13,32,116,L,1,1,2010-10-27,MIN vs. SAC,Regular Season,2010-11,2010,MIN,SAC,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,Kings,SAC,Sacramento,240:00,0 days 04:00:00,111.8,114.7,110.1,112.6,1.6,2.1,0.641,1.92,17.4,0.309,0.680,0.486,12.419,12.7,0.482,0.554,1.0,0.199,105.00,102.50,85.42,102,0.518,240.0,1610612758,1.000,240,39,85,0.459,4,11,0.364,35,47,0.744681,14,31,45,25,8,4,13,24,117,W,-1,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [3]:
columns_names_all_list = list(df.columns)
pl(columns_names_all_list)

390

['game_id',
 'TEAM_NAME_a',
 'TEAM_ABBREVIATION_a',
 'TEAM_CITY_a',
 'MIN_a',
 'duration_a',
 'E_OFF_RATING_a',
 'OFF_RATING_a',
 'E_DEF_RATING_a',
 'DEF_RATING_a',
 'E_NET_RATING_a',
 'NET_RATING_a',
 'AST_PCT_a',
 'AST_TOV_a',
 'AST_RATIO_a',
 'OREB_PCT_a',
 'DREB_PCT_a',
 'REB_PCT_a',
 'E_TM_TOV_PCT_a',
 'TM_TOV_PCT_a',
 'EFG_PCT_a',
 'TS_PCT_a',
 'USG_PCT_a',
 'E_USG_PCT_a',
 'E_PACE_a',
 'PACE_a',
 'PACE_PER40_a',
 'POSS_a',
 'PIE_a',
 'duration_minutes_a',
 'team_id_a',
 'w_pct_a',
 'min_a',
 'fgm_a',
 'fga_a',
 'fg_pct_a',
 'fg3m_a',
 'fg3a_a',
 'fg3_pct_a',
 'ftm_a',
 'fta_a',
 'ft_pct_a',
 'oreb_a',
 'dreb_a',
 'reb_a',
 'ast_a',
 'stl_a',
 'blk_a',
 'tov_a',
 'pf_a',
 'pts_a',
 'wl_a',
 'spread_a',
 'away_home_a',
 'game_date',
 'matchup',
 'season_type',
 'season',
 'season_year',
 'a',
 'b',
 'E_OFF_RATING_cma_a',
 'OFF_RATING_cma_a',
 'E_DEF_RATING_cma_a',
 'DEF_RATING_cma_a',
 'E_NET_RATING_cma_a',
 'NET_RATING_cma_a',
 'AST_PCT_cma_a',
 'AST_TOV_cma_a',
 'AST_RATIO_cma_a',
 'OREB_PCT_cma_a',
 'DREB_PCT_cma_a',
 'REB_PCT_cma_a',
 'E_TM_TOV_PCT_cma_a',
 'TM_TOV_PCT_cma_a',
 'EFG_PCT_cma_a',
 'TS_PCT_cma_a',
 'USG_PCT_cma_a',
 'E_USG_PCT_cma_a',
 'E_PACE_cma_a',
 'PACE_cma_a',
 'PACE_PER40_cma_a',
 'POSS_cma_a',
 'PIE_cma_a',
 'duration_minutes_cma_a',
 'w_pct_cma_a',
 'min_cma_a',
 'fgm_cma_a',
 'fga_cma_a',
 'fg_pct_cma_a',
 'fg3m_cma_a',
 'fg3a_cma_a',
 'fg3_pct_cma_a',
 'ftm_cma_a',
 'fta_cma_a',
 'ft_pct_cma_a',
 'oreb_cma_a',
 'dreb_cma_a',
 'reb_cma_a',
 'ast_cma_a',
 'stl_cma_a',
 'blk_cma_a',
 'tov_cma_a',
 'pf_cma_a',
 'pts_cma_a',
 'spread_cma_a',
 'away_home_cma_a',
 'TEAM_NAME_b',
 'TEAM_ABBREVIATION_b',
 'TEAM_CITY_b',
 'MIN_b',
 'duration_b',
 'E_OFF_RATING_b',
 'OFF_RATING_b',
 'E_DEF_RATING_b',
 'DEF_RATING_b',
 'E_NET_RATING_b',
 'NET_RATING_b',
 'AST_PCT_b',
 'AST_TOV_b',
 'AST_RATIO_b',
 'OREB_PCT_b',
 'DREB_PCT_b',
 'REB_PCT_b',
 'E_TM_TOV_PCT_b',
 'TM_TOV_PCT_b',
 'EFG_PCT_b',
 'TS_PCT_b',
 'USG_PCT_b',
 'E_USG_PCT_b',
 'E_PACE_b',
 'PACE_b',
 'PACE_PER40_b',
 'POSS_b',
 'PIE_b',
 'duration_minutes_b',
 'team_id_b',
 'w_pct_b',
 'min_b',
 'fgm_b',
 'fga_b',
 'fg_pct_b',
 'fg3m_b',
 'fg3a_b',
 'fg3_pct_b',
 'ftm_b',
 'fta_b',
 'ft_pct_b',
 'oreb_b',
 'dreb_b',
 'reb_b',
 'ast_b',
 'stl_b',
 'blk_b',
 'tov_b',
 'pf_b',
 'pts_b',
 'wl_b',
 'spread_b',
 'away_home_b',
 'E_OFF_RATING_cma_b',
 'OFF_RATING_cma_b',
 'E_DEF_RATING_cma_b',
 'DEF_RATING_cma_b',
 'E_NET_RATING_cma_b',
 'NET_RATING_cma_b',
 'AST_PCT_cma_b',
 'AST_TOV_cma_b',
 'AST_RATIO_cma_b',
 'OREB_PCT_cma_b',
 'DREB_PCT_cma_b',
 'REB_PCT_cma_b',
 'E_TM_TOV_PCT_cma_b',
 'TM_TOV_PCT_cma_b',
 'EFG_PCT_cma_b',
 'TS_PCT_cma_b',
 'USG_PCT_cma_b',
 'E_USG_PCT_cma_b',
 'E_PACE_cma_b',
 'PACE_cma_b',
 'PACE_PER40_cma_b',
 'POSS_cma_b',
 'PIE_cma_b',
 'duration_minutes_cma_b',
 'w_pct_cma_b',
 'min_cma_b',
 'fgm_cma_b',
 'fga_cma_b',
 'fg_pct_cma_b',
 'fg3m_cma_b',
 'fg3a_cma_b',
 'fg3_pct_cma_b',
 'ftm_cma_b',
 'fta_cma_b',
 'ft_pct_cma_b',
 'oreb_cma_b',
 'dreb_cma_b',
 'reb_cma_b',
 'ast_cma_b',
 'stl_cma_b',
 'blk_cma_b',
 'tov_cma_b',
 'pf_cma_b',
 'pts_cma_b',
 'spread_cma_b',
 'away_home_cma_b',
 'E_OFF_RATING_cma_diff',
 'OFF_RATING_cma_diff',
 'E_DEF_RATING_cma_diff',
 'DEF_RATING_cma_diff',
 'E_NET_RATING_cma_diff',
 'NET_RATING_cma_diff',
 'AST_PCT_cma_diff',
 'AST_TOV_cma_diff',
 'AST_RATIO_cma_diff',
 'OREB_PCT_cma_diff',
 'DREB_PCT_cma_diff',
 'REB_PCT_cma_diff',
 'E_TM_TOV_PCT_cma_diff',
 'TM_TOV_PCT_cma_diff',
 'EFG_PCT_cma_diff',
 'TS_PCT_cma_diff',
 'USG_PCT_cma_diff',
 'E_USG_PCT_cma_diff',
 'E_PACE_cma_diff',
 'PACE_cma_diff',
 'PACE_PER40_cma_diff',
 'POSS_cma_diff',
 'PIE_cma_diff',
 'duration_minutes_cma_diff',
 'w_pct_cma_diff',
 'min_cma_diff',
 'fgm_cma_diff',
 'fga_cma_diff',
 'fg_pct_cma_diff',
 'fg3m_cma_diff',
 'fg3a_cma_diff',
 'fg3_pct_cma_diff',
 'ftm_cma_diff',
 'fta_cma_diff',
 'ft_pct_cma_diff',
 'oreb_cma_diff',
 'dreb_cma_diff',
 'reb_cma_diff',
 'ast_cma_diff',
 'stl_cma_diff',
 'blk_cma_diff',
 'tov_cma_diff',
 'pf_cma_diff',
 'pts_cma_diff',
 'spread_cma_diff',
 'away_home_cma_diff',
 'E_OFF_RATING_sm_cma_diff',
 'OFF_RATING_sm_cma_diff',
 'E_DEF_RATING_sm_cma_diff',
 'DEF_RATING_sm_cma_diff',
 'E_NET_RATING_sm_cma_diff',
 'NET_RATING_sm_cma_diff',
 'AST_PCT_sm_cma_diff',
 'AST_TOV_sm_cma_diff',
 'AST_RATIO_sm_cma_diff',
 'OREB_PCT_sm_cma_diff',
 'DREB_PCT_sm_cma_diff',
 'REB_PCT_sm_cma_diff',
 'E_TM_TOV_PCT_sm_cma_diff',
 'TM_TOV_PCT_sm_cma_diff',
 'EFG_PCT_sm_cma_diff',
 'TS_PCT_sm_cma_diff',
 'USG_PCT_sm_cma_diff',
 'E_USG_PCT_sm_cma_diff',
 'E_PACE_sm_cma_diff',
 'PACE_sm_cma_diff',
 'PACE_PER40_sm_cma_diff',
 'POSS_sm_cma_diff',
 'PIE_sm_cma_diff',
 'duration_minutes_sm_cma_diff',
 'w_pct_sm_cma_diff',
 'min_sm_cma_diff',
 'fgm_sm_cma_diff',
 'fga_sm_cma_diff',
 'fg_pct_sm_cma_diff',
 'fg3m_sm_cma_diff',
 'fg3a_sm_cma_diff',
 'fg3_pct_sm_cma_diff',
 'ftm_sm_cma_diff',
 'fta_sm_cma_diff',
 'ft_pct_sm_cma_diff',
 'oreb_sm_cma_diff',
 'dreb_sm_cma_diff',
 'reb_sm_cma_diff',
 'ast_sm_cma_diff',
 'stl_sm_cma_diff',
 'blk_sm_cma_diff',
 'tov_sm_cma_diff',
 'pf_sm_cma_diff',
 'pts_sm_cma_diff',
 'spread_sm_cma_diff',
 'away_home_sm_cma_diff',
 'E_OFF_RATING_sm_cma_a',
 'OFF_RATING_sm_cma_a',
 'E_DEF_RATING_sm_cma_a',
 'DEF_RATING_sm_cma_a',
 'E_NET_RATING_sm_cma_a',
 'NET_RATING_sm_cma_a',
 'AST_PCT_sm_cma_a',
 'AST_TOV_sm_cma_a',
 'AST_RATIO_sm_cma_a',
 'OREB_PCT_sm_cma_a',
 'DREB_PCT_sm_cma_a',
 'REB_PCT_sm_cma_a',
 'E_TM_TOV_PCT_sm_cma_a',
 'TM_TOV_PCT_sm_cma_a',
 'EFG_PCT_sm_cma_a',
 'TS_PCT_sm_cma_a',
 'USG_PCT_sm_cma_a',
 'E_USG_PCT_sm_cma_a',
 'E_PACE_sm_cma_a',
 'PACE_sm_cma_a',
 'PACE_PER40_sm_cma_a',
 'POSS_sm_cma_a',
 'PIE_sm_cma_a',
 'duration_minutes_sm_cma_a',
 'w_pct_sm_cma_a',
 'min_sm_cma_a',
 'fgm_sm_cma_a',
 'fga_sm_cma_a',
 'fg_pct_sm_cma_a',
 'fg3m_sm_cma_a',
 'fg3a_sm_cma_a',
 'fg3_pct_sm_cma_a',
 'ftm_sm_cma_a',
 'fta_sm_cma_a',
 'ft_pct_sm_cma_a',
 'oreb_sm_cma_a',
 'dreb_sm_cma_a',
 'reb_sm_cma_a',
 'ast_sm_cma_a',
 'stl_sm_cma_a',
 'blk_sm_cma_a',
 'tov_sm_cma_a',
 'pf_sm_cma_a',
 'pts_sm_cma_a',
 'spread_sm_cma_a',
 'away_home_sm_cma_a',
 'E_OFF_RATING_sm_cma_b',
 'OFF_RATING_sm_cma_b',
 'E_DEF_RATING_sm_cma_b',
 'DEF_RATING_sm_cma_b',
 'E_NET_RATING_sm_cma_b',
 'NET_RATING_sm_cma_b',
 'AST_PCT_sm_cma_b',
 'AST_TOV_sm_cma_b',
 'AST_RATIO_sm_cma_b',
 'OREB_PCT_sm_cma_b',
 'DREB_PCT_sm_cma_b',
 'REB_PCT_sm_cma_b',
 'E_TM_TOV_PCT_sm_cma_b',
 'TM_TOV_PCT_sm_cma_b',
 'EFG_PCT_sm_cma_b',
 'TS_PCT_sm_cma_b',
 'USG_PCT_sm_cma_b',
 'E_USG_PCT_sm_cma_b',
 'E_PACE_sm_cma_b',
 'PACE_sm_cma_b',
 'PACE_PER40_sm_cma_b',
 'POSS_sm_cma_b',
 'PIE_sm_cma_b',
 'duration_minutes_sm_cma_b',
 'w_pct_sm_cma_b',
 'min_sm_cma_b',
 'fgm_sm_cma_b',
 'fga_sm_cma_b',
 'fg_pct_sm_cma_b',
 'fg3m_sm_cma_b',
 'fg3a_sm_cma_b',
 'fg3_pct_sm_cma_b',
 'ftm_sm_cma_b',
 'fta_sm_cma_b',
 'ft_pct_sm_cma_b',
 'oreb_sm_cma_b',
 'dreb_sm_cma_b',
 'reb_sm_cma_b',
 'ast_sm_cma_b',
 'stl_sm_cma_b',
 'blk_sm_cma_b',
 'tov_sm_cma_b',
 'pf_sm_cma_b',
 'pts_sm_cma_b',
 'spread_sm_cma_b',
 'away_home_sm_cma_b']

In [4]:
column_names_number_list_pred = list(df.select_dtypes('number'))
pl(column_names_number_list_pred)

372

['game_id',
 'E_OFF_RATING_a',
 'OFF_RATING_a',
 'E_DEF_RATING_a',
 'DEF_RATING_a',
 'E_NET_RATING_a',
 'NET_RATING_a',
 'AST_PCT_a',
 'AST_TOV_a',
 'AST_RATIO_a',
 'OREB_PCT_a',
 'DREB_PCT_a',
 'REB_PCT_a',
 'E_TM_TOV_PCT_a',
 'TM_TOV_PCT_a',
 'EFG_PCT_a',
 'TS_PCT_a',
 'USG_PCT_a',
 'E_USG_PCT_a',
 'E_PACE_a',
 'PACE_a',
 'PACE_PER40_a',
 'POSS_a',
 'PIE_a',
 'duration_minutes_a',
 'team_id_a',
 'w_pct_a',
 'min_a',
 'fgm_a',
 'fga_a',
 'fg_pct_a',
 'fg3m_a',
 'fg3a_a',
 'fg3_pct_a',
 'ftm_a',
 'fta_a',
 'ft_pct_a',
 'oreb_a',
 'dreb_a',
 'reb_a',
 'ast_a',
 'stl_a',
 'blk_a',
 'tov_a',
 'pf_a',
 'pts_a',
 'spread_a',
 'away_home_a',
 'season_year',
 'E_OFF_RATING_cma_a',
 'OFF_RATING_cma_a',
 'E_DEF_RATING_cma_a',
 'DEF_RATING_cma_a',
 'E_NET_RATING_cma_a',
 'NET_RATING_cma_a',
 'AST_PCT_cma_a',
 'AST_TOV_cma_a',
 'AST_RATIO_cma_a',
 'OREB_PCT_cma_a',
 'DREB_PCT_cma_a',
 'REB_PCT_cma_a',
 'E_TM_TOV_PCT_cma_a',
 'TM_TOV_PCT_cma_a',
 'EFG_PCT_cma_a',
 'TS_PCT_cma_a',
 'USG_PCT_cma_a',
 'E_USG_PCT_cma_a',
 'E_PACE_cma_a',
 'PACE_cma_a',
 'PACE_PER40_cma_a',
 'POSS_cma_a',
 'PIE_cma_a',
 'duration_minutes_cma_a',
 'w_pct_cma_a',
 'min_cma_a',
 'fgm_cma_a',
 'fga_cma_a',
 'fg_pct_cma_a',
 'fg3m_cma_a',
 'fg3a_cma_a',
 'fg3_pct_cma_a',
 'ftm_cma_a',
 'fta_cma_a',
 'ft_pct_cma_a',
 'oreb_cma_a',
 'dreb_cma_a',
 'reb_cma_a',
 'ast_cma_a',
 'stl_cma_a',
 'blk_cma_a',
 'tov_cma_a',
 'pf_cma_a',
 'pts_cma_a',
 'spread_cma_a',
 'away_home_cma_a',
 'E_OFF_RATING_b',
 'OFF_RATING_b',
 'E_DEF_RATING_b',
 'DEF_RATING_b',
 'E_NET_RATING_b',
 'NET_RATING_b',
 'AST_PCT_b',
 'AST_TOV_b',
 'AST_RATIO_b',
 'OREB_PCT_b',
 'DREB_PCT_b',
 'REB_PCT_b',
 'E_TM_TOV_PCT_b',
 'TM_TOV_PCT_b',
 'EFG_PCT_b',
 'TS_PCT_b',
 'USG_PCT_b',
 'E_USG_PCT_b',
 'E_PACE_b',
 'PACE_b',
 'PACE_PER40_b',
 'POSS_b',
 'PIE_b',
 'duration_minutes_b',
 'team_id_b',
 'w_pct_b',
 'min_b',
 'fgm_b',
 'fga_b',
 'fg_pct_b',
 'fg3m_b',
 'fg3a_b',
 'fg3_pct_b',
 'ftm_b',
 'fta_b',
 'ft_pct_b',
 'oreb_b',
 'dreb_b',
 'reb_b',
 'ast_b',
 'stl_b',
 'blk_b',
 'tov_b',
 'pf_b',
 'pts_b',
 'spread_b',
 'away_home_b',
 'E_OFF_RATING_cma_b',
 'OFF_RATING_cma_b',
 'E_DEF_RATING_cma_b',
 'DEF_RATING_cma_b',
 'E_NET_RATING_cma_b',
 'NET_RATING_cma_b',
 'AST_PCT_cma_b',
 'AST_TOV_cma_b',
 'AST_RATIO_cma_b',
 'OREB_PCT_cma_b',
 'DREB_PCT_cma_b',
 'REB_PCT_cma_b',
 'E_TM_TOV_PCT_cma_b',
 'TM_TOV_PCT_cma_b',
 'EFG_PCT_cma_b',
 'TS_PCT_cma_b',
 'USG_PCT_cma_b',
 'E_USG_PCT_cma_b',
 'E_PACE_cma_b',
 'PACE_cma_b',
 'PACE_PER40_cma_b',
 'POSS_cma_b',
 'PIE_cma_b',
 'duration_minutes_cma_b',
 'w_pct_cma_b',
 'min_cma_b',
 'fgm_cma_b',
 'fga_cma_b',
 'fg_pct_cma_b',
 'fg3m_cma_b',
 'fg3a_cma_b',
 'fg3_pct_cma_b',
 'ftm_cma_b',
 'fta_cma_b',
 'ft_pct_cma_b',
 'oreb_cma_b',
 'dreb_cma_b',
 'reb_cma_b',
 'ast_cma_b',
 'stl_cma_b',
 'blk_cma_b',
 'tov_cma_b',
 'pf_cma_b',
 'pts_cma_b',
 'spread_cma_b',
 'away_home_cma_b',
 'E_OFF_RATING_cma_diff',
 'OFF_RATING_cma_diff',
 'E_DEF_RATING_cma_diff',
 'DEF_RATING_cma_diff',
 'E_NET_RATING_cma_diff',
 'NET_RATING_cma_diff',
 'AST_PCT_cma_diff',
 'AST_TOV_cma_diff',
 'AST_RATIO_cma_diff',
 'OREB_PCT_cma_diff',
 'DREB_PCT_cma_diff',
 'REB_PCT_cma_diff',
 'E_TM_TOV_PCT_cma_diff',
 'TM_TOV_PCT_cma_diff',
 'EFG_PCT_cma_diff',
 'TS_PCT_cma_diff',
 'USG_PCT_cma_diff',
 'E_USG_PCT_cma_diff',
 'E_PACE_cma_diff',
 'PACE_cma_diff',
 'PACE_PER40_cma_diff',
 'POSS_cma_diff',
 'PIE_cma_diff',
 'duration_minutes_cma_diff',
 'w_pct_cma_diff',
 'min_cma_diff',
 'fgm_cma_diff',
 'fga_cma_diff',
 'fg_pct_cma_diff',
 'fg3m_cma_diff',
 'fg3a_cma_diff',
 'fg3_pct_cma_diff',
 'ftm_cma_diff',
 'fta_cma_diff',
 'ft_pct_cma_diff',
 'oreb_cma_diff',
 'dreb_cma_diff',
 'reb_cma_diff',
 'ast_cma_diff',
 'stl_cma_diff',
 'blk_cma_diff',
 'tov_cma_diff',
 'pf_cma_diff',
 'pts_cma_diff',
 'spread_cma_diff',
 'away_home_cma_diff',
 'E_OFF_RATING_sm_cma_diff',
 'OFF_RATING_sm_cma_diff',
 'E_DEF_RATING_sm_cma_diff',
 'DEF_RATING_sm_cma_diff',
 'E_NET_RATING_sm_cma_diff',
 'NET_RATING_sm_cma_diff',
 'AST_PCT_sm_cma_diff',
 'AST_TOV_sm_cma_diff',
 'AST_RATIO_sm_cma_diff',
 'OREB_PCT_sm_cma_diff',
 'DREB_PCT_sm_cma_diff',
 'REB_PCT_sm_cma_diff',
 'E_TM_TOV_PCT_sm_cma_diff',
 'TM_TOV_PCT_sm_cma_diff',
 'EFG_PCT_sm_cma_diff',
 'TS_PCT_sm_cma_diff',
 'USG_PCT_sm_cma_diff',
 'E_USG_PCT_sm_cma_diff',
 'E_PACE_sm_cma_diff',
 'PACE_sm_cma_diff',
 'PACE_PER40_sm_cma_diff',
 'POSS_sm_cma_diff',
 'PIE_sm_cma_diff',
 'duration_minutes_sm_cma_diff',
 'w_pct_sm_cma_diff',
 'min_sm_cma_diff',
 'fgm_sm_cma_diff',
 'fga_sm_cma_diff',
 'fg_pct_sm_cma_diff',
 'fg3m_sm_cma_diff',
 'fg3a_sm_cma_diff',
 'fg3_pct_sm_cma_diff',
 'ftm_sm_cma_diff',
 'fta_sm_cma_diff',
 'ft_pct_sm_cma_diff',
 'oreb_sm_cma_diff',
 'dreb_sm_cma_diff',
 'reb_sm_cma_diff',
 'ast_sm_cma_diff',
 'stl_sm_cma_diff',
 'blk_sm_cma_diff',
 'tov_sm_cma_diff',
 'pf_sm_cma_diff',
 'pts_sm_cma_diff',
 'spread_sm_cma_diff',
 'away_home_sm_cma_diff',
 'E_OFF_RATING_sm_cma_a',
 'OFF_RATING_sm_cma_a',
 'E_DEF_RATING_sm_cma_a',
 'DEF_RATING_sm_cma_a',
 'E_NET_RATING_sm_cma_a',
 'NET_RATING_sm_cma_a',
 'AST_PCT_sm_cma_a',
 'AST_TOV_sm_cma_a',
 'AST_RATIO_sm_cma_a',
 'OREB_PCT_sm_cma_a',
 'DREB_PCT_sm_cma_a',
 'REB_PCT_sm_cma_a',
 'E_TM_TOV_PCT_sm_cma_a',
 'TM_TOV_PCT_sm_cma_a',
 'EFG_PCT_sm_cma_a',
 'TS_PCT_sm_cma_a',
 'USG_PCT_sm_cma_a',
 'E_USG_PCT_sm_cma_a',
 'E_PACE_sm_cma_a',
 'PACE_sm_cma_a',
 'PACE_PER40_sm_cma_a',
 'POSS_sm_cma_a',
 'PIE_sm_cma_a',
 'duration_minutes_sm_cma_a',
 'w_pct_sm_cma_a',
 'min_sm_cma_a',
 'fgm_sm_cma_a',
 'fga_sm_cma_a',
 'fg_pct_sm_cma_a',
 'fg3m_sm_cma_a',
 'fg3a_sm_cma_a',
 'fg3_pct_sm_cma_a',
 'ftm_sm_cma_a',
 'fta_sm_cma_a',
 'ft_pct_sm_cma_a',
 'oreb_sm_cma_a',
 'dreb_sm_cma_a',
 'reb_sm_cma_a',
 'ast_sm_cma_a',
 'stl_sm_cma_a',
 'blk_sm_cma_a',
 'tov_sm_cma_a',
 'pf_sm_cma_a',
 'pts_sm_cma_a',
 'spread_sm_cma_a',
 'away_home_sm_cma_a',
 'E_OFF_RATING_sm_cma_b',
 'OFF_RATING_sm_cma_b',
 'E_DEF_RATING_sm_cma_b',
 'DEF_RATING_sm_cma_b',
 'E_NET_RATING_sm_cma_b',
 'NET_RATING_sm_cma_b',
 'AST_PCT_sm_cma_b',
 'AST_TOV_sm_cma_b',
 'AST_RATIO_sm_cma_b',
 'OREB_PCT_sm_cma_b',
 'DREB_PCT_sm_cma_b',
 'REB_PCT_sm_cma_b',
 'E_TM_TOV_PCT_sm_cma_b',
 'TM_TOV_PCT_sm_cma_b',
 'EFG_PCT_sm_cma_b',
 'TS_PCT_sm_cma_b',
 'USG_PCT_sm_cma_b',
 'E_USG_PCT_sm_cma_b',
 'E_PACE_sm_cma_b',
 'PACE_sm_cma_b',
 'PACE_PER40_sm_cma_b',
 'POSS_sm_cma_b',
 'PIE_sm_cma_b',
 'duration_minutes_sm_cma_b',
 'w_pct_sm_cma_b',
 'min_sm_cma_b',
 'fgm_sm_cma_b',
 'fga_sm_cma_b',
 'fg_pct_sm_cma_b',
 'fg3m_sm_cma_b',
 'fg3a_sm_cma_b',
 'fg3_pct_sm_cma_b',
 'ftm_sm_cma_b',
 'fta_sm_cma_b',
 'ft_pct_sm_cma_b',
 'oreb_sm_cma_b',
 'dreb_sm_cma_b',
 'reb_sm_cma_b',
 'ast_sm_cma_b',
 'stl_sm_cma_b',
 'blk_sm_cma_b',
 'tov_sm_cma_b',
 'pf_sm_cma_b',
 'pts_sm_cma_b',
 'spread_sm_cma_b',
 'away_home_sm_cma_b']

In [5]:
column_names_cma_list_pred = [k for k in column_names_number_list_pred if '_cma' in k]
pl(column_names_cma_list_pred)

276

['E_OFF_RATING_cma_a',
 'OFF_RATING_cma_a',
 'E_DEF_RATING_cma_a',
 'DEF_RATING_cma_a',
 'E_NET_RATING_cma_a',
 'NET_RATING_cma_a',
 'AST_PCT_cma_a',
 'AST_TOV_cma_a',
 'AST_RATIO_cma_a',
 'OREB_PCT_cma_a',
 'DREB_PCT_cma_a',
 'REB_PCT_cma_a',
 'E_TM_TOV_PCT_cma_a',
 'TM_TOV_PCT_cma_a',
 'EFG_PCT_cma_a',
 'TS_PCT_cma_a',
 'USG_PCT_cma_a',
 'E_USG_PCT_cma_a',
 'E_PACE_cma_a',
 'PACE_cma_a',
 'PACE_PER40_cma_a',
 'POSS_cma_a',
 'PIE_cma_a',
 'duration_minutes_cma_a',
 'w_pct_cma_a',
 'min_cma_a',
 'fgm_cma_a',
 'fga_cma_a',
 'fg_pct_cma_a',
 'fg3m_cma_a',
 'fg3a_cma_a',
 'fg3_pct_cma_a',
 'ftm_cma_a',
 'fta_cma_a',
 'ft_pct_cma_a',
 'oreb_cma_a',
 'dreb_cma_a',
 'reb_cma_a',
 'ast_cma_a',
 'stl_cma_a',
 'blk_cma_a',
 'tov_cma_a',
 'pf_cma_a',
 'pts_cma_a',
 'spread_cma_a',
 'away_home_cma_a',
 'E_OFF_RATING_cma_b',
 'OFF_RATING_cma_b',
 'E_DEF_RATING_cma_b',
 'DEF_RATING_cma_b',
 'E_NET_RATING_cma_b',
 'NET_RATING_cma_b',
 'AST_PCT_cma_b',
 'AST_TOV_cma_b',
 'AST_RATIO_cma_b',
 'OREB_PCT_cma_b',
 'DREB_PCT_cma_b',
 'REB_PCT_cma_b',
 'E_TM_TOV_PCT_cma_b',
 'TM_TOV_PCT_cma_b',
 'EFG_PCT_cma_b',
 'TS_PCT_cma_b',
 'USG_PCT_cma_b',
 'E_USG_PCT_cma_b',
 'E_PACE_cma_b',
 'PACE_cma_b',
 'PACE_PER40_cma_b',
 'POSS_cma_b',
 'PIE_cma_b',
 'duration_minutes_cma_b',
 'w_pct_cma_b',
 'min_cma_b',
 'fgm_cma_b',
 'fga_cma_b',
 'fg_pct_cma_b',
 'fg3m_cma_b',
 'fg3a_cma_b',
 'fg3_pct_cma_b',
 'ftm_cma_b',
 'fta_cma_b',
 'ft_pct_cma_b',
 'oreb_cma_b',
 'dreb_cma_b',
 'reb_cma_b',
 'ast_cma_b',
 'stl_cma_b',
 'blk_cma_b',
 'tov_cma_b',
 'pf_cma_b',
 'pts_cma_b',
 'spread_cma_b',
 'away_home_cma_b',
 'E_OFF_RATING_cma_diff',
 'OFF_RATING_cma_diff',
 'E_DEF_RATING_cma_diff',
 'DEF_RATING_cma_diff',
 'E_NET_RATING_cma_diff',
 'NET_RATING_cma_diff',
 'AST_PCT_cma_diff',
 'AST_TOV_cma_diff',
 'AST_RATIO_cma_diff',
 'OREB_PCT_cma_diff',
 'DREB_PCT_cma_diff',
 'REB_PCT_cma_diff',
 'E_TM_TOV_PCT_cma_diff',
 'TM_TOV_PCT_cma_diff',
 'EFG_PCT_cma_diff',
 'TS_PCT_cma_diff',
 'USG_PCT_cma_diff',
 'E_USG_PCT_cma_diff',
 'E_PACE_cma_diff',
 'PACE_cma_diff',
 'PACE_PER40_cma_diff',
 'POSS_cma_diff',
 'PIE_cma_diff',
 'duration_minutes_cma_diff',
 'w_pct_cma_diff',
 'min_cma_diff',
 'fgm_cma_diff',
 'fga_cma_diff',
 'fg_pct_cma_diff',
 'fg3m_cma_diff',
 'fg3a_cma_diff',
 'fg3_pct_cma_diff',
 'ftm_cma_diff',
 'fta_cma_diff',
 'ft_pct_cma_diff',
 'oreb_cma_diff',
 'dreb_cma_diff',
 'reb_cma_diff',
 'ast_cma_diff',
 'stl_cma_diff',
 'blk_cma_diff',
 'tov_cma_diff',
 'pf_cma_diff',
 'pts_cma_diff',
 'spread_cma_diff',
 'away_home_cma_diff',
 'E_OFF_RATING_sm_cma_diff',
 'OFF_RATING_sm_cma_diff',
 'E_DEF_RATING_sm_cma_diff',
 'DEF_RATING_sm_cma_diff',
 'E_NET_RATING_sm_cma_diff',
 'NET_RATING_sm_cma_diff',
 'AST_PCT_sm_cma_diff',
 'AST_TOV_sm_cma_diff',
 'AST_RATIO_sm_cma_diff',
 'OREB_PCT_sm_cma_diff',
 'DREB_PCT_sm_cma_diff',
 'REB_PCT_sm_cma_diff',
 'E_TM_TOV_PCT_sm_cma_diff',
 'TM_TOV_PCT_sm_cma_diff',
 'EFG_PCT_sm_cma_diff',
 'TS_PCT_sm_cma_diff',
 'USG_PCT_sm_cma_diff',
 'E_USG_PCT_sm_cma_diff',
 'E_PACE_sm_cma_diff',
 'PACE_sm_cma_diff',
 'PACE_PER40_sm_cma_diff',
 'POSS_sm_cma_diff',
 'PIE_sm_cma_diff',
 'duration_minutes_sm_cma_diff',
 'w_pct_sm_cma_diff',
 'min_sm_cma_diff',
 'fgm_sm_cma_diff',
 'fga_sm_cma_diff',
 'fg_pct_sm_cma_diff',
 'fg3m_sm_cma_diff',
 'fg3a_sm_cma_diff',
 'fg3_pct_sm_cma_diff',
 'ftm_sm_cma_diff',
 'fta_sm_cma_diff',
 'ft_pct_sm_cma_diff',
 'oreb_sm_cma_diff',
 'dreb_sm_cma_diff',
 'reb_sm_cma_diff',
 'ast_sm_cma_diff',
 'stl_sm_cma_diff',
 'blk_sm_cma_diff',
 'tov_sm_cma_diff',
 'pf_sm_cma_diff',
 'pts_sm_cma_diff',
 'spread_sm_cma_diff',
 'away_home_sm_cma_diff',
 'E_OFF_RATING_sm_cma_a',
 'OFF_RATING_sm_cma_a',
 'E_DEF_RATING_sm_cma_a',
 'DEF_RATING_sm_cma_a',
 'E_NET_RATING_sm_cma_a',
 'NET_RATING_sm_cma_a',
 'AST_PCT_sm_cma_a',
 'AST_TOV_sm_cma_a',
 'AST_RATIO_sm_cma_a',
 'OREB_PCT_sm_cma_a',
 'DREB_PCT_sm_cma_a',
 'REB_PCT_sm_cma_a',
 'E_TM_TOV_PCT_sm_cma_a',
 'TM_TOV_PCT_sm_cma_a',
 'EFG_PCT_sm_cma_a',
 'TS_PCT_sm_cma_a',
 'USG_PCT_sm_cma_a',
 'E_USG_PCT_sm_cma_a',
 'E_PACE_sm_cma_a',
 'PACE_sm_cma_a',
 'PACE_PER40_sm_cma_a',
 'POSS_sm_cma_a',
 'PIE_sm_cma_a',
 'duration_minutes_sm_cma_a',
 'w_pct_sm_cma_a',
 'min_sm_cma_a',
 'fgm_sm_cma_a',
 'fga_sm_cma_a',
 'fg_pct_sm_cma_a',
 'fg3m_sm_cma_a',
 'fg3a_sm_cma_a',
 'fg3_pct_sm_cma_a',
 'ftm_sm_cma_a',
 'fta_sm_cma_a',
 'ft_pct_sm_cma_a',
 'oreb_sm_cma_a',
 'dreb_sm_cma_a',
 'reb_sm_cma_a',
 'ast_sm_cma_a',
 'stl_sm_cma_a',
 'blk_sm_cma_a',
 'tov_sm_cma_a',
 'pf_sm_cma_a',
 'pts_sm_cma_a',
 'spread_sm_cma_a',
 'away_home_sm_cma_a',
 'E_OFF_RATING_sm_cma_b',
 'OFF_RATING_sm_cma_b',
 'E_DEF_RATING_sm_cma_b',
 'DEF_RATING_sm_cma_b',
 'E_NET_RATING_sm_cma_b',
 'NET_RATING_sm_cma_b',
 'AST_PCT_sm_cma_b',
 'AST_TOV_sm_cma_b',
 'AST_RATIO_sm_cma_b',
 'OREB_PCT_sm_cma_b',
 'DREB_PCT_sm_cma_b',
 'REB_PCT_sm_cma_b',
 'E_TM_TOV_PCT_sm_cma_b',
 'TM_TOV_PCT_sm_cma_b',
 'EFG_PCT_sm_cma_b',
 'TS_PCT_sm_cma_b',
 'USG_PCT_sm_cma_b',
 'E_USG_PCT_sm_cma_b',
 'E_PACE_sm_cma_b',
 'PACE_sm_cma_b',
 'PACE_PER40_sm_cma_b',
 'POSS_sm_cma_b',
 'PIE_sm_cma_b',
 'duration_minutes_sm_cma_b',
 'w_pct_sm_cma_b',
 'min_sm_cma_b',
 'fgm_sm_cma_b',
 'fga_sm_cma_b',
 'fg_pct_sm_cma_b',
 'fg3m_sm_cma_b',
 'fg3a_sm_cma_b',
 'fg3_pct_sm_cma_b',
 'ftm_sm_cma_b',
 'fta_sm_cma_b',
 'ft_pct_sm_cma_b',
 'oreb_sm_cma_b',
 'dreb_sm_cma_b',
 'reb_sm_cma_b',
 'ast_sm_cma_b',
 'stl_sm_cma_b',
 'blk_sm_cma_b',
 'tov_sm_cma_b',
 'pf_sm_cma_b',
 'pts_sm_cma_b',
 'spread_sm_cma_b',
 'away_home_sm_cma_b']

In [6]:
columns_names_list_temp = [k for k in columns_names_all_list if (not k in column_names_cma_list_pred)]
columns_names_list_temp

['game_id',
 'TEAM_NAME_a',
 'TEAM_ABBREVIATION_a',
 'TEAM_CITY_a',
 'MIN_a',
 'duration_a',
 'E_OFF_RATING_a',
 'OFF_RATING_a',
 'E_DEF_RATING_a',
 'DEF_RATING_a',
 'E_NET_RATING_a',
 'NET_RATING_a',
 'AST_PCT_a',
 'AST_TOV_a',
 'AST_RATIO_a',
 'OREB_PCT_a',
 'DREB_PCT_a',
 'REB_PCT_a',
 'E_TM_TOV_PCT_a',
 'TM_TOV_PCT_a',
 'EFG_PCT_a',
 'TS_PCT_a',
 'USG_PCT_a',
 'E_USG_PCT_a',
 'E_PACE_a',
 'PACE_a',
 'PACE_PER40_a',
 'POSS_a',
 'PIE_a',
 'duration_minutes_a',
 'team_id_a',
 'w_pct_a',
 'min_a',
 'fgm_a',
 'fga_a',
 'fg_pct_a',
 'fg3m_a',
 'fg3a_a',
 'fg3_pct_a',
 'ftm_a',
 'fta_a',
 'ft_pct_a',
 'oreb_a',
 'dreb_a',
 'reb_a',
 'ast_a',
 'stl_a',
 'blk_a',
 'tov_a',
 'pf_a',
 'pts_a',
 'wl_a',
 'spread_a',
 'away_home_a',
 'game_date',
 'matchup',
 'season_type',
 'season',
 'season_year',
 'a',
 'b',
 'TEAM_NAME_b',
 'TEAM_ABBREVIATION_b',
 'TEAM_CITY_b',
 'MIN_b',
 'duration_b',
 'E_OFF_RATING_b',
 'OFF_RATING_b',
 'E_DEF_RATING_b',
 'DEF_RATING_b',
 'E_NET_RATING_b',
 'NET_RATING_b',
 'AST_PCT_b',
 'AST_TOV_b',
 'AST_RATIO_b',
 'OREB_PCT_b',
 'DREB_PCT_b',
 'REB_PCT_b',
 'E_TM_TOV_PCT_b',
 'TM_TOV_PCT_b',
 'EFG_PCT_b',
 'TS_PCT_b',
 'USG_PCT_b',
 'E_USG_PCT_b',
 'E_PACE_b',
 'PACE_b',
 'PACE_PER40_b',
 'POSS_b',
 'PIE_b',
 'duration_minutes_b',
 'team_id_b',
 'w_pct_b',
 'min_b',
 'fgm_b',
 'fga_b',
 'fg_pct_b',
 'fg3m_b',
 'fg3a_b',
 'fg3_pct_b',
 'ftm_b',
 'fta_b',
 'ft_pct_b',
 'oreb_b',
 'dreb_b',
 'reb_b',
 'ast_b',
 'stl_b',
 'blk_b',
 'tov_b',
 'pf_b',
 'pts_b',
 'wl_b',
 'spread_b',
 'away_home_b']

In [7]:
df_number_temp = df.loc[:, columns_names_list_temp].select_dtypes('number')
p(df_number_temp)

(10266, 96)

,game_id,E_OFF_RATING_a,OFF_RATING_a,E_DEF_RATING_a,DEF_RATING_a,E_NET_RATING_a,NET_RATING_a,AST_PCT_a,AST_TOV_a,AST_RATIO_a,OREB_PCT_a,DREB_PCT_a,REB_PCT_a,E_TM_TOV_PCT_a,TM_TOV_PCT_a,EFG_PCT_a,TS_PCT_a,USG_PCT_a,E_USG_PCT_a,E_PACE_a,PACE_a,PACE_PER40_a,POSS_a,PIE_a,duration_minutes_a,team_id_a,w_pct_a,min_a,fgm_a,fga_a,fg_pct_a,fg3m_a,fg3a_a,fg3_pct_a,ftm_a,fta_a,ft_pct_a,oreb_a,dreb_a,reb_a,ast_a,stl_a,blk_a,tov_a,pf_a,pts_a,spread_a,away_home_a,season_year,E_OFF_RATING_b,OFF_RATING_b,E_DEF_RATING_b,DEF_RATING_b,E_NET_RATING_b,NET_RATING_b,AST_PCT_b,AST_TOV_b,AST_RATIO_b,OREB_PCT_b,DREB_PCT_b,REB_PCT_b,E_TM_TOV_PCT_b,TM_TOV_PCT_b,EFG_PCT_b,TS_PCT_b,USG_PCT_b,E_USG_PCT_b,E_PACE_b,PACE_b,PACE_PER40_b,POSS_b,PIE_b,duration_minutes_b,team_id_b,w_pct_b,min_b,fgm_b,fga_b,fg_pct_b,fg3m_b,fg3a_b,fg3_pct_b,ftm_b,fta_b,ft_pct_b,oreb_b,dreb_b,reb_b,ast_b,stl_b,blk_b,tov_b,pf_b,pts_b,spread_b,away_home_b
0,21000001,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.50,76.25,92,0.599,240.0,1610612738,1.000,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,-8,1,2010,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.50,76.25,91,0.401,240.0,1610612748,0.000,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,8,0
1,21000002,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.00,75.00,90,0.375,240.0,1610612756,0.000,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,14,0,2010,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.00,75.00,90,0.625,240.0,1610612757,1.000,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,-14,1
2,21000003,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.50,86.25,103,0.507,240.0,1610612745,0.000,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,2,0,2010,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.50,86.25,104,0.493,240.0,1610612747,1.000,240,40,96,0.417,9,21,0.429,23,28,0.821429,14,30,44,21,11,4,12,24,112,-2,1
3,21000009,110.1,112.6,111.8,114.7,-1.6,-2.1,0.512,1.69,15.9,0.320,0.691,0.514,12.343,12.6,0.516,0.561,1.0,0.199,105.00,102.50,85.42,103,0.482,240.0,1610612750,0.000,240,43,91,0.473,8,18,0.444,22,28,0.785714,11,35,46,22,5,8,13,32,116,1,1,2010,111.8,114.7,110.1,112.6,1.6,2.1,0.641,1.92,17.4,0.309,0.680,0.486,12.419,12.7,0.482,0.554,1.0,0.199,105.00,102.50,85.42,102,0.518,240.0,1610612758,1.000,240,39,85,0.459,4,11,0.364,35,47,0.744681,14,31,45,25,8,4,13,24,117,-1,0
4,21000006,103.6,103.2,89.8,94.6,13.7,8.6,0.455,0.94,13.2,0.220,0.708,0.483,17.087,17.0,0.536,0.587,1.0,0.201,95.24,93.00,77.50,94,0.550,240.0,1610612748,0.500,240,33,69,0.478,8,16,0.500,23,31,0.741935,5,32,37,15,8,6,16,18,97,-10,0,2010,89.8,94.6,103.6,103.2,-13.7,-8.6,0.667,1.26,18.3,0.292,0.780,0.517,19.620,20.7,0.476,0.495,1.0,0.193,95.24,93.00,77.50,92,0.450,240.0,1610612755,0.000,240,36,83,0.434,7,18,0.389,8,11,0.727273,10,28,38,24,10,4,16,22,87,10,1
10261,41700317,109.6,111.0,97.2,101.1,12.4,9.9,0.641,1.47,19.5,0.341,0.633,0.510,18.446,18.7,0.588,0.586,1.0,0.200,93.42,91.00,75.83,91,0.568,240.0,1610612744,0.571,240,39,80,0.488,16,39,0.410,7,14,0.500000,11,31,42,25,9,7,16,22,101,-9,0,2017,97.2,101.1,109.6,111.0,-12.4,-9.9,0.472,1.42,13.2,0.367,0.659,0.490,12.674,13.2,0.439,0.461,1.0,0.201,93.42,91.00,75.83,91,0.432,240.0,1610612745,0.429,240,36,90,0.400,7,44,0.159,13,22,0.590909,17,27,44,17,13,3,12,17,92,9,1
10262,41700401,112.1,112.9,120.6,125.3,-8.5,-12.4,0.409,1.50,13.0,0.404,0.822,0.588,11.802,11.9,0.495,0.524,1.0,0.197,92.59,90.57,75.47,101,0.406,265.0,1610612739,0.000,265,44,99,0.444,10,37,0.270,16,22,0.727273,19,34,53,18,5,3,11,18,114,10,0,2017,120.6,125.3,112.1,112.9,8.5,12.4,0.674,3.88,22.5,0.178,0.596,0.412,7.782,8.1,0.583,0.628,1.0,0.195,92.59,90.57,75.47,99,0.594,265.0,1610612744,1.000,265,46,90,0.511,13,36,0.361,19,20,0.950000,4,34,38,31,10,6,7,18,124,-10,1
10263,41700402,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.50,79.58,97,0.435,240.0,1610612739,0.000,240,37,90,0.411,9,27,0.333,20,26,0.769231,16,26,42,25,9,4,10,15,103,19,0,2017,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.50,79.58,94,0.565,240.0,1610612744,1.000,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,-19,1
10264,41700403,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.50,78.75,95,0.431,240.0,1610612739,0.000,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,8,1,2017,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.50,78.75,94,0.569,240.0,1610612744,1.000,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,-8,0
10265,41700404,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.50,75.42,90,0.328,240.0,1610612739,0.000,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,23,1,2017,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.50,75.42,91,0.672,240.0,1610612744,1.000,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,-23,0

In [8]:
column_names_df_number_temp_list = list(df_number_temp.columns)
pl(column_names_df_number_temp_list)

96

['game_id',
 'E_OFF_RATING_a',
 'OFF_RATING_a',
 'E_DEF_RATING_a',
 'DEF_RATING_a',
 'E_NET_RATING_a',
 'NET_RATING_a',
 'AST_PCT_a',
 'AST_TOV_a',
 'AST_RATIO_a',
 'OREB_PCT_a',
 'DREB_PCT_a',
 'REB_PCT_a',
 'E_TM_TOV_PCT_a',
 'TM_TOV_PCT_a',
 'EFG_PCT_a',
 'TS_PCT_a',
 'USG_PCT_a',
 'E_USG_PCT_a',
 'E_PACE_a',
 'PACE_a',
 'PACE_PER40_a',
 'POSS_a',
 'PIE_a',
 'duration_minutes_a',
 'team_id_a',
 'w_pct_a',
 'min_a',
 'fgm_a',
 'fga_a',
 'fg_pct_a',
 'fg3m_a',
 'fg3a_a',
 'fg3_pct_a',
 'ftm_a',
 'fta_a',
 'ft_pct_a',
 'oreb_a',
 'dreb_a',
 'reb_a',
 'ast_a',
 'stl_a',
 'blk_a',
 'tov_a',
 'pf_a',
 'pts_a',
 'spread_a',
 'away_home_a',
 'season_year',
 'E_OFF_RATING_b',
 'OFF_RATING_b',
 'E_DEF_RATING_b',
 'DEF_RATING_b',
 'E_NET_RATING_b',
 'NET_RATING_b',
 'AST_PCT_b',
 'AST_TOV_b',
 'AST_RATIO_b',
 'OREB_PCT_b',
 'DREB_PCT_b',
 'REB_PCT_b',
 'E_TM_TOV_PCT_b',
 'TM_TOV_PCT_b',
 'EFG_PCT_b',
 'TS_PCT_b',
 'USG_PCT_b',
 'E_USG_PCT_b',
 'E_PACE_b',
 'PACE_b',
 'PACE_PER40_b',
 'POSS_b',
 'PIE_b',
 'duration_minutes_b',
 'team_id_b',
 'w_pct_b',
 'min_b',
 'fgm_b',
 'fga_b',
 'fg_pct_b',
 'fg3m_b',
 'fg3a_b',
 'fg3_pct_b',
 'ftm_b',
 'fta_b',
 'ft_pct_b',
 'oreb_b',
 'dreb_b',
 'reb_b',
 'ast_b',
 'stl_b',
 'blk_b',
 'tov_b',
 'pf_b',
 'pts_b',
 'spread_b',
 'away_home_b']

In [9]:
column_names_remove_list = [k for k in column_names_df_number_temp_list if not k in ['game_id', 'team_id_a', 'team_id_b', 
                                                          'spread_a','spread_b','away_home_a', 'away_home_b',
                                                          'season_year']]
pl(column_names_remove_list)

88

['E_OFF_RATING_a',
 'OFF_RATING_a',
 'E_DEF_RATING_a',
 'DEF_RATING_a',
 'E_NET_RATING_a',
 'NET_RATING_a',
 'AST_PCT_a',
 'AST_TOV_a',
 'AST_RATIO_a',
 'OREB_PCT_a',
 'DREB_PCT_a',
 'REB_PCT_a',
 'E_TM_TOV_PCT_a',
 'TM_TOV_PCT_a',
 'EFG_PCT_a',
 'TS_PCT_a',
 'USG_PCT_a',
 'E_USG_PCT_a',
 'E_PACE_a',
 'PACE_a',
 'PACE_PER40_a',
 'POSS_a',
 'PIE_a',
 'duration_minutes_a',
 'w_pct_a',
 'min_a',
 'fgm_a',
 'fga_a',
 'fg_pct_a',
 'fg3m_a',
 'fg3a_a',
 'fg3_pct_a',
 'ftm_a',
 'fta_a',
 'ft_pct_a',
 'oreb_a',
 'dreb_a',
 'reb_a',
 'ast_a',
 'stl_a',
 'blk_a',
 'tov_a',
 'pf_a',
 'pts_a',
 'E_OFF_RATING_b',
 'OFF_RATING_b',
 'E_DEF_RATING_b',
 'DEF_RATING_b',
 'E_NET_RATING_b',
 'NET_RATING_b',
 'AST_PCT_b',
 'AST_TOV_b',
 'AST_RATIO_b',
 'OREB_PCT_b',
 'DREB_PCT_b',
 'REB_PCT_b',
 'E_TM_TOV_PCT_b',
 'TM_TOV_PCT_b',
 'EFG_PCT_b',
 'TS_PCT_b',
 'USG_PCT_b',
 'E_USG_PCT_b',
 'E_PACE_b',
 'PACE_b',
 'PACE_PER40_b',
 'POSS_b',
 'PIE_b',
 'duration_minutes_b',
 'w_pct_b',
 'min_b',
 'fgm_b',
 'fga_b',
 'fg_pct_b',
 'fg3m_b',
 'fg3a_b',
 'fg3_pct_b',
 'ftm_b',
 'fta_b',
 'ft_pct_b',
 'oreb_b',
 'dreb_b',
 'reb_b',
 'ast_b',
 'stl_b',
 'blk_b',
 'tov_b',
 'pf_b',
 'pts_b']

In [10]:
column_names_cleaning_list = [k for k in columns_names_all_list if not k in column_names_remove_list]
pl(column_names_cleaning_list)

302

['game_id',
 'TEAM_NAME_a',
 'TEAM_ABBREVIATION_a',
 'TEAM_CITY_a',
 'MIN_a',
 'duration_a',
 'team_id_a',
 'wl_a',
 'spread_a',
 'away_home_a',
 'game_date',
 'matchup',
 'season_type',
 'season',
 'season_year',
 'a',
 'b',
 'E_OFF_RATING_cma_a',
 'OFF_RATING_cma_a',
 'E_DEF_RATING_cma_a',
 'DEF_RATING_cma_a',
 'E_NET_RATING_cma_a',
 'NET_RATING_cma_a',
 'AST_PCT_cma_a',
 'AST_TOV_cma_a',
 'AST_RATIO_cma_a',
 'OREB_PCT_cma_a',
 'DREB_PCT_cma_a',
 'REB_PCT_cma_a',
 'E_TM_TOV_PCT_cma_a',
 'TM_TOV_PCT_cma_a',
 'EFG_PCT_cma_a',
 'TS_PCT_cma_a',
 'USG_PCT_cma_a',
 'E_USG_PCT_cma_a',
 'E_PACE_cma_a',
 'PACE_cma_a',
 'PACE_PER40_cma_a',
 'POSS_cma_a',
 'PIE_cma_a',
 'duration_minutes_cma_a',
 'w_pct_cma_a',
 'min_cma_a',
 'fgm_cma_a',
 'fga_cma_a',
 'fg_pct_cma_a',
 'fg3m_cma_a',
 'fg3a_cma_a',
 'fg3_pct_cma_a',
 'ftm_cma_a',
 'fta_cma_a',
 'ft_pct_cma_a',
 'oreb_cma_a',
 'dreb_cma_a',
 'reb_cma_a',
 'ast_cma_a',
 'stl_cma_a',
 'blk_cma_a',
 'tov_cma_a',
 'pf_cma_a',
 'pts_cma_a',
 'spread_cma_a',
 'away_home_cma_a',
 'TEAM_NAME_b',
 'TEAM_ABBREVIATION_b',
 'TEAM_CITY_b',
 'MIN_b',
 'duration_b',
 'team_id_b',
 'wl_b',
 'spread_b',
 'away_home_b',
 'E_OFF_RATING_cma_b',
 'OFF_RATING_cma_b',
 'E_DEF_RATING_cma_b',
 'DEF_RATING_cma_b',
 'E_NET_RATING_cma_b',
 'NET_RATING_cma_b',
 'AST_PCT_cma_b',
 'AST_TOV_cma_b',
 'AST_RATIO_cma_b',
 'OREB_PCT_cma_b',
 'DREB_PCT_cma_b',
 'REB_PCT_cma_b',
 'E_TM_TOV_PCT_cma_b',
 'TM_TOV_PCT_cma_b',
 'EFG_PCT_cma_b',
 'TS_PCT_cma_b',
 'USG_PCT_cma_b',
 'E_USG_PCT_cma_b',
 'E_PACE_cma_b',
 'PACE_cma_b',
 'PACE_PER40_cma_b',
 'POSS_cma_b',
 'PIE_cma_b',
 'duration_minutes_cma_b',
 'w_pct_cma_b',
 'min_cma_b',
 'fgm_cma_b',
 'fga_cma_b',
 'fg_pct_cma_b',
 'fg3m_cma_b',
 'fg3a_cma_b',
 'fg3_pct_cma_b',
 'ftm_cma_b',
 'fta_cma_b',
 'ft_pct_cma_b',
 'oreb_cma_b',
 'dreb_cma_b',
 'reb_cma_b',
 'ast_cma_b',
 'stl_cma_b',
 'blk_cma_b',
 'tov_cma_b',
 'pf_cma_b',
 'pts_cma_b',
 'spread_cma_b',
 'away_home_cma_b',
 'E_OFF_RATING_cma_diff',
 'OFF_RATING_cma_diff',
 'E_DEF_RATING_cma_diff',
 'DEF_RATING_cma_diff',
 'E_NET_RATING_cma_diff',
 'NET_RATING_cma_diff',
 'AST_PCT_cma_diff',
 'AST_TOV_cma_diff',
 'AST_RATIO_cma_diff',
 'OREB_PCT_cma_diff',
 'DREB_PCT_cma_diff',
 'REB_PCT_cma_diff',
 'E_TM_TOV_PCT_cma_diff',
 'TM_TOV_PCT_cma_diff',
 'EFG_PCT_cma_diff',
 'TS_PCT_cma_diff',
 'USG_PCT_cma_diff',
 'E_USG_PCT_cma_diff',
 'E_PACE_cma_diff',
 'PACE_cma_diff',
 'PACE_PER40_cma_diff',
 'POSS_cma_diff',
 'PIE_cma_diff',
 'duration_minutes_cma_diff',
 'w_pct_cma_diff',
 'min_cma_diff',
 'fgm_cma_diff',
 'fga_cma_diff',
 'fg_pct_cma_diff',
 'fg3m_cma_diff',
 'fg3a_cma_diff',
 'fg3_pct_cma_diff',
 'ftm_cma_diff',
 'fta_cma_diff',
 'ft_pct_cma_diff',
 'oreb_cma_diff',
 'dreb_cma_diff',
 'reb_cma_diff',
 'ast_cma_diff',
 'stl_cma_diff',
 'blk_cma_diff',
 'tov_cma_diff',
 'pf_cma_diff',
 'pts_cma_diff',
 'spread_cma_diff',
 'away_home_cma_diff',
 'E_OFF_RATING_sm_cma_diff',
 'OFF_RATING_sm_cma_diff',
 'E_DEF_RATING_sm_cma_diff',
 'DEF_RATING_sm_cma_diff',
 'E_NET_RATING_sm_cma_diff',
 'NET_RATING_sm_cma_diff',
 'AST_PCT_sm_cma_diff',
 'AST_TOV_sm_cma_diff',
 'AST_RATIO_sm_cma_diff',
 'OREB_PCT_sm_cma_diff',
 'DREB_PCT_sm_cma_diff',
 'REB_PCT_sm_cma_diff',
 'E_TM_TOV_PCT_sm_cma_diff',
 'TM_TOV_PCT_sm_cma_diff',
 'EFG_PCT_sm_cma_diff',
 'TS_PCT_sm_cma_diff',
 'USG_PCT_sm_cma_diff',
 'E_USG_PCT_sm_cma_diff',
 'E_PACE_sm_cma_diff',
 'PACE_sm_cma_diff',
 'PACE_PER40_sm_cma_diff',
 'POSS_sm_cma_diff',
 'PIE_sm_cma_diff',
 'duration_minutes_sm_cma_diff',
 'w_pct_sm_cma_diff',
 'min_sm_cma_diff',
 'fgm_sm_cma_diff',
 'fga_sm_cma_diff',
 'fg_pct_sm_cma_diff',
 'fg3m_sm_cma_diff',
 'fg3a_sm_cma_diff',
 'fg3_pct_sm_cma_diff',
 'ftm_sm_cma_diff',
 'fta_sm_cma_diff',
 'ft_pct_sm_cma_diff',
 'oreb_sm_cma_diff',
 'dreb_sm_cma_diff',
 'reb_sm_cma_diff',
 'ast_sm_cma_diff',
 'stl_sm_cma_diff',
 'blk_sm_cma_diff',
 'tov_sm_cma_diff',
 'pf_sm_cma_diff',
 'pts_sm_cma_diff',
 'spread_sm_cma_diff',
 'away_home_sm_cma_diff',
 'E_OFF_RATING_sm_cma_a',
 'OFF_RATING_sm_cma_a',
 'E_DEF_RATING_sm_cma_a',
 'DEF_RATING_sm_cma_a',
 'E_NET_RATING_sm_cma_a',
 'NET_RATING_sm_cma_a',
 'AST_PCT_sm_cma_a',
 'AST_TOV_sm_cma_a',
 'AST_RATIO_sm_cma_a',
 'OREB_PCT_sm_cma_a',
 'DREB_PCT_sm_cma_a',
 'REB_PCT_sm_cma_a',
 'E_TM_TOV_PCT_sm_cma_a',
 'TM_TOV_PCT_sm_cma_a',
 'EFG_PCT_sm_cma_a',
 'TS_PCT_sm_cma_a',
 'USG_PCT_sm_cma_a',
 'E_USG_PCT_sm_cma_a',
 'E_PACE_sm_cma_a',
 'PACE_sm_cma_a',
 'PACE_PER40_sm_cma_a',
 'POSS_sm_cma_a',
 'PIE_sm_cma_a',
 'duration_minutes_sm_cma_a',
 'w_pct_sm_cma_a',
 'min_sm_cma_a',
 'fgm_sm_cma_a',
 'fga_sm_cma_a',
 'fg_pct_sm_cma_a',
 'fg3m_sm_cma_a',
 'fg3a_sm_cma_a',
 'fg3_pct_sm_cma_a',
 'ftm_sm_cma_a',
 'fta_sm_cma_a',
 'ft_pct_sm_cma_a',
 'oreb_sm_cma_a',
 'dreb_sm_cma_a',
 'reb_sm_cma_a',
 'ast_sm_cma_a',
 'stl_sm_cma_a',
 'blk_sm_cma_a',
 'tov_sm_cma_a',
 'pf_sm_cma_a',
 'pts_sm_cma_a',
 'spread_sm_cma_a',
 'away_home_sm_cma_a',
 'E_OFF_RATING_sm_cma_b',
 'OFF_RATING_sm_cma_b',
 'E_DEF_RATING_sm_cma_b',
 'DEF_RATING_sm_cma_b',
 'E_NET_RATING_sm_cma_b',
 'NET_RATING_sm_cma_b',
 'AST_PCT_sm_cma_b',
 'AST_TOV_sm_cma_b',
 'AST_RATIO_sm_cma_b',
 'OREB_PCT_sm_cma_b',
 'DREB_PCT_sm_cma_b',
 'REB_PCT_sm_cma_b',
 'E_TM_TOV_PCT_sm_cma_b',
 'TM_TOV_PCT_sm_cma_b',
 'EFG_PCT_sm_cma_b',
 'TS_PCT_sm_cma_b',
 'USG_PCT_sm_cma_b',
 'E_USG_PCT_sm_cma_b',
 'E_PACE_sm_cma_b',
 'PACE_sm_cma_b',
 'PACE_PER40_sm_cma_b',
 'POSS_sm_cma_b',
 'PIE_sm_cma_b',
 'duration_minutes_sm_cma_b',
 'w_pct_sm_cma_b',
 'min_sm_cma_b',
 'fgm_sm_cma_b',
 'fga_sm_cma_b',
 'fg_pct_sm_cma_b',
 'fg3m_sm_cma_b',
 'fg3a_sm_cma_b',
 'fg3_pct_sm_cma_b',
 'ftm_sm_cma_b',
 'fta_sm_cma_b',
 'ft_pct_sm_cma_b',
 'oreb_sm_cma_b',
 'dreb_sm_cma_b',
 'reb_sm_cma_b',
 'ast_sm_cma_b',
 'stl_sm_cma_b',
 'blk_sm_cma_b',
 'tov_sm_cma_b',
 'pf_sm_cma_b',
 'pts_sm_cma_b',
 'spread_sm_cma_b',
 'away_home_sm_cma_b']

In [11]:
#not known prior to the start of the game
column_names_cleaning_list = [k for k in column_names_cleaning_list if
                              not k in ['duration_a', 'duration_b', 'MIN_a', 'MIN_b', 'wl_a',
                                        'wl_b', ]]
pl(column_names_cleaning_list)

296

['game_id',
 'TEAM_NAME_a',
 'TEAM_ABBREVIATION_a',
 'TEAM_CITY_a',
 'team_id_a',
 'spread_a',
 'away_home_a',
 'game_date',
 'matchup',
 'season_type',
 'season',
 'season_year',
 'a',
 'b',
 'E_OFF_RATING_cma_a',
 'OFF_RATING_cma_a',
 'E_DEF_RATING_cma_a',
 'DEF_RATING_cma_a',
 'E_NET_RATING_cma_a',
 'NET_RATING_cma_a',
 'AST_PCT_cma_a',
 'AST_TOV_cma_a',
 'AST_RATIO_cma_a',
 'OREB_PCT_cma_a',
 'DREB_PCT_cma_a',
 'REB_PCT_cma_a',
 'E_TM_TOV_PCT_cma_a',
 'TM_TOV_PCT_cma_a',
 'EFG_PCT_cma_a',
 'TS_PCT_cma_a',
 'USG_PCT_cma_a',
 'E_USG_PCT_cma_a',
 'E_PACE_cma_a',
 'PACE_cma_a',
 'PACE_PER40_cma_a',
 'POSS_cma_a',
 'PIE_cma_a',
 'duration_minutes_cma_a',
 'w_pct_cma_a',
 'min_cma_a',
 'fgm_cma_a',
 'fga_cma_a',
 'fg_pct_cma_a',
 'fg3m_cma_a',
 'fg3a_cma_a',
 'fg3_pct_cma_a',
 'ftm_cma_a',
 'fta_cma_a',
 'ft_pct_cma_a',
 'oreb_cma_a',
 'dreb_cma_a',
 'reb_cma_a',
 'ast_cma_a',
 'stl_cma_a',
 'blk_cma_a',
 'tov_cma_a',
 'pf_cma_a',
 'pts_cma_a',
 'spread_cma_a',
 'away_home_cma_a',
 'TEAM_NAME_b',
 'TEAM_ABBREVIATION_b',
 'TEAM_CITY_b',
 'team_id_b',
 'spread_b',
 'away_home_b',
 'E_OFF_RATING_cma_b',
 'OFF_RATING_cma_b',
 'E_DEF_RATING_cma_b',
 'DEF_RATING_cma_b',
 'E_NET_RATING_cma_b',
 'NET_RATING_cma_b',
 'AST_PCT_cma_b',
 'AST_TOV_cma_b',
 'AST_RATIO_cma_b',
 'OREB_PCT_cma_b',
 'DREB_PCT_cma_b',
 'REB_PCT_cma_b',
 'E_TM_TOV_PCT_cma_b',
 'TM_TOV_PCT_cma_b',
 'EFG_PCT_cma_b',
 'TS_PCT_cma_b',
 'USG_PCT_cma_b',
 'E_USG_PCT_cma_b',
 'E_PACE_cma_b',
 'PACE_cma_b',
 'PACE_PER40_cma_b',
 'POSS_cma_b',
 'PIE_cma_b',
 'duration_minutes_cma_b',
 'w_pct_cma_b',
 'min_cma_b',
 'fgm_cma_b',
 'fga_cma_b',
 'fg_pct_cma_b',
 'fg3m_cma_b',
 'fg3a_cma_b',
 'fg3_pct_cma_b',
 'ftm_cma_b',
 'fta_cma_b',
 'ft_pct_cma_b',
 'oreb_cma_b',
 'dreb_cma_b',
 'reb_cma_b',
 'ast_cma_b',
 'stl_cma_b',
 'blk_cma_b',
 'tov_cma_b',
 'pf_cma_b',
 'pts_cma_b',
 'spread_cma_b',
 'away_home_cma_b',
 'E_OFF_RATING_cma_diff',
 'OFF_RATING_cma_diff',
 'E_DEF_RATING_cma_diff',
 'DEF_RATING_cma_diff',
 'E_NET_RATING_cma_diff',
 'NET_RATING_cma_diff',
 'AST_PCT_cma_diff',
 'AST_TOV_cma_diff',
 'AST_RATIO_cma_diff',
 'OREB_PCT_cma_diff',
 'DREB_PCT_cma_diff',
 'REB_PCT_cma_diff',
 'E_TM_TOV_PCT_cma_diff',
 'TM_TOV_PCT_cma_diff',
 'EFG_PCT_cma_diff',
 'TS_PCT_cma_diff',
 'USG_PCT_cma_diff',
 'E_USG_PCT_cma_diff',
 'E_PACE_cma_diff',
 'PACE_cma_diff',
 'PACE_PER40_cma_diff',
 'POSS_cma_diff',
 'PIE_cma_diff',
 'duration_minutes_cma_diff',
 'w_pct_cma_diff',
 'min_cma_diff',
 'fgm_cma_diff',
 'fga_cma_diff',
 'fg_pct_cma_diff',
 'fg3m_cma_diff',
 'fg3a_cma_diff',
 'fg3_pct_cma_diff',
 'ftm_cma_diff',
 'fta_cma_diff',
 'ft_pct_cma_diff',
 'oreb_cma_diff',
 'dreb_cma_diff',
 'reb_cma_diff',
 'ast_cma_diff',
 'stl_cma_diff',
 'blk_cma_diff',
 'tov_cma_diff',
 'pf_cma_diff',
 'pts_cma_diff',
 'spread_cma_diff',
 'away_home_cma_diff',
 'E_OFF_RATING_sm_cma_diff',
 'OFF_RATING_sm_cma_diff',
 'E_DEF_RATING_sm_cma_diff',
 'DEF_RATING_sm_cma_diff',
 'E_NET_RATING_sm_cma_diff',
 'NET_RATING_sm_cma_diff',
 'AST_PCT_sm_cma_diff',
 'AST_TOV_sm_cma_diff',
 'AST_RATIO_sm_cma_diff',
 'OREB_PCT_sm_cma_diff',
 'DREB_PCT_sm_cma_diff',
 'REB_PCT_sm_cma_diff',
 'E_TM_TOV_PCT_sm_cma_diff',
 'TM_TOV_PCT_sm_cma_diff',
 'EFG_PCT_sm_cma_diff',
 'TS_PCT_sm_cma_diff',
 'USG_PCT_sm_cma_diff',
 'E_USG_PCT_sm_cma_diff',
 'E_PACE_sm_cma_diff',
 'PACE_sm_cma_diff',
 'PACE_PER40_sm_cma_diff',
 'POSS_sm_cma_diff',
 'PIE_sm_cma_diff',
 'duration_minutes_sm_cma_diff',
 'w_pct_sm_cma_diff',
 'min_sm_cma_diff',
 'fgm_sm_cma_diff',
 'fga_sm_cma_diff',
 'fg_pct_sm_cma_diff',
 'fg3m_sm_cma_diff',
 'fg3a_sm_cma_diff',
 'fg3_pct_sm_cma_diff',
 'ftm_sm_cma_diff',
 'fta_sm_cma_diff',
 'ft_pct_sm_cma_diff',
 'oreb_sm_cma_diff',
 'dreb_sm_cma_diff',
 'reb_sm_cma_diff',
 'ast_sm_cma_diff',
 'stl_sm_cma_diff',
 'blk_sm_cma_diff',
 'tov_sm_cma_diff',
 'pf_sm_cma_diff',
 'pts_sm_cma_diff',
 'spread_sm_cma_diff',
 'away_home_sm_cma_diff',
 'E_OFF_RATING_sm_cma_a',
 'OFF_RATING_sm_cma_a',
 'E_DEF_RATING_sm_cma_a',
 'DEF_RATING_sm_cma_a',
 'E_NET_RATING_sm_cma_a',
 'NET_RATING_sm_cma_a',
 'AST_PCT_sm_cma_a',
 'AST_TOV_sm_cma_a',
 'AST_RATIO_sm_cma_a',
 'OREB_PCT_sm_cma_a',
 'DREB_PCT_sm_cma_a',
 'REB_PCT_sm_cma_a',
 'E_TM_TOV_PCT_sm_cma_a',
 'TM_TOV_PCT_sm_cma_a',
 'EFG_PCT_sm_cma_a',
 'TS_PCT_sm_cma_a',
 'USG_PCT_sm_cma_a',
 'E_USG_PCT_sm_cma_a',
 'E_PACE_sm_cma_a',
 'PACE_sm_cma_a',
 'PACE_PER40_sm_cma_a',
 'POSS_sm_cma_a',
 'PIE_sm_cma_a',
 'duration_minutes_sm_cma_a',
 'w_pct_sm_cma_a',
 'min_sm_cma_a',
 'fgm_sm_cma_a',
 'fga_sm_cma_a',
 'fg_pct_sm_cma_a',
 'fg3m_sm_cma_a',
 'fg3a_sm_cma_a',
 'fg3_pct_sm_cma_a',
 'ftm_sm_cma_a',
 'fta_sm_cma_a',
 'ft_pct_sm_cma_a',
 'oreb_sm_cma_a',
 'dreb_sm_cma_a',
 'reb_sm_cma_a',
 'ast_sm_cma_a',
 'stl_sm_cma_a',
 'blk_sm_cma_a',
 'tov_sm_cma_a',
 'pf_sm_cma_a',
 'pts_sm_cma_a',
 'spread_sm_cma_a',
 'away_home_sm_cma_a',
 'E_OFF_RATING_sm_cma_b',
 'OFF_RATING_sm_cma_b',
 'E_DEF_RATING_sm_cma_b',
 'DEF_RATING_sm_cma_b',
 'E_NET_RATING_sm_cma_b',
 'NET_RATING_sm_cma_b',
 'AST_PCT_sm_cma_b',
 'AST_TOV_sm_cma_b',
 'AST_RATIO_sm_cma_b',
 'OREB_PCT_sm_cma_b',
 'DREB_PCT_sm_cma_b',
 'REB_PCT_sm_cma_b',
 'E_TM_TOV_PCT_sm_cma_b',
 'TM_TOV_PCT_sm_cma_b',
 'EFG_PCT_sm_cma_b',
 'TS_PCT_sm_cma_b',
 'USG_PCT_sm_cma_b',
 'E_USG_PCT_sm_cma_b',
 'E_PACE_sm_cma_b',
 'PACE_sm_cma_b',
 'PACE_PER40_sm_cma_b',
 'POSS_sm_cma_b',
 'PIE_sm_cma_b',
 'duration_minutes_sm_cma_b',
 'w_pct_sm_cma_b',
 'min_sm_cma_b',
 'fgm_sm_cma_b',
 'fga_sm_cma_b',
 'fg_pct_sm_cma_b',
 'fg3m_sm_cma_b',
 'fg3a_sm_cma_b',
 'fg3_pct_sm_cma_b',
 'ftm_sm_cma_b',
 'fta_sm_cma_b',
 'ft_pct_sm_cma_b',
 'oreb_sm_cma_b',
 'dreb_sm_cma_b',
 'reb_sm_cma_b',
 'ast_sm_cma_b',
 'stl_sm_cma_b',
 'blk_sm_cma_b',
 'tov_sm_cma_b',
 'pf_sm_cma_b',
 'pts_sm_cma_b',
 'spread_sm_cma_b',
 'away_home_sm_cma_b']

In [12]:
df_predictive = df.loc[:, column_names_cleaning_list]
p(df_predictive)

(10266, 296)

,game_id,TEAM_NAME_a,TEAM_ABBREVIATION_a,TEAM_CITY_a,team_id_a,spread_a,away_home_a,game_date,matchup,season_type,season,season_year,a,b,E_OFF_RATING_cma_a,OFF_RATING_cma_a,E_DEF_RATING_cma_a,DEF_RATING_cma_a,E_NET_RATING_cma_a,NET_RATING_cma_a,AST_PCT_cma_a,AST_TOV_cma_a,AST_RATIO_cma_a,OREB_PCT_cma_a,DREB_PCT_cma_a,REB_PCT_cma_a,E_TM_TOV_PCT_cma_a,TM_TOV_PCT_cma_a,EFG_PCT_cma_a,TS_PCT_cma_a,USG_PCT_cma_a,E_USG_PCT_cma_a,E_PACE_cma_a,PACE_cma_a,PACE_PER40_cma_a,POSS_cma_a,PIE_cma_a,duration_minutes_cma_a,w_pct_cma_a,min_cma_a,fgm_cma_a,fga_cma_a,fg_pct_cma_a,fg3m_cma_a,fg3a_cma_a,fg3_pct_cma_a,ftm_cma_a,fta_cma_a,ft_pct_cma_a,oreb_cma_a,dreb_cma_a,reb_cma_a,ast_cma_a,stl_cma_a,blk_cma_a,tov_cma_a,pf_cma_a,pts_cma_a,spread_cma_a,away_home_cma_a,TEAM_NAME_b,TEAM_ABBREVIATION_b,TEAM_CITY_b,team_id_b,spread_b,away_home_b,E_OFF_RATING_cma_b,OFF_RATING_cma_b,E_DEF_RATING_cma_b,DEF_RATING_cma_b,E_NET_RATING_cma_b,NET_RATING_cma_b,AST_PCT_cma_b,AST_TOV_cma_b,AST_RATIO_cma_b,OREB_PCT_cma_b,DREB_PCT_cma_b,REB_PCT_cma_b,E_TM_TOV_PCT_cma_b,TM_TOV_PCT_cma_b,EFG_PCT_cma_b,TS_PCT_cma_b,USG_PCT_cma_b,E_USG_PCT_cma_b,E_PACE_cma_b,PACE_cma_b,PACE_PER40_cma_b,POSS_cma_b,PIE_cma_b,duration_minutes_cma_b,w_pct_cma_b,min_cma_b,fgm_cma_b,fga_cma_b,fg_pct_cma_b,fg3m_cma_b,fg3a_cma_b,fg3_pct_cma_b,ftm_cma_b,fta_cma_b,ft_pct_cma_b,oreb_cma_b,dreb_cma_b,reb_cma_b,ast_cma_b,stl_cma_b,blk_cma_b,tov_cma_b,pf_cma_b,pts_cma_b,spread_cma_b,away_home_cma_b,E_OFF_RATING_cma_diff,OFF_RATING_cma_diff,E_DEF_RATING_cma_diff,DEF_RATING_cma_diff,E_NET_RATING_cma_diff,NET_RATING_cma_diff,AST_PCT_cma_diff,AST_TOV_cma_diff,AST_RATIO_cma_diff,OREB_PCT_cma_diff,DREB_PCT_cma_diff,REB_PCT_cma_diff,E_TM_TOV_PCT_cma_diff,TM_TOV_PCT_cma_diff,EFG_PCT_cma_diff,TS_PCT_cma_diff,USG_PCT_cma_diff,E_USG_PCT_cma_diff,E_PACE_cma_diff,PACE_cma_diff,PACE_PER40_cma_diff,POSS_cma_diff,PIE_cma_diff,duration_minutes_cma_diff,w_pct_cma_diff,min_cma_diff,fgm_cma_diff,fga_cma_diff,fg_pct_cma_diff,fg3m_cma_diff,fg3a_cma_diff,fg3_pct_cma_diff,ftm_cma_diff,fta_cma_diff,ft_pct_cma_diff,oreb_cma_diff,dreb_cma_diff,reb_cma_diff,ast_cma_diff,stl_cma_diff,blk_cma_diff,tov_cma_diff,pf_cma_diff,pts_cma_diff,spread_cma_diff,away_home_cma_diff,E_OFF_RATING_sm_cma_diff,OFF_RATING_sm_cma_diff,E_DEF_RATING_sm_cma_diff,DEF_RATING_sm_cma_diff,E_NET_RATING_sm_cma_diff,NET_RATING_sm_cma_diff,AST_PCT_sm_cma_diff,AST_TOV_sm_cma_diff,AST_RATIO_sm_cma_diff,OREB_PCT_sm_cma_diff,DREB_PCT_sm_cma_diff,REB_PCT_sm_cma_diff,E_TM_TOV_PCT_sm_cma_diff,TM_TOV_PCT_sm_cma_diff,EFG_PCT_sm_cma_diff,TS_PCT_sm_cma_diff,USG_PCT_sm_cma_diff,E_USG_PCT_sm_cma_diff,E_PACE_sm_cma_diff,PACE_sm_cma_diff,PACE_PER40_sm_cma_diff,POSS_sm_cma_diff,PIE_sm_cma_diff,duration_minutes_sm_cma_diff,w_pct_sm_cma_diff,min_sm_cma_diff,fgm_sm_cma_diff,fga_sm_cma_diff,fg_pct_sm_cma_diff,fg3m_sm_cma_diff,fg3a_sm_cma_diff,fg3_pct_sm_cma_diff,ftm_sm_cma_diff,fta_sm_cma_diff,ft_pct_sm_cma_diff,oreb_sm_cma_diff,dreb_sm_cma_diff,reb_sm_cma_diff,ast_sm_cma_diff,stl_sm_cma_diff,blk_sm_cma_diff,tov_sm_cma_diff,pf_sm_cma_diff,pts_sm_cma_diff,spread_sm_cma_diff,away_home_sm_cma_diff,E_OFF_RATING_sm_cma_a,OFF_RATING_sm_cma_a,E_DEF_RATING_sm_cma_a,DEF_RATING_sm_cma_a,E_NET_RATING_sm_cma_a,NET_RATING_sm_cma_a,AST_PCT_sm_cma_a,AST_TOV_sm_cma_a,AST_RATIO_sm_cma_a,OREB_PCT_sm_cma_a,DREB_PCT_sm_cma_a,REB_PCT_sm_cma_a,E_TM_TOV_PCT_sm_cma_a,TM_TOV_PCT_sm_cma_a,EFG_PCT_sm_cma_a,TS_PCT_sm_cma_a,USG_PCT_sm_cma_a,E_USG_PCT_sm_cma_a,E_PACE_sm_cma_a,PACE_sm_cma_a,PACE_PER40_sm_cma_a,POSS_sm_cma_a,PIE_sm_cma_a,duration_minutes_sm_cma_a,w_pct_sm_cma_a,min_sm_cma_a,fgm_sm_cma_a,fga_sm_cma_a,fg_pct_sm_cma_a,fg3m_sm_cma_a,fg3a_sm_cma_a,fg3_pct_sm_cma_a,ftm_sm_cma_a,fta_sm_cma_a,ft_pct_sm_cma_a,oreb_sm_cma_a,dreb_sm_cma_a,reb_sm_cma_a,ast_sm_cma_a,stl_sm_cma_a,blk_sm_cma_a,tov_sm_cma_a,pf_sm_cma_a,pts_sm_cma_a,spread_sm_cma_a,away_home_sm_cma_a,E_OFF_RATING_sm_cma_b,OFF_RATING_sm_cma_b,E_DEF_RATING_sm_cma_b,DEF_RATING_sm_cma_b,E_NET_RATING_sm_cma_b,NET_RATING_sm_cma_b,AST_PCT_sm_cma_b,AST_TOV_sm_cma_b,AST_RATIO_sm_cma_b,OREB_PCT_sm_cma_b,DREB_PCT_sm_cma_b,REB_PCT_sm_cma_b,E_TM_TOV_PCT_sm_cma_b,TM_TOV_PCT_sm_cma_b,EFG_PCT_sm_cma_b,TS_PCT_sm_cma_b,USG_PCT_sm_cma_b,E_USG_PCT_sm_cma_b,E_PACE_sm_cma_b,PACE_sm_cma_b,PACE_PER40_sm_cma_b,POSS_sm_cma_b,PIE_sm_cma_b,duration_minutes_sm_cma_b,w_pct_sm_cma_b,min_sm_cma_b,fgm_sm_cma_b,fga_sm_cma_b,fg_pct_sm_cma_b,fg3m_sm_cma_b,fg3a_sm_cma_b,fg3_pct_sm_cma_b,ftm_sm_cma_b,fta_sm_cma_b,ft_pct_sm_cma_b,oreb_sm_cma_b,dreb_sm_cma_b,reb_sm_cma_b,ast_sm_cma_b,stl_sm_cma_b,blk_sm_cma_b,tov_sm_cma_b,pf_sm_cma_b,pts_sm_cma_b,spread_sm_cma_b,away_home_sm_cma_b
0,21000001,Celtics,BOS,Boston,1610612738,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,Heat,MIA,Miami,1610612748,8,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,21000002,Suns,PHX,Phoenix,1610612756,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,Trail Blazers,POR,Portland,1610612757,-14,1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,21000003,Rockets,HOU,Houston,1610612745,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,HOU,LAL,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,Lakers,LAL,Los Angeles,1610612747,-2,1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,21000009,Timberwolves,MIN,Minnesota,1610612750,1,1,2010-10-27,MIN vs. SAC,Regular Season,2010-11,2010,MIN,SAC,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,Kings,SAC,Sacramento,1610612758,-1,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,21000006,Heat,MIA,Miami,1610612748,-10,0,2010-10-27,MIA vs. PHI,Regular Season,2010-11,2010,MIA,PHI,87.900000,87.900000,95.700000,95.700000,-7.700000,-7.700000,0.556000,0.880000,12.800000,0.250000,0.732000,0.472000,18.681000,18.700000,0.419000,0.471000,1.0,0.200000,91.500000,91.500000,76.250000,91.000000,0.401000,240.000000,0.000000,240.000000,27.000000,74.000000,0.365000,8.000000,20.000000,0.400000,18.000000,25.000000,0.720000,11.000000,28.000000,39.000000,15.000000,10.000000,6.000000,17.000000,21.000000,80.000000,8.000000,0.000000,76ers,PHI,Philadelphia,1610612755,10,1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,87.900000,87.900000,95.700000,95.700000,-7.700000,-7.700000,0.556000,0.880000,12.800000,0.250000,0.732000,0.472000,18.681000,18.700000,0.419000,0.471000,1.0,0.200000,91.500000,91.500000,76.250000,91.000000,0.401000,240.000000,0.000000,240.000000,27.000000,74.000000,0.365000,8.000000,20.000000,0.400000,18.000000,25.000000,0.720000,11.000000,28.000000,39.000000,15.000000,10.000000,6.000000,17.000000,21.000000,80.000000,8.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [13]:
datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)

datapath_df = os.path.join(datapath, '53Aprediction_stats_2010_2018.csv')
if not os.path.exists(datapath_df):
    df_predictive.to_csv(datapath_df, index=False)