In [1]:
#number of away games in coming window# (games#): future_away_count_game#

#number of home games in coming window# (games#): future_home_count_game#



#number of games in coming window# (day#): future_game_count_day#

In [2]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA
from sklearn.preprocessing import scale


pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

pd.set_option('display.max_colwidth', None)
pd.options.display.max_info_columns = 999

#return the first 5 and last 5 rows of this dataframe
def p(df_):
    if df_.shape[0] > 6:
        print(df_.shape)
        return pd.concat([df_.head(), df_.tail()])
    else:
        return df_

def rcp(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'processed_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'processed_data', file_), parse_dates=pd_)
    
def rcr(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'raw_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'raw_data', file_), parse_dates=pd_)
    
#sort dataframe by column
def s(df_, column_):
    return df_.sort_values(column_)

#reset index and sort dataframe by column
def sr(df_, column_):
    df_ = df_.sort_values(column_)
    return df_.reset_index(drop=True)

#print length of list
def pl(list_):
    print(len(list_))
    return list_

#print length of list
def pdc(dict_):
    print(len(dict_))
    return dict_

#import my functions
import my_functions as f



def feature_engineer(df_, group_by_columns_, column_features_, operators_, window_size_, shift_num_=1):
    
    '''
    example operators: 'max', 'min', 'count', 'median', 'mean'
    '''
    df_.groupby([group_by_columns_])\
           [column_features_]\
           .rolling(window_size_,1).agg([operators_])\
           .shift(shift_num_)

In [3]:
df = rcp('64_city_proper_metro_area_gdp_2010_2018.csv', ['game_date'])
df = df.sort_values(['game_date', 'game_id'], ascending=False)
p(df)

(20532, 72)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,latitude,longitude,game_latitude,game_longitude,travel_distance,game_time_zone,time_zone,time_zone_diff,time_zone_diff_abs,city_proper_metro_area,Country/Region,city_proper_metro_area_GDP_bil,city_proper_metro_area_GDP_bil1
20530,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0.0,0.0,Cleveland,United States,135,215.1
20531,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3.0,3.0,San Francisco,United States,995,631.0
20528,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0.0,0.0,Cleveland,United States,135,215.1
20529,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3.0,3.0,San Francisco,United States,995,631.0
20526,41700402,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.5,79.58,97,0.435,240.0,1610612739,0.0,240,37,90,0.411,9,27,0.333,20,26,0.769231,16,26,42,25,9,4,10,15,103,L,19,0,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,37.854666,-122.292136,2153.640745,America/Los_Angeles,America/New_York,-3.0,3.0,Cleveland,United States,135,215.1
5,21000003,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.5,86.25,104,0.493,240.0,1610612747,1.0,240,40,96,0.417,9,21,0.429,23,28,0.821429,14,30,44,21,11,4,12,24,112,W,-2,1,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,34.053691,-118.242766,34.053691,-118.242766,0.000000,America/Los_Angeles,America/Los_Angeles,0.0,0.0,Los Angeles,United States,"1,048","1,528.27"
2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,33.448437,-112.074142,45.520247,-122.674195,1005.606855,America/Los_Angeles,America/Phoenix,0.0,0.0,Phoenix,United States,255.211,607.1
3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,45.520247,-122.674195,45.520247,-122.674195,0.000000,America/Los_Angeles,America/Los_Angeles,0.0,0.0,Portland,United States,164.419,158.5
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,25.774173,-80.193620,42.360253,-71.058291,1257.755091,America/New_York,America/New_York,0.0,0.0,Miami,United States,377.5,262.7
1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,42.360253,-71.058291,42.360253,-71.058291,0.000000,America/New_York,America/New_York,0.0,0.0,Boston,United States,463.570,560.1

In [4]:
def get_future_game_count_percentage_away_home_both_day_window(df_, day_window_):
    
    len(day_window_) - 1
    
    df_ = df_.set_index('game_date')
    
    df1_ = df_.groupby(['team_id', 'season'])['away_home_']\
              .rolling(day_window_).sum().reset_index()\
              .rename(columns={'away_home_':'future_home_game_count_day' + day_window_[0:len(day_window_) - 1]})    
    
    df1_['future_home_game_count_day' \
         + day_window_[0:len(day_window_) - 1]] = \
    df1_['future_home_game_count_day' + day_window_[0:len(day_window_) - 1]]#.astype('int64')
    
    
    df_.away_home_ = abs(df_.away_home_ - 1)
    
    df0_ = df_.groupby(['team_id', 'season'])['away_home_']\
             .rolling(day_window_).sum().reset_index()\
             .rename(columns={'away_home_':'future_away_game_count_day' + day_window_[0:len(day_window_) - 1]})
    
    df0_['future_away_game_count_day' \
         + day_window_[0:len(day_window_) - 1]] = \
    df0_['future_away_game_count_day' + day_window_[0:len(day_window_) - 1]]#.astype('int64')
    
    
    df_.away_home_ = abs(df_.away_home_ - 1)
    
    df2_ = df_.groupby(['team_id', 'season'])['away_home_']\
              .rolling(day_window_).count().reset_index()\
              .rename(columns={'away_home_':'future_game_count_day' + day_window_[0:len(day_window_) - 1]})
    
    df2_['future_game_count_day' \
         + day_window_[0:len(day_window_) - 1]] = \
    df2_['future_game_count_day' + day_window_[0:len(day_window_) - 1]]#.astype('int64')
    
    
    column_names_common_list01_ = [k for k in df0_.columns if k in df1_.columns]
    
    df01_ = pd.merge(df0_, df1_, on=column_names_common_list01_)
    
    column_names_common_list012_ = [k for k in df01_.columns if k in df2_.columns]
    
    df012_ = pd.merge(df01_, df2_, on=column_names_common_list012_)
    
    column_names_common_list012_ = [k for k in df01_.columns if k in df2_.columns]

    df012_['future_away_game_percent_day' \
         + day_window_[0:len(day_window_) - 1]] = \
    df012_['future_away_game_count_day' + day_window_[0:len(day_window_) - 1]] /\
    df012_['future_game_count_day' + day_window_[0:len(day_window_) - 1]].values
    
    
    df012_['future_home_game_percent_day' \
         + day_window_[0:len(day_window_) - 1]] = \
    df012_['future_home_game_count_day' + day_window_[0:len(day_window_) - 1]] /\
    df012_['future_game_count_day' + day_window_[0:len(day_window_) - 1]].values
    
    df_ = pd.merge(df_, df012_, on=['team_id', 'season', 'game_date'])
    
    
    return df_

In [5]:
day_windows = [2, 5, 8, 12, 999]
day_windows

[2, 5, 8, 12, 999]

In [6]:
for i in day_windows:
    df = get_future_game_count_percentage_away_home_both_day_window(df, str(i) + 'D')

In [7]:
p(df)

(20532, 97)

,game_id,TEAM_NAME,game_date,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,matchup,season_type,season,season_year,latitude,longitude,game_latitude,game_longitude,travel_distance,game_time_zone,time_zone,time_zone_diff,time_zone_diff_abs,city_proper_metro_area,Country/Region,city_proper_metro_area_GDP_bil,city_proper_metro_area_GDP_bil1,future_away_game_count_day2,future_home_game_count_day2,future_game_count_day2,future_away_game_percent_day2,future_home_game_percent_day2,future_away_game_count_day5,future_home_game_count_day5,future_game_count_day5,future_away_game_percent_day5,future_home_game_percent_day5,future_away_game_count_day8,future_home_game_count_day8,future_game_count_day8,future_away_game_percent_day8,future_home_game_percent_day8,future_away_game_count_day12,future_home_game_count_day12,future_game_count_day12,future_away_game_percent_day12,future_home_game_percent_day12,future_away_game_count_day999,future_home_game_count_day999,future_game_count_day999,future_away_game_percent_day999,future_home_game_percent_day999
0,41700404,Cavaliers,2018-06-08,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0.0,0.0,Cleveland,United States,135,215.1,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000
1,41700404,Warriors,2018-06-08,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3.0,3.0,San Francisco,United States,995,631.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.000000,0.000000
2,41700403,Cavaliers,2018-06-06,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0.0,0.0,Cleveland,United States,135,215.1,0.0,1.0,1.0,0.0,1.0,0.0,2.0,2.0,0.000000,1.000000,0.0,2.0,2.0,0.000000,1.000000,0.0,2.0,2.0,0.000000,1.000000,0.0,2.0,2.0,0.000000,1.000000
3,41700403,Warriors,2018-06-06,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3.0,3.0,San Francisco,United States,995,631.0,1.0,0.0,1.0,1.0,0.0,2.0,0.0,2.0,1.000000,0.000000,2.0,0.0,2.0,1.000000,0.000000,2.0,0.0,2.0,1.000000,0.000000,2.0,0.0,2.0,1.000000,0.000000
4,41700402,Cavaliers,2018-06-03,CLE,Cleveland,240:00,0 days 04:00:00,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.5,79.58,97,0.435,240.0,1610612739,0.0,240,37,90,0.411,9,27,0.333,20,26,0.769231,16,26,42,25,9,4,10,15,103,L,19,0,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,37.854666,-122.292136,2153.640745,America/Los_Angeles,America/New_York,-3.0,3.0,Cleveland,United States,135,215.1,1.0,0.0,1.0,1.0,0.0,1.0,1.0,2.0,0.500000,0.500000,1.0,2.0,3.0,0.333333,0.666667,1.0,2.0,3.0,0.333333,0.666667,1.0,2.0,3.0,0.333333,0.666667
20527,21000003,Lakers,2010-10-26,LAL,Los Angeles,240:00,0 days 04:00:00,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.5,86.25,104,0.493,240.0,1610612747,1.0,240,40,96,0.417,9,21,0.429,23,28,0.821429,14,30,44,21,11,4,12,24,112,W,-2,1,HOU vs. LAL,Regular Season,2010-11,2010,34.053691,-118.242766,34.053691,-118.242766,0.000000,America/Los_Angeles,America/Los_Angeles,0.0,0.0,Los Angeles,United States,"1,048","1,528.27",0.0,1.0,1.0,0.0,1.0,1.0,1.0,2.0,0.500000,0.500000,1.0,3.0,4.0,0.250000,0.750000,2.0,4.0,6.0,0.333333,0.666667,46.0,46.0,92.0,0.500000,0.500000
20528,21000002,Suns,2010-10-26,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,PHX vs. POR,Regular Season,2010-11,2010,33.448437,-112.074142,45.520247,-122.674195,1005.606855,America/Los_Angeles,America/Phoenix,0.0,0.0,Phoenix,United States,255.211,607.1,1.0,0.0,1.0,1.0,0.0,2.0,1.0,3.0,0.666667,0.333333,2.0,1.0,3.0,0.666667,0.333333,2.0,3.0,5.0,0.400000,0.600000,41.0,41.0,82.0,0.500000,0.500000
20529,21000002,Trail Blazers,2010-10-26,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,PHX vs. POR,Regular Season,2010-11,2010,45.520247,-122.674195,45.520247,-122.674195,0.000000,America/Los_Angeles,America/Los_Angeles,0.0,0.0,Portland,United States,164.419,158.5,1.0,1.0,2.0,0.5,0.5,2.0,1.0,3.0,0.666667,0.333333,4.0,1.0,5.0,0.800000,0.200000,4.0,3.0,7.0,0.571429,0.428571,44.0,44.0,88.0,0.500000,0.500000
20530,21000001,Heat,2010-10-26,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,BOS vs. MIA,Regular Season,2010-11,2010,25.774173,-80.193620,42.360253,-71.058291,1257.755091,America/New_York,America/New_York,0.0,0.0,Miami,United States,377.5,262.7,2.0,0.0,2.0,1.0,0.0,2.0,1.0,3.0,0.666667,0.333333,3.0,2.0,5.0,0.600000,0.400000,4.0,3.0,7.0,0.571429,0.428571,51.0,52.0,103.0,0.495146,0.504854
20531,21000001,Celtics,2010-10-26,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,BOS vs. MIA,Regular Season,2010-11,2010,42.360253,-71.058291,42.360253,-71.058291,0.000000,America/New_York,America/New_York,0.0,0.0,Boston,United States,463.570,560.1,1.0,1.0,2.0,0.5,0.5,1.0,2.0,3.0,0.333333,0.666667,2.0,2.0,4.0,0.500000,0.500000,2.0,4.0,6.0,0.333333,0.666667,46.0,45.0,91.0,0.505495,0.494505

In [8]:
df_sub = df[['team_id', 'TEAM_NAME', 'TEAM_ABBREVIATION', 
             'game_date', 'away_home_', 'future_away_game_count_day5',
             'future_home_game_count_day5', 'future_game_count_day5']]
p(df_sub)

(20532, 8)

,team_id,TEAM_NAME,TEAM_ABBREVIATION,game_date,away_home_,future_away_game_count_day5,future_home_game_count_day5,future_game_count_day5
0,1610612739,Cavaliers,CLE,2018-06-08,1,0.0,1.0,1.0
1,1610612744,Warriors,GSW,2018-06-08,0,1.0,0.0,1.0
2,1610612739,Cavaliers,CLE,2018-06-06,1,0.0,2.0,2.0
3,1610612744,Warriors,GSW,2018-06-06,0,2.0,0.0,2.0
4,1610612739,Cavaliers,CLE,2018-06-03,0,1.0,1.0,2.0
20527,1610612747,Lakers,LAL,2010-10-26,1,1.0,1.0,2.0
20528,1610612756,Suns,PHX,2010-10-26,0,2.0,1.0,3.0
20529,1610612757,Trail Blazers,POR,2010-10-26,1,2.0,1.0,3.0
20530,1610612748,Heat,MIA,2010-10-26,0,2.0,1.0,3.0
20531,1610612738,Celtics,BOS,2010-10-26,1,1.0,2.0,3.0

In [9]:
df_sub[df_sub.team_id == 1610612738]

,team_id,TEAM_NAME,TEAM_ABBREVIATION,game_date,away_home_,future_away_game_count_day5,future_home_game_count_day5,future_game_count_day5
10,1610612738,Celtics,BOS,2018-05-27,1,0.0,1.0,1.0
14,1610612738,Celtics,BOS,2018-05-25,0,1.0,1.0,2.0
18,1610612738,Celtics,BOS,2018-05-23,1,1.0,2.0,3.0
22,1610612738,Celtics,BOS,2018-05-21,0,2.0,1.0,3.0
26,1610612738,Celtics,BOS,2018-05-19,0,2.0,1.0,3.0
30,1610612738,Celtics,BOS,2018-05-15,1,1.0,1.0,2.0
34,1610612738,Celtics,BOS,2018-05-13,1,0.0,2.0,2.0
36,1610612738,Celtics,BOS,2018-05-09,1,0.0,2.0,2.0
42,1610612738,Celtics,BOS,2018-05-07,0,1.0,1.0,2.0
50,1610612738,Celtics,BOS,2018-05-05,0,2.0,1.0,3.0
58,1610612738,Celtics,BOS,2018-05-03,1,2.0,1.0,3.0
68,1610612738,Celtics,BOS,2018-04-30,1,0.0,2.0,2.0
76,1610612738,Celtics,BOS,2018-04-28,1,0.0,2.0,2.0
84,1610612738,Celtics,BOS,2018-04-26,0,1.0,2.0,3.0
98,1610612738,Celtics,BOS,2018-04-24,1,1.0,2.0,3.0
108,1610612738,Celtics,BOS,2018-04-22,0,2.0,1.0,3.0
122,1610612738,Celtics,BOS,2018-04-20,0,2.0,1.0,3.0
140,1610612738,Celtics,BOS,2018-04-17,1,1.0,1.0,2.0
154,1610612738,Celtics,BOS,2018-04-15,1,0.0,2.0,2.0
186,1610612738,Celtics,BOS,2018-04-11,1,0.0,2.0,2.0
194,1610612738,Celtics,BOS,2018-04-10,0,1.0,1.0,2.0
220,1610612738,Celtics,BOS,2018-04-08,1,1.0,2.0,3.0
254,1610612738,Celtics,BOS,2018-04-06,1,1.0,2.0,3.0
282,1610612738,Celtics,BOS,2018-04-04,0,1.0,2.0,3.0
300,1610612738,Celtics,BOS,2018-04-03,0,2.0,1.0,3.0
344,1610612738,Celtics,BOS,2018-03-31,1,2.0,1.0,3.0
382,1610612738,Celtics,BOS,2018-03-28,0,1.0,1.0,2.0
410,1610612738,Celtics,BOS,2018-03-26,0,2.0,0.0,2.0
426,1610612738,Celtics,BOS,2018-03-25,0,3.0,0.0,3.0
452,1610612738,Celtics,BOS,2018-03-23,0,3.0,0.0,3.0
508,1610612738,Celtics,BOS,2018-03-20,1,1.0,1.0,2.0
532,1610612738,Celtics,BOS,2018-03-18,0,1.0,1.0,2.0
568,1610612738,Celtics,BOS,2018-03-16,0,2.0,1.0,3.0
592,1610612738,Celtics,BOS,2018-03-14,1,2.0,1.0,3.0
630,1610612738,Celtics,BOS,2018-03-11,1,0.0,2.0,2.0
678,1610612738,Celtics,BOS,2018-03-08,0,1.0,1.0,2.0
720,1610612738,Celtics,BOS,2018-03-05,0,2.0,0.0,2.0
748,1610612738,Celtics,BOS,2018-03-03,0,2.0,0.0,2.0
794,1610612738,Celtics,BOS,2018-02-28,1,1.0,1.0,2.0
830,1610612738,Celtics,BOS,2018-02-26,1,0.0,2.0,2.0
854,1610612738,Celtics,BOS,2018-02-24,0,1.0,2.0,3.0
880,1610612738,Celtics,BOS,2018-02-23,0,2.0,1.0,3.0
910,1610612738,Celtics,BOS,2018-02-14,1,0.0,1.0,1.0
956,1610612738,Celtics,BOS,2018-02-11,1,0.0,2.0,2.0
986,1610612738,Celtics,BOS,2018-02-09,1,0.0,2.0,2.0
1000,1610612738,Celtics,BOS,2018-02-08,0,1.0,2.0,3.0
1028,1610612738,Celtics,BOS,2018-02-06,0,2.0,1.0,3.0
1056,1610612738,Celtics,BOS,2018-02-04,1,2.0,1.0,3.0
1090,1610612738,Celtics,BOS,2018-02-02,1,1.0,2.0,3.0
1108,1610612738,Celtics,BOS,2018-01-31,1,0.0,3.0,3.0
1138,1610612738,Celtics,BOS,2018-01-29,0,1.0,2.0,3.0
1168,1610612738,Celtics,BOS,2018-01-27,0,2.0,1.0,3.0
1206,1610612738,Celtics,BOS,2018-01-24,0,2.0,0.0,2.0
1224,1610612738,Celtics,BOS,2018-01-23,0,3.0,0.0,3.0
1258,1610612738,Celtics,BOS,2018-01-21,1,2.0,1.0,3.0
1298,1610612738,Celtics,BOS,2018-01-18,1,0.0,2.0,2.0
1324,1610612738,Celtics,BOS,2018-01-16,1,0.0,2.0,2.0
1396,1610612738,Celtics,BOS,2018-01-11,0,1.0,0.0,1.0
1466,1610612738,Celtics,BOS,2018-01-06,0,1.0,0.0,1.0
1484,1610612738,Celtics,BOS,2018-01-05,1,1.0,1.0,2.0
1506,1610612738,Celtics,BOS,2018-01-03,1,1.0,2.0,3.0
1546,1610612738,Celtics,BOS,2017-12-31,1,0.0,2.0,2.0
1590,1610612738,Celtics,BOS,2017-12-28,1,0.0,2.0,2.0
1612,1610612738,Celtics,BOS,2017-12-27,0,1.0,2.0,3.0
1634,1610612738,Celtics,BOS,2017-12-25,1,1.0,2.0,3.0
1654,1610612738,Celtics,BOS,2017-12-23,1,1.0,2.0,3.0
1688,1610612738,Celtics,BOS,2017-12-21,0,1.0,2.0,3.0
1713,1610612738,Celtics,BOS,2017-12-20,1,1.0,2.0,3.0
1740,1610612738,Celtics,BOS,2017-12-18,0,2.0,1.0,3.0
1752,1610612738,Celtics,BOS,2017-12-16,0,2.0,1.0,3.0
1778,1610612738,Celtics,BOS,2017-12-15,1,2.0,1.0,3.0
1810,1610612738,Celtics,BOS,2017-12-13,1,1.0,2.0,3.0
1842,1610612738,Celtics,BOS,2017-12-11,0,1.0,2.0,3.0
1852,1610612738,Celtics,BOS,2017-12-10,0,2.0,1.0,3.0
1876,1610612738,Celtics,BOS,2017-12-08,0,3.0,0.0,3.0
1912,1610612738,Celtics,BOS,2017-12-06,1,2.0,1.0,3.0
1938,1610612738,Celtics,BOS,2017-12-04,1,1.0,2.0,3.0
1972,1610612738,Celtics,BOS,2017-12-02,1,0.0,3.0,3.0
1996,1610612738,Celtics,BOS,2017-11-30,1,0.0,3.0,3.0
2040,1610612738,Celtics,BOS,2017-11-27,1,0.0,2.0,2.0
2062,1610612738,Celtics,BOS,2017-11-25,0,1.0,1.0,2.0
2086,1610612738,Celtics,BOS,2017-11-24,1,1.0,2.0,3.0
2111,1610612738,Celtics,BOS,2017-11-22,0,2.0,1.0,3.0
2126,1610612738,Celtics,BOS,2017-11-20,0,2.0,1.0,3.0
2164,1610612738,Celtics,BOS,2017-11-18,0,3.0,0.0,3.0
2194,1610612738,Celtics,BOS,2017-11-16,1,2.0,1.0,3.0
2222,1610612738,Celtics,BOS,2017-11-14,0,2.0,1.0,3.0
2248,1610612738,Celtics,BOS,2017-11-12,1,1.0,2.0,3.0
2284,1610612738,Celtics,BOS,2017-11-10,1,1.0,2.0,3.0
2302,1610612738,Celtics,BOS,2017-11-08,1,0.0,3.0,3.0
2332,1610612738,Celtics,BOS,2017-11-06,0,1.0,2.0,3.0
2348,1610612738,Celtics,BOS,2017-11-05,0,2.0,1.0,3.0
2366,1610612738,Celtics,BOS,2017-11-03,0,3.0,0.0,3.0
2406,1610612738,Celtics,BOS,2017-11-01,1,2.0,1.0,3.0
2440,1610612738,Celtics,BOS,2017-10-30,1,1.0,2.0,3.0
2469,1610612738,Celtics,BOS,2017-10-28,0,1.0,2.0,3.0
2490,1610612738,Celtics,BOS,2017-10-26,0,2.0,1.0,3.0
2522,1610612738,Celtics,BOS,2017-10-24,1,2.0,1.0,3.0
2586,1610612738,Celtics,BOS,2017-10-20,0,1.0,1.0,2.0
2610,1610612738,Celtics,BOS,2017-10-18,1,1.0,1.0,2.0
2622,1610612738,Celtics,BOS,2017-10-17,0,2.0,1.0,3.0
2634,1610612738,Celtics,BOS,2017-05-25,1,0.0,1.0,1.0
2636,1610612738,Celtics,BOS,2017-05-23,0,1.0,1.0,2.0
2640,1610612738,Celtics,BOS,2017-05-21,0,2.0,1.0,3.0
2644,1610612738,Celtics,BOS,2017-05-19,1,2.0,1.0,3.0
2646,1610612738,Celtics,BOS,2017-05-17,1,1.0,2.0,3.0
2650,1610612738,Celtics,BOS,2017-05-15,1,0.0,3.0,3.0
2654,1610612738,Celtics,BOS,2017-05-12,0,1.0,1.0,2.0
2658,1610612738,Celtics,BOS,2017-05-10,1,1.0,1.0,2.0
2668,1610612738,Celtics,BOS,2017-05-07,0,1.0,1.0,2.0
2678,1610612738,Celtics,BOS,2017-05-04,0,2.0,0.0,2.0
2686,1610612738,Celtics,BOS,2017-05-02,1,1.0,1.0,2.0
2692,1610612738,Celtics,BOS,2017-04-30,1,1.0,2.0,3.0
2700,1610612738,Celtics,BOS,2017-04-28,0,1.0,2.0,3.0
2708,1610612738,Celtics,BOS,2017-04-26,1,1.0,2.0,3.0
2728,1610612738,Celtics,BOS,2017-04-23,0,1.0,1.0,2.0
2742,1610612738,Celtics,BOS,2017-04-21,0,2.0,0.0,2.0
2760,1610612738,Celtics,BOS,2017-04-18,1,1.0,1.0,2.0
2772,1610612738,Celtics,BOS,2017-04-16,1,0.0,2.0,2.0
2804,1610612738,Celtics,BOS,2017-04-12,1,0.0,2.0,2.0
2834,1610612738,Celtics,BOS,2017-04-10,1,0.0,2.0,2.0
2864,1610612738,Celtics,BOS,2017-04-08,0,1.0,2.0,3.0
2888,1610612738,Celtics,BOS,2017-04-06,0,2.0,1.0,3.0
2904,1610612738,Celtics,BOS,2017-04-05,1,2.0,1.0,3.0
2954,1610612738,Celtics,BOS,2017-04-02,0,2.0,1.0,3.0
2986,1610612738,Celtics,BOS,2017-03-31,1,1.0,1.0,2.0
3018,1610612738,Celtics,BOS,2017-03-29,1,1.0,2.0,3.0
3059,1610612738,Celtics,BOS,2017-03-26,1,0.0,2.0,2.0
3092,1610612738,Celtics,BOS,2017-03-24,1,0.0,2.0,2.0
3124,1610612738,Celtics,BOS,2017-03-22,1,0.0,3.0,3.0
3150,1610612738,Celtics,BOS,2017-03-20,1,0.0,3.0,3.0
3170,1610612738,Celtics,BOS,2017-03-19,0,1.0,2.0,3.0
3200,1610612738,Celtics,BOS,2017-03-17,0,2.0,1.0,3.0
3232,1610612738,Celtics,BOS,2017-03-15,1,2.0,1.0,3.0
3274,1610612738,Celtics,BOS,2017-03-12,1,0.0,2.0,2.0
3304,1610612738,Celtics,BOS,2017-03-10,0,1.0,1.0,2.0
3326,1610612738,Celtics,BOS,2017-03-08,0,2.0,1.0,3.0
3354,1610612738,Celtics,BOS,2017-03-06,0,3.0,0.0,3.0
3384,1610612738,Celtics,BOS,2017-03-05,0,3.0,0.0,3.0
3406,1610612738,Celtics,BOS,2017-03-03,0,3.0,0.0,3.0
3440,1610612738,Celtics,BOS,2017-03-01,1,2.0,1.0,3.0
3472,1610612738,Celtics,BOS,2017-02-27,1,1.0,2.0,3.0
3484,1610612738,Celtics,BOS,2017-02-26,0,1.0,2.0,3.0
3526,1610612738,Celtics,BOS,2017-02-24,0,2.0,1.0,3.0
3544,1610612738,Celtics,BOS,2017-02-16,0,1.0,0.0,1.0
3570,1610612738,Celtics,BOS,2017-02-15,1,1.0,1.0,2.0
3590,1610612738,Celtics,BOS,2017-02-13,0,2.0,1.0,3.0
3612,1610612738,Celtics,BOS,2017-02-11,0,2.0,1.0,3.0
3646,1610612738,Celtics,BOS,2017-02-09,0,3.0,0.0,3.0
3656,1610612738,Celtics,BOS,2017-02-08,0,3.0,0.0,3.0
3710,1610612738,Celtics,BOS,2017-02-05,1,2.0,1.0,3.0
3740,1610612738,Celtics,BOS,2017-02-03,1,0.0,2.0,2.0
3778,1610612738,Celtics,BOS,2017-02-01,1,0.0,3.0,3.0
3800,1610612738,Celtics,BOS,2017-01-30,1,0.0,3.0,3.0
3832,1610612738,Celtics,BOS,2017-01-28,0,1.0,2.0,3.0
3850,1610612738,Celtics,BOS,2017-01-27,1,1.0,2.0,3.0
3882,1610612738,Celtics,BOS,2017-01-25,1,1.0,2.0,3.0
3892,1610612738,Celtics,BOS,2017-01-24,0,2.0,2.0,4.0
3944,1610612738,Celtics,BOS,2017-01-21,1,1.0,2.0,3.0
3984,1610612738,Celtics,BOS,2017-01-18,1,0.0,2.0,2.0
4008,1610612738,Celtics,BOS,2017-01-16,1,0.0,2.0,2.0
4050,1610612738,Celtics,BOS,2017-01-13,0,1.0,1.0,2.0
4078,1610612738,Celtics,BOS,2017-01-11,1,1.0,1.0,2.0
4100,1610612738,Celtics,BOS,2017-01-10,0,2.0,1.0,3.0
4138,1610612738,Celtics,BOS,2017-01-07,1,1.0,2.0,3.0
4152,1610612738,Celtics,BOS,2017-01-06,1,1.0,2.0,3.0
4200,1610612738,Celtics,BOS,2017-01-03,1,0.0,3.0,3.0
4257,1610612738,Celtics,BOS,2016-12-30,1,0.0,2.0,2.0
4268,1610612738,Celtics,BOS,2016-12-29,0,1.0,1.0,2.0
4300,1610612738,Celtics,BOS,2016-12-27,1,1.0,2.0,3.0
4332,1610612738,Celtics,BOS,2016-12-25,0,2.0,1.0,3.0
4354,1610612738,Celtics,BOS,2016-12-23,1,1.0,2.0,3.0
4364,1610612738,Celtics,BOS,2016-12-22,0,2.0,1.0,3.0
4396,1610612738,Celtics,BOS,2016-12-20,0,2.0,1.0,3.0
4425,1610612738,Celtics,BOS,2016-12-18,0,3.0,0.0,3.0
4462,1610612738,Celtics,BOS,2016-12-16,1,2.0,1.0,3.0
4478,1610612738,Celtics,BOS,2016-12-14,0,2.0,1.0,3.0
4530,1610612738,Celtics,BOS,2016-12-11,0,2.0,0.0,2.0
4566,1610612738,Celtics,BOS,2016-12-09,1,1.0,1.0,2.0
4600,1610612738,Celtics,BOS,2016-12-07,0,2.0,1.0,3.0
4622,1610612738,Celtics,BOS,2016-12-05,0,2.0,1.0,3.0
4656,1610612738,Celtics,BOS,2016-12-03,0,3.0,0.0,3.0
4678,1610612738,Celtics,BOS,2016-12-02,1,2.0,1.0,3.0
4710,1610612738,Celtics,BOS,2016-11-30,1,1.0,2.0,3.0
4731,1610612738,Celtics,BOS,2016-11-28,0,1.0,2.0,3.0
4792,1610612738,Celtics,BOS,2016-11-25,1,1.0,1.0,2.0
4808,1610612738,Celtics,BOS,2016-11-23,0,1.0,1.0,2.0
4832,1610612738,Celtics,BOS,2016-11-21,0,2.0,1.0,3.0
4866,1610612738,Celtics,BOS,2016-11-19,0,3.0,0.0,3.0
4884,1610612738,Celtics,BOS,2016-11-18,1,2.0,1.0,3.0
4920,1610612738,Celtics,BOS,2016-11-16,1,1.0,2.0,3.0
4946,1610612738,Celtics,BOS,2016-11-14,0,1.0,2.0,3.0
4982,1610612738,Celtics,BOS,2016-11-12,0,2.0,1.0,3.0
4992,1610612738,Celtics,BOS,2016-11-11,1,2.0,1.0,3.0
5028,1610612738,Celtics,BOS,2016-11-09,0,2.0,1.0,3.0
5060,1610612738,Celtics,BOS,2016-11-06,1,1.0,1.0,2.0
5106,1610612738,Celtics,BOS,2016-11-03,0,1.0,1.0,2.0
5120,1610612738,Celtics,BOS,2016-11-02,1,1.0,2.0,3.0
5188,1610612738,Celtics,BOS,2016-10-29,0,1.0,1.0,2.0
5212,1610612738,Celtics,BOS,2016-10-27,0,2.0,0.0,2.0
5230,1610612738,Celtics,BOS,2016-10-26,1,2.0,1.0,3.0
5336,1610612738,Celtics,BOS,2016-04-28,1,0.0,1.0,1.0
5344,1610612738,Celtics,BOS,2016-04-26,0,1.0,1.0,2.0
5358,1610612738,Celtics,BOS,2016-04-24,1,1.0,2.0,3.0
5372,1610612738,Celtics,BOS,2016-04-22,1,1.0,2.0,3.0
5390,1610612738,Celtics,BOS,2016-04-19,0,1.0,1.0,2.0
5410,1610612738,Celtics,BOS,2016-04-16,0,2.0,0.0,2.0
5441,1610612738,Celtics,BOS,2016-04-13,1,1.0,1.0,2.0
5464,1610612738,Celtics,BOS,2016-04-11,1,0.0,2.0,2.0
5498,1610612738,Celtics,BOS,2016-04-09,0,1.0,2.0,3.0
5512,1610612738,Celtics,BOS,2016-04-08,1,1.0,2.0,3.0
5538,1610612738,Celtics,BOS,2016-04-06,1,1.0,2.0,3.0
5568,1610612738,Celtics,BOS,2016-04-03,0,1.0,1.0,2.0
5602,1610612738,Celtics,BOS,2016-04-01,0,2.0,0.0,2.0
5620,1610612738,Celtics,BOS,2016-03-31,0,3.0,0.0,3.0
5662,1610612738,Celtics,BOS,2016-03-28,0,3.0,0.0,3.0
5694,1610612738,Celtics,BOS,2016-03-26,0,2.0,0.0,2.0
5760,1610612738,Celtics,BOS,2016-03-23,1,1.0,1.0,2.0
5782,1610612738,Celtics,BOS,2016-03-21,1,0.0,2.0,2.0
5796,1610612738,Celtics,BOS,2016-03-20,0,1.0,2.0,3.0
5828,1610612738,Celtics,BOS,2016-03-18,0,2.0,1.0,3.0
5868,1610612738,Celtics,BOS,2016-03-16,1,2.0,1.0,3.0
5880,1610612738,Celtics,BOS,2016-03-15,0,2.0,1.0,3.0
5944,1610612738,Celtics,BOS,2016-03-11,1,1.0,1.0,2.0
5968,1610612738,Celtics,BOS,2016-03-09,1,0.0,2.0,2.0
6030,1610612738,Celtics,BOS,2016-03-05,0,1.0,1.0,2.0
6044,1610612738,Celtics,BOS,2016-03-04,1,1.0,1.0,2.0
6076,1610612738,Celtics,BOS,2016-03-02,1,1.0,2.0,3.0
6102,1610612738,Celtics,BOS,2016-02-29,1,0.0,3.0,3.0
6137,1610612738,Celtics,BOS,2016-02-27,1,0.0,3.0,3.0
6162,1610612738,Celtics,BOS,2016-02-25,1,0.0,3.0,3.0
6198,1610612738,Celtics,BOS,2016-02-22,0,1.0,1.0,2.0
6224,1610612738,Celtics,BOS,2016-02-21,0,2.0,1.0,3.0
6240,1610612738,Celtics,BOS,2016-02-19,0,3.0,0.0,3.0
6292,1610612738,Celtics,BOS,2016-02-10,1,0.0,1.0,1.0
6304,1610612738,Celtics,BOS,2016-02-09,0,1.0,1.0,2.0
6330,1610612738,Celtics,BOS,2016-02-07,1,1.0,2.0,3.0
6366,1610612738,Celtics,BOS,2016-02-05,0,2.0,1.0,3.0
6402,1610612738,Celtics,BOS,2016-02-03,1,1.0,2.0,3.0
6416,1610612738,Celtics,BOS,2016-02-02,0,2.0,1.0,3.0
6444,1610612738,Celtics,BOS,2016-01-31,0,2.0,1.0,3.0
6480,1610612738,Celtics,BOS,2016-01-29,1,2.0,1.0,3.0
6506,1610612738,Celtics,BOS,2016-01-27,1,1.0,2.0,3.0
6540,1610612738,Celtics,BOS,2016-01-25,0,1.0,2.0,3.0
6550,1610612738,Celtics,BOS,2016-01-24,0,2.0,1.0,3.0
6582,1610612738,Celtics,BOS,2016-01-22,1,2.0,1.0,3.0
6608,1610612738,Celtics,BOS,2016-01-20,0,2.0,1.0,3.0
6628,1610612738,Celtics,BOS,2016-01-18,0,2.0,1.0,3.0
6666,1610612738,Celtics,BOS,2016-01-16,0,3.0,0.0,3.0
6684,1610612738,Celtics,BOS,2016-01-15,1,2.0,1.0,3.0
6714,1610612738,Celtics,BOS,2016-01-13,1,1.0,2.0,3.0
6732,1610612738,Celtics,BOS,2016-01-12,0,2.0,2.0,4.0
6754,1610612738,Celtics,BOS,2016-01-10,0,2.0,1.0,3.0
6800,1610612738,Celtics,BOS,2016-01-07,0,2.0,0.0,2.0
6818,1610612738,Celtics,BOS,2016-01-06,1,2.0,1.0,3.0
6848,1610612738,Celtics,BOS,2016-01-04,0,2.0,1.0,3.0
6884,1610612738,Celtics,BOS,2016-01-02,1,1.0,2.0,3.0
6922,1610612738,Celtics,BOS,2015-12-30,1,0.0,2.0,2.0
6966,1610612738,Celtics,BOS,2015-12-27,1,0.0,2.0,2.0
6982,1610612738,Celtics,BOS,2015-12-26,0,1.0,2.0,3.0
7028,1610612738,Celtics,BOS,2015-12-23,0,2.0,1.0,3.0
7052,1610612738,Celtics,BOS,2015-12-21,1,1.0,1.0,2.0
7096,1610612738,Celtics,BOS,2015-12-18,1,0.0,2.0,2.0
7126,1610612738,Celtics,BOS,2015-12-16,0,1.0,1.0,2.0
7140,1610612738,Celtics,BOS,2015-12-15,1,1.0,2.0,3.0
7184,1610612738,Celtics,BOS,2015-12-12,0,2.0,1.0,3.0
7202,1610612738,Celtics,BOS,2015-12-11,1,1.0,2.0,3.0
7236,1610612738,Celtics,BOS,2015-12-09,1,1.0,2.0,3.0
7250,1610612738,Celtics,BOS,2015-12-07,0,1.0,2.0,3.0
7282,1610612738,Celtics,BOS,2015-12-05,0,2.0,1.0,3.0
7310,1610612738,Celtics,BOS,2015-12-03,0,3.0,0.0,3.0
7365,1610612738,Celtics,BOS,2015-11-30,0,2.0,0.0,2.0
7376,1610612738,Celtics,BOS,2015-11-29,0,3.0,0.0,3.0
7416,1610612738,Celtics,BOS,2015-11-27,1,2.0,1.0,3.0
7440,1610612738,Celtics,BOS,2015-11-25,1,1.0,2.0,3.0
7454,1610612738,Celtics,BOS,2015-11-24,0,1.0,2.0,3.0
7480,1610612738,Celtics,BOS,2015-11-22,0,2.0,1.0,3.0
7516,1610612738,Celtics,BOS,2015-11-20,1,2.0,1.0,3.0
7538,1610612738,Celtics,BOS,2015-11-18,1,1.0,2.0,3.0
7566,1610612738,Celtics,BOS,2015-11-16,0,1.0,2.0,3.0
7576,1610612738,Celtics,BOS,2015-11-15,0,2.0,1.0,3.0
7616,1610612738,Celtics,BOS,2015-11-13,1,2.0,1.0,3.0
7642,1610612738,Celtics,BOS,2015-11-11,1,1.0,2.0,3.0
7654,1610612738,Celtics,BOS,2015-11-10,0,1.0,2.0,3.0
7722,1610612738,Celtics,BOS,2015-11-06,1,1.0,1.0,2.0
7754,1610612738,Celtics,BOS,2015-11-04,0,1.0,1.0,2.0
7794,1610612738,Celtics,BOS,2015-11-01,1,1.0,1.0,2.0
7826,1610612738,Celtics,BOS,2015-10-30,1,0.0,2.0,2.0
7864,1610612738,Celtics,BOS,2015-10-28,1,0.0,3.0,3.0
7982,1610612738,Celtics,BOS,2015-04-26,1,0.0,1.0,1.0
8002,1610612738,Celtics,BOS,2015-04-23,1,0.0,2.0,2.0
8014,1610612738,Celtics,BOS,2015-04-21,0,1.0,1.0,2.0
8024,1610612738,Celtics,BOS,2015-04-19,0,2.0,1.0,3.0
8054,1610612738,Celtics,BOS,2015-04-15,0,2.0,0.0,2.0
8068,1610612738,Celtics,BOS,2015-04-14,1,1.0,1.0,2.0
8108,1610612738,Celtics,BOS,2015-04-12,1,1.0,2.0,3.0
8140,1610612738,Celtics,BOS,2015-04-10,0,1.0,2.0,3.0
8168,1610612738,Celtics,BOS,2015-04-08,0,2.0,1.0,3.0
8218,1610612738,Celtics,BOS,2015-04-04,0,2.0,0.0,2.0
8240,1610612738,Celtics,BOS,2015-04-03,1,1.0,1.0,2.0
8268,1610612738,Celtics,BOS,2015-04-01,1,1.0,2.0,3.0
8296,1610612738,Celtics,BOS,2015-03-30,0,1.0,2.0,3.0
8308,1610612738,Celtics,BOS,2015-03-29,1,1.0,2.0,3.0
8340,1610612738,Celtics,BOS,2015-03-27,0,2.0,1.0,3.0
8371,1610612738,Celtics,BOS,2015-03-25,1,1.0,2.0,3.0
8400,1610612738,Celtics,BOS,2015-03-23,0,2.0,1.0,3.0
8412,1610612738,Celtics,BOS,2015-03-22,1,1.0,2.0,3.0
8442,1610612738,Celtics,BOS,2015-03-20,0,2.0,1.0,3.0
8476,1610612738,Celtics,BOS,2015-03-18,0,2.0,1.0,3.0
8514,1610612738,Celtics,BOS,2015-03-16,1,2.0,1.0,3.0
8546,1610612738,Celtics,BOS,2015-03-14,0,2.0,1.0,3.0
8560,1610612738,Celtics,BOS,2015-03-13,1,1.0,2.0,3.0
8590,1610612738,Celtics,BOS,2015-03-11,1,1.0,2.0,3.0
8619,1610612738,Celtics,BOS,2015-03-09,0,1.0,2.0,3.0
8628,1610612738,Celtics,BOS,2015-03-08,0,2.0,1.0,3.0
8660,1610612738,Celtics,BOS,2015-03-06,0,3.0,0.0,3.0
8702,1610612738,Celtics,BOS,2015-03-04,1,2.0,1.0,3.0
8716,1610612738,Celtics,BOS,2015-03-03,0,2.0,1.0,3.0
8740,1610612738,Celtics,BOS,2015-03-01,1,1.0,2.0,3.0
8782,1610612738,Celtics,BOS,2015-02-27,1,1.0,2.0,3.0
8812,1610612738,Celtics,BOS,2015-02-25,1,0.0,3.0,3.0
8830,1610612738,Celtics,BOS,2015-02-23,0,1.0,2.0,3.0
8842,1610612738,Celtics,BOS,2015-02-22,0,2.0,1.0,3.0
8874,1610612738,Celtics,BOS,2015-02-20,0,3.0,0.0,3.0
8922,1610612738,Celtics,BOS,2015-02-11,1,0.0,1.0,1.0
8974,1610612738,Celtics,BOS,2015-02-07,0,1.0,1.0,2.0
9000,1610612738,Celtics,BOS,2015-02-06,1,1.0,1.0,2.0
9034,1610612738,Celtics,BOS,2015-02-04,1,1.0,2.0,3.0
9044,1610612738,Celtics,BOS,2015-02-03,0,2.0,2.0,4.0
9069,1610612738,Celtics,BOS,2015-02-01,1,1.0,2.0,3.0
9104,1610612738,Celtics,BOS,2015-01-30,1,1.0,2.0,3.0
9128,1610612738,Celtics,BOS,2015-01-28,0,1.0,2.0,3.0
9154,1610612738,Celtics,BOS,2015-01-26,0,2.0,1.0,3.0
9166,1610612738,Celtics,BOS,2015-01-25,0,3.0,0.0,3.0
9198,1610612738,Celtics,BOS,2015-01-23,0,3.0,0.0,3.0
9218,1610612738,Celtics,BOS,2015-01-22,0,4.0,0.0,4.0
9268,1610612738,Celtics,BOS,2015-01-19,0,3.0,0.0,3.0
9314,1610612738,Celtics,BOS,2015-01-16,1,1.0,1.0,2.0
9336,1610612738,Celtics,BOS,2015-01-14,1,0.0,2.0,2.0
9370,1610612738,Celtics,BOS,2015-01-12,1,0.0,3.0,3.0
9390,1610612738,Celtics,BOS,2015-01-10,0,1.0,2.0,3.0
9420,1610612738,Celtics,BOS,2015-01-09,0,2.0,1.0,3.0
9442,1610612738,Celtics,BOS,2015-01-07,0,3.0,0.0,3.0
9476,1610612738,Celtics,BOS,2015-01-05,1,2.0,1.0,3.0
9504,1610612738,Celtics,BOS,2015-01-03,0,2.0,1.0,3.0
9524,1610612738,Celtics,BOS,2015-01-02,1,1.0,2.0,3.0
9546,1610612738,Celtics,BOS,2014-12-31,1,1.0,2.0,3.0
9606,1610612738,Celtics,BOS,2014-12-27,0,1.0,1.0,2.0
9632,1610612738,Celtics,BOS,2014-12-26,1,1.0,1.0,2.0
9660,1610612738,Celtics,BOS,2014-12-23,0,2.0,1.0,3.0
9689,1610612738,Celtics,BOS,2014-12-21,0,2.0,0.0,2.0
9726,1610612738,Celtics,BOS,2014-12-19,1,2.0,1.0,3.0
9754,1610612738,Celtics,BOS,2014-12-17,1,1.0,2.0,3.0
9782,1610612738,Celtics,BOS,2014-12-15,0,1.0,2.0,3.0
9834,1610612738,Celtics,BOS,2014-12-12,1,1.0,1.0,2.0
9864,1610612738,Celtics,BOS,2014-12-10,0,1.0,1.0,2.0
9892,1610612738,Celtics,BOS,2014-12-08,0,2.0,1.0,3.0
9908,1610612738,Celtics,BOS,2014-12-07,1,2.0,1.0,3.0
9938,1610612738,Celtics,BOS,2014-12-05,1,1.0,2.0,3.0
9966,1610612738,Celtics,BOS,2014-12-03,1,0.0,3.0,3.0
9988,1610612738,Celtics,BOS,2014-12-02,0,1.0,2.0,3.0
10014,1610612738,Celtics,BOS,2014-11-30,1,1.0,2.0,3.0
10050,1610612738,Celtics,BOS,2014-11-28,1,1.0,2.0,3.0
10108,1610612738,Celtics,BOS,2014-11-23,1,0.0,1.0,1.0
10144,1610612738,Celtics,BOS,2014-11-21,0,1.0,1.0,2.0
10172,1610612738,Celtics,BOS,2014-11-19,0,2.0,1.0,3.0
10200,1610612738,Celtics,BOS,2014-11-17,1,2.0,1.0,3.0
10246,1610612738,Celtics,BOS,2014-11-14,1,0.0,2.0,2.0
10274,1610612738,Celtics,BOS,2014-11-12,1,0.0,2.0,2.0
10324,1610612738,Celtics,BOS,2014-11-08,0,1.0,1.0,2.0
10348,1610612738,Celtics,BOS,2014-11-07,1,1.0,1.0,2.0
10378,1610612738,Celtics,BOS,2014-11-05,1,1.0,2.0,3.0
10404,1610612738,Celtics,BOS,2014-11-03,0,1.0,2.0,3.0
10428,1610612738,Celtics,BOS,2014-11-01,0,2.0,1.0,3.0
10484,1610612738,Celtics,BOS,2014-10-29,1,1.0,1.0,2.0

In [10]:
'''from functools import reduce
data_frames = [df_game_count_day4, df_game_count_day7, df_game_count_day12, df_game_count_day999]

df_merged = reduce(lambda  left,right: pd.merge(left,right,on=column_names_common_list,
                                            how='outer'), data_frames)
p(df_merged)'''

"from functools import reduce\ndata_frames = [df_game_count_day4, df_game_count_day7, df_game_count_day12, df_game_count_day999]\n\ndf_merged = reduce(lambda  left,right: pd.merge(left,right,on=column_names_common_list,\n                                            how='outer'), data_frames)\np(df_merged)"

In [11]:
datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)

datapath_df = os.path.join(datapath, '66C_future_away_game_count_percentage_day2_5_8_12_999_future_home_game_count_percentage_day2_5_8_12_999_2010_2018.csv')
if not os.path.exists(datapath_df):
    df.to_csv(datapath_df, index=False)

In [12]:
df_66B_away_game_count_percentage_day2_5_8_12_999_home_game_count_percentage_day2_5_8_12_999_2010_2018_readback = rcp('66C_future_away_game_count_percentage_day2_5_8_12_999_future_home_game_count_percentage_day2_5_8_12_999_2010_2018.csv')
p(df_66B_away_game_count_percentage_day2_5_8_12_999_home_game_count_percentage_day2_5_8_12_999_2010_2018_readback)

(20532, 97)

,game_id,TEAM_NAME,game_date,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,matchup,season_type,season,season_year,latitude,longitude,game_latitude,game_longitude,travel_distance,game_time_zone,time_zone,time_zone_diff,time_zone_diff_abs,city_proper_metro_area,Country/Region,city_proper_metro_area_GDP_bil,city_proper_metro_area_GDP_bil1,future_away_game_count_day2,future_home_game_count_day2,future_game_count_day2,future_away_game_percent_day2,future_home_game_percent_day2,future_away_game_count_day5,future_home_game_count_day5,future_game_count_day5,future_away_game_percent_day5,future_home_game_percent_day5,future_away_game_count_day8,future_home_game_count_day8,future_game_count_day8,future_away_game_percent_day8,future_home_game_percent_day8,future_away_game_count_day12,future_home_game_count_day12,future_game_count_day12,future_away_game_percent_day12,future_home_game_percent_day12,future_away_game_count_day999,future_home_game_count_day999,future_game_count_day999,future_away_game_percent_day999,future_home_game_percent_day999
0,41700404,Cavaliers,2018-06-08,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0.0,0.0,Cleveland,United States,135,215.1,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000
1,41700404,Warriors,2018-06-08,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3.0,3.0,San Francisco,United States,995,631.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.000000,0.000000
2,41700403,Cavaliers,2018-06-06,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0.0,0.0,Cleveland,United States,135,215.1,0.0,1.0,1.0,0.0,1.0,0.0,2.0,2.0,0.000000,1.000000,0.0,2.0,2.0,0.000000,1.000000,0.0,2.0,2.0,0.000000,1.000000,0.0,2.0,2.0,0.000000,1.000000
3,41700403,Warriors,2018-06-06,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3.0,3.0,San Francisco,United States,995,631.0,1.0,0.0,1.0,1.0,0.0,2.0,0.0,2.0,1.000000,0.000000,2.0,0.0,2.0,1.000000,0.000000,2.0,0.0,2.0,1.000000,0.000000,2.0,0.0,2.0,1.000000,0.000000
4,41700402,Cavaliers,2018-06-03,CLE,Cleveland,240:00,0 days 04:00:00,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.5,79.58,97,0.435,240.0,1610612739,0.0,240,37,90,0.411,9,27,0.333,20,26,0.769231,16,26,42,25,9,4,10,15,103,L,19,0,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,37.854666,-122.292136,2153.640745,America/Los_Angeles,America/New_York,-3.0,3.0,Cleveland,United States,135,215.1,1.0,0.0,1.0,1.0,0.0,1.0,1.0,2.0,0.500000,0.500000,1.0,2.0,3.0,0.333333,0.666667,1.0,2.0,3.0,0.333333,0.666667,1.0,2.0,3.0,0.333333,0.666667
20527,21000003,Lakers,2010-10-26,LAL,Los Angeles,240:00,0 days 04:00:00,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.5,86.25,104,0.493,240.0,1610612747,1.0,240,40,96,0.417,9,21,0.429,23,28,0.821429,14,30,44,21,11,4,12,24,112,W,-2,1,HOU vs. LAL,Regular Season,2010-11,2010,34.053691,-118.242766,34.053691,-118.242766,0.000000,America/Los_Angeles,America/Los_Angeles,0.0,0.0,Los Angeles,United States,"1,048","1,528.27",0.0,1.0,1.0,0.0,1.0,1.0,1.0,2.0,0.500000,0.500000,1.0,3.0,4.0,0.250000,0.750000,2.0,4.0,6.0,0.333333,0.666667,46.0,46.0,92.0,0.500000,0.500000
20528,21000002,Suns,2010-10-26,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,PHX vs. POR,Regular Season,2010-11,2010,33.448437,-112.074142,45.520247,-122.674195,1005.606855,America/Los_Angeles,America/Phoenix,0.0,0.0,Phoenix,United States,255.211,607.1,1.0,0.0,1.0,1.0,0.0,2.0,1.0,3.0,0.666667,0.333333,2.0,1.0,3.0,0.666667,0.333333,2.0,3.0,5.0,0.400000,0.600000,41.0,41.0,82.0,0.500000,0.500000
20529,21000002,Trail Blazers,2010-10-26,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,PHX vs. POR,Regular Season,2010-11,2010,45.520247,-122.674195,45.520247,-122.674195,0.000000,America/Los_Angeles,America/Los_Angeles,0.0,0.0,Portland,United States,164.419,158.5,1.0,1.0,2.0,0.5,0.5,2.0,1.0,3.0,0.666667,0.333333,4.0,1.0,5.0,0.800000,0.200000,4.0,3.0,7.0,0.571429,0.428571,44.0,44.0,88.0,0.500000,0.500000
20530,21000001,Heat,2010-10-26,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,BOS vs. MIA,Regular Season,2010-11,2010,25.774173,-80.193620,42.360253,-71.058291,1257.755091,America/New_York,America/New_York,0.0,0.0,Miami,United States,377.5,262.7,2.0,0.0,2.0,1.0,0.0,2.0,1.0,3.0,0.666667,0.333333,3.0,2.0,5.0,0.600000,0.400000,4.0,3.0,7.0,0.571429,0.428571,51.0,52.0,103.0,0.495146,0.504854
20531,21000001,Celtics,2010-10-26,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,BOS vs. MIA,Regular Season,2010-11,2010,42.360253,-71.058291,42.360253,-71.058291,0.000000,America/New_York,America/New_York,0.0,0.0,Boston,United States,463.570,560.1,1.0,1.0,2.0,0.5,0.5,1.0,2.0,3.0,0.333333,0.666667,2.0,2.0,4.0,0.500000,0.500000,2.0,4.0,6.0,0.333333,0.666667,46.0,45.0,91.0,0.505495,0.494505