In [1]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA
from sklearn.preprocessing import scale


pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

pd.set_option('display.max_colwidth', None)
pd.options.display.max_info_columns = 999

#return the first 5 and last 5 rows of this dataframe
def p(df_):
    if df_.shape[0] > 6:
        print(df_.shape)
        return pd.concat([df_.head(), df_.tail()])
    else:
        return df_

def rcp(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'processed_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'processed_data', file_), parse_dates=pd_)
    
def rcr(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'raw_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'raw_data', file_), parse_dates=pd_)
    
#sort dataframe by column
def s(df_, column_):
    return df_.sort_values(column_)

#reset index and sort dataframe by column
def sr(df_, column_):
    df_ = df_.sort_values(column_)
    return df_.reset_index(drop=True)

#print length of list
def pl(list_):
    print(len(list_))
    return list_

#print length of list
def pdc(dict_):
    print(len(dict_))
    return dict_

#import my functions
import my_functions as f

In [2]:
df_game_id_team_id_a_team_id_b_away_home_a_ = rcp('60_game_id_team_id_a_team_id_b_away_home_a_2010_2018.csv')
p(df_game_id_team_id_a_team_id_b_away_home_a_)

(10266, 4)

        game_id   team_id_a   team_id_b  away_home_a
0      21000001  1610612738  1610612748            1
1      21000002  1610612756  1610612757            0
2      21000003  1610612745  1610612747            0
3      21000004  1610612738  1610612739            0
4      21000005  1610612765  1610612751            0
10261  41700317  1610612744  1610612745            0
10262  41700401  1610612739  1610612744            0
10263  41700402  1610612739  1610612744            0
10264  41700403  1610612739  1610612744            1
10265  41700404  1610612739  1610612744            1

In [3]:
df59 = rcp('59merge_58A_lost_contribution_58B_stat_cma5_12_999_cmax5_12_999_diff_58C_stat_seaon_matchup_cma12_cmax12_diff.csv')
p(df59)

(10266, 865)

,game_id,team_id_a,TEAM_ABBREVIATION_a,game_date,season,team_id_b,TEAM_ABBREVIATION_b,losses_diff,wins_diff,win_pct_diff,opp_win_pct_diff,opp_losses_diff,opp_wins_diff,opp_opps_losses_diff,opp_opps_wins_diff,opp_opps_win_pct_diff,strength_of_schedule_diff,season_type,season_year,Team_a,TEAM_NAME_a,TEAM_CITY_a,wl_a,matchup_a,a_a,b_a,Team_b,TEAM_NAME_b,TEAM_CITY_b,wl_b,matchup_b,a_b,b_b,lc_sum_MIN_cma5_diff,lc_sum_E_OFF_RATING_cma5_diff,lc_sum_OFF_RATING_cma5_diff,lc_sum_E_DEF_RATING_cma5_diff,lc_sum_DEF_RATING_cma5_diff,lc_sum_E_NET_RATING_cma5_diff,lc_sum_NET_RATING_cma5_diff,lc_sum_AST_PCT_cma5_diff,lc_sum_AST_TOV_cma5_diff,lc_sum_AST_RATIO_cma5_diff,lc_sum_OREB_PCT_cma5_diff,lc_sum_DREB_PCT_cma5_diff,lc_sum_REB_PCT_cma5_diff,lc_sum_TM_TOV_PCT_cma5_diff,lc_sum_EFG_PCT_cma5_diff,lc_sum_TS_PCT_cma5_diff,lc_sum_USG_PCT_cma5_diff,lc_sum_E_USG_PCT_cma5_diff,lc_sum_E_PACE_cma5_diff,lc_sum_PACE_cma5_diff,lc_sum_PACE_PER40_cma5_diff,lc_sum_POSS_cma5_diff,lc_sum_PIE_cma5_diff,lc_mean_MIN_cma5_diff,lc_mean_E_OFF_RATING_cma5_diff,lc_mean_OFF_RATING_cma5_diff,lc_mean_E_DEF_RATING_cma5_diff,lc_mean_DEF_RATING_cma5_diff,lc_mean_E_NET_RATING_cma5_diff,lc_mean_NET_RATING_cma5_diff,lc_mean_AST_PCT_cma5_diff,lc_mean_AST_TOV_cma5_diff,lc_mean_AST_RATIO_cma5_diff,lc_mean_OREB_PCT_cma5_diff,lc_mean_DREB_PCT_cma5_diff,lc_mean_REB_PCT_cma5_diff,lc_mean_TM_TOV_PCT_cma5_diff,lc_mean_EFG_PCT_cma5_diff,lc_mean_TS_PCT_cma5_diff,lc_mean_USG_PCT_cma5_diff,lc_mean_E_USG_PCT_cma5_diff,lc_mean_E_PACE_cma5_diff,lc_mean_PACE_cma5_diff,lc_mean_PACE_PER40_cma5_diff,lc_mean_POSS_cma5_diff,lc_mean_PIE_cma5_diff,lc_max_MIN_cma5_diff,lc_max_E_OFF_RATING_cma5_diff,lc_max_OFF_RATING_cma5_diff,lc_max_E_DEF_RATING_cma5_diff,lc_max_DEF_RATING_cma5_diff,lc_max_E_NET_RATING_cma5_diff,lc_max_NET_RATING_cma5_diff,lc_max_AST_PCT_cma5_diff,lc_max_AST_TOV_cma5_diff,lc_max_AST_RATIO_cma5_diff,lc_max_OREB_PCT_cma5_diff,lc_max_DREB_PCT_cma5_diff,lc_max_REB_PCT_cma5_diff,lc_max_TM_TOV_PCT_cma5_diff,lc_max_EFG_PCT_cma5_diff,lc_max_TS_PCT_cma5_diff,lc_max_USG_PCT_cma5_diff,lc_max_E_USG_PCT_cma5_diff,lc_max_E_PACE_cma5_diff,lc_max_PACE_cma5_diff,lc_max_PACE_PER40_cma5_diff,lc_max_POSS_cma5_diff,lc_max_PIE_cma5_diff,lc_sum_MIN_cma12_diff,lc_sum_E_OFF_RATING_cma12_diff,lc_sum_OFF_RATING_cma12_diff,lc_sum_E_DEF_RATING_cma12_diff,lc_sum_DEF_RATING_cma12_diff,lc_sum_E_NET_RATING_cma12_diff,lc_sum_NET_RATING_cma12_diff,lc_sum_AST_PCT_cma12_diff,lc_sum_AST_TOV_cma12_diff,lc_sum_AST_RATIO_cma12_diff,lc_sum_OREB_PCT_cma12_diff,lc_sum_DREB_PCT_cma12_diff,lc_sum_REB_PCT_cma12_diff,lc_sum_TM_TOV_PCT_cma12_diff,lc_sum_EFG_PCT_cma12_diff,lc_sum_TS_PCT_cma12_diff,lc_sum_USG_PCT_cma12_diff,lc_sum_E_USG_PCT_cma12_diff,lc_sum_E_PACE_cma12_diff,lc_sum_PACE_cma12_diff,lc_sum_PACE_PER40_cma12_diff,lc_sum_POSS_cma12_diff,lc_sum_PIE_cma12_diff,lc_mean_MIN_cma12_diff,lc_mean_E_OFF_RATING_cma12_diff,lc_mean_OFF_RATING_cma12_diff,lc_mean_E_DEF_RATING_cma12_diff,lc_mean_DEF_RATING_cma12_diff,lc_mean_E_NET_RATING_cma12_diff,lc_mean_NET_RATING_cma12_diff,lc_mean_AST_PCT_cma12_diff,lc_mean_AST_TOV_cma12_diff,lc_mean_AST_RATIO_cma12_diff,lc_mean_OREB_PCT_cma12_diff,lc_mean_DREB_PCT_cma12_diff,lc_mean_REB_PCT_cma12_diff,lc_mean_TM_TOV_PCT_cma12_diff,lc_mean_EFG_PCT_cma12_diff,lc_mean_TS_PCT_cma12_diff,lc_mean_USG_PCT_cma12_diff,lc_mean_E_USG_PCT_cma12_diff,lc_mean_E_PACE_cma12_diff,lc_mean_PACE_cma12_diff,lc_mean_PACE_PER40_cma12_diff,lc_mean_POSS_cma12_diff,lc_mean_PIE_cma12_diff,lc_max_MIN_cma12_diff,lc_max_E_OFF_RATING_cma12_diff,lc_max_OFF_RATING_cma12_diff,lc_max_E_DEF_RATING_cma12_diff,lc_max_DEF_RATING_cma12_diff,lc_max_E_NET_RATING_cma12_diff,lc_max_NET_RATING_cma12_diff,lc_max_AST_PCT_cma12_diff,lc_max_AST_TOV_cma12_diff,lc_max_AST_RATIO_cma12_diff,lc_max_OREB_PCT_cma12_diff,lc_max_DREB_PCT_cma12_diff,lc_max_REB_PCT_cma12_diff,lc_max_TM_TOV_PCT_cma12_diff,lc_max_EFG_PCT_cma12_diff,lc_max_TS_PCT_cma12_diff,lc_max_USG_PCT_cma12_diff,lc_max_E_USG_PCT_cma12_diff,lc_max_E_PACE_cma12_diff,lc_max_PACE_cma12_diff,lc_max_PACE_PER40_cma12_diff,lc_max_POSS_cma12_diff,lc_max_PIE_cma12_diff,lc_sum_MIN_cma999_diff,lc_sum_E_OFF_RATING_cma999_diff,lc_sum_OFF_RATING_cma999_diff,lc_sum_E_DEF_RATING_cma999_diff,lc_sum_DEF_RATING_cma999_diff,lc_sum_E_NET_RATING_cma999_diff,lc_sum_NET_RATING_cma999_diff,lc_sum_AST_PCT_cma999_diff,lc_sum_AST_TOV_cma999_diff,lc_sum_AST_RATIO_cma999_diff,lc_sum_OREB_PCT_cma999_diff,lc_sum_DREB_PCT_cma999_diff,lc_sum_REB_PCT_cma999_diff,lc_sum_TM_TOV_PCT_cma999_diff,lc_sum_EFG_PCT_cma999_diff,lc_sum_TS_PCT_cma999_diff,lc_sum_USG_PCT_cma999_diff,lc_sum_E_USG_PCT_cma999_diff,lc_sum_E_PACE_cma999_diff,lc_sum_PACE_cma999_diff,lc_sum_PACE_PER40_cma999_diff,lc_sum_POSS_cma999_diff,lc_sum_PIE_cma999_diff,lc_mean_MIN_cma999_diff,lc_mean_E_OFF_RATING_cma999_diff,lc_mean_OFF_RATING_cma999_diff,lc_mean_E_DEF_RATING_cma999_diff,lc_mean_DEF_RATING_cma999_diff,lc_mean_E_NET_RATING_cma999_diff,lc_mean_NET_RATING_cma999_diff,lc_mean_AST_PCT_cma999_diff,lc_mean_AST_TOV_cma999_diff,lc_mean_AST_RATIO_cma999_diff,lc_mean_OREB_PCT_cma999_diff,lc_mean_DREB_PCT_cma999_diff,lc_mean_REB_PCT_cma999_diff,lc_mean_TM_TOV_PCT_cma999_diff,lc_mean_EFG_PCT_cma999_diff,lc_mean_TS_PCT_cma999_diff,lc_mean_USG_PCT_cma999_diff,lc_mean_E_USG_PCT_cma999_diff,lc_mean_E_PACE_cma999_diff,lc_mean_PACE_cma999_diff,lc_mean_PACE_PER40_cma999_diff,lc_mean_POSS_cma999_diff,lc_mean_PIE_cma999_diff,lc_max_MIN_cma999_diff,lc_max_E_OFF_RATING_cma999_diff,lc_max_OFF_RATING_cma999_diff,lc_max_E_DEF_RATING_cma999_diff,lc_max_DEF_RATING_cma999_diff,lc_max_E_NET_RATING_cma999_diff,lc_max_NET_RATING_cma999_diff,lc_max_AST_PCT_cma999_diff,lc_max_AST_TOV_cma999_diff,lc_max_AST_RATIO_cma999_diff,lc_max_OREB_PCT_cma999_diff,lc_max_DREB_PCT_cma999_diff,lc_max_REB_PCT_cma999_diff,lc_max_TM_TOV_PCT_cma999_diff,lc_max_EFG_PCT_cma999_diff,lc_max_TS_PCT_cma999_diff,lc_max_USG_PCT_cma999_diff,lc_max_E_USG_PCT_cma999_diff,lc_max_E_PACE_cma999_diff,lc_max_PACE_cma999_diff,lc_max_PACE_PER40_cma999_diff,lc_max_POSS_cma999_diff,lc_max_PIE_cma999_diff,lc_sum_MIN_cmax5_diff,lc_sum_E_OFF_RATING_cmax5_diff,lc_sum_OFF_RATING_cmax5_diff,lc_sum_E_DEF_RATING_cmax5_diff,lc_sum_DEF_RATING_cmax5_diff,lc_sum_E_NET_RATING_cmax5_diff,lc_sum_NET_RATING_cmax5_diff,lc_sum_AST_PCT_cmax5_diff,lc_sum_AST_TOV_cmax5_diff,lc_sum_AST_RATIO_cmax5_diff,lc_sum_OREB_PCT_cmax5_diff,lc_sum_DREB_PCT_cmax5_diff,lc_sum_REB_PCT_cmax5_diff,lc_sum_TM_TOV_PCT_cmax5_diff,lc_sum_EFG_PCT_cmax5_diff,lc_sum_TS_PCT_cmax5_diff,lc_sum_USG_PCT_cmax5_diff,lc_sum_E_USG_PCT_cmax5_diff,lc_sum_E_PACE_cmax5_diff,lc_sum_PACE_cmax5_diff,lc_sum_PACE_PER40_cmax5_diff,lc_sum_POSS_cmax5_diff,lc_sum_PIE_cmax5_diff,lc_mean_MIN_cmax5_diff,lc_mean_E_OFF_RATING_cmax5_diff,lc_mean_OFF_RATING_cmax5_diff,lc_mean_E_DEF_RATING_cmax5_diff,lc_mean_DEF_RATING_cmax5_diff,lc_mean_E_NET_RATING_cmax5_diff,lc_mean_NET_RATING_cmax5_diff,lc_mean_AST_PCT_cmax5_diff,lc_mean_AST_TOV_cmax5_diff,lc_mean_AST_RATIO_cmax5_diff,lc_mean_OREB_PCT_cmax5_diff,lc_mean_DREB_PCT_cmax5_diff,lc_mean_REB_PCT_cmax5_diff,lc_mean_TM_TOV_PCT_cmax5_diff,lc_mean_EFG_PCT_cmax5_diff,lc_mean_TS_PCT_cmax5_diff,lc_mean_USG_PCT_cmax5_diff,lc_mean_E_USG_PCT_cmax5_diff,lc_mean_E_PACE_cmax5_diff,lc_mean_PACE_cmax5_diff,lc_mean_PACE_PER40_cmax5_diff,lc_mean_POSS_cmax5_diff,lc_mean_PIE_cmax5_diff,lc_max_MIN_cmax5_diff,lc_max_E_OFF_RATING_cmax5_diff,lc_max_OFF_RATING_cmax5_diff,lc_max_E_DEF_RATING_cmax5_diff,lc_max_DEF_RATING_cmax5_diff,lc_max_E_NET_RATING_cmax5_diff,lc_max_NET_RATING_cmax5_diff,lc_max_AST_PCT_cmax5_diff,lc_max_AST_TOV_cmax5_diff,lc_max_AST_RATIO_cmax5_diff,lc_max_OREB_PCT_cmax5_diff,lc_max_DREB_PCT_cmax5_diff,lc_max_REB_PCT_cmax5_diff,lc_max_TM_TOV_PCT_cmax5_diff,lc_max_EFG_PCT_cmax5_diff,lc_max_TS_PCT_cmax5_diff,lc_max_USG_PCT_cmax5_diff,lc_max_E_USG_PCT_cmax5_diff,lc_max_E_PACE_cmax5_diff,lc_max_PACE_cmax5_diff,lc_max_PACE_PER40_cmax5_diff,lc_max_POSS_cmax5_diff,lc_max_PIE_cmax5_diff,lc_sum_MIN_cmax12_diff,lc_sum_E_OFF_RATING_cmax12_diff,lc_sum_OFF_RATING_cmax12_diff,lc_sum_E_DEF_RATING_cmax12_diff,lc_sum_DEF_RATING_cmax12_diff,lc_sum_E_NET_RATING_cmax12_diff,lc_sum_NET_RATING_cmax12_diff,lc_sum_AST_PCT_cmax12_diff,lc_sum_AST_TOV_cmax12_diff,lc_sum_AST_RATIO_cmax12_diff,lc_sum_OREB_PCT_cmax12_diff,lc_sum_DREB_PCT_cmax12_diff,lc_sum_REB_PCT_cmax12_diff,lc_sum_TM_TOV_PCT_cmax12_diff,lc_sum_EFG_PCT_cmax12_diff,lc_sum_TS_PCT_cmax12_diff,lc_sum_USG_PCT_cmax12_diff,lc_sum_E_USG_PCT_cmax12_diff,lc_sum_E_PACE_cmax12_diff,lc_sum_PACE_cmax12_diff,lc_sum_PACE_PER40_cmax12_diff,lc_sum_POSS_cmax12_diff,lc_sum_PIE_cmax12_diff,lc_mean_MIN_cmax12_diff,lc_mean_E_OFF_RATING_cmax12_diff,lc_mean_OFF_RATING_cmax12_diff,lc_mean_E_DEF_RATING_cmax12_diff,lc_mean_DEF_RATING_cmax12_diff,lc_mean_E_NET_RATING_cmax12_diff,lc_mean_NET_RATING_cmax12_diff,lc_mean_AST_PCT_cmax12_diff,lc_mean_AST_TOV_cmax12_diff,lc_mean_AST_RATIO_cmax12_diff,lc_mean_OREB_PCT_cmax12_diff,lc_mean_DREB_PCT_cmax12_diff,lc_mean_REB_PCT_cmax12_diff,lc_mean_TM_TOV_PCT_cmax12_diff,lc_mean_EFG_PCT_cmax12_diff,lc_mean_TS_PCT_cmax12_diff,lc_mean_USG_PCT_cmax12_diff,lc_mean_E_USG_PCT_cmax12_diff,lc_mean_E_PACE_cmax12_diff,lc_mean_PACE_cmax12_diff,lc_mean_PACE_PER40_cmax12_diff,lc_mean_POSS_cmax12_diff,lc_mean_PIE_cmax12_diff,lc_max_MIN_cmax12_diff,lc_max_E_OFF_RATING_cmax12_diff,lc_max_OFF_RATING_cmax12_diff,lc_max_E_DEF_RATING_cmax12_diff,lc_max_DEF_RATING_cmax12_diff,lc_max_E_NET_RATING_cmax12_diff,lc_max_NET_RATING_cmax12_diff,lc_max_AST_PCT_cmax12_diff,lc_max_AST_TOV_cmax12_diff,lc_max_AST_RATIO_cmax12_diff,lc_max_OREB_PCT_cmax12_diff,lc_max_DREB_PCT_cmax12_diff,lc_max_REB_PCT_cmax12_diff,lc_max_TM_TOV_PCT_cmax12_diff,lc_max_EFG_PCT_cmax12_diff,lc_max_TS_PCT_cmax12_diff,lc_max_USG_PCT_cmax12_diff,lc_max_E_USG_PCT_cmax12_diff,lc_max_E_PACE_cmax12_diff,lc_max_PACE_cmax12_diff,lc_max_PACE_PER40_cmax12_diff,lc_max_POSS_cmax12_diff,lc_max_PIE_cmax12_diff,lc_sum_MIN_cmax999_diff,lc_sum_E_OFF_RATING_cmax999_diff,lc_sum_OFF_RATING_cmax999_diff,lc_sum_E_DEF_RATING_cmax999_diff,lc_sum_DEF_RATING_cmax999_diff,lc_sum_E_NET_RATING_cmax999_diff,lc_sum_NET_RATING_cmax999_diff,lc_sum_AST_PCT_cmax999_diff,lc_sum_AST_TOV_cmax999_diff,lc_sum_AST_RATIO_cmax999_diff,lc_sum_OREB_PCT_cmax999_diff,lc_sum_DREB_PCT_cmax999_diff,lc_sum_REB_PCT_cmax999_diff,lc_sum_TM_TOV_PCT_cmax999_diff,lc_sum_EFG_PCT_cmax999_diff,lc_sum_TS_PCT_cmax999_diff,lc_sum_USG_PCT_cmax999_diff,lc_sum_E_USG_PCT_cmax999_diff,lc_sum_E_PACE_cmax999_diff,lc_sum_PACE_cmax999_diff,lc_sum_PACE_PER40_cmax999_diff,lc_sum_POSS_cmax999_diff,lc_sum_PIE_cmax999_diff,lc_mean_MIN_cmax999_diff,lc_mean_E_OFF_RATING_cmax999_diff,lc_mean_OFF_RATING_cmax999_diff,lc_mean_E_DEF_RATING_cmax999_diff,lc_mean_DEF_RATING_cmax999_diff,lc_mean_E_NET_RATING_cmax999_diff,lc_mean_NET_RATING_cmax999_diff,lc_mean_AST_PCT_cmax999_diff,lc_mean_AST_TOV_cmax999_diff,lc_mean_AST_RATIO_cmax999_diff,lc_mean_OREB_PCT_cmax999_diff,lc_mean_DREB_PCT_cmax999_diff,lc_mean_REB_PCT_cmax999_diff,lc_mean_TM_TOV_PCT_cmax999_diff,lc_mean_EFG_PCT_cmax999_diff,lc_mean_TS_PCT_cmax999_diff,lc_mean_USG_PCT_cmax999_diff,lc_mean_E_USG_PCT_cmax999_diff,lc_mean_E_PACE_cmax999_diff,lc_mean_PACE_cmax999_diff,lc_mean_PACE_PER40_cmax999_diff,lc_mean_POSS_cmax999_diff,lc_mean_PIE_cmax999_diff,lc_max_MIN_cmax999_diff,lc_max_E_OFF_RATING_cmax999_diff,lc_max_OFF_RATING_cmax999_diff,lc_max_E_DEF_RATING_cmax999_diff,lc_max_DEF_RATING_cmax999_diff,lc_max_E_NET_RATING_cmax999_diff,lc_max_NET_RATING_cmax999_diff,lc_max_AST_PCT_cmax999_diff,lc_max_AST_TOV_cmax999_diff,lc_max_AST_RATIO_cmax999_diff,lc_max_OREB_PCT_cmax999_diff,lc_max_DREB_PCT_cmax999_diff,lc_max_REB_PCT_cmax999_diff,lc_max_TM_TOV_PCT_cmax999_diff,lc_max_EFG_PCT_cmax999_diff,lc_max_TS_PCT_cmax999_diff,lc_max_USG_PCT_cmax999_diff,lc_max_E_USG_PCT_cmax999_diff,lc_max_E_PACE_cmax999_diff,lc_max_PACE_cmax999_diff,lc_max_PACE_PER40_cmax999_diff,lc_max_POSS_cmax999_diff,lc_max_PIE_cmax999_diff,MIN_a,duration_a,MIN_b,duration_b,E_OFF_RATING_cma5_diff,OFF_RATING_cma5_diff,E_DEF_RATING_cma5_diff,DEF_RATING_cma5_diff,E_NET_RATING_cma5_diff,NET_RATING_cma5_diff,AST_PCT_cma5_diff,AST_TOV_cma5_diff,AST_RATIO_cma5_diff,OREB_PCT_cma5_diff,DREB_PCT_cma5_diff,REB_PCT_cma5_diff,E_TM_TOV_PCT_cma5_diff,TM_TOV_PCT_cma5_diff,EFG_PCT_cma5_diff,TS_PCT_cma5_diff,USG_PCT_cma5_diff,E_USG_PCT_cma5_diff,E_PACE_cma5_diff,PACE_cma5_diff,PACE_PER40_cma5_diff,POSS_cma5_diff,PIE_cma5_diff,duration_minutes_cma5_diff,w_pct_cma5_diff,min_cma5_diff,fgm_cma5_diff,fga_cma5_diff,fg_pct_cma5_diff,fg3m_cma5_diff,fg3a_cma5_diff,fg3_pct_cma5_diff,ftm_cma5_diff,fta_cma5_diff,ft_pct_cma5_diff,oreb_cma5_diff,dreb_cma5_diff,reb_cma5_diff,ast_cma5_diff,stl_cma5_diff,blk_cma5_diff,tov_cma5_diff,pf_cma5_diff,pts_cma5_diff,spread_cma5_diff,away_home__cma5_diff,E_OFF_RATING_cma12_diff,OFF_RATING_cma12_diff,E_DEF_RATING_cma12_diff,DEF_RATING_cma12_diff,E_NET_RATING_cma12_diff,NET_RATING_cma12_diff,AST_PCT_cma12_diff,AST_TOV_cma12_diff,AST_RATIO_cma12_diff,OREB_PCT_cma12_diff,DREB_PCT_cma12_diff,REB_PCT_cma12_diff,E_TM_TOV_PCT_cma12_diff,TM_TOV_PCT_cma12_diff,EFG_PCT_cma12_diff,TS_PCT_cma12_diff,USG_PCT_cma12_diff,E_USG_PCT_cma12_diff,E_PACE_cma12_diff,PACE_cma12_diff,PACE_PER40_cma12_diff,POSS_cma12_diff,PIE_cma12_diff,duration_minutes_cma12_diff,w_pct_cma12_diff,min_cma12_diff,fgm_cma12_diff,fga_cma12_diff,fg_pct_cma12_diff,fg3m_cma12_diff,fg3a_cma12_diff,fg3_pct_cma12_diff,ftm_cma12_diff,fta_cma12_diff,ft_pct_cma12_diff,oreb_cma12_diff,dreb_cma12_diff,reb_cma12_diff,ast_cma12_diff,stl_cma12_diff,blk_cma12_diff,tov_cma12_diff,pf_cma12_diff,pts_cma12_diff,spread_cma12_diff,away_home__cma12_diff,E_OFF_RATING_cma999_diff,OFF_RATING_cma999_diff,E_DEF_RATING_cma999_diff,DEF_RATING_cma999_diff,E_NET_RATING_cma999_diff,NET_RATING_cma999_diff,AST_PCT_cma999_diff,AST_TOV_cma999_diff,AST_RATIO_cma999_diff,OREB_PCT_cma999_diff,DREB_PCT_cma999_diff,REB_PCT_cma999_diff,E_TM_TOV_PCT_cma999_diff,TM_TOV_PCT_cma999_diff,EFG_PCT_cma999_diff,TS_PCT_cma999_diff,USG_PCT_cma999_diff,E_USG_PCT_cma999_diff,E_PACE_cma999_diff,PACE_cma999_diff,PACE_PER40_cma999_diff,POSS_cma999_diff,PIE_cma999_diff,duration_minutes_cma999_diff,w_pct_cma999_diff,min_cma999_diff,fgm_cma999_diff,fga_cma999_diff,fg_pct_cma999_diff,fg3m_cma999_diff,fg3a_cma999_diff,fg3_pct_cma999_diff,ftm_cma999_diff,fta_cma999_diff,ft_pct_cma999_diff,oreb_cma999_diff,dreb_cma999_diff,reb_cma999_diff,ast_cma999_diff,stl_cma999_diff,blk_cma999_diff,tov_cma999_diff,pf_cma999_diff,pts_cma999_diff,spread_cma999_diff,away_home__cma999_diff,E_OFF_RATING_cmax5_diff,OFF_RATING_cmax5_diff,E_DEF_RATING_cmax5_diff,DEF_RATING_cmax5_diff,E_NET_RATING_cmax5_diff,NET_RATING_cmax5_diff,AST_PCT_cmax5_diff,AST_TOV_cmax5_diff,AST_RATIO_cmax5_diff,OREB_PCT_cmax5_diff,DREB_PCT_cmax5_diff,REB_PCT_cmax5_diff,E_TM_TOV_PCT_cmax5_diff,TM_TOV_PCT_cmax5_diff,EFG_PCT_cmax5_diff,TS_PCT_cmax5_diff,USG_PCT_cmax5_diff,E_USG_PCT_cmax5_diff,E_PACE_cmax5_diff,PACE_cmax5_diff,PACE_PER40_cmax5_diff,POSS_cmax5_diff,PIE_cmax5_diff,duration_minutes_cmax5_diff,w_pct_cmax5_diff,min_cmax5_diff,fgm_cmax5_diff,fga_cmax5_diff,fg_pct_cmax5_diff,fg3m_cmax5_diff,fg3a_cmax5_diff,fg3_pct_cmax5_diff,ftm_cmax5_diff,fta_cmax5_diff,ft_pct_cmax5_diff,oreb_cmax5_diff,dreb_cmax5_diff,reb_cmax5_diff,ast_cmax5_diff,stl_cmax5_diff,blk_cmax5_diff,tov_cmax5_diff,pf_cmax5_diff,pts_cmax5_diff,spread_cmax5_diff,away_home__cmax5_diff,E_OFF_RATING_cmax12_diff,OFF_RATING_cmax12_diff,E_DEF_RATING_cmax12_diff,DEF_RATING_cmax12_diff,E_NET_RATING_cmax12_diff,NET_RATING_cmax12_diff,AST_PCT_cmax12_diff,AST_TOV_cmax12_diff,AST_RATIO_cmax12_diff,OREB_PCT_cmax12_diff,DREB_PCT_cmax12_diff,REB_PCT_cmax12_diff,E_TM_TOV_PCT_cmax12_diff,TM_TOV_PCT_cmax12_diff,EFG_PCT_cmax12_diff,TS_PCT_cmax12_diff,USG_PCT_cmax12_diff,E_USG_PCT_cmax12_diff,E_PACE_cmax12_diff,PACE_cmax12_diff,PACE_PER40_cmax12_diff,POSS_cmax12_diff,PIE_cmax12_diff,duration_minutes_cmax12_diff,w_pct_cmax12_diff,min_cmax12_diff,fgm_cmax12_diff,fga_cmax12_diff,fg_pct_cmax12_diff,fg3m_cmax12_diff,fg3a_cmax12_diff,fg3_pct_cmax12_diff,ftm_cmax12_diff,fta_cmax12_diff,ft_pct_cmax12_diff,oreb_cmax12_diff,dreb_cmax12_diff,reb_cmax12_diff,ast_cmax12_diff,stl_cmax12_diff,blk_cmax12_diff,tov_cmax12_diff,pf_cmax12_diff,pts_cmax12_diff,spread_cmax12_diff,away_home__cmax12_diff,E_OFF_RATING_cmax999_diff,OFF_RATING_cmax999_diff,E_DEF_RATING_cmax999_diff,DEF_RATING_cmax999_diff,E_NET_RATING_cmax999_diff,NET_RATING_cmax999_diff,AST_PCT_cmax999_diff,AST_TOV_cmax999_diff,AST_RATIO_cmax999_diff,OREB_PCT_cmax999_diff,DREB_PCT_cmax999_diff,REB_PCT_cmax999_diff,E_TM_TOV_PCT_cmax999_diff,TM_TOV_PCT_cmax999_diff,EFG_PCT_cmax999_diff,TS_PCT_cmax999_diff,USG_PCT_cmax999_diff,E_USG_PCT_cmax999_diff,E_PACE_cmax999_diff,PACE_cmax999_diff,PACE_PER40_cmax999_diff,POSS_cmax999_diff,PIE_cmax999_diff,duration_minutes_cmax999_diff,w_pct_cmax999_diff,min_cmax999_diff,fgm_cmax999_diff,fga_cmax999_diff,fg_pct_cmax999_diff,fg3m_cmax999_diff,fg3a_cmax999_diff,fg3_pct_cmax999_diff,ftm_cmax999_diff,fta_cmax999_diff,ft_pct_cmax999_diff,oreb_cmax999_diff,dreb_cmax999_diff,reb_cmax999_diff,ast_cmax999_diff,stl_cmax999_diff,blk_cmax999_diff,tov_cmax999_diff,pf_cmax999_diff,pts_cmax999_diff,spread_cmax999_diff,away_home__cmax999_diff,E_OFF_RATING_sm_cma12_diff,OFF_RATING_sm_cma12_diff,E_DEF_RATING_sm_cma12_diff,DEF_RATING_sm_cma12_diff,E_NET_RATING_sm_cma12_diff,NET_RATING_sm_cma12_diff,AST_PCT_sm_cma12_diff,AST_TOV_sm_cma12_diff,AST_RATIO_sm_cma12_diff,OREB_PCT_sm_cma12_diff,DREB_PCT_sm_cma12_diff,REB_PCT_sm_cma12_diff,E_TM_TOV_PCT_sm_cma12_diff,TM_TOV_PCT_sm_cma12_diff,EFG_PCT_sm_cma12_diff,TS_PCT_sm_cma12_diff,USG_PCT_sm_cma12_diff,E_USG_PCT_sm_cma12_diff,E_PACE_sm_cma12_diff,PACE_sm_cma12_diff,PACE_PER40_sm_cma12_diff,POSS_sm_cma12_diff,PIE_sm_cma12_diff,duration_minutes_sm_cma12_diff,w_pct_sm_cma12_diff,min_sm_cma12_diff,fgm_sm_cma12_diff,fga_sm_cma12_diff,fg_pct_sm_cma12_diff,fg3m_sm_cma12_diff,fg3a_sm_cma12_diff,fg3_pct_sm_cma12_diff,ftm_sm_cma12_diff,fta_sm_cma12_diff,ft_pct_sm_cma12_diff,oreb_sm_cma12_diff,dreb_sm_cma12_diff,reb_sm_cma12_diff,ast_sm_cma12_diff,stl_sm_cma12_diff,blk_sm_cma12_diff,tov_sm_cma12_diff,pf_sm_cma12_diff,pts_sm_cma12_diff,spread_sm_cma12_diff,away_home_sm_cma12_diff,E_OFF_RATING_sm_cmax12_diff,OFF_RATING_sm_cmax12_diff,E_DEF_RATING_sm_cmax12_diff,DEF_RATING_sm_cmax12_diff,E_NET_RATING_sm_cmax12_diff,NET_RATING_sm_cmax12_diff,AST_PCT_sm_cmax12_diff,AST_TOV_sm_cmax12_diff,AST_RATIO_sm_cmax12_diff,OREB_PCT_sm_cmax12_diff,DREB_PCT_sm_cmax12_diff,REB_PCT_sm_cmax12_diff,E_TM_TOV_PCT_sm_cmax12_diff,TM_TOV_PCT_sm_cmax12_diff,EFG_PCT_sm_cmax12_diff,TS_PCT_sm_cmax12_diff,USG_PCT_sm_cmax12_diff,E_USG_PCT_sm_cmax12_diff,E_PACE_sm_cmax12_diff,PACE_sm_cmax12_diff,PACE_PER40_sm_cmax12_diff,POSS_sm_cmax12_diff,PIE_sm_cmax12_diff,duration_minutes_sm_cmax12_diff,w_pct_sm_cmax12_diff,min_sm_cmax12_diff,fgm_sm_cmax12_diff,fga_sm_cmax12_diff,fg_pct_sm_cmax12_diff,fg3m_sm_cmax12_diff,fg3a_sm_cmax12_diff,fg3_pct_sm_cmax12_diff,ftm_sm_cmax12_diff,fta_sm_cmax12_diff,ft_pct_sm_cmax12_diff,oreb_sm_cmax12_diff,dreb_sm_cmax12_diff,reb_sm_cmax12_diff,ast_sm_cmax12_diff,stl_sm_cmax12_diff,blk_sm_cmax12_diff,tov_sm_cmax12_diff,pf_sm_cmax12_diff,pts_sm_cmax12_diff,spread_sm_cmax12_diff,away_home_sm_cmax12_diff,E_OFF_RATING_cma_sm_cmax12_diff,OFF_RATING_cma_sm_cmax12_diff,E_DEF_RATING_cma_sm_cmax12_diff,DEF_RATING_cma_sm_cmax12_diff,E_NET_RATING_cma_sm_cmax12_diff,NET_RATING_cma_sm_cmax12_diff,AST_PCT_cma_sm_cmax12_diff,AST_TOV_cma_sm_cmax12_diff,AST_RATIO_cma_sm_cmax12_diff,OREB_PCT_cma_sm_cmax12_diff,DREB_PCT_cma_sm_cmax12_diff,REB_PCT_cma_sm_cmax12_diff,E_TM_TOV_PCT_cma_sm_cmax12_diff,TM_TOV_PCT_cma_sm_cmax12_diff,EFG_PCT_cma_sm_cmax12_diff,TS_PCT_cma_sm_cmax12_diff,USG_PCT_cma_sm_cmax12_diff,E_USG_PCT_cma_sm_cmax12_diff,E_PACE_cma_sm_cmax12_diff,PACE_cma_sm_cmax12_diff,PACE_PER40_cma_sm_cmax12_diff,POSS_cma_sm_cmax12_diff,PIE_cma_sm_cmax12_diff,duration_minutes_cma_sm_cmax12_diff,w_pct_cma_sm_cmax12_diff,min_cma_sm_cmax12_diff,fgm_cma_sm_cmax12_diff,fga_cma_sm_cmax12_diff,fg_pct_cma_sm_cmax12_diff,fg3m_cma_sm_cmax12_diff,fg3a_cma_sm_cmax12_diff,fg3_p

In [4]:
df_merged = pd.merge(df_game_id_team_id_a_team_id_b_away_home_a_,
                     df59,
                     on=['game_id', 'team_id_a', 'team_id_b'])
p(df_merged)

(10266, 866)

,game_id,team_id_a,team_id_b,away_home_a,TEAM_ABBREVIATION_a,game_date,season,TEAM_ABBREVIATION_b,losses_diff,wins_diff,win_pct_diff,opp_win_pct_diff,opp_losses_diff,opp_wins_diff,opp_opps_losses_diff,opp_opps_wins_diff,opp_opps_win_pct_diff,strength_of_schedule_diff,season_type,season_year,Team_a,TEAM_NAME_a,TEAM_CITY_a,wl_a,matchup_a,a_a,b_a,Team_b,TEAM_NAME_b,TEAM_CITY_b,wl_b,matchup_b,a_b,b_b,lc_sum_MIN_cma5_diff,lc_sum_E_OFF_RATING_cma5_diff,lc_sum_OFF_RATING_cma5_diff,lc_sum_E_DEF_RATING_cma5_diff,lc_sum_DEF_RATING_cma5_diff,lc_sum_E_NET_RATING_cma5_diff,lc_sum_NET_RATING_cma5_diff,lc_sum_AST_PCT_cma5_diff,lc_sum_AST_TOV_cma5_diff,lc_sum_AST_RATIO_cma5_diff,lc_sum_OREB_PCT_cma5_diff,lc_sum_DREB_PCT_cma5_diff,lc_sum_REB_PCT_cma5_diff,lc_sum_TM_TOV_PCT_cma5_diff,lc_sum_EFG_PCT_cma5_diff,lc_sum_TS_PCT_cma5_diff,lc_sum_USG_PCT_cma5_diff,lc_sum_E_USG_PCT_cma5_diff,lc_sum_E_PACE_cma5_diff,lc_sum_PACE_cma5_diff,lc_sum_PACE_PER40_cma5_diff,lc_sum_POSS_cma5_diff,lc_sum_PIE_cma5_diff,lc_mean_MIN_cma5_diff,lc_mean_E_OFF_RATING_cma5_diff,lc_mean_OFF_RATING_cma5_diff,lc_mean_E_DEF_RATING_cma5_diff,lc_mean_DEF_RATING_cma5_diff,lc_mean_E_NET_RATING_cma5_diff,lc_mean_NET_RATING_cma5_diff,lc_mean_AST_PCT_cma5_diff,lc_mean_AST_TOV_cma5_diff,lc_mean_AST_RATIO_cma5_diff,lc_mean_OREB_PCT_cma5_diff,lc_mean_DREB_PCT_cma5_diff,lc_mean_REB_PCT_cma5_diff,lc_mean_TM_TOV_PCT_cma5_diff,lc_mean_EFG_PCT_cma5_diff,lc_mean_TS_PCT_cma5_diff,lc_mean_USG_PCT_cma5_diff,lc_mean_E_USG_PCT_cma5_diff,lc_mean_E_PACE_cma5_diff,lc_mean_PACE_cma5_diff,lc_mean_PACE_PER40_cma5_diff,lc_mean_POSS_cma5_diff,lc_mean_PIE_cma5_diff,lc_max_MIN_cma5_diff,lc_max_E_OFF_RATING_cma5_diff,lc_max_OFF_RATING_cma5_diff,lc_max_E_DEF_RATING_cma5_diff,lc_max_DEF_RATING_cma5_diff,lc_max_E_NET_RATING_cma5_diff,lc_max_NET_RATING_cma5_diff,lc_max_AST_PCT_cma5_diff,lc_max_AST_TOV_cma5_diff,lc_max_AST_RATIO_cma5_diff,lc_max_OREB_PCT_cma5_diff,lc_max_DREB_PCT_cma5_diff,lc_max_REB_PCT_cma5_diff,lc_max_TM_TOV_PCT_cma5_diff,lc_max_EFG_PCT_cma5_diff,lc_max_TS_PCT_cma5_diff,lc_max_USG_PCT_cma5_diff,lc_max_E_USG_PCT_cma5_diff,lc_max_E_PACE_cma5_diff,lc_max_PACE_cma5_diff,lc_max_PACE_PER40_cma5_diff,lc_max_POSS_cma5_diff,lc_max_PIE_cma5_diff,lc_sum_MIN_cma12_diff,lc_sum_E_OFF_RATING_cma12_diff,lc_sum_OFF_RATING_cma12_diff,lc_sum_E_DEF_RATING_cma12_diff,lc_sum_DEF_RATING_cma12_diff,lc_sum_E_NET_RATING_cma12_diff,lc_sum_NET_RATING_cma12_diff,lc_sum_AST_PCT_cma12_diff,lc_sum_AST_TOV_cma12_diff,lc_sum_AST_RATIO_cma12_diff,lc_sum_OREB_PCT_cma12_diff,lc_sum_DREB_PCT_cma12_diff,lc_sum_REB_PCT_cma12_diff,lc_sum_TM_TOV_PCT_cma12_diff,lc_sum_EFG_PCT_cma12_diff,lc_sum_TS_PCT_cma12_diff,lc_sum_USG_PCT_cma12_diff,lc_sum_E_USG_PCT_cma12_diff,lc_sum_E_PACE_cma12_diff,lc_sum_PACE_cma12_diff,lc_sum_PACE_PER40_cma12_diff,lc_sum_POSS_cma12_diff,lc_sum_PIE_cma12_diff,lc_mean_MIN_cma12_diff,lc_mean_E_OFF_RATING_cma12_diff,lc_mean_OFF_RATING_cma12_diff,lc_mean_E_DEF_RATING_cma12_diff,lc_mean_DEF_RATING_cma12_diff,lc_mean_E_NET_RATING_cma12_diff,lc_mean_NET_RATING_cma12_diff,lc_mean_AST_PCT_cma12_diff,lc_mean_AST_TOV_cma12_diff,lc_mean_AST_RATIO_cma12_diff,lc_mean_OREB_PCT_cma12_diff,lc_mean_DREB_PCT_cma12_diff,lc_mean_REB_PCT_cma12_diff,lc_mean_TM_TOV_PCT_cma12_diff,lc_mean_EFG_PCT_cma12_diff,lc_mean_TS_PCT_cma12_diff,lc_mean_USG_PCT_cma12_diff,lc_mean_E_USG_PCT_cma12_diff,lc_mean_E_PACE_cma12_diff,lc_mean_PACE_cma12_diff,lc_mean_PACE_PER40_cma12_diff,lc_mean_POSS_cma12_diff,lc_mean_PIE_cma12_diff,lc_max_MIN_cma12_diff,lc_max_E_OFF_RATING_cma12_diff,lc_max_OFF_RATING_cma12_diff,lc_max_E_DEF_RATING_cma12_diff,lc_max_DEF_RATING_cma12_diff,lc_max_E_NET_RATING_cma12_diff,lc_max_NET_RATING_cma12_diff,lc_max_AST_PCT_cma12_diff,lc_max_AST_TOV_cma12_diff,lc_max_AST_RATIO_cma12_diff,lc_max_OREB_PCT_cma12_diff,lc_max_DREB_PCT_cma12_diff,lc_max_REB_PCT_cma12_diff,lc_max_TM_TOV_PCT_cma12_diff,lc_max_EFG_PCT_cma12_diff,lc_max_TS_PCT_cma12_diff,lc_max_USG_PCT_cma12_diff,lc_max_E_USG_PCT_cma12_diff,lc_max_E_PACE_cma12_diff,lc_max_PACE_cma12_diff,lc_max_PACE_PER40_cma12_diff,lc_max_POSS_cma12_diff,lc_max_PIE_cma12_diff,lc_sum_MIN_cma999_diff,lc_sum_E_OFF_RATING_cma999_diff,lc_sum_OFF_RATING_cma999_diff,lc_sum_E_DEF_RATING_cma999_diff,lc_sum_DEF_RATING_cma999_diff,lc_sum_E_NET_RATING_cma999_diff,lc_sum_NET_RATING_cma999_diff,lc_sum_AST_PCT_cma999_diff,lc_sum_AST_TOV_cma999_diff,lc_sum_AST_RATIO_cma999_diff,lc_sum_OREB_PCT_cma999_diff,lc_sum_DREB_PCT_cma999_diff,lc_sum_REB_PCT_cma999_diff,lc_sum_TM_TOV_PCT_cma999_diff,lc_sum_EFG_PCT_cma999_diff,lc_sum_TS_PCT_cma999_diff,lc_sum_USG_PCT_cma999_diff,lc_sum_E_USG_PCT_cma999_diff,lc_sum_E_PACE_cma999_diff,lc_sum_PACE_cma999_diff,lc_sum_PACE_PER40_cma999_diff,lc_sum_POSS_cma999_diff,lc_sum_PIE_cma999_diff,lc_mean_MIN_cma999_diff,lc_mean_E_OFF_RATING_cma999_diff,lc_mean_OFF_RATING_cma999_diff,lc_mean_E_DEF_RATING_cma999_diff,lc_mean_DEF_RATING_cma999_diff,lc_mean_E_NET_RATING_cma999_diff,lc_mean_NET_RATING_cma999_diff,lc_mean_AST_PCT_cma999_diff,lc_mean_AST_TOV_cma999_diff,lc_mean_AST_RATIO_cma999_diff,lc_mean_OREB_PCT_cma999_diff,lc_mean_DREB_PCT_cma999_diff,lc_mean_REB_PCT_cma999_diff,lc_mean_TM_TOV_PCT_cma999_diff,lc_mean_EFG_PCT_cma999_diff,lc_mean_TS_PCT_cma999_diff,lc_mean_USG_PCT_cma999_diff,lc_mean_E_USG_PCT_cma999_diff,lc_mean_E_PACE_cma999_diff,lc_mean_PACE_cma999_diff,lc_mean_PACE_PER40_cma999_diff,lc_mean_POSS_cma999_diff,lc_mean_PIE_cma999_diff,lc_max_MIN_cma999_diff,lc_max_E_OFF_RATING_cma999_diff,lc_max_OFF_RATING_cma999_diff,lc_max_E_DEF_RATING_cma999_diff,lc_max_DEF_RATING_cma999_diff,lc_max_E_NET_RATING_cma999_diff,lc_max_NET_RATING_cma999_diff,lc_max_AST_PCT_cma999_diff,lc_max_AST_TOV_cma999_diff,lc_max_AST_RATIO_cma999_diff,lc_max_OREB_PCT_cma999_diff,lc_max_DREB_PCT_cma999_diff,lc_max_REB_PCT_cma999_diff,lc_max_TM_TOV_PCT_cma999_diff,lc_max_EFG_PCT_cma999_diff,lc_max_TS_PCT_cma999_diff,lc_max_USG_PCT_cma999_diff,lc_max_E_USG_PCT_cma999_diff,lc_max_E_PACE_cma999_diff,lc_max_PACE_cma999_diff,lc_max_PACE_PER40_cma999_diff,lc_max_POSS_cma999_diff,lc_max_PIE_cma999_diff,lc_sum_MIN_cmax5_diff,lc_sum_E_OFF_RATING_cmax5_diff,lc_sum_OFF_RATING_cmax5_diff,lc_sum_E_DEF_RATING_cmax5_diff,lc_sum_DEF_RATING_cmax5_diff,lc_sum_E_NET_RATING_cmax5_diff,lc_sum_NET_RATING_cmax5_diff,lc_sum_AST_PCT_cmax5_diff,lc_sum_AST_TOV_cmax5_diff,lc_sum_AST_RATIO_cmax5_diff,lc_sum_OREB_PCT_cmax5_diff,lc_sum_DREB_PCT_cmax5_diff,lc_sum_REB_PCT_cmax5_diff,lc_sum_TM_TOV_PCT_cmax5_diff,lc_sum_EFG_PCT_cmax5_diff,lc_sum_TS_PCT_cmax5_diff,lc_sum_USG_PCT_cmax5_diff,lc_sum_E_USG_PCT_cmax5_diff,lc_sum_E_PACE_cmax5_diff,lc_sum_PACE_cmax5_diff,lc_sum_PACE_PER40_cmax5_diff,lc_sum_POSS_cmax5_diff,lc_sum_PIE_cmax5_diff,lc_mean_MIN_cmax5_diff,lc_mean_E_OFF_RATING_cmax5_diff,lc_mean_OFF_RATING_cmax5_diff,lc_mean_E_DEF_RATING_cmax5_diff,lc_mean_DEF_RATING_cmax5_diff,lc_mean_E_NET_RATING_cmax5_diff,lc_mean_NET_RATING_cmax5_diff,lc_mean_AST_PCT_cmax5_diff,lc_mean_AST_TOV_cmax5_diff,lc_mean_AST_RATIO_cmax5_diff,lc_mean_OREB_PCT_cmax5_diff,lc_mean_DREB_PCT_cmax5_diff,lc_mean_REB_PCT_cmax5_diff,lc_mean_TM_TOV_PCT_cmax5_diff,lc_mean_EFG_PCT_cmax5_diff,lc_mean_TS_PCT_cmax5_diff,lc_mean_USG_PCT_cmax5_diff,lc_mean_E_USG_PCT_cmax5_diff,lc_mean_E_PACE_cmax5_diff,lc_mean_PACE_cmax5_diff,lc_mean_PACE_PER40_cmax5_diff,lc_mean_POSS_cmax5_diff,lc_mean_PIE_cmax5_diff,lc_max_MIN_cmax5_diff,lc_max_E_OFF_RATING_cmax5_diff,lc_max_OFF_RATING_cmax5_diff,lc_max_E_DEF_RATING_cmax5_diff,lc_max_DEF_RATING_cmax5_diff,lc_max_E_NET_RATING_cmax5_diff,lc_max_NET_RATING_cmax5_diff,lc_max_AST_PCT_cmax5_diff,lc_max_AST_TOV_cmax5_diff,lc_max_AST_RATIO_cmax5_diff,lc_max_OREB_PCT_cmax5_diff,lc_max_DREB_PCT_cmax5_diff,lc_max_REB_PCT_cmax5_diff,lc_max_TM_TOV_PCT_cmax5_diff,lc_max_EFG_PCT_cmax5_diff,lc_max_TS_PCT_cmax5_diff,lc_max_USG_PCT_cmax5_diff,lc_max_E_USG_PCT_cmax5_diff,lc_max_E_PACE_cmax5_diff,lc_max_PACE_cmax5_diff,lc_max_PACE_PER40_cmax5_diff,lc_max_POSS_cmax5_diff,lc_max_PIE_cmax5_diff,lc_sum_MIN_cmax12_diff,lc_sum_E_OFF_RATING_cmax12_diff,lc_sum_OFF_RATING_cmax12_diff,lc_sum_E_DEF_RATING_cmax12_diff,lc_sum_DEF_RATING_cmax12_diff,lc_sum_E_NET_RATING_cmax12_diff,lc_sum_NET_RATING_cmax12_diff,lc_sum_AST_PCT_cmax12_diff,lc_sum_AST_TOV_cmax12_diff,lc_sum_AST_RATIO_cmax12_diff,lc_sum_OREB_PCT_cmax12_diff,lc_sum_DREB_PCT_cmax12_diff,lc_sum_REB_PCT_cmax12_diff,lc_sum_TM_TOV_PCT_cmax12_diff,lc_sum_EFG_PCT_cmax12_diff,lc_sum_TS_PCT_cmax12_diff,lc_sum_USG_PCT_cmax12_diff,lc_sum_E_USG_PCT_cmax12_diff,lc_sum_E_PACE_cmax12_diff,lc_sum_PACE_cmax12_diff,lc_sum_PACE_PER40_cmax12_diff,lc_sum_POSS_cmax12_diff,lc_sum_PIE_cmax12_diff,lc_mean_MIN_cmax12_diff,lc_mean_E_OFF_RATING_cmax12_diff,lc_mean_OFF_RATING_cmax12_diff,lc_mean_E_DEF_RATING_cmax12_diff,lc_mean_DEF_RATING_cmax12_diff,lc_mean_E_NET_RATING_cmax12_diff,lc_mean_NET_RATING_cmax12_diff,lc_mean_AST_PCT_cmax12_diff,lc_mean_AST_TOV_cmax12_diff,lc_mean_AST_RATIO_cmax12_diff,lc_mean_OREB_PCT_cmax12_diff,lc_mean_DREB_PCT_cmax12_diff,lc_mean_REB_PCT_cmax12_diff,lc_mean_TM_TOV_PCT_cmax12_diff,lc_mean_EFG_PCT_cmax12_diff,lc_mean_TS_PCT_cmax12_diff,lc_mean_USG_PCT_cmax12_diff,lc_mean_E_USG_PCT_cmax12_diff,lc_mean_E_PACE_cmax12_diff,lc_mean_PACE_cmax12_diff,lc_mean_PACE_PER40_cmax12_diff,lc_mean_POSS_cmax12_diff,lc_mean_PIE_cmax12_diff,lc_max_MIN_cmax12_diff,lc_max_E_OFF_RATING_cmax12_diff,lc_max_OFF_RATING_cmax12_diff,lc_max_E_DEF_RATING_cmax12_diff,lc_max_DEF_RATING_cmax12_diff,lc_max_E_NET_RATING_cmax12_diff,lc_max_NET_RATING_cmax12_diff,lc_max_AST_PCT_cmax12_diff,lc_max_AST_TOV_cmax12_diff,lc_max_AST_RATIO_cmax12_diff,lc_max_OREB_PCT_cmax12_diff,lc_max_DREB_PCT_cmax12_diff,lc_max_REB_PCT_cmax12_diff,lc_max_TM_TOV_PCT_cmax12_diff,lc_max_EFG_PCT_cmax12_diff,lc_max_TS_PCT_cmax12_diff,lc_max_USG_PCT_cmax12_diff,lc_max_E_USG_PCT_cmax12_diff,lc_max_E_PACE_cmax12_diff,lc_max_PACE_cmax12_diff,lc_max_PACE_PER40_cmax12_diff,lc_max_POSS_cmax12_diff,lc_max_PIE_cmax12_diff,lc_sum_MIN_cmax999_diff,lc_sum_E_OFF_RATING_cmax999_diff,lc_sum_OFF_RATING_cmax999_diff,lc_sum_E_DEF_RATING_cmax999_diff,lc_sum_DEF_RATING_cmax999_diff,lc_sum_E_NET_RATING_cmax999_diff,lc_sum_NET_RATING_cmax999_diff,lc_sum_AST_PCT_cmax999_diff,lc_sum_AST_TOV_cmax999_diff,lc_sum_AST_RATIO_cmax999_diff,lc_sum_OREB_PCT_cmax999_diff,lc_sum_DREB_PCT_cmax999_diff,lc_sum_REB_PCT_cmax999_diff,lc_sum_TM_TOV_PCT_cmax999_diff,lc_sum_EFG_PCT_cmax999_diff,lc_sum_TS_PCT_cmax999_diff,lc_sum_USG_PCT_cmax999_diff,lc_sum_E_USG_PCT_cmax999_diff,lc_sum_E_PACE_cmax999_diff,lc_sum_PACE_cmax999_diff,lc_sum_PACE_PER40_cmax999_diff,lc_sum_POSS_cmax999_diff,lc_sum_PIE_cmax999_diff,lc_mean_MIN_cmax999_diff,lc_mean_E_OFF_RATING_cmax999_diff,lc_mean_OFF_RATING_cmax999_diff,lc_mean_E_DEF_RATING_cmax999_diff,lc_mean_DEF_RATING_cmax999_diff,lc_mean_E_NET_RATING_cmax999_diff,lc_mean_NET_RATING_cmax999_diff,lc_mean_AST_PCT_cmax999_diff,lc_mean_AST_TOV_cmax999_diff,lc_mean_AST_RATIO_cmax999_diff,lc_mean_OREB_PCT_cmax999_diff,lc_mean_DREB_PCT_cmax999_diff,lc_mean_REB_PCT_cmax999_diff,lc_mean_TM_TOV_PCT_cmax999_diff,lc_mean_EFG_PCT_cmax999_diff,lc_mean_TS_PCT_cmax999_diff,lc_mean_USG_PCT_cmax999_diff,lc_mean_E_USG_PCT_cmax999_diff,lc_mean_E_PACE_cmax999_diff,lc_mean_PACE_cmax999_diff,lc_mean_PACE_PER40_cmax999_diff,lc_mean_POSS_cmax999_diff,lc_mean_PIE_cmax999_diff,lc_max_MIN_cmax999_diff,lc_max_E_OFF_RATING_cmax999_diff,lc_max_OFF_RATING_cmax999_diff,lc_max_E_DEF_RATING_cmax999_diff,lc_max_DEF_RATING_cmax999_diff,lc_max_E_NET_RATING_cmax999_diff,lc_max_NET_RATING_cmax999_diff,lc_max_AST_PCT_cmax999_diff,lc_max_AST_TOV_cmax999_diff,lc_max_AST_RATIO_cmax999_diff,lc_max_OREB_PCT_cmax999_diff,lc_max_DREB_PCT_cmax999_diff,lc_max_REB_PCT_cmax999_diff,lc_max_TM_TOV_PCT_cmax999_diff,lc_max_EFG_PCT_cmax999_diff,lc_max_TS_PCT_cmax999_diff,lc_max_USG_PCT_cmax999_diff,lc_max_E_USG_PCT_cmax999_diff,lc_max_E_PACE_cmax999_diff,lc_max_PACE_cmax999_diff,lc_max_PACE_PER40_cmax999_diff,lc_max_POSS_cmax999_diff,lc_max_PIE_cmax999_diff,MIN_a,duration_a,MIN_b,duration_b,E_OFF_RATING_cma5_diff,OFF_RATING_cma5_diff,E_DEF_RATING_cma5_diff,DEF_RATING_cma5_diff,E_NET_RATING_cma5_diff,NET_RATING_cma5_diff,AST_PCT_cma5_diff,AST_TOV_cma5_diff,AST_RATIO_cma5_diff,OREB_PCT_cma5_diff,DREB_PCT_cma5_diff,REB_PCT_cma5_diff,E_TM_TOV_PCT_cma5_diff,TM_TOV_PCT_cma5_diff,EFG_PCT_cma5_diff,TS_PCT_cma5_diff,USG_PCT_cma5_diff,E_USG_PCT_cma5_diff,E_PACE_cma5_diff,PACE_cma5_diff,PACE_PER40_cma5_diff,POSS_cma5_diff,PIE_cma5_diff,duration_minutes_cma5_diff,w_pct_cma5_diff,min_cma5_diff,fgm_cma5_diff,fga_cma5_diff,fg_pct_cma5_diff,fg3m_cma5_diff,fg3a_cma5_diff,fg3_pct_cma5_diff,ftm_cma5_diff,fta_cma5_diff,ft_pct_cma5_diff,oreb_cma5_diff,dreb_cma5_diff,reb_cma5_diff,ast_cma5_diff,stl_cma5_diff,blk_cma5_diff,tov_cma5_diff,pf_cma5_diff,pts_cma5_diff,spread_cma5_diff,away_home__cma5_diff,E_OFF_RATING_cma12_diff,OFF_RATING_cma12_diff,E_DEF_RATING_cma12_diff,DEF_RATING_cma12_diff,E_NET_RATING_cma12_diff,NET_RATING_cma12_diff,AST_PCT_cma12_diff,AST_TOV_cma12_diff,AST_RATIO_cma12_diff,OREB_PCT_cma12_diff,DREB_PCT_cma12_diff,REB_PCT_cma12_diff,E_TM_TOV_PCT_cma12_diff,TM_TOV_PCT_cma12_diff,EFG_PCT_cma12_diff,TS_PCT_cma12_diff,USG_PCT_cma12_diff,E_USG_PCT_cma12_diff,E_PACE_cma12_diff,PACE_cma12_diff,PACE_PER40_cma12_diff,POSS_cma12_diff,PIE_cma12_diff,duration_minutes_cma12_diff,w_pct_cma12_diff,min_cma12_diff,fgm_cma12_diff,fga_cma12_diff,fg_pct_cma12_diff,fg3m_cma12_diff,fg3a_cma12_diff,fg3_pct_cma12_diff,ftm_cma12_diff,fta_cma12_diff,ft_pct_cma12_diff,oreb_cma12_diff,dreb_cma12_diff,reb_cma12_diff,ast_cma12_diff,stl_cma12_diff,blk_cma12_diff,tov_cma12_diff,pf_cma12_diff,pts_cma12_diff,spread_cma12_diff,away_home__cma12_diff,E_OFF_RATING_cma999_diff,OFF_RATING_cma999_diff,E_DEF_RATING_cma999_diff,DEF_RATING_cma999_diff,E_NET_RATING_cma999_diff,NET_RATING_cma999_diff,AST_PCT_cma999_diff,AST_TOV_cma999_diff,AST_RATIO_cma999_diff,OREB_PCT_cma999_diff,DREB_PCT_cma999_diff,REB_PCT_cma999_diff,E_TM_TOV_PCT_cma999_diff,TM_TOV_PCT_cma999_diff,EFG_PCT_cma999_diff,TS_PCT_cma999_diff,USG_PCT_cma999_diff,E_USG_PCT_cma999_diff,E_PACE_cma999_diff,PACE_cma999_diff,PACE_PER40_cma999_diff,POSS_cma999_diff,PIE_cma999_diff,duration_minutes_cma999_diff,w_pct_cma999_diff,min_cma999_diff,fgm_cma999_diff,fga_cma999_diff,fg_pct_cma999_diff,fg3m_cma999_diff,fg3a_cma999_diff,fg3_pct_cma999_diff,ftm_cma999_diff,fta_cma999_diff,ft_pct_cma999_diff,oreb_cma999_diff,dreb_cma999_diff,reb_cma999_diff,ast_cma999_diff,stl_cma999_diff,blk_cma999_diff,tov_cma999_diff,pf_cma999_diff,pts_cma999_diff,spread_cma999_diff,away_home__cma999_diff,E_OFF_RATING_cmax5_diff,OFF_RATING_cmax5_diff,E_DEF_RATING_cmax5_diff,DEF_RATING_cmax5_diff,E_NET_RATING_cmax5_diff,NET_RATING_cmax5_diff,AST_PCT_cmax5_diff,AST_TOV_cmax5_diff,AST_RATIO_cmax5_diff,OREB_PCT_cmax5_diff,DREB_PCT_cmax5_diff,REB_PCT_cmax5_diff,E_TM_TOV_PCT_cmax5_diff,TM_TOV_PCT_cmax5_diff,EFG_PCT_cmax5_diff,TS_PCT_cmax5_diff,USG_PCT_cmax5_diff,E_USG_PCT_cmax5_diff,E_PACE_cmax5_diff,PACE_cmax5_diff,PACE_PER40_cmax5_diff,POSS_cmax5_diff,PIE_cmax5_diff,duration_minutes_cmax5_diff,w_pct_cmax5_diff,min_cmax5_diff,fgm_cmax5_diff,fga_cmax5_diff,fg_pct_cmax5_diff,fg3m_cmax5_diff,fg3a_cmax5_diff,fg3_pct_cmax5_diff,ftm_cmax5_diff,fta_cmax5_diff,ft_pct_cmax5_diff,oreb_cmax5_diff,dreb_cmax5_diff,reb_cmax5_diff,ast_cmax5_diff,stl_cmax5_diff,blk_cmax5_diff,tov_cmax5_diff,pf_cmax5_diff,pts_cmax5_diff,spread_cmax5_diff,away_home__cmax5_diff,E_OFF_RATING_cmax12_diff,OFF_RATING_cmax12_diff,E_DEF_RATING_cmax12_diff,DEF_RATING_cmax12_diff,E_NET_RATING_cmax12_diff,NET_RATING_cmax12_diff,AST_PCT_cmax12_diff,AST_TOV_cmax12_diff,AST_RATIO_cmax12_diff,OREB_PCT_cmax12_diff,DREB_PCT_cmax12_diff,REB_PCT_cmax12_diff,E_TM_TOV_PCT_cmax12_diff,TM_TOV_PCT_cmax12_diff,EFG_PCT_cmax12_diff,TS_PCT_cmax12_diff,USG_PCT_cmax12_diff,E_USG_PCT_cmax12_diff,E_PACE_cmax12_diff,PACE_cmax12_diff,PACE_PER40_cmax12_diff,POSS_cmax12_diff,PIE_cmax12_diff,duration_minutes_cmax12_diff,w_pct_cmax12_diff,min_cmax12_diff,fgm_cmax12_diff,fga_cmax12_diff,fg_pct_cmax12_diff,fg3m_cmax12_diff,fg3a_cmax12_diff,fg3_pct_cmax12_diff,ftm_cmax12_diff,fta_cmax12_diff,ft_pct_cmax12_diff,oreb_cmax12_diff,dreb_cmax12_diff,reb_cmax12_diff,ast_cmax12_diff,stl_cmax12_diff,blk_cmax12_diff,tov_cmax12_diff,pf_cmax12_diff,pts_cmax12_diff,spread_cmax12_diff,away_home__cmax12_diff,E_OFF_RATING_cmax999_diff,OFF_RATING_cmax999_diff,E_DEF_RATING_cmax999_diff,DEF_RATING_cmax999_diff,E_NET_RATING_cmax999_diff,NET_RATING_cmax999_diff,AST_PCT_cmax999_diff,AST_TOV_cmax999_diff,AST_RATIO_cmax999_diff,OREB_PCT_cmax999_diff,DREB_PCT_cmax999_diff,REB_PCT_cmax999_diff,E_TM_TOV_PCT_cmax999_diff,TM_TOV_PCT_cmax999_diff,EFG_PCT_cmax999_diff,TS_PCT_cmax999_diff,USG_PCT_cmax999_diff,E_USG_PCT_cmax999_diff,E_PACE_cmax999_diff,PACE_cmax999_diff,PACE_PER40_cmax999_diff,POSS_cmax999_diff,PIE_cmax999_diff,duration_minutes_cmax999_diff,w_pct_cmax999_diff,min_cmax999_diff,fgm_cmax999_diff,fga_cmax999_diff,fg_pct_cmax999_diff,fg3m_cmax999_diff,fg3a_cmax999_diff,fg3_pct_cmax999_diff,ftm_cmax999_diff,fta_cmax999_diff,ft_pct_cmax999_diff,oreb_cmax999_diff,dreb_cmax999_diff,reb_cmax999_diff,ast_cmax999_diff,stl_cmax999_diff,blk_cmax999_diff,tov_cmax999_diff,pf_cmax999_diff,pts_cmax999_diff,spread_cmax999_diff,away_home__cmax999_diff,E_OFF_RATING_sm_cma12_diff,OFF_RATING_sm_cma12_diff,E_DEF_RATING_sm_cma12_diff,DEF_RATING_sm_cma12_diff,E_NET_RATING_sm_cma12_diff,NET_RATING_sm_cma12_diff,AST_PCT_sm_cma12_diff,AST_TOV_sm_cma12_diff,AST_RATIO_sm_cma12_diff,OREB_PCT_sm_cma12_diff,DREB_PCT_sm_cma12_diff,REB_PCT_sm_cma12_diff,E_TM_TOV_PCT_sm_cma12_diff,TM_TOV_PCT_sm_cma12_diff,EFG_PCT_sm_cma12_diff,TS_PCT_sm_cma12_diff,USG_PCT_sm_cma12_diff,E_USG_PCT_sm_cma12_diff,E_PACE_sm_cma12_diff,PACE_sm_cma12_diff,PACE_PER40_sm_cma12_diff,POSS_sm_cma12_diff,PIE_sm_cma12_diff,duration_minutes_sm_cma12_diff,w_pct_sm_cma12_diff,min_sm_cma12_diff,fgm_sm_cma12_diff,fga_sm_cma12_diff,fg_pct_sm_cma12_diff,fg3m_sm_cma12_diff,fg3a_sm_cma12_diff,fg3_pct_sm_cma12_diff,ftm_sm_cma12_diff,fta_sm_cma12_diff,ft_pct_sm_cma12_diff,oreb_sm_cma12_diff,dreb_sm_cma12_diff,reb_sm_cma12_diff,ast_sm_cma12_diff,stl_sm_cma12_diff,blk_sm_cma12_diff,tov_sm_cma12_diff,pf_sm_cma12_diff,pts_sm_cma12_diff,spread_sm_cma12_diff,away_home_sm_cma12_diff,E_OFF_RATING_sm_cmax12_diff,OFF_RATING_sm_cmax12_diff,E_DEF_RATING_sm_cmax12_diff,DEF_RATING_sm_cmax12_diff,E_NET_RATING_sm_cmax12_diff,NET_RATING_sm_cmax12_diff,AST_PCT_sm_cmax12_diff,AST_TOV_sm_cmax12_diff,AST_RATIO_sm_cmax12_diff,OREB_PCT_sm_cmax12_diff,DREB_PCT_sm_cmax12_diff,REB_PCT_sm_cmax12_diff,E_TM_TOV_PCT_sm_cmax12_diff,TM_TOV_PCT_sm_cmax12_diff,EFG_PCT_sm_cmax12_diff,TS_PCT_sm_cmax12_diff,USG_PCT_sm_cmax12_diff,E_USG_PCT_sm_cmax12_diff,E_PACE_sm_cmax12_diff,PACE_sm_cmax12_diff,PACE_PER40_sm_cmax12_diff,POSS_sm_cmax12_diff,PIE_sm_cmax12_diff,duration_minutes_sm_cmax12_diff,w_pct_sm_cmax12_diff,min_sm_cmax12_diff,fgm_sm_cmax12_diff,fga_sm_cmax12_diff,fg_pct_sm_cmax12_diff,fg3m_sm_cmax12_diff,fg3a_sm_cmax12_diff,fg3_pct_sm_cmax12_diff,ftm_sm_cmax12_diff,fta_sm_cmax12_diff,ft_pct_sm_cmax12_diff,oreb_sm_cmax12_diff,dreb_sm_cmax12_diff,reb_sm_cmax12_diff,ast_sm_cmax12_diff,stl_sm_cmax12_diff,blk_sm_cmax12_diff,tov_sm_cmax12_diff,pf_sm_cmax12_diff,pts_sm_cmax12_diff,spread_sm_cmax12_diff,away_home_sm_cmax12_diff,E_OFF_RATING_cma_sm_cmax12_diff,OFF_RATING_cma_sm_cmax12_diff,E_DEF_RATING_cma_sm_cmax12_diff,DEF_RATING_cma_sm_cmax12_diff,E_NET_RATING_cma_sm_cmax12_diff,NET_RATING_cma_sm_cmax12_diff,AST_PCT_cma_sm_cmax12_diff,AST_TOV_cma_sm_cmax12_diff,AST_RATIO_cma_sm_cmax12_diff,OREB_PCT_cma_sm_cmax12_diff,DREB_PCT_cma_sm_cmax12_diff,REB_PCT_cma_sm_cmax12_diff,E_TM_TOV_PCT_cma_sm_cmax12_diff,TM_TOV_PCT_cma_sm_cmax12_diff,EFG_PCT_cma_sm_cmax12_diff,TS_PCT_cma_sm_cmax12_diff,USG_PCT_cma_sm_cmax12_diff,E_USG_PCT_cma_sm_cmax12_diff,E_PACE_cma_sm_cmax12_diff,PACE_cma_sm_cmax12_diff,PACE_PER40_cma_sm_cmax12_diff,POSS_cma_sm_cmax12_diff,PIE_cma_sm_cmax12_diff,duration_minutes_cma_sm_cmax12_diff,w_pct_cma_sm_cmax12_diff,min_cma_sm_cmax12_diff,fgm_cma_sm_cmax12_diff,fga_cma_sm_cmax12_diff,fg_pct_cma_sm_cmax12_diff,fg3m_cma_sm_cmax12_diff,fg3a_cma_sm_cmax1

In [5]:
datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)

datapath_df = os.path.join(datapath, '61merge_60_away_home_a_59_lost_contribution___stat_cma5_12_999_cmax5_12_999_diff___stat_seaon_matchup_cma12_cmax12_diff.csv')
if not os.path.exists(datapath_df):
    df_merged.to_csv(datapath_df, index=False)

In [6]:
df_readback = rcp('61merge_60_away_home_a_59_lost_contribution___stat_cma5_12_999_cmax5_12_999_diff___stat_seaon_matchup_cma12_cmax12_diff.csv')
p(df_readback)

(10266, 866)

,game_id,team_id_a,team_id_b,away_home_a,TEAM_ABBREVIATION_a,game_date,season,TEAM_ABBREVIATION_b,losses_diff,wins_diff,win_pct_diff,opp_win_pct_diff,opp_losses_diff,opp_wins_diff,opp_opps_losses_diff,opp_opps_wins_diff,opp_opps_win_pct_diff,strength_of_schedule_diff,season_type,season_year,Team_a,TEAM_NAME_a,TEAM_CITY_a,wl_a,matchup_a,a_a,b_a,Team_b,TEAM_NAME_b,TEAM_CITY_b,wl_b,matchup_b,a_b,b_b,lc_sum_MIN_cma5_diff,lc_sum_E_OFF_RATING_cma5_diff,lc_sum_OFF_RATING_cma5_diff,lc_sum_E_DEF_RATING_cma5_diff,lc_sum_DEF_RATING_cma5_diff,lc_sum_E_NET_RATING_cma5_diff,lc_sum_NET_RATING_cma5_diff,lc_sum_AST_PCT_cma5_diff,lc_sum_AST_TOV_cma5_diff,lc_sum_AST_RATIO_cma5_diff,lc_sum_OREB_PCT_cma5_diff,lc_sum_DREB_PCT_cma5_diff,lc_sum_REB_PCT_cma5_diff,lc_sum_TM_TOV_PCT_cma5_diff,lc_sum_EFG_PCT_cma5_diff,lc_sum_TS_PCT_cma5_diff,lc_sum_USG_PCT_cma5_diff,lc_sum_E_USG_PCT_cma5_diff,lc_sum_E_PACE_cma5_diff,lc_sum_PACE_cma5_diff,lc_sum_PACE_PER40_cma5_diff,lc_sum_POSS_cma5_diff,lc_sum_PIE_cma5_diff,lc_mean_MIN_cma5_diff,lc_mean_E_OFF_RATING_cma5_diff,lc_mean_OFF_RATING_cma5_diff,lc_mean_E_DEF_RATING_cma5_diff,lc_mean_DEF_RATING_cma5_diff,lc_mean_E_NET_RATING_cma5_diff,lc_mean_NET_RATING_cma5_diff,lc_mean_AST_PCT_cma5_diff,lc_mean_AST_TOV_cma5_diff,lc_mean_AST_RATIO_cma5_diff,lc_mean_OREB_PCT_cma5_diff,lc_mean_DREB_PCT_cma5_diff,lc_mean_REB_PCT_cma5_diff,lc_mean_TM_TOV_PCT_cma5_diff,lc_mean_EFG_PCT_cma5_diff,lc_mean_TS_PCT_cma5_diff,lc_mean_USG_PCT_cma5_diff,lc_mean_E_USG_PCT_cma5_diff,lc_mean_E_PACE_cma5_diff,lc_mean_PACE_cma5_diff,lc_mean_PACE_PER40_cma5_diff,lc_mean_POSS_cma5_diff,lc_mean_PIE_cma5_diff,lc_max_MIN_cma5_diff,lc_max_E_OFF_RATING_cma5_diff,lc_max_OFF_RATING_cma5_diff,lc_max_E_DEF_RATING_cma5_diff,lc_max_DEF_RATING_cma5_diff,lc_max_E_NET_RATING_cma5_diff,lc_max_NET_RATING_cma5_diff,lc_max_AST_PCT_cma5_diff,lc_max_AST_TOV_cma5_diff,lc_max_AST_RATIO_cma5_diff,lc_max_OREB_PCT_cma5_diff,lc_max_DREB_PCT_cma5_diff,lc_max_REB_PCT_cma5_diff,lc_max_TM_TOV_PCT_cma5_diff,lc_max_EFG_PCT_cma5_diff,lc_max_TS_PCT_cma5_diff,lc_max_USG_PCT_cma5_diff,lc_max_E_USG_PCT_cma5_diff,lc_max_E_PACE_cma5_diff,lc_max_PACE_cma5_diff,lc_max_PACE_PER40_cma5_diff,lc_max_POSS_cma5_diff,lc_max_PIE_cma5_diff,lc_sum_MIN_cma12_diff,lc_sum_E_OFF_RATING_cma12_diff,lc_sum_OFF_RATING_cma12_diff,lc_sum_E_DEF_RATING_cma12_diff,lc_sum_DEF_RATING_cma12_diff,lc_sum_E_NET_RATING_cma12_diff,lc_sum_NET_RATING_cma12_diff,lc_sum_AST_PCT_cma12_diff,lc_sum_AST_TOV_cma12_diff,lc_sum_AST_RATIO_cma12_diff,lc_sum_OREB_PCT_cma12_diff,lc_sum_DREB_PCT_cma12_diff,lc_sum_REB_PCT_cma12_diff,lc_sum_TM_TOV_PCT_cma12_diff,lc_sum_EFG_PCT_cma12_diff,lc_sum_TS_PCT_cma12_diff,lc_sum_USG_PCT_cma12_diff,lc_sum_E_USG_PCT_cma12_diff,lc_sum_E_PACE_cma12_diff,lc_sum_PACE_cma12_diff,lc_sum_PACE_PER40_cma12_diff,lc_sum_POSS_cma12_diff,lc_sum_PIE_cma12_diff,lc_mean_MIN_cma12_diff,lc_mean_E_OFF_RATING_cma12_diff,lc_mean_OFF_RATING_cma12_diff,lc_mean_E_DEF_RATING_cma12_diff,lc_mean_DEF_RATING_cma12_diff,lc_mean_E_NET_RATING_cma12_diff,lc_mean_NET_RATING_cma12_diff,lc_mean_AST_PCT_cma12_diff,lc_mean_AST_TOV_cma12_diff,lc_mean_AST_RATIO_cma12_diff,lc_mean_OREB_PCT_cma12_diff,lc_mean_DREB_PCT_cma12_diff,lc_mean_REB_PCT_cma12_diff,lc_mean_TM_TOV_PCT_cma12_diff,lc_mean_EFG_PCT_cma12_diff,lc_mean_TS_PCT_cma12_diff,lc_mean_USG_PCT_cma12_diff,lc_mean_E_USG_PCT_cma12_diff,lc_mean_E_PACE_cma12_diff,lc_mean_PACE_cma12_diff,lc_mean_PACE_PER40_cma12_diff,lc_mean_POSS_cma12_diff,lc_mean_PIE_cma12_diff,lc_max_MIN_cma12_diff,lc_max_E_OFF_RATING_cma12_diff,lc_max_OFF_RATING_cma12_diff,lc_max_E_DEF_RATING_cma12_diff,lc_max_DEF_RATING_cma12_diff,lc_max_E_NET_RATING_cma12_diff,lc_max_NET_RATING_cma12_diff,lc_max_AST_PCT_cma12_diff,lc_max_AST_TOV_cma12_diff,lc_max_AST_RATIO_cma12_diff,lc_max_OREB_PCT_cma12_diff,lc_max_DREB_PCT_cma12_diff,lc_max_REB_PCT_cma12_diff,lc_max_TM_TOV_PCT_cma12_diff,lc_max_EFG_PCT_cma12_diff,lc_max_TS_PCT_cma12_diff,lc_max_USG_PCT_cma12_diff,lc_max_E_USG_PCT_cma12_diff,lc_max_E_PACE_cma12_diff,lc_max_PACE_cma12_diff,lc_max_PACE_PER40_cma12_diff,lc_max_POSS_cma12_diff,lc_max_PIE_cma12_diff,lc_sum_MIN_cma999_diff,lc_sum_E_OFF_RATING_cma999_diff,lc_sum_OFF_RATING_cma999_diff,lc_sum_E_DEF_RATING_cma999_diff,lc_sum_DEF_RATING_cma999_diff,lc_sum_E_NET_RATING_cma999_diff,lc_sum_NET_RATING_cma999_diff,lc_sum_AST_PCT_cma999_diff,lc_sum_AST_TOV_cma999_diff,lc_sum_AST_RATIO_cma999_diff,lc_sum_OREB_PCT_cma999_diff,lc_sum_DREB_PCT_cma999_diff,lc_sum_REB_PCT_cma999_diff,lc_sum_TM_TOV_PCT_cma999_diff,lc_sum_EFG_PCT_cma999_diff,lc_sum_TS_PCT_cma999_diff,lc_sum_USG_PCT_cma999_diff,lc_sum_E_USG_PCT_cma999_diff,lc_sum_E_PACE_cma999_diff,lc_sum_PACE_cma999_diff,lc_sum_PACE_PER40_cma999_diff,lc_sum_POSS_cma999_diff,lc_sum_PIE_cma999_diff,lc_mean_MIN_cma999_diff,lc_mean_E_OFF_RATING_cma999_diff,lc_mean_OFF_RATING_cma999_diff,lc_mean_E_DEF_RATING_cma999_diff,lc_mean_DEF_RATING_cma999_diff,lc_mean_E_NET_RATING_cma999_diff,lc_mean_NET_RATING_cma999_diff,lc_mean_AST_PCT_cma999_diff,lc_mean_AST_TOV_cma999_diff,lc_mean_AST_RATIO_cma999_diff,lc_mean_OREB_PCT_cma999_diff,lc_mean_DREB_PCT_cma999_diff,lc_mean_REB_PCT_cma999_diff,lc_mean_TM_TOV_PCT_cma999_diff,lc_mean_EFG_PCT_cma999_diff,lc_mean_TS_PCT_cma999_diff,lc_mean_USG_PCT_cma999_diff,lc_mean_E_USG_PCT_cma999_diff,lc_mean_E_PACE_cma999_diff,lc_mean_PACE_cma999_diff,lc_mean_PACE_PER40_cma999_diff,lc_mean_POSS_cma999_diff,lc_mean_PIE_cma999_diff,lc_max_MIN_cma999_diff,lc_max_E_OFF_RATING_cma999_diff,lc_max_OFF_RATING_cma999_diff,lc_max_E_DEF_RATING_cma999_diff,lc_max_DEF_RATING_cma999_diff,lc_max_E_NET_RATING_cma999_diff,lc_max_NET_RATING_cma999_diff,lc_max_AST_PCT_cma999_diff,lc_max_AST_TOV_cma999_diff,lc_max_AST_RATIO_cma999_diff,lc_max_OREB_PCT_cma999_diff,lc_max_DREB_PCT_cma999_diff,lc_max_REB_PCT_cma999_diff,lc_max_TM_TOV_PCT_cma999_diff,lc_max_EFG_PCT_cma999_diff,lc_max_TS_PCT_cma999_diff,lc_max_USG_PCT_cma999_diff,lc_max_E_USG_PCT_cma999_diff,lc_max_E_PACE_cma999_diff,lc_max_PACE_cma999_diff,lc_max_PACE_PER40_cma999_diff,lc_max_POSS_cma999_diff,lc_max_PIE_cma999_diff,lc_sum_MIN_cmax5_diff,lc_sum_E_OFF_RATING_cmax5_diff,lc_sum_OFF_RATING_cmax5_diff,lc_sum_E_DEF_RATING_cmax5_diff,lc_sum_DEF_RATING_cmax5_diff,lc_sum_E_NET_RATING_cmax5_diff,lc_sum_NET_RATING_cmax5_diff,lc_sum_AST_PCT_cmax5_diff,lc_sum_AST_TOV_cmax5_diff,lc_sum_AST_RATIO_cmax5_diff,lc_sum_OREB_PCT_cmax5_diff,lc_sum_DREB_PCT_cmax5_diff,lc_sum_REB_PCT_cmax5_diff,lc_sum_TM_TOV_PCT_cmax5_diff,lc_sum_EFG_PCT_cmax5_diff,lc_sum_TS_PCT_cmax5_diff,lc_sum_USG_PCT_cmax5_diff,lc_sum_E_USG_PCT_cmax5_diff,lc_sum_E_PACE_cmax5_diff,lc_sum_PACE_cmax5_diff,lc_sum_PACE_PER40_cmax5_diff,lc_sum_POSS_cmax5_diff,lc_sum_PIE_cmax5_diff,lc_mean_MIN_cmax5_diff,lc_mean_E_OFF_RATING_cmax5_diff,lc_mean_OFF_RATING_cmax5_diff,lc_mean_E_DEF_RATING_cmax5_diff,lc_mean_DEF_RATING_cmax5_diff,lc_mean_E_NET_RATING_cmax5_diff,lc_mean_NET_RATING_cmax5_diff,lc_mean_AST_PCT_cmax5_diff,lc_mean_AST_TOV_cmax5_diff,lc_mean_AST_RATIO_cmax5_diff,lc_mean_OREB_PCT_cmax5_diff,lc_mean_DREB_PCT_cmax5_diff,lc_mean_REB_PCT_cmax5_diff,lc_mean_TM_TOV_PCT_cmax5_diff,lc_mean_EFG_PCT_cmax5_diff,lc_mean_TS_PCT_cmax5_diff,lc_mean_USG_PCT_cmax5_diff,lc_mean_E_USG_PCT_cmax5_diff,lc_mean_E_PACE_cmax5_diff,lc_mean_PACE_cmax5_diff,lc_mean_PACE_PER40_cmax5_diff,lc_mean_POSS_cmax5_diff,lc_mean_PIE_cmax5_diff,lc_max_MIN_cmax5_diff,lc_max_E_OFF_RATING_cmax5_diff,lc_max_OFF_RATING_cmax5_diff,lc_max_E_DEF_RATING_cmax5_diff,lc_max_DEF_RATING_cmax5_diff,lc_max_E_NET_RATING_cmax5_diff,lc_max_NET_RATING_cmax5_diff,lc_max_AST_PCT_cmax5_diff,lc_max_AST_TOV_cmax5_diff,lc_max_AST_RATIO_cmax5_diff,lc_max_OREB_PCT_cmax5_diff,lc_max_DREB_PCT_cmax5_diff,lc_max_REB_PCT_cmax5_diff,lc_max_TM_TOV_PCT_cmax5_diff,lc_max_EFG_PCT_cmax5_diff,lc_max_TS_PCT_cmax5_diff,lc_max_USG_PCT_cmax5_diff,lc_max_E_USG_PCT_cmax5_diff,lc_max_E_PACE_cmax5_diff,lc_max_PACE_cmax5_diff,lc_max_PACE_PER40_cmax5_diff,lc_max_POSS_cmax5_diff,lc_max_PIE_cmax5_diff,lc_sum_MIN_cmax12_diff,lc_sum_E_OFF_RATING_cmax12_diff,lc_sum_OFF_RATING_cmax12_diff,lc_sum_E_DEF_RATING_cmax12_diff,lc_sum_DEF_RATING_cmax12_diff,lc_sum_E_NET_RATING_cmax12_diff,lc_sum_NET_RATING_cmax12_diff,lc_sum_AST_PCT_cmax12_diff,lc_sum_AST_TOV_cmax12_diff,lc_sum_AST_RATIO_cmax12_diff,lc_sum_OREB_PCT_cmax12_diff,lc_sum_DREB_PCT_cmax12_diff,lc_sum_REB_PCT_cmax12_diff,lc_sum_TM_TOV_PCT_cmax12_diff,lc_sum_EFG_PCT_cmax12_diff,lc_sum_TS_PCT_cmax12_diff,lc_sum_USG_PCT_cmax12_diff,lc_sum_E_USG_PCT_cmax12_diff,lc_sum_E_PACE_cmax12_diff,lc_sum_PACE_cmax12_diff,lc_sum_PACE_PER40_cmax12_diff,lc_sum_POSS_cmax12_diff,lc_sum_PIE_cmax12_diff,lc_mean_MIN_cmax12_diff,lc_mean_E_OFF_RATING_cmax12_diff,lc_mean_OFF_RATING_cmax12_diff,lc_mean_E_DEF_RATING_cmax12_diff,lc_mean_DEF_RATING_cmax12_diff,lc_mean_E_NET_RATING_cmax12_diff,lc_mean_NET_RATING_cmax12_diff,lc_mean_AST_PCT_cmax12_diff,lc_mean_AST_TOV_cmax12_diff,lc_mean_AST_RATIO_cmax12_diff,lc_mean_OREB_PCT_cmax12_diff,lc_mean_DREB_PCT_cmax12_diff,lc_mean_REB_PCT_cmax12_diff,lc_mean_TM_TOV_PCT_cmax12_diff,lc_mean_EFG_PCT_cmax12_diff,lc_mean_TS_PCT_cmax12_diff,lc_mean_USG_PCT_cmax12_diff,lc_mean_E_USG_PCT_cmax12_diff,lc_mean_E_PACE_cmax12_diff,lc_mean_PACE_cmax12_diff,lc_mean_PACE_PER40_cmax12_diff,lc_mean_POSS_cmax12_diff,lc_mean_PIE_cmax12_diff,lc_max_MIN_cmax12_diff,lc_max_E_OFF_RATING_cmax12_diff,lc_max_OFF_RATING_cmax12_diff,lc_max_E_DEF_RATING_cmax12_diff,lc_max_DEF_RATING_cmax12_diff,lc_max_E_NET_RATING_cmax12_diff,lc_max_NET_RATING_cmax12_diff,lc_max_AST_PCT_cmax12_diff,lc_max_AST_TOV_cmax12_diff,lc_max_AST_RATIO_cmax12_diff,lc_max_OREB_PCT_cmax12_diff,lc_max_DREB_PCT_cmax12_diff,lc_max_REB_PCT_cmax12_diff,lc_max_TM_TOV_PCT_cmax12_diff,lc_max_EFG_PCT_cmax12_diff,lc_max_TS_PCT_cmax12_diff,lc_max_USG_PCT_cmax12_diff,lc_max_E_USG_PCT_cmax12_diff,lc_max_E_PACE_cmax12_diff,lc_max_PACE_cmax12_diff,lc_max_PACE_PER40_cmax12_diff,lc_max_POSS_cmax12_diff,lc_max_PIE_cmax12_diff,lc_sum_MIN_cmax999_diff,lc_sum_E_OFF_RATING_cmax999_diff,lc_sum_OFF_RATING_cmax999_diff,lc_sum_E_DEF_RATING_cmax999_diff,lc_sum_DEF_RATING_cmax999_diff,lc_sum_E_NET_RATING_cmax999_diff,lc_sum_NET_RATING_cmax999_diff,lc_sum_AST_PCT_cmax999_diff,lc_sum_AST_TOV_cmax999_diff,lc_sum_AST_RATIO_cmax999_diff,lc_sum_OREB_PCT_cmax999_diff,lc_sum_DREB_PCT_cmax999_diff,lc_sum_REB_PCT_cmax999_diff,lc_sum_TM_TOV_PCT_cmax999_diff,lc_sum_EFG_PCT_cmax999_diff,lc_sum_TS_PCT_cmax999_diff,lc_sum_USG_PCT_cmax999_diff,lc_sum_E_USG_PCT_cmax999_diff,lc_sum_E_PACE_cmax999_diff,lc_sum_PACE_cmax999_diff,lc_sum_PACE_PER40_cmax999_diff,lc_sum_POSS_cmax999_diff,lc_sum_PIE_cmax999_diff,lc_mean_MIN_cmax999_diff,lc_mean_E_OFF_RATING_cmax999_diff,lc_mean_OFF_RATING_cmax999_diff,lc_mean_E_DEF_RATING_cmax999_diff,lc_mean_DEF_RATING_cmax999_diff,lc_mean_E_NET_RATING_cmax999_diff,lc_mean_NET_RATING_cmax999_diff,lc_mean_AST_PCT_cmax999_diff,lc_mean_AST_TOV_cmax999_diff,lc_mean_AST_RATIO_cmax999_diff,lc_mean_OREB_PCT_cmax999_diff,lc_mean_DREB_PCT_cmax999_diff,lc_mean_REB_PCT_cmax999_diff,lc_mean_TM_TOV_PCT_cmax999_diff,lc_mean_EFG_PCT_cmax999_diff,lc_mean_TS_PCT_cmax999_diff,lc_mean_USG_PCT_cmax999_diff,lc_mean_E_USG_PCT_cmax999_diff,lc_mean_E_PACE_cmax999_diff,lc_mean_PACE_cmax999_diff,lc_mean_PACE_PER40_cmax999_diff,lc_mean_POSS_cmax999_diff,lc_mean_PIE_cmax999_diff,lc_max_MIN_cmax999_diff,lc_max_E_OFF_RATING_cmax999_diff,lc_max_OFF_RATING_cmax999_diff,lc_max_E_DEF_RATING_cmax999_diff,lc_max_DEF_RATING_cmax999_diff,lc_max_E_NET_RATING_cmax999_diff,lc_max_NET_RATING_cmax999_diff,lc_max_AST_PCT_cmax999_diff,lc_max_AST_TOV_cmax999_diff,lc_max_AST_RATIO_cmax999_diff,lc_max_OREB_PCT_cmax999_diff,lc_max_DREB_PCT_cmax999_diff,lc_max_REB_PCT_cmax999_diff,lc_max_TM_TOV_PCT_cmax999_diff,lc_max_EFG_PCT_cmax999_diff,lc_max_TS_PCT_cmax999_diff,lc_max_USG_PCT_cmax999_diff,lc_max_E_USG_PCT_cmax999_diff,lc_max_E_PACE_cmax999_diff,lc_max_PACE_cmax999_diff,lc_max_PACE_PER40_cmax999_diff,lc_max_POSS_cmax999_diff,lc_max_PIE_cmax999_diff,MIN_a,duration_a,MIN_b,duration_b,E_OFF_RATING_cma5_diff,OFF_RATING_cma5_diff,E_DEF_RATING_cma5_diff,DEF_RATING_cma5_diff,E_NET_RATING_cma5_diff,NET_RATING_cma5_diff,AST_PCT_cma5_diff,AST_TOV_cma5_diff,AST_RATIO_cma5_diff,OREB_PCT_cma5_diff,DREB_PCT_cma5_diff,REB_PCT_cma5_diff,E_TM_TOV_PCT_cma5_diff,TM_TOV_PCT_cma5_diff,EFG_PCT_cma5_diff,TS_PCT_cma5_diff,USG_PCT_cma5_diff,E_USG_PCT_cma5_diff,E_PACE_cma5_diff,PACE_cma5_diff,PACE_PER40_cma5_diff,POSS_cma5_diff,PIE_cma5_diff,duration_minutes_cma5_diff,w_pct_cma5_diff,min_cma5_diff,fgm_cma5_diff,fga_cma5_diff,fg_pct_cma5_diff,fg3m_cma5_diff,fg3a_cma5_diff,fg3_pct_cma5_diff,ftm_cma5_diff,fta_cma5_diff,ft_pct_cma5_diff,oreb_cma5_diff,dreb_cma5_diff,reb_cma5_diff,ast_cma5_diff,stl_cma5_diff,blk_cma5_diff,tov_cma5_diff,pf_cma5_diff,pts_cma5_diff,spread_cma5_diff,away_home__cma5_diff,E_OFF_RATING_cma12_diff,OFF_RATING_cma12_diff,E_DEF_RATING_cma12_diff,DEF_RATING_cma12_diff,E_NET_RATING_cma12_diff,NET_RATING_cma12_diff,AST_PCT_cma12_diff,AST_TOV_cma12_diff,AST_RATIO_cma12_diff,OREB_PCT_cma12_diff,DREB_PCT_cma12_diff,REB_PCT_cma12_diff,E_TM_TOV_PCT_cma12_diff,TM_TOV_PCT_cma12_diff,EFG_PCT_cma12_diff,TS_PCT_cma12_diff,USG_PCT_cma12_diff,E_USG_PCT_cma12_diff,E_PACE_cma12_diff,PACE_cma12_diff,PACE_PER40_cma12_diff,POSS_cma12_diff,PIE_cma12_diff,duration_minutes_cma12_diff,w_pct_cma12_diff,min_cma12_diff,fgm_cma12_diff,fga_cma12_diff,fg_pct_cma12_diff,fg3m_cma12_diff,fg3a_cma12_diff,fg3_pct_cma12_diff,ftm_cma12_diff,fta_cma12_diff,ft_pct_cma12_diff,oreb_cma12_diff,dreb_cma12_diff,reb_cma12_diff,ast_cma12_diff,stl_cma12_diff,blk_cma12_diff,tov_cma12_diff,pf_cma12_diff,pts_cma12_diff,spread_cma12_diff,away_home__cma12_diff,E_OFF_RATING_cma999_diff,OFF_RATING_cma999_diff,E_DEF_RATING_cma999_diff,DEF_RATING_cma999_diff,E_NET_RATING_cma999_diff,NET_RATING_cma999_diff,AST_PCT_cma999_diff,AST_TOV_cma999_diff,AST_RATIO_cma999_diff,OREB_PCT_cma999_diff,DREB_PCT_cma999_diff,REB_PCT_cma999_diff,E_TM_TOV_PCT_cma999_diff,TM_TOV_PCT_cma999_diff,EFG_PCT_cma999_diff,TS_PCT_cma999_diff,USG_PCT_cma999_diff,E_USG_PCT_cma999_diff,E_PACE_cma999_diff,PACE_cma999_diff,PACE_PER40_cma999_diff,POSS_cma999_diff,PIE_cma999_diff,duration_minutes_cma999_diff,w_pct_cma999_diff,min_cma999_diff,fgm_cma999_diff,fga_cma999_diff,fg_pct_cma999_diff,fg3m_cma999_diff,fg3a_cma999_diff,fg3_pct_cma999_diff,ftm_cma999_diff,fta_cma999_diff,ft_pct_cma999_diff,oreb_cma999_diff,dreb_cma999_diff,reb_cma999_diff,ast_cma999_diff,stl_cma999_diff,blk_cma999_diff,tov_cma999_diff,pf_cma999_diff,pts_cma999_diff,spread_cma999_diff,away_home__cma999_diff,E_OFF_RATING_cmax5_diff,OFF_RATING_cmax5_diff,E_DEF_RATING_cmax5_diff,DEF_RATING_cmax5_diff,E_NET_RATING_cmax5_diff,NET_RATING_cmax5_diff,AST_PCT_cmax5_diff,AST_TOV_cmax5_diff,AST_RATIO_cmax5_diff,OREB_PCT_cmax5_diff,DREB_PCT_cmax5_diff,REB_PCT_cmax5_diff,E_TM_TOV_PCT_cmax5_diff,TM_TOV_PCT_cmax5_diff,EFG_PCT_cmax5_diff,TS_PCT_cmax5_diff,USG_PCT_cmax5_diff,E_USG_PCT_cmax5_diff,E_PACE_cmax5_diff,PACE_cmax5_diff,PACE_PER40_cmax5_diff,POSS_cmax5_diff,PIE_cmax5_diff,duration_minutes_cmax5_diff,w_pct_cmax5_diff,min_cmax5_diff,fgm_cmax5_diff,fga_cmax5_diff,fg_pct_cmax5_diff,fg3m_cmax5_diff,fg3a_cmax5_diff,fg3_pct_cmax5_diff,ftm_cmax5_diff,fta_cmax5_diff,ft_pct_cmax5_diff,oreb_cmax5_diff,dreb_cmax5_diff,reb_cmax5_diff,ast_cmax5_diff,stl_cmax5_diff,blk_cmax5_diff,tov_cmax5_diff,pf_cmax5_diff,pts_cmax5_diff,spread_cmax5_diff,away_home__cmax5_diff,E_OFF_RATING_cmax12_diff,OFF_RATING_cmax12_diff,E_DEF_RATING_cmax12_diff,DEF_RATING_cmax12_diff,E_NET_RATING_cmax12_diff,NET_RATING_cmax12_diff,AST_PCT_cmax12_diff,AST_TOV_cmax12_diff,AST_RATIO_cmax12_diff,OREB_PCT_cmax12_diff,DREB_PCT_cmax12_diff,REB_PCT_cmax12_diff,E_TM_TOV_PCT_cmax12_diff,TM_TOV_PCT_cmax12_diff,EFG_PCT_cmax12_diff,TS_PCT_cmax12_diff,USG_PCT_cmax12_diff,E_USG_PCT_cmax12_diff,E_PACE_cmax12_diff,PACE_cmax12_diff,PACE_PER40_cmax12_diff,POSS_cmax12_diff,PIE_cmax12_diff,duration_minutes_cmax12_diff,w_pct_cmax12_diff,min_cmax12_diff,fgm_cmax12_diff,fga_cmax12_diff,fg_pct_cmax12_diff,fg3m_cmax12_diff,fg3a_cmax12_diff,fg3_pct_cmax12_diff,ftm_cmax12_diff,fta_cmax12_diff,ft_pct_cmax12_diff,oreb_cmax12_diff,dreb_cmax12_diff,reb_cmax12_diff,ast_cmax12_diff,stl_cmax12_diff,blk_cmax12_diff,tov_cmax12_diff,pf_cmax12_diff,pts_cmax12_diff,spread_cmax12_diff,away_home__cmax12_diff,E_OFF_RATING_cmax999_diff,OFF_RATING_cmax999_diff,E_DEF_RATING_cmax999_diff,DEF_RATING_cmax999_diff,E_NET_RATING_cmax999_diff,NET_RATING_cmax999_diff,AST_PCT_cmax999_diff,AST_TOV_cmax999_diff,AST_RATIO_cmax999_diff,OREB_PCT_cmax999_diff,DREB_PCT_cmax999_diff,REB_PCT_cmax999_diff,E_TM_TOV_PCT_cmax999_diff,TM_TOV_PCT_cmax999_diff,EFG_PCT_cmax999_diff,TS_PCT_cmax999_diff,USG_PCT_cmax999_diff,E_USG_PCT_cmax999_diff,E_PACE_cmax999_diff,PACE_cmax999_diff,PACE_PER40_cmax999_diff,POSS_cmax999_diff,PIE_cmax999_diff,duration_minutes_cmax999_diff,w_pct_cmax999_diff,min_cmax999_diff,fgm_cmax999_diff,fga_cmax999_diff,fg_pct_cmax999_diff,fg3m_cmax999_diff,fg3a_cmax999_diff,fg3_pct_cmax999_diff,ftm_cmax999_diff,fta_cmax999_diff,ft_pct_cmax999_diff,oreb_cmax999_diff,dreb_cmax999_diff,reb_cmax999_diff,ast_cmax999_diff,stl_cmax999_diff,blk_cmax999_diff,tov_cmax999_diff,pf_cmax999_diff,pts_cmax999_diff,spread_cmax999_diff,away_home__cmax999_diff,E_OFF_RATING_sm_cma12_diff,OFF_RATING_sm_cma12_diff,E_DEF_RATING_sm_cma12_diff,DEF_RATING_sm_cma12_diff,E_NET_RATING_sm_cma12_diff,NET_RATING_sm_cma12_diff,AST_PCT_sm_cma12_diff,AST_TOV_sm_cma12_diff,AST_RATIO_sm_cma12_diff,OREB_PCT_sm_cma12_diff,DREB_PCT_sm_cma12_diff,REB_PCT_sm_cma12_diff,E_TM_TOV_PCT_sm_cma12_diff,TM_TOV_PCT_sm_cma12_diff,EFG_PCT_sm_cma12_diff,TS_PCT_sm_cma12_diff,USG_PCT_sm_cma12_diff,E_USG_PCT_sm_cma12_diff,E_PACE_sm_cma12_diff,PACE_sm_cma12_diff,PACE_PER40_sm_cma12_diff,POSS_sm_cma12_diff,PIE_sm_cma12_diff,duration_minutes_sm_cma12_diff,w_pct_sm_cma12_diff,min_sm_cma12_diff,fgm_sm_cma12_diff,fga_sm_cma12_diff,fg_pct_sm_cma12_diff,fg3m_sm_cma12_diff,fg3a_sm_cma12_diff,fg3_pct_sm_cma12_diff,ftm_sm_cma12_diff,fta_sm_cma12_diff,ft_pct_sm_cma12_diff,oreb_sm_cma12_diff,dreb_sm_cma12_diff,reb_sm_cma12_diff,ast_sm_cma12_diff,stl_sm_cma12_diff,blk_sm_cma12_diff,tov_sm_cma12_diff,pf_sm_cma12_diff,pts_sm_cma12_diff,spread_sm_cma12_diff,away_home_sm_cma12_diff,E_OFF_RATING_sm_cmax12_diff,OFF_RATING_sm_cmax12_diff,E_DEF_RATING_sm_cmax12_diff,DEF_RATING_sm_cmax12_diff,E_NET_RATING_sm_cmax12_diff,NET_RATING_sm_cmax12_diff,AST_PCT_sm_cmax12_diff,AST_TOV_sm_cmax12_diff,AST_RATIO_sm_cmax12_diff,OREB_PCT_sm_cmax12_diff,DREB_PCT_sm_cmax12_diff,REB_PCT_sm_cmax12_diff,E_TM_TOV_PCT_sm_cmax12_diff,TM_TOV_PCT_sm_cmax12_diff,EFG_PCT_sm_cmax12_diff,TS_PCT_sm_cmax12_diff,USG_PCT_sm_cmax12_diff,E_USG_PCT_sm_cmax12_diff,E_PACE_sm_cmax12_diff,PACE_sm_cmax12_diff,PACE_PER40_sm_cmax12_diff,POSS_sm_cmax12_diff,PIE_sm_cmax12_diff,duration_minutes_sm_cmax12_diff,w_pct_sm_cmax12_diff,min_sm_cmax12_diff,fgm_sm_cmax12_diff,fga_sm_cmax12_diff,fg_pct_sm_cmax12_diff,fg3m_sm_cmax12_diff,fg3a_sm_cmax12_diff,fg3_pct_sm_cmax12_diff,ftm_sm_cmax12_diff,fta_sm_cmax12_diff,ft_pct_sm_cmax12_diff,oreb_sm_cmax12_diff,dreb_sm_cmax12_diff,reb_sm_cmax12_diff,ast_sm_cmax12_diff,stl_sm_cmax12_diff,blk_sm_cmax12_diff,tov_sm_cmax12_diff,pf_sm_cmax12_diff,pts_sm_cmax12_diff,spread_sm_cmax12_diff,away_home_sm_cmax12_diff,E_OFF_RATING_cma_sm_cmax12_diff,OFF_RATING_cma_sm_cmax12_diff,E_DEF_RATING_cma_sm_cmax12_diff,DEF_RATING_cma_sm_cmax12_diff,E_NET_RATING_cma_sm_cmax12_diff,NET_RATING_cma_sm_cmax12_diff,AST_PCT_cma_sm_cmax12_diff,AST_TOV_cma_sm_cmax12_diff,AST_RATIO_cma_sm_cmax12_diff,OREB_PCT_cma_sm_cmax12_diff,DREB_PCT_cma_sm_cmax12_diff,REB_PCT_cma_sm_cmax12_diff,E_TM_TOV_PCT_cma_sm_cmax12_diff,TM_TOV_PCT_cma_sm_cmax12_diff,EFG_PCT_cma_sm_cmax12_diff,TS_PCT_cma_sm_cmax12_diff,USG_PCT_cma_sm_cmax12_diff,E_USG_PCT_cma_sm_cmax12_diff,E_PACE_cma_sm_cmax12_diff,PACE_cma_sm_cmax12_diff,PACE_PER40_cma_sm_cmax12_diff,POSS_cma_sm_cmax12_diff,PIE_cma_sm_cmax12_diff,duration_minutes_cma_sm_cmax12_diff,w_pct_cma_sm_cmax12_diff,min_cma_sm_cmax12_diff,fgm_cma_sm_cmax12_diff,fga_cma_sm_cmax12_diff,fg_pct_cma_sm_cmax12_diff,fg3m_cma_sm_cmax12_diff,fg3a_cma_sm_cmax1