In [1]:
#number of games in past window# (day#): game_count_day#



#number of away games in past window# (games#): away_count_game#

#number of home games in past window# (games#): home_count_game#

In [2]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA
from sklearn.preprocessing import scale


pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

pd.set_option('display.max_colwidth', None)
pd.options.display.max_info_columns = 999

#return the first 5 and last 5 rows of this dataframe
def p(df_):
    if df_.shape[0] > 6:
        print(df_.shape)
        return pd.concat([df_.head(), df_.tail()])
    else:
        return df_

def rcp(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'processed_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'processed_data', file_), parse_dates=pd_)
    
def rcr(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'raw_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'raw_data', file_), parse_dates=pd_)
    
#sort dataframe by column
def s(df_, column_):
    return df_.sort_values(column_)

#reset index and sort dataframe by column
def sr(df_, column_):
    df_ = df_.sort_values(column_)
    return df_.reset_index(drop=True)

#print length of list
def pl(list_):
    print(len(list_))
    return list_

#print length of list
def pdc(dict_):
    print(len(dict_))
    return dict_

#import my functions
import my_functions as f



def feature_engineer(df_, group_by_columns_, column_features_, operators_, window_size_, shift_num_=1):
    
    '''
    example operators: 'max', 'min', 'count', 'median', 'mean'
    '''
    df_.groupby([group_by_columns_])\
           [column_features_]\
           .rolling(window_size_,1).agg([operators_])\
           .shift(shift_num_)
    

from functools import reduce

def merge_dataframe(df_list_, merge_on_list_):
    return reduce(lambda  left,right: pd.merge(left,right,on=column_names_common_list, how='outer'), data_frames)

In [3]:
df = rcp('64_city_proper_metro_area_gdp_2010_2018.csv', ['game_date'])
df = df.sort_values(['game_date', 'game_id'], ascending=True)
p(df)

(20532, 72)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,latitude,longitude,game_latitude,game_longitude,travel_distance,game_time_zone,time_zone,time_zone_diff,time_zone_diff_abs,city_proper_metro_area,Country/Region,city_proper_metro_area_GDP_bil,city_proper_metro_area_GDP_bil1
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,25.774173,-80.193620,42.360253,-71.058291,1257.755091,America/New_York,America/New_York,0.0,0.0,Miami,United States,377.5,262.7
1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,42.360253,-71.058291,42.360253,-71.058291,0.000000,America/New_York,America/New_York,0.0,0.0,Boston,United States,463.570,560.1
2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,33.448437,-112.074142,45.520247,-122.674195,1005.606855,America/Los_Angeles,America/Phoenix,0.0,0.0,Phoenix,United States,255.211,607.1
3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,45.520247,-122.674195,45.520247,-122.674195,0.000000,America/Los_Angeles,America/Los_Angeles,0.0,0.0,Portland,United States,164.419,158.5
4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,29.758938,-95.367697,34.053691,-118.242766,1371.020326,America/Los_Angeles,America/Chicago,-2.0,2.0,Houston,United States,478.778,883.2
20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,37.854666,-122.292136,0.000000,America/Los_Angeles,America/Los_Angeles,0.0,0.0,San Francisco,United States,995,631.0
20528,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0.0,0.0,Cleveland,United States,135,215.1
20529,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3.0,3.0,San Francisco,United States,995,631.0
20530,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0.0,0.0,Cleveland,United States,135,215.1
20531,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3.0,3.0,San Francisco,United States,995,631.0

In [4]:
def get_game_count_percentage_away_home_both_day_window(df_, day_window_):
    
    len(day_window_) - 1
    
    df_ = df_.set_index('game_date')
    
    df1_ = df_.groupby(['team_id', 'season'])['away_home_']\
              .rolling(day_window_).sum().reset_index()\
              .rename(columns={'away_home_':'home_game_count_day' + day_window_[0:len(day_window_) - 1]})    
    
    df1_['home_game_count_day' \
         + day_window_[0:len(day_window_) - 1]] = \
    df1_['home_game_count_day' + day_window_[0:len(day_window_) - 1]]#.astype('int64')
    
    
    df_.away_home_ = abs(df_.away_home_ - 1)
    
    df0_ = df_.groupby(['team_id', 'season'])['away_home_']\
             .rolling(day_window_).sum().reset_index()\
             .rename(columns={'away_home_':'away_game_count_day' + day_window_[0:len(day_window_) - 1]})
    
    df0_['away_game_count_day' \
         + day_window_[0:len(day_window_) - 1]] = \
    df0_['away_game_count_day' + day_window_[0:len(day_window_) - 1]]#.astype('int64')
    
    
    df_.away_home_ = abs(df_.away_home_ - 1)
    
    df2_ = df_.groupby(['team_id', 'season'])['away_home_']\
              .rolling(day_window_).count().reset_index()\
              .rename(columns={'away_home_':'game_count_day' + day_window_[0:len(day_window_) - 1]})
    
    df2_['game_count_day' \
         + day_window_[0:len(day_window_) - 1]] = \
    df2_['game_count_day' + day_window_[0:len(day_window_) - 1]]#.astype('int64')
    
    
    column_names_common_list01_ = [k for k in df0_.columns if k in df1_.columns]
    
    df01_ = pd.merge(df0_, df1_, on=column_names_common_list01_)
    
    column_names_common_list012_ = [k for k in df01_.columns if k in df2_.columns]
    
    df012_ = pd.merge(df01_, df2_, on=column_names_common_list012_)
    
    column_names_common_list012_ = [k for k in df01_.columns if k in df2_.columns]

    df012_['away_game_percent_day' \
         + day_window_[0:len(day_window_) - 1]] = \
    df012_['away_game_count_day' + day_window_[0:len(day_window_) - 1]] /\
    df012_['game_count_day' + day_window_[0:len(day_window_) - 1]].values
    
    
    df012_['home_game_percent_day' \
         + day_window_[0:len(day_window_) - 1]] = \
    df012_['home_game_count_day' + day_window_[0:len(day_window_) - 1]] /\
    df012_['game_count_day' + day_window_[0:len(day_window_) - 1]].values
    
    df_ = pd.merge(df_, df012_, on=['team_id', 'season', 'game_date'])
    
    
    return df_

In [5]:
day_windows = [2, 5, 8, 12, 999]
day_windows

[2, 5, 8, 12, 999]

In [6]:
for i in day_windows:
    df = get_game_count_percentage_away_home_both_day_window(df, str(i) + 'D')

In [7]:
p(df)

(20532, 97)

,game_id,TEAM_NAME,game_date,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,matchup,season_type,season,season_year,latitude,longitude,game_latitude,game_longitude,travel_distance,game_time_zone,time_zone,time_zone_diff,time_zone_diff_abs,city_proper_metro_area,Country/Region,city_proper_metro_area_GDP_bil,city_proper_metro_area_GDP_bil1,away_game_count_day2,home_game_count_day2,game_count_day2,away_game_percent_day2,home_game_percent_day2,away_game_count_day5,home_game_count_day5,game_count_day5,away_game_percent_day5,home_game_percent_day5,away_game_count_day8,home_game_count_day8,game_count_day8,away_game_percent_day8,home_game_percent_day8,away_game_count_day12,home_game_count_day12,game_count_day12,away_game_percent_day12,home_game_percent_day12,away_game_count_day999,home_game_count_day999,game_count_day999,away_game_percent_day999,home_game_percent_day999
0,21000001,Heat,2010-10-26,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,BOS vs. MIA,Regular Season,2010-11,2010,25.774173,-80.193620,42.360253,-71.058291,1257.755091,America/New_York,America/New_York,0.0,0.0,Miami,United States,377.5,262.7,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.00,0.00,1.0,0.0,1.0,1.000000,0.000000
1,21000001,Celtics,2010-10-26,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,BOS vs. MIA,Regular Season,2010-11,2010,42.360253,-71.058291,42.360253,-71.058291,0.000000,America/New_York,America/New_York,0.0,0.0,Boston,United States,463.570,560.1,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.00,1.00,0.0,1.0,1.0,0.000000,1.000000
2,21000002,Suns,2010-10-26,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,PHX vs. POR,Regular Season,2010-11,2010,33.448437,-112.074142,45.520247,-122.674195,1005.606855,America/Los_Angeles,America/Phoenix,0.0,0.0,Phoenix,United States,255.211,607.1,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.00,0.00,1.0,0.0,1.0,1.000000,0.000000
3,21000002,Trail Blazers,2010-10-26,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,PHX vs. POR,Regular Season,2010-11,2010,45.520247,-122.674195,45.520247,-122.674195,0.000000,America/Los_Angeles,America/Los_Angeles,0.0,0.0,Portland,United States,164.419,158.5,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.00,1.00,0.0,1.0,1.0,0.000000,1.000000
4,21000003,Rockets,2010-10-26,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,HOU vs. LAL,Regular Season,2010-11,2010,29.758938,-95.367697,34.053691,-118.242766,1371.020326,America/Los_Angeles,America/Chicago,-2.0,2.0,Houston,United States,478.778,883.2,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.00,0.00,1.0,0.0,1.0,1.000000,0.000000
20527,41700402,Warriors,2018-06-03,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,37.854666,-122.292136,0.000000,America/Los_Angeles,America/Los_Angeles,0.0,0.0,San Francisco,United States,995,631.0,0.0,1.0,1.0,0.0,1.0,0.0,2.0,2.0,0.0,1.0,1.0,2.0,3.0,0.333333,0.666667,2.0,3.0,5.0,0.40,0.60,49.0,52.0,101.0,0.485149,0.514851
20528,41700403,Cavaliers,2018-06-06,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0.0,0.0,Cleveland,United States,135,215.1,0.0,1.0,1.0,0.0,1.0,1.0,1.0,2.0,0.5,0.5,2.0,1.0,3.0,0.666667,0.333333,3.0,1.0,4.0,0.75,0.25,52.0,51.0,103.0,0.504854,0.495146
20529,41700403,Warriors,2018-06-06,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3.0,3.0,San Francisco,United States,995,631.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,2.0,0.5,0.5,1.0,2.0,3.0,0.333333,0.666667,2.0,3.0,5.0,0.40,0.60,50.0,52.0,102.0,0.490196,0.509804
20530,41700404,Cavaliers,2018-06-08,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0.0,0.0,Cleveland,United States,135,215.1,0.0,1.0,1.0,0.0,1.0,0.0,2.0,2.0,0.0,1.0,1.0,2.0,3.0,0.333333,0.666667,2.0,2.0,4.0,0.50,0.50,52.0,52.0,104.0,0.500000,0.500000
20531,41700404,Warriors,2018-06-08,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3.0,3.0,San Francisco,United States,995,631.0,1.0,0.0,1.0,1.0,0.0,2.0,0.0,2.0,1.0,0.0,2.0,1.0,3.0,0.666667,0.333333,3.0,2.0,5.0,0.60,0.40,51.0,52.0,103.0,0.495146,0.504854

In [8]:
df_sub = df[['team_id', 'TEAM_NAME', 'TEAM_ABBREVIATION', 
             'game_date', 'away_home_', 'away_game_count_day5',
             'home_game_count_day5', 'game_count_day5']]
p(df_sub)

(20532, 8)

,team_id,TEAM_NAME,TEAM_ABBREVIATION,game_date,away_home_,away_game_count_day5,home_game_count_day5,game_count_day5
0,1610612748,Heat,MIA,2010-10-26,0,1.0,0.0,1.0
1,1610612738,Celtics,BOS,2010-10-26,1,0.0,1.0,1.0
2,1610612756,Suns,PHX,2010-10-26,0,1.0,0.0,1.0
3,1610612757,Trail Blazers,POR,2010-10-26,1,0.0,1.0,1.0
4,1610612745,Rockets,HOU,2010-10-26,0,1.0,0.0,1.0
20527,1610612744,Warriors,GSW,2018-06-03,1,0.0,2.0,2.0
20528,1610612739,Cavaliers,CLE,2018-06-06,1,1.0,1.0,2.0
20529,1610612744,Warriors,GSW,2018-06-06,0,1.0,1.0,2.0
20530,1610612739,Cavaliers,CLE,2018-06-08,1,0.0,2.0,2.0
20531,1610612744,Warriors,GSW,2018-06-08,0,2.0,0.0,2.0

In [9]:
df_sub[df_sub.team_id == 1610612738]

,team_id,TEAM_NAME,TEAM_ABBREVIATION,game_date,away_home_,away_game_count_day5,home_game_count_day5,game_count_day5
1,1610612738,Celtics,BOS,2010-10-26,1,0.0,1.0,1.0
6,1610612738,Celtics,BOS,2010-10-27,0,1.0,1.0,2.0
44,1610612738,Celtics,BOS,2010-10-29,1,1.0,2.0,3.0
96,1610612738,Celtics,BOS,2010-11-02,0,1.0,1.0,2.0
112,1610612738,Celtics,BOS,2010-11-03,1,1.0,1.0,2.0
142,1610612738,Celtics,BOS,2010-11-05,1,1.0,2.0,3.0
182,1610612738,Celtics,BOS,2010-11-07,0,1.0,2.0,3.0
196,1610612738,Celtics,BOS,2010-11-08,0,2.0,1.0,3.0
233,1610612738,Celtics,BOS,2010-11-11,0,3.0,0.0,3.0
266,1610612738,Celtics,BOS,2010-11-13,0,2.0,0.0,2.0
316,1610612738,Celtics,BOS,2010-11-17,1,1.0,1.0,2.0
338,1610612738,Celtics,BOS,2010-11-19,1,0.0,2.0,2.0
378,1610612738,Celtics,BOS,2010-11-21,0,1.0,2.0,3.0
386,1610612738,Celtics,BOS,2010-11-22,0,2.0,1.0,3.0
420,1610612738,Celtics,BOS,2010-11-24,1,2.0,1.0,3.0
444,1610612738,Celtics,BOS,2010-11-26,1,1.0,2.0,3.0
504,1610612738,Celtics,BOS,2010-11-30,0,1.0,1.0,2.0
524,1610612738,Celtics,BOS,2010-12-01,1,1.0,1.0,2.0
556,1610612738,Celtics,BOS,2010-12-03,1,1.0,2.0,3.0
584,1610612738,Celtics,BOS,2010-12-05,0,1.0,2.0,3.0
628,1610612738,Celtics,BOS,2010-12-08,1,1.0,1.0,2.0
650,1610612738,Celtics,BOS,2010-12-09,0,2.0,1.0,3.0
682,1610612738,Celtics,BOS,2010-12-11,0,2.0,1.0,3.0
732,1610612738,Celtics,BOS,2010-12-15,0,2.0,0.0,2.0
754,1610612738,Celtics,BOS,2010-12-16,1,1.0,1.0,2.0
796,1610612738,Celtics,BOS,2010-12-19,1,1.0,2.0,3.0
844,1610612738,Celtics,BOS,2010-12-22,1,0.0,2.0,2.0
864,1610612738,Celtics,BOS,2010-12-25,0,1.0,1.0,2.0
908,1610612738,Celtics,BOS,2010-12-28,0,2.0,0.0,2.0
926,1610612738,Celtics,BOS,2010-12-29,0,3.0,0.0,3.0
948,1610612738,Celtics,BOS,2010-12-31,1,2.0,1.0,3.0
984,1610612738,Celtics,BOS,2011-01-02,0,2.0,1.0,3.0
998,1610612738,Celtics,BOS,2011-01-03,1,1.0,2.0,3.0
1028,1610612738,Celtics,BOS,2011-01-05,1,1.0,2.0,3.0
1052,1610612738,Celtics,BOS,2011-01-07,1,0.0,3.0,3.0
1076,1610612738,Celtics,BOS,2011-01-08,0,1.0,2.0,3.0
1100,1610612738,Celtics,BOS,2011-01-10,1,1.0,2.0,3.0
1122,1610612738,Celtics,BOS,2011-01-12,1,1.0,2.0,3.0
1152,1610612738,Celtics,BOS,2011-01-14,1,0.0,3.0,3.0
1210,1610612738,Celtics,BOS,2011-01-17,1,0.0,2.0,2.0
1226,1610612738,Celtics,BOS,2011-01-19,1,0.0,2.0,2.0
1258,1610612738,Celtics,BOS,2011-01-21,1,0.0,3.0,3.0
1276,1610612738,Celtics,BOS,2011-01-22,0,1.0,2.0,3.0
1322,1610612738,Celtics,BOS,2011-01-25,1,1.0,2.0,3.0
1354,1610612738,Celtics,BOS,2011-01-27,0,1.0,1.0,2.0
1374,1610612738,Celtics,BOS,2011-01-28,0,2.0,1.0,3.0
1398,1610612738,Celtics,BOS,2011-01-30,0,3.0,0.0,3.0
1428,1610612738,Celtics,BOS,2011-02-01,0,3.0,0.0,3.0
1474,1610612738,Celtics,BOS,2011-02-04,1,1.0,1.0,2.0
1508,1610612738,Celtics,BOS,2011-02-06,1,0.0,2.0,2.0
1510,1610612738,Celtics,BOS,2011-02-07,0,1.0,2.0,3.0
1560,1610612738,Celtics,BOS,2011-02-10,1,1.0,2.0,3.0
1603,1610612738,Celtics,BOS,2011-02-13,1,0.0,2.0,2.0
1646,1610612738,Celtics,BOS,2011-02-16,1,0.0,2.0,2.0
1684,1610612738,Celtics,BOS,2011-02-22,0,1.0,0.0,1.0
1714,1610612738,Celtics,BOS,2011-02-24,0,2.0,0.0,2.0
1750,1610612738,Celtics,BOS,2011-02-26,0,3.0,0.0,3.0
1778,1610612738,Celtics,BOS,2011-02-28,0,3.0,0.0,3.0
1804,1610612738,Celtics,BOS,2011-03-02,1,2.0,1.0,3.0
1830,1610612738,Celtics,BOS,2011-03-04,1,1.0,2.0,3.0
1872,1610612738,Celtics,BOS,2011-03-06,0,1.0,2.0,3.0
1908,1610612738,Celtics,BOS,2011-03-09,1,1.0,1.0,2.0
1932,1610612738,Celtics,BOS,2011-03-11,0,1.0,1.0,2.0
1970,1610612738,Celtics,BOS,2011-03-13,1,1.0,2.0,3.0
1976,1610612738,Celtics,BOS,2011-03-14,0,2.0,1.0,3.0
2004,1610612738,Celtics,BOS,2011-03-16,1,1.0,2.0,3.0
2044,1610612738,Celtics,BOS,2011-03-18,0,2.0,1.0,3.0
2060,1610612738,Celtics,BOS,2011-03-19,0,2.0,1.0,3.0
2088,1610612738,Celtics,BOS,2011-03-21,0,3.0,0.0,3.0
2110,1610612738,Celtics,BOS,2011-03-23,1,2.0,1.0,3.0
2136,1610612738,Celtics,BOS,2011-03-25,1,1.0,2.0,3.0
2178,1610612738,Celtics,BOS,2011-03-27,0,1.0,2.0,3.0
2192,1610612738,Celtics,BOS,2011-03-28,0,2.0,1.0,3.0
2234,1610612738,Celtics,BOS,2011-03-31,0,3.0,0.0,3.0
2248,1610612738,Celtics,BOS,2011-04-01,0,3.0,0.0,3.0
2278,1610612738,Celtics,BOS,2011-04-03,1,2.0,1.0,3.0
2306,1610612738,Celtics,BOS,2011-04-05,1,1.0,2.0,3.0
2346,1610612738,Celtics,BOS,2011-04-07,0,1.0,2.0,3.0
2356,1610612738,Celtics,BOS,2011-04-08,1,1.0,2.0,3.0
2387,1610612738,Celtics,BOS,2011-04-10,0,2.0,1.0,3.0
2408,1610612738,Celtics,BOS,2011-04-11,0,3.0,1.0,4.0
2430,1610612738,Celtics,BOS,2011-04-13,1,2.0,1.0,3.0
2468,1610612738,Celtics,BOS,2011-04-17,1,0.0,2.0,2.0
2480,1610612738,Celtics,BOS,2011-04-19,1,0.0,2.0,2.0
2498,1610612738,Celtics,BOS,2011-04-22,0,1.0,1.0,2.0
2514,1610612738,Celtics,BOS,2011-04-24,0,2.0,0.0,2.0
2547,1610612738,Celtics,BOS,2011-05-01,0,1.0,0.0,1.0
2555,1610612738,Celtics,BOS,2011-05-03,0,2.0,0.0,2.0
2567,1610612738,Celtics,BOS,2011-05-07,1,1.0,1.0,2.0
2575,1610612738,Celtics,BOS,2011-05-09,1,0.0,2.0,2.0
2581,1610612738,Celtics,BOS,2011-05-11,0,1.0,2.0,3.0
2622,1610612738,Celtics,BOS,2011-12-25,0,1.0,0.0,1.0
2659,1610612738,Celtics,BOS,2011-12-27,0,2.0,0.0,2.0
2676,1610612738,Celtics,BOS,2011-12-28,0,3.0,0.0,3.0
2702,1610612738,Celtics,BOS,2011-12-30,1,2.0,1.0,3.0
2734,1610612738,Celtics,BOS,2012-01-01,0,2.0,1.0,3.0
2754,1610612738,Celtics,BOS,2012-01-02,1,1.0,2.0,3.0
2788,1610612738,Celtics,BOS,2012-01-04,1,1.0,2.0,3.0
2824,1610612738,Celtics,BOS,2012-01-06,1,0.0,3.0,3.0
2912,1610612738,Celtics,BOS,2012-01-11,1,0.0,1.0,1.0
2944,1610612738,Celtics,BOS,2012-01-13,1,0.0,2.0,2.0
2966,1610612738,Celtics,BOS,2012-01-14,0,1.0,2.0,3.0
3004,1610612738,Celtics,BOS,2012-01-16,1,1.0,2.0,3.0
3030,1610612738,Celtics,BOS,2012-01-18,1,1.0,2.0,3.0
3058,1610612738,Celtics,BOS,2012-01-20,1,0.0,3.0,3.0
3094,1610612738,Celtics,BOS,2012-01-22,0,1.0,2.0,3.0
3106,1610612738,Celtics,BOS,2012-01-23,1,1.0,2.0,3.0
3160,1610612738,Celtics,BOS,2012-01-26,0,2.0,1.0,3.0
3166,1610612738,Celtics,BOS,2012-01-27,1,1.0,2.0,3.0
3204,1610612738,Celtics,BOS,2012-01-29,1,1.0,2.0,3.0
3238,1610612738,Celtics,BOS,2012-01-31,0,1.0,2.0,3.0
3254,1610612738,Celtics,BOS,2012-02-01,1,1.0,2.0,3.0
3294,1610612738,Celtics,BOS,2012-02-03,1,1.0,2.0,3.0
3330,1610612738,Celtics,BOS,2012-02-05,1,0.0,3.0,3.0
3356,1610612738,Celtics,BOS,2012-02-07,1,0.0,3.0,3.0
3388,1610612738,Celtics,BOS,2012-02-09,1,0.0,3.0,3.0
3396,1610612738,Celtics,BOS,2012-02-10,0,1.0,2.0,3.0
3438,1610612738,Celtics,BOS,2012-02-12,1,1.0,2.0,3.0
3482,1610612738,Celtics,BOS,2012-02-15,1,0.0,2.0,2.0
3506,1610612738,Celtics,BOS,2012-02-16,0,1.0,2.0,3.0
3544,1610612738,Celtics,BOS,2012-02-19,0,2.0,1.0,3.0
3568,1610612738,Celtics,BOS,2012-02-20,0,3.0,0.0,3.0
3600,1610612738,Celtics,BOS,2012-02-22,0,3.0,0.0,3.0
3626,1610612738,Celtics,BOS,2012-02-28,0,1.0,0.0,1.0
3648,1610612738,Celtics,BOS,2012-02-29,1,1.0,1.0,2.0
3678,1610612738,Celtics,BOS,2012-03-02,1,1.0,2.0,3.0
3712,1610612738,Celtics,BOS,2012-03-04,1,0.0,3.0,3.0
3750,1610612738,Celtics,BOS,2012-03-06,1,0.0,3.0,3.0
3760,1610612738,Celtics,BOS,2012-03-07,0,1.0,2.0,3.0
3792,1610612738,Celtics,BOS,2012-03-09,1,1.0,2.0,3.0
3828,1610612738,Celtics,BOS,2012-03-11,0,2.0,1.0,3.0
3854,1610612738,Celtics,BOS,2012-03-12,0,2.0,1.0,3.0
3894,1610612738,Celtics,BOS,2012-03-14,0,3.0,0.0,3.0
3922,1610612738,Celtics,BOS,2012-03-16,0,3.0,0.0,3.0
3940,1610612738,Celtics,BOS,2012-03-17,0,3.0,0.0,3.0
3964,1610612738,Celtics,BOS,2012-03-19,0,3.0,0.0,3.0
4008,1610612738,Celtics,BOS,2012-03-22,0,2.0,0.0,2.0
4030,1610612738,Celtics,BOS,2012-03-23,0,3.0,0.0,3.0
4062,1610612738,Celtics,BOS,2012-03-25,1,2.0,1.0,3.0
4078,1610612738,Celtics,BOS,2012-03-26,0,3.0,1.0,4.0
4114,1610612738,Celtics,BOS,2012-03-28,1,1.0,2.0,3.0
4150,1610612738,Celtics,BOS,2012-03-30,0,2.0,1.0,3.0
4177,1610612738,Celtics,BOS,2012-04-01,1,1.0,2.0,3.0
4222,1610612738,Celtics,BOS,2012-04-04,1,0.0,2.0,2.0
4246,1610612738,Celtics,BOS,2012-04-05,0,1.0,2.0,3.0
4274,1610612738,Celtics,BOS,2012-04-07,0,2.0,1.0,3.0
4292,1610612738,Celtics,BOS,2012-04-08,1,2.0,2.0,4.0
4327,1610612738,Celtics,BOS,2012-04-10,0,2.0,1.0,3.0
4340,1610612738,Celtics,BOS,2012-04-11,1,2.0,2.0,4.0
4368,1610612738,Celtics,BOS,2012-04-13,0,2.0,1.0,3.0
4396,1610612738,Celtics,BOS,2012-04-14,0,3.0,1.0,4.0
4410,1610612738,Celtics,BOS,2012-04-15,0,3.0,1.0,4.0
4450,1610612738,Celtics,BOS,2012-04-17,0,4.0,0.0,4.0
4468,1610612738,Celtics,BOS,2012-04-18,1,3.0,1.0,4.0
4496,1610612738,Celtics,BOS,2012-04-20,0,2.0,1.0,3.0
4555,1610612738,Celtics,BOS,2012-04-24,1,1.0,1.0,2.0
4578,1610612738,Celtics,BOS,2012-04-26,1,0.0,2.0,2.0
4610,1610612738,Celtics,BOS,2012-04-29,0,1.0,1.0,2.0
4626,1610612738,Celtics,BOS,2012-05-01,0,2.0,0.0,2.0
4642,1610612738,Celtics,BOS,2012-05-04,1,1.0,1.0,2.0
4658,1610612738,Celtics,BOS,2012-05-06,1,0.0,2.0,2.0
4670,1610612738,Celtics,BOS,2012-05-08,0,1.0,2.0,3.0
4680,1610612738,Celtics,BOS,2012-05-10,1,1.0,2.0,3.0
4688,1610612738,Celtics,BOS,2012-05-12,1,1.0,2.0,3.0
4694,1610612738,Celtics,BOS,2012-05-14,1,0.0,3.0,3.0
4702,1610612738,Celtics,BOS,2012-05-16,0,1.0,2.0,3.0
4710,1610612738,Celtics,BOS,2012-05-18,0,2.0,1.0,3.0
4722,1610612738,Celtics,BOS,2012-05-21,1,1.0,1.0,2.0
4728,1610612738,Celtics,BOS,2012-05-23,0,1.0,1.0,2.0
4732,1610612738,Celtics,BOS,2012-05-26,1,1.0,1.0,2.0
4737,1610612738,Celtics,BOS,2012-05-28,0,1.0,1.0,2.0
4741,1610612738,Celtics,BOS,2012-05-30,0,2.0,1.0,3.0
4745,1610612738,Celtics,BOS,2012-06-01,1,2.0,1.0,3.0
4749,1610612738,Celtics,BOS,2012-06-03,1,1.0,2.0,3.0
4753,1610612738,Celtics,BOS,2012-06-05,0,1.0,2.0,3.0
4757,1610612738,Celtics,BOS,2012-06-07,1,1.0,2.0,3.0
4759,1610612738,Celtics,BOS,2012-06-09,0,2.0,1.0,3.0
4773,1610612738,Celtics,BOS,2012-10-30,0,1.0,0.0,1.0
4800,1610612738,Celtics,BOS,2012-11-02,1,1.0,1.0,2.0
4820,1610612738,Celtics,BOS,2012-11-03,0,2.0,1.0,3.0
4874,1610612738,Celtics,BOS,2012-11-07,1,1.0,1.0,2.0
4906,1610612738,Celtics,BOS,2012-11-09,1,0.0,2.0,2.0
4938,1610612738,Celtics,BOS,2012-11-10,0,1.0,2.0,3.0
4962,1610612738,Celtics,BOS,2012-11-12,0,2.0,1.0,3.0
4986,1610612738,Celtics,BOS,2012-11-14,1,2.0,1.0,3.0
5004,1610612738,Celtics,BOS,2012-11-15,0,2.0,1.0,3.0
5028,1610612738,Celtics,BOS,2012-11-17,1,1.0,2.0,3.0
5054,1610612738,Celtics,BOS,2012-11-18,0,2.0,2.0,4.0
5088,1610612738,Celtics,BOS,2012-11-21,1,1.0,2.0,3.0
5112,1610612738,Celtics,BOS,2012-11-23,1,0.0,2.0,2.0
5156,1610612738,Celtics,BOS,2012-11-25,0,1.0,2.0,3.0
5190,1610612738,Celtics,BOS,2012-11-28,1,1.0,1.0,2.0
5218,1610612738,Celtics,BOS,2012-11-30,1,0.0,2.0,2.0
5244,1610612738,Celtics,BOS,2012-12-01,0,1.0,2.0,3.0
5286,1610612738,Celtics,BOS,2012-12-05,1,1.0,1.0,2.0
5308,1610612738,Celtics,BOS,2012-12-07,0,1.0,1.0,2.0
5338,1610612738,Celtics,BOS,2012-12-08,1,1.0,2.0,3.0
5398,1610612738,Celtics,BOS,2012-12-12,1,0.0,2.0,2.0
5432,1610612738,Celtics,BOS,2012-12-14,0,1.0,1.0,2.0
5456,1610612738,Celtics,BOS,2012-12-15,0,2.0,1.0,3.0
5488,1610612738,Celtics,BOS,2012-12-18,0,3.0,0.0,3.0
5508,1610612738,Celtics,BOS,2012-12-19,1,2.0,1.0,3.0
5532,1610612738,Celtics,BOS,2012-12-21,1,1.0,2.0,3.0
5578,1610612738,Celtics,BOS,2012-12-25,0,1.0,1.0,2.0
5614,1610612738,Celtics,BOS,2012-12-27,0,2.0,0.0,2.0
5660,1610612738,Celtics,BOS,2012-12-29,0,3.0,0.0,3.0
5666,1610612738,Celtics,BOS,2012-12-30,0,3.0,0.0,3.0
5702,1610612738,Celtics,BOS,2013-01-02,1,2.0,1.0,3.0
5732,1610612738,Celtics,BOS,2013-01-04,1,0.0,2.0,2.0
5744,1610612738,Celtics,BOS,2013-01-05,0,1.0,2.0,3.0
5776,1610612738,Celtics,BOS,2013-01-07,0,2.0,1.0,3.0
5804,1610612738,Celtics,BOS,2013-01-09,1,2.0,1.0,3.0
5828,1610612738,Celtics,BOS,2013-01-11,1,1.0,2.0,3.0
5880,1610612738,Celtics,BOS,2013-01-14,1,0.0,2.0,2.0
5912,1610612738,Celtics,BOS,2013-01-16,1,0.0,2.0,2.0
5934,1610612738,Celtics,BOS,2013-01-18,1,0.0,3.0,3.0
5972,1610612738,Celtics,BOS,2013-01-20,0,1.0,2.0,3.0
5994,1610612738,Celtics,BOS,2013-01-22,0,2.0,1.0,3.0
6026,1610612738,Celtics,BOS,2013-01-24,1,2.0,1.0,3.0
6032,1610612738,Celtics,BOS,2013-01-25,0,2.0,1.0,3.0
6071,1610612738,Celtics,BOS,2013-01-27,1,1.0,2.0,3.0
6110,1610612738,Celtics,BOS,2013-01-30,1,0.0,2.0,2.0
6138,1610612738,Celtics,BOS,2013-02-01,1,0.0,2.0,2.0
6176,1610612738,Celtics,BOS,2013-02-03,1,0.0,3.0,3.0
6208,1610612738,Celtics,BOS,2013-02-06,0,1.0,1.0,2.0
6234,1610612738,Celtics,BOS,2013-02-07,1,1.0,2.0,3.0
6276,1610612738,Celtics,BOS,2013-02-10,1,1.0,2.0,3.0
6292,1610612738,Celtics,BOS,2013-02-11,0,1.0,2.0,3.0
6324,1610612738,Celtics,BOS,2013-02-13,1,1.0,2.0,3.0
6356,1610612738,Celtics,BOS,2013-02-19,0,1.0,0.0,1.0
6382,1610612738,Celtics,BOS,2013-02-20,0,2.0,0.0,2.0
6408,1610612738,Celtics,BOS,2013-02-22,0,3.0,0.0,3.0
6442,1610612738,Celtics,BOS,2013-02-24,0,3.0,0.0,3.0
6452,1610612738,Celtics,BOS,2013-02-25,0,3.0,0.0,3.0
6502,1610612738,Celtics,BOS,2013-03-01,1,1.0,1.0,2.0
6560,1610612738,Celtics,BOS,2013-03-05,0,1.0,1.0,2.0
6570,1610612738,Celtics,BOS,2013-03-06,0,2.0,0.0,2.0
6602,1610612738,Celtics,BOS,2013-03-08,1,2.0,1.0,3.0
6636,1610612738,Celtics,BOS,2013-03-10,0,2.0,1.0,3.0
6664,1610612738,Celtics,BOS,2013-03-12,0,2.0,1.0,3.0
6686,1610612738,Celtics,BOS,2013-03-13,1,2.0,1.0,3.0
6728,1610612738,Celtics,BOS,2013-03-16,1,1.0,2.0,3.0
6765,1610612738,Celtics,BOS,2013-03-18,1,0.0,2.0,2.0
6794,1610612738,Celtics,BOS,2013-03-20,0,1.0,2.0,3.0
6826,1610612738,Celtics,BOS,2013-03-22,0,2.0,1.0,3.0
6840,1610612738,Celtics,BOS,2013-03-23,0,3.0,0.0,3.0
6876,1610612738,Celtics,BOS,2013-03-26,1,2.0,1.0,3.0
6888,1610612738,Celtics,BOS,2013-03-27,0,2.0,1.0,3.0
6918,1610612738,Celtics,BOS,2013-03-29,1,1.0,2.0,3.0
6966,1610612738,Celtics,BOS,2013-03-31,0,2.0,1.0,3.0
6978,1610612738,Celtics,BOS,2013-04-01,0,2.0,1.0,3.0
6998,1610612738,Celtics,BOS,2013-04-03,1,2.0,1.0,3.0
7022,1610612738,Celtics,BOS,2013-04-05,1,1.0,2.0,3.0
7062,1610612738,Celtics,BOS,2013-04-07,1,0.0,3.0,3.0
7104,1610612738,Celtics,BOS,2013-04-10,1,0.0,2.0,2.0
7129,1610612738,Celtics,BOS,2013-04-12,0,1.0,1.0,2.0
7150,1610612738,Celtics,BOS,2013-04-13,0,2.0,1.0,3.0
7198,1610612738,Celtics,BOS,2013-04-17,0,2.0,0.0,2.0
7228,1610612738,Celtics,BOS,2013-04-20,0,2.0,0.0,2.0
7250,1610612738,Celtics,BOS,2013-04-23,0,2.0,0.0,2.0
7266,1610612738,Celtics,BOS,2013-04-26,1,1.0,1.0,2.0
7282,1610612738,Celtics,BOS,2013-04-28,1,0.0,2.0,2.0
7298,1610612738,Celtics,BOS,2013-05-01,0,1.0,1.0,2.0
7308,1610612738,Celtics,BOS,2013-05-03,1,1.0,1.0,2.0
7408,1610612738,Celtics,BOS,2013-10-30,0,1.0,0.0,1.0
7444,1610612738,Celtics,BOS,2013-11-01,1,1.0,1.0,2.0
7478,1610612738,Celtics,BOS,2013-11-03,0,2.0,1.0,3.0
7494,1610612738,Celtics,BOS,2013-11-04,0,2.0,1.0,3.0
7524,1610612738,Celtics,BOS,2013-11-06,1,2.0,1.0,3.0
7546,1610612738,Celtics,BOS,2013-11-08,0,2.0,1.0,3.0
7575,1610612738,Celtics,BOS,2013-11-09,0,2.0,1.0,3.0
7598,1610612738,Celtics,BOS,2013-11-11,1,2.0,1.0,3.0
7622,1610612738,Celtics,BOS,2013-11-13,1,1.0,2.0,3.0
7652,1610612738,Celtics,BOS,2013-11-15,1,0.0,3.0,3.0
7680,1610612738,Celtics,BOS,2013-11-16,0,1.0,2.0,3.0
7714,1610612738,Celtics,BOS,2013-11-19,0,2.0,1.0,3.0
7736,1610612738,Celtics,BOS,2013-11-20,0,3.0,0.0,3.0
7754,1610612738,Celtics,BOS,2013-11-22,1,2.0,1.0,3.0
7776,1610612738,Celtics,BOS,2013-11-23,0,3.0,1.0,4.0
7800,1610612738,Celtics,BOS,2013-11-25,0,2.0,1.0,3.0
7830,1610612738,Celtics,BOS,2013-11-27,1,2.0,1.0,3.0
7860,1610612738,Celtics,BOS,2013-11-29,1,1.0,2.0,3.0
7890,1610612738,Celtics,BOS,2013-11-30,0,1.0,2.0,3.0
7920,1610612738,Celtics,BOS,2013-12-03,1,1.0,2.0,3.0
7960,1610612738,Celtics,BOS,2013-12-06,1,0.0,2.0,2.0
7992,1610612738,Celtics,BOS,2013-12-08,0,1.0,1.0,2.0
8022,1610612738,Celtics,BOS,2013-12-10,0,2.0,1.0,3.0
8032,1610612738,Celtics,BOS,2013-12-11,1,2.0,1.0,3.0
8060,1610612738,Celtics,BOS,2013-12-13,1,1.0,2.0,3.0
8110,1610612738,Celtics,BOS,2013-12-16,1,0.0,2.0,2.0
8140,1610612738,Celtics,BOS,2013-12-18,1,0.0,2.0,2.0
8180,1610612738,Celtics,BOS,2013-12-21,1,0.0,2.0,2.0
8202,1610612738,Celtics,BOS,2013-12-22,0,1.0,2.0,3.0
8266,1610612738,Celtics,BOS,2013-12-28,1,0.0,1.0,1.0
8314,1610612738,Celtics,BOS,2013-12-31,1,0.0,2.0,2.0
8344,1610612738,Celtics,BOS,2014-01-02,0,1.0,1.0,2.0
8362,1610612738,Celtics,BOS,2014-01-03,1,1.0,2.0,3.0
8398,1610612738,Celtics,BOS,2014-01-05,0,2.0,1.0,3.0
8428,1610612738,Celtics,BOS,2014-01-07,0,2.0,1.0,3.0
8450,1610612738,Celtics,BOS,2014-01-08,0,3.0,0.0,3.0
8476,1610612738,Celtics,BOS,2014-01-10,0,3.0,0.0,3.0
8496,1610612738,Celtics,BOS,2014-01-11,0,4.0,0.0,4.0
8506,1610612738,Celtics,BOS,2014-01-13,1,2.0,1.0,3.0
8532,1610612738,Celtics,BOS,2014-01-15,1,1.0,2.0,3.0
8566,1610612738,Celtics,BOS,2014-01-17,1,0.0,3.0,3.0
8598,1610612738,Celtics,BOS,2014-01-19,0,1.0,2.0,3.0
8629,1610612738,Celtics,BOS,2014-01-21,0,2.0,1.0,3.0
8644,1610612738,Celtics,BOS,2014-01-22,0,3.0,0.0,3.0
8666,1610612738,Celtics,BOS,2014-01-24,1,2.0,1.0,3.0
8710,1610612738,Celtics,BOS,2014-01-26,1,1.0,2.0,3.0
8734,1610612738,Celtics,BOS,2014-01-28,0,1.0,2.0,3.0
8748,1610612738,Celtics,BOS,2014-01-29,1,1.0,2.0,3.0
8810,1610612738,Celtics,BOS,2014-02-02,1,0.0,2.0,2.0
8844,1610612738,Celtics,BOS,2014-02-05,0,1.0,1.0,2.0
8878,1610612738,Celtics,BOS,2014-02-07,1,1.0,1.0,2.0
8908,1610612738,Celtics,BOS,2014-02-09,1,1.0,2.0,3.0
8926,1610612738,Celtics,BOS,2014-02-10,0,1.0,2.0,3.0
8952,1610612738,Celtics,BOS,2014-02-12,1,1.0,2.0,3.0
9006,1610612738,Celtics,BOS,2014-02-19,0,1.0,0.0,1.0
9040,1610612738,Celtics,BOS,2014-02-21,0,2.0,0.0,2.0
9054,1610612738,Celtics,BOS,2014-02-22,0,3.0,0.0,3.0
9082,1610612738,Celtics,BOS,2014-02-24,0,3.0,0.0,3.0
9100,1610612738,Celtics,BOS,2014-02-26,1,2.0,1.0,3.0
9146,1610612738,Celtics,BOS,2014-03-01,1,0.0,2.0,2.0
9206,1610612738,Celtics,BOS,2014-03-05,1,0.0,2.0,2.0
9232,1610612738,Celtics,BOS,2014-03-07,1,0.0,2.0,2.0
9266,1610612738,Celtics,BOS,2014-03-09,1,0.0,3.0,3.0
9292,1610612738,Celtics,BOS,2014-03-11,0,1.0,2.0,3.0
9316,1610612738,Celtics,BOS,2014-03-12,1,1.0,2.0,3.0
9342,1610612738,Celtics,BOS,2014-03-14,1,1.0,2.0,3.0
9372,1610612738,Celtics,BOS,2014-03-16,0,1.0,2.0,3.0
9394,1610612738,Celtics,BOS,2014-03-17,0,2.0,1.0,3.0
9411,1610612738,Celtics,BOS,2014-03-19,1,2.0,1.0,3.0
9444,1610612738,Celtics,BOS,2014-03-21,0,2.0,1.0,3.0
9518,1610612738,Celtics,BOS,2014-03-26,1,0.0,1.0,1.0
9544,1610612738,Celtics,BOS,2014-03-28,0,1.0,1.0,2.0
9586,1610612738,Celtics,BOS,2014-03-30,1,1.0,2.0,3.0
9604,1610612738,Celtics,BOS,2014-03-31,0,2.0,1.0,3.0
9630,1610612738,Celtics,BOS,2014-04-02,0,2.0,1.0,3.0
9658,1610612738,Celtics,BOS,2014-04-04,1,2.0,1.0,3.0
9684,1610612738,Celtics,BOS,2014-04-05,0,2.0,1.0,3.0
9728,1610612738,Celtics,BOS,2014-04-09,0,2.0,0.0,2.0
9752,1610612738,Celtics,BOS,2014-04-11,1,1.0,1.0,2.0
9782,1610612738,Celtics,BOS,2014-04-12,0,2.0,1.0,3.0
9804,1610612738,Celtics,BOS,2014-04-14,0,2.0,1.0,3.0
9840,1610612738,Celtics,BOS,2014-04-16,1,2.0,1.0,3.0
10046,1610612738,Celtics,BOS,2014-10-29,1,0.0,1.0,1.0
10102,1610612738,Celtics,BOS,2014-11-01,0,1.0,1.0,2.0
10126,1610612738,Celtics,BOS,2014-11-03,0,2.0,0.0,2.0
10152,1610612738,Celtics,BOS,2014-11-05,1,2.0,1.0,3.0
10182,1610612738,Celtics,BOS,2014-11-07,1,1.0,2.0,3.0
10206,1610612738,Celtics,BOS,2014-11-08,0,1.0,2.0,3.0
10256,1610612738,Celtics,BOS,2014-11-12,1,1.0,1.0,2.0
10284,1610612738,Celtics,BOS,2014-11-14,1,0.0,2.0,2.0
10330,1610612738,Celtics,BOS,2014-11-17,1,0.0,2.0,2.0
10358,1610612738,Celtics,BOS,2014-11-19,0,1.0,1.0,2.0
10386,1610612738,Celtics,BOS,2014-11-21,0,2.0,1.0,3.0
10422,1610612738,Celtics,BOS,2014-11-23,1,2.0,1.0,3.0
10480,1610612738,Celtics,BOS,2014-11-28,1,0.0,1.0,1.0
10516,1610612738,Celtics,BOS,2014-11-30,1,0.0,2.0,2.0
10542,1610612738,Celtics,BOS,2014-12-02,0,1.0,2.0,3.0
10564,1610612738,Celtics,BOS,2014-12-03,1,1.0,2.0,3.0
10592,1610612738,Celtics,BOS,2014-12-05,1,1.0,2.0,3.0
10622,1610612738,Celtics,BOS,2014-12-07,1,0.0,3.0,3.0
10638,1610612738,Celtics,BOS,2014-12-08,0,1.0,2.0,3.0
10666,1610612738,Celtics,BOS,2014-12-10,0,2.0,1.0,3.0
10696,1610612738,Celtics,BOS,2014-12-12,1,2.0,1.0,3.0
10748,1610612738,Celtics,BOS,2014-12-15,0,1.0,1.0,2.0
10776,1610612738,Celtics,BOS,2014-12-17,1,1.0,1.0,2.0
10804,1610612738,Celtics,BOS,2014-12-19,1,1.0,2.0,3.0
10843,1610612738,Celtics,BOS,2014-12-21,0,1.0,2.0,3.0
10870,1610612738,Celtics,BOS,2014-12-23,0,2.0,1.0,3.0
10898,1610612738,Celtics,BOS,2014-12-26,1,1.0,1.0,2.0
10924,1610612738,Celtics,BOS,2014-12-27,0,2.0,1.0,3.0
10984,1610612738,Celtics,BOS,2014-12-31,1,1.0,1.0,2.0

In [10]:
'''from functools import reduce
data_frames = [df_game_count_day4, df_game_count_day7, df_game_count_day12, df_game_count_day999]

df_merged = reduce(lambda  left,right: pd.merge(left,right,on=column_names_common_list,
                                            how='outer'), data_frames)
p(df_merged)'''

"from functools import reduce\ndata_frames = [df_game_count_day4, df_game_count_day7, df_game_count_day12, df_game_count_day999]\n\ndf_merged = reduce(lambda  left,right: pd.merge(left,right,on=column_names_common_list,\n                                            how='outer'), data_frames)\np(df_merged)"

In [11]:
datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)

datapath_df = os.path.join(datapath, '66B_away_game_count_percentage_day2_5_8_12_999_home_game_count_percentage_day2_5_8_12_999_2010_2018.csv')
if not os.path.exists(datapath_df):
    df.to_csv(datapath_df, index=False)

In [12]:
df_66B_away_game_count_percentage_day2_5_8_12_999_home_game_count_percentage_day2_5_8_12_999_2010_2018_readback = rcp('66B_away_game_count_percentage_day2_5_8_12_999_home_game_count_percentage_day2_5_8_12_999_2010_2018.csv')
p(df_66B_away_game_count_percentage_day2_5_8_12_999_home_game_count_percentage_day2_5_8_12_999_2010_2018_readback)

(20532, 97)

,game_id,TEAM_NAME,game_date,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,matchup,season_type,season,season_year,latitude,longitude,game_latitude,game_longitude,travel_distance,game_time_zone,time_zone,time_zone_diff,time_zone_diff_abs,city_proper_metro_area,Country/Region,city_proper_metro_area_GDP_bil,city_proper_metro_area_GDP_bil1,away_game_count_day2,home_game_count_day2,game_count_day2,away_game_percent_day2,home_game_percent_day2,away_game_count_day5,home_game_count_day5,game_count_day5,away_game_percent_day5,home_game_percent_day5,away_game_count_day8,home_game_count_day8,game_count_day8,away_game_percent_day8,home_game_percent_day8,away_game_count_day12,home_game_count_day12,game_count_day12,away_game_percent_day12,home_game_percent_day12,away_game_count_day999,home_game_count_day999,game_count_day999,away_game_percent_day999,home_game_percent_day999
0,21000001,Heat,2010-10-26,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,BOS vs. MIA,Regular Season,2010-11,2010,25.774173,-80.193620,42.360253,-71.058291,1257.755091,America/New_York,America/New_York,0.0,0.0,Miami,United States,377.5,262.7,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.00,0.00,1.0,0.0,1.0,1.000000,0.000000
1,21000001,Celtics,2010-10-26,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,BOS vs. MIA,Regular Season,2010-11,2010,42.360253,-71.058291,42.360253,-71.058291,0.000000,America/New_York,America/New_York,0.0,0.0,Boston,United States,463.570,560.1,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.00,1.00,0.0,1.0,1.0,0.000000,1.000000
2,21000002,Suns,2010-10-26,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,PHX vs. POR,Regular Season,2010-11,2010,33.448437,-112.074142,45.520247,-122.674195,1005.606855,America/Los_Angeles,America/Phoenix,0.0,0.0,Phoenix,United States,255.211,607.1,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.00,0.00,1.0,0.0,1.0,1.000000,0.000000
3,21000002,Trail Blazers,2010-10-26,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,PHX vs. POR,Regular Season,2010-11,2010,45.520247,-122.674195,45.520247,-122.674195,0.000000,America/Los_Angeles,America/Los_Angeles,0.0,0.0,Portland,United States,164.419,158.5,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.00,1.00,0.0,1.0,1.0,0.000000,1.000000
4,21000003,Rockets,2010-10-26,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,HOU vs. LAL,Regular Season,2010-11,2010,29.758938,-95.367697,34.053691,-118.242766,1371.020326,America/Los_Angeles,America/Chicago,-2.0,2.0,Houston,United States,478.778,883.2,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.00,0.00,1.0,0.0,1.0,1.000000,0.000000
20527,41700402,Warriors,2018-06-03,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,37.854666,-122.292136,0.000000,America/Los_Angeles,America/Los_Angeles,0.0,0.0,San Francisco,United States,995,631.0,0.0,1.0,1.0,0.0,1.0,0.0,2.0,2.0,0.0,1.0,1.0,2.0,3.0,0.333333,0.666667,2.0,3.0,5.0,0.40,0.60,49.0,52.0,101.0,0.485149,0.514851
20528,41700403,Cavaliers,2018-06-06,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0.0,0.0,Cleveland,United States,135,215.1,0.0,1.0,1.0,0.0,1.0,1.0,1.0,2.0,0.5,0.5,2.0,1.0,3.0,0.666667,0.333333,3.0,1.0,4.0,0.75,0.25,52.0,51.0,103.0,0.504854,0.495146
20529,41700403,Warriors,2018-06-06,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3.0,3.0,San Francisco,United States,995,631.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,2.0,0.5,0.5,1.0,2.0,3.0,0.333333,0.666667,2.0,3.0,5.0,0.40,0.60,50.0,52.0,102.0,0.490196,0.509804
20530,41700404,Cavaliers,2018-06-08,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0.0,0.0,Cleveland,United States,135,215.1,0.0,1.0,1.0,0.0,1.0,0.0,2.0,2.0,0.0,1.0,1.0,2.0,3.0,0.333333,0.666667,2.0,2.0,4.0,0.50,0.50,52.0,52.0,104.0,0.500000,0.500000
20531,41700404,Warriors,2018-06-08,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3.0,3.0,San Francisco,United States,995,631.0,1.0,0.0,1.0,1.0,0.0,2.0,0.0,2.0,1.0,0.0,2.0,1.0,3.0,0.666667,0.333333,3.0,2.0,5.0,0.60,0.40,51.0,52.0,103.0,0.495146,0.504854