In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import sqlite3

pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

pd.set_option('max_colwidth', None)

In [2]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:90% !important; }</style>"))

In [3]:
#return the first 5 and last 5 rows of this dataframe
def p(df_):
    if df_.shape[0] > 6:
        print(df_.shape)
        return pd.concat([df_.head(), df_.tail()])
    else:
        return df_

def rcp(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'processed_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'processed_data', file_), parse_dates=pd_)
    
def rcr(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'raw_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'raw_data', file_), parse_dates=pd_)

In [4]:
df_5bsa0918 = pd.read_csv(os.path.join('..', 'processed_data', '5boxscoreadvancedv2_2009_2018.csv'))
print(df_5bsa0918.shape)
p(df_5bsa0918)

(291643, 31)
(291643, 31)

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
0,20900001,1.610613e+09,BOS,Boston,1718.0,Paul Pierce,F,NaN,37:59,95.3,97.4,96.5,98.6,-1.2,-1.3,0.053,0.50,4.8,0.028,0.270,0.151,9.5,0.538,0.661,0.233,0.239,96.88,94.76,78.97,76.0,0.189
1,20900001,1.610613e+09,BOS,Boston,708.0,Kevin Garnett,F,NaN,33:05,95.6,95.5,101.0,103.1,-5.4,-7.6,0.059,1.00,7.1,0.097,0.233,0.164,7.1,0.500,0.553,0.178,0.181,95.96,95.03,79.19,66.0,0.147
2,20900001,1.610613e+09,BOS,Boston,2570.0,Kendrick Perkins,C,NaN,25:42,99.2,100.0,108.2,104.3,-9.1,-4.3,0.077,0.33,9.1,0.000,0.050,0.024,27.3,0.571,0.605,0.196,0.198,86.53,87.77,73.14,47.0,0.030
3,20900001,1.610613e+09,BOS,Boston,951.0,Ray Allen,G,NaN,42:21,105.2,108.8,105.4,105.1,-0.2,3.7,0.120,1.00,12.5,0.000,0.054,0.028,12.5,0.375,0.440,0.236,0.240,91.50,90.12,75.10,80.0,0.051
4,20900001,1.610613e+09,BOS,Boston,200765.0,Rajon Rondo,G,NaN,34:29,92.7,94.1,98.0,97.1,-5.3,-3.0,0.526,5.00,50.0,0.061,0.125,0.092,10.0,0.500,0.500,0.130,0.133,95.63,95.36,79.46,68.0,0.158
291638,41700404,1.610613e+09,CLE,Cleveland,1626204.0,Larry Nance Jr.,NaN,NaN,23:12,93.4,97.6,93.1,95.2,0.3,2.3,0.333,0.00,33.3,0.176,0.077,0.133,0.0,0.429,0.444,0.148,0.146,88.76,85.87,71.56,41.0,0.139
291639,41700404,1.610613e+09,CLE,Cleveland,1626224.0,Cedi Osman,NaN,NaN,4:03,100.0,114.3,76.1,75.0,23.9,39.3,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.333,0.333,0.333,0.333,94.10,88.89,74.07,7.0,0.000
291640,41700404,1.610613e+09,CLE,Cleveland,101181.0,Jose Calderon,NaN,NaN,4:03,100.0,114.3,76.1,75.0,23.9,39.3,0.250,0.00,50.0,0.000,0.200,0.100,0.0,0.000,0.000,0.111,0.111,94.10,88.89,74.07,7.0,0.174
291641,41700404,1.610613e+09,CLE,Cleveland,1627790.0,Ante Zizic,NaN,NaN,1:40,100.0,133.3,0.0,0.0,100.0,133.3,0.000,0.00,0.0,0.333,0.000,0.200,0.0,1.000,1.000,0.400,0.400,100.80,86.40,72.00,3.0,2.250
291642,41700404,1.610613e+09,CLE,Cleveland,203903.0,Jordan Clarkson,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN

In [5]:
df_5bsa0918.PLAYER_NAME = df_5bsa0918.PLAYER_NAME.fillna('')
df_5bsa0918.MIN = df_5bsa0918.MIN.fillna('00:00')
df_5bsa0918.MIN = pd.to_timedelta('00:' + df_5bsa0918.MIN).astype('timedelta64[s]').astype('float64') / 60
df_5bsa0918.TEAM_ID = df_5bsa0918.TEAM_ID.fillna(0).astype('int64')
print(df_5bsa0918.shape)
p(df_5bsa0918)

(291643, 31)
(291643, 31)

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
0,20900001,1610612738,BOS,Boston,1718.0,Paul Pierce,F,NaN,37.983333,95.3,97.4,96.5,98.6,-1.2,-1.3,0.053,0.50,4.8,0.028,0.270,0.151,9.5,0.538,0.661,0.233,0.239,96.88,94.76,78.97,76.0,0.189
1,20900001,1610612738,BOS,Boston,708.0,Kevin Garnett,F,NaN,33.083333,95.6,95.5,101.0,103.1,-5.4,-7.6,0.059,1.00,7.1,0.097,0.233,0.164,7.1,0.500,0.553,0.178,0.181,95.96,95.03,79.19,66.0,0.147
2,20900001,1610612738,BOS,Boston,2570.0,Kendrick Perkins,C,NaN,25.700000,99.2,100.0,108.2,104.3,-9.1,-4.3,0.077,0.33,9.1,0.000,0.050,0.024,27.3,0.571,0.605,0.196,0.198,86.53,87.77,73.14,47.0,0.030
3,20900001,1610612738,BOS,Boston,951.0,Ray Allen,G,NaN,42.350000,105.2,108.8,105.4,105.1,-0.2,3.7,0.120,1.00,12.5,0.000,0.054,0.028,12.5,0.375,0.440,0.236,0.240,91.50,90.12,75.10,80.0,0.051
4,20900001,1610612738,BOS,Boston,200765.0,Rajon Rondo,G,NaN,34.483333,92.7,94.1,98.0,97.1,-5.3,-3.0,0.526,5.00,50.0,0.061,0.125,0.092,10.0,0.500,0.500,0.130,0.133,95.63,95.36,79.46,68.0,0.158
291638,41700404,1610612739,CLE,Cleveland,1626204.0,Larry Nance Jr.,NaN,NaN,23.200000,93.4,97.6,93.1,95.2,0.3,2.3,0.333,0.00,33.3,0.176,0.077,0.133,0.0,0.429,0.444,0.148,0.146,88.76,85.87,71.56,41.0,0.139
291639,41700404,1610612739,CLE,Cleveland,1626224.0,Cedi Osman,NaN,NaN,4.050000,100.0,114.3,76.1,75.0,23.9,39.3,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.333,0.333,0.333,0.333,94.10,88.89,74.07,7.0,0.000
291640,41700404,1610612739,CLE,Cleveland,101181.0,Jose Calderon,NaN,NaN,4.050000,100.0,114.3,76.1,75.0,23.9,39.3,0.250,0.00,50.0,0.000,0.200,0.100,0.0,0.000,0.000,0.111,0.111,94.10,88.89,74.07,7.0,0.174
291641,41700404,1610612739,CLE,Cleveland,1627790.0,Ante Zizic,NaN,NaN,1.666667,100.0,133.3,0.0,0.0,100.0,133.3,0.000,0.00,0.0,0.333,0.000,0.200,0.0,1.000,1.000,0.400,0.400,100.80,86.40,72.00,3.0,2.250
291642,41700404,1610612739,CLE,Cleveland,203903.0,Jordan Clarkson,NaN,DNP - Coach's Decision,0.000000,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN

In [6]:
path = os.path.join('..', 'processed_data', '3game_id_game_date_team_id.csv')
path
df_3gigdti = pd.read_csv(path, parse_dates=['game_date'])
df_3gigdti0918 = df_3gigdti[(df_3gigdti.season == '2009-10') |
                            (df_3gigdti.season == '2010-11') |
                            (df_3gigdti.season == '2011-12') |
                            (df_3gigdti.season == '2012-13') |
                            (df_3gigdti.season == '2013-14') |
                            (df_3gigdti.season == '2014-15') |
                            (df_3gigdti.season == '2015-16') |
                            (df_3gigdti.season == '2016-17') |
                            (df_3gigdti.season == '2017-18')]
print(df_3gigdti0918.shape)
p(df_3gigdti0918)

(23158, 27)
(23158, 27)

,game_id,game_date,team_id,is_home,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,season_year,season_type,season
7380,20900001,2009-10-27,1610612739,t,0.0,240,29.0,70.0,0.414,6.0,17.0,0.353,25.0,32.0,1.0,6.0,26.0,32,17.0,7.0,9.0,13.0,22.0,89,2009,Regular Season,2009-10
7381,20900001,2009-10-27,1610612738,f,1.0,240,32.0,72.0,0.444,9.0,19.0,0.474,22.0,26.0,1.0,6.0,32.0,38,20.0,9.0,8.0,14.0,27.0,95,2009,Regular Season,2009-10
7382,20900002,2009-10-27,1610612742,t,0.0,240,30.0,76.0,0.395,4.0,18.0,0.222,27.0,34.0,1.0,11.0,31.0,42,16.0,6.0,9.0,9.0,20.0,91,2009,Regular Season,2009-10
7383,20900002,2009-10-27,1610612764,f,1.0,240,39.0,84.0,0.464,4.0,13.0,0.308,20.0,24.0,1.0,9.0,37.0,46,19.0,6.0,4.0,9.0,29.0,102,2009,Regular Season,2009-10
7384,20900003,2009-10-27,1610612757,t,1.0,240,33.0,77.0,0.429,10.0,21.0,0.476,20.0,22.0,1.0,12.0,39.0,51,23.0,9.0,12.0,26.0,27.0,96,2009,Regular Season,2009-10
31033,41700402,2018-06-03,1610612744,t,1.0,240,47.0,82.0,0.573,15.0,36.0,0.417,13.0,21.0,1.0,7.0,34.0,41,28.0,3.0,8.0,12.0,25.0,122,2017,Playoffs,2017-18
31034,41700403,2018-06-06,1610612744,f,1.0,240,42.0,81.0,0.519,9.0,26.0,0.346,17.0,19.0,1.0,6.0,31.0,37,27.0,6.0,5.0,10.0,20.0,110,2017,Playoffs,2017-18
31035,41700403,2018-06-06,1610612739,t,0.0,240,40.0,92.0,0.435,9.0,31.0,0.290,13.0,17.0,1.0,15.0,32.0,47,20.0,6.0,4.0,13.0,18.0,102,2017,Playoffs,2017-18
31036,41700404,2018-06-08,1610612739,t,0.0,240,30.0,87.0,0.345,8.0,27.0,0.296,17.0,25.0,1.0,17.0,27.0,44,21.0,5.0,5.0,11.0,22.0,85,2017,Playoffs,2017-18
31037,41700404,2018-06-08,1610612744,f,1.0,240,39.0,86.0,0.453,14.0,38.0,0.368,16.0,16.0,1.0,10.0,34.0,44,25.0,7.0,13.0,8.0,24.0,108,2017,Playoffs,2017-18

In [7]:
#filter for 2009-10 thru 2017-18 seasons: df_5bsa1018
df_5bsa0918 = pd.merge(df_3gigdti0918[['game_id', 'game_date', 'team_id', 'season']], df_5bsa0918.rename(columns={'GAME_ID':'game_id', 'TEAM_ID':'team_id'}), on=['game_id', 'team_id'], how='inner')
print(df_5bsa0918.shape)
p(df_5bsa0918)

(291642, 33)
(291642, 33)

,game_id,game_date,team_id,season,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
0,20900001,2009-10-27,1610612739,2009-10,CLE,Cleveland,2544.0,LeBron James,F,NaN,44.916667,99.8,101.2,99.2,101.2,0.5,0.0,0.471,1.60,19.5,0.000,0.100,0.049,12.2,0.636,0.685,0.351,0.354,93.44,91.90,76.59,86.0,0.240
1,20900001,2009-10-27,1610612739,2009-10,CLE,Cleveland,2760.0,Anderson Varejao,F,NaN,32.833333,109.3,108.2,115.5,116.1,-6.1,-7.9,0.050,0.00,8.3,0.179,0.091,0.140,0.0,0.333,0.418,0.167,0.168,89.69,89.89,74.91,61.0,0.040
2,20900001,2009-10-27,1610612739,2009-10,CLE,Cleveland,406.0,Shaquille O'Neal,C,NaN,28.800000,98.5,96.4,95.5,96.2,3.0,0.1,0.083,1.00,7.1,0.000,0.385,0.200,7.1,0.455,0.421,0.213,0.221,89.33,89.99,75.00,55.0,0.121
3,20900001,2009-10-27,1610612739,2009-10,CLE,Cleveland,1515.0,Anthony Parker,G,NaN,40.166667,108.0,107.8,101.4,103.9,6.6,3.9,0.160,1.33,23.5,0.000,0.083,0.042,17.6,0.444,0.506,0.153,0.157,93.10,92.03,76.69,77.0,0.076
4,20900001,2009-10-27,1610612739,2009-10,CLE,Cleveland,2590.0,Mo Williams,G,NaN,35.033333,98.9,92.8,109.1,107.2,-10.2,-14.5,0.167,1.50,18.8,0.000,0.000,0.000,12.5,0.375,0.564,0.176,0.187,90.74,94.53,78.77,69.0,0.044
291637,41700404,2018-06-08,1610612744,2017-18,GSW,Golden State,201156.0,Nick Young,NaN,NaN,8.983333,131.9,133.3,98.8,106.3,33.0,27.1,0.000,0.00,0.0,0.000,0.067,0.042,0.0,0.375,0.375,0.190,0.198,94.66,90.92,75.77,18.0,0.000
291638,41700404,2018-06-08,1610612744,2017-18,GSW,Golden State,2561.0,David West,NaN,NaN,7.600000,97.6,92.9,128.7,135.7,-31.1,-42.9,0.333,0.00,50.0,0.000,0.000,0.000,0.0,1.000,1.000,0.071,0.075,88.67,88.42,73.68,14.0,0.039
291639,41700404,2018-06-08,1610612744,2017-18,GSW,Golden State,1626172.0,Kevon Looney,NaN,NaN,2.783333,68.0,66.7,100.0,120.0,-32.0,-53.3,0.000,0.00,0.0,0.250,0.000,0.125,0.0,0.500,0.500,0.222,0.254,102.44,94.85,79.04,6.0,0.214
291640,41700404,2018-06-08,1610612744,2017-18,GSW,Golden State,2585.0,Zaza Pachulia,NaN,NaN,2.783333,68.0,66.7,100.0,120.0,-32.0,-53.3,0.000,0.00,0.0,0.000,0.250,0.125,33.3,0.000,0.532,0.333,0.381,102.44,94.85,79.04,6.0,0.143
291641,41700404,2018-06-08,1610612744,2017-18,GSW,Golden State,1627775.0,Patrick McCaw,NaN,NaN,2.783333,68.0,66.7,100.0,120.0,-32.0,-53.3,0.000,0.00,0.0,0.250,0.000,0.125,0.0,0.000,0.000,0.000,0.000,102.44,94.85,79.04,6.0,0.071

In [8]:
#pd.merge(df_5bsa1018.rename(columns={'GAME_ID':'game_id'}), df_3gigdti1018[['game_id', 'game_date', 'season']].drop_duplicates(), on=['game_id'] , how='inner')

In [9]:
'''df_5bsa0918 = df_5bsa0918[df_5bsa0918.MIN == 0]
print(df_5bsa0918[df_5bsa0918.MIN == 0].shape)
p(df_5bsa0918[df_5bsa0918.MIN == 0])'''

'df_5bsa0918 = df_5bsa0918[df_5bsa0918.MIN == 0]\nprint(df_5bsa0918[df_5bsa0918.MIN == 0].shape)\np(df_5bsa0918[df_5bsa0918.MIN == 0])'

In [10]:
df_5bsa0918.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 291642 entries, 0 to 291641
Data columns (total 33 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   game_id            291642 non-null  int64
 1   game_date          291642 non-null  datetime64[ns]
 2   team_id            291642 non-null  int64
 3   season             291642 non-null  object
 4   TEAM_ABBREVIATION  291642 non-null  object
 5   TEAM_CITY          291642 non-null  object
 6   PLAYER_ID          291642 non-null  float64
 7   PLAYER_NAME        291642 non-null  object
 8   START_POSITION     115780 non-null  object
 9   COMMENT            49511 non-null   object
 10  MIN                291642 non-null  float64
 11  E_OFF_RATING       242144 non-null  float64
 12  OFF_RATING         291642 non-null  float64
 13  E_DEF_RATING       242144 non-null  float64
 14  DEF_RATING         291642 non-null  float64
 15  E_NET_RATING       242144 non-null  float64
 16  NET_RATING         291642 non-null  float64
 17  AST_PCT            242144 non-null  float64
 18  AST_TOV            242144 non-null  float64
 19  AST_RATIO          242144 non-null  float64
 20  OREB_PCT           291642 non-null  float64
 21  DREB_PCT           291642 non-null  float64
 22  REB_PCT            291642 non-null  float64
 23  TM_TOV_PCT         242144 non-null  float64
 24  EFG_PCT            242144 non-null  float64
 25  TS_PCT             242144 non-null  float64
 26  USG_PCT            291642 non-null  float64
 27  E_USG_PCT          291642 non-null  float64
 28  E_PACE             242144 non-null  float64
 29  PACE               242144 non-null  float64
 30  PACE_PER40         242144 non-null  float64
 31  POSS               291642 non-null  float64
 32  PIE                242144 non-null  float64
dtypes: datetime64[ns](1), float64(24), int64(2), object(6)
memory usage: 75.7+ MB

In [11]:
df_5bsa0918[['E_OFF_RATING', 'OFF_RATING',
       'E_DEF_RATING', 'DEF_RATING', 'E_NET_RATING', 'NET_RATING', 'AST_PCT',
       'AST_TOV', 'AST_RATIO', 'OREB_PCT', 'DREB_PCT', 'REB_PCT', 'TM_TOV_PCT',
       'EFG_PCT', 'TS_PCT', 'USG_PCT', 'E_USG_PCT', 'E_PACE', 'PACE',
       'PACE_PER40', 'POSS', 'PIE']] = df_5bsa0918[['E_OFF_RATING', 'OFF_RATING',
       'E_DEF_RATING', 'DEF_RATING', 'E_NET_RATING', 'NET_RATING', 'AST_PCT',
       'AST_TOV', 'AST_RATIO', 'OREB_PCT', 'DREB_PCT', 'REB_PCT', 'TM_TOV_PCT',
       'EFG_PCT', 'TS_PCT', 'USG_PCT', 'E_USG_PCT', 'E_PACE', 'PACE',
       'PACE_PER40', 'POSS', 'PIE']].fillna(0)

In [12]:
print(df_5bsa0918.shape)
p(df_5bsa0918)

(291642, 33)
(291642, 33)

,game_id,game_date,team_id,season,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
0,20900001,2009-10-27,1610612739,2009-10,CLE,Cleveland,2544.0,LeBron James,F,NaN,44.916667,99.8,101.2,99.2,101.2,0.5,0.0,0.471,1.60,19.5,0.000,0.100,0.049,12.2,0.636,0.685,0.351,0.354,93.44,91.90,76.59,86.0,0.240
1,20900001,2009-10-27,1610612739,2009-10,CLE,Cleveland,2760.0,Anderson Varejao,F,NaN,32.833333,109.3,108.2,115.5,116.1,-6.1,-7.9,0.050,0.00,8.3,0.179,0.091,0.140,0.0,0.333,0.418,0.167,0.168,89.69,89.89,74.91,61.0,0.040
2,20900001,2009-10-27,1610612739,2009-10,CLE,Cleveland,406.0,Shaquille O'Neal,C,NaN,28.800000,98.5,96.4,95.5,96.2,3.0,0.1,0.083,1.00,7.1,0.000,0.385,0.200,7.1,0.455,0.421,0.213,0.221,89.33,89.99,75.00,55.0,0.121
3,20900001,2009-10-27,1610612739,2009-10,CLE,Cleveland,1515.0,Anthony Parker,G,NaN,40.166667,108.0,107.8,101.4,103.9,6.6,3.9,0.160,1.33,23.5,0.000,0.083,0.042,17.6,0.444,0.506,0.153,0.157,93.10,92.03,76.69,77.0,0.076
4,20900001,2009-10-27,1610612739,2009-10,CLE,Cleveland,2590.0,Mo Williams,G,NaN,35.033333,98.9,92.8,109.1,107.2,-10.2,-14.5,0.167,1.50,18.8,0.000,0.000,0.000,12.5,0.375,0.564,0.176,0.187,90.74,94.53,78.77,69.0,0.044
291637,41700404,2018-06-08,1610612744,2017-18,GSW,Golden State,201156.0,Nick Young,NaN,NaN,8.983333,131.9,133.3,98.8,106.3,33.0,27.1,0.000,0.00,0.0,0.000,0.067,0.042,0.0,0.375,0.375,0.190,0.198,94.66,90.92,75.77,18.0,0.000
291638,41700404,2018-06-08,1610612744,2017-18,GSW,Golden State,2561.0,David West,NaN,NaN,7.600000,97.6,92.9,128.7,135.7,-31.1,-42.9,0.333,0.00,50.0,0.000,0.000,0.000,0.0,1.000,1.000,0.071,0.075,88.67,88.42,73.68,14.0,0.039
291639,41700404,2018-06-08,1610612744,2017-18,GSW,Golden State,1626172.0,Kevon Looney,NaN,NaN,2.783333,68.0,66.7,100.0,120.0,-32.0,-53.3,0.000,0.00,0.0,0.250,0.000,0.125,0.0,0.500,0.500,0.222,0.254,102.44,94.85,79.04,6.0,0.214
291640,41700404,2018-06-08,1610612744,2017-18,GSW,Golden State,2585.0,Zaza Pachulia,NaN,NaN,2.783333,68.0,66.7,100.0,120.0,-32.0,-53.3,0.000,0.00,0.0,0.000,0.250,0.125,33.3,0.000,0.532,0.333,0.381,102.44,94.85,79.04,6.0,0.143
291641,41700404,2018-06-08,1610612744,2017-18,GSW,Golden State,1627775.0,Patrick McCaw,NaN,NaN,2.783333,68.0,66.7,100.0,120.0,-32.0,-53.3,0.000,0.00,0.0,0.250,0.000,0.125,0.0,0.000,0.000,0.000,0.000,102.44,94.85,79.04,6.0,0.071

In [13]:
df_5bsa0918.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 291642 entries, 0 to 291641
Data columns (total 33 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   game_id            291642 non-null  int64
 1   game_date          291642 non-null  datetime64[ns]
 2   team_id            291642 non-null  int64
 3   season             291642 non-null  object
 4   TEAM_ABBREVIATION  291642 non-null  object
 5   TEAM_CITY          291642 non-null  object
 6   PLAYER_ID          291642 non-null  float64
 7   PLAYER_NAME        291642 non-null  object
 8   START_POSITION     115780 non-null  object
 9   COMMENT            49511 non-null   object
 10  MIN                291642 non-null  float64
 11  E_OFF_RATING       291642 non-null  float64
 12  OFF_RATING         291642 non-null  float64
 13  E_DEF_RATING       291642 non-null  float64
 14  DEF_RATING         291642 non-null  float64
 15  E_NET_RATING       291642 non-null  float64
 16  NET_RATING         291642 non-null  float64
 17  AST_PCT            291642 non-null  float64
 18  AST_TOV            291642 non-null  float64
 19  AST_RATIO          291642 non-null  float64
 20  OREB_PCT           291642 non-null  float64
 21  DREB_PCT           291642 non-null  float64
 22  REB_PCT            291642 non-null  float64
 23  TM_TOV_PCT         291642 non-null  float64
 24  EFG_PCT            291642 non-null  float64
 25  TS_PCT             291642 non-null  float64
 26  USG_PCT            291642 non-null  float64
 27  E_USG_PCT          291642 non-null  float64
 28  E_PACE             291642 non-null  float64
 29  PACE               291642 non-null  float64
 30  PACE_PER40         291642 non-null  float64
 31  POSS               291642 non-null  float64
 32  PIE                291642 non-null  float64
dtypes: datetime64[ns](1), float64(24), int64(2), object(6)
memory usage: 75.7+ MB

In [14]:
df_5bsa0918.reset_index(drop=True, inplace=True)

In [15]:
df_5bsa0918_pip = df_5bsa0918[['PLAYER_ID','PLAYER_NAME']].drop_duplicates()
print(df_5bsa0918_pip.shape)
p(df_5bsa0918_pip)

(1146, 2)
(1146, 2)

        PLAYER_ID       PLAYER_NAME
0          2544.0      LeBron James
1          2760.0  Anderson Varejao
2           406.0  Shaquille O'Neal
3          1515.0    Anthony Parker
4          2590.0       Mo Williams
267202  1628449.0     Chris Boucher
271464   204179.0     Omari Johnson
272108  1628410.0     Edmond Sumner
272218   201281.0      Andre Ingram
272517  1628935.0     Aaron Jackson

In [16]:
print(df_5bsa0918_pip.value_counts('PLAYER_ID').shape)
p(df_5bsa0918_pip.value_counts('PLAYER_ID'))

(1146,)
(1146,)

PLAYER_ID
1628935.0    1
201569.0     1
201563.0     1
201564.0     1
201565.0     1
203491.0     1
203490.0     1
203489.0     1
203488.0     1
255.0        1
dtype: int64

In [17]:
print(df_5bsa0918_pip.value_counts('PLAYER_NAME').shape)
p(df_5bsa0918_pip.value_counts('PLAYER_NAME'))

(1142,)
(1142,)

PLAYER_NAME
Chris Johnson         2
Mike James            2
Tony Mitchell         2
Chris Wright          2
Zydrunas Ilgauskas    1
Marshall Plumlee      1
Marreese Speights     1
Marqus Blakely        1
Marquis Teague        1
AJ Hammons            1
dtype: int64

In [18]:
playerl = list(df_5bsa0918_pip.value_counts('PLAYER_NAME')[df_5bsa0918_pip.value_counts('PLAYER_NAME') > 1].reset_index().PLAYER_NAME)
playerl

['Chris Johnson', 'Mike James', 'Tony Mitchell', 'Chris Wright']

In [19]:
#two different players
df_5bsa0918[df_5bsa0918.PLAYER_NAME.str.contains(playerl[0])]

,game_id,game_date,team_id,season,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
45355,21000661,2011-01-24,1610612757,2010-11,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
45810,21000680,2011-01-27,1610612757,2010-11,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
46672,21000716,2011-02-01,1610612757,2010-11,POR,Portland,202419.0,Chris Johnson,NaN,NaN,4.316667,87.2,75.0,159.9,137.5,-72.7,-62.5,0.000,0.00,0.0,0.000,0.500,0.250,0.0,0.000,1.136,0.111,0.127,76.50,88.96,74.13,8.0,0.296
46913,21000726,2011-02-02,1610612757,2010-11,POR,Portland,202419.0,Chris Johnson,NaN,NaN,12.150000,94.7,96.2,127.6,118.5,-32.9,-22.4,0.143,1.00,16.7,0.000,0.222,0.087,16.7,0.333,0.258,0.179,0.176,101.70,104.71,87.25,26.0,-0.032
50119,21000860,2011-02-24,1610612738,2010-11,BOS,Boston,202419.0,Chris Johnson,NaN,NaN,16.850000,93.7,91.2,106.6,100.0,-12.9,-8.8,0.000,0.00,0.0,0.000,0.063,0.029,20.0,0.667,0.773,0.143,0.147,93.89,98.28,81.90,34.0,0.057
50536,21000878,2011-02-26,1610612738,2010-11,BOS,Boston,202419.0,Chris Johnson,NaN,NaN,3.516667,69.4,71.4,87.2,85.7,-17.8,-14.3,0.000,0.00,0.0,0.000,0.250,0.125,0.0,0.000,0.000,0.000,0.000,96.09,95.55,79.62,7.0,0.222
50886,21000892,2011-02-28,1610612738,2010-11,BOS,Boston,202419.0,Chris Johnson,NaN,NaN,3.083333,94.9,100.0,124.2,133.3,-29.3,-33.3,0.500,0.00,100.0,0.000,0.500,0.200,0.0,0.000,0.000,0.000,0.000,99.32,93.41,77.84,6.0,0.200
51198,21000905,2011-03-02,1610612738,2010-11,BOS,Boston,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
51497,21000918,2011-03-04,1610612738,2010-11,BOS,Boston,202419.0,Chris Johnson,NaN,NaN,8.966667,115.3,106.7,108.4,114.3,6.9,-7.6,0.000,0.00,0.0,0.167,0.125,0.143,100.0,0.000,0.000,0.059,0.063,76.73,77.69,64.74,15.0,0.018
53508,21001002,2011-03-15,1610612757,2010-11,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
53855,21001016,2011-03-17,1610612757,2010-11,POR,Portland,202419.0,Chris Johnson,NaN,NaN,3.716667,137.5,122.2,77.3,75.0,60.2,47.2,0.000,0.00,0.0,0.250,0.000,0.143,50.0,1.000,1.000,0.182,0.200,101.77,109.78,91.48,9.0,0.143
54288,21001034,2011-03-19,1610612757,2010-11,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
54492,21001043,2011-03-20,1610612757,2010-11,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
54704,21001052,2011-03-22,1610612757,2010-11,POR,Portland,202419.0,Chris Johnson,NaN,NaN,15.766667,71.1,75.0,75.1,71.4,-4.0,3.6,0.000,0.00,0.0,0.000,0.176,0.094,40.0,1.000,0.931,0.135,0.132,102.04,101.98,84.98,32.0,0.176
55329,21001078,2011-03-25,1610612757,2010-11,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
55676,21001092,2011-03-27,1610612757,2010-11,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
55845,21001099,2011-03-28,1610612757,2010-11,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
56193,21001114,2011-03-30,1610612757,2010-11,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
56576,21001130,2011-04-01,1610612757,2010-11,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
57017,21001148,2011-04-03,1610612757,2010-11,POR,Portland,202419.0,Chris Johnson,NaN,NaN,5.933333,33.3,33.3,130.1,127.3,-96.8,-93.9,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.500,0.500,0.154,0.167,92.06,93.03,77.53,12.0,0.000
57293,21001160,2011-04-05,1610612757,2010-11,POR,Portland,202419.0,Chris Johnson,NaN,NaN,6.816667,85.4,78.6,117.1,121.4,-31.7,-42.9,0.000,0.00,0.0,0.100,0.143,0.118,50.0,0.000,1.136,0.118,0.126,96.38,98.49,82.07,14.0,0.028
57664,21001175,2011-04-07,1610612757,2010-11,POR,Portland,202419.0,Chris Johnson,NaN,NaN,9.900000,91.9,100.0,94.1,95.0,-2.1,5.0,0.000,0.00,0.0,0.111,0.222,0.167,50.0,1.000,1.000,0.083,0.084,101.72,96.97,80.81,20.0,0.128
57950,21001187,2011-04-08,1610612757,2010-11,POR,Portland,202419.0,Chris Johnson,NaN,NaN,6.983333,58.3,50.0,110.0,107.1,-51.6,-57.1,0.000,0.00,0.0,0.000,0.167,0.071,0.0,0.000,0.000,0.071,0.083,88.12,96.23,80.19,14.0,-0.148
58601,21001214,2011-04-12,1610612757,2010-11,POR,Portland,202419.0,Chris Johnson,NaN,NaN,0.566667,200.0,200.0,0.0,0.0,200.0,200.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,42.23,168.92,140.76,1.0,0.000
58893,21001227,2011-04-13,1610612757,2010-11,POR,Portland,202419.0,Chris Johnson,F,NaN,40.316667,92.3,95.0,117.5,120.0,-25.2,-25.0,0.042,0.50,6.7,0.163,0.132,0.149,13.3,0.125,0.347,0.143,0.144,97.67,95.25,79.37,80.0,0.029
59384,21100016,2011-12-26,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,NaN,1.833333,75.0,75.0,212.8,200.0,-137.8,-125.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.250,0.250,101.59,104.73,87.27,4.0,-0.167
59512,21100021,2011-12-27,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,NaN,8.233333,130.8,121.4,142.5,137.5,-11.7,-16.1,0.000,0.00,0.0,0.143,0.091,0.111,0.0,1.000,1.000,0.063,0.067,82.90,87.45,72.87,14.0,0.078
59937,21100037,2011-12-29,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
60644,21100065,2012-01-01,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
61017,21100079,2012-01-03,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
61477,21100097,2012-01-05,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
61750,21100108,2012-01-06,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,NaN,8.833333,101.5,100.0,124.2,127.8,-22.7,-27.8,0.000,0.00,0.0,0.111,0.111,0.111,0.0,0.000,0.725,0.150,0.152,101.18,100.53,83.77,19.0,0.180
62157,21100124,2012-01-08,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,NaN,2.983333,101.7,87.5,133.1,128.6,-31.4,-41.1,0.000,0.00,0.0,0.000,0.000,0.000,100.0,0.000,0.000,0.125,0.145,109.73,120.67,100.56,8.0,-0.292
62581,21100140,2012-01-10,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
62890,21100152,2012-01-11,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
63251,21100166,2012-01-13,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,NaN,4.666667,73.5,72.7,101.4,90.0,-27.8,-17.3,0.000,0.00,0.0,0.143,0.250,0.182,0.0,1.000,1.000,0.083,0.084,101.62,108.00,90.00,11.0,0.185
63511,21100176,2012-01-14,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
63859,21100190,2012-01-16,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
64323,21100208,2012-01-18,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
64543,21100216,2012-01-20,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
64888,21100230,2012-01-21,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,NaN,0.866667,0.0,0.0,56.8,50.0,-56.8,-50.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.500,0.500,103.33,109.92,91.60,2.0,1.000
65403,21100250,2012-01-23,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,NaN,1.350000,100.0,75.0,200.0,200.0,-100.0,-125.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,106.67,124.44,103.70,4.0,0.000
65558,21100256,2012-01-24,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,NaN,3.566667,67.6,60.0,126.0,130.0,-58.4,-70.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.500,0.500,0.200,0.225,129.20,134.58,112.15,10.0,0.000
65894,21100269,2012-01-25,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
66254,21100283,2012-01-27,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,NaN,5.950000,119.0,114.3,97.8,100.0,21.3,14.3,0.167,0.00,25.0,0.000,0.000,0.000,0.0,0.333,0.333,0.188,0.194,111.97,112.94,94.12,14.0,0.038
66822,21100305,2012-01-30,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
67311,21100324,2012-02-01,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,NaN,5.066667,64.3,63.6,83.6,81.8,-19.3,-18.2,0.000,0.00,0.0,0.000,0.143,0.100,50.0,1.000,0.694,0.167,0.168,102.51,104.21,86.84,11.0,0.000
67439,21100329,2012-02-02,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
68097,21100354,2012-02-04,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,NaN,2.750000,85.0,71.4,153.1,150.0,-68.0,-78.6,0.000,0.00,0.0,0.000,0.000,0.000,33.3,0.000,0.532,0.429,0.510,102.63,113.45,94.55,7.0,-0.083
68392,21100366,2012-02-06,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
68839,21100383,2012-02-08,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
69188,21100397,2012-02-10,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
69405,21100405,2012-02-11,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
69961,21100427,2012-02-14,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
70290,21100440,2012-02-15,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,NaN,2.500000,0.0,0.0,160.0,160.0,-160.0,-160.0,0.000,0.00,0.0,0.000,0.500,0.143,0.0,0.000,0.000,0.000,0.000,105.60,105.60,88.00,6.0,0.133
70410,21100444,2012-02-16,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
70778,21100459,2012-02-18,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,NaN,2.000000,166.7,125.0,87.2,100.0,79.5,25.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,77.28,84.00,70.00,4.0,0.000
71306,21100479,2012-02-20,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,NaN,2.616667,187.1,157.1,83.3,83.3,103.7,73.8,0.000,0.00,0.0,0.000,1.000,0.500,0.0,1.000,1.000,0.125,0.145,108.96,119.24,99.36,7.0,0.216
71448,21100485,2012-02-21,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,NaN,7.950000,116.5,110.0,113.4,115.8,3.1,-5.8,0.000,0.00,0.0,0.000,0.167,0.105,0.0,0.333,0.333,0.143,0.151,115.56,117.74,98.11,20.0,0.000
72371,21100521,2012-02-29,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,NaN,9.533333,105.6,123.5,101.6,88.2,4.0,35.3,0.000,0.00,0.0,0.077,0.000,0.053,25.0,0.500,0.694,0.167,0.168,87.28,85.67,71.39,17.0,0.036
72540,21100527,2012-03-01,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
73000,21100545,2012-03-03,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,NaN,1.450000,61.5,75.0,80.0,100.0,-18.5,-25.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.568,0.200,0.205,163.53,132.41,110.34,4.0,0.143
74048,21100586,2012-03-09,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,NaN,8.600000,145.9,153.3,86.5,80.0,59.5,73.3,0.000,0.00,0.0,0.500,0.000,0.176,25.0,0.667,0.667,0.200,0.202,82.72,83.72,69.77,15.0,0.176
74265,21100594,2012-03-10,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
74925,21100620,2012-03-13,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,NaN,3.800000,78.8,77.8,78.8,77.8,0.0,0.0,0.000,0.00,0.0,0.000,0.250,0.100,0.0,0.000,0.000,0.000,0.000,112.17,113.68,94.74,9.0,0.040
75143,21100628,2012-03-14,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,NaN,8.500000,62.1,60.0,148.6,152.6,-86.5,-92.6,0.000,0.00,0.0,0.091,0.125,0.105,50.0,0.500,0.615,0.182,0.188,109.67,110.12,91.76,20.0,-0.046
76658,21100688,2012-03-21,1610612740,2011-12,NOH,New Orleans,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
76848,21100695,2012-03-22,1610612740,2011-12,NOH,New Orleans,202419.0,Chris Johnson,NaN,NaN,4.866667,114.2,100.0,174.2,170.0,-60.0,-70.0,0.000,0.00,0.0,0.000,0.000,0.000,50.0,0.000,1.136,0.182,0.205,91.33,98.63,82.19,10.0,0.000
77347,21100715,2012-03-24,1610612740,2011-12,NOH,New Orleans,202419.0,Chris Johnson,NaN,NaN,4.750000,94.8,100.0,55.6,62.5,39.2,37.5,0.000,0.00,0.0,0.000,0.333,0.222,0.0,0.000,0.000,0.000,0.000,88.12,80.84,67.37,8.0,0.400
77866,21100735,2012-03-26,1610612740,2011-12,NOH,New Orleans,202419.0,Chris Johnson,NaN,NaN,20.750000,113.1,117.5,107.2,109.8,5.8,7.7,0.000,0.00,0.0,0.154,0.222,0.194,20.0,0.667,0.671,0.213,0.215,96.60,93.69,78.07,40.0,0.104
78300,21100752,2012-03-28,1610612740,2011-12,NOH,New Orleans,202419.0,Chris Johnson,NaN,NaN,13.533333,118.2,118.2,92.4,87.0,25.8,31.2,0.000,0.00,0.0,0.000,0.133,0.074,50.0,0.500,0.500,0.160,0.160,77.37,79.78,66.49,22.0,-0.034
78379,21100755,2012-03-29,1610612740,2011-12,NOH,New Orleans,202419.0,Chris Johnson,NaN,NaN,8.733333,85.3,84.2,125.6,122.2,-40.3,-38.0,0.000,0.00,0.0,0.091,0.286,0.167,25.0,0.333,0.333,0.174,0.184,99.78,101.76,84.80,19.0,0.054
78723,21100769,2012-03-31,1610612740,2011-12,NOH,New Orleans,202419.0,Chris Johnson,NaN,NaN,26.233333,99.8,102.1,98.0,100.0,1.8,2.1,0.053,1.00,11.1,0.133,0.148,0.140,11.1,0.429,0.429,0.138,0.138,88.78,86.91,72.43,47.0,0.094
79062,21100782,2012-04-01,1610612740,2011-12,NOH,New Orleans,202419.0,Chris Johnson,NaN,NaN,3.550000,114.3,114.3,118.3,114.3,-4.1,0.0,0.000,0.00,0.0,0.000,1.000,0.333,100.0,0.000,0.000,0.143,0.143,93.03,94.65,78.87,7.0,-0.111
79654,21100805,2012-04-04,1610612740,2011-12,NOH,New Orleans,202419.0,Chris Johnson,NaN,DND - Concussion,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
80095,21100822,2012-04-06,1610612740,2011-12,NOH,New Orleans,202419.0,Chris Johnson,NaN,NWT - Concussion,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
80300,21100830,2012-04-07,1610612740,2011-12,NOH,New Orleans,202419.0,Chris Johnson,NaN,DND - Concussion,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
80738,21100847,2012-04-09,1610612740,2011-12,NOH,New Orleans,202419.0,Chris Johnson,NaN,DND - Concussion,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
99642,21200597,2013-01-19,1610612750,2012-13,MIN,Minnesota,202419.0,Chris Johnson,NaN,NaN,18.000000,124.2,111.8,116.1,122.6,8.0,-10.8,0.000,0.00,0.0,0.200,0.158,0.176,0.0,1.000,0.997,0.195,0.219,84.43,86.67,72.22,34.0,0.252
99924,21200608,2013-01-21,1610612750,2012-13,MIN,Minnesota,202419.0,Chris Johnson,NaN,NaN,9.683333,126.3,126.3,113.9,126.3,12.5,0.0,0.000,0.00,0.0,0.000,0.100,0.063,0.0,1.000,1.000,0.100,0.100,99.34,94.18,78.49,19.0,0.011
100242,21200621,2013-01-23,1610612763,2012-13,MEM,Memphis,203187.0,Chris Johnson,NaN,NaN,7.200000,135.1,128.6,79.9,84.6,55.2,44.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.500,0.500,0.211,0.218,90.22,89.96,74.97,14.0,0.105
100301,21200623,2013-01-23,1610612750,2012-13,MIN,Minnesota,202419.0,Chris Johnson,NaN,NaN,24.016667,99.1,100.0,117.1,115.6,-18.1,-15.6,0.125,0.00,16.7,0.048,0.185,0.125,0.0,0.600,0.600,0.204,0.202,90.76,90.92,75.76,46.0,0.175
100529,21200632,2013-01-25,1610612750,2012-13,MIN,Minnesota,202419.0,Chris Johnson,NaN,NaN,21.350000,100.4,102.3,109.4,111.1,-9.0,-8.8,0.000,0.00,0.0,0.111,0.105,0.109,18.2,0.500,0.521,0.196,0.197,101.80,100.05,83.37,44.0,0.026
100657,21200637,2013-01-25,1610612763,2012-13,MEM,Memphis,203187.0,Chris Johnson,NaN,NaN,21.516667,114.1,123.7,68.3,66.7,45.8,57.0,0.000,0.00,0.0,0.143,0.043,0.091,14.3,0.833,0.833,0.146,0.145,88.44,85.90,71.58,38.0,0.147
100848,21200645,2013-01-26,1610612750,2012-13,MIN,Minnesota,202419.0,Chris Johnson,NaN,NaN,12.516667,72.3,75.0,126.3,120.8,-54.0,-45.8,0.000,0.00,0.0,0.077,0.000,0.043,25.0,1.000,1.000,0.148,0.149,91.73,92.04,76.70,24.0,0.085
101116,21200655,2013-01-27,1610612763,2012-13,MEM,Memphis,203187.0,Chris Johnson,NaN,NaN,16.350000,85.3,87.1,62.0,63.3,23.3,23.8,0.125,1.00,14.3,0.000,0.150,0.071,14.3,0.600,0.600,0.146,0.151,91.38,89.50,74.59,31.0,0.500
101242,21200660,2013-01-28,1610612763,2012-13,MEM,Memphis,203187.0,Chris Johnson,NaN,NaN,25.883333,150.5,146.9,110.7,112.8,39.8,34.2,0.040,0.00,20.0,0.000,0.000,0.000,0.0,1.000,1.000,0.075,0.079,88.76,89.01,74.18,49.0,0.060

In [20]:
#two different players
df_5bsa0918[df_5bsa0918.PLAYER_NAME.str.contains(playerl[1])]

,game_id,game_date,team_id,season,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
46,20900002,2009-10-27,1610612764,2009-10,WAS,Washington,2229.0,Mike James,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
502,20900021,2009-10-30,1610612764,2009-10,WAS,Washington,2229.0,Mike James,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
765,20900032,2009-10-31,1610612764,2009-10,WAS,Washington,2229.0,Mike James,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
1208,20900051,2009-11-03,1610612764,2009-10,WAS,Washington,2229.0,Mike James,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
1481,20900062,2009-11-04,1610612764,2009-10,WAS,Washington,2229.0,Mike James,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
1745,20900073,2009-11-06,1610612764,2009-10,WAS,Washington,2229.0,Mike James,NaN,NaN,22.050000,103.1,104.5,80.1,84.1,23.1,20.5,0.200,3.00,21.4,0.000,0.043,0.020,7.1,0.250,0.307,0.200,0.205,98.83,95.78,79.82,44.0,0.018
2222,20900093,2009-11-08,1610612764,2009-10,WAS,Washington,2229.0,Mike James,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
10695,20900447,2009-12-28,1610612764,2009-10,WAS,Washington,2229.0,Mike James,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
13276,20900554,2010-01-12,1610612764,2009-10,WAS,Washington,2229.0,Mike James,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
14034,20900586,2010-01-16,1610612764,2009-10,WAS,Washington,2229.0,Mike James,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
15497,20900647,2010-01-24,1610612764,2009-10,WAS,Washington,2229.0,Mike James,NaN,NaN,19.083333,85.9,89.2,82.1,78.9,3.8,10.2,0.250,0.67,11.8,0.000,0.037,0.022,17.6,0.455,0.463,0.349,0.354,94.22,94.32,78.60,37.0,0.088
15760,20900658,2010-01-26,1610612764,2009-10,WAS,Washington,2229.0,Mike James,NaN,NaN,1.916667,77.3,75.0,175.0,140.0,-97.7,-65.0,0.000,0.00,0.0,1.000,0.000,0.250,50.0,0.000,0.568,0.400,0.410,98.67,112.70,93.91,4.0,-0.083
17288,20900721,2010-02-03,1610612764,2009-10,WAS,Washington,2229.0,Mike James,NaN,NaN,2.650000,80.0,80.0,250.0,200.0,-170.0,-120.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.200,0.200,81.51,90.57,75.47,5.0,-0.148
19045,20900794,2010-02-17,1610612764,2009-10,WAS,Washington,2229.0,Mike James,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
62748,21100147,2012-01-11,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,NaN,0.666667,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.500,1.000,71.64,107.46,89.55,2.0,0.000
63139,21100162,2012-01-13,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
63446,21100174,2012-01-14,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
63730,21100185,2012-01-16,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
64067,21100198,2012-01-17,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
64685,21100222,2012-01-20,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,NaN,8.133333,119.0,127.8,79.9,77.8,39.1,50.0,0.125,1.00,20.0,0.000,0.200,0.133,20.0,0.333,0.436,0.200,0.207,108.71,106.23,88.52,18.0,0.113
64950,21100232,2012-01-21,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,NaN,16.516667,124.0,126.7,93.7,93.5,30.4,33.1,0.833,10.00,58.8,0.000,0.067,0.037,5.9,0.750,0.750,0.212,0.208,89.51,88.64,73.86,30.0,0.230
65249,21100244,2012-01-23,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
65700,21100261,2012-01-25,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
66112,21100277,2012-01-27,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
69870,21100423,2012-02-14,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
70369,21100443,2012-02-16,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,NaN,17.350000,121.2,128.1,76.8,74.3,44.3,53.8,0.333,1.33,28.6,0.000,0.000,0.000,21.4,0.500,0.592,0.286,0.287,93.58,92.64,77.20,32.0,-0.009
70726,21100457,2012-02-18,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,NaN,23.016667,120.6,131.0,100.7,104.7,19.9,26.3,0.467,0.00,33.3,0.033,0.077,0.054,0.0,0.500,0.559,0.250,0.247,94.11,88.61,73.84,42.0,0.181
71060,21100470,2012-02-20,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,NaN,12.633333,72.0,69.2,99.2,96.0,-27.2,-26.8,0.400,1.00,18.2,0.053,0.000,0.030,18.2,0.500,0.500,0.273,0.290,93.47,96.89,80.74,26.0,0.080
71645,21100493,2012-02-22,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,NaN,8.183333,85.5,86.7,58.1,62.5,27.4,24.2,0.200,0.50,16.7,0.000,0.000,0.000,33.3,0.000,0.000,0.250,0.260,95.02,90.92,75.76,15.0,-0.750
75169,21100629,2012-03-14,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
75626,21100647,2012-03-16,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
75886,21100658,2012-03-17,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,NaN,4.416667,22.2,20.0,78.8,77.8,-56.6,-57.8,0.000,0.00,0.0,0.000,0.167,0.083,33.3,0.000,0.000,0.250,0.273,97.16,103.25,86.04,10.0,-0.545
76289,21100673,2012-03-19,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
76529,21100683,2012-03-21,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
79861,21100813,2012-04-05,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
80427,21100835,2012-04-08,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
80992,21100857,2012-04-10,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,NaN,0.100000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,225.00,450.00,375.00,1.0,0.000
81329,21100870,2012-04-12,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
82037,21100897,2012-04-15,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
82295,21100907,2012-04-16,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
82592,21100919,2012-04-18,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,NaN,4.866667,50.6,55.6,41.0,50.0,9.6,5.6,0.000,0.00,0.0,0.000,0.000,0.000,33.3,0.000,0.000,0.214,0.233,96.85,83.84,69.86,9.0,0.800
82994,21100934,2012-04-19,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
83293,21100946,2012-04-21,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
83991,21100973,2012-04-25,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
84286,21100984,2012-04-26,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,NaN,24.350000,139.1,141.9,69.3,75.0,69.9,66.9,0.200,1.33,28.6,0.000,0.059,0.041,21.4,0.714,0.714,0.208,0.209,90.17,85.76,71.46,43.0,0.118
97784,21200525,2013-01-09,1610612742,2012-13,DAL,Dallas,2229.0,Mike James,NaN,NaN,0.083333,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,300.00,600.00,500.00,1.0,0.000
97859,21200528,2013-01-10,1610612742,2012-13,DAL,Dallas,2229.0,Mike James,NaN,NaN,14.500000,137.9,127.8,105.1,97.1,32.8,30.7,0.000,0.00,0.0,0.000,0.083,0.038,0.0,0.333,0.333,0.075,0.080,107.15,115.82,96.52,36.0,0.016
98358,21200547,2013-01-12,1610612742,2012-13,DAL,Dallas,2229.0,Mike James,NaN,NaN,7.833333,66.0,60.0,105.6,107.1,-39.7,-47.1,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.176,0.192,85.30,88.85,74.04,15.0,-0.222
98680,21200560,2013-01-14,1610612742,2012-13,DAL,Dallas,2229.0,Mike James,NaN,NaN,1.750000,66.7,50.0,208.3,200.0,-141.7,-150.0,0.000,0.00,0.0,0.000,0.000,0.000,33.3,0.500,0.500,0.750,1.000,80.79,96.18,80.15,4.0,-0.143
99063,21200575,2013-01-16,1610612742,2012-13,DAL,Dallas,2229.0,Mike James,NaN,NaN,16.766667,124.0,116.2,71.4,70.3,52.6,45.9,0.500,0.00,33.3,0.000,0.043,0.023,0.0,0.125,0.205,0.250,0.265,101.78,105.96,88.30,37.0,-0.044
99500,21200592,2013-01-18,1610612742,2012-13,DAL,Dallas,2229.0,Mike James,NaN,NaN,22.250000,103.5,100.0,112.1,113.3,-8.6,-13.3,0.200,0.67,16.7,0.000,0.087,0.043,25.0,0.714,0.714,0.196,0.202,95.93,97.05,80.87,45.0,0.086
99770,21200602,2013-01-20,1610612742,2012-13,DAL,Dallas,2229.0,Mike James,NaN,NaN,12.883333,119.3,108.0,105.4,100.0,13.8,8.0,0.125,0.00,14.3,0.063,0.083,0.071,0.0,0.333,0.333,0.194,0.209,84.57,91.28,76.07,25.0,0.031
100707,21200639,2013-01-25,1610612742,2012-13,DAL,Dallas,2229.0,Mike James,NaN,NaN,11.633333,110.5,113.0,56.8,56.5,53.7,56.5,0.125,1.00,16.7,0.000,0.125,0.080,16.7,0.500,0.515,0.208,0.204,95.72,94.90,79.08,23.0,0.069
101157,21200657,2013-01-27,1610612742,2012-13,DAL,Dallas,2229.0,Mike James,NaN,NaN,1.466667,66.7,50.0,69.4,66.7,-2.8,-16.7,0.000,0.00,0.0,0.000,0.000,0.000,100.0,0.000,0.000,0.250,0.333,96.22,114.55,95.45,4.0,-0.333
101439,21200668,2013-01-29,1610612742,2012-13,DAL,Dallas,2229.0,Mike James,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
101837,21200683,2013-01-31,1610612742,2012-13,DAL,Dallas,2229.0,Mike James,NaN,NaN,0.033333,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,720.00,720.01,600.01,1.0,0.000
102114,21200694,2013-02-01,1610612742,2012-13,DAL,Dallas,2229.0,Mike James,NaN,NaN,16.833333,115.8,117.1,100.5,97.2,15.4,19.9,0.357,1.67,27.8,0.000,0.167,0.094,16.7,0.111,0.202,0.333,0.348,100.13,101.22,84.35,35.0,0.000
102579,21200712,2013-02-04,1610612742,2012-13,DAL,Dallas,2229.0,Mike James,NaN,NaN,12.066667,50.5,50.0,98.7,104.3,-48.2,-54.3,0.167,0.50,20.0,0.000,0.118,0.059,40.0,0.000,0.000,0.138,0.144,99.61,97.46,81.22,26.0,-0.069
103045,21200730,2013-02-06,1610612742,2012-13,DAL,Dallas,2229.0,Mike James,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
103556,21200750,2013-02-09,1610612742,2012-13,DAL,Dallas,2229.0,Mike James,NaN,NaN,4.216667,168.3,175.0,87.5,77.8,80.8,97.2,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,92.89,96.76,80.63,8.0,-0.048
104014,21200768,2013-02-11,1610612742,2012-13,DAL,Dallas,2229.0,Mike James,NaN,NaN,4.666667,77.8,87.5,100.0,88.9,-22.2,-1.4,0.333,0.00,33.3,0.000,0.000,0.000,0.0,0.000,0.000,0.222,0.222,87.43,87.43,72.86,8.0,-0.154
104450,21200785,2013-02-13,1610612742,2012-13,DAL,Dallas,2229.0,Mike James,NaN,NaN,9.583333,145.8,133.3,106.3,105.0,39.6,28.3,0.500,3.00,27.3,0.000,0.000,0.000,9.1,0.500,0.538,0.320,0.345,97.52,102.62,85.52,21.0,0.121
104970,21200806,2013-02-20,1610612742,2012-13,DAL,Dallas,2229.0,Mike James,NaN,NaN,16.983333,129.5,122.9,103.2,97.1,26.4,25.7,0.333,0.00,30.8,0.000,0.000,0.000,0.0,0.667,0.667,0.250,0.263,93.49,98.92,82.43,35.0,0.134
105272,21200818,2013-02-22,1610612742,2012-13,DAL,Dallas,2229.0,Mike James,NaN,NaN,20.966667,126.8,123.7,117.1,122.5,9.6,1.2,0.125,0.00,33.3,0.056,0.100,0.079,0.0,0.625,0.625,0.093,0.095,90.33,89.28,74.40,38.0,0.074
105574,21200830,2013-02-24,1610612742,2012-13,DAL,Dallas,2229.0,Mike James,NaN,NaN,19.283333,113.3,110.8,110.7,107.9,2.6,2.9,0.286,0.00,30.8,0.063,0.125,0.094,0.0,0.333,0.333,0.225,0.230,91.15,93.34,77.79,37.0,0.067
106030,21200848,2013-02-26,1610612742,2012-13,DAL,Dallas,2229.0,Mike James,NaN,NaN,10.983333,63.0,61.9,101.8,100.0,-38.8,-38.1,0.250,0.50,14.3,0.000,0.125,0.038,28.6,0.000,0.000,0.214,0.217,88.02,89.59,74.66,21.0,-0.235
106221,21200855,2013-02-27,1610612742,2012-13,DAL,Dallas,2229.0,Mike James,NaN,NaN,21.366667,77.8,81.0,70.0,68.2,7.7,12.8,0.300,3.00,20.0,0.000,0.000,0.000,6.7,0.200,0.276,0.250,0.251,97.23,96.60,80.50,42.0,0.063
106593,21200870,2013-03-01,1610612742,2012-13,DAL,Dallas,2229.0,Mike James,NaN,NaN,23.216667,117.1,118.2,89.6,87.0,27.5,31.2,0.167,0.00,27.3,0.000,0.053,0.026,0.0,0.429,0.444,0.170,0.172,92.04,93.04,77.53,44.0,0.026
106976,21200885,2013-03-03,1610612742,2012-13,DAL,Dallas,2229.0,Mike James,NaN,NaN,18.150000,113.0,107.9,142.3,142.1,-29.2,-34.2,0.222,1.00,16.7,0.059,0.000,0.032,16.7,0.688,0.688,0.233,0.242,98.18,100.51,83.75,38.0,0.064
107573,21200908,2013-03-06,1610612742,2012-13,DAL,Dallas,2229.0,Mike James,G,NaN,24.983333,123.4,122.4,113.2,111.8,10.2,10.7,0.273,6.00,40.0,0.048,0.087,0.068,6.7,0.500,0.500,0.173,0.174,95.13,96.09,80.07,49.0,0.060
107856,21200919,2013-03-08,1610612742,2012-13,DAL,Dallas,2229.0,Mike James,G,NaN,28.583333,105.2,103.4,113.6,121.1,-8.4,-17.7,0.143,1.00,21.4,0.000,0.028,0.016,21.4,0.750,0.750,0.175,0.180,99.65,97.40,81.17,59.0,0.052
108379,21200940,2013-03-10,1610612742,2012-13,DAL,Dallas,2229.0,Mike James,G,NaN,22.516667,100.3,95.7,65.8,63.0,34.5,32.6,0.167,0.00,33.3,0.000,0.000,0.000,0.0,0.250,0.250,0.120,0.128,93.75,98.06,81.72,46.0,-0.047
108723,21200953,2013-03-12,1610612742,2012-13,DAL,Dallas,2229.0,Mike James,G,NaN,31.483333,119.3,123.1,97.0,97.0,22.3,26.1,0.280,3.50,33.3,0.000,0.176,0.095,9.5,0.500,0.547,0.197,0.200,101.39,99.86,83.22,65.0,0.100
109081,21200967,2013-03-14,1610612742,2012-13,DAL,Dallas,2229.0,Mike James,G,NaN,35.466667,102.9,103.0,94.9,100.0,8.0,3.0,0.217,2.50,29.4,0.000,0.025,0.014,11.8,0.500,0.500,0.169,0.171,93.93,91.36,76.13,66.0,0.046
109310,21200976,2013-03-15,1610612742,2012-13,DAL,Dallas,2229.0,Mike James,G,NaN,21.200000,83.7,86.0,84.7,81.8,-1.0,4.2,0.308,2.00,30.8,0.042,0.042,0.042,15.4,0.500,0.500,0.184,0.183,98.17,98.49,82.08,43.0,0.086
109666,21200990,2013-03-17,1610612742,2012-13,DAL,Dallas,2229.0,Mike James,G,NaN,32.383333,101.8,97.0,112.4,112.3,-10.6,-15.3,0.211,2.00,22.2,0.033,0.071,0.052,11.1,0.545,0.589,0.192,0.200,95.43,97.83,81.52,67.0,0.077
109820,21200996,2013-03-18,1610612742,2012-13,DAL,Dallas,2229.0,Mike James,G,NaN,23.516667,126.5,125.5,109.2,108.5,17.3,17.0,0.158,0.75,25.0,0.000,0.111,0.054,33.3,0.900,0.900,0.180,0.181,95.28,95.93,79.94,47.0,0.088
110303,21201015,2013-03-20,1610612742,2012-13,DAL,Dallas,2229.0,Mike James,G,NaN,26.900000,117.6,120.8,120.4,128.0,-2.8,-7.2,0.333,7.00,31.8,0.043,0.077,0.061,4.5,0.429,0.429,0.278,0.276,91.45,87.46,72.88,48.0,0.053
110651,21201029,2013-03-22,1610612742,2012-13,DAL,Dallas,2229.0,Mike James,G,NaN,24.600000,109.3,105.9,121.3,116.7,-12.0,-10.8,0.316,6.00,40.0,0.000,0.091,0.043,6.7,0.357,0.444,0.158,0.162,93.25,96.61,80.51,51.0,0.078
111058,21201045,2013-03-24,1610612742,2012-13,DAL,Dallas,2229.0,Mike James,G,NaN,32.066667,124.0,122.2,120.5,120.0,3.4,2.2,0.294,1.67,26.3,0.043,0.067,0.057,15.8,0.850,0.873,0.206,0.209,94.94,95.81,79.84,63.0,0.136
111339,21201056,2013-03-26,1610612742,2012-13,DAL,Dallas,2229.0,Mike James,G,NaN,27.450000,110.9,111.8,99.7,100.0,11.2,11.8,0.333,6.00,40.0,0.000,0.148,0.085,6.7,0.625,0.625,0.164,0.165,89.67,89.18,74.32,51.0,0.096
111762,21201072,2013-03-28,1610612742,2012-13,DAL,Dallas,2229.0,Mike James,G,NaN,19.500000,78.3,75.7,136.6,131.6,-58.3,-55.9,0.333,4.00,44.4,0.000,0.000,0.000,11.1,0.000,0.000,0.125,0.129,89.04,92.28,76.90,37.0,-0.063
112085,21201085,2013-03-30,1610612742,2012-13,DAL,Dallas,2229.0,Mike James,G,NaN,30.750000,108.8,108.8,119.2,122.8,-10.4,-14.0,0.304,3.50,38.9,0.000,0.040,0.020,11.1,0.250,0.282,0.177,0.183,90.29,88.98,74.15,57.0,0.008
112738,21201110,2013-04-02,1610612742,2012-13,DAL,Dallas,2229.0,Mike James,G,NaN,20.650000,82.1,82.1,89.6,92.3,-7.5,-10.3,0.267,4.00,50.0,0.000,0.074,0.041,12.5,0.000,0.000,0.091,0.093,92.05,90.65,75.54,39.0,0.047
113096,21201124,2013-04-04,1610612742,2012-13,DAL,Dallas,2229.0,Mike James,G,NaN,24.966667,111.2,113.0,99.7,100.0,11.5,13.0,0.238,1.67,33.3,0.000,0.125,0.083,20.0,0.429,0.429,0.200,0.205,90.30,89.41,74.51,46.0,0.057
113364,21201135,2013-04-05,1610612742,2012-13,DAL,Dallas,2229.0,Mike James,G,NaN,18.300000,133.0,128.9,100.4,97.4,32.6,31.5,0.125,0.00,33.3,0.000,0.000,0.000,0.0,1.000,1.031,0.098,0.100,97.94,100.98,84.15,38.0,0.096
113826,21201153,2013-04-07,1610612742,2012-13,DAL,Dallas,2229.0,Mike James,G,NaN,24.966667,93.5,90.2,106.1,108.2,-12.6,-18.0,0.211,0.00,50.0,0.000,0.087,0.037,0.0,0.250,0.250,0.065,0.068,95.35,96.15,80.13,51.0,0.044
114235,21201169,2013-04-10,1610612742,2012-13,DAL,Dallas,2229.0,Mike James,G,NaN,27.116667,96.2,96.2,108.8,107.5,-12.6,-11.4,0.200,1.50,27.3,0.000,0.148,0.067,18.2,0.750,0.750,0.127,0.129,92.37,92.93,77.44,52.0,0.089
114654,21201185,2013-04-12,1610612742,2012-13,DAL,Dallas,2229.0,Mike James,G,NaN,34.333333,101.5,104.4,90.3,91.2,11.2,13.2,0.192,2.50,33.3,0.000,0.077,0.042,13.3,0.429,0.444,0.132,0.133,96.89,95.07,79.22,68.0,0.049
114995,21201199,2013-04-14,1610612742,2012-13,DAL,Dallas,2229.0,Mike James,G,NaN,18.583333,109.1,109.1,116.4,115.2,-7.3,-6.1,0.214,3.00,30.0,0.000,0.087,0.049,10.0,0.333,0.333,0.184,0.189,84.77,85.24,71.03,33.0,0.041

In [21]:
df_5bsa0918[df_5bsa0918.PLAYER_NAME.str.contains(playerl[1])][['PLAYER_ID', 'PLAYER_NAME']].value_counts('PLAYER_ID')

PLAYER_ID
2229.0       134
1628455.0     47
dtype: int64

In [22]:
#different players
df_5bsa0918[df_5bsa0918.PLAYER_NAME.str.contains(playerl[2])]

,game_id,game_date,team_id,season,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
115945,21300007,2013-10-30,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,NaN,0.316667,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,1.000,1.000,0.0,0.0,0.000,0.000,0.000,77.01,154.01,128.34,1.0,0.000
116436,21300026,2013-11-01,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
116835,21300041,2013-11-03,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
117146,21300053,2013-11-05,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
117791,21300078,2013-11-08,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
118473,21300105,2013-11-11,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
118573,21300109,2013-11-12,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,NaN,12.716667,100.1,96.4,123.2,119.2,-23.1,-22.8,0.111,0.0,25.0,0.133,0.143,0.136,0.0,0.5,0.521,0.094,0.097,98.37,101.91,84.93,28.0,0.053
119257,21300135,2013-11-15,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
119616,21300149,2013-11-17,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,NaN,0.816667,0.0,0.0,227.3,100.0,-227.3,-100.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,83.95,116.60,97.17,2.0,0.000
119809,21300157,2013-11-19,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
120055,21300166,2013-11-20,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
120403,21300180,2013-11-22,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
120853,21300197,2013-11-24,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,NaN,0.416667,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,56.69,113.39,94.49,1.0,0.000
121034,21300204,2013-11-25,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,NaN,2.266667,150.0,120.0,126.1,120.0,23.9,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,1.0,1.000,0.167,0.200,92.75,105.88,88.24,5.0,0.160
121439,21300220,2013-11-27,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,NaN,2.083333,103.1,100.0,66.7,50.0,36.4,50.0,0.000,0.0,0.0,0.500,0.000,0.500,0.0,0.0,0.000,0.167,0.170,79.26,92.16,76.80,4.0,-0.250
121764,21300233,2013-11-29,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
122209,21300250,2013-12-01,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,NaN,2.583333,0.0,0.0,51.5,40.0,-51.5,-40.0,0.000,0.0,0.0,0.000,0.333,0.111,0.0,0.0,0.000,0.000,0.000,82.50,92.90,77.42,5.0,-3.000
122567,21300264,2013-12-03,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
122760,21300272,2013-12-04,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
123284,21300292,2013-12-07,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
123476,21300300,2013-12-08,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,NaN,3.516667,71.4,83.3,33.3,33.3,38.1,50.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.125,0.143,88.72,81.90,68.25,6.0,-0.286
123860,21300315,2013-12-10,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,NaN,9.566667,80.5,78.9,96.2,95.0,-15.7,-16.1,0.000,0.0,0.0,0.273,0.091,0.182,50.0,1.5,1.064,0.174,0.177,96.33,97.84,81.53,19.0,0.238
124079,21300323,2013-12-11,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
124361,21300334,2013-12-13,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
124912,21300356,2013-12-16,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
125349,21300373,2013-12-18,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
125695,21300386,2013-12-20,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
125941,21300396,2013-12-21,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,NaN,2.566667,134.6,116.7,85.0,100.0,49.6,16.7,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.568,0.286,0.323,103.61,102.86,85.71,6.0,0.000
131025,21300595,2014-01-18,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
131334,21300607,2014-01-20,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
131870,21300628,2014-01-22,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
132165,21300639,2014-01-24,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
132672,21300659,2014-01-26,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,NaN,0.783333,200.0,200.0,0.0,0.0,200.0,200.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,61.54,92.31,76.92,1.0,0.000
132925,21300669,2014-01-28,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,NaN,5.600000,92.2,75.0,159.0,163.6,-66.8,-88.6,0.000,0.0,0.0,0.167,0.250,0.200,0.0,0.0,1.136,0.143,0.170,90.34,98.57,82.14,12.0,0.234
133116,21300677,2014-04-08,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
136103,21300795,2014-02-18,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
136270,21300801,2014-02-19,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,NaN,1.216667,100.0,100.0,0.0,0.0,100.0,100.0,0.000,0.0,0.0,0.500,0.000,0.333,0.0,0.0,0.000,0.333,0.333,59.18,78.90,65.75,2.0,-0.500
137720,21300859,2014-02-26,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,NaN,0.766667,150.0,150.0,0.0,0.0,150.0,150.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,93.71,124.95,104.12,2.0,0.000
138153,21300876,2014-03-01,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
138556,21300892,2014-03-03,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
138987,21300909,2014-03-05,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
139025,21300910,2014-03-05,1610612749,2013-14,MIL,Milwaukee,203183.0,Tony Mitchell,NaN,NaN,3.450000,170.1,166.7,80.0,66.7,90.1,100.0,0.000,0.0,0.0,0.333,0.000,0.143,0.0,0.5,0.500,0.250,0.254,75.69,83.48,69.57,6.0,0.120
139319,21300922,2014-03-07,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
139345,21300923,2014-03-07,1610612749,2013-14,MIL,Milwaukee,203183.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
139547,21300931,2014-03-08,1610612749,2013-14,MIL,Milwaukee,203183.0,Tony Mitchell,NaN,NaN,4.533333,67.6,66.7,189.6,200.0,-122.0,-133.3,0.500,0.0,50.0,0.000,0.000,0.000,0.0,0.0,0.000,0.100,0.101,91.69,90.00,75.00,9.0,0.049
139701,21300937,2014-03-09,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
139967,21300947,2014-03-10,1610612749,2013-14,MIL,Milwaukee,203183.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
140055,21300951,2014-03-11,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
140131,21300954,2014-03-11,1610612749,2013-14,MIL,Milwaukee,203183.0,Tony Mitchell,NaN,NaN,1.766667,208.3,200.0,0.0,0.0,208.3,200.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,1.0,1.000,0.667,0.694,79.88,95.09,79.25,3.0,0.571
140284,21300960,2014-03-12,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,NaN,0.450000,208.3,300.0,113.6,50.0,94.7,250.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,123.73,160.00,133.33,1.0,0.000
140525,21300969,2014-03-13,1610612749,2013-14,MIL,Milwaukee,203183.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
140909,21300984,2014-03-15,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
141678,21301015,2014-03-19,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
142034,21301029,2014-03-21,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
142288,21301039,2014-03-22,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
142696,21301055,2014-03-24,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,NaN,1.783333,208.3,150.0,66.7,66.7,141.7,83.3,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,1.136,0.200,0.258,79.13,94.21,78.50,4.0,0.267
142926,21301064,2014-03-26,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
143323,21301079,2014-03-28,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,NaN,4.733333,62.5,62.5,60.1,55.6,2.4,6.9,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,82.75,86.20,71.83,8.0,0.000
143510,21301087,2014-03-29,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,NaN,5.766667,131.6,130.0,100.0,90.9,31.6,39.1,0.250,1.0,33.3,0.250,0.200,0.222,33.3,1.0,1.000,0.182,0.184,82.74,87.40,72.83,10.0,0.067
143942,21301104,2014-03-31,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
144197,21301114,2014-04-02,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
144704,21301134,2014-04-04,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
145006,21301146,2014-04-05,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
145425,21301162,2014-04-09,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,NaN,8.383333,99.6,117.6,76.5,76.5,23.1,41.2,0.000,0.0,0.0,0.167,0.444,0.286,0.0,0.0,0.174,0.130,0.130,106.15,97.34,81.11,17.0,0.167
145895,21301181,2014-04-11,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
146336,21301198,2014-04-13,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,NaN,6.683333,127.8,128.6,147.1,157.1,-19.2,-28.6,0.000,0.0,0.0,0.300,0.000,0.250,33.3,0.5,0.410,0.150,0.149,104.21,100.47,83.73,14.0,-0.048
146885,21301220,2014-04-16,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,NaN,6.100000,120.8,118.2,82.7,75.0,38.1,43.2,0.000,0.0,0.0,0.000,0.143,0.077,0.0,0.0,0.000,0.083,0.085,85.14,90.49,75.41,11.0,0.069
147441,21400011,2014-10-29,1610612765,2014-15,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
147583,21400017,2014-10-30,1610612765,2014-15,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
147996,21400033,2014-11-01,1610612765,2014-15,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
148718,21400061,2014-11-05,1610612765,2014-15,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
149120,21400076,2014-11-07,1610612765,2014-15,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
149507,21400091,2014-11-09,1610612765,2014-15,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
149766,21400101,2014-11-10,1610612765,2014-15,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
149974,21400109,2014-11-12,1610612765,2014-15,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
150488,21400129,2014-11-14,1610612765,2014-15,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
150669,21400136,2014-11-15,1610612765,2014-15,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
151020,21400150,2014-11-17,1610612765,2014-15,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
151420,21400165,2014-11-19,1610612765,2014-15,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
151637,21400174,2014-11-21,1610612765,2014-15,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
152495,21400207,2014-11-25,1610612765,2014-15,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
159200,21400469,2014-12-30,1610612756,2014-15,PHX,Phoenix,203502.0,Tony Mitchell,NaN,NWT - Not With Team,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000

In [23]:
#two different players
df_5bsa0918[df_5bsa0918.PLAYER_NAME.str.contains(playerl[3])]

,game_id,game_date,team_id,season,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
59799,21100032,2011-12-28,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
60423,21100056,2011-12-31,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,NaN,6.266667,100.9,100.0,129.9,133.3,-28.9,-33.3,0.000,0.0,0.0,0.286,0.500,0.333,33.3,0.000,0.000,0.176,0.189,96.51,95.74,79.79,13.0,-0.019
60672,21100066,2012-01-02,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
61773,21100109,2012-01-06,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,NaN,4.150000,130.8,128.6,125.6,137.5,5.2,-8.9,0.333,0.0,50.0,0.000,0.333,0.167,0.0,0.000,1.136,0.125,0.127,90.45,86.75,72.29,7.0,0.143
62619,21100142,2012-01-10,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,NaN,0.416667,200.0,200.0,100.0,100.0,100.0,100.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,1.000,1.000,1.000,1.000,172.80,172.80,144.00,1.0,0.400
63034,21100158,2012-01-12,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
63366,21100171,2012-01-14,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,NaN,4.666667,45.7,44.4,152.3,120.0,-106.6,-75.6,0.000,0.0,0.0,0.000,0.000,0.000,50.0,0.000,0.568,0.222,0.228,85.58,97.71,81.43,9.0,-0.190
63639,21100181,2012-01-15,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,NaN,0.566667,0.0,0.0,300.0,300.0,-300.0,-300.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,85.46,128.19,106.83,2.0,0.000
64016,21100196,2012-01-17,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
64286,21100206,2012-01-18,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
68560,21100372,2012-02-07,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
68893,21100385,2012-02-09,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,NaN,3.266667,52.4,44.4,171.7,177.8,-119.3,-133.3,0.000,0.0,0.0,0.000,0.500,0.167,0.0,0.000,0.000,0.000,0.000,124.60,132.24,110.20,9.0,0.057
69587,21100412,2012-02-12,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,NaN,0.500000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,47.68,95.36,79.47,1.0,0.000
69757,21100419,2012-02-13,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
70308,21100440,2012-02-15,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
70641,21100453,2012-02-17,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,NaN,7.533333,86.4,87.5,70.3,64.7,16.1,22.8,0.000,0.0,0.0,0.000,0.000,0.000,50.0,1.000,1.000,0.095,0.094,101.44,105.13,87.61,16.0,-0.059
70767,21100458,2012-02-18,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
71333,21100480,2012-02-20,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
71743,21100496,2012-02-22,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
71946,21100504,2012-02-28,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,NaN,12.800000,106.2,104.3,67.8,76.0,38.4,28.3,0.000,0.0,0.0,0.188,0.167,0.176,0.0,0.400,0.557,0.286,0.290,94.97,90.02,75.02,23.0,0.955
72258,21100516,2012-02-29,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
72665,21100532,2012-03-02,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,NaN,2.750000,80.0,80.0,200.0,166.7,-120.0,-86.7,0.000,0.0,0.0,0.000,0.000,0.000,0.0,1.000,1.000,0.200,0.200,87.06,95.77,79.81,5.0,0.143
73066,21100548,2012-03-04,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,NaN,0.083333,0.0,0.0,113.6,100.0,-113.6,-100.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,264.00,300.00,250.00,0.0,1.000
73247,21100555,2012-03-05,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,NaN,1.966667,103.1,80.0,77.3,75.0,25.8,5.0,0.000,0.0,0.0,0.000,0.500,0.200,0.0,1.000,1.064,0.333,0.410,94.70,109.83,91.53,5.0,1.111
73918,21100581,2012-03-07,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,NaN,6.283333,126.4,127.3,120.8,100.0,5.5,27.3,0.000,0.0,0.0,0.143,0.333,0.231,0.0,0.000,0.000,0.000,0.000,83.42,91.67,76.39,11.0,0.114
74471,21100602,2012-03-10,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,NaN,5.550000,99.4,92.9,73.3,71.4,26.1,21.4,0.250,1.0,33.3,0.000,0.143,0.077,33.3,0.000,1.136,0.133,0.142,115.55,121.08,100.90,14.0,0.158
74680,21100610,2012-03-11,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
75064,21100625,2012-03-13,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,NaN,2.900000,147.1,116.7,121.5,116.7,25.5,0.0,0.000,0.0,0.0,0.000,0.250,0.200,0.0,0.000,1.136,0.167,0.210,87.06,99.31,82.76,6.0,0.313
75374,21100637,2012-03-14,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
75776,21100653,2012-03-16,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,NaN,9.283333,105.8,100.0,129.5,136.8,-23.7,-36.8,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.000,0.568,0.045,0.048,98.40,98.29,81.91,19.0,-0.027
75970,21100661,2012-03-17,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
76340,21100675,2012-03-19,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
76671,21100688,2012-03-21,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
76874,21100696,2012-03-22,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,NaN,10.700000,75.1,73.9,88.8,90.9,-13.7,-17.0,0.333,0.0,12.5,0.091,0.000,0.038,0.0,0.500,0.581,0.269,0.284,101.29,100.93,84.11,23.0,0.190
79693,21100806,2012-04-04,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
80146,21100824,2012-04-06,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
80415,21100834,2012-04-07,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,NaN,2.700000,77.3,60.0,82.0,100.0,-4.6,-40.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.167,0.205,77.87,80.00,66.67,5.0,-2.000
80801,21100849,2012-04-09,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,NaN,8.183333,80.6,85.0,124.2,115.0,-43.5,-30.0,0.000,0.0,0.0,0.000,0.250,0.056,20.0,0.333,0.515,0.208,0.208,116.14,117.31,97.76,20.0,0.031
82422,21100912,2012-04-16,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,NaN,16.450000,112.3,110.8,87.0,89.2,25.2,21.6,0.000,0.0,0.0,0.238,0.100,0.171,20.0,0.000,0.000,0.114,0.115,108.61,107.96,89.97,37.0,0.000
82901,21100931,2012-04-18,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,NaN,4.316667,116.5,110.0,22.5,20.0,94.0,90.0,0.000,0.0,0.0,0.167,0.333,0.250,0.0,0.000,0.000,0.083,0.087,101.86,111.20,92.66,10.0,0.176
83133,21100940,2012-04-20,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,NaN,1.466667,103.1,100.0,0.0,0.0,103.1,100.0,0.000,0.0,0.0,0.000,1.000,0.500,0.0,0.000,0.266,0.500,0.515,112.58,130.91,109.09,4.0,0.000
83345,21100948,2012-04-21,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
83589,21100957,2012-04-22,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
83923,21100970,2012-04-24,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,NaN,26.716667,91.9,97.8,103.4,102.2,-11.5,-4.4,0.063,1.0,14.3,0.192,0.087,0.143,14.3,0.500,0.512,0.102,0.105,83.92,81.73,68.11,46.0,0.085
84418,21100990,2012-04-26,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,F,NaN,46.316667,102.8,105.3,107.9,107.4,-5.1,-2.1,0.000,0.0,0.0,0.023,0.130,0.082,6.3,0.786,0.793,0.155,0.153,98.39,97.42,81.18,94.0,0.143
109089,21200967,2013-03-14,1610612742,2012-13,DAL,Dallas,203203.0,Chris Wright,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
109317,21200976,2013-03-15,1610612742,2012-13,DAL,Dallas,203203.0,Chris Wright,NaN,NaN,0.683333,100.0,66.7,200.0,200.0,-100.0,-133.3,0.000,0.0,0.0,0.000,0.000,0.000,0.0,1.000,1.000,0.333,0.500,140.15,175.18,145.99,3.0,0.250
109674,21200990,2013-03-17,1610612742,2012-13,DAL,Dallas,203203.0,Chris Wright,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
109827,21200996,2013-03-18,1610612742,2012-13,DAL,Dallas,203203.0,Chris Wright,NaN,NaN,2.816667,58.1,50.0,123.0,128.6,-64.8,-78.6,0.000,0.0,0.0,0.000,0.000,0.000,50.0,0.000,0.000,0.222,0.291,120.99,127.81,106.51,8.0,-0.308
110309,21201015,2013-03-20,1610612742,2012-13,DAL,Dallas,203203.0,Chris Wright,NaN,NaN,0.866667,0.0,0.0,69.4,50.0,-69.4,-50.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,94.53,109.92,91.60,2.0,0.000
110659,21201029,2013-03-22,1610612742,2012-13,DAL,Dallas,203203.0,Chris Wright,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
140831,21300981,2014-03-15,1610612749,2013-14,MIL,Milwaukee,202874.0,Chris Wright,NaN,NaN,6.600000,102.5,107.1,135.5,120.0,-33.1,-12.9,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.000,0.399,0.235,0.240,101.53,105.45,87.88,14.0,0.000
140984,21300987,2014-03-16,1610612749,2013-14,MIL,Milwaukee,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
141427,21301005,2014-03-18,1610612749,2013-14,MIL,Milwaukee,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
141835,21301021,2014-03-20,1610612749,2013-14,MIL,Milwaukee,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,0.00,0.00,0.0,0.000
142401,21301043,2014-03-23,1610612749,2013-14,MIL,Milwaukee,202874.0,Chris Wright,NaN,NaN,26.116667,129.5,133.3,113.6,116.4,15.9,17.0,0.115,0.0,33.3,0.105,0.071,0.085,0.0,0.800,0.712,0.103,0.102,102.89,100.17,83.47,54.0,0.083
145052,21301148,2014-04-05,1610612749,2013-14,MIL,Milwaukee,202874.0,Chris Wright,NaN,NaN,15.983333,129.9,128.6,118.6,116.7,11.3,11.9,0.000,0.0,0.0,0.154,0.111,0.129,0.0,1.000,0.532,0.118,0.122,85.96,87.10,72.58,28.0,0.102
145563,21301168,2014-04-09,1610612749,2013-14,MIL,Milwaukee,202874.0,Chris Wright,NaN,NaN,14.733333,91.4,93.3,109.0,109.7,-17.6,-16.3,0.000,0.0,0.0,0.125,0.000,0.069,33.3,0.500,0.500,0.158,0.159,100.77,99.40,82.83,30.0,0.000
146007,21301185,2014-04-11,1610612749,2013-14,MIL,Milwaukee,202874.0,Chris Wright,NaN,NaN,16.583333,109.9,102.6,107.8,105.1,2.1,-2.5,0.143,1.0,9.1,0.067,0.150,0.114,9.1,0.778,0.778,0.250,0.267,106.40,111.44,92.86,38.0,0.210
146145,21301191,2014-04-12,1610612749,2013-14,MIL,Milwaukee,202874.0,Chris Wright,NaN,NaN,17.483333,89.2,82.4,93.1,97.1,-3.9,-14.8,0.125,1.0,16.7,0.067,0.000,0.027,16.7,0.333,0.515,0.132,0.141,93.25,94.74,78.95,34.0,-0.011
146502,21301205,2014-04-14,1610612749,2013-14,MIL,Milwaukee,202874.0,Chris Wright,NaN,NaN,10.483333,109.1,115.0,154.8,147.8,-45.7,-32.8,0.000,0.0,0.0,0.000,0.000,0.000,25.0,0.667,0.515,0.190,0.181,98.53,98.44,82.03,20.0,-0.041
146808,21301217,2014-04-16,1610612749,2013-14,MIL,Milwaukee,202874.0,Chris Wright,NaN,NaN,17.533333,90.3,88.6,109.0,108.8,-18.6,-20.3,0.000,0.0,0.0,0.125,0.231,0.172,0.0,0.429,0.429,0.175,0.183,93.46,94.45,78.71,35.0,0.100

In [24]:
datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)

datapath_df = os.path.join(datapath, 'A12bsa_game_id_team_id_player_id_2009_2018.csv')
if not os.path.exists(datapath_df):
    df_5bsa0918.to_csv(datapath_df, index=False)

In [25]:
df = pd.read_csv(os.path.join('..', 'processed_data', 'A12bsa_game_id_team_id_player_id_2009_2018.csv'))
print(df.shape)
p(df)

(291642, 33)
(291642, 33)

,game_id,game_date,team_id,season,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
0,20900001,2009-10-27,1610612739,2009-10,CLE,Cleveland,2544.0,LeBron James,F,NaN,44.916667,99.8,101.2,99.2,101.2,0.5,0.0,0.471,1.60,19.5,0.000,0.100,0.049,12.2,0.636,0.685,0.351,0.354,93.44,91.90,76.59,86.0,0.240
1,20900001,2009-10-27,1610612739,2009-10,CLE,Cleveland,2760.0,Anderson Varejao,F,NaN,32.833333,109.3,108.2,115.5,116.1,-6.1,-7.9,0.050,0.00,8.3,0.179,0.091,0.140,0.0,0.333,0.418,0.167,0.168,89.69,89.89,74.91,61.0,0.040
2,20900001,2009-10-27,1610612739,2009-10,CLE,Cleveland,406.0,Shaquille O'Neal,C,NaN,28.800000,98.5,96.4,95.5,96.2,3.0,0.1,0.083,1.00,7.1,0.000,0.385,0.200,7.1,0.455,0.421,0.213,0.221,89.33,89.99,75.00,55.0,0.121
3,20900001,2009-10-27,1610612739,2009-10,CLE,Cleveland,1515.0,Anthony Parker,G,NaN,40.166667,108.0,107.8,101.4,103.9,6.6,3.9,0.160,1.33,23.5,0.000,0.083,0.042,17.6,0.444,0.506,0.153,0.157,93.10,92.03,76.69,77.0,0.076
4,20900001,2009-10-27,1610612739,2009-10,CLE,Cleveland,2590.0,Mo Williams,G,NaN,35.033333,98.9,92.8,109.1,107.2,-10.2,-14.5,0.167,1.50,18.8,0.000,0.000,0.000,12.5,0.375,0.564,0.176,0.187,90.74,94.53,78.77,69.0,0.044
291637,41700404,2018-06-08,1610612744,2017-18,GSW,Golden State,201156.0,Nick Young,NaN,NaN,8.983333,131.9,133.3,98.8,106.3,33.0,27.1,0.000,0.00,0.0,0.000,0.067,0.042,0.0,0.375,0.375,0.190,0.198,94.66,90.92,75.77,18.0,0.000
291638,41700404,2018-06-08,1610612744,2017-18,GSW,Golden State,2561.0,David West,NaN,NaN,7.600000,97.6,92.9,128.7,135.7,-31.1,-42.9,0.333,0.00,50.0,0.000,0.000,0.000,0.0,1.000,1.000,0.071,0.075,88.67,88.42,73.68,14.0,0.039
291639,41700404,2018-06-08,1610612744,2017-18,GSW,Golden State,1626172.0,Kevon Looney,NaN,NaN,2.783333,68.0,66.7,100.0,120.0,-32.0,-53.3,0.000,0.00,0.0,0.250,0.000,0.125,0.0,0.500,0.500,0.222,0.254,102.44,94.85,79.04,6.0,0.214
291640,41700404,2018-06-08,1610612744,2017-18,GSW,Golden State,2585.0,Zaza Pachulia,NaN,NaN,2.783333,68.0,66.7,100.0,120.0,-32.0,-53.3,0.000,0.00,0.0,0.000,0.250,0.125,33.3,0.000,0.532,0.333,0.381,102.44,94.85,79.04,6.0,0.143
291641,41700404,2018-06-08,1610612744,2017-18,GSW,Golden State,1627775.0,Patrick McCaw,NaN,NaN,2.783333,68.0,66.7,100.0,120.0,-32.0,-53.3,0.000,0.00,0.0,0.250,0.000,0.125,0.0,0.000,0.000,0.000,0.000,102.44,94.85,79.04,6.0,0.071